class AirportExecutor{
public static void main(String[] args){
Airport refOne = new Airport();

System.out.println("The airportId is: " + refOne.airportId);
System.out.println("The airportName is: " + refOne.airportName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfTerminals is: " + refOne.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refOne.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refOne.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refOne.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refOne.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refOne.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refOne.hasLounges);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasCarRental is: " + refOne.hasCarRental);
System.out.println("The hasHotelNearby is: " + refOne.hasHotelNearby);
System.out.println("The airportCode is: " + refOne.airportCode);
System.out.println("The authorityName is: " + refOne.authorityName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The annualPassengers is: " + refOne.annualPassengers);
System.out.println("The airportType is: " + refOne.airportType);

refOne.airportId = 1;
refOne.airportName = "Kempegowda International Airport";
refOne.location = "Devanahalli";
refOne.city = "Bengaluru";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfTerminals = 2;
refOne.numberOfRunways = 2;
refOne.hasInternationalFlights = true;
refOne.hasDomesticFlights = true;
refOne.hasCargoFacility = true;
refOne.hasDutyFreeShops = true;
refOne.hasLounges = true;
refOne.hasWifi = true;
refOne.hasParking = true;
refOne.hasCarRental = true;
refOne.hasHotelNearby = true;
refOne.airportCode = "BLR";
refOne.authorityName = "Bangalore International Airport Limited";
refOne.establishedYear = 2008;
refOne.contactNumber = "+91 80 6675 0000";
refOne.email = "info@blrairport.com";
refOne.website = "https://www.bengaluruairport.com";
refOne.annualPassengers = 35000000;
refOne.airportType = "International";

System.out.println("The airportId is: " + refOne.airportId);
System.out.println("The airportName is: " + refOne.airportName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfTerminals is: " + refOne.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refOne.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refOne.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refOne.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refOne.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refOne.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refOne.hasLounges);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasCarRental is: " + refOne.hasCarRental);
System.out.println("The hasHotelNearby is: " + refOne.hasHotelNearby);
System.out.println("The airportCode is: " + refOne.airportCode);
System.out.println("The authorityName is: " + refOne.authorityName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The annualPassengers is: " + refOne.annualPassengers);
System.out.println("The airportType is: " + refOne.airportType);
Airport refTwo = new Airport();

System.out.println("The airportId is: " + refTwo.airportId);
System.out.println("The airportName is: " + refTwo.airportName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfTerminals is: " + refTwo.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refTwo.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refTwo.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refTwo.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refTwo.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refTwo.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refTwo.hasLounges);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasCarRental is: " + refTwo.hasCarRental);
System.out.println("The hasHotelNearby is: " + refTwo.hasHotelNearby);
System.out.println("The airportCode is: " + refTwo.airportCode);
System.out.println("The authorityName is: " + refTwo.authorityName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The annualPassengers is: " + refTwo.annualPassengers);
System.out.println("The airportType is: " + refTwo.airportType);

refTwo.airportId = 2;
refTwo.airportName = "Indira Gandhi International Airport";
refTwo.location = "Palam";
refTwo.city = "New Delhi";
refTwo.state = "Delhi";
refTwo.country = "India";
refTwo.numberOfTerminals = 3;
refTwo.numberOfRunways = 3;
refTwo.hasInternationalFlights = true;
refTwo.hasDomesticFlights = true;
refTwo.hasCargoFacility = true;
refTwo.hasDutyFreeShops = true;
refTwo.hasLounges = true;
refTwo.hasWifi = true;
refTwo.hasParking = true;
refTwo.hasCarRental = true;
refTwo.hasHotelNearby = true;
refTwo.airportCode = "DEL";
refTwo.authorityName = "Delhi International Airport Limited";
refTwo.establishedYear = 1962;
refTwo.contactNumber = "+91 11 2567 1234";
refTwo.email = "info@delairport.com";
refTwo.website = "https://www.newdelhiairport.in";
refTwo.annualPassengers = 68000000;
refTwo.airportType = "International";

System.out.println("The airportId is: " + refTwo.airportId);
System.out.println("The airportName is: " + refTwo.airportName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfTerminals is: " + refTwo.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refTwo.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refTwo.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refTwo.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refTwo.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refTwo.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refTwo.hasLounges);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasCarRental is: " + refTwo.hasCarRental);
System.out.println("The hasHotelNearby is: " + refTwo.hasHotelNearby);
System.out.println("The airportCode is: " + refTwo.airportCode);
System.out.println("The authorityName is: " + refTwo.authorityName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The annualPassengers is: " + refTwo.annualPassengers);
System.out.println("The airportType is: " + refTwo.airportType);
Airport refThree = new Airport();

System.out.println("The airportId is: " + refThree.airportId);
System.out.println("The airportName is: " + refThree.airportName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfTerminals is: " + refThree.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refThree.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refThree.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refThree.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refThree.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refThree.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refThree.hasLounges);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasCarRental is: " + refThree.hasCarRental);
System.out.println("The hasHotelNearby is: " + refThree.hasHotelNearby);
System.out.println("The airportCode is: " + refThree.airportCode);
System.out.println("The authorityName is: " + refThree.authorityName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The annualPassengers is: " + refThree.annualPassengers);
System.out.println("The airportType is: " + refThree.airportType);

refThree.airportId = 3;
refThree.airportName = "Chhatrapati Shivaji Maharaj International Airport";
refThree.location = "Santacruz";
refThree.city = "Mumbai";
refThree.state = "Maharashtra";
refThree.country = "India";
refThree.numberOfTerminals = 2;
refThree.numberOfRunways = 2;
refThree.hasInternationalFlights = true;
refThree.hasDomesticFlights = true;
refThree.hasCargoFacility = true;
refThree.hasDutyFreeShops = true;
refThree.hasLounges = true;
refThree.hasWifi = true;
refThree.hasParking = true;
refThree.hasCarRental = true;
refThree.hasHotelNearby = true;
refThree.airportCode = "BOM";
refThree.authorityName = "Mumbai International Airport Limited";
refThree.establishedYear = 1942;
refThree.contactNumber = "+91 22 6689 1234";
refThree.email = "info@csmairport.com";
refThree.website = "https://www.csmairport.in";
refThree.annualPassengers = 50000000;
refThree.airportType = "International";

System.out.println("The airportId is: " + refThree.airportId);
System.out.println("The airportName is: " + refThree.airportName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfTerminals is: " + refThree.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refThree.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refThree.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refThree.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refThree.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refThree.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refThree.hasLounges);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasCarRental is: " + refThree.hasCarRental);
System.out.println("The hasHotelNearby is: " + refThree.hasHotelNearby);
System.out.println("The airportCode is: " + refThree.airportCode);
System.out.println("The authorityName is: " + refThree.authorityName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The annualPassengers is: " + refThree.annualPassengers);
System.out.println("The airportType is: " + refThree.airportType);
Airport refFour = new Airport();

System.out.println("The airportId is: " + refFour.airportId);
System.out.println("The airportName is: " + refFour.airportName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfTerminals is: " + refFour.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refFour.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refFour.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refFour.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refFour.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refFour.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refFour.hasLounges);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasCarRental is: " + refFour.hasCarRental);
System.out.println("The hasHotelNearby is: " + refFour.hasHotelNearby);
System.out.println("The airportCode is: " + refFour.airportCode);
System.out.println("The authorityName is: " + refFour.authorityName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The annualPassengers is: " + refFour.annualPassengers);
System.out.println("The airportType is: " + refFour.airportType);

refFour.airportId = 4;
refFour.airportName = "Rajiv Gandhi International Airport";
refFour.location = "Shamshabad";
refFour.city = "Hyderabad";
refFour.state = "Telangana";
refFour.country = "India";
refFour.numberOfTerminals = 1;
refFour.numberOfRunways = 2;
refFour.hasInternationalFlights = true;
refFour.hasDomesticFlights = true;
refFour.hasCargoFacility = true;
refFour.hasDutyFreeShops = true;
refFour.hasLounges = true;
refFour.hasWifi = true;
refFour.hasParking = true;
refFour.hasCarRental = true;
refFour.hasHotelNearby = true;
refFour.airportCode = "HYD";
refFour.authorityName = "GMR Hyderabad International Airport Limited";
refFour.establishedYear = 2008;
refFour.contactNumber = "+91 40 6654 0000";
refFour.email = "info@hydairport.com";
refFour.website = "https://www.hyderabad.aero";
refFour.annualPassengers = 21000000;
refFour.airportType = "International";

System.out.println("The airportId is: " + refFour.airportId);
System.out.println("The airportName is: " + refFour.airportName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfTerminals is: " + refFour.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refFour.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refFour.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refFour.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refFour.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refFour.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refFour.hasLounges);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasCarRental is: " + refFour.hasCarRental);
System.out.println("The hasHotelNearby is: " + refFour.hasHotelNearby);
System.out.println("The airportCode is: " + refFour.airportCode);
System.out.println("The authorityName is: " + refFour.authorityName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The annualPassengers is: " + refFour.annualPassengers);
System.out.println("The airportType is: " + refFour.airportType);
Airport refFive = new Airport();

System.out.println("The airportId is: " + refFive.airportId);
System.out.println("The airportName is: " + refFive.airportName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfTerminals is: " + refFive.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refFive.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refFive.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refFive.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refFive.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refFive.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refFive.hasLounges);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The hasParking is: " + refFive.hasParking);
System.out.println("The hasCarRental is: " + refFive.hasCarRental);
System.out.println("The hasHotelNearby is: " + refFive.hasHotelNearby);
System.out.println("The airportCode is: " + refFive.airportCode);
System.out.println("The authorityName is: " + refFive.authorityName);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The annualPassengers is: " + refFive.annualPassengers);
System.out.println("The airportType is: " + refFive.airportType);

refFive.airportId = 5;
refFive.airportName = "Cochin International Airport";
refFive.location = "Nedumbassery";
refFive.city = "Kochi";
refFive.state = "Kerala";
refFive.country = "India";
refFive.numberOfTerminals = 1;
refFive.numberOfRunways = 2;
refFive.hasInternationalFlights = true;
refFive.hasDomesticFlights = true;
refFive.hasCargoFacility = true;
refFive.hasDutyFreeShops = true;
refFive.hasLounges = true;
refFive.hasWifi = true;
refFive.hasParking = true;
refFive.hasCarRental = true;
refFive.hasHotelNearby = true;
refFive.airportCode = "COK";
refFive.authorityName = "Cochin International Airport Limited";
refFive.establishedYear = 1999;
refFive.contactNumber = "+91 484 2540 000";
refFive.email = "info@cochinairport.com";
refFive.website = "https://www.cochin-airport.in";
refFive.annualPassengers = 7000000;
refFive.airportType = "International";

System.out.println("The airportId is: " + refFive.airportId);
System.out.println("The airportName is: " + refFive.airportName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfTerminals is: " + refFive.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refFive.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refFive.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refFive.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refFive.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refFive.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refFive.hasLounges);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The hasParking is: " + refFive.hasParking);
System.out.println("The hasCarRental is: " + refFive.hasCarRental);
System.out.println("The hasHotelNearby is: " + refFive.hasHotelNearby);
System.out.println("The airportCode is: " + refFive.airportCode);
System.out.println("The authorityName is: " + refFive.authorityName);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The annualPassengers is: " + refFive.annualPassengers);
System.out.println("The airportType is: " + refFive.airportType);
Airport refSix = new Airport();

System.out.println("The airportId is: " + refSix.airportId);
System.out.println("The airportName is: " + refSix.airportName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfTerminals is: " + refSix.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refSix.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refSix.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refSix.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refSix.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refSix.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refSix.hasLounges);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasCarRental is: " + refSix.hasCarRental);
System.out.println("The hasHotelNearby is: " + refSix.hasHotelNearby);
System.out.println("The airportCode is: " + refSix.airportCode);
System.out.println("The authorityName is: " + refSix.authorityName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The annualPassengers is: " + refSix.annualPassengers);
System.out.println("The airportType is: " + refSix.airportType);

refSix.airportId = 6;
refSix.airportName = "Dabolim Airport";
refSix.location = "Dabolim";
refSix.city = "Goa";
refSix.state = "Goa";
refSix.country = "India";
refSix.numberOfTerminals = 1;
refSix.numberOfRunways = 1;
refSix.hasInternationalFlights = true;
refSix.hasDomesticFlights = true;
refSix.hasCargoFacility = false;
refSix.hasDutyFreeShops = true;
refSix.hasLounges = true;
refSix.hasWifi = true;
refSix.hasParking = true;
refSix.hasCarRental = true;
refSix.hasHotelNearby = true;
refSix.airportCode = "GOI";
refSix.authorityName = "Directorate General of Civil Aviation";
refSix.establishedYear = 1955;
refSix.contactNumber = "+91 832 251 0000";
refSix.email = "info@goaairport.com";
refSix.website = "https://www.goanairport.com";
refSix.annualPassengers = 2500000;
refSix.airportType = "International";

System.out.println("The airportId is: " + refSix.airportId);
System.out.println("The airportName is: " + refSix.airportName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfTerminals is: " + refSix.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refSix.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refSix.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refSix.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refSix.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refSix.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refSix.hasLounges);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasCarRental is: " + refSix.hasCarRental);
System.out.println("The hasHotelNearby is: " + refSix.hasHotelNearby);
System.out.println("The airportCode is: " + refSix.airportCode);
System.out.println("The authorityName is: " + refSix.authorityName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The annualPassengers is: " + refSix.annualPassengers);
System.out.println("The airportType is: " + refSix.airportType);
Airport refSeven = new Airport();

System.out.println("The airportId is: " + refSeven.airportId);
System.out.println("The airportName is: " + refSeven.airportName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfTerminals is: " + refSeven.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refSeven.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refSeven.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refSeven.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refSeven.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refSeven.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refSeven.hasLounges);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasCarRental is: " + refSeven.hasCarRental);
System.out.println("The hasHotelNearby is: " + refSeven.hasHotelNearby);
System.out.println("The airportCode is: " + refSeven.airportCode);
System.out.println("The authorityName is: " + refSeven.authorityName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The annualPassengers is: " + refSeven.annualPassengers);
System.out.println("The airportType is: " + refSeven.airportType);

refSeven.airportId = 7;
refSeven.airportName = "Netaji Subhas Chandra Bose International Airport";
refSeven.location = "Dumdum";
refSeven.city = "Kolkata";
refSeven.state = "West Bengal";
refSeven.country = "India";
refSeven.numberOfTerminals = 2;
refSeven.numberOfRunways = 2;
refSeven.hasInternationalFlights = true;
refSeven.hasDomesticFlights = true;
refSeven.hasCargoFacility = true;
refSeven.hasDutyFreeShops = true;
refSeven.hasLounges = true;
refSeven.hasWifi = true;
refSeven.hasParking = true;
refSeven.hasCarRental = true;
refSeven.hasHotelNearby = true;
refSeven.airportCode = "CCU";
refSeven.authorityName = "Kolkata Airport Authority";
refSeven.establishedYear = 1924;
refSeven.contactNumber = "+91 33 2512 1234";
refSeven.email = "info@ccuairport.com";
refSeven.website = "https://www.kolkataairport.in";
refSeven.annualPassengers = 21000000;
refSeven.airportType = "International";

System.out.println("The airportId is: " + refSeven.airportId);
System.out.println("The airportName is: " + refSeven.airportName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfTerminals is: " + refSeven.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refSeven.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refSeven.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refSeven.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refSeven.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refSeven.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refSeven.hasLounges);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasCarRental is: " + refSeven.hasCarRental);
System.out.println("The hasHotelNearby is: " + refSeven.hasHotelNearby);
System.out.println("The airportCode is: " + refSeven.airportCode);
System.out.println("The authorityName is: " + refSeven.authorityName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The annualPassengers is: " + refSeven.annualPassengers);
System.out.println("The airportType is: " + refSeven.airportType);
Airport refEight = new Airport();

System.out.println("The airportId is: " + refEight.airportId);
System.out.println("The airportName is: " + refEight.airportName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfTerminals is: " + refEight.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refEight.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refEight.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refEight.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refEight.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refEight.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refEight.hasLounges);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasCarRental is: " + refEight.hasCarRental);
System.out.println("The hasHotelNearby is: " + refEight.hasHotelNearby);
System.out.println("The airportCode is: " + refEight.airportCode);
System.out.println("The authorityName is: " + refEight.authorityName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The annualPassengers is: " + refEight.annualPassengers);
System.out.println("The airportType is: " + refEight.airportType);

refEight.airportId = 8;
refEight.airportName = "Pune Airport";
refEight.location = "Lohegaon";
refEight.city = "Pune";
refEight.state = "Maharashtra";
refEight.country = "India";
refEight.numberOfTerminals = 1;
refEight.numberOfRunways = 2;
refEight.hasInternationalFlights = true;
refEight.hasDomesticFlights = true;
refEight.hasCargoFacility = false;
refEight.hasDutyFreeShops = true;
refEight.hasLounges = true;
refEight.hasWifi = true;
refEight.hasParking = true;
refEight.hasCarRental = true;
refEight.hasHotelNearby = true;
refEight.airportCode = "PNQ";
refEight.authorityName = "Airports Authority of India";
refEight.establishedYear = 1939;
refEight.contactNumber = "+91 20 2661 0000";
refEight.email = "info@puneairport.com";
refEight.website = "https://www.puneairport.com";
refEight.annualPassengers = 5600000;
refEight.airportType = "International";

System.out.println("The airportId is: " + refEight.airportId);
System.out.println("The airportName is: " + refEight.airportName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfTerminals is: " + refEight.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refEight.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refEight.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refEight.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refEight.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refEight.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refEight.hasLounges);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasCarRental is: " + refEight.hasCarRental);
System.out.println("The hasHotelNearby is: " + refEight.hasHotelNearby);
System.out.println("The airportCode is: " + refEight.airportCode);
System.out.println("The authorityName is: " + refEight.authorityName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The annualPassengers is: " + refEight.annualPassengers);
System.out.println("The airportType is: " + refEight.airportType);
Airport refNine = new Airport();

System.out.println("The airportId is: " + refNine.airportId);
System.out.println("The airportName is: " + refNine.airportName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfTerminals is: " + refNine.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refNine.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refNine.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refNine.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refNine.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refNine.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refNine.hasLounges);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasCarRental is: " + refNine.hasCarRental);
System.out.println("The hasHotelNearby is: " + refNine.hasHotelNearby);
System.out.println("The airportCode is: " + refNine.airportCode);
System.out.println("The authorityName is: " + refNine.authorityName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The annualPassengers is: " + refNine.annualPassengers);
System.out.println("The airportType is: " + refNine.airportType);

refNine.airportId = 9;
refNine.airportName = "Chandigarh International Airport";
refNine.location = "Chandigarh";
refNine.city = "Chandigarh";
refNine.state = "Chandigarh";
refNine.country = "India";
refNine.numberOfTerminals = 1;
refNine.numberOfRunways = 1;
refNine.hasInternationalFlights = true;
refNine.hasDomesticFlights = true;
refNine.hasCargoFacility = false;
refNine.hasDutyFreeShops = true;
refNine.hasLounges = true;
refNine.hasWifi = true;
refNine.hasParking = true;
refNine.hasCarRental = true;
refNine.hasHotelNearby = true;
refNine.airportCode = "IXC";
refNine.authorityName = "Airports Authority of India";
refNine.establishedYear = 2015;
refNine.contactNumber = "+91 172 267 0000";
refNine.email = "info@chandigarhairport.com";
refNine.website = "https://www.chandigarhairport.com";
refNine.annualPassengers = 1500000;
refNine.airportType = "International";

System.out.println("The airportId is: " + refNine.airportId);
System.out.println("The airportName is: " + refNine.airportName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfTerminals is: " + refNine.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refNine.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refNine.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refNine.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refNine.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refNine.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refNine.hasLounges);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasCarRental is: " + refNine.hasCarRental);
System.out.println("The hasHotelNearby is: " + refNine.hasHotelNearby);
System.out.println("The airportCode is: " + refNine.airportCode);
System.out.println("The authorityName is: " + refNine.authorityName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The annualPassengers is: " + refNine.annualPassengers);
System.out.println("The airportType is: " + refNine.airportType);
Airport refTen = new Airport();

System.out.println("The airportId is: " + refTen.airportId);
System.out.println("The airportName is: " + refTen.airportName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfTerminals is: " + refTen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refTen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refTen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refTen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refTen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refTen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refTen.hasLounges);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasCarRental is: " + refTen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refTen.hasHotelNearby);
System.out.println("The airportCode is: " + refTen.airportCode);
System.out.println("The authorityName is: " + refTen.authorityName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The annualPassengers is: " + refTen.annualPassengers);
System.out.println("The airportType is: " + refTen.airportType);

refTen.airportId = 10;
refTen.airportName = "Trivandrum International Airport";
refTen.location = "Chacka";
refTen.city = "Thiruvananthapuram";
refTen.state = "Kerala";
refTen.country = "India";
refTen.numberOfTerminals = 1;
refTen.numberOfRunways = 1;
refTen.hasInternationalFlights = true;
refTen.hasDomesticFlights = true;
refTen.hasCargoFacility = false;
refTen.hasDutyFreeShops = true;
refTen.hasLounges = true;
refTen.hasWifi = true;
refTen.hasParking = true;
refTen.hasCarRental = true;
refTen.hasHotelNearby = true;
refTen.airportCode = "TRV";
refTen.authorityName = "Airports Authority of India";
refTen.establishedYear = 1932;
refTen.contactNumber = "+91 471 250 0000";
refTen.email = "info@trivandrumairport.com";
refTen.website = "https://www.trivandrumairport.in";
refTen.annualPassengers = 3500000;
refTen.airportType = "International";

System.out.println("The airportId is: " + refTen.airportId);
System.out.println("The airportName is: " + refTen.airportName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfTerminals is: " + refTen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refTen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refTen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refTen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refTen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refTen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refTen.hasLounges);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasCarRental is: " + refTen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refTen.hasHotelNearby);
System.out.println("The airportCode is: " + refTen.airportCode);
System.out.println("The authorityName is: " + refTen.authorityName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The annualPassengers is: " + refTen.annualPassengers);
System.out.println("The airportType is: " + refTen.airportType);
Airport refEleven = new Airport();

System.out.println("The airportId is: " + refEleven.airportId);
System.out.println("The airportName is: " + refEleven.airportName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfTerminals is: " + refEleven.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refEleven.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refEleven.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refEleven.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refEleven.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refEleven.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refEleven.hasLounges);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasCarRental is: " + refEleven.hasCarRental);
System.out.println("The hasHotelNearby is: " + refEleven.hasHotelNearby);
System.out.println("The airportCode is: " + refEleven.airportCode);
System.out.println("The authorityName is: " + refEleven.authorityName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The annualPassengers is: " + refEleven.annualPassengers);
System.out.println("The airportType is: " + refEleven.airportType);

refEleven.airportId = 11;
refEleven.airportName = "Sardar Vallabhbhai Patel International Airport";
refEleven.location = "Ahmedabad";
refEleven.city = "Ahmedabad";
refEleven.state = "Gujarat";
refEleven.country = "India";
refEleven.numberOfTerminals = 2;
refEleven.numberOfRunways = 2;
refEleven.hasInternationalFlights = true;
refEleven.hasDomesticFlights = true;
refEleven.hasCargoFacility = true;
refEleven.hasDutyFreeShops = true;
refEleven.hasLounges = true;
refEleven.hasWifi = true;
refEleven.hasParking = true;
refEleven.hasCarRental = true;
refEleven.hasHotelNearby = true;
refEleven.airportCode = "AMD";
refEleven.authorityName = "Airports Authority of India";
refEleven.establishedYear = 1937;
refEleven.contactNumber = "+91 79 2550 1234";
refEleven.email = "info@ahmedabadairport.com";
refEleven.website = "https://www.aai.aero/amd";
refEleven.annualPassengers = 10000000;
refEleven.airportType = "International";

System.out.println("The airportId is: " + refEleven.airportId);
System.out.println("The airportName is: " + refEleven.airportName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfTerminals is: " + refEleven.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refEleven.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refEleven.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refEleven.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refEleven.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refEleven.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refEleven.hasLounges);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasCarRental is: " + refEleven.hasCarRental);
System.out.println("The hasHotelNearby is: " + refEleven.hasHotelNearby);
System.out.println("The airportCode is: " + refEleven.airportCode);
System.out.println("The authorityName is: " + refEleven.authorityName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The annualPassengers is: " + refEleven.annualPassengers);
System.out.println("The airportType is: " + refEleven.airportType);
Airport refTwelve = new Airport();

System.out.println("The airportId is: " + refTwelve.airportId);
System.out.println("The airportName is: " + refTwelve.airportName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfTerminals is: " + refTwelve.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refTwelve.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refTwelve.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refTwelve.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refTwelve.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refTwelve.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refTwelve.hasLounges);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasCarRental is: " + refTwelve.hasCarRental);
System.out.println("The hasHotelNearby is: " + refTwelve.hasHotelNearby);
System.out.println("The airportCode is: " + refTwelve.airportCode);
System.out.println("The authorityName is: " + refTwelve.authorityName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The annualPassengers is: " + refTwelve.annualPassengers);
System.out.println("The airportType is: " + refTwelve.airportType);

refTwelve.airportId = 12;
refTwelve.airportName = "Coimbatore International Airport";
refTwelve.location = "Peelamedu";
refTwelve.city = "Coimbatore";
refTwelve.state = "Tamil Nadu";
refTwelve.country = "India";
refTwelve.numberOfTerminals = 1;
refTwelve.numberOfRunways = 1;
refTwelve.hasInternationalFlights = true;
refTwelve.hasDomesticFlights = true;
refTwelve.hasCargoFacility = true;
refTwelve.hasDutyFreeShops = true;
refTwelve.hasLounges = true;
refTwelve.hasWifi = true;
refTwelve.hasParking = true;
refTwelve.hasCarRental = true;
refTwelve.hasHotelNearby = true;
refTwelve.airportCode = "CJB";
refTwelve.authorityName = "Airports Authority of India";
refTwelve.establishedYear = 1958;
refTwelve.contactNumber = "+91 422 259 0000";
refTwelve.email = "info@coimbatoreairport.com";
refTwelve.website = "https://www.aai.aero/cjb";
refTwelve.annualPassengers = 2200000;
refTwelve.airportType = "International";

System.out.println("The airportId is: " + refTwelve.airportId);
System.out.println("The airportName is: " + refTwelve.airportName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfTerminals is: " + refTwelve.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refTwelve.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refTwelve.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refTwelve.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refTwelve.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refTwelve.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refTwelve.hasLounges);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasCarRental is: " + refTwelve.hasCarRental);
System.out.println("The hasHotelNearby is: " + refTwelve.hasHotelNearby);
System.out.println("The airportCode is: " + refTwelve.airportCode);
System.out.println("The authorityName is: " + refTwelve.authorityName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The annualPassengers is: " + refTwelve.annualPassengers);
System.out.println("The airportType is: " + refTwelve.airportType);
Airport refThirteen = new Airport();

System.out.println("The airportId is: " + refThirteen.airportId);
System.out.println("The airportName is: " + refThirteen.airportName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfTerminals is: " + refThirteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refThirteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refThirteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refThirteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refThirteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refThirteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refThirteen.hasLounges);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasCarRental is: " + refThirteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refThirteen.hasHotelNearby);
System.out.println("The airportCode is: " + refThirteen.airportCode);
System.out.println("The authorityName is: " + refThirteen.authorityName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The annualPassengers is: " + refThirteen.annualPassengers);
System.out.println("The airportType is: " + refThirteen.airportType);

refThirteen.airportId = 13;
refThirteen.airportName = "Jaipur International Airport";
refThirteen.location = "Sanganeer";
refThirteen.city = "Jaipur";
refThirteen.state = "Rajasthan";
refThirteen.country = "India";
refThirteen.numberOfTerminals = 1;
refThirteen.numberOfRunways = 2;
refThirteen.hasInternationalFlights = true;
refThirteen.hasDomesticFlights = true;
refThirteen.hasCargoFacility = true;
refThirteen.hasDutyFreeShops = true;
refThirteen.hasLounges = true;
refThirteen.hasWifi = true;
refThirteen.hasParking = true;
refThirteen.hasCarRental = true;
refThirteen.hasHotelNearby = true;
refThirteen.airportCode = "JAI";
refThirteen.authorityName = "Airports Authority of India";
refThirteen.establishedYear = 2008;
refThirteen.contactNumber = "+91 141 225 0000";
refThirteen.email = "info@jaipurairport.com";
refThirteen.website = "https://www.jaipurairport.in";
refThirteen.annualPassengers = 4200000;
refThirteen.airportType = "International";

System.out.println("The airportId is: " + refThirteen.airportId);
System.out.println("The airportName is: " + refThirteen.airportName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfTerminals is: " + refThirteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refThirteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refThirteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refThirteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refThirteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refThirteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refThirteen.hasLounges);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasCarRental is: " + refThirteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refThirteen.hasHotelNearby);
System.out.println("The airportCode is: " + refThirteen.airportCode);
System.out.println("The authorityName is: " + refThirteen.authorityName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The annualPassengers is: " + refThirteen.annualPassengers);
System.out.println("The airportType is: " + refThirteen.airportType);
Airport refFourteen = new Airport();

System.out.println("The airportId is: " + refFourteen.airportId);
System.out.println("The airportName is: " + refFourteen.airportName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfTerminals is: " + refFourteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refFourteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refFourteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refFourteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refFourteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refFourteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refFourteen.hasLounges);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasCarRental is: " + refFourteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refFourteen.hasHotelNearby);
System.out.println("The airportCode is: " + refFourteen.airportCode);
System.out.println("The authorityName is: " + refFourteen.authorityName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The annualPassengers is: " + refFourteen.annualPassengers);
System.out.println("The airportType is: " + refFourteen.airportType);

refFourteen.airportId = 14;
refFourteen.airportName = "Surat Airport";
refFourteen.location = "Magdalla";
refFourteen.city = "Surat";
refFourteen.state = "Gujarat";
refFourteen.country = "India";
refFourteen.numberOfTerminals = 1;
refFourteen.numberOfRunways = 1;
refFourteen.hasInternationalFlights = true;
refFourteen.hasDomesticFlights = true;
refFourteen.hasCargoFacility = false;
refFourteen.hasDutyFreeShops = true;
refFourteen.hasLounges = true;
refFourteen.hasWifi = true;
refFourteen.hasParking = true;
refFourteen.hasCarRental = true;
refFourteen.hasHotelNearby = true;
refFourteen.airportCode = "STV";
refFourteen.authorityName = "Airports Authority of India";
refFourteen.establishedYear = 1972;
refFourteen.contactNumber = "+91 261 264 0000";
refFourteen.email = "info@suratairport.com";
refFourteen.website = "https://www.suratairport.in";
refFourteen.annualPassengers = 1200000;
refFourteen.airportType = "International";

System.out.println("The airportId is: " + refFourteen.airportId);
System.out.println("The airportName is: " + refFourteen.airportName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfTerminals is: " + refFourteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refFourteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refFourteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refFourteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refFourteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refFourteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refFourteen.hasLounges);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasCarRental is: " + refFourteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refFourteen.hasHotelNearby);
System.out.println("The airportCode is: " + refFourteen.airportCode);
System.out.println("The authorityName is: " + refFourteen.authorityName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The annualPassengers is: " + refFourteen.annualPassengers);
System.out.println("The airportType is: " + refFourteen.airportType);
Airport refFifteen = new Airport();

System.out.println("The airportId is: " + refFifteen.airportId);
System.out.println("The airportName is: " + refFifteen.airportName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfTerminals is: " + refFifteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refFifteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refFifteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refFifteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refFifteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refFifteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refFifteen.hasLounges);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasCarRental is: " + refFifteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refFifteen.hasHotelNearby);
System.out.println("The airportCode is: " + refFifteen.airportCode);
System.out.println("The authorityName is: " + refFifteen.authorityName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The annualPassengers is: " + refFifteen.annualPassengers);
System.out.println("The airportType is: " + refFifteen.airportType);

refFifteen.airportId = 15;
refFifteen.airportName = "Agra Airport";
refFifteen.location = "Kheria";
refFifteen.city = "Agra";
refFifteen.state = "Uttar Pradesh";
refFifteen.country = "India";
refFifteen.numberOfTerminals = 1;
refFifteen.numberOfRunways = 1;
refFifteen.hasInternationalFlights = false;
refFifteen.hasDomesticFlights = true;
refFifteen.hasCargoFacility = false;
refFifteen.hasDutyFreeShops = false;
refFifteen.hasLounges = false;
refFifteen.hasWifi = true;
refFifteen.hasParking = true;
refFifteen.hasCarRental = true;
refFifteen.hasHotelNearby = true;
refFifteen.airportCode = "AGR";
refFifteen.authorityName = "Airports Authority of India";
refFifteen.establishedYear = 1970;
refFifteen.contactNumber = "+91 562 252 0000";
refFifteen.email = "info@agraairport.com";
refFifteen.website = "https://www.agraairport.in";
refFifteen.annualPassengers = 400000;
refFifteen.airportType = "Domestic";

System.out.println("The airportId is: " + refFifteen.airportId);
System.out.println("The airportName is: " + refFifteen.airportName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfTerminals is: " + refFifteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refFifteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refFifteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refFifteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refFifteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refFifteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refFifteen.hasLounges);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasCarRental is: " + refFifteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refFifteen.hasHotelNearby);
System.out.println("The airportCode is: " + refFifteen.airportCode);
System.out.println("The authorityName is: " + refFifteen.authorityName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The annualPassengers is: " + refFifteen.annualPassengers);
System.out.println("The airportType is: " + refFifteen.airportType);
Airport refSixteen = new Airport();

System.out.println("The airportId is: " + refSixteen.airportId);
System.out.println("The airportName is: " + refSixteen.airportName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfTerminals is: " + refSixteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refSixteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refSixteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refSixteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refSixteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refSixteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refSixteen.hasLounges);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasCarRental is: " + refSixteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refSixteen.hasHotelNearby);
System.out.println("The airportCode is: " + refSixteen.airportCode);
System.out.println("The authorityName is: " + refSixteen.authorityName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The annualPassengers is: " + refSixteen.annualPassengers);
System.out.println("The airportType is: " + refSixteen.airportType);

refSixteen.airportId = 16;
refSixteen.airportName = "Lucknow Airport";
refSixteen.location = "Amausi";
refSixteen.city = "Lucknow";
refSixteen.state = "Uttar Pradesh";
refSixteen.country = "India";
refSixteen.numberOfTerminals = 1;
refSixteen.numberOfRunways = 1;
refSixteen.hasInternationalFlights = true;
refSixteen.hasDomesticFlights = true;
refSixteen.hasCargoFacility = false;
refSixteen.hasDutyFreeShops = true;
refSixteen.hasLounges = true;
refSixteen.hasWifi = true;
refSixteen.hasParking = true;
refSixteen.hasCarRental = true;
refSixteen.hasHotelNearby = true;
refSixteen.airportCode = "LKO";
refSixteen.authorityName = "Airports Authority of India";
refSixteen.establishedYear = 1986;
refSixteen.contactNumber = "+91 522 257 0000";
refSixteen.email = "info@lucknowairport.com";
refSixteen.website = "https://www.lkoairport.in";
refSixteen.annualPassengers = 2900000;
refSixteen.airportType = "International";

System.out.println("The airportId is: " + refSixteen.airportId);
System.out.println("The airportName is: " + refSixteen.airportName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfTerminals is: " + refSixteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refSixteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refSixteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refSixteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refSixteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refSixteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refSixteen.hasLounges);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasCarRental is: " + refSixteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refSixteen.hasHotelNearby);
System.out.println("The airportCode is: " + refSixteen.airportCode);
System.out.println("The authorityName is: " + refSixteen.authorityName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The annualPassengers is: " + refSixteen.annualPassengers);
System.out.println("The airportType is: " + refSixteen.airportType);
Airport refSeventeen = new Airport();

System.out.println("The airportId is: " + refSeventeen.airportId);
System.out.println("The airportName is: " + refSeventeen.airportName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfTerminals is: " + refSeventeen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refSeventeen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refSeventeen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refSeventeen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refSeventeen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refSeventeen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refSeventeen.hasLounges);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasCarRental is: " + refSeventeen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refSeventeen.hasHotelNearby);
System.out.println("The airportCode is: " + refSeventeen.airportCode);
System.out.println("The authorityName is: " + refSeventeen.authorityName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The annualPassengers is: " + refSeventeen.annualPassengers);
System.out.println("The airportType is: " + refSeventeen.airportType);

refSeventeen.airportId = 17;
refSeventeen.airportName = "Varanasi Airport";
refSeventeen.location = "Babatpur";
refSeventeen.city = "Varanasi";
refSeventeen.state = "Uttar Pradesh";
refSeventeen.country = "India";
refSeventeen.numberOfTerminals = 1;
refSeventeen.numberOfRunways = 1;
refSeventeen.hasInternationalFlights = true;
refSeventeen.hasDomesticFlights = true;
refSeventeen.hasCargoFacility = false;
refSeventeen.hasDutyFreeShops = true;
refSeventeen.hasLounges = true;
refSeventeen.hasWifi = true;
refSeventeen.hasParking = true;
refSeventeen.hasCarRental = true;
refSeventeen.hasHotelNearby = true;
refSeventeen.airportCode = "VNS";
refSeventeen.authorityName = "Airports Authority of India";
refSeventeen.establishedYear = 1937;
refSeventeen.contactNumber = "+91 542 256 0000";
refSeventeen.email = "info@varanasiairport.com";
refSeventeen.website = "https://www.varanasiairport.in";
refSeventeen.annualPassengers = 1300000;
refSeventeen.airportType = "International";

System.out.println("The airportId is: " + refSeventeen.airportId);
System.out.println("The airportName is: " + refSeventeen.airportName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfTerminals is: " + refSeventeen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refSeventeen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refSeventeen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refSeventeen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refSeventeen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refSeventeen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refSeventeen.hasLounges);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasCarRental is: " + refSeventeen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refSeventeen.hasHotelNearby);
System.out.println("The airportCode is: " + refSeventeen.airportCode);
System.out.println("The authorityName is: " + refSeventeen.authorityName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The annualPassengers is: " + refSeventeen.annualPassengers);
System.out.println("The airportType is: " + refSeventeen.airportType);
Airport refEighteen = new Airport();

System.out.println("The airportId is: " + refEighteen.airportId);
System.out.println("The airportName is: " + refEighteen.airportName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfTerminals is: " + refEighteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refEighteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refEighteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refEighteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refEighteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refEighteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refEighteen.hasLounges);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasCarRental is: " + refEighteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refEighteen.hasHotelNearby);
System.out.println("The airportCode is: " + refEighteen.airportCode);
System.out.println("The authorityName is: " + refEighteen.authorityName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The annualPassengers is: " + refEighteen.annualPassengers);
System.out.println("The airportType is: " + refEighteen.airportType);

refEighteen.airportId = 18;
refEighteen.airportName = "Bhubaneswar Airport";
refEighteen.location = "Biju Patnaik Airport";
refEighteen.city = "Bhubaneswar";
refEighteen.state = "Odisha";
refEighteen.country = "India";
refEighteen.numberOfTerminals = 1;
refEighteen.numberOfRunways = 1;
refEighteen.hasInternationalFlights = true;
refEighteen.hasDomesticFlights = true;
refEighteen.hasCargoFacility = true;
refEighteen.hasDutyFreeShops = true;
refEighteen.hasLounges = true;
refEighteen.hasWifi = true;
refEighteen.hasParking = true;
refEighteen.hasCarRental = true;
refEighteen.hasHotelNearby = true;
refEighteen.airportCode = "BBI";
refEighteen.authorityName = "Airports Authority of India";
refEighteen.establishedYear = 1942;
refEighteen.contactNumber = "+91 674 256 0000";
refEighteen.email = "info@bhubaneswarairport.com";
refEighteen.website = "https://www.bhubaneswarairport.in";
refEighteen.annualPassengers = 1700000;
refEighteen.airportType = "International";

System.out.println("The airportId is: " + refEighteen.airportId);
System.out.println("The airportName is: " + refEighteen.airportName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfTerminals is: " + refEighteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refEighteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refEighteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refEighteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refEighteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refEighteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refEighteen.hasLounges);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasCarRental is: " + refEighteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refEighteen.hasHotelNearby);
System.out.println("The airportCode is: " + refEighteen.airportCode);
System.out.println("The authorityName is: " + refEighteen.authorityName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The annualPassengers is: " + refEighteen.annualPassengers);
System.out.println("The airportType is: " + refEighteen.airportType);
Airport refNineteen = new Airport();

System.out.println("The airportId is: " + refNineteen.airportId);
System.out.println("The airportName is: " + refNineteen.airportName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfTerminals is: " + refNineteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refNineteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refNineteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refNineteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refNineteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refNineteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refNineteen.hasLounges);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasCarRental is: " + refNineteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refNineteen.hasHotelNearby);
System.out.println("The airportCode is: " + refNineteen.airportCode);
System.out.println("The authorityName is: " + refNineteen.authorityName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The annualPassengers is: " + refNineteen.annualPassengers);
System.out.println("The airportType is: " + refNineteen.airportType);

refNineteen.airportId = 19;
refNineteen.airportName = "Indore Airport";
refNineteen.location = "Devi Ahilyabai Holkar Airport";
refNineteen.city = "Indore";
refNineteen.state = "Madhya Pradesh";
refNineteen.country = "India";
refNineteen.numberOfTerminals = 1;
refNineteen.numberOfRunways = 1;
refNineteen.hasInternationalFlights = true;
refNineteen.hasDomesticFlights = true;
refNineteen.hasCargoFacility = true;
refNineteen.hasDutyFreeShops = true;
refNineteen.hasLounges = true;
refNineteen.hasWifi = true;
refNineteen.hasParking = true;
refNineteen.hasCarRental = true;
refNineteen.hasHotelNearby = true;
refNineteen.airportCode = "IDR";
refNineteen.authorityName = "Airports Authority of India";
refNineteen.establishedYear = 1950;
refNineteen.contactNumber = "+91 731 252 0000";
refNineteen.email = "info@indoreairport.com";
refNineteen.website = "https://www.indoreairport.in";
refNineteen.annualPassengers = 1400000;
refNineteen.airportType = "International";

System.out.println("The airportId is: " + refNineteen.airportId);
System.out.println("The airportName is: " + refNineteen.airportName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfTerminals is: " + refNineteen.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refNineteen.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refNineteen.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refNineteen.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refNineteen.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refNineteen.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refNineteen.hasLounges);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasCarRental is: " + refNineteen.hasCarRental);
System.out.println("The hasHotelNearby is: " + refNineteen.hasHotelNearby);
System.out.println("The airportCode is: " + refNineteen.airportCode);
System.out.println("The authorityName is: " + refNineteen.authorityName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The annualPassengers is: " + refNineteen.annualPassengers);
System.out.println("The airportType is: " + refNineteen.airportType);
Airport refTwenty = new Airport();

System.out.println("The airportId is: " + refTwenty.airportId);
System.out.println("The airportName is: " + refTwenty.airportName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfTerminals is: " + refTwenty.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refTwenty.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refTwenty.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refTwenty.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refTwenty.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refTwenty.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refTwenty.hasLounges);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasCarRental is: " + refTwenty.hasCarRental);
System.out.println("The hasHotelNearby is: " + refTwenty.hasHotelNearby);
System.out.println("The airportCode is: " + refTwenty.airportCode);
System.out.println("The authorityName is: " + refTwenty.authorityName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The annualPassengers is: " + refTwenty.annualPassengers);
System.out.println("The airportType is: " + refTwenty.airportType);

refTwenty.airportId = 20;
refTwenty.airportName = "Patna Airport";
refTwenty.location = "Jay Prakash Narayan Airport";
refTwenty.city = "Patna";
refTwenty.state = "Bihar";
refTwenty.country = "India";
refTwenty.numberOfTerminals = 1;
refTwenty.numberOfRunways = 1;
refTwenty.hasInternationalFlights = true;
refTwenty.hasDomesticFlights = true;
refTwenty.hasCargoFacility = false;
refTwenty.hasDutyFreeShops = true;
refTwenty.hasLounges = true;
refTwenty.hasWifi = true;
refTwenty.hasParking = true;
refTwenty.hasCarRental = true;
refTwenty.hasHotelNearby = true;
refTwenty.airportCode = "PAT";
refTwenty.authorityName = "Airports Authority of India";
refTwenty.establishedYear = 1962;
refTwenty.contactNumber = "+91 612 223 0000";
refTwenty.email = "info@patnaairport.com";
refTwenty.website = "https://www.patnaairport.in";
refTwenty.annualPassengers = 1200000;
refTwenty.airportType = "International";

System.out.println("The airportId is: " + refTwenty.airportId);
System.out.println("The airportName is: " + refTwenty.airportName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfTerminals is: " + refTwenty.numberOfTerminals);
System.out.println("The numberOfRunways is: " + refTwenty.numberOfRunways);
System.out.println("The hasInternationalFlights is: " + refTwenty.hasInternationalFlights);
System.out.println("The hasDomesticFlights is: " + refTwenty.hasDomesticFlights);
System.out.println("The hasCargoFacility is: " + refTwenty.hasCargoFacility);
System.out.println("The hasDutyFreeShops is: " + refTwenty.hasDutyFreeShops);
System.out.println("The hasLounges is: " + refTwenty.hasLounges);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasCarRental is: " + refTwenty.hasCarRental);
System.out.println("The hasHotelNearby is: " + refTwenty.hasHotelNearby);
System.out.println("The airportCode is: " + refTwenty.airportCode);
System.out.println("The authorityName is: " + refTwenty.authorityName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The annualPassengers is: " + refTwenty.annualPassengers);
System.out.println("The airportType is: " + refTwenty.airportType);
}
}