class BankExecutor{
public static void main(String[] args){
Bank refOne = new Bank();

System.out.println("The bankId is: " + refOne.bankId);
System.out.println("The bankName is: " + refOne.bankName);
System.out.println("The branchName is: " + refOne.branchName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The ifscCode is: " + refOne.ifscCode);
System.out.println("The managerName is: " + refOne.managerName);
System.out.println("The numberOfEmployees is: " + refOne.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refOne.numberOfCustomers);
System.out.println("The hasATM is: " + refOne.hasATM);
System.out.println("The hasLoanFacility is: " + refOne.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refOne.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refOne.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refOne.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refOne.numberOfATMs);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The bankType is: " + refOne.bankType);
System.out.println("The totalAssets is: " + refOne.totalAssets);
System.out.println("The headquarters is: " + refOne.headquarters);
System.out.println("The isGovernmentBank is: " + refOne.isGovernmentBank);


refOne.bankId = 1;
refOne.bankName = "State Bank of India";
refOne.branchName = "MG Road Branch";
refOne.location = "MG Road";
refOne.city = "Bangalore";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.ifscCode = "SBIN0001234";
refOne.managerName = "Ramesh Kumar";
refOne.numberOfEmployees = 45;
refOne.numberOfCustomers = 12000;
refOne.hasATM = true;
refOne.hasLoanFacility = true;
refOne.hasNetBanking = true;
refOne.hasMobileBanking = true;
refOne.hasLockerFacility = true;
refOne.numberOfATMs = 3;
refOne.contactNumber = "08023456789";
refOne.email = "mgr.sbi@sbi.co.in";
refOne.website = "www.sbi.co.in";
refOne.establishedYear = 1955;
refOne.bankType = "Public Sector";
refOne.totalAssets = 5200000000.75;
refOne.headquarters = "Mumbai";
refOne.isGovernmentBank = true;


System.out.println("The bankId is: " + refOne.bankId);
System.out.println("The bankName is: " + refOne.bankName);
System.out.println("The branchName is: " + refOne.branchName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The ifscCode is: " + refOne.ifscCode);
System.out.println("The managerName is: " + refOne.managerName);
System.out.println("The numberOfEmployees is: " + refOne.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refOne.numberOfCustomers);
System.out.println("The hasATM is: " + refOne.hasATM);
System.out.println("The hasLoanFacility is: " + refOne.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refOne.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refOne.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refOne.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refOne.numberOfATMs);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The bankType is: " + refOne.bankType);
System.out.println("The totalAssets is: " + refOne.totalAssets);
System.out.println("The headquarters is: " + refOne.headquarters);
System.out.println("The isGovernmentBank is: " + refOne.isGovernmentBank);
Bank refThree = new Bank();

System.out.println("The bankId is: " + refThree.bankId);
System.out.println("The bankName is: " + refThree.bankName);
System.out.println("The branchName is: " + refThree.branchName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The ifscCode is: " + refThree.ifscCode);
System.out.println("The managerName is: " + refThree.managerName);
System.out.println("The numberOfEmployees is: " + refThree.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refThree.numberOfCustomers);
System.out.println("The hasATM is: " + refThree.hasATM);
System.out.println("The hasLoanFacility is: " + refThree.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refThree.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refThree.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refThree.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refThree.numberOfATMs);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The bankType is: " + refThree.bankType);
System.out.println("The totalAssets is: " + refThree.totalAssets);
System.out.println("The headquarters is: " + refThree.headquarters);
System.out.println("The isGovernmentBank is: " + refThree.isGovernmentBank);


refThree.bankId = 3;
refThree.bankName = "ICICI Bank";
refThree.branchName = "Whitefield Branch";
refThree.location = "Whitefield";
refThree.city = "Bangalore";
refThree.state = "Karnataka";
refThree.country = "India";
refThree.ifscCode = "ICIC0003456";
refThree.managerName = "Anil Verma";
refThree.numberOfEmployees = 40;
refThree.numberOfCustomers = 10500;
refThree.hasATM = true;
refThree.hasLoanFacility = true;
refThree.hasNetBanking = true;
refThree.hasMobileBanking = true;
refThree.hasLockerFacility = true;
refThree.numberOfATMs = 3;
refThree.contactNumber = "08045678901";
refThree.email = "manager.whitefield@icicibank.com";
refThree.website = "www.icicibank.com";
refThree.establishedYear = 1994;
refThree.bankType = "Private Sector";
refThree.totalAssets = 3900000000.80;
refThree.headquarters = "Mumbai";
refThree.isGovernmentBank = false;


System.out.println("The bankId is: " + refThree.bankId);
System.out.println("The bankName is: " + refThree.bankName);
System.out.println("The branchName is: " + refThree.branchName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The ifscCode is: " + refThree.ifscCode);
System.out.println("The managerName is: " + refThree.managerName);
System.out.println("The numberOfEmployees is: " + refThree.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refThree.numberOfCustomers);
System.out.println("The hasATM is: " + refThree.hasATM);
System.out.println("The hasLoanFacility is: " + refThree.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refThree.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refThree.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refThree.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refThree.numberOfATMs);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The bankType is: " + refThree.bankType);
System.out.println("The totalAssets is: " + refThree.totalAssets);
System.out.println("The headquarters is: " + refThree.headquarters);
System.out.println("The isGovernmentBank is: " + refThree.isGovernmentBank);
Bank refFour = new Bank();

System.out.println("The bankId is: " + refFour.bankId);
System.out.println("The bankName is: " + refFour.bankName);
System.out.println("The branchName is: " + refFour.branchName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The ifscCode is: " + refFour.ifscCode);
System.out.println("The managerName is: " + refFour.managerName);
System.out.println("The numberOfEmployees is: " + refFour.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refFour.numberOfCustomers);
System.out.println("The hasATM is: " + refFour.hasATM);
System.out.println("The hasLoanFacility is: " + refFour.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refFour.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refFour.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refFour.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refFour.numberOfATMs);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The bankType is: " + refFour.bankType);
System.out.println("The totalAssets is: " + refFour.totalAssets);
System.out.println("The headquarters is: " + refFour.headquarters);
System.out.println("The isGovernmentBank is: " + refFour.isGovernmentBank);


refFour.bankId = 4;
refFour.bankName = "Axis Bank";
refFour.branchName = "BTM Branch";
refFour.location = "BTM Layout";
refFour.city = "Bangalore";
refFour.state = "Karnataka";
refFour.country = "India";
refFour.ifscCode = "UTIB0007890";
refFour.managerName = "Sanjay Mehta";
refFour.numberOfEmployees = 35;
refFour.numberOfCustomers = 8700;
refFour.hasATM = true;
refFour.hasLoanFacility = true;
refFour.hasNetBanking = true;
refFour.hasMobileBanking = true;
refFour.hasLockerFacility = false;
refFour.numberOfATMs = 2;
refFour.contactNumber = "08056789012";
refFour.email = "manager.btm@axisbank.com";
refFour.website = "www.axisbank.com";
refFour.establishedYear = 1993;
refFour.bankType = "Private Sector";
refFour.totalAssets = 3100000000.60;
refFour.headquarters = "Mumbai";
refFour.isGovernmentBank = false;


System.out.println("The bankId is: " + refFour.bankId);
System.out.println("The bankName is: " + refFour.bankName);
System.out.println("The branchName is: " + refFour.branchName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The ifscCode is: " + refFour.ifscCode);
System.out.println("The managerName is: " + refFour.managerName);
System.out.println("The numberOfEmployees is: " + refFour.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refFour.numberOfCustomers);
System.out.println("The hasATM is: " + refFour.hasATM);
System.out.println("The hasLoanFacility is: " + refFour.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refFour.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refFour.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refFour.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refFour.numberOfATMs);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The bankType is: " + refFour.bankType);
System.out.println("The totalAssets is: " + refFour.totalAssets);
System.out.println("The headquarters is: " + refFour.headquarters);
System.out.println("The isGovernmentBank is: " + refFour.isGovernmentBank);
Bank refFive = new Bank();

System.out.println("The bankId is: " + refFive.bankId);
System.out.println("The bankName is: " + refFive.bankName);
System.out.println("The branchName is: " + refFive.branchName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The ifscCode is: " + refFive.ifscCode);
System.out.println("The managerName is: " + refFive.managerName);
System.out.println("The numberOfEmployees is: " + refFive.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refFive.numberOfCustomers);
System.out.println("The hasATM is: " + refFive.hasATM);
System.out.println("The hasLoanFacility is: " + refFive.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refFive.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refFive.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refFive.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refFive.numberOfATMs);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The bankType is: " + refFive.bankType);
System.out.println("The totalAssets is: " + refFive.totalAssets);
System.out.println("The headquarters is: " + refFive.headquarters);
System.out.println("The isGovernmentBank is: " + refFive.isGovernmentBank);


refFive.bankId = 5;
refFive.bankName = "Canara Bank";
refFive.branchName = "Jayanagar Branch";
refFive.location = "Jayanagar";
refFive.city = "Bangalore";
refFive.state = "Karnataka";
refFive.country = "India";
refFive.ifscCode = "CNRB0002345";
refFive.managerName = "Lakshmi Narayan";
refFive.numberOfEmployees = 42;
refFive.numberOfCustomers = 11000;
refFive.hasATM = true;
refFive.hasLoanFacility = true;
refFive.hasNetBanking = true;
refFive.hasMobileBanking = true;
refFive.hasLockerFacility = true;
refFive.numberOfATMs = 4;
refFive.contactNumber = "08067890123";
refFive.email = "manager.jayanagar@canarabank.com";
refFive.website = "www.canarabank.com";
refFive.establishedYear = 1906;
refFive.bankType = "Public Sector";
refFive.totalAssets = 2800000000.45;
refFive.headquarters = "Bangalore";
refFive.isGovernmentBank = true;


System.out.println("The bankId is: " + refFive.bankId);
System.out.println("The bankName is: " + refFive.bankName);
System.out.println("The branchName is: " + refFive.branchName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The ifscCode is: " + refFive.ifscCode);
System.out.println("The managerName is: " + refFive.managerName);
System.out.println("The numberOfEmployees is: " + refFive.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refFive.numberOfCustomers);
System.out.println("The hasATM is: " + refFive.hasATM);
System.out.println("The hasLoanFacility is: " + refFive.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refFive.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refFive.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refFive.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refFive.numberOfATMs);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The bankType is: " + refFive.bankType);
System.out.println("The totalAssets is: " + refFive.totalAssets);
System.out.println("The headquarters is: " + refFive.headquarters);
System.out.println("The isGovernmentBank is: " + refFive.isGovernmentBank);
Bank refSix = new Bank();

System.out.println("The bankId is: " + refSix.bankId);
System.out.println("The bankName is: " + refSix.bankName);
System.out.println("The branchName is: " + refSix.branchName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The ifscCode is: " + refSix.ifscCode);
System.out.println("The managerName is: " + refSix.managerName);
System.out.println("The numberOfEmployees is: " + refSix.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refSix.numberOfCustomers);
System.out.println("The hasATM is: " + refSix.hasATM);
System.out.println("The hasLoanFacility is: " + refSix.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refSix.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refSix.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refSix.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refSix.numberOfATMs);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The bankType is: " + refSix.bankType);
System.out.println("The totalAssets is: " + refSix.totalAssets);
System.out.println("The headquarters is: " + refSix.headquarters);
System.out.println("The isGovernmentBank is: " + refSix.isGovernmentBank);


refSix.bankId = 6;
refSix.bankName = "Union Bank of India";
refSix.branchName = "Malleshwaram Branch";
refSix.location = "Malleshwaram";
refSix.city = "Bangalore";
refSix.state = "Karnataka";
refSix.country = "India";
refSix.ifscCode = "UBIN0004567";
refSix.managerName = "Karthik Reddy";
refSix.numberOfEmployees = 37;
refSix.numberOfCustomers = 9200;
refSix.hasATM = true;
refSix.hasLoanFacility = true;
refSix.hasNetBanking = true;
refSix.hasMobileBanking = true;
refSix.hasLockerFacility = false;
refSix.numberOfATMs = 2;
refSix.contactNumber = "08078901234";
refSix.email = "manager.malleshwaram@unionbank.com";
refSix.website = "www.unionbankofindia.co.in";
refSix.establishedYear = 1919;
refSix.bankType = "Public Sector";
refSix.totalAssets = 2600000000.35;
refSix.headquarters = "Mumbai";
refSix.isGovernmentBank = true;


System.out.println("The bankId is: " + refSix.bankId);
System.out.println("The bankName is: " + refSix.bankName);
System.out.println("The branchName is: " + refSix.branchName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The ifscCode is: " + refSix.ifscCode);
System.out.println("The managerName is: " + refSix.managerName);
System.out.println("The numberOfEmployees is: " + refSix.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refSix.numberOfCustomers);
System.out.println("The hasATM is: " + refSix.hasATM);
System.out.println("The hasLoanFacility is: " + refSix.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refSix.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refSix.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refSix.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refSix.numberOfATMs);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The bankType is: " + refSix.bankType);
System.out.println("The totalAssets is: " + refSix.totalAssets);
System.out.println("The headquarters is: " + refSix.headquarters);
System.out.println("The isGovernmentBank is: " + refSix.isGovernmentBank);
Bank refSeven = new Bank();

System.out.println("The bankId is: " + refSeven.bankId);
System.out.println("The bankName is: " + refSeven.bankName);
System.out.println("The branchName is: " + refSeven.branchName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The ifscCode is: " + refSeven.ifscCode);
System.out.println("The managerName is: " + refSeven.managerName);
System.out.println("The numberOfEmployees is: " + refSeven.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refSeven.numberOfCustomers);
System.out.println("The hasATM is: " + refSeven.hasATM);
System.out.println("The hasLoanFacility is: " + refSeven.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refSeven.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refSeven.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refSeven.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refSeven.numberOfATMs);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The bankType is: " + refSeven.bankType);
System.out.println("The totalAssets is: " + refSeven.totalAssets);
System.out.println("The headquarters is: " + refSeven.headquarters);
System.out.println("The isGovernmentBank is: " + refSeven.isGovernmentBank);


refSeven.bankId = 7;
refSeven.bankName = "Punjab National Bank";
refSeven.branchName = "Rajajinagar Branch";
refSeven.location = "Rajajinagar";
refSeven.city = "Bangalore";
refSeven.state = "Karnataka";
refSeven.country = "India";
refSeven.ifscCode = "PUNB0005678";
refSeven.managerName = "Arvind Singh";
refSeven.numberOfEmployees = 39;
refSeven.numberOfCustomers = 9500;
refSeven.hasATM = true;
refSeven.hasLoanFacility = true;
refSeven.hasNetBanking = true;
refSeven.hasMobileBanking = true;
refSeven.hasLockerFacility = true;
refSeven.numberOfATMs = 3;
refSeven.contactNumber = "08089012345";
refSeven.email = "manager.rajajinagar@pnb.co.in";
refSeven.website = "www.pnbindia.in";
refSeven.establishedYear = 1894;
refSeven.bankType = "Public Sector";
refSeven.totalAssets = 3000000000.75;
refSeven.headquarters = "New Delhi";
refSeven.isGovernmentBank = true;


System.out.println("The bankId is: " + refSeven.bankId);
System.out.println("The bankName is: " + refSeven.bankName);
System.out.println("The branchName is: " + refSeven.branchName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The ifscCode is: " + refSeven.ifscCode);
System.out.println("The managerName is: " + refSeven.managerName);
System.out.println("The numberOfEmployees is: " + refSeven.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refSeven.numberOfCustomers);
System.out.println("The hasATM is: " + refSeven.hasATM);
System.out.println("The hasLoanFacility is: " + refSeven.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refSeven.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refSeven.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refSeven.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refSeven.numberOfATMs);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The bankType is: " + refSeven.bankType);
System.out.println("The totalAssets is: " + refSeven.totalAssets);
System.out.println("The headquarters is: " + refSeven.headquarters);
System.out.println("The isGovernmentBank is: " + refSeven.isGovernmentBank);
Bank refEight = new Bank();

System.out.println("The bankId is: " + refEight.bankId);
System.out.println("The bankName is: " + refEight.bankName);
System.out.println("The branchName is: " + refEight.branchName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The ifscCode is: " + refEight.ifscCode);
System.out.println("The managerName is: " + refEight.managerName);
System.out.println("The numberOfEmployees is: " + refEight.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refEight.numberOfCustomers);
System.out.println("The hasATM is: " + refEight.hasATM);
System.out.println("The hasLoanFacility is: " + refEight.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refEight.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refEight.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refEight.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refEight.numberOfATMs);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The bankType is: " + refEight.bankType);
System.out.println("The totalAssets is: " + refEight.totalAssets);
System.out.println("The headquarters is: " + refEight.headquarters);
System.out.println("The isGovernmentBank is: " + refEight.isGovernmentBank);


refEight.bankId = 8;
refEight.bankName = "Bank of Baroda";
refEight.branchName = "Yelahanka Branch";
refEight.location = "Yelahanka";
refEight.city = "Bangalore";
refEight.state = "Karnataka";
refEight.country = "India";
refEight.ifscCode = "BARB0006789";
refEight.managerName = "Deepak Joshi";
refEight.numberOfEmployees = 36;
refEight.numberOfCustomers = 8700;
refEight.hasATM = true;
refEight.hasLoanFacility = true;
refEight.hasNetBanking = true;
refEight.hasMobileBanking = true;
refEight.hasLockerFacility = true;
refEight.numberOfATMs = 2;
refEight.contactNumber = "08090123456";
refEight.email = "manager.yelahanka@bankofbaroda.com";
refEight.website = "www.bankofbaroda.in";
refEight.establishedYear = 1908;
refEight.bankType = "Public Sector";
refEight.totalAssets = 2950000000.55;
refEight.headquarters = "Vadodara";
refEight.isGovernmentBank = true;


System.out.println("The bankId is: " + refEight.bankId);
System.out.println("The bankName is: " + refEight.bankName);
System.out.println("The branchName is: " + refEight.branchName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The ifscCode is: " + refEight.ifscCode);
System.out.println("The managerName is: " + refEight.managerName);
System.out.println("The numberOfEmployees is: " + refEight.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refEight.numberOfCustomers);
System.out.println("The hasATM is: " + refEight.hasATM);
System.out.println("The hasLoanFacility is: " + refEight.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refEight.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refEight.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refEight.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refEight.numberOfATMs);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The bankType is: " + refEight.bankType);
System.out.println("The totalAssets is: " + refEight.totalAssets);
System.out.println("The headquarters is: " + refEight.headquarters);
System.out.println("The isGovernmentBank is: " + refEight.isGovernmentBank);
Bank refNine = new Bank();

System.out.println("The bankId is: " + refNine.bankId);
System.out.println("The bankName is: " + refNine.bankName);
System.out.println("The branchName is: " + refNine.branchName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The ifscCode is: " + refNine.ifscCode);
System.out.println("The managerName is: " + refNine.managerName);
System.out.println("The numberOfEmployees is: " + refNine.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refNine.numberOfCustomers);
System.out.println("The hasATM is: " + refNine.hasATM);
System.out.println("The hasLoanFacility is: " + refNine.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refNine.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refNine.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refNine.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refNine.numberOfATMs);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The bankType is: " + refNine.bankType);
System.out.println("The totalAssets is: " + refNine.totalAssets);
System.out.println("The headquarters is: " + refNine.headquarters);
System.out.println("The isGovernmentBank is: " + refNine.isGovernmentBank);


refNine.bankId = 9;
refNine.bankName = "Kotak Mahindra Bank";
refNine.branchName = "Electronic City Branch";
refNine.location = "Electronic City";
refNine.city = "Bangalore";
refNine.state = "Karnataka";
refNine.country = "India";
refNine.ifscCode = "KKBK0003456";
refNine.managerName = "Rahul Khanna";
refNine.numberOfEmployees = 34;
refNine.numberOfCustomers = 7600;
refNine.hasATM = true;
refNine.hasLoanFacility = true;
refNine.hasNetBanking = true;
refNine.hasMobileBanking = true;
refNine.hasLockerFacility = false;
refNine.numberOfATMs = 2;
refNine.contactNumber = "08091234567";
refNine.email = "manager.ecity@kotak.com";
refNine.website = "www.kotak.com";
refNine.establishedYear = 2003;
refNine.bankType = "Private Sector";
refNine.totalAssets = 2500000000.40;
refNine.headquarters = "Mumbai";
refNine.isGovernmentBank = false;


System.out.println("The bankId is: " + refNine.bankId);
System.out.println("The bankName is: " + refNine.bankName);
System.out.println("The branchName is: " + refNine.branchName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The ifscCode is: " + refNine.ifscCode);
System.out.println("The managerName is: " + refNine.managerName);
System.out.println("The numberOfEmployees is: " + refNine.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refNine.numberOfCustomers);
System.out.println("The hasATM is: " + refNine.hasATM);
System.out.println("The hasLoanFacility is: " + refNine.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refNine.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refNine.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refNine.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refNine.numberOfATMs);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The bankType is: " + refNine.bankType);
System.out.println("The totalAssets is: " + refNine.totalAssets);
System.out.println("The headquarters is: " + refNine.headquarters);
System.out.println("The isGovernmentBank is: " + refNine.isGovernmentBank);
Bank refTen = new Bank();

System.out.println("The bankId is: " + refTen.bankId);
System.out.println("The bankName is: " + refTen.bankName);
System.out.println("The branchName is: " + refTen.branchName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The ifscCode is: " + refTen.ifscCode);
System.out.println("The managerName is: " + refTen.managerName);
System.out.println("The numberOfEmployees is: " + refTen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refTen.numberOfCustomers);
System.out.println("The hasATM is: " + refTen.hasATM);
System.out.println("The hasLoanFacility is: " + refTen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refTen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refTen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refTen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refTen.numberOfATMs);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The bankType is: " + refTen.bankType);
System.out.println("The totalAssets is: " + refTen.totalAssets);
System.out.println("The headquarters is: " + refTen.headquarters);
System.out.println("The isGovernmentBank is: " + refTen.isGovernmentBank);


refTen.bankId = 10;
refTen.bankName = "Indian Bank";
refTen.branchName = "Basavanagudi Branch";
refTen.location = "Basavanagudi";
refTen.city = "Bangalore";
refTen.state = "Karnataka";
refTen.country = "India";
refTen.ifscCode = "IDIB0004567";
refTen.managerName = "Suresh Babu";
refTen.numberOfEmployees = 33;
refTen.numberOfCustomers = 8400;
refTen.hasATM = true;
refTen.hasLoanFacility = true;
refTen.hasNetBanking = true;
refTen.hasMobileBanking = true;
refTen.hasLockerFacility = true;
refTen.numberOfATMs = 2;
refTen.contactNumber = "08092345678";
refTen.email = "manager.basavanagudi@indianbank.in";
refTen.website = "www.indianbank.in";
refTen.establishedYear = 1907;
refTen.bankType = "Public Sector";
refTen.totalAssets = 2400000000.25;
refTen.headquarters = "Chennai";
refTen.isGovernmentBank = true;


System.out.println("The bankId is: " + refTen.bankId);
System.out.println("The bankName is: " + refTen.bankName);
System.out.println("The branchName is: " + refTen.branchName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The ifscCode is: " + refTen.ifscCode);
System.out.println("The managerName is: " + refTen.managerName);
System.out.println("The numberOfEmployees is: " + refTen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refTen.numberOfCustomers);
System.out.println("The hasATM is: " + refTen.hasATM);
System.out.println("The hasLoanFacility is: " + refTen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refTen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refTen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refTen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refTen.numberOfATMs);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The bankType is: " + refTen.bankType);
System.out.println("The totalAssets is: " + refTen.totalAssets);
System.out.println("The headquarters is: " + refTen.headquarters);
System.out.println("The isGovernmentBank is: " + refTen.isGovernmentBank);
Bank refEleven = new Bank();

System.out.println("The bankId is: " + refEleven.bankId);
System.out.println("The bankName is: " + refEleven.bankName);
System.out.println("The branchName is: " + refEleven.branchName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The ifscCode is: " + refEleven.ifscCode);
System.out.println("The managerName is: " + refEleven.managerName);
System.out.println("The numberOfEmployees is: " + refEleven.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refEleven.numberOfCustomers);
System.out.println("The hasATM is: " + refEleven.hasATM);
System.out.println("The hasLoanFacility is: " + refEleven.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refEleven.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refEleven.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refEleven.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refEleven.numberOfATMs);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The bankType is: " + refEleven.bankType);
System.out.println("The totalAssets is: " + refEleven.totalAssets);
System.out.println("The headquarters is: " + refEleven.headquarters);
System.out.println("The isGovernmentBank is: " + refEleven.isGovernmentBank);


refEleven.bankId = 11;
refEleven.bankName = "UCO Bank";
refEleven.branchName = "Hebbal Branch";
refEleven.location = "Hebbal";
refEleven.city = "Bangalore";
refEleven.state = "Karnataka";
refEleven.country = "India";
refEleven.ifscCode = "UCBA0005678";
refEleven.managerName = "Manoj Kumar";
refEleven.numberOfEmployees = 28;
refEleven.numberOfCustomers = 6900;
refEleven.hasATM = true;
refEleven.hasLoanFacility = true;
refEleven.hasNetBanking = true;
refEleven.hasMobileBanking = true;
refEleven.hasLockerFacility = false;
refEleven.numberOfATMs = 1;
refEleven.contactNumber = "08093456789";
refEleven.email = "manager.hebbal@ucobank.co.in";
refEleven.website = "www.ucobank.com";
refEleven.establishedYear = 1943;
refEleven.bankType = "Public Sector";
refEleven.totalAssets = 2100000000.15;
refEleven.headquarters = "Kolkata";
refEleven.isGovernmentBank = true;


System.out.println("The bankId is: " + refEleven.bankId);
System.out.println("The bankName is: " + refEleven.bankName);
System.out.println("The branchName is: " + refEleven.branchName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The ifscCode is: " + refEleven.ifscCode);
System.out.println("The managerName is: " + refEleven.managerName);
System.out.println("The numberOfEmployees is: " + refEleven.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refEleven.numberOfCustomers);
System.out.println("The hasATM is: " + refEleven.hasATM);
System.out.println("The hasLoanFacility is: " + refEleven.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refEleven.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refEleven.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refEleven.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refEleven.numberOfATMs);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The bankType is: " + refEleven.bankType);
System.out.println("The totalAssets is: " + refEleven.totalAssets);
System.out.println("The headquarters is: " + refEleven.headquarters);
System.out.println("The isGovernmentBank is: " + refEleven.isGovernmentBank);
Bank refTwelve = new Bank();

System.out.println("The bankId is: " + refTwelve.bankId);
System.out.println("The bankName is: " + refTwelve.bankName);
System.out.println("The branchName is: " + refTwelve.branchName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The ifscCode is: " + refTwelve.ifscCode);
System.out.println("The managerName is: " + refTwelve.managerName);
System.out.println("The numberOfEmployees is: " + refTwelve.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refTwelve.numberOfCustomers);
System.out.println("The hasATM is: " + refTwelve.hasATM);
System.out.println("The hasLoanFacility is: " + refTwelve.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refTwelve.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refTwelve.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refTwelve.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refTwelve.numberOfATMs);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The bankType is: " + refTwelve.bankType);
System.out.println("The totalAssets is: " + refTwelve.totalAssets);
System.out.println("The headquarters is: " + refTwelve.headquarters);
System.out.println("The isGovernmentBank is: " + refTwelve.isGovernmentBank);


refTwelve.bankId = 12;
refTwelve.bankName = "Yes Bank";
refTwelve.branchName = "Koramangala Branch";
refTwelve.location = "Koramangala";
refTwelve.city = "Bangalore";
refTwelve.state = "Karnataka";
refTwelve.country = "India";
refTwelve.ifscCode = "YESB0001234";
refTwelve.managerName = "Ananya Kapoor";
refTwelve.numberOfEmployees = 30;
refTwelve.numberOfCustomers = 7200;
refTwelve.hasATM = true;
refTwelve.hasLoanFacility = true;
refTwelve.hasNetBanking = true;
refTwelve.hasMobileBanking = true;
refTwelve.hasLockerFacility = false;
refTwelve.numberOfATMs = 2;
refTwelve.contactNumber = "08094567890";
refTwelve.email = "manager.koramangala@yesbank.in";
refTwelve.website = "www.yesbank.in";
refTwelve.establishedYear = 2004;
refTwelve.bankType = "Private Sector";
refTwelve.totalAssets = 2000000000.50;
refTwelve.headquarters = "Mumbai";
refTwelve.isGovernmentBank = false;


System.out.println("The bankId is: " + refTwelve.bankId);
System.out.println("The bankName is: " + refTwelve.bankName);
System.out.println("The branchName is: " + refTwelve.branchName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The ifscCode is: " + refTwelve.ifscCode);
System.out.println("The managerName is: " + refTwelve.managerName);
System.out.println("The numberOfEmployees is: " + refTwelve.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refTwelve.numberOfCustomers);
System.out.println("The hasATM is: " + refTwelve.hasATM);
System.out.println("The hasLoanFacility is: " + refTwelve.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refTwelve.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refTwelve.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refTwelve.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refTwelve.numberOfATMs);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The bankType is: " + refTwelve.bankType);
System.out.println("The totalAssets is: " + refTwelve.totalAssets);
System.out.println("The headquarters is: " + refTwelve.headquarters);
System.out.println("The isGovernmentBank is: " + refTwelve.isGovernmentBank);
Bank refThirteen = new Bank();

System.out.println("The bankId is: " + refThirteen.bankId);
System.out.println("The bankName is: " + refThirteen.bankName);
System.out.println("The branchName is: " + refThirteen.branchName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The ifscCode is: " + refThirteen.ifscCode);
System.out.println("The managerName is: " + refThirteen.managerName);
System.out.println("The numberOfEmployees is: " + refThirteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refThirteen.numberOfCustomers);
System.out.println("The hasATM is: " + refThirteen.hasATM);
System.out.println("The hasLoanFacility is: " + refThirteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refThirteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refThirteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refThirteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refThirteen.numberOfATMs);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The bankType is: " + refThirteen.bankType);
System.out.println("The totalAssets is: " + refThirteen.totalAssets);
System.out.println("The headquarters is: " + refThirteen.headquarters);
System.out.println("The isGovernmentBank is: " + refThirteen.isGovernmentBank);


refThirteen.bankId = 13;
refThirteen.bankName = "Federal Bank";
refThirteen.branchName = "Marathahalli Branch";
refThirteen.location = "Marathahalli";
refThirteen.city = "Bangalore";
refThirteen.state = "Karnataka";
refThirteen.country = "India";
refThirteen.ifscCode = "FDRL0009876";
refThirteen.managerName = "Vijay Nair";
refThirteen.numberOfEmployees = 29;
refThirteen.numberOfCustomers = 6700;
refThirteen.hasATM = true;
refThirteen.hasLoanFacility = true;
refThirteen.hasNetBanking = true;
refThirteen.hasMobileBanking = true;
refThirteen.hasLockerFacility = false;
refThirteen.numberOfATMs = 1;
refThirteen.contactNumber = "08095678901";
refThirteen.email = "manager.marathahalli@federalbank.co.in";
refThirteen.website = "www.federalbank.co.in";
refThirteen.establishedYear = 1931;
refThirteen.bankType = "Private Sector";
refThirteen.totalAssets = 1850000000.65;
refThirteen.headquarters = "Aluva";
refThirteen.isGovernmentBank = false;


System.out.println("The bankId is: " + refThirteen.bankId);
System.out.println("The bankName is: " + refThirteen.bankName);
System.out.println("The branchName is: " + refThirteen.branchName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The ifscCode is: " + refThirteen.ifscCode);
System.out.println("The managerName is: " + refThirteen.managerName);
System.out.println("The numberOfEmployees is: " + refThirteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refThirteen.numberOfCustomers);
System.out.println("The hasATM is: " + refThirteen.hasATM);
System.out.println("The hasLoanFacility is: " + refThirteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refThirteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refThirteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refThirteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refThirteen.numberOfATMs);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The bankType is: " + refThirteen.bankType);
System.out.println("The totalAssets is: " + refThirteen.totalAssets);
System.out.println("The headquarters is: " + refThirteen.headquarters);
System.out.println("The isGovernmentBank is: " + refThirteen.isGovernmentBank);
Bank refFourteen = new Bank();

System.out.println("The bankId is: " + refFourteen.bankId);
System.out.println("The bankName is: " + refFourteen.bankName);
System.out.println("The branchName is: " + refFourteen.branchName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The ifscCode is: " + refFourteen.ifscCode);
System.out.println("The managerName is: " + refFourteen.managerName);
System.out.println("The numberOfEmployees is: " + refFourteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refFourteen.numberOfCustomers);
System.out.println("The hasATM is: " + refFourteen.hasATM);
System.out.println("The hasLoanFacility is: " + refFourteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refFourteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refFourteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refFourteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refFourteen.numberOfATMs);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The bankType is: " + refFourteen.bankType);
System.out.println("The totalAssets is: " + refFourteen.totalAssets);
System.out.println("The headquarters is: " + refFourteen.headquarters);
System.out.println("The isGovernmentBank is: " + refFourteen.isGovernmentBank);


refFourteen.bankId = 14;
refFourteen.bankName = "South Indian Bank";
refFourteen.branchName = "HSR Layout Branch";
refFourteen.location = "HSR Layout";
refFourteen.city = "Bangalore";
refFourteen.state = "Karnataka";
refFourteen.country = "India";
refFourteen.ifscCode = "SIBL0003456";
refFourteen.managerName = "Joseph Mathew";
refFourteen.numberOfEmployees = 27;
refFourteen.numberOfCustomers = 6400;
refFourteen.hasATM = true;
refFourteen.hasLoanFacility = true;
refFourteen.hasNetBanking = true;
refFourteen.hasMobileBanking = true;
refFourteen.hasLockerFacility = false;
refFourteen.numberOfATMs = 1;
refFourteen.contactNumber = "08096789012";
refFourteen.email = "manager.hsr@southindianbank.com";
refFourteen.website = "www.southindianbank.com";
refFourteen.establishedYear = 1929;
refFourteen.bankType = "Private Sector";
refFourteen.totalAssets = 1700000000.45;
refFourteen.headquarters = "Thrissur";
refFourteen.isGovernmentBank = false;


System.out.println("The bankId is: " + refFourteen.bankId);
System.out.println("The bankName is: " + refFourteen.bankName);
System.out.println("The branchName is: " + refFourteen.branchName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The ifscCode is: " + refFourteen.ifscCode);
System.out.println("The managerName is: " + refFourteen.managerName);
System.out.println("The numberOfEmployees is: " + refFourteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refFourteen.numberOfCustomers);
System.out.println("The hasATM is: " + refFourteen.hasATM);
System.out.println("The hasLoanFacility is: " + refFourteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refFourteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refFourteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refFourteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refFourteen.numberOfATMs);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The bankType is: " + refFourteen.bankType);
System.out.println("The totalAssets is: " + refFourteen.totalAssets);
System.out.println("The headquarters is: " + refFourteen.headquarters);
System.out.println("The isGovernmentBank is: " + refFourteen.isGovernmentBank);
Bank refFifteen = new Bank();

System.out.println("The bankId is: " + refFifteen.bankId);
System.out.println("The bankName is: " + refFifteen.bankName);
System.out.println("The branchName is: " + refFifteen.branchName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The ifscCode is: " + refFifteen.ifscCode);
System.out.println("The managerName is: " + refFifteen.managerName);
System.out.println("The numberOfEmployees is: " + refFifteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refFifteen.numberOfCustomers);
System.out.println("The hasATM is: " + refFifteen.hasATM);
System.out.println("The hasLoanFacility is: " + refFifteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refFifteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refFifteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refFifteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refFifteen.numberOfATMs);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The bankType is: " + refFifteen.bankType);
System.out.println("The totalAssets is: " + refFifteen.totalAssets);
System.out.println("The headquarters is: " + refFifteen.headquarters);
System.out.println("The isGovernmentBank is: " + refFifteen.isGovernmentBank);


refFifteen.bankId = 15;
refFifteen.bankName = "Karur Vysya Bank";
refFifteen.branchName = "Banashankari Branch";
refFifteen.location = "Banashankari";
refFifteen.city = "Bangalore";
refFifteen.state = "Karnataka";
refFifteen.country = "India";
refFifteen.ifscCode = "KVBL0005678";
refFifteen.managerName = "Prakash Iyer";
refFifteen.numberOfEmployees = 26;
refFifteen.numberOfCustomers = 6000;
refFifteen.hasATM = true;
refFifteen.hasLoanFacility = true;
refFifteen.hasNetBanking = true;
refFifteen.hasMobileBanking = true;
refFifteen.hasLockerFacility = false;
refFifteen.numberOfATMs = 1;
refFifteen.contactNumber = "08097890123";
refFifteen.email = "manager.banashankari@kvb.co.in";
refFifteen.website = "www.kvb.co.in";
refFifteen.establishedYear = 1916;
refFifteen.bankType = "Private Sector";
refFifteen.totalAssets = 1500000000.30;
refFifteen.headquarters = "Karur";
refFifteen.isGovernmentBank = false;


System.out.println("The bankId is: " + refFifteen.bankId);
System.out.println("The bankName is: " + refFifteen.bankName);
System.out.println("The branchName is: " + refFifteen.branchName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The ifscCode is: " + refFifteen.ifscCode);
System.out.println("The managerName is: " + refFifteen.managerName);
System.out.println("The numberOfEmployees is: " + refFifteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refFifteen.numberOfCustomers);
System.out.println("The hasATM is: " + refFifteen.hasATM);
System.out.println("The hasLoanFacility is: " + refFifteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refFifteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refFifteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refFifteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refFifteen.numberOfATMs);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The bankType is: " + refFifteen.bankType);
System.out.println("The totalAssets is: " + refFifteen.totalAssets);
System.out.println("The headquarters is: " + refFifteen.headquarters);
System.out.println("The isGovernmentBank is: " + refFifteen.isGovernmentBank);
Bank refSixteen = new Bank();

System.out.println("The bankId is: " + refSixteen.bankId);
System.out.println("The bankName is: " + refSixteen.bankName);
System.out.println("The branchName is: " + refSixteen.branchName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The ifscCode is: " + refSixteen.ifscCode);
System.out.println("The managerName is: " + refSixteen.managerName);
System.out.println("The numberOfEmployees is: " + refSixteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refSixteen.numberOfCustomers);
System.out.println("The hasATM is: " + refSixteen.hasATM);
System.out.println("The hasLoanFacility is: " + refSixteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refSixteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refSixteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refSixteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refSixteen.numberOfATMs);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The bankType is: " + refSixteen.bankType);
System.out.println("The totalAssets is: " + refSixteen.totalAssets);
System.out.println("The headquarters is: " + refSixteen.headquarters);
System.out.println("The isGovernmentBank is: " + refSixteen.isGovernmentBank);


refSixteen.bankId = 16;
refSixteen.bankName = "IDBI Bank";
refSixteen.branchName = "JP Nagar Branch";
refSixteen.location = "JP Nagar";
refSixteen.city = "Bangalore";
refSixteen.state = "Karnataka";
refSixteen.country = "India";
refSixteen.ifscCode = "IBKL0002345";
refSixteen.managerName = "Rohit Sharma";
refSixteen.numberOfEmployees = 31;
refSixteen.numberOfCustomers = 7200;
refSixteen.hasATM = true;
refSixteen.hasLoanFacility = true;
refSixteen.hasNetBanking = true;
refSixteen.hasMobileBanking = true;
refSixteen.hasLockerFacility = true;
refSixteen.numberOfATMs = 2;
refSixteen.contactNumber = "08098901234";
refSixteen.email = "manager.jpnagar@idbi.co.in";
refSixteen.website = "www.idbibank.in";
refSixteen.establishedYear = 1964;
refSixteen.bankType = "Public Sector";
refSixteen.totalAssets = 2100000000.75;
refSixteen.headquarters = "Mumbai";
refSixteen.isGovernmentBank = true;


System.out.println("The bankId is: " + refSixteen.bankId);
System.out.println("The bankName is: " + refSixteen.bankName);
System.out.println("The branchName is: " + refSixteen.branchName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The ifscCode is: " + refSixteen.ifscCode);
System.out.println("The managerName is: " + refSixteen.managerName);
System.out.println("The numberOfEmployees is: " + refSixteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refSixteen.numberOfCustomers);
System.out.println("The hasATM is: " + refSixteen.hasATM);
System.out.println("The hasLoanFacility is: " + refSixteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refSixteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refSixteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refSixteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refSixteen.numberOfATMs);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The bankType is: " + refSixteen.bankType);
System.out.println("The totalAssets is: " + refSixteen.totalAssets);
System.out.println("The headquarters is: " + refSixteen.headquarters);
System.out.println("The isGovernmentBank is: " + refSixteen.isGovernmentBank);
Bank refSeventeen = new Bank();

System.out.println("The bankId is: " + refSeventeen.bankId);
System.out.println("The bankName is: " + refSeventeen.bankName);
System.out.println("The branchName is: " + refSeventeen.branchName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The ifscCode is: " + refSeventeen.ifscCode);
System.out.println("The managerName is: " + refSeventeen.managerName);
System.out.println("The numberOfEmployees is: " + refSeventeen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refSeventeen.numberOfCustomers);
System.out.println("The hasATM is: " + refSeventeen.hasATM);
System.out.println("The hasLoanFacility is: " + refSeventeen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refSeventeen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refSeventeen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refSeventeen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refSeventeen.numberOfATMs);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The bankType is: " + refSeventeen.bankType);
System.out.println("The totalAssets is: " + refSeventeen.totalAssets);
System.out.println("The headquarters is: " + refSeventeen.headquarters);
System.out.println("The isGovernmentBank is: " + refSeventeen.isGovernmentBank);


refSeventeen.bankId = 17;
refSeventeen.bankName = "Bandhan Bank";
refSeventeen.branchName = "Bellandur Branch";
refSeventeen.location = "Bellandur";
refSeventeen.city = "Bangalore";
refSeventeen.state = "Karnataka";
refSeventeen.country = "India";
refSeventeen.ifscCode = "BDBL0001765";
refSeventeen.managerName = "Neha Gupta";
refSeventeen.numberOfEmployees = 24;
refSeventeen.numberOfCustomers = 5200;
refSeventeen.hasATM = true;
refSeventeen.hasLoanFacility = true;
refSeventeen.hasNetBanking = true;
refSeventeen.hasMobileBanking = true;
refSeventeen.hasLockerFacility = false;
refSeventeen.numberOfATMs = 1;
refSeventeen.contactNumber = "08099887766";
refSeventeen.email = "manager.bellandur@bandhanbank.com";
refSeventeen.website = "www.bandhanbank.com";
refSeventeen.establishedYear = 2015;
refSeventeen.bankType = "Private Sector";
refSeventeen.totalAssets = 1300000000.60;
refSeventeen.headquarters = "Kolkata";
refSeventeen.isGovernmentBank = false;


System.out.println("The bankId is: " + refSeventeen.bankId);
System.out.println("The bankName is: " + refSeventeen.bankName);
System.out.println("The branchName is: " + refSeventeen.branchName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The ifscCode is: " + refSeventeen.ifscCode);
System.out.println("The managerName is: " + refSeventeen.managerName);
System.out.println("The numberOfEmployees is: " + refSeventeen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refSeventeen.numberOfCustomers);
System.out.println("The hasATM is: " + refSeventeen.hasATM);
System.out.println("The hasLoanFacility is: " + refSeventeen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refSeventeen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refSeventeen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refSeventeen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refSeventeen.numberOfATMs);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The bankType is: " + refSeventeen.bankType);
System.out.println("The totalAssets is: " + refSeventeen.totalAssets);
System.out.println("The headquarters is: " + refSeventeen.headquarters);
System.out.println("The isGovernmentBank is: " + refSeventeen.isGovernmentBank);
Bank refEighteen = new Bank();

System.out.println("The bankId is: " + refEighteen.bankId);
System.out.println("The bankName is: " + refEighteen.bankName);
System.out.println("The branchName is: " + refEighteen.branchName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The ifscCode is: " + refEighteen.ifscCode);
System.out.println("The managerName is: " + refEighteen.managerName);
System.out.println("The numberOfEmployees is: " + refEighteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refEighteen.numberOfCustomers);
System.out.println("The hasATM is: " + refEighteen.hasATM);
System.out.println("The hasLoanFacility is: " + refEighteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refEighteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refEighteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refEighteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refEighteen.numberOfATMs);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The bankType is: " + refEighteen.bankType);
System.out.println("The totalAssets is: " + refEighteen.totalAssets);
System.out.println("The headquarters is: " + refEighteen.headquarters);
System.out.println("The isGovernmentBank is: " + refEighteen.isGovernmentBank);


refEighteen.bankId = 18;
refEighteen.bankName = "RBL Bank";
refEighteen.branchName = "Indiranagar Branch";
refEighteen.location = "Indiranagar";
refEighteen.city = "Bangalore";
refEighteen.state = "Karnataka";
refEighteen.country = "India";
refEighteen.ifscCode = "RATN0001234";
refEighteen.managerName = "Amit Kulkarni";
refEighteen.numberOfEmployees = 22;
refEighteen.numberOfCustomers = 4800;
refEighteen.hasATM = true;
refEighteen.hasLoanFacility = true;
refEighteen.hasNetBanking = true;
refEighteen.hasMobileBanking = true;
refEighteen.hasLockerFacility = false;
refEighteen.numberOfATMs = 1;
refEighteen.contactNumber = "08088776655";
refEighteen.email = "manager.indiranagar@rblbank.com";
refEighteen.website = "www.rblbank.com";
refEighteen.establishedYear = 1943;
refEighteen.bankType = "Private Sector";
refEighteen.totalAssets = 1200000000.80;
refEighteen.headquarters = "Mumbai";
refEighteen.isGovernmentBank = false;


System.out.println("The bankId is: " + refEighteen.bankId);
System.out.println("The bankName is: " + refEighteen.bankName);
System.out.println("The branchName is: " + refEighteen.branchName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The ifscCode is: " + refEighteen.ifscCode);
System.out.println("The managerName is: " + refEighteen.managerName);
System.out.println("The numberOfEmployees is: " + refEighteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refEighteen.numberOfCustomers);
System.out.println("The hasATM is: " + refEighteen.hasATM);
System.out.println("The hasLoanFacility is: " + refEighteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refEighteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refEighteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refEighteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refEighteen.numberOfATMs);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The bankType is: " + refEighteen.bankType);
System.out.println("The totalAssets is: " + refEighteen.totalAssets);
System.out.println("The headquarters is: " + refEighteen.headquarters);
System.out.println("The isGovernmentBank is: " + refEighteen.isGovernmentBank);
Bank refNineteen = new Bank();

System.out.println("The bankId is: " + refNineteen.bankId);
System.out.println("The bankName is: " + refNineteen.bankName);
System.out.println("The branchName is: " + refNineteen.branchName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The ifscCode is: " + refNineteen.ifscCode);
System.out.println("The managerName is: " + refNineteen.managerName);
System.out.println("The numberOfEmployees is: " + refNineteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refNineteen.numberOfCustomers);
System.out.println("The hasATM is: " + refNineteen.hasATM);
System.out.println("The hasLoanFacility is: " + refNineteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refNineteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refNineteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refNineteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refNineteen.numberOfATMs);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The bankType is: " + refNineteen.bankType);
System.out.println("The totalAssets is: " + refNineteen.totalAssets);
System.out.println("The headquarters is: " + refNineteen.headquarters);
System.out.println("The isGovernmentBank is: " + refNineteen.isGovernmentBank);


refNineteen.bankId = 19;
refNineteen.bankName = "Yes Bank";
refNineteen.branchName = "MG Road Branch";
refNineteen.location = "MG Road";
refNineteen.city = "Bangalore";
refNineteen.state = "Karnataka";
refNineteen.country = "India";
refNineteen.ifscCode = "YESB0006789";
refNineteen.managerName = "Sonia Mehta";
refNineteen.numberOfEmployees = 25;
refNineteen.numberOfCustomers = 5000;
refNineteen.hasATM = true;
refNineteen.hasLoanFacility = true;
refNineteen.hasNetBanking = true;
refNineteen.hasMobileBanking = true;
refNineteen.hasLockerFacility = false;
refNineteen.numberOfATMs = 1;
refNineteen.contactNumber = "08099887744";
refNineteen.email = "manager.mgroad@yesbank.in";
refNineteen.website = "www.yesbank.in";
refNineteen.establishedYear = 2004;
refNineteen.bankType = "Private Sector";
refNineteen.totalAssets = 1400000000.35;
refNineteen.headquarters = "Mumbai";
refNineteen.isGovernmentBank = false;


System.out.println("The bankId is: " + refNineteen.bankId);
System.out.println("The bankName is: " + refNineteen.bankName);
System.out.println("The branchName is: " + refNineteen.branchName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The ifscCode is: " + refNineteen.ifscCode);
System.out.println("The managerName is: " + refNineteen.managerName);
System.out.println("The numberOfEmployees is: " + refNineteen.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refNineteen.numberOfCustomers);
System.out.println("The hasATM is: " + refNineteen.hasATM);
System.out.println("The hasLoanFacility is: " + refNineteen.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refNineteen.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refNineteen.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refNineteen.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refNineteen.numberOfATMs);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The bankType is: " + refNineteen.bankType);
System.out.println("The totalAssets is: " + refNineteen.totalAssets);
System.out.println("The headquarters is: " + refNineteen.headquarters);
System.out.println("The isGovernmentBank is: " + refNineteen.isGovernmentBank);
Bank refTwenty = new Bank();

System.out.println("The bankId is: " + refTwenty.bankId);
System.out.println("The bankName is: " + refTwenty.bankName);
System.out.println("The branchName is: " + refTwenty.branchName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The ifscCode is: " + refTwenty.ifscCode);
System.out.println("The managerName is: " + refTwenty.managerName);
System.out.println("The numberOfEmployees is: " + refTwenty.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refTwenty.numberOfCustomers);
System.out.println("The hasATM is: " + refTwenty.hasATM);
System.out.println("The hasLoanFacility is: " + refTwenty.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refTwenty.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refTwenty.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refTwenty.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refTwenty.numberOfATMs);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The bankType is: " + refTwenty.bankType);
System.out.println("The totalAssets is: " + refTwenty.totalAssets);
System.out.println("The headquarters is: " + refTwenty.headquarters);
System.out.println("The isGovernmentBank is: " + refTwenty.isGovernmentBank);


refTwenty.bankId = 20;
refTwenty.bankName = "IDFC First Bank";
refTwenty.branchName = "Whitefield Branch";
refTwenty.location = "Whitefield";
refTwenty.city = "Bangalore";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.ifscCode = "IDFB0002345";
refTwenty.managerName = "Ritika Sharma";
refTwenty.numberOfEmployees = 23;
refTwenty.numberOfCustomers = 5400;
refTwenty.hasATM = true;
refTwenty.hasLoanFacility = true;
refTwenty.hasNetBanking = true;
refTwenty.hasMobileBanking = true;
refTwenty.hasLockerFacility = false;
refTwenty.numberOfATMs = 1;
refTwenty.contactNumber = "08098765432";
refTwenty.email = "manager.whitefield@idfcfirstbank.com";
refTwenty.website = "www.idfcfirstbank.com";
refTwenty.establishedYear = 2015;
refTwenty.bankType = "Private Sector";
refTwenty.totalAssets = 1250000000.90;
refTwenty.headquarters = "Mumbai";
refTwenty.isGovernmentBank = false;


System.out.println("The bankId is: " + refTwenty.bankId);
System.out.println("The bankName is: " + refTwenty.bankName);
System.out.println("The branchName is: " + refTwenty.branchName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The ifscCode is: " + refTwenty.ifscCode);
System.out.println("The managerName is: " + refTwenty.managerName);
System.out.println("The numberOfEmployees is: " + refTwenty.numberOfEmployees);
System.out.println("The numberOfCustomers is: " + refTwenty.numberOfCustomers);
System.out.println("The hasATM is: " + refTwenty.hasATM);
System.out.println("The hasLoanFacility is: " + refTwenty.hasLoanFacility);
System.out.println("The hasNetBanking is: " + refTwenty.hasNetBanking);
System.out.println("The hasMobileBanking is: " + refTwenty.hasMobileBanking);
System.out.println("The hasLockerFacility is: " + refTwenty.hasLockerFacility);
System.out.println("The numberOfATMs is: " + refTwenty.numberOfATMs);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The bankType is: " + refTwenty.bankType);
System.out.println("The totalAssets is: " + refTwenty.totalAssets);
System.out.println("The headquarters is: " + refTwenty.headquarters);
System.out.println("The isGovernmentBank is: " + refTwenty.isGovernmentBank);
}
}