class BankExecutor {
    public static void main(String[] args) {

        Bank b1 = new Bank();
        b1.setBankId(1);
        b1.setBankName("SBI");
        b1.setBranch("Branch1");
        b1.setIfscCode("IFSC001");
        b1.setAccountType("Savings");
        b1.setBalance(1000);
        b1.setCustomerName("User1");
        System.out.println(b1.getBankId());
        System.out.println(b1.getBankName());
        System.out.println(b1.getBranch());
        System.out.println(b1.getIfscCode());
        System.out.println(b1.getAccountType());
        System.out.println(b1.getBalance());
        System.out.println(b1.getCustomerName());

        Bank b2 = new Bank();
        b2.setBankId(2);
        b2.setBankName("HDFC");
        b2.setBranch("Branch2");
        b2.setIfscCode("IFSC002");
        b2.setAccountType("Current");
        b2.setBalance(2000);
        b2.setCustomerName("User2");
        System.out.println(b2.getBankId());
        System.out.println(b2.getBankName());
        System.out.println(b2.getBranch());
        System.out.println(b2.getIfscCode());
        System.out.println(b2.getAccountType());
        System.out.println(b2.getBalance());
        System.out.println(b2.getCustomerName());

        Bank b3 = new Bank();
        b3.setBankId(3);
        b3.setBankName("ICICI");
        b3.setBranch("Branch3");
        b3.setIfscCode("IFSC003");
        b3.setAccountType("Savings");
        b3.setBalance(3000);
        b3.setCustomerName("User3");
        System.out.println(b3.getBankId());
        System.out.println(b3.getBankName());
        System.out.println(b3.getBranch());
        System.out.println(b3.getIfscCode());
        System.out.println(b3.getAccountType());
        System.out.println(b3.getBalance());
        System.out.println(b3.getCustomerName());

        Bank b4 = new Bank();
        b4.setBankId(4);
        b4.setBankName("Axis");
        b4.setBranch("Branch4");
        b4.setIfscCode("IFSC004");
        b4.setAccountType("Current");
        b4.setBalance(4000);
        b4.setCustomerName("User4");
        System.out.println(b4.getBankId());
        System.out.println(b4.getBankName());
        System.out.println(b4.getBranch());
        System.out.println(b4.getIfscCode());
        System.out.println(b4.getAccountType());
        System.out.println(b4.getBalance());
        System.out.println(b4.getCustomerName());

        Bank b5 = new Bank();
        b5.setBankId(5);
        b5.setBankName("Canara");
        b5.setBranch("Branch5");
        b5.setIfscCode("IFSC005");
        b5.setAccountType("Savings");
        b5.setBalance(5000);
        b5.setCustomerName("User5");
        System.out.println(b5.getBankId());
        System.out.println(b5.getBankName());
        System.out.println(b5.getBranch());
        System.out.println(b5.getIfscCode());
        System.out.println(b5.getAccountType());
        System.out.println(b5.getBalance());
        System.out.println(b5.getCustomerName());

        Bank b6 = new Bank();
        b6.setBankId(6);
        b6.setBankName("SBI");
        b6.setBranch("Branch6");
        b6.setIfscCode("IFSC006");
        b6.setAccountType("Current");
        b6.setBalance(6000);
        b6.setCustomerName("User6");
        System.out.println(b6.getBankId());
        System.out.println(b6.getBankName());
        System.out.println(b6.getBranch());
        System.out.println(b6.getIfscCode());
        System.out.println(b6.getAccountType());
        System.out.println(b6.getBalance());
        System.out.println(b6.getCustomerName());

        Bank b7 = new Bank();
        b7.setBankId(7);
        b7.setBankName("HDFC");
        b7.setBranch("Branch7");
        b7.setIfscCode("IFSC007");
        b7.setAccountType("Savings");
        b7.setBalance(7000);
        b7.setCustomerName("User7");
        System.out.println(b7.getBankId());
        System.out.println(b7.getBankName());
        System.out.println(b7.getBranch());
        System.out.println(b7.getIfscCode());
        System.out.println(b7.getAccountType());
        System.out.println(b7.getBalance());
        System.out.println(b7.getCustomerName());

        Bank b8 = new Bank();
        b8.setBankId(8);
        b8.setBankName("ICICI");
        b8.setBranch("Branch8");
        b8.setIfscCode("IFSC008");
        b8.setAccountType("Current");
        b8.setBalance(8000);
        b8.setCustomerName("User8");
        System.out.println(b8.getBankId());
        System.out.println(b8.getBankName());
        System.out.println(b8.getBranch());
        System.out.println(b8.getIfscCode());
        System.out.println(b8.getAccountType());
        System.out.println(b8.getBalance());
        System.out.println(b8.getCustomerName());

        Bank b9 = new Bank();
        b9.setBankId(9);
        b9.setBankName("Axis");
        b9.setBranch("Branch9");
        b9.setIfscCode("IFSC009");
        b9.setAccountType("Savings");
        b9.setBalance(9000);
        b9.setCustomerName("User9");
        System.out.println(b9.getBankId());
        System.out.println(b9.getBankName());
        System.out.println(b9.getBranch());
        System.out.println(b9.getIfscCode());
        System.out.println(b9.getAccountType());
        System.out.println(b9.getBalance());
        System.out.println(b9.getCustomerName());

        Bank b10 = new Bank();
        b10.setBankId(10);
        b10.setBankName("Canara");
        b10.setBranch("Branch10");
        b10.setIfscCode("IFSC010");
        b10.setAccountType("Current");
        b10.setBalance(10000);
        b10.setCustomerName("User10");
        System.out.println(b10.getBankId());
        System.out.println(b10.getBankName());
        System.out.println(b10.getBranch());
        System.out.println(b10.getIfscCode());
        System.out.println(b10.getAccountType());
        System.out.println(b10.getBalance());
        System.out.println(b10.getCustomerName());

        Bank b11 = new Bank();
        b11.setBankId(11);
        b11.setBankName("SBI");
        b11.setBranch("Branch11");
        b11.setIfscCode("IFSC011");
        b11.setAccountType("Savings");
        b11.setBalance(11000);
        b11.setCustomerName("User11");
        System.out.println(b11.getBankId());
        System.out.println(b11.getBankName());
        System.out.println(b11.getBranch());
        System.out.println(b11.getIfscCode());
        System.out.println(b11.getAccountType());
        System.out.println(b11.getBalance());
        System.out.println(b11.getCustomerName());

        Bank b12 = new Bank();
        b12.setBankId(12);
        b12.setBankName("HDFC");
        b12.setBranch("Branch12");
        b12.setIfscCode("IFSC012");
        b12.setAccountType("Current");
        b12.setBalance(12000);
        b12.setCustomerName("User12");
        System.out.println(b12.getBankId());
        System.out.println(b12.getBankName());
        System.out.println(b12.getBranch());
        System.out.println(b12.getIfscCode());
        System.out.println(b12.getAccountType());
        System.out.println(b12.getBalance());
        System.out.println(b12.getCustomerName());

        Bank b13 = new Bank();
        b13.setBankId(13);
        b13.setBankName("ICICI");
        b13.setBranch("Branch13");
        b13.setIfscCode("IFSC013");
        b13.setAccountType("Savings");
        b13.setBalance(13000);
        b13.setCustomerName("User13");
        System.out.println(b13.getBankId());
        System.out.println(b13.getBankName());
        System.out.println(b13.getBranch());
        System.out.println(b13.getIfscCode());
        System.out.println(b13.getAccountType());
        System.out.println(b13.getBalance());
        System.out.println(b13.getCustomerName());

        Bank b14 = new Bank();
        b14.setBankId(14);
        b14.setBankName("Axis");
        b14.setBranch("Branch14");
        b14.setIfscCode("IFSC014");
        b14.setAccountType("Current");
        b14.setBalance(14000);
        b14.setCustomerName("User14");
        System.out.println(b14.getBankId());
        System.out.println(b14.getBankName());
        System.out.println(b14.getBranch());
        System.out.println(b14.getIfscCode());
        System.out.println(b14.getAccountType());
        System.out.println(b14.getBalance());
        System.out.println(b14.getCustomerName());

        Bank b15 = new Bank();
        b15.setBankId(15);
        b15.setBankName("Canara");
        b15.setBranch("Branch15");
        b15.setIfscCode("IFSC015");
        b15.setAccountType("Savings");
        b15.setBalance(15000);
        b15.setCustomerName("User15");
        System.out.println(b15.getBankId());
        System.out.println(b15.getBankName());
        System.out.println(b15.getBranch());
        System.out.println(b15.getIfscCode());
        System.out.println(b15.getAccountType());
        System.out.println(b15.getBalance());
        System.out.println(b15.getCustomerName());

        Bank b16 = new Bank();
        b16.setBankId(16);
        b16.setBankName("SBI");
        b16.setBranch("Branch16");
        b16.setIfscCode("IFSC016");
        b16.setAccountType("Current");
        b16.setBalance(16000);
        b16.setCustomerName("User16");
        System.out.println(b16.getBankId());
        System.out.println(b16.getBankName());
        System.out.println(b16.getBranch());
        System.out.println(b16.getIfscCode());
        System.out.println(b16.getAccountType());
        System.out.println(b16.getBalance());
        System.out.println(b16.getCustomerName());

        Bank b17 = new Bank();
        b17.setBankId(17);
        b17.setBankName("HDFC");
        b17.setBranch("Branch17");
        b17.setIfscCode("IFSC017");
        b17.setAccountType("Savings");
        b17.setBalance(17000);
        b17.setCustomerName("User17");
        System.out.println(b17.getBankId());
        System.out.println(b17.getBankName());
        System.out.println(b17.getBranch());
        System.out.println(b17.getIfscCode());
        System.out.println(b17.getAccountType());
        System.out.println(b17.getBalance());
        System.out.println(b17.getCustomerName());

        Bank b18 = new Bank();
        b18.setBankId(18);
        b18.setBankName("ICICI");
        b18.setBranch("Branch18");
        b18.setIfscCode("IFSC018");
        b18.setAccountType("Current");
        b18.setBalance(18000);
        b18.setCustomerName("User18");
        System.out.println(b18.getBankId());
        System.out.println(b18.getBankName());
        System.out.println(b18.getBranch());
        System.out.println(b18.getIfscCode());
        System.out.println(b18.getAccountType());
        System.out.println(b18.getBalance());
        System.out.println(b18.getCustomerName());

        Bank b19 = new Bank();
        b19.setBankId(19);
        b19.setBankName("Axis");
        b19.setBranch("Branch19");
        b19.setIfscCode("IFSC019");
        b19.setAccountType("Savings");
        b19.setBalance(19000);
        b19.setCustomerName("User19");
        System.out.println(b19.getBankId());
        System.out.println(b19.getBankName());
        System.out.println(b19.getBranch());
        System.out.println(b19.getIfscCode());
        System.out.println(b19.getAccountType());
        System.out.println(b19.getBalance());
        System.out.println(b19.getCustomerName());

        Bank b20 = new Bank();
        b20.setBankId(20);
        b20.setBankName("Canara");
        b20.setBranch("Branch20");
        b20.setIfscCode("IFSC020");
        b20.setAccountType("Current");
        b20.setBalance(20000);
        b20.setCustomerName("User20");
        System.out.println(b20.getBankId());
        System.out.println(b20.getBankName());
        System.out.println(b20.getBranch());
        System.out.println(b20.getIfscCode());
        System.out.println(b20.getAccountType());
        System.out.println(b20.getBalance());
        System.out.println(b20.getCustomerName());

        Bank b21 = new Bank();
        b21.setBankId(21);
        b21.setBankName("SBI");
        b21.setBranch("Branch21");
        b21.setIfscCode("IFSC021");
        b21.setAccountType("Savings");
        b21.setBalance(21000);
        b21.setCustomerName("User21");
        System.out.println(b21.getBankId());
        System.out.println(b21.getBankName());
        System.out.println(b21.getBranch());
        System.out.println(b21.getIfscCode());
        System.out.println(b21.getAccountType());
        System.out.println(b21.getBalance());
        System.out.println(b21.getCustomerName());

        Bank b22 = new Bank();
        b22.setBankId(22);
        b22.setBankName("HDFC");
        b22.setBranch("Branch22");
        b22.setIfscCode("IFSC022");
        b22.setAccountType("Current");
        b22.setBalance(22000);
        b22.setCustomerName("User22");
        System.out.println(b22.getBankId());
        System.out.println(b22.getBankName());
        System.out.println(b22.getBranch());
        System.out.println(b22.getIfscCode());
        System.out.println(b22.getAccountType());
        System.out.println(b22.getBalance());
        System.out.println(b22.getCustomerName());

        Bank b23 = new Bank();
        b23.setBankId(23);
        b23.setBankName("ICICI");
        b23.setBranch("Branch23");
        b23.setIfscCode("IFSC023");
        b23.setAccountType("Savings");
        b23.setBalance(23000);
        b23.setCustomerName("User23");
        System.out.println(b23.getBankId());
        System.out.println(b23.getBankName());
        System.out.println(b23.getBranch());
        System.out.println(b23.getIfscCode());
        System.out.println(b23.getAccountType());
        System.out.println(b23.getBalance());
        System.out.println(b23.getCustomerName());

        Bank b24 = new Bank();
        b24.setBankId(24);
        b24.setBankName("Axis");
        b24.setBranch("Branch24");
        b24.setIfscCode("IFSC024");
        b24.setAccountType("Current");
        b24.setBalance(24000);
        b24.setCustomerName("User24");
        System.out.println(b24.getBankId());
        System.out.println(b24.getBankName());
        System.out.println(b24.getBranch());
        System.out.println(b24.getIfscCode());
        System.out.println(b24.getAccountType());
        System.out.println(b24.getBalance());
        System.out.println(b24.getCustomerName());

        Bank b25 = new Bank();
        b25.setBankId(25);
        b25.setBankName("Canara");
        b25.setBranch("Branch25");
        b25.setIfscCode("IFSC025");
        b25.setAccountType("Savings");
        b25.setBalance(25000);
        b25.setCustomerName("User25");
        System.out.println(b25.getBankId());
        System.out.println(b25.getBankName());
        System.out.println(b25.getBranch());
        System.out.println(b25.getIfscCode());
        System.out.println(b25.getAccountType());
        System.out.println(b25.getBalance());
        System.out.println(b25.getCustomerName());

        Bank b26 = new Bank();
        b26.setBankId(26);
        b26.setBankName("SBI");
        b26.setBranch("Branch26");
        b26.setIfscCode("IFSC026");
        b26.setAccountType("Current");
        b26.setBalance(26000);
        b26.setCustomerName("User26");
        System.out.println(b26.getBankId());
        System.out.println(b26.getBankName());
        System.out.println(b26.getBranch());
        System.out.println(b26.getIfscCode());
        System.out.println(b26.getAccountType());
        System.out.println(b26.getBalance());
        System.out.println(b26.getCustomerName());

        Bank b27 = new Bank();
        b27.setBankId(27);
        b27.setBankName("HDFC");
        b27.setBranch("Branch27");
        b27.setIfscCode("IFSC027");
        b27.setAccountType("Savings");
        b27.setBalance(27000);
        b27.setCustomerName("User27");
        System.out.println(b27.getBankId());
        System.out.println(b27.getBankName());
        System.out.println(b27.getBranch());
        System.out.println(b27.getIfscCode());
        System.out.println(b27.getAccountType());
        System.out.println(b27.getBalance());
        System.out.println(b27.getCustomerName());

        Bank b28 = new Bank();
        b28.setBankId(28);
        b28.setBankName("ICICI");
        b28.setBranch("Branch28");
        b28.setIfscCode("IFSC028");
        b28.setAccountType("Current");
        b28.setBalance(28000);
        b28.setCustomerName("User28");
        System.out.println(b28.getBankId());
        System.out.println(b28.getBankName());
        System.out.println(b28.getBranch());
        System.out.println(b28.getIfscCode());
        System.out.println(b28.getAccountType());
        System.out.println(b28.getBalance());
        System.out.println(b28.getCustomerName());

        Bank b29 = new Bank();
        b29.setBankId(29);
        b29.setBankName("Axis");
        b29.setBranch("Branch29");
        b29.setIfscCode("IFSC029");
        b29.setAccountType("Savings");
        b29.setBalance(29000);
        b29.setCustomerName("User29");
        System.out.println(b29.getBankId());
        System.out.println(b29.getBankName());
        System.out.println(b29.getBranch());
        System.out.println(b29.getIfscCode());
        System.out.println(b29.getAccountType());
        System.out.println(b29.getBalance());
        System.out.println(b29.getCustomerName());
    }
}