class BookExecutor{
public static void main(String[] args){
Book refOne = new Book();

System.out.println("The bookId is: " + refOne.bookId);
System.out.println("The title is: " + refOne.title);
System.out.println("The author is: " + refOne.author);
System.out.println("The publisher is: " + refOne.publisher);
System.out.println("The publicationYear is: " + refOne.publicationYear);
System.out.println("The numberOfPages is: " + refOne.numberOfPages);
System.out.println("The language is: " + refOne.language);
System.out.println("The price is: " + refOne.price);
System.out.println("The genre is: " + refOne.genre);
System.out.println("The isbn is: " + refOne.isbn);
System.out.println("The isHardcover is: " + refOne.isHardcover);
System.out.println("The isEbookAvailable is: " + refOne.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refOne.isAudioBookAvailable);
System.out.println("The rating is: " + refOne.rating);
System.out.println("The numberOfReviews is: " + refOne.numberOfReviews);
System.out.println("The edition is: " + refOne.edition);
System.out.println("The coverColor is: " + refOne.coverColor);
System.out.println("The weight is: " + refOne.weight);
System.out.println("The shelfLocation is: " + refOne.shelfLocation);
System.out.println("The isAvailable is: " + refOne.isAvailable);
System.out.println("The borrowerName is: " + refOne.borrowerName);
System.out.println("The libraryName is: " + refOne.libraryName);
System.out.println("The countryOfPublication is: " + refOne.countryOfPublication);
System.out.println("The translator is: " + refOne.translator);
System.out.println("The category is: " + refOne.category);


refOne.bookId = 1;
refOne.title = "Wings of Fire";
refOne.author = "A.P.J Abdul Kalam";
refOne.publisher = "Universities Press";
refOne.publicationYear = 1999;
refOne.numberOfPages = 180;
refOne.language = "English";
refOne.price = 350;
refOne.genre = "Autobiography";
refOne.isbn = "9788173711466";
refOne.isHardcover = false;
refOne.isEbookAvailable = true;
refOne.isAudioBookAvailable = true;
refOne.rating = 4.7;
refOne.numberOfReviews = 25000;
refOne.edition = "1st";
refOne.coverColor = "Blue";
refOne.weight = 300;
refOne.shelfLocation = "A12";
refOne.isAvailable = true;
refOne.borrowerName = "None";
refOne.libraryName = "City Library";
refOne.countryOfPublication = "India";
refOne.translator = "None";
refOne.category = "Motivation";

System.out.println("The bookId is: " + refOne.bookId);
System.out.println("The title is: " + refOne.title);
System.out.println("The author is: " + refOne.author);
System.out.println("The publisher is: " + refOne.publisher);
System.out.println("The publicationYear is: " + refOne.publicationYear);
System.out.println("The numberOfPages is: " + refOne.numberOfPages);
System.out.println("The language is: " + refOne.language);
System.out.println("The price is: " + refOne.price);
System.out.println("The genre is: " + refOne.genre);
System.out.println("The isbn is: " + refOne.isbn);
System.out.println("The isHardcover is: " + refOne.isHardcover);
System.out.println("The isEbookAvailable is: " + refOne.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refOne.isAudioBookAvailable);
System.out.println("The rating is: " + refOne.rating);
System.out.println("The numberOfReviews is: " + refOne.numberOfReviews);
System.out.println("The edition is: " + refOne.edition);
System.out.println("The coverColor is: " + refOne.coverColor);
System.out.println("The weight is: " + refOne.weight);
System.out.println("The shelfLocation is: " + refOne.shelfLocation);
System.out.println("The isAvailable is: " + refOne.isAvailable);
System.out.println("The borrowerName is: " + refOne.borrowerName);
System.out.println("The libraryName is: " + refOne.libraryName);
System.out.println("The countryOfPublication is: " + refOne.countryOfPublication);
System.out.println("The translator is: " + refOne.translator);
System.out.println("The category is: " + refOne.category);
Book refTwo = new Book();

System.out.println("The bookId is: " + refTwo.bookId);
System.out.println("The title is: " + refTwo.title);
System.out.println("The author is: " + refTwo.author);
System.out.println("The publisher is: " + refTwo.publisher);
System.out.println("The publicationYear is: " + refTwo.publicationYear);
System.out.println("The numberOfPages is: " + refTwo.numberOfPages);
System.out.println("The language is: " + refTwo.language);
System.out.println("The price is: " + refTwo.price);
System.out.println("The genre is: " + refTwo.genre);
System.out.println("The isbn is: " + refTwo.isbn);
System.out.println("The isHardcover is: " + refTwo.isHardcover);
System.out.println("The isEbookAvailable is: " + refTwo.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refTwo.isAudioBookAvailable);
System.out.println("The rating is: " + refTwo.rating);
System.out.println("The numberOfReviews is: " + refTwo.numberOfReviews);
System.out.println("The edition is: " + refTwo.edition);
System.out.println("The coverColor is: " + refTwo.coverColor);
System.out.println("The weight is: " + refTwo.weight);
System.out.println("The shelfLocation is: " + refTwo.shelfLocation);
System.out.println("The isAvailable is: " + refTwo.isAvailable);
System.out.println("The borrowerName is: " + refTwo.borrowerName);
System.out.println("The libraryName is: " + refTwo.libraryName);
System.out.println("The countryOfPublication is: " + refTwo.countryOfPublication);
System.out.println("The translator is: " + refTwo.translator);
System.out.println("The category is: " + refTwo.category);


refTwo.bookId = 2;
refTwo.title = "The Alchemist";
refTwo.author = "Paulo Coelho";
refTwo.publisher = "HarperCollins";
refTwo.publicationYear = 1988;
refTwo.numberOfPages = 208;
refTwo.language = "English";
refTwo.price = 450;
refTwo.genre = "Fiction";
refTwo.isbn = "9780061122415";
refTwo.isHardcover = true;
refTwo.isEbookAvailable = true;
refTwo.isAudioBookAvailable = true;
refTwo.rating = 4.6;
refTwo.numberOfReviews = 30000;
refTwo.edition = "2nd";
refTwo.coverColor = "Gold";
refTwo.weight = 320;
refTwo.shelfLocation = "B10";
refTwo.isAvailable = true;
refTwo.borrowerName = "None";
refTwo.libraryName = "Central Library";
refTwo.countryOfPublication = "Brazil";
refTwo.translator = "Alan R Clarke";
refTwo.category = "Philosophical";

System.out.println("The bookId is: " + refTwo.bookId);
System.out.println("The title is: " + refTwo.title);
System.out.println("The author is: " + refTwo.author);
System.out.println("The publisher is: " + refTwo.publisher);
System.out.println("The publicationYear is: " + refTwo.publicationYear);
System.out.println("The numberOfPages is: " + refTwo.numberOfPages);
System.out.println("The language is: " + refTwo.language);
System.out.println("The price is: " + refTwo.price);
System.out.println("The genre is: " + refTwo.genre);
System.out.println("The isbn is: " + refTwo.isbn);
System.out.println("The isHardcover is: " + refTwo.isHardcover);
System.out.println("The isEbookAvailable is: " + refTwo.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refTwo.isAudioBookAvailable);
System.out.println("The rating is: " + refTwo.rating);
System.out.println("The numberOfReviews is: " + refTwo.numberOfReviews);
System.out.println("The edition is: " + refTwo.edition);
System.out.println("The coverColor is: " + refTwo.coverColor);
System.out.println("The weight is: " + refTwo.weight);
System.out.println("The shelfLocation is: " + refTwo.shelfLocation);
System.out.println("The isAvailable is: " + refTwo.isAvailable);
System.out.println("The borrowerName is: " + refTwo.borrowerName);
System.out.println("The libraryName is: " + refTwo.libraryName);
System.out.println("The countryOfPublication is: " + refTwo.countryOfPublication);
System.out.println("The translator is: " + refTwo.translator);
System.out.println("The category is: " + refTwo.category);
Book refThree = new Book();

System.out.println("The bookId is: " + refThree.bookId);
System.out.println("The title is: " + refThree.title);
System.out.println("The author is: " + refThree.author);
System.out.println("The publisher is: " + refThree.publisher);
System.out.println("The publicationYear is: " + refThree.publicationYear);
System.out.println("The numberOfPages is: " + refThree.numberOfPages);
System.out.println("The language is: " + refThree.language);
System.out.println("The price is: " + refThree.price);
System.out.println("The genre is: " + refThree.genre);
System.out.println("The isbn is: " + refThree.isbn);
System.out.println("The isHardcover is: " + refThree.isHardcover);
System.out.println("The isEbookAvailable is: " + refThree.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refThree.isAudioBookAvailable);
System.out.println("The rating is: " + refThree.rating);
System.out.println("The numberOfReviews is: " + refThree.numberOfReviews);
System.out.println("The edition is: " + refThree.edition);
System.out.println("The coverColor is: " + refThree.coverColor);
System.out.println("The weight is: " + refThree.weight);
System.out.println("The shelfLocation is: " + refThree.shelfLocation);
System.out.println("The isAvailable is: " + refThree.isAvailable);
System.out.println("The borrowerName is: " + refThree.borrowerName);
System.out.println("The libraryName is: " + refThree.libraryName);
System.out.println("The countryOfPublication is: " + refThree.countryOfPublication);
System.out.println("The translator is: " + refThree.translator);
System.out.println("The category is: " + refThree.category);


refThree.bookId = 3;
refThree.title = "Rich Dad Poor Dad";
refThree.author = "Robert T. Kiyosaki";
refThree.publisher = "Plata Publishing";
refThree.publicationYear = 1997;
refThree.numberOfPages = 336;
refThree.language = "English";
refThree.price = 500;
refThree.genre = "Finance";
refThree.isbn = "9781612680194";
refThree.isHardcover = true;
refThree.isEbookAvailable = true;
refThree.isAudioBookAvailable = true;
refThree.rating = 4.5;
refThree.numberOfReviews = 40000;
refThree.edition = "1st";
refThree.coverColor = "Purple";
refThree.weight = 350;
refThree.shelfLocation = "C05";
refThree.isAvailable = true;
refThree.borrowerName = "None";
refThree.libraryName = "Knowledge Library";
refThree.countryOfPublication = "USA";
refThree.translator = "None";
refThree.category = "Self Help";

System.out.println("The bookId is: " + refThree.bookId);
System.out.println("The title is: " + refThree.title);
System.out.println("The author is: " + refThree.author);
System.out.println("The publisher is: " + refThree.publisher);
System.out.println("The publicationYear is: " + refThree.publicationYear);
System.out.println("The numberOfPages is: " + refThree.numberOfPages);
System.out.println("The language is: " + refThree.language);
System.out.println("The price is: " + refThree.price);
System.out.println("The genre is: " + refThree.genre);
System.out.println("The isbn is: " + refThree.isbn);
System.out.println("The isHardcover is: " + refThree.isHardcover);
System.out.println("The isEbookAvailable is: " + refThree.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refThree.isAudioBookAvailable);
System.out.println("The rating is: " + refThree.rating);
System.out.println("The numberOfReviews is: " + refThree.numberOfReviews);
System.out.println("The edition is: " + refThree.edition);
System.out.println("The coverColor is: " + refThree.coverColor);
System.out.println("The weight is: " + refThree.weight);
System.out.println("The shelfLocation is: " + refThree.shelfLocation);
System.out.println("The isAvailable is: " + refThree.isAvailable);
System.out.println("The borrowerName is: " + refThree.borrowerName);
System.out.println("The libraryName is: " + refThree.libraryName);
System.out.println("The countryOfPublication is: " + refThree.countryOfPublication);
System.out.println("The translator is: " + refThree.translator);
System.out.println("The category is: " + refThree.category);
Book refFour = new Book();

System.out.println("The bookId is: " + refFour.bookId);
System.out.println("The title is: " + refFour.title);
System.out.println("The author is: " + refFour.author);
System.out.println("The publisher is: " + refFour.publisher);
System.out.println("The publicationYear is: " + refFour.publicationYear);
System.out.println("The numberOfPages is: " + refFour.numberOfPages);
System.out.println("The language is: " + refFour.language);
System.out.println("The price is: " + refFour.price);
System.out.println("The genre is: " + refFour.genre);
System.out.println("The isbn is: " + refFour.isbn);
System.out.println("The isHardcover is: " + refFour.isHardcover);
System.out.println("The isEbookAvailable is: " + refFour.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refFour.isAudioBookAvailable);
System.out.println("The rating is: " + refFour.rating);
System.out.println("The numberOfReviews is: " + refFour.numberOfReviews);
System.out.println("The edition is: " + refFour.edition);
System.out.println("The coverColor is: " + refFour.coverColor);
System.out.println("The weight is: " + refFour.weight);
System.out.println("The shelfLocation is: " + refFour.shelfLocation);
System.out.println("The isAvailable is: " + refFour.isAvailable);
System.out.println("The borrowerName is: " + refFour.borrowerName);
System.out.println("The libraryName is: " + refFour.libraryName);
System.out.println("The countryOfPublication is: " + refFour.countryOfPublication);
System.out.println("The translator is: " + refFour.translator);
System.out.println("The category is: " + refFour.category);


refFour.bookId = 4;
refFour.title = "Think and Grow Rich";
refFour.author = "Napoleon Hill";
refFour.publisher = "The Ralston Society";
refFour.publicationYear = 1937;
refFour.numberOfPages = 320;
refFour.language = "English";
refFour.price = 420;
refFour.genre = "Self Help";
refFour.isbn = "9781585424337";
refFour.isHardcover = true;
refFour.isEbookAvailable = true;
refFour.isAudioBookAvailable = true;
refFour.rating = 4.4;
refFour.numberOfReviews = 35000;
refFour.edition = "Revised";
refFour.coverColor = "Black";
refFour.weight = 340;
refFour.shelfLocation = "D07";
refFour.isAvailable = true;
refFour.borrowerName = "None";
refFour.libraryName = "City Central Library";
refFour.countryOfPublication = "USA";
refFour.translator = "None";
refFour.category = "Motivation";

System.out.println("The bookId is: " + refFour.bookId);
System.out.println("The title is: " + refFour.title);
System.out.println("The author is: " + refFour.author);
System.out.println("The publisher is: " + refFour.publisher);
System.out.println("The publicationYear is: " + refFour.publicationYear);
System.out.println("The numberOfPages is: " + refFour.numberOfPages);
System.out.println("The language is: " + refFour.language);
System.out.println("The price is: " + refFour.price);
System.out.println("The genre is: " + refFour.genre);
System.out.println("The isbn is: " + refFour.isbn);
System.out.println("The isHardcover is: " + refFour.isHardcover);
System.out.println("The isEbookAvailable is: " + refFour.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refFour.isAudioBookAvailable);
System.out.println("The rating is: " + refFour.rating);
System.out.println("The numberOfReviews is: " + refFour.numberOfReviews);
System.out.println("The edition is: " + refFour.edition);
System.out.println("The coverColor is: " + refFour.coverColor);
System.out.println("The weight is: " + refFour.weight);
System.out.println("The shelfLocation is: " + refFour.shelfLocation);
System.out.println("The isAvailable is: " + refFour.isAvailable);
System.out.println("The borrowerName is: " + refFour.borrowerName);
System.out.println("The libraryName is: " + refFour.libraryName);
System.out.println("The countryOfPublication is: " + refFour.countryOfPublication);
System.out.println("The translator is: " + refFour.translator);
System.out.println("The category is: " + refFour.category);
Book refFive = new Book();

System.out.println("The bookId is: " + refFive.bookId);
System.out.println("The title is: " + refFive.title);
System.out.println("The author is: " + refFive.author);
System.out.println("The publisher is: " + refFive.publisher);
System.out.println("The publicationYear is: " + refFive.publicationYear);
System.out.println("The numberOfPages is: " + refFive.numberOfPages);
System.out.println("The language is: " + refFive.language);
System.out.println("The price is: " + refFive.price);
System.out.println("The genre is: " + refFive.genre);
System.out.println("The isbn is: " + refFive.isbn);
System.out.println("The isHardcover is: " + refFive.isHardcover);
System.out.println("The isEbookAvailable is: " + refFive.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refFive.isAudioBookAvailable);
System.out.println("The rating is: " + refFive.rating);
System.out.println("The numberOfReviews is: " + refFive.numberOfReviews);
System.out.println("The edition is: " + refFive.edition);
System.out.println("The coverColor is: " + refFive.coverColor);
System.out.println("The weight is: " + refFive.weight);
System.out.println("The shelfLocation is: " + refFive.shelfLocation);
System.out.println("The isAvailable is: " + refFive.isAvailable);
System.out.println("The borrowerName is: " + refFive.borrowerName);
System.out.println("The libraryName is: " + refFive.libraryName);
System.out.println("The countryOfPublication is: " + refFive.countryOfPublication);
System.out.println("The translator is: " + refFive.translator);
System.out.println("The category is: " + refFive.category);


refFive.bookId = 5;
refFive.title = "Atomic Habits";
refFive.author = "James Clear";
refFive.publisher = "Penguin Random House";
refFive.publicationYear = 2018;
refFive.numberOfPages = 320;
refFive.language = "English";
refFive.price = 550;
refFive.genre = "Self Improvement";
refFive.isbn = "9780735211292";
refFive.isHardcover = true;
refFive.isEbookAvailable = true;
refFive.isAudioBookAvailable = true;
refFive.rating = 4.8;
refFive.numberOfReviews = 50000;
refFive.edition = "1st";
refFive.coverColor = "White";
refFive.weight = 360;
refFive.shelfLocation = "E09";
refFive.isAvailable = true;
refFive.borrowerName = "None";
refFive.libraryName = "National Library";
refFive.countryOfPublication = "USA";
refFive.translator = "None";
refFive.category = "Productivity";

System.out.println("The bookId is: " + refFive.bookId);
System.out.println("The title is: " + refFive.title);
System.out.println("The author is: " + refFive.author);
System.out.println("The publisher is: " + refFive.publisher);
System.out.println("The publicationYear is: " + refFive.publicationYear);
System.out.println("The numberOfPages is: " + refFive.numberOfPages);
System.out.println("The language is: " + refFive.language);
System.out.println("The price is: " + refFive.price);
System.out.println("The genre is: " + refFive.genre);
System.out.println("The isbn is: " + refFive.isbn);
System.out.println("The isHardcover is: " + refFive.isHardcover);
System.out.println("The isEbookAvailable is: " + refFive.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refFive.isAudioBookAvailable);
System.out.println("The rating is: " + refFive.rating);
System.out.println("The numberOfReviews is: " + refFive.numberOfReviews);
System.out.println("The edition is: " + refFive.edition);
System.out.println("The coverColor is: " + refFive.coverColor);
System.out.println("The weight is: " + refFive.weight);
System.out.println("The shelfLocation is: " + refFive.shelfLocation);
System.out.println("The isAvailable is: " + refFive.isAvailable);
System.out.println("The borrowerName is: " + refFive.borrowerName);
System.out.println("The libraryName is: " + refFive.libraryName);
System.out.println("The countryOfPublication is: " + refFive.countryOfPublication);
System.out.println("The translator is: " + refFive.translator);
System.out.println("The category is: " + refFive.category);
Book refSix = new Book();

System.out.println("The bookId is: " + refSix.bookId);
System.out.println("The title is: " + refSix.title);
System.out.println("The author is: " + refSix.author);
System.out.println("The publisher is: " + refSix.publisher);
System.out.println("The publicationYear is: " + refSix.publicationYear);
System.out.println("The numberOfPages is: " + refSix.numberOfPages);
System.out.println("The language is: " + refSix.language);
System.out.println("The price is: " + refSix.price);
System.out.println("The genre is: " + refSix.genre);
System.out.println("The isbn is: " + refSix.isbn);
System.out.println("The isHardcover is: " + refSix.isHardcover);
System.out.println("The isEbookAvailable is: " + refSix.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refSix.isAudioBookAvailable);
System.out.println("The rating is: " + refSix.rating);
System.out.println("The numberOfReviews is: " + refSix.numberOfReviews);
System.out.println("The edition is: " + refSix.edition);
System.out.println("The coverColor is: " + refSix.coverColor);
System.out.println("The weight is: " + refSix.weight);
System.out.println("The shelfLocation is: " + refSix.shelfLocation);
System.out.println("The isAvailable is: " + refSix.isAvailable);
System.out.println("The borrowerName is: " + refSix.borrowerName);
System.out.println("The libraryName is: " + refSix.libraryName);
System.out.println("The countryOfPublication is: " + refSix.countryOfPublication);
System.out.println("The translator is: " + refSix.translator);
System.out.println("The category is: " + refSix.category);


refSix.bookId = 6;
refSix.title = "The Power of Now";
refSix.author = "Eckhart Tolle";
refSix.publisher = "New World Library";
refSix.publicationYear = 1997;
refSix.numberOfPages = 236;
refSix.language = "English";
refSix.price = 480;
refSix.genre = "Spiritual";
refSix.isbn = "9781577314806";
refSix.isHardcover = false;
refSix.isEbookAvailable = true;
refSix.isAudioBookAvailable = true;
refSix.rating = 4.6;
refSix.numberOfReviews = 20000;
refSix.edition = "1st";
refSix.coverColor = "Yellow";
refSix.weight = 310;
refSix.shelfLocation = "F02";
refSix.isAvailable = true;
refSix.borrowerName = "None";
refSix.libraryName = "Wisdom Library";
refSix.countryOfPublication = "USA";
refSix.translator = "None";
refSix.category = "Spirituality";

System.out.println("The bookId is: " + refSix.bookId);
System.out.println("The title is: " + refSix.title);
System.out.println("The author is: " + refSix.author);
System.out.println("The publisher is: " + refSix.publisher);
System.out.println("The publicationYear is: " + refSix.publicationYear);
System.out.println("The numberOfPages is: " + refSix.numberOfPages);
System.out.println("The language is: " + refSix.language);
System.out.println("The price is: " + refSix.price);
System.out.println("The genre is: " + refSix.genre);
System.out.println("The isbn is: " + refSix.isbn);
System.out.println("The isHardcover is: " + refSix.isHardcover);
System.out.println("The isEbookAvailable is: " + refSix.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refSix.isAudioBookAvailable);
System.out.println("The rating is: " + refSix.rating);
System.out.println("The numberOfReviews is: " + refSix.numberOfReviews);
System.out.println("The edition is: " + refSix.edition);
System.out.println("The coverColor is: " + refSix.coverColor);
System.out.println("The weight is: " + refSix.weight);
System.out.println("The shelfLocation is: " + refSix.shelfLocation);
System.out.println("The isAvailable is: " + refSix.isAvailable);
System.out.println("The borrowerName is: " + refSix.borrowerName);
System.out.println("The libraryName is: " + refSix.libraryName);
System.out.println("The countryOfPublication is: " + refSix.countryOfPublication);
System.out.println("The translator is: " + refSix.translator);
System.out.println("The category is: " + refSix.category);
Book refSeven = new Book();

System.out.println("The bookId is: " + refSeven.bookId);
System.out.println("The title is: " + refSeven.title);
System.out.println("The author is: " + refSeven.author);
System.out.println("The publisher is: " + refSeven.publisher);
System.out.println("The publicationYear is: " + refSeven.publicationYear);
System.out.println("The numberOfPages is: " + refSeven.numberOfPages);
System.out.println("The language is: " + refSeven.language);
System.out.println("The price is: " + refSeven.price);
System.out.println("The genre is: " + refSeven.genre);
System.out.println("The isbn is: " + refSeven.isbn);
System.out.println("The isHardcover is: " + refSeven.isHardcover);
System.out.println("The isEbookAvailable is: " + refSeven.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refSeven.isAudioBookAvailable);
System.out.println("The rating is: " + refSeven.rating);
System.out.println("The numberOfReviews is: " + refSeven.numberOfReviews);
System.out.println("The edition is: " + refSeven.edition);
System.out.println("The coverColor is: " + refSeven.coverColor);
System.out.println("The weight is: " + refSeven.weight);
System.out.println("The shelfLocation is: " + refSeven.shelfLocation);
System.out.println("The isAvailable is: " + refSeven.isAvailable);
System.out.println("The borrowerName is: " + refSeven.borrowerName);
System.out.println("The libraryName is: " + refSeven.libraryName);
System.out.println("The countryOfPublication is: " + refSeven.countryOfPublication);
System.out.println("The translator is: " + refSeven.translator);
System.out.println("The category is: " + refSeven.category);


refSeven.bookId = 7;
refSeven.title = "Ikigai";
refSeven.author = "Hector Garcia";
refSeven.publisher = "Penguin Books";
refSeven.publicationYear = 2016;
refSeven.numberOfPages = 208;
refSeven.language = "English";
refSeven.price = 390;
refSeven.genre = "Lifestyle";
refSeven.isbn = "9780143130727";
refSeven.isHardcover = false;
refSeven.isEbookAvailable = true;
refSeven.isAudioBookAvailable = true;
refSeven.rating = 4.5;
refSeven.numberOfReviews = 15000;
refSeven.edition = "1st";
refSeven.coverColor = "Light Blue";
refSeven.weight = 280;
refSeven.shelfLocation = "G04";
refSeven.isAvailable = true;
refSeven.borrowerName = "None";
refSeven.libraryName = "Community Library";
refSeven.countryOfPublication = "Japan";
refSeven.translator = "Francesc Miralles";
refSeven.category = "Wellness";

System.out.println("The bookId is: " + refSeven.bookId);
System.out.println("The title is: " + refSeven.title);
System.out.println("The author is: " + refSeven.author);
System.out.println("The publisher is: " + refSeven.publisher);
System.out.println("The publicationYear is: " + refSeven.publicationYear);
System.out.println("The numberOfPages is: " + refSeven.numberOfPages);
System.out.println("The language is: " + refSeven.language);
System.out.println("The price is: " + refSeven.price);
System.out.println("The genre is: " + refSeven.genre);
System.out.println("The isbn is: " + refSeven.isbn);
System.out.println("The isHardcover is: " + refSeven.isHardcover);
System.out.println("The isEbookAvailable is: " + refSeven.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refSeven.isAudioBookAvailable);
System.out.println("The rating is: " + refSeven.rating);
System.out.println("The numberOfReviews is: " + refSeven.numberOfReviews);
System.out.println("The edition is: " + refSeven.edition);
System.out.println("The coverColor is: " + refSeven.coverColor);
System.out.println("The weight is: " + refSeven.weight);
System.out.println("The shelfLocation is: " + refSeven.shelfLocation);
System.out.println("The isAvailable is: " + refSeven.isAvailable);
System.out.println("The borrowerName is: " + refSeven.borrowerName);
System.out.println("The libraryName is: " + refSeven.libraryName);
System.out.println("The countryOfPublication is: " + refSeven.countryOfPublication);
System.out.println("The translator is: " + refSeven.translator);
System.out.println("The category is: " + refSeven.category);
Book refEight = new Book();

System.out.println("The bookId is: " + refEight.bookId);
System.out.println("The title is: " + refEight.title);
System.out.println("The author is: " + refEight.author);
System.out.println("The publisher is: " + refEight.publisher);
System.out.println("The publicationYear is: " + refEight.publicationYear);
System.out.println("The numberOfPages is: " + refEight.numberOfPages);
System.out.println("The language is: " + refEight.language);
System.out.println("The price is: " + refEight.price);
System.out.println("The genre is: " + refEight.genre);
System.out.println("The isbn is: " + refEight.isbn);
System.out.println("The isHardcover is: " + refEight.isHardcover);
System.out.println("The isEbookAvailable is: " + refEight.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refEight.isAudioBookAvailable);
System.out.println("The rating is: " + refEight.rating);
System.out.println("The numberOfReviews is: " + refEight.numberOfReviews);
System.out.println("The edition is: " + refEight.edition);
System.out.println("The coverColor is: " + refEight.coverColor);
System.out.println("The weight is: " + refEight.weight);
System.out.println("The shelfLocation is: " + refEight.shelfLocation);
System.out.println("The isAvailable is: " + refEight.isAvailable);
System.out.println("The borrowerName is: " + refEight.borrowerName);
System.out.println("The libraryName is: " + refEight.libraryName);
System.out.println("The countryOfPublication is: " + refEight.countryOfPublication);
System.out.println("The translator is: " + refEight.translator);
System.out.println("The category is: " + refEight.category);


refEight.bookId = 8;
refEight.title = "The Psychology of Money";
refEight.author = "Morgan Housel";
refEight.publisher = "Harriman House";
refEight.publicationYear = 2020;
refEight.numberOfPages = 256;
refEight.language = "English";
refEight.price = 520;
refEight.genre = "Finance";
refEight.isbn = "9780857197689";
refEight.isHardcover = true;
refEight.isEbookAvailable = true;
refEight.isAudioBookAvailable = true;
refEight.rating = 4.7;
refEight.numberOfReviews = 22000;
refEight.edition = "1st";
refEight.coverColor = "Orange";
refEight.weight = 330;
refEight.shelfLocation = "H01";
refEight.isAvailable = true;
refEight.borrowerName = "None";
refEight.libraryName = "Central Knowledge Library";
refEight.countryOfPublication = "USA";
refEight.translator = "None";
refEight.category = "Finance";

System.out.println("The bookId is: " + refEight.bookId);
System.out.println("The title is: " + refEight.title);
System.out.println("The author is: " + refEight.author);
System.out.println("The publisher is: " + refEight.publisher);
System.out.println("The publicationYear is: " + refEight.publicationYear);
System.out.println("The numberOfPages is: " + refEight.numberOfPages);
System.out.println("The language is: " + refEight.language);
System.out.println("The price is: " + refEight.price);
System.out.println("The genre is: " + refEight.genre);
System.out.println("The isbn is: " + refEight.isbn);
System.out.println("The isHardcover is: " + refEight.isHardcover);
System.out.println("The isEbookAvailable is: " + refEight.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refEight.isAudioBookAvailable);
System.out.println("The rating is: " + refEight.rating);
System.out.println("The numberOfReviews is: " + refEight.numberOfReviews);
System.out.println("The edition is: " + refEight.edition);
System.out.println("The coverColor is: " + refEight.coverColor);
System.out.println("The weight is: " + refEight.weight);
System.out.println("The shelfLocation is: " + refEight.shelfLocation);
System.out.println("The isAvailable is: " + refEight.isAvailable);
System.out.println("The borrowerName is: " + refEight.borrowerName);
System.out.println("The libraryName is: " + refEight.libraryName);
System.out.println("The countryOfPublication is: " + refEight.countryOfPublication);
System.out.println("The translator is: " + refEight.translator);
System.out.println("The category is: " + refEight.category);
Book refNine = new Book();

System.out.println("The bookId is: " + refNine.bookId);
System.out.println("The title is: " + refNine.title);
System.out.println("The author is: " + refNine.author);
System.out.println("The publisher is: " + refNine.publisher);
System.out.println("The publicationYear is: " + refNine.publicationYear);
System.out.println("The numberOfPages is: " + refNine.numberOfPages);
System.out.println("The language is: " + refNine.language);
System.out.println("The price is: " + refNine.price);
System.out.println("The genre is: " + refNine.genre);
System.out.println("The isbn is: " + refNine.isbn);
System.out.println("The isHardcover is: " + refNine.isHardcover);
System.out.println("The isEbookAvailable is: " + refNine.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refNine.isAudioBookAvailable);
System.out.println("The rating is: " + refNine.rating);
System.out.println("The numberOfReviews is: " + refNine.numberOfReviews);
System.out.println("The edition is: " + refNine.edition);
System.out.println("The coverColor is: " + refNine.coverColor);
System.out.println("The weight is: " + refNine.weight);
System.out.println("The shelfLocation is: " + refNine.shelfLocation);
System.out.println("The isAvailable is: " + refNine.isAvailable);
System.out.println("The borrowerName is: " + refNine.borrowerName);
System.out.println("The libraryName is: " + refNine.libraryName);
System.out.println("The countryOfPublication is: " + refNine.countryOfPublication);
System.out.println("The translator is: " + refNine.translator);
System.out.println("The category is: " + refNine.category);


refNine.bookId = 9;
refNine.title = "Deep Work";
refNine.author = "Cal Newport";
refNine.publisher = "Grand Central Publishing";
refNine.publicationYear = 2016;
refNine.numberOfPages = 296;
refNine.language = "English";
refNine.price = 480;
refNine.genre = "Productivity";
refNine.isbn = "9781455586691";
refNine.isHardcover = true;
refNine.isEbookAvailable = true;
refNine.isAudioBookAvailable = true;
refNine.rating = 4.6;
refNine.numberOfReviews = 18000;
refNine.edition = "1st";
refNine.coverColor = "Blue";
refNine.weight = 340;
refNine.shelfLocation = "I03";
refNine.isAvailable = true;
refNine.borrowerName = "None";
refNine.libraryName = "Modern Library";
refNine.countryOfPublication = "USA";
refNine.translator = "None";
refNine.category = "Productivity";

System.out.println("The bookId is: " + refNine.bookId);
System.out.println("The title is: " + refNine.title);
System.out.println("The author is: " + refNine.author);
System.out.println("The publisher is: " + refNine.publisher);
System.out.println("The publicationYear is: " + refNine.publicationYear);
System.out.println("The numberOfPages is: " + refNine.numberOfPages);
System.out.println("The language is: " + refNine.language);
System.out.println("The price is: " + refNine.price);
System.out.println("The genre is: " + refNine.genre);
System.out.println("The isbn is: " + refNine.isbn);
System.out.println("The isHardcover is: " + refNine.isHardcover);
System.out.println("The isEbookAvailable is: " + refNine.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refNine.isAudioBookAvailable);
System.out.println("The rating is: " + refNine.rating);
System.out.println("The numberOfReviews is: " + refNine.numberOfReviews);
System.out.println("The edition is: " + refNine.edition);
System.out.println("The coverColor is: " + refNine.coverColor);
System.out.println("The weight is: " + refNine.weight);
System.out.println("The shelfLocation is: " + refNine.shelfLocation);
System.out.println("The isAvailable is: " + refNine.isAvailable);
System.out.println("The borrowerName is: " + refNine.borrowerName);
System.out.println("The libraryName is: " + refNine.libraryName);
System.out.println("The countryOfPublication is: " + refNine.countryOfPublication);
System.out.println("The translator is: " + refNine.translator);
System.out.println("The category is: " + refNine.category);
Book refTen = new Book();

System.out.println("The bookId is: " + refTen.bookId);
System.out.println("The title is: " + refTen.title);
System.out.println("The author is: " + refTen.author);
System.out.println("The publisher is: " + refTen.publisher);
System.out.println("The publicationYear is: " + refTen.publicationYear);
System.out.println("The numberOfPages is: " + refTen.numberOfPages);
System.out.println("The language is: " + refTen.language);
System.out.println("The price is: " + refTen.price);
System.out.println("The genre is: " + refTen.genre);
System.out.println("The isbn is: " + refTen.isbn);
System.out.println("The isHardcover is: " + refTen.isHardcover);
System.out.println("The isEbookAvailable is: " + refTen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refTen.isAudioBookAvailable);
System.out.println("The rating is: " + refTen.rating);
System.out.println("The numberOfReviews is: " + refTen.numberOfReviews);
System.out.println("The edition is: " + refTen.edition);
System.out.println("The coverColor is: " + refTen.coverColor);
System.out.println("The weight is: " + refTen.weight);
System.out.println("The shelfLocation is: " + refTen.shelfLocation);
System.out.println("The isAvailable is: " + refTen.isAvailable);
System.out.println("The borrowerName is: " + refTen.borrowerName);
System.out.println("The libraryName is: " + refTen.libraryName);
System.out.println("The countryOfPublication is: " + refTen.countryOfPublication);
System.out.println("The translator is: " + refTen.translator);
System.out.println("The category is: " + refTen.category);


refTen.bookId = 10;
refTen.title = "Start With Why";
refTen.author = "Simon Sinek";
refTen.publisher = "Portfolio";
refTen.publicationYear = 2009;
refTen.numberOfPages = 256;
refTen.language = "English";
refTen.price = 470;
refTen.genre = "Leadership";
refTen.isbn = "9781591846444";
refTen.isHardcover = true;
refTen.isEbookAvailable = true;
refTen.isAudioBookAvailable = true;
refTen.rating = 4.6;
refTen.numberOfReviews = 21000;
refTen.edition = "1st";
refTen.coverColor = "Yellow";
refTen.weight = 330;
refTen.shelfLocation = "J08";
refTen.isAvailable = true;
refTen.borrowerName = "None";
refTen.libraryName = "Leadership Library";
refTen.countryOfPublication = "USA";
refTen.translator = "None";
refTen.category = "Leadership";

System.out.println("The bookId is: " + refTen.bookId);
System.out.println("The title is: " + refTen.title);
System.out.println("The author is: " + refTen.author);
System.out.println("The publisher is: " + refTen.publisher);
System.out.println("The publicationYear is: " + refTen.publicationYear);
System.out.println("The numberOfPages is: " + refTen.numberOfPages);
System.out.println("The language is: " + refTen.language);
System.out.println("The price is: " + refTen.price);
System.out.println("The genre is: " + refTen.genre);
System.out.println("The isbn is: " + refTen.isbn);
System.out.println("The isHardcover is: " + refTen.isHardcover);
System.out.println("The isEbookAvailable is: " + refTen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refTen.isAudioBookAvailable);
System.out.println("The rating is: " + refTen.rating);
System.out.println("The numberOfReviews is: " + refTen.numberOfReviews);
System.out.println("The edition is: " + refTen.edition);
System.out.println("The coverColor is: " + refTen.coverColor);
System.out.println("The weight is: " + refTen.weight);
System.out.println("The shelfLocation is: " + refTen.shelfLocation);
System.out.println("The isAvailable is: " + refTen.isAvailable);
System.out.println("The borrowerName is: " + refTen.borrowerName);
System.out.println("The libraryName is: " + refTen.libraryName);
System.out.println("The countryOfPublication is: " + refTen.countryOfPublication);
System.out.println("The translator is: " + refTen.translator);
System.out.println("The category is: " + refTen.category);
Book refEleven = new Book();

System.out.println("The bookId is: " + refEleven.bookId);
System.out.println("The title is: " + refEleven.title);
System.out.println("The author is: " + refEleven.author);
System.out.println("The publisher is: " + refEleven.publisher);
System.out.println("The publicationYear is: " + refEleven.publicationYear);
System.out.println("The numberOfPages is: " + refEleven.numberOfPages);
System.out.println("The language is: " + refEleven.language);
System.out.println("The price is: " + refEleven.price);
System.out.println("The genre is: " + refEleven.genre);
System.out.println("The isbn is: " + refEleven.isbn);
System.out.println("The isHardcover is: " + refEleven.isHardcover);
System.out.println("The isEbookAvailable is: " + refEleven.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refEleven.isAudioBookAvailable);
System.out.println("The rating is: " + refEleven.rating);
System.out.println("The numberOfReviews is: " + refEleven.numberOfReviews);
System.out.println("The edition is: " + refEleven.edition);
System.out.println("The coverColor is: " + refEleven.coverColor);
System.out.println("The weight is: " + refEleven.weight);
System.out.println("The shelfLocation is: " + refEleven.shelfLocation);
System.out.println("The isAvailable is: " + refEleven.isAvailable);
System.out.println("The borrowerName is: " + refEleven.borrowerName);
System.out.println("The libraryName is: " + refEleven.libraryName);
System.out.println("The countryOfPublication is: " + refEleven.countryOfPublication);
System.out.println("The translator is: " + refEleven.translator);
System.out.println("The category is: " + refEleven.category);


refEleven.bookId = 11;
refEleven.title = "The 7 Habits of Highly Effective People";
refEleven.author = "Stephen R. Covey";
refEleven.publisher = "Free Press";
refEleven.publicationYear = 1989;
refEleven.numberOfPages = 381;
refEleven.language = "English";
refEleven.price = 530;
refEleven.genre = "Self Development";
refEleven.isbn = "9780743269513";
refEleven.isHardcover = true;
refEleven.isEbookAvailable = true;
refEleven.isAudioBookAvailable = true;
refEleven.rating = 4.7;
refEleven.numberOfReviews = 27000;
refEleven.edition = "Revised";
refEleven.coverColor = "Red";
refEleven.weight = 360;
refEleven.shelfLocation = "K05";
refEleven.isAvailable = true;
refEleven.borrowerName = "None";
refEleven.libraryName = "Success Library";
refEleven.countryOfPublication = "USA";
refEleven.translator = "None";
refEleven.category = "Self Development";

System.out.println("The bookId is: " + refEleven.bookId);
System.out.println("The title is: " + refEleven.title);
System.out.println("The author is: " + refEleven.author);
System.out.println("The publisher is: " + refEleven.publisher);
System.out.println("The publicationYear is: " + refEleven.publicationYear);
System.out.println("The numberOfPages is: " + refEleven.numberOfPages);
System.out.println("The language is: " + refEleven.language);
System.out.println("The price is: " + refEleven.price);
System.out.println("The genre is: " + refEleven.genre);
System.out.println("The isbn is: " + refEleven.isbn);
System.out.println("The isHardcover is: " + refEleven.isHardcover);
System.out.println("The isEbookAvailable is: " + refEleven.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refEleven.isAudioBookAvailable);
System.out.println("The rating is: " + refEleven.rating);
System.out.println("The numberOfReviews is: " + refEleven.numberOfReviews);
System.out.println("The edition is: " + refEleven.edition);
System.out.println("The coverColor is: " + refEleven.coverColor);
System.out.println("The weight is: " + refEleven.weight);
System.out.println("The shelfLocation is: " + refEleven.shelfLocation);
System.out.println("The isAvailable is: " + refEleven.isAvailable);
System.out.println("The borrowerName is: " + refEleven.borrowerName);
System.out.println("The libraryName is: " + refEleven.libraryName);
System.out.println("The countryOfPublication is: " + refEleven.countryOfPublication);
System.out.println("The translator is: " + refEleven.translator);
System.out.println("The category is: " + refEleven.category);
Book refTwelve = new Book();

System.out.println("The bookId is: " + refTwelve.bookId);
System.out.println("The title is: " + refTwelve.title);
System.out.println("The author is: " + refTwelve.author);
System.out.println("The publisher is: " + refTwelve.publisher);
System.out.println("The publicationYear is: " + refTwelve.publicationYear);
System.out.println("The numberOfPages is: " + refTwelve.numberOfPages);
System.out.println("The language is: " + refTwelve.language);
System.out.println("The price is: " + refTwelve.price);
System.out.println("The genre is: " + refTwelve.genre);
System.out.println("The isbn is: " + refTwelve.isbn);
System.out.println("The isHardcover is: " + refTwelve.isHardcover);
System.out.println("The isEbookAvailable is: " + refTwelve.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refTwelve.isAudioBookAvailable);
System.out.println("The rating is: " + refTwelve.rating);
System.out.println("The numberOfReviews is: " + refTwelve.numberOfReviews);
System.out.println("The edition is: " + refTwelve.edition);
System.out.println("The coverColor is: " + refTwelve.coverColor);
System.out.println("The weight is: " + refTwelve.weight);
System.out.println("The shelfLocation is: " + refTwelve.shelfLocation);
System.out.println("The isAvailable is: " + refTwelve.isAvailable);
System.out.println("The borrowerName is: " + refTwelve.borrowerName);
System.out.println("The libraryName is: " + refTwelve.libraryName);
System.out.println("The countryOfPublication is: " + refTwelve.countryOfPublication);
System.out.println("The translator is: " + refTwelve.translator);
System.out.println("The category is: " + refTwelve.category);


refTwelve.bookId = 12;
refTwelve.title = "Can't Hurt Me";
refTwelve.author = "David Goggins";
refTwelve.publisher = "Lioncrest Publishing";
refTwelve.publicationYear = 2018;
refTwelve.numberOfPages = 364;
refTwelve.language = "English";
refTwelve.price = 540;
refTwelve.genre = "Motivation";
refTwelve.isbn = "9781544512280";
refTwelve.isHardcover = true;
refTwelve.isEbookAvailable = true;
refTwelve.isAudioBookAvailable = true;
refTwelve.rating = 4.8;
refTwelve.numberOfReviews = 30000;
refTwelve.edition = "1st";
refTwelve.coverColor = "Black";
refTwelve.weight = 380;
refTwelve.shelfLocation = "L02";
refTwelve.isAvailable = true;
refTwelve.borrowerName = "None";
refTwelve.libraryName = "Inspiration Library";
refTwelve.countryOfPublication = "USA";
refTwelve.translator = "None";
refTwelve.category = "Motivation";

System.out.println("The bookId is: " + refTwelve.bookId);
System.out.println("The title is: " + refTwelve.title);
System.out.println("The author is: " + refTwelve.author);
System.out.println("The publisher is: " + refTwelve.publisher);
System.out.println("The publicationYear is: " + refTwelve.publicationYear);
System.out.println("The numberOfPages is: " + refTwelve.numberOfPages);
System.out.println("The language is: " + refTwelve.language);
System.out.println("The price is: " + refTwelve.price);
System.out.println("The genre is: " + refTwelve.genre);
System.out.println("The isbn is: " + refTwelve.isbn);
System.out.println("The isHardcover is: " + refTwelve.isHardcover);
System.out.println("The isEbookAvailable is: " + refTwelve.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refTwelve.isAudioBookAvailable);
System.out.println("The rating is: " + refTwelve.rating);
System.out.println("The numberOfReviews is: " + refTwelve.numberOfReviews);
System.out.println("The edition is: " + refTwelve.edition);
System.out.println("The coverColor is: " + refTwelve.coverColor);
System.out.println("The weight is: " + refTwelve.weight);
System.out.println("The shelfLocation is: " + refTwelve.shelfLocation);
System.out.println("The isAvailable is: " + refTwelve.isAvailable);
System.out.println("The borrowerName is: " + refTwelve.borrowerName);
System.out.println("The libraryName is: " + refTwelve.libraryName);
System.out.println("The countryOfPublication is: " + refTwelve.countryOfPublication);
System.out.println("The translator is: " + refTwelve.translator);
System.out.println("The category is: " + refTwelve.category);
Book refThirteen = new Book();

System.out.println("The bookId is: " + refThirteen.bookId);
System.out.println("The title is: " + refThirteen.title);
System.out.println("The author is: " + refThirteen.author);
System.out.println("The publisher is: " + refThirteen.publisher);
System.out.println("The publicationYear is: " + refThirteen.publicationYear);
System.out.println("The numberOfPages is: " + refThirteen.numberOfPages);
System.out.println("The language is: " + refThirteen.language);
System.out.println("The price is: " + refThirteen.price);
System.out.println("The genre is: " + refThirteen.genre);
System.out.println("The isbn is: " + refThirteen.isbn);
System.out.println("The isHardcover is: " + refThirteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refThirteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refThirteen.isAudioBookAvailable);
System.out.println("The rating is: " + refThirteen.rating);
System.out.println("The numberOfReviews is: " + refThirteen.numberOfReviews);
System.out.println("The edition is: " + refThirteen.edition);
System.out.println("The coverColor is: " + refThirteen.coverColor);
System.out.println("The weight is: " + refThirteen.weight);
System.out.println("The shelfLocation is: " + refThirteen.shelfLocation);
System.out.println("The isAvailable is: " + refThirteen.isAvailable);
System.out.println("The borrowerName is: " + refThirteen.borrowerName);
System.out.println("The libraryName is: " + refThirteen.libraryName);
System.out.println("The countryOfPublication is: " + refThirteen.countryOfPublication);
System.out.println("The translator is: " + refThirteen.translator);
System.out.println("The category is: " + refThirteen.category);


refThirteen.bookId = 13;
refThirteen.title = "Mindset";
refThirteen.author = "Carol S. Dweck";
refThirteen.publisher = "Random House";
refThirteen.publicationYear = 2006;
refThirteen.numberOfPages = 320;
refThirteen.language = "English";
refThirteen.price = 460;
refThirteen.genre = "Psychology";
refThirteen.isbn = "9780345472328";
refThirteen.isHardcover = true;
refThirteen.isEbookAvailable = true;
refThirteen.isAudioBookAvailable = true;
refThirteen.rating = 4.6;
refThirteen.numberOfReviews = 19000;
refThirteen.edition = "1st";
refThirteen.coverColor = "White";
refThirteen.weight = 340;
refThirteen.shelfLocation = "M03";
refThirteen.isAvailable = true;
refThirteen.borrowerName = "None";
refThirteen.libraryName = "Learning Library";
refThirteen.countryOfPublication = "USA";
refThirteen.translator = "None";
refThirteen.category = "Psychology";

System.out.println("The bookId is: " + refThirteen.bookId);
System.out.println("The title is: " + refThirteen.title);
System.out.println("The author is: " + refThirteen.author);
System.out.println("The publisher is: " + refThirteen.publisher);
System.out.println("The publicationYear is: " + refThirteen.publicationYear);
System.out.println("The numberOfPages is: " + refThirteen.numberOfPages);
System.out.println("The language is: " + refThirteen.language);
System.out.println("The price is: " + refThirteen.price);
System.out.println("The genre is: " + refThirteen.genre);
System.out.println("The isbn is: " + refThirteen.isbn);
System.out.println("The isHardcover is: " + refThirteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refThirteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refThirteen.isAudioBookAvailable);
System.out.println("The rating is: " + refThirteen.rating);
System.out.println("The numberOfReviews is: " + refThirteen.numberOfReviews);
System.out.println("The edition is: " + refThirteen.edition);
System.out.println("The coverColor is: " + refThirteen.coverColor);
System.out.println("The weight is: " + refThirteen.weight);
System.out.println("The shelfLocation is: " + refThirteen.shelfLocation);
System.out.println("The isAvailable is: " + refThirteen.isAvailable);
System.out.println("The borrowerName is: " + refThirteen.borrowerName);
System.out.println("The libraryName is: " + refThirteen.libraryName);
System.out.println("The countryOfPublication is: " + refThirteen.countryOfPublication);
System.out.println("The translator is: " + refThirteen.translator);
System.out.println("The category is: " + refThirteen.category);
Book refFourteen = new Book();

System.out.println("The bookId is: " + refFourteen.bookId);
System.out.println("The title is: " + refFourteen.title);
System.out.println("The author is: " + refFourteen.author);
System.out.println("The publisher is: " + refFourteen.publisher);
System.out.println("The publicationYear is: " + refFourteen.publicationYear);
System.out.println("The numberOfPages is: " + refFourteen.numberOfPages);
System.out.println("The language is: " + refFourteen.language);
System.out.println("The price is: " + refFourteen.price);
System.out.println("The genre is: " + refFourteen.genre);
System.out.println("The isbn is: " + refFourteen.isbn);
System.out.println("The isHardcover is: " + refFourteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refFourteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refFourteen.isAudioBookAvailable);
System.out.println("The rating is: " + refFourteen.rating);
System.out.println("The numberOfReviews is: " + refFourteen.numberOfReviews);
System.out.println("The edition is: " + refFourteen.edition);
System.out.println("The coverColor is: " + refFourteen.coverColor);
System.out.println("The weight is: " + refFourteen.weight);
System.out.println("The shelfLocation is: " + refFourteen.shelfLocation);
System.out.println("The isAvailable is: " + refFourteen.isAvailable);
System.out.println("The borrowerName is: " + refFourteen.borrowerName);
System.out.println("The libraryName is: " + refFourteen.libraryName);
System.out.println("The countryOfPublication is: " + refFourteen.countryOfPublication);
System.out.println("The translator is: " + refFourteen.translator);
System.out.println("The category is: " + refFourteen.category);


refFourteen.bookId = 14;
refFourteen.title = "The Subtle Art of Not Giving a F*ck";
refFourteen.author = "Mark Manson";
refFourteen.publisher = "HarperOne";
refFourteen.publicationYear = 2016;
refFourteen.numberOfPages = 224;
refFourteen.language = "English";
refFourteen.price = 450;
refFourteen.genre = "Self Help";
refFourteen.isbn = "9780062457714";
refFourteen.isHardcover = false;
refFourteen.isEbookAvailable = true;
refFourteen.isAudioBookAvailable = true;
refFourteen.rating = 4.5;
refFourteen.numberOfReviews = 26000;
refFourteen.edition = "1st";
refFourteen.coverColor = "Orange";
refFourteen.weight = 300;
refFourteen.shelfLocation = "N06";
refFourteen.isAvailable = true;
refFourteen.borrowerName = "None";
refFourteen.libraryName = "Modern Reading Library";
refFourteen.countryOfPublication = "USA";
refFourteen.translator = "None";
refFourteen.category = "Self Help";

System.out.println("The bookId is: " + refFourteen.bookId);
System.out.println("The title is: " + refFourteen.title);
System.out.println("The author is: " + refFourteen.author);
System.out.println("The publisher is: " + refFourteen.publisher);
System.out.println("The publicationYear is: " + refFourteen.publicationYear);
System.out.println("The numberOfPages is: " + refFourteen.numberOfPages);
System.out.println("The language is: " + refFourteen.language);
System.out.println("The price is: " + refFourteen.price);
System.out.println("The genre is: " + refFourteen.genre);
System.out.println("The isbn is: " + refFourteen.isbn);
System.out.println("The isHardcover is: " + refFourteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refFourteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refFourteen.isAudioBookAvailable);
System.out.println("The rating is: " + refFourteen.rating);
System.out.println("The numberOfReviews is: " + refFourteen.numberOfReviews);
System.out.println("The edition is: " + refFourteen.edition);
System.out.println("The coverColor is: " + refFourteen.coverColor);
System.out.println("The weight is: " + refFourteen.weight);
System.out.println("The shelfLocation is: " + refFourteen.shelfLocation);
System.out.println("The isAvailable is: " + refFourteen.isAvailable);
System.out.println("The borrowerName is: " + refFourteen.borrowerName);
System.out.println("The libraryName is: " + refFourteen.libraryName);
System.out.println("The countryOfPublication is: " + refFourteen.countryOfPublication);
System.out.println("The translator is: " + refFourteen.translator);
System.out.println("The category is: " + refFourteen.category);
Book refFifteen = new Book();

System.out.println("The bookId is: " + refFifteen.bookId);
System.out.println("The title is: " + refFifteen.title);
System.out.println("The author is: " + refFifteen.author);
System.out.println("The publisher is: " + refFifteen.publisher);
System.out.println("The publicationYear is: " + refFifteen.publicationYear);
System.out.println("The numberOfPages is: " + refFifteen.numberOfPages);
System.out.println("The language is: " + refFifteen.language);
System.out.println("The price is: " + refFifteen.price);
System.out.println("The genre is: " + refFifteen.genre);
System.out.println("The isbn is: " + refFifteen.isbn);
System.out.println("The isHardcover is: " + refFifteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refFifteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refFifteen.isAudioBookAvailable);
System.out.println("The rating is: " + refFifteen.rating);
System.out.println("The numberOfReviews is: " + refFifteen.numberOfReviews);
System.out.println("The edition is: " + refFifteen.edition);
System.out.println("The coverColor is: " + refFifteen.coverColor);
System.out.println("The weight is: " + refFifteen.weight);
System.out.println("The shelfLocation is: " + refFifteen.shelfLocation);
System.out.println("The isAvailable is: " + refFifteen.isAvailable);
System.out.println("The borrowerName is: " + refFifteen.borrowerName);
System.out.println("The libraryName is: " + refFifteen.libraryName);
System.out.println("The countryOfPublication is: " + refFifteen.countryOfPublication);
System.out.println("The translator is: " + refFifteen.translator);
System.out.println("The category is: " + refFifteen.category);


refFifteen.bookId = 15;
refFifteen.title = "Zero to One";
refFifteen.author = "Peter Thiel";
refFifteen.publisher = "Crown Business";
refFifteen.publicationYear = 2014;
refFifteen.numberOfPages = 224;
refFifteen.language = "English";
refFifteen.price = 490;
refFifteen.genre = "Business";
refFifteen.isbn = "9780804139298";
refFifteen.isHardcover = true;
refFifteen.isEbookAvailable = true;
refFifteen.isAudioBookAvailable = true;
refFifteen.rating = 4.5;
refFifteen.numberOfReviews = 17000;
refFifteen.edition = "1st";
refFifteen.coverColor = "Blue";
refFifteen.weight = 310;
refFifteen.shelfLocation = "O04";
refFifteen.isAvailable = true;
refFifteen.borrowerName = "None";
refFifteen.libraryName = "Startup Library";
refFifteen.countryOfPublication = "USA";
refFifteen.translator = "None";
refFifteen.category = "Business";

System.out.println("The bookId is: " + refFifteen.bookId);
System.out.println("The title is: " + refFifteen.title);
System.out.println("The author is: " + refFifteen.author);
System.out.println("The publisher is: " + refFifteen.publisher);
System.out.println("The publicationYear is: " + refFifteen.publicationYear);
System.out.println("The numberOfPages is: " + refFifteen.numberOfPages);
System.out.println("The language is: " + refFifteen.language);
System.out.println("The price is: " + refFifteen.price);
System.out.println("The genre is: " + refFifteen.genre);
System.out.println("The isbn is: " + refFifteen.isbn);
System.out.println("The isHardcover is: " + refFifteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refFifteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refFifteen.isAudioBookAvailable);
System.out.println("The rating is: " + refFifteen.rating);
System.out.println("The numberOfReviews is: " + refFifteen.numberOfReviews);
System.out.println("The edition is: " + refFifteen.edition);
System.out.println("The coverColor is: " + refFifteen.coverColor);
System.out.println("The weight is: " + refFifteen.weight);
System.out.println("The shelfLocation is: " + refFifteen.shelfLocation);
System.out.println("The isAvailable is: " + refFifteen.isAvailable);
System.out.println("The borrowerName is: " + refFifteen.borrowerName);
System.out.println("The libraryName is: " + refFifteen.libraryName);
System.out.println("The countryOfPublication is: " + refFifteen.countryOfPublication);
System.out.println("The translator is: " + refFifteen.translator);
System.out.println("The category is: " + refFifteen.category);
Book refSixteen = new Book();

System.out.println("The bookId is: " + refSixteen.bookId);
System.out.println("The title is: " + refSixteen.title);
System.out.println("The author is: " + refSixteen.author);
System.out.println("The publisher is: " + refSixteen.publisher);
System.out.println("The publicationYear is: " + refSixteen.publicationYear);
System.out.println("The numberOfPages is: " + refSixteen.numberOfPages);
System.out.println("The language is: " + refSixteen.language);
System.out.println("The price is: " + refSixteen.price);
System.out.println("The genre is: " + refSixteen.genre);
System.out.println("The isbn is: " + refSixteen.isbn);
System.out.println("The isHardcover is: " + refSixteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refSixteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refSixteen.isAudioBookAvailable);
System.out.println("The rating is: " + refSixteen.rating);
System.out.println("The numberOfReviews is: " + refSixteen.numberOfReviews);
System.out.println("The edition is: " + refSixteen.edition);
System.out.println("The coverColor is: " + refSixteen.coverColor);
System.out.println("The weight is: " + refSixteen.weight);
System.out.println("The shelfLocation is: " + refSixteen.shelfLocation);
System.out.println("The isAvailable is: " + refSixteen.isAvailable);
System.out.println("The borrowerName is: " + refSixteen.borrowerName);
System.out.println("The libraryName is: " + refSixteen.libraryName);
System.out.println("The countryOfPublication is: " + refSixteen.countryOfPublication);
System.out.println("The translator is: " + refSixteen.translator);
System.out.println("The category is: " + refSixteen.category);


refSixteen.bookId = 16;
refSixteen.title = "Good to Great";
refSixteen.author = "Jim Collins";
refSixteen.publisher = "HarperBusiness";
refSixteen.publicationYear = 2001;
refSixteen.numberOfPages = 320;
refSixteen.language = "English";
refSixteen.price = 500;
refSixteen.genre = "Business";
refSixteen.isbn = "9780066620992";
refSixteen.isHardcover = true;
refSixteen.isEbookAvailable = true;
refSixteen.isAudioBookAvailable = true;
refSixteen.rating = 4.6;
refSixteen.numberOfReviews = 21000;
refSixteen.edition = "1st";
refSixteen.coverColor = "White";
refSixteen.weight = 340;
refSixteen.shelfLocation = "P07";
refSixteen.isAvailable = true;
refSixteen.borrowerName = "None";
refSixteen.libraryName = "Business Library";
refSixteen.countryOfPublication = "USA";
refSixteen.translator = "None";
refSixteen.category = "Business";

System.out.println("The bookId is: " + refSixteen.bookId);
System.out.println("The title is: " + refSixteen.title);
System.out.println("The author is: " + refSixteen.author);
System.out.println("The publisher is: " + refSixteen.publisher);
System.out.println("The publicationYear is: " + refSixteen.publicationYear);
System.out.println("The numberOfPages is: " + refSixteen.numberOfPages);
System.out.println("The language is: " + refSixteen.language);
System.out.println("The price is: " + refSixteen.price);
System.out.println("The genre is: " + refSixteen.genre);
System.out.println("The isbn is: " + refSixteen.isbn);
System.out.println("The isHardcover is: " + refSixteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refSixteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refSixteen.isAudioBookAvailable);
System.out.println("The rating is: " + refSixteen.rating);
System.out.println("The numberOfReviews is: " + refSixteen.numberOfReviews);
System.out.println("The edition is: " + refSixteen.edition);
System.out.println("The coverColor is: " + refSixteen.coverColor);
System.out.println("The weight is: " + refSixteen.weight);
System.out.println("The shelfLocation is: " + refSixteen.shelfLocation);
System.out.println("The isAvailable is: " + refSixteen.isAvailable);
System.out.println("The borrowerName is: " + refSixteen.borrowerName);
System.out.println("The libraryName is: " + refSixteen.libraryName);
System.out.println("The countryOfPublication is: " + refSixteen.countryOfPublication);
System.out.println("The translator is: " + refSixteen.translator);
System.out.println("The category is: " + refSixteen.category);
Book refSeventeen = new Book();

System.out.println("The bookId is: " + refSeventeen.bookId);
System.out.println("The title is: " + refSeventeen.title);
System.out.println("The author is: " + refSeventeen.author);
System.out.println("The publisher is: " + refSeventeen.publisher);
System.out.println("The publicationYear is: " + refSeventeen.publicationYear);
System.out.println("The numberOfPages is: " + refSeventeen.numberOfPages);
System.out.println("The language is: " + refSeventeen.language);
System.out.println("The price is: " + refSeventeen.price);
System.out.println("The genre is: " + refSeventeen.genre);
System.out.println("The isbn is: " + refSeventeen.isbn);
System.out.println("The isHardcover is: " + refSeventeen.isHardcover);
System.out.println("The isEbookAvailable is: " + refSeventeen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refSeventeen.isAudioBookAvailable);
System.out.println("The rating is: " + refSeventeen.rating);
System.out.println("The numberOfReviews is: " + refSeventeen.numberOfReviews);
System.out.println("The edition is: " + refSeventeen.edition);
System.out.println("The coverColor is: " + refSeventeen.coverColor);
System.out.println("The weight is: " + refSeventeen.weight);
System.out.println("The shelfLocation is: " + refSeventeen.shelfLocation);
System.out.println("The isAvailable is: " + refSeventeen.isAvailable);
System.out.println("The borrowerName is: " + refSeventeen.borrowerName);
System.out.println("The libraryName is: " + refSeventeen.libraryName);
System.out.println("The countryOfPublication is: " + refSeventeen.countryOfPublication);
System.out.println("The translator is: " + refSeventeen.translator);
System.out.println("The category is: " + refSeventeen.category);


refSeventeen.bookId = 17;
refSeventeen.title = "Thinking, Fast and Slow";
refSeventeen.author = "Daniel Kahneman";
refSeventeen.publisher = "Farrar, Straus and Giroux";
refSeventeen.publicationYear = 2011;
refSeventeen.numberOfPages = 499;
refSeventeen.language = "English";
refSeventeen.price = 520;
refSeventeen.genre = "Psychology";
refSeventeen.isbn = "9780374533557";
refSeventeen.isHardcover = true;
refSeventeen.isEbookAvailable = true;
refSeventeen.isAudioBookAvailable = true;
refSeventeen.rating = 4.6;
refSeventeen.numberOfReviews = 24000;
refSeventeen.edition = "1st";
refSeventeen.coverColor = "White";
refSeventeen.weight = 400;
refSeventeen.shelfLocation = "Q02";
refSeventeen.isAvailable = true;
refSeventeen.borrowerName = "None";
refSeventeen.libraryName = "Cognitive Library";
refSeventeen.countryOfPublication = "USA";
refSeventeen.translator = "None";
refSeventeen.category = "Psychology";

System.out.println("The bookId is: " + refSeventeen.bookId);
System.out.println("The title is: " + refSeventeen.title);
System.out.println("The author is: " + refSeventeen.author);
System.out.println("The publisher is: " + refSeventeen.publisher);
System.out.println("The publicationYear is: " + refSeventeen.publicationYear);
System.out.println("The numberOfPages is: " + refSeventeen.numberOfPages);
System.out.println("The language is: " + refSeventeen.language);
System.out.println("The price is: " + refSeventeen.price);
System.out.println("The genre is: " + refSeventeen.genre);
System.out.println("The isbn is: " + refSeventeen.isbn);
System.out.println("The isHardcover is: " + refSeventeen.isHardcover);
System.out.println("The isEbookAvailable is: " + refSeventeen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refSeventeen.isAudioBookAvailable);
System.out.println("The rating is: " + refSeventeen.rating);
System.out.println("The numberOfReviews is: " + refSeventeen.numberOfReviews);
System.out.println("The edition is: " + refSeventeen.edition);
System.out.println("The coverColor is: " + refSeventeen.coverColor);
System.out.println("The weight is: " + refSeventeen.weight);
System.out.println("The shelfLocation is: " + refSeventeen.shelfLocation);
System.out.println("The isAvailable is: " + refSeventeen.isAvailable);
System.out.println("The borrowerName is: " + refSeventeen.borrowerName);
System.out.println("The libraryName is: " + refSeventeen.libraryName);
System.out.println("The countryOfPublication is: " + refSeventeen.countryOfPublication);
System.out.println("The translator is: " + refSeventeen.translator);
System.out.println("The category is: " + refSeventeen.category);
Book refEighteen = new Book();

System.out.println("The bookId is: " + refEighteen.bookId);
System.out.println("The title is: " + refEighteen.title);
System.out.println("The author is: " + refEighteen.author);
System.out.println("The publisher is: " + refEighteen.publisher);
System.out.println("The publicationYear is: " + refEighteen.publicationYear);
System.out.println("The numberOfPages is: " + refEighteen.numberOfPages);
System.out.println("The language is: " + refEighteen.language);
System.out.println("The price is: " + refEighteen.price);
System.out.println("The genre is: " + refEighteen.genre);
System.out.println("The isbn is: " + refEighteen.isbn);
System.out.println("The isHardcover is: " + refEighteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refEighteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refEighteen.isAudioBookAvailable);
System.out.println("The rating is: " + refEighteen.rating);
System.out.println("The numberOfReviews is: " + refEighteen.numberOfReviews);
System.out.println("The edition is: " + refEighteen.edition);
System.out.println("The coverColor is: " + refEighteen.coverColor);
System.out.println("The weight is: " + refEighteen.weight);
System.out.println("The shelfLocation is: " + refEighteen.shelfLocation);
System.out.println("The isAvailable is: " + refEighteen.isAvailable);
System.out.println("The borrowerName is: " + refEighteen.borrowerName);
System.out.println("The libraryName is: " + refEighteen.libraryName);
System.out.println("The countryOfPublication is: " + refEighteen.countryOfPublication);
System.out.println("The translator is: " + refEighteen.translator);
System.out.println("The category is: " + refEighteen.category);


refEighteen.bookId = 18;
refEighteen.title = "The Lean Startup";
refEighteen.author = "Eric Ries";
refEighteen.publisher = "Crown Business";
refEighteen.publicationYear = 2011;
refEighteen.numberOfPages = 336;
refEighteen.language = "English";
refEighteen.price = 510;
refEighteen.genre = "Startup";
refEighteen.isbn = "9780307887894";
refEighteen.isHardcover = true;
refEighteen.isEbookAvailable = true;
refEighteen.isAudioBookAvailable = true;
refEighteen.rating = 4.6;
refEighteen.numberOfReviews = 23000;
refEighteen.edition = "1st";
refEighteen.coverColor = "White";
refEighteen.weight = 350;
refEighteen.shelfLocation = "R05";
refEighteen.isAvailable = true;
refEighteen.borrowerName = "None";
refEighteen.libraryName = "Startup Library";
refEighteen.countryOfPublication = "USA";
refEighteen.translator = "None";
refEighteen.category = "Startup";

System.out.println("The bookId is: " + refEighteen.bookId);
System.out.println("The title is: " + refEighteen.title);
System.out.println("The author is: " + refEighteen.author);
System.out.println("The publisher is: " + refEighteen.publisher);
System.out.println("The publicationYear is: " + refEighteen.publicationYear);
System.out.println("The numberOfPages is: " + refEighteen.numberOfPages);
System.out.println("The language is: " + refEighteen.language);
System.out.println("The price is: " + refEighteen.price);
System.out.println("The genre is: " + refEighteen.genre);
System.out.println("The isbn is: " + refEighteen.isbn);
System.out.println("The isHardcover is: " + refEighteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refEighteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refEighteen.isAudioBookAvailable);
System.out.println("The rating is: " + refEighteen.rating);
System.out.println("The numberOfReviews is: " + refEighteen.numberOfReviews);
System.out.println("The edition is: " + refEighteen.edition);
System.out.println("The coverColor is: " + refEighteen.coverColor);
System.out.println("The weight is: " + refEighteen.weight);
System.out.println("The shelfLocation is: " + refEighteen.shelfLocation);
System.out.println("The isAvailable is: " + refEighteen.isAvailable);
System.out.println("The borrowerName is: " + refEighteen.borrowerName);
System.out.println("The libraryName is: " + refEighteen.libraryName);
System.out.println("The countryOfPublication is: " + refEighteen.countryOfPublication);
System.out.println("The translator is: " + refEighteen.translator);
System.out.println("The category is: " + refEighteen.category);
Book refNineteen = new Book();

System.out.println("The bookId is: " + refNineteen.bookId);
System.out.println("The title is: " + refNineteen.title);
System.out.println("The author is: " + refNineteen.author);
System.out.println("The publisher is: " + refNineteen.publisher);
System.out.println("The publicationYear is: " + refNineteen.publicationYear);
System.out.println("The numberOfPages is: " + refNineteen.numberOfPages);
System.out.println("The language is: " + refNineteen.language);
System.out.println("The price is: " + refNineteen.price);
System.out.println("The genre is: " + refNineteen.genre);
System.out.println("The isbn is: " + refNineteen.isbn);
System.out.println("The isHardcover is: " + refNineteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refNineteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refNineteen.isAudioBookAvailable);
System.out.println("The rating is: " + refNineteen.rating);
System.out.println("The numberOfReviews is: " + refNineteen.numberOfReviews);
System.out.println("The edition is: " + refNineteen.edition);
System.out.println("The coverColor is: " + refNineteen.coverColor);
System.out.println("The weight is: " + refNineteen.weight);
System.out.println("The shelfLocation is: " + refNineteen.shelfLocation);
System.out.println("The isAvailable is: " + refNineteen.isAvailable);
System.out.println("The borrowerName is: " + refNineteen.borrowerName);
System.out.println("The libraryName is: " + refNineteen.libraryName);
System.out.println("The countryOfPublication is: " + refNineteen.countryOfPublication);
System.out.println("The translator is: " + refNineteen.translator);
System.out.println("The category is: " + refNineteen.category);


refNineteen.bookId = 19;
refNineteen.title = "Sapiens";
refNineteen.author = "Yuval Noah Harari";
refNineteen.publisher = "Harper";
refNineteen.publicationYear = 2011;
refNineteen.numberOfPages = 443;
refNineteen.language = "English";
refNineteen.price = 560;
refNineteen.genre = "History";
refNineteen.isbn = "9780062316097";
refNineteen.isHardcover = true;
refNineteen.isEbookAvailable = true;
refNineteen.isAudioBookAvailable = true;
refNineteen.rating = 4.7;
refNineteen.numberOfReviews = 35000;
refNineteen.edition = "1st";
refNineteen.coverColor = "Brown";
refNineteen.weight = 420;
refNineteen.shelfLocation = "S03";
refNineteen.isAvailable = true;
refNineteen.borrowerName = "None";
refNineteen.libraryName = "World History Library";
refNineteen.countryOfPublication = "Israel";
refNineteen.translator = "None";
refNineteen.category = "History";

System.out.println("The bookId is: " + refNineteen.bookId);
System.out.println("The title is: " + refNineteen.title);
System.out.println("The author is: " + refNineteen.author);
System.out.println("The publisher is: " + refNineteen.publisher);
System.out.println("The publicationYear is: " + refNineteen.publicationYear);
System.out.println("The numberOfPages is: " + refNineteen.numberOfPages);
System.out.println("The language is: " + refNineteen.language);
System.out.println("The price is: " + refNineteen.price);
System.out.println("The genre is: " + refNineteen.genre);
System.out.println("The isbn is: " + refNineteen.isbn);
System.out.println("The isHardcover is: " + refNineteen.isHardcover);
System.out.println("The isEbookAvailable is: " + refNineteen.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refNineteen.isAudioBookAvailable);
System.out.println("The rating is: " + refNineteen.rating);
System.out.println("The numberOfReviews is: " + refNineteen.numberOfReviews);
System.out.println("The edition is: " + refNineteen.edition);
System.out.println("The coverColor is: " + refNineteen.coverColor);
System.out.println("The weight is: " + refNineteen.weight);
System.out.println("The shelfLocation is: " + refNineteen.shelfLocation);
System.out.println("The isAvailable is: " + refNineteen.isAvailable);
System.out.println("The borrowerName is: " + refNineteen.borrowerName);
System.out.println("The libraryName is: " + refNineteen.libraryName);
System.out.println("The countryOfPublication is: " + refNineteen.countryOfPublication);
System.out.println("The translator is: " + refNineteen.translator);
System.out.println("The category is: " + refNineteen.category);
Book refTwenty = new Book();

System.out.println("The bookId is: " + refTwenty.bookId);
System.out.println("The title is: " + refTwenty.title);
System.out.println("The author is: " + refTwenty.author);
System.out.println("The publisher is: " + refTwenty.publisher);
System.out.println("The publicationYear is: " + refTwenty.publicationYear);
System.out.println("The numberOfPages is: " + refTwenty.numberOfPages);
System.out.println("The language is: " + refTwenty.language);
System.out.println("The price is: " + refTwenty.price);
System.out.println("The genre is: " + refTwenty.genre);
System.out.println("The isbn is: " + refTwenty.isbn);
System.out.println("The isHardcover is: " + refTwenty.isHardcover);
System.out.println("The isEbookAvailable is: " + refTwenty.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refTwenty.isAudioBookAvailable);
System.out.println("The rating is: " + refTwenty.rating);
System.out.println("The numberOfReviews is: " + refTwenty.numberOfReviews);
System.out.println("The edition is: " + refTwenty.edition);
System.out.println("The coverColor is: " + refTwenty.coverColor);
System.out.println("The weight is: " + refTwenty.weight);
System.out.println("The shelfLocation is: " + refTwenty.shelfLocation);
System.out.println("The isAvailable is: " + refTwenty.isAvailable);
System.out.println("The borrowerName is: " + refTwenty.borrowerName);
System.out.println("The libraryName is: " + refTwenty.libraryName);
System.out.println("The countryOfPublication is: " + refTwenty.countryOfPublication);
System.out.println("The translator is: " + refTwenty.translator);
System.out.println("The category is: " + refTwenty.category);


refTwenty.bookId = 20;
refTwenty.title = "Homo Deus";
refTwenty.author = "Yuval Noah Harari";
refTwenty.publisher = "Harper";
refTwenty.publicationYear = 2015;
refTwenty.numberOfPages = 450;
refTwenty.language = "English";
refTwenty.price = 580;
refTwenty.genre = "History";
refTwenty.isbn = "9780062464316";
refTwenty.isHardcover = true;
refTwenty.isEbookAvailable = true;
refTwenty.isAudioBookAvailable = true;
refTwenty.rating = 4.7;
refTwenty.numberOfReviews = 28000;
refTwenty.edition = "1st";
refTwenty.coverColor = "Black";
refTwenty.weight = 430;
refTwenty.shelfLocation = "T01";
refTwenty.isAvailable = true;
refTwenty.borrowerName = "None";
refTwenty.libraryName = "Future Studies Library";
refTwenty.countryOfPublication = "Israel";
refTwenty.translator = "None";
refTwenty.category = "History";

System.out.println("The bookId is: " + refTwenty.bookId);
System.out.println("The title is: " + refTwenty.title);
System.out.println("The author is: " + refTwenty.author);
System.out.println("The publisher is: " + refTwenty.publisher);
System.out.println("The publicationYear is: " + refTwenty.publicationYear);
System.out.println("The numberOfPages is: " + refTwenty.numberOfPages);
System.out.println("The language is: " + refTwenty.language);
System.out.println("The price is: " + refTwenty.price);
System.out.println("The genre is: " + refTwenty.genre);
System.out.println("The isbn is: " + refTwenty.isbn);
System.out.println("The isHardcover is: " + refTwenty.isHardcover);
System.out.println("The isEbookAvailable is: " + refTwenty.isEbookAvailable);
System.out.println("The isAudioBookAvailable is: " + refTwenty.isAudioBookAvailable);
System.out.println("The rating is: " + refTwenty.rating);
System.out.println("The numberOfReviews is: " + refTwenty.numberOfReviews);
System.out.println("The edition is: " + refTwenty.edition);
System.out.println("The coverColor is: " + refTwenty.coverColor);
System.out.println("The weight is: " + refTwenty.weight);
System.out.println("The shelfLocation is: " + refTwenty.shelfLocation);
System.out.println("The isAvailable is: " + refTwenty.isAvailable);
System.out.println("The borrowerName is: " + refTwenty.borrowerName);
System.out.println("The libraryName is: " + refTwenty.libraryName);
System.out.println("The countryOfPublication is: " + refTwenty.countryOfPublication);
System.out.println("The translator is: " + refTwenty.translator);
System.out.println("The category is: " + refTwenty.category);
}
}