class CarExecutor{
public static void main(String[] args){

		Car refOne = new Car();
		System.out.println("The carModel is: " + refOne.carModel);
		System.out.println("The carColor is: " + refOne.carColor);
		System.out.println("The manufacturingYear is: " + refOne.manufacturingYear);
		System.out.println("The price is: " + refOne.price);
		System.out.println("The fuelType is: " + refOne.fuelType);
		System.out.println("The seatingCapacity is: " + refOne.seatingCapacity);
		System.out.println("The engineCapacity is: " + refOne.engineCapacity);
		System.out.println("The transmissionType is: " + refOne.transmissionType);
		System.out.println("The numberOfDoors is: " + refOne.numberOfDoors);
		System.out.println("The isAutomatic is: " + refOne.isAutomatic);
		System.out.println("The hasSunroof is: " + refOne.hasSunroof);
		System.out.println("The hasAirbags is: " + refOne.hasAirbags);
		System.out.println("The hasABS is: " + refOne.hasABS);
		System.out.println("The mileage is: " + refOne.mileage);
		System.out.println("The registrationNumber is: " + refOne.registrationNumber);
		System.out.println("The ownerName is: " + refOne.ownerName);
		System.out.println("The insuranceProviderDDD is: " + refOne.insuranceProvider);
		System.out.println("The insuranceExpiryDate is: " + refOne.insuranceExpiryDate);
		System.out.println("The tyreType is: " + refOne.tyreType);
		System.out.println("The batteryType is: " + refOne.batteryType);
		System.out.println("The navigationSystem is: " + refOne.navigationSystem);
		System.out.println("The musicSystem is: " + refOne.musicSystem);
		System.out.println("The isElectric is: " + refOne.isElectric);
		
		refOne.carId = 1;
        refOne.carBrand = "Audi";
        refOne.carModel = "A6";
        refOne.carColor = "Black";
        refOne.manufacturingYear = 2023;
        refOne.price = 6500000;
        refOne.fuelType = "Petrol";
        refOne.seatingCapacity = 5;
        refOne.engineCapacity = 2.0;
        refOne.transmissionType = "Automatic";
        refOne.numberOfDoors = 4;
        refOne.isAutomatic = true;
        refOne.hasSunroof = true;
        refOne.hasAirbags = true;
        refOne.hasABS = true;
        refOne.mileage = 14.5;
        refOne.registrationNumber = "KA01AB1234";
        refOne.ownerName = "Rahul";
        refOne.insuranceProvider = "ICICI";
        refOne.insuranceExpiryDate = "2027-05-10";
        refOne.tyreType = "Tubeless";
        refOne.batteryType = "Lithium";
        refOne.navigationSystem = "Built-in GPS";
        refOne.musicSystem = "Bose";
        refOne.isElectric = false;
		System.out.println("The carId is: " + refOne.carId);
		System.out.println("The carBrand is: " + refOne.carBrand);
		System.out.println("The carModel is: " + refOne.carModel);
		System.out.println("The carColor is: " + refOne.carColor);
		System.out.println("The manufacturingYear is: " + refOne.manufacturingYear);
		System.out.println("The price is: " + refOne.price);
		System.out.println("The fuelType is: " + refOne.fuelType);
		System.out.println("The seatingCapacity is: " + refOne.seatingCapacity);
		System.out.println("The engineCapacity is: " + refOne.engineCapacity);
		System.out.println("The transmissionType is: " + refOne.transmissionType);
		System.out.println("The numberOfDoors is: " + refOne.numberOfDoors);
		System.out.println("The isAutomatic is: " + refOne.isAutomatic);
		System.out.println("The hasSunroof is: " + refOne.hasSunroof);
		System.out.println("The hasAirbags is: " + refOne.hasAirbags);
		System.out.println("The hasABS is: " + refOne.hasABS);
		System.out.println("The mileage is: " + refOne.mileage);
		System.out.println("The registrationNumber is: " + refOne.registrationNumber);
		System.out.println("The ownerName is: " + refOne.ownerName);
		System.out.println("The insuranceProvider is: " + refOne.insuranceProvider);
		System.out.println("The insuranceExpiryDate is: " + refOne.insuranceExpiryDate);
		System.out.println("The tyreType is: " + refOne.tyreType);
		System.out.println("The batteryType is: " + refOne.batteryType);
		System.out.println("The navigationSystem is: " + refOne.navigationSystem);
		System.out.println("The musicSystem is: " + refOne.musicSystem);
		System.out.println("The isElectric is: " + refOne.isElectric);
		
		Car refTwo = new Car();

System.out.println("The carModel is: " + refTwo.carModel);
System.out.println("The carColor is: " + refTwo.carColor);
System.out.println("The manufacturingYear is: " + refTwo.manufacturingYear);
System.out.println("The price is: " + refTwo.price);
System.out.println("The fuelType is: " + refTwo.fuelType);
System.out.println("The seatingCapacity is: " + refTwo.seatingCapacity);
System.out.println("The engineCapacity is: " + refTwo.engineCapacity);
System.out.println("The transmissionType is: " + refTwo.transmissionType);
System.out.println("The numberOfDoors is: " + refTwo.numberOfDoors);
System.out.println("The isAutomatic is: " + refTwo.isAutomatic);
System.out.println("The hasSunroof is: " + refTwo.hasSunroof);
System.out.println("The hasAirbags is: " + refTwo.hasAirbags);
System.out.println("The hasABS is: " + refTwo.hasABS);
System.out.println("The mileage is: " + refTwo.mileage);
System.out.println("The registrationNumber is: " + refTwo.registrationNumber);
System.out.println("The ownerName is: " + refTwo.ownerName);
System.out.println("The insuranceProvider is: " + refTwo.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refTwo.insuranceExpiryDate);
System.out.println("The tyreType is: " + refTwo.tyreType);
System.out.println("The batteryType is: " + refTwo.batteryType);
System.out.println("The navigationSystem is: " + refTwo.navigationSystem);
System.out.println("The musicSystem is: " + refTwo.musicSystem);
System.out.println("The isElectric is: " + refTwo.isElectric);

refTwo.carId = 2;
refTwo.carBrand = "BMW";
refTwo.carModel = "X5";
refTwo.carColor = "White";
refTwo.manufacturingYear = 2022;
refTwo.price = 7200000;
refTwo.fuelType = "Diesel";
refTwo.seatingCapacity = 5;
refTwo.engineCapacity = 3.0;
refTwo.transmissionType = "Automatic";
refTwo.numberOfDoors = 4;
refTwo.isAutomatic = true;
refTwo.hasSunroof = true;
refTwo.hasAirbags = true;
refTwo.hasABS = true;
refTwo.mileage = 13.5;
refTwo.registrationNumber = "KA02CD5678";
refTwo.ownerName = "Arjun";
refTwo.insuranceProvider = "HDFC";
refTwo.insuranceExpiryDate = "2026-08-12";
refTwo.tyreType = "Tubeless";
refTwo.batteryType = "Lithium";
refTwo.navigationSystem = "Built-in GPS";
refTwo.musicSystem = "Sony";
refTwo.isElectric = false;

System.out.println("The carId is: " + refTwo.carId);
System.out.println("The carBrand is: " + refTwo.carBrand);
System.out.println("The carModel is: " + refTwo.carModel);
System.out.println("The carColor is: " + refTwo.carColor);
System.out.println("The manufacturingYear is: " + refTwo.manufacturingYear);
System.out.println("The price is: " + refTwo.price);
System.out.println("The fuelType is: " + refTwo.fuelType);
System.out.println("The seatingCapacity is: " + refTwo.seatingCapacity);
System.out.println("The engineCapacity is: " + refTwo.engineCapacity);
System.out.println("The transmissionType is: " + refTwo.transmissionType);
System.out.println("The numberOfDoors is: " + refTwo.numberOfDoors);
System.out.println("The isAutomatic is: " + refTwo.isAutomatic);
System.out.println("The hasSunroof is: " + refTwo.hasSunroof);
System.out.println("The hasAirbags is: " + refTwo.hasAirbags);
System.out.println("The hasABS is: " + refTwo.hasABS);
System.out.println("The mileage is: " + refTwo.mileage);
System.out.println("The registrationNumber is: " + refTwo.registrationNumber);
System.out.println("The ownerName is: " + refTwo.ownerName);
System.out.println("The insuranceProvider is: " + refTwo.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refTwo.insuranceExpiryDate);
System.out.println("The tyreType is: " + refTwo.tyreType);
System.out.println("The batteryType is: " + refTwo.batteryType);
System.out.println("The navigationSystem is: " + refTwo.navigationSystem);
System.out.println("The musicSystem is: " + refTwo.musicSystem);
System.out.println("The isElectric is: " + refTwo.isElectric);
Car refThree = new Car();
System.out.println("The carId is: " + refThree.carId);
System.out.println("The carBrand is: " + refThree.carBrand);
System.out.println("The carModel is: " + refThree.carModel);
System.out.println("The carColor is: " + refThree.carColor);
System.out.println("The manufacturingYear is: " + refThree.manufacturingYear);
System.out.println("The price is: " + refThree.price);
System.out.println("The fuelType is: " + refThree.fuelType);
System.out.println("The seatingCapacity is: " + refThree.seatingCapacity);
System.out.println("The engineCapacity is: " + refThree.engineCapacity);
System.out.println("The transmissionType is: " + refThree.transmissionType);
System.out.println("The numberOfDoors is: " + refThree.numberOfDoors);
System.out.println("The isAutomatic is: " + refThree.isAutomatic);
System.out.println("The hasSunroof is: " + refThree.hasSunroof);
System.out.println("The hasAirbags is: " + refThree.hasAirbags);
System.out.println("The hasABS is: " + refThree.hasABS);
System.out.println("The mileage is: " + refThree.mileage);
System.out.println("The registrationNumber is: " + refThree.registrationNumber);
System.out.println("The ownerName is: " + refThree.ownerName);
System.out.println("The insuranceProvider is: " + refThree.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refThree.insuranceExpiryDate);
System.out.println("The tyreType is: " + refThree.tyreType);
System.out.println("The batteryType is: " + refThree.batteryType);
System.out.println("The navigationSystem is: " + refThree.navigationSystem);
System.out.println("The musicSystem is: " + refThree.musicSystem);
System.out.println("The isElectric is: " + refThree.isElectric);

refThree.carId = 3;
refThree.carBrand = "Tesla";
refThree.carModel = "Model 3";
refThree.carColor = "Red";
refThree.manufacturingYear = 2024;
refThree.price = 6000000;
refThree.fuelType = "Electric";
refThree.seatingCapacity = 5;
refThree.engineCapacity = 0.0;
refThree.transmissionType = "Automatic";
refThree.numberOfDoors = 4;
refThree.isAutomatic = true;
refThree.hasSunroof = true;
refThree.hasAirbags = true;
refThree.hasABS = true;
refThree.mileage = 0;
refThree.registrationNumber = "KA03EF9999";
refThree.ownerName = "Kiran";
refThree.insuranceProvider = "Bajaj";
refThree.insuranceExpiryDate = "2028-02-11";
refThree.tyreType = "Radial";
refThree.batteryType = "Lithium Ion";
refThree.navigationSystem = "Smart GPS";
refThree.musicSystem = "Dolby";
refThree.isElectric = true;

System.out.println("The carId is: " + refThree.carId);
System.out.println("The carBrand is: " + refThree.carBrand);
System.out.println("The carModel is: " + refThree.carModel);
System.out.println("The carColor is: " + refThree.carColor);
System.out.println("The manufacturingYear is: " + refThree.manufacturingYear);
System.out.println("The price is: " + refThree.price);
System.out.println("The fuelType is: " + refThree.fuelType);
System.out.println("The seatingCapacity is: " + refThree.seatingCapacity);
System.out.println("The engineCapacity is: " + refThree.engineCapacity);
System.out.println("The transmissionType is: " + refThree.transmissionType);
System.out.println("The numberOfDoors is: " + refThree.numberOfDoors);
System.out.println("The isAutomatic is: " + refThree.isAutomatic);
System.out.println("The hasSunroof is: " + refThree.hasSunroof);
System.out.println("The hasAirbags is: " + refThree.hasAirbags);
System.out.println("The hasABS is: " + refThree.hasABS);
System.out.println("The mileage is: " + refThree.mileage);
System.out.println("The registrationNumber is: " + refThree.registrationNumber);
System.out.println("The ownerName is: " + refThree.ownerName);
System.out.println("The insuranceProvider is: " + refThree.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refThree.insuranceExpiryDate);
System.out.println("The tyreType is: " + refThree.tyreType);
System.out.println("The batteryType is: " + refThree.batteryType);
System.out.println("The navigationSystem is: " + refThree.navigationSystem);
System.out.println("The musicSystem is: " + refThree.musicSystem);
System.out.println("The isElectric is: " + refThree.isElectric);

Car refFour = new Car();
System.out.println("The carId is: " + refFour.carId);
System.out.println("The carBrand is: " + refFour.carBrand);
System.out.println("The carModel is: " + refFour.carModel);
System.out.println("The carColor is: " + refFour.carColor);
System.out.println("The manufacturingYear is: " + refFour.manufacturingYear);
System.out.println("The price is: " + refFour.price);
System.out.println("The fuelType is: " + refFour.fuelType);
System.out.println("The seatingCapacity is: " + refFour.seatingCapacity);
System.out.println("The engineCapacity is: " + refFour.engineCapacity);
System.out.println("The transmissionType is: " + refFour.transmissionType);
System.out.println("The numberOfDoors is: " + refFour.numberOfDoors);
System.out.println("The isAutomatic is: " + refFour.isAutomatic);
System.out.println("The hasSunroof is: " + refFour.hasSunroof);
System.out.println("The hasAirbags is: " + refFour.hasAirbags);
System.out.println("The hasABS is: " + refFour.hasABS);
System.out.println("The mileage is: " + refFour.mileage);
System.out.println("The registrationNumber is: " + refFour.registrationNumber);
System.out.println("The ownerName is: " + refFour.ownerName);
System.out.println("The insuranceProvider is: " + refFour.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refFour.insuranceExpiryDate);
System.out.println("The tyreType is: " + refFour.tyreType);
System.out.println("The batteryType is: " + refFour.batteryType);
System.out.println("The navigationSystem is: " + refFour.navigationSystem);
System.out.println("The musicSystem is: " + refFour.musicSystem);
System.out.println("The isElectric is: " + refFour.isElectric);
//Car refFour = new Car();

refFour.carId = 4;
refFour.carBrand = "Hyundai";
refFour.carModel = "Creta";
refFour.carColor = "Silver";
refFour.manufacturingYear = 2021;
refFour.price = 1800000;
refFour.fuelType = "Petrol";
refFour.seatingCapacity = 5;
refFour.engineCapacity = 1.5;
refFour.transmissionType = "Manual";
refFour.numberOfDoors = 4;
refFour.isAutomatic = false;
refFour.hasSunroof = true;
refFour.hasAirbags = true;
refFour.hasABS = true;
refFour.mileage = 17;
refFour.registrationNumber = "KA04GH4567";
refFour.ownerName = "Ravi";
refFour.insuranceProvider = "SBI";
refFour.insuranceExpiryDate = "2027-01-10";
refFour.tyreType = "Tubeless";
refFour.batteryType = "Lithium";
refFour.navigationSystem = "GPS";
refFour.musicSystem = "JBL";
refFour.isElectric = false;
System.out.println("The carId is: " + refFour.carId);
System.out.println("The carBrand is: " + refFour.carBrand);
System.out.println("The carModel is: " + refFour.carModel);
System.out.println("The carColor is: " + refFour.carColor);
System.out.println("The manufacturingYear is: " + refFour.manufacturingYear);
System.out.println("The price is: " + refFour.price);
System.out.println("The fuelType is: " + refFour.fuelType);
System.out.println("The seatingCapacity is: " + refFour.seatingCapacity);
System.out.println("The engineCapacity is: " + refFour.engineCapacity);
System.out.println("The transmissionType is: " + refFour.transmissionType);
System.out.println("The numberOfDoors is: " + refFour.numberOfDoors);
System.out.println("The isAutomatic is: " + refFour.isAutomatic);
System.out.println("The hasSunroof is: " + refFour.hasSunroof);
System.out.println("The hasAirbags is: " + refFour.hasAirbags);
System.out.println("The hasABS is: " + refFour.hasABS);
System.out.println("The mileage is: " + refFour.mileage);
System.out.println("The registrationNumber is: " + refFour.registrationNumber);
System.out.println("The ownerName is: " + refFour.ownerName);
System.out.println("The insuranceProvider is: " + refFour.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refFour.insuranceExpiryDate);
System.out.println("The tyreType is: " + refFour.tyreType);
System.out.println("The batteryType is: " + refFour.batteryType);
System.out.println("The navigationSystem is: " + refFour.navigationSystem);
System.out.println("The musicSystem is: " + refFour.musicSystem);
System.out.println("The isElectric is: " + refFour.isElectric);
Car refFive = new Car();

System.out.println("The carModel is: " + refFive.carModel);
System.out.println("The carColor is: " + refFive.carColor);
System.out.println("The manufacturingYear is: " + refFive.manufacturingYear);
System.out.println("The price is: " + refFive.price);
System.out.println("The fuelType is: " + refFive.fuelType);
System.out.println("The seatingCapacity is: " + refFive.seatingCapacity);
System.out.println("The engineCapacity is: " + refFive.engineCapacity);
System.out.println("The transmissionType is: " + refFive.transmissionType);
System.out.println("The numberOfDoors is: " + refFive.numberOfDoors);
System.out.println("The isAutomatic is: " + refFive.isAutomatic);
System.out.println("The hasSunroof is: " + refFive.hasSunroof);
System.out.println("The hasAirbags is: " + refFive.hasAirbags);
System.out.println("The hasABS is: " + refFive.hasABS);
System.out.println("The mileage is: " + refFive.mileage);
System.out.println("The registrationNumber is: " + refFive.registrationNumber);
System.out.println("The ownerName is: " + refFive.ownerName);
System.out.println("The insuranceProvider is: " + refFive.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refFive.insuranceExpiryDate);
System.out.println("The tyreType is: " + refFive.tyreType);
System.out.println("The batteryType is: " + refFive.batteryType);
System.out.println("The navigationSystem is: " + refFive.navigationSystem);
System.out.println("The musicSystem is: " + refFive.musicSystem);
System.out.println("The isElectric is: " + refFive.isElectric);

refFive.carId = 5;
refFive.carBrand = "Toyota";
refFive.carModel = "Fortuner";
refFive.carColor = "Black";
refFive.manufacturingYear = 2023;
refFive.price = 4200000;
refFive.fuelType = "Diesel";
refFive.seatingCapacity = 7;
refFive.engineCapacity = 2.8;
refFive.transmissionType = "Automatic";
refFive.numberOfDoors = 4;
refFive.isAutomatic = true;
refFive.hasSunroof = true;
refFive.hasAirbags = true;
refFive.hasABS = true;
refFive.mileage = 12.5;
refFive.registrationNumber = "KA05IJ8888";
refFive.ownerName = "Manoj";
refFive.insuranceProvider = "HDFC";
refFive.insuranceExpiryDate = "2027-06-20";
refFive.tyreType = "Tubeless";
refFive.batteryType = "Lithium";
refFive.navigationSystem = "GPS";
refFive.musicSystem = "Sony";
refFive.isElectric = false;

System.out.println("The carId is: " + refFive.carId);
System.out.println("The carBrand is: " + refFive.carBrand);
System.out.println("The carModel is: " + refFive.carModel);
System.out.println("The carColor is: " + refFive.carColor);
System.out.println("The manufacturingYear is: " + refFive.manufacturingYear);
System.out.println("The price is: " + refFive.price);
System.out.println("The fuelType is: " + refFive.fuelType);
System.out.println("The seatingCapacity is: " + refFive.seatingCapacity);
System.out.println("The engineCapacity is: " + refFive.engineCapacity);
System.out.println("The transmissionType is: " + refFive.transmissionType);
System.out.println("The numberOfDoors is: " + refFive.numberOfDoors);
System.out.println("The isAutomatic is: " + refFive.isAutomatic);
System.out.println("The hasSunroof is: " + refFive.hasSunroof);
System.out.println("The hasAirbags is: " + refFive.hasAirbags);
System.out.println("The hasABS is: " + refFive.hasABS);
System.out.println("The mileage is: " + refFive.mileage);
System.out.println("The registrationNumber is: " + refFive.registrationNumber);
System.out.println("The ownerName is: " + refFive.ownerName);
System.out.println("The insuranceProvider is: " + refFive.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refFive.insuranceExpiryDate);
System.out.println("The tyreType is: " + refFive.tyreType);
System.out.println("The batteryType is: " + refFive.batteryType);
System.out.println("The navigationSystem is: " + refFive.navigationSystem);
System.out.println("The musicSystem is: " + refFive.musicSystem);
System.out.println("The isElectric is: " + refFive.isElectric);	
Car refSix = new Car();

System.out.println("The carModel is: " + refSix.carModel);
System.out.println("The carColor is: " + refSix.carColor);
System.out.println("The manufacturingYear is: " + refSix.manufacturingYear);
System.out.println("The price is: " + refSix.price);
System.out.println("The fuelType is: " + refSix.fuelType);
System.out.println("The seatingCapacity is: " + refSix.seatingCapacity);
System.out.println("The engineCapacity is: " + refSix.engineCapacity);
System.out.println("The transmissionType is: " + refSix.transmissionType);
System.out.println("The numberOfDoors is: " + refSix.numberOfDoors);
System.out.println("The isAutomatic is: " + refSix.isAutomatic);
System.out.println("The hasSunroof is: " + refSix.hasSunroof);
System.out.println("The hasAirbags is: " + refSix.hasAirbags);
System.out.println("The hasABS is: " + refSix.hasABS);
System.out.println("The mileage is: " + refSix.mileage);
System.out.println("The registrationNumber is: " + refSix.registrationNumber);
System.out.println("The ownerName is: " + refSix.ownerName);
System.out.println("The insuranceProvider is: " + refSix.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refSix.insuranceExpiryDate);
System.out.println("The tyreType is: " + refSix.tyreType);
System.out.println("The batteryType is: " + refSix.batteryType);
System.out.println("The navigationSystem is: " + refSix.navigationSystem);
System.out.println("The musicSystem is: " + refSix.musicSystem);
System.out.println("The isElectric is: " + refSix.isElectric);

refSix.carId = 6;
refSix.carBrand = "Honda";
refSix.carModel = "City";
refSix.carColor = "Blue";
refSix.manufacturingYear = 2022;
refSix.price = 1500000;
refSix.fuelType = "Petrol";
refSix.seatingCapacity = 5;
refSix.engineCapacity = 1.5;
refSix.transmissionType = "Manual";
refSix.numberOfDoors = 4;
refSix.isAutomatic = false;
refSix.hasSunroof = true;
refSix.hasAirbags = true;
refSix.hasABS = true;
refSix.mileage = 18.4;
refSix.registrationNumber = "KA06KL1212";
refSix.ownerName = "Suresh";
refSix.insuranceProvider = "ICICI";
refSix.insuranceExpiryDate = "2027-07-15";
refSix.tyreType = "Tubeless";
refSix.batteryType = "Lithium";
refSix.navigationSystem = "GPS";
refSix.musicSystem = "Sony";
refSix.isElectric = false;

System.out.println("The carId is: " + refSix.carId);
System.out.println("The carBrand is: " + refSix.carBrand);
System.out.println("The carModel is: " + refSix.carModel);
System.out.println("The carColor is: " + refSix.carColor);
System.out.println("The manufacturingYear is: " + refSix.manufacturingYear);
System.out.println("The price is: " + refSix.price);
System.out.println("The fuelType is: " + refSix.fuelType);
System.out.println("The seatingCapacity is: " + refSix.seatingCapacity);
System.out.println("The engineCapacity is: " + refSix.engineCapacity);
System.out.println("The transmissionType is: " + refSix.transmissionType);
System.out.println("The numberOfDoors is: " + refSix.numberOfDoors);
System.out.println("The isAutomatic is: " + refSix.isAutomatic);
System.out.println("The hasSunroof is: " + refSix.hasSunroof);
System.out.println("The hasAirbags is: " + refSix.hasAirbags);
System.out.println("The hasABS is: " + refSix.hasABS);
System.out.println("The mileage is: " + refSix.mileage);
System.out.println("The registrationNumber is: " + refSix.registrationNumber);
System.out.println("The ownerName is: " + refSix.ownerName);
System.out.println("The insuranceProvider is: " + refSix.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refSix.insuranceExpiryDate);
System.out.println("The tyreType is: " + refSix.tyreType);
System.out.println("The batteryType is: " + refSix.batteryType);
System.out.println("The navigationSystem is: " + refSix.navigationSystem);
System.out.println("The musicSystem is: " + refSix.musicSystem);
System.out.println("The isElectric is: " + refSix.isElectric);
Car refSeven = new Car();

System.out.println("The carModel is: " + refSeven.carModel);
System.out.println("The carColor is: " + refSeven.carColor);
System.out.println("The manufacturingYear is: " + refSeven.manufacturingYear);
System.out.println("The price is: " + refSeven.price);
System.out.println("The fuelType is: " + refSeven.fuelType);
System.out.println("The seatingCapacity is: " + refSeven.seatingCapacity);
System.out.println("The engineCapacity is: " + refSeven.engineCapacity);
System.out.println("The transmissionType is: " + refSeven.transmissionType);
System.out.println("The numberOfDoors is: " + refSeven.numberOfDoors);
System.out.println("The isAutomatic is: " + refSeven.isAutomatic);
System.out.println("The hasSunroof is: " + refSeven.hasSunroof);
System.out.println("The hasAirbags is: " + refSeven.hasAirbags);
System.out.println("The hasABS is: " + refSeven.hasABS);
System.out.println("The mileage is: " + refSeven.mileage);
System.out.println("The registrationNumber is: " + refSeven.registrationNumber);
System.out.println("The ownerName is: " + refSeven.ownerName);
System.out.println("The insuranceProvider is: " + refSeven.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refSeven.insuranceExpiryDate);
System.out.println("The tyreType is: " + refSeven.tyreType);
System.out.println("The batteryType is: " + refSeven.batteryType);
System.out.println("The navigationSystem is: " + refSeven.navigationSystem);
System.out.println("The musicSystem is: " + refSeven.musicSystem);
System.out.println("The isElectric is: " + refSeven.isElectric);

refSeven.carId = 7;
refSeven.carBrand = "Kia";
refSeven.carModel = "Seltos";
refSeven.carColor = "Orange";
refSeven.manufacturingYear = 2023;
refSeven.price = 1900000;
refSeven.fuelType = "Petrol";
refSeven.seatingCapacity = 5;
refSeven.engineCapacity = 1.5;
refSeven.transmissionType = "Automatic";
refSeven.numberOfDoors = 4;
refSeven.isAutomatic = true;
refSeven.hasSunroof = true;
refSeven.hasAirbags = true;
refSeven.hasABS = true;
refSeven.mileage = 16.8;
refSeven.registrationNumber = "KA07MN2323";
refSeven.ownerName = "Deepak";
refSeven.insuranceProvider = "HDFC";
refSeven.insuranceExpiryDate = "2027-08-22";
refSeven.tyreType = "Tubeless";
refSeven.batteryType = "Lithium";
refSeven.navigationSystem = "GPS";
refSeven.musicSystem = "Sony";
refSeven.isElectric = false;

System.out.println("The carId is: " + refSeven.carId);
System.out.println("The carBrand is: " + refSeven.carBrand);
System.out.println("The carModel is: " + refSeven.carModel);
System.out.println("The carColor is: " + refSeven.carColor);
System.out.println("The manufacturingYear is: " + refSeven.manufacturingYear);
System.out.println("The price is: " + refSeven.price);
System.out.println("The fuelType is: " + refSeven.fuelType);
System.out.println("The seatingCapacity is: " + refSeven.seatingCapacity);
System.out.println("The engineCapacity is: " + refSeven.engineCapacity);
System.out.println("The transmissionType is: " + refSeven.transmissionType);
System.out.println("The numberOfDoors is: " + refSeven.numberOfDoors);
System.out.println("The isAutomatic is: " + refSeven.isAutomatic);
System.out.println("The hasSunroof is: " + refSeven.hasSunroof);
System.out.println("The hasAirbags is: " + refSeven.hasAirbags);
System.out.println("The hasABS is: " + refSeven.hasABS);
System.out.println("The mileage is: " + refSeven.mileage);
System.out.println("The registrationNumber is: " + refSeven.registrationNumber);
System.out.println("The ownerName is: " + refSeven.ownerName);
System.out.println("The insuranceProvider is: " + refSeven.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refSeven.insuranceExpiryDate);
System.out.println("The tyreType is: " + refSeven.tyreType);
System.out.println("The batteryType is: " + refSeven.batteryType);
System.out.println("The navigationSystem is: " + refSeven.navigationSystem);
System.out.println("The musicSystem is: " + refSeven.musicSystem);
System.out.println("The isElectric is: " + refSeven.isElectric);
Car refEight = new Car();

System.out.println("The carModel is: " + refEight.carModel);
System.out.println("The carColor is: " + refEight.carColor);
System.out.println("The manufacturingYear is: " + refEight.manufacturingYear);
System.out.println("The price is: " + refEight.price);
System.out.println("The fuelType is: " + refEight.fuelType);
System.out.println("The seatingCapacity is: " + refEight.seatingCapacity);
System.out.println("The engineCapacity is: " + refEight.engineCapacity);
System.out.println("The transmissionType is: " + refEight.transmissionType);
System.out.println("The numberOfDoors is: " + refEight.numberOfDoors);
System.out.println("The isAutomatic is: " + refEight.isAutomatic);
System.out.println("The hasSunroof is: " + refEight.hasSunroof);
System.out.println("The hasAirbags is: " + refEight.hasAirbags);
System.out.println("The hasABS is: " + refEight.hasABS);
System.out.println("The mileage is: " + refEight.mileage);
System.out.println("The registrationNumber is: " + refEight.registrationNumber);
System.out.println("The ownerName is: " + refEight.ownerName);
System.out.println("The insuranceProvider is: " + refEight.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refEight.insuranceExpiryDate);
System.out.println("The tyreType is: " + refEight.tyreType);
System.out.println("The batteryType is: " + refEight.batteryType);
System.out.println("The navigationSystem is: " + refEight.navigationSystem);
System.out.println("The musicSystem is: " + refEight.musicSystem);
System.out.println("The isElectric is: " + refEight.isElectric);

refEight.carId = 8;
refEight.carBrand = "Mahindra";
refEight.carModel = "Thar";
refEight.carColor = "Green";
refEight.manufacturingYear = 2022;
refEight.price = 1700000;
refEight.fuelType = "Diesel";
refEight.seatingCapacity = 4;
refEight.engineCapacity = 2.2;
refEight.transmissionType = "Manual";
refEight.numberOfDoors = 3;
refEight.isAutomatic = false;
refEight.hasSunroof = false;
refEight.hasAirbags = true;
refEight.hasABS = true;
refEight.mileage = 15.2;
refEight.registrationNumber = "KA08OP4545";
refEight.ownerName = "Rahul";
refEight.insuranceProvider = "ICICI";
refEight.insuranceExpiryDate = "2027-09-12";
refEight.tyreType = "All-Terrain";
refEight.batteryType = "Lithium";
refEight.navigationSystem = "GPS";
refEight.musicSystem = "Sony";
refEight.isElectric = false;

System.out.println("The carId is: " + refEight.carId);
System.out.println("The carBrand is: " + refEight.carBrand);
System.out.println("The carModel is: " + refEight.carModel);
System.out.println("The carColor is: " + refEight.carColor);
System.out.println("The manufacturingYear is: " + refEight.manufacturingYear);
System.out.println("The price is: " + refEight.price);
System.out.println("The fuelType is: " + refEight.fuelType);
System.out.println("The seatingCapacity is: " + refEight.seatingCapacity);
System.out.println("The engineCapacity is: " + refEight.engineCapacity);
System.out.println("The transmissionType is: " + refEight.transmissionType);
System.out.println("The numberOfDoors is: " + refEight.numberOfDoors);
System.out.println("The isAutomatic is: " + refEight.isAutomatic);
System.out.println("The hasSunroof is: " + refEight.hasSunroof);
System.out.println("The hasAirbags is: " + refEight.hasAirbags);
System.out.println("The hasABS is: " + refEight.hasABS);
System.out.println("The mileage is: " + refEight.mileage);
System.out.println("The registrationNumber is: " + refEight.registrationNumber);
System.out.println("The ownerName is: " + refEight.ownerName);
System.out.println("The insuranceProvider is: " + refEight.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refEight.insuranceExpiryDate);
System.out.println("The tyreType is: " + refEight.tyreType);
System.out.println("The batteryType is: " + refEight.batteryType);
System.out.println("The navigationSystem is: " + refEight.navigationSystem);
System.out.println("The musicSystem is: " + refEight.musicSystem);
System.out.println("The isElectric is: " + refEight.isElectric);
Car refNine = new Car();

System.out.println("The carModel is: " + refNine.carModel);
System.out.println("The carColor is: " + refNine.carColor);
System.out.println("The manufacturingYear is: " + refNine.manufacturingYear);
System.out.println("The price is: " + refNine.price);
System.out.println("The fuelType is: " + refNine.fuelType);
System.out.println("The seatingCapacity is: " + refNine.seatingCapacity);
System.out.println("The engineCapacity is: " + refNine.engineCapacity);
System.out.println("The transmissionType is: " + refNine.transmissionType);
System.out.println("The numberOfDoors is: " + refNine.numberOfDoors);
System.out.println("The isAutomatic is: " + refNine.isAutomatic);
System.out.println("The hasSunroof is: " + refNine.hasSunroof);
System.out.println("The hasAirbags is: " + refNine.hasAirbags);
System.out.println("The hasABS is: " + refNine.hasABS);
System.out.println("The mileage is: " + refNine.mileage);
System.out.println("The registrationNumber is: " + refNine.registrationNumber);
System.out.println("The ownerName is: " + refNine.ownerName);
System.out.println("The insuranceProvider is: " + refNine.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refNine.insuranceExpiryDate);
System.out.println("The tyreType is: " + refNine.tyreType);
System.out.println("The batteryType is: " + refNine.batteryType);
System.out.println("The navigationSystem is: " + refNine.navigationSystem);
System.out.println("The musicSystem is: " + refNine.musicSystem);
System.out.println("The isElectric is: " + refNine.isElectric);

refNine.carId = 9;
refNine.carBrand = "Skoda";
refNine.carModel = "Slavia";
refNine.carColor = "Grey";
refNine.manufacturingYear = 2023;
refNine.price = 1600000;
refNine.fuelType = "Petrol";
refNine.seatingCapacity = 5;
refNine.engineCapacity = 1.5;
refNine.transmissionType = "Manual";
refNine.numberOfDoors = 4;
refNine.isAutomatic = false;
refNine.hasSunroof = true;
refNine.hasAirbags = true;
refNine.hasABS = true;
refNine.mileage = 18.2;
refNine.registrationNumber = "KA09QR7878";
refNine.ownerName = "Ajay";
refNine.insuranceProvider = "Bajaj";
refNine.insuranceExpiryDate = "2027-10-18";
refNine.tyreType = "Tubeless";
refNine.batteryType = "Lithium";
refNine.navigationSystem = "GPS";
refNine.musicSystem = "Sony";
refNine.isElectric = false;

System.out.println("The carId is: " + refNine.carId);
System.out.println("The carBrand is: " + refNine.carBrand);
System.out.println("The carModel is: " + refNine.carModel);
System.out.println("The carColor is: " + refNine.carColor);
System.out.println("The manufacturingYear is: " + refNine.manufacturingYear);
System.out.println("The price is: " + refNine.price);
System.out.println("The fuelType is: " + refNine.fuelType);
System.out.println("The seatingCapacity is: " + refNine.seatingCapacity);
System.out.println("The engineCapacity is: " + refNine.engineCapacity);
System.out.println("The transmissionType is: " + refNine.transmissionType);
System.out.println("The numberOfDoors is: " + refNine.numberOfDoors);
System.out.println("The isAutomatic is: " + refNine.isAutomatic);
System.out.println("The hasSunroof is: " + refNine.hasSunroof);
System.out.println("The hasAirbags is: " + refNine.hasAirbags);
System.out.println("The hasABS is: " + refNine.hasABS);
System.out.println("The mileage is: " + refNine.mileage);
System.out.println("The registrationNumber is: " + refNine.registrationNumber);
System.out.println("The ownerName is: " + refNine.ownerName);
System.out.println("The insuranceProvider is: " + refNine.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refNine.insuranceExpiryDate);
System.out.println("The tyreType is: " + refNine.tyreType);
System.out.println("The batteryType is: " + refNine.batteryType);
System.out.println("The navigationSystem is: " + refNine.navigationSystem);
System.out.println("The musicSystem is: " + refNine.musicSystem);
System.out.println("The isElectric is: " + refNine.isElectric);
Car refTen = new Car();

System.out.println("The carModel is: " + refTen.carModel);
System.out.println("The carColor is: " + refTen.carColor);
System.out.println("The manufacturingYear is: " + refTen.manufacturingYear);
System.out.println("The price is: " + refTen.price);
System.out.println("The fuelType is: " + refTen.fuelType);
System.out.println("The seatingCapacity is: " + refTen.seatingCapacity);
System.out.println("The engineCapacity is: " + refTen.engineCapacity);
System.out.println("The transmissionType is: " + refTen.transmissionType);
System.out.println("The numberOfDoors is: " + refTen.numberOfDoors);
System.out.println("The isAutomatic is: " + refTen.isAutomatic);
System.out.println("The hasSunroof is: " + refTen.hasSunroof);
System.out.println("The hasAirbags is: " + refTen.hasAirbags);
System.out.println("The hasABS is: " + refTen.hasABS);
System.out.println("The mileage is: " + refTen.mileage);
System.out.println("The registrationNumber is: " + refTen.registrationNumber);
System.out.println("The ownerName is: " + refTen.ownerName);
System.out.println("The insuranceProvider is: " + refTen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refTen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refTen.tyreType);
System.out.println("The batteryType is: " + refTen.batteryType);
System.out.println("The navigationSystem is: " + refTen.navigationSystem);
System.out.println("The musicSystem is: " + refTen.musicSystem);
System.out.println("The isElectric is: " + refTen.isElectric);

refTen.carId = 10;
refTen.carBrand = "Volkswagen";
refTen.carModel = "Virtus";
refTen.carColor = "White";
refTen.manufacturingYear = 2023;
refTen.price = 1700000;
refTen.fuelType = "Petrol";
refTen.seatingCapacity = 5;
refTen.engineCapacity = 1.5;
refTen.transmissionType = "Automatic";
refTen.numberOfDoors = 4;
refTen.isAutomatic = true;
refTen.hasSunroof = true;
refTen.hasAirbags = true;
refTen.hasABS = true;
refTen.mileage = 18.7;
refTen.registrationNumber = "KA10ST9999";
refTen.ownerName = "Varun";
refTen.insuranceProvider = "HDFC";
refTen.insuranceExpiryDate = "2027-11-25";
refTen.tyreType = "Tubeless";
refTen.batteryType = "Lithium";
refTen.navigationSystem = "GPS";
refTen.musicSystem = "Sony";
refTen.isElectric = false;

System.out.println("The carId is: " + refTen.carId);
System.out.println("The carBrand is: " + refTen.carBrand);
System.out.println("The carModel is: " + refTen.carModel);
System.out.println("The carColor is: " + refTen.carColor);
System.out.println("The manufacturingYear is: " + refTen.manufacturingYear);
System.out.println("The price is: " + refTen.price);
System.out.println("The fuelType is: " + refTen.fuelType);
System.out.println("The seatingCapacity is: " + refTen.seatingCapacity);
System.out.println("The engineCapacity is: " + refTen.engineCapacity);
System.out.println("The transmissionType is: " + refTen.transmissionType);
System.out.println("The numberOfDoors is: " + refTen.numberOfDoors);
System.out.println("The isAutomatic is: " + refTen.isAutomatic);
System.out.println("The hasSunroof is: " + refTen.hasSunroof);
System.out.println("The hasAirbags is: " + refTen.hasAirbags);
System.out.println("The hasABS is: " + refTen.hasABS);
System.out.println("The mileage is: " + refTen.mileage);
System.out.println("The registrationNumber is: " + refTen.registrationNumber);
System.out.println("The ownerName is: " + refTen.ownerName);
System.out.println("The insuranceProvider is: " + refTen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refTen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refTen.tyreType);
System.out.println("The batteryType is: " + refTen.batteryType);
System.out.println("The navigationSystem is: " + refTen.navigationSystem);
System.out.println("The musicSystem is: " + refTen.musicSystem);
System.out.println("The isElectric is: " + refTen.isElectric);
Car refEleven = new Car();

System.out.println("The carModel is: " + refEleven.carModel);
System.out.println("The carColor is: " + refEleven.carColor);
System.out.println("The manufacturingYear is: " + refEleven.manufacturingYear);
System.out.println("The price is: " + refEleven.price);
System.out.println("The fuelType is: " + refEleven.fuelType);
System.out.println("The seatingCapacity is: " + refEleven.seatingCapacity);
System.out.println("The engineCapacity is: " + refEleven.engineCapacity);
System.out.println("The transmissionType is: " + refEleven.transmissionType);
System.out.println("The numberOfDoors is: " + refEleven.numberOfDoors);
System.out.println("The isAutomatic is: " + refEleven.isAutomatic);
System.out.println("The hasSunroof is: " + refEleven.hasSunroof);
System.out.println("The hasAirbags is: " + refEleven.hasAirbags);
System.out.println("The hasABS is: " + refEleven.hasABS);
System.out.println("The mileage is: " + refEleven.mileage);
System.out.println("The registrationNumber is: " + refEleven.registrationNumber);
System.out.println("The ownerName is: " + refEleven.ownerName);
System.out.println("The insuranceProvider is: " + refEleven.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refEleven.insuranceExpiryDate);
System.out.println("The tyreType is: " + refEleven.tyreType);
System.out.println("The batteryType is: " + refEleven.batteryType);
System.out.println("The navigationSystem is: " + refEleven.navigationSystem);
System.out.println("The musicSystem is: " + refEleven.musicSystem);
System.out.println("The isElectric is: " + refEleven.isElectric);

refEleven.carId = 11;
refEleven.carBrand = "MG";
refEleven.carModel = "Hector";
refEleven.carColor = "Black";
refEleven.manufacturingYear = 2022;
refEleven.price = 2100000;
refEleven.fuelType = "Petrol";
refEleven.seatingCapacity = 5;
refEleven.engineCapacity = 2.0;
refEleven.transmissionType = "Automatic";
refEleven.numberOfDoors = 4;
refEleven.isAutomatic = true;
refEleven.hasSunroof = true;
refEleven.hasAirbags = true;
refEleven.hasABS = true;
refEleven.mileage = 15.5;
refEleven.registrationNumber = "KA11UV3434";
refEleven.ownerName = "Naveen";
refEleven.insuranceProvider = "ICICI";
refEleven.insuranceExpiryDate = "2027-12-15";
refEleven.tyreType = "Tubeless";
refEleven.batteryType = "Lithium";
refEleven.navigationSystem = "GPS";
refEleven.musicSystem = "Sony";
refEleven.isElectric = false;

System.out.println("The carId is: " + refEleven.carId);
System.out.println("The carBrand is: " + refEleven.carBrand);
System.out.println("The carModel is: " + refEleven.carModel);
System.out.println("The carColor is: " + refEleven.carColor);
System.out.println("The manufacturingYear is: " + refEleven.manufacturingYear);
System.out.println("The price is: " + refEleven.price);
System.out.println("The fuelType is: " + refEleven.fuelType);
System.out.println("The seatingCapacity is: " + refEleven.seatingCapacity);
System.out.println("The engineCapacity is: " + refEleven.engineCapacity);
System.out.println("The transmissionType is: " + refEleven.transmissionType);
System.out.println("The numberOfDoors is: " + refEleven.numberOfDoors);
System.out.println("The isAutomatic is: " + refEleven.isAutomatic);
System.out.println("The hasSunroof is: " + refEleven.hasSunroof);
System.out.println("The hasAirbags is: " + refEleven.hasAirbags);
System.out.println("The hasABS is: " + refEleven.hasABS);
System.out.println("The mileage is: " + refEleven.mileage);
System.out.println("The registrationNumber is: " + refEleven.registrationNumber);
System.out.println("The ownerName is: " + refEleven.ownerName);
System.out.println("The insuranceProvider is: " + refEleven.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refEleven.insuranceExpiryDate);
System.out.println("The tyreType is: " + refEleven.tyreType);
System.out.println("The batteryType is: " + refEleven.batteryType);
System.out.println("The navigationSystem is: " + refEleven.navigationSystem);
System.out.println("The musicSystem is: " + refEleven.musicSystem);
System.out.println("The isElectric is: " + refEleven.isElectric);
Car refTwelve = new Car();

System.out.println("The carModel is: " + refTwelve.carModel);
System.out.println("The carColor is: " + refTwelve.carColor);
System.out.println("The manufacturingYear is: " + refTwelve.manufacturingYear);
System.out.println("The price is: " + refTwelve.price);
System.out.println("The fuelType is: " + refTwelve.fuelType);
System.out.println("The seatingCapacity is: " + refTwelve.seatingCapacity);
System.out.println("The engineCapacity is: " + refTwelve.engineCapacity);
System.out.println("The transmissionType is: " + refTwelve.transmissionType);
System.out.println("The numberOfDoors is: " + refTwelve.numberOfDoors);
System.out.println("The isAutomatic is: " + refTwelve.isAutomatic);
System.out.println("The hasSunroof is: " + refTwelve.hasSunroof);
System.out.println("The hasAirbags is: " + refTwelve.hasAirbags);
System.out.println("The hasABS is: " + refTwelve.hasABS);
System.out.println("The mileage is: " + refTwelve.mileage);
System.out.println("The registrationNumber is: " + refTwelve.registrationNumber);
System.out.println("The ownerName is: " + refTwelve.ownerName);
System.out.println("The insuranceProvider is: " + refTwelve.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refTwelve.insuranceExpiryDate);
System.out.println("The tyreType is: " + refTwelve.tyreType);
System.out.println("The batteryType is: " + refTwelve.batteryType);
System.out.println("The navigationSystem is: " + refTwelve.navigationSystem);
System.out.println("The musicSystem is: " + refTwelve.musicSystem);
System.out.println("The isElectric is: " + refTwelve.isElectric);

refTwelve.carId = 12;
refTwelve.carBrand = "Tata";
refTwelve.carModel = "Nexon";
refTwelve.carColor = "Blue";
refTwelve.manufacturingYear = 2024;
refTwelve.price = 1500000;
refTwelve.fuelType = "Electric";
refTwelve.seatingCapacity = 5;
refTwelve.engineCapacity = 0.0;
refTwelve.transmissionType = "Automatic";
refTwelve.numberOfDoors = 4;
refTwelve.isAutomatic = true;
refTwelve.hasSunroof = true;
refTwelve.hasAirbags = true;
refTwelve.hasABS = true;
refTwelve.mileage = 0;
refTwelve.registrationNumber = "KA12WX5656";
refTwelve.ownerName = "Prakash";
refTwelve.insuranceProvider = "Bajaj";
refTwelve.insuranceExpiryDate = "2028-01-10";
refTwelve.tyreType = "Tubeless";
refTwelve.batteryType = "Lithium Ion";
refTwelve.navigationSystem = "GPS";
refTwelve.musicSystem = "JBL";
refTwelve.isElectric = true;

System.out.println("The carId is: " + refTwelve.carId);
System.out.println("The carBrand is: " + refTwelve.carBrand);
System.out.println("The carModel is: " + refTwelve.carModel);
System.out.println("The carColor is: " + refTwelve.carColor);
System.out.println("The manufacturingYear is: " + refTwelve.manufacturingYear);
System.out.println("The price is: " + refTwelve.price);
System.out.println("The fuelType is: " + refTwelve.fuelType);
System.out.println("The seatingCapacity is: " + refTwelve.seatingCapacity);
System.out.println("The engineCapacity is: " + refTwelve.engineCapacity);
System.out.println("The transmissionType is: " + refTwelve.transmissionType);
System.out.println("The numberOfDoors is: " + refTwelve.numberOfDoors);
System.out.println("The isAutomatic is: " + refTwelve.isAutomatic);
System.out.println("The hasSunroof is: " + refTwelve.hasSunroof);
System.out.println("The hasAirbags is: " + refTwelve.hasAirbags);
System.out.println("The hasABS is: " + refTwelve.hasABS);
System.out.println("The mileage is: " + refTwelve.mileage);
System.out.println("The registrationNumber is: " + refTwelve.registrationNumber);
System.out.println("The ownerName is: " + refTwelve.ownerName);
System.out.println("The insuranceProvider is: " + refTwelve.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refTwelve.insuranceExpiryDate);
System.out.println("The tyreType is: " + refTwelve.tyreType);
System.out.println("The batteryType is: " + refTwelve.batteryType);
System.out.println("The navigationSystem is: " + refTwelve.navigationSystem);
System.out.println("The musicSystem is: " + refTwelve.musicSystem);
System.out.println("The isElectric is: " + refTwelve.isElectric);
Car refThirteen = new Car();

System.out.println("The carModel is: " + refThirteen.carModel);
System.out.println("The carColor is: " + refThirteen.carColor);
System.out.println("The manufacturingYear is: " + refThirteen.manufacturingYear);
System.out.println("The price is: " + refThirteen.price);
System.out.println("The fuelType is: " + refThirteen.fuelType);
System.out.println("The seatingCapacity is: " + refThirteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refThirteen.engineCapacity);
System.out.println("The transmissionType is: " + refThirteen.transmissionType);
System.out.println("The numberOfDoors is: " + refThirteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refThirteen.isAutomatic);
System.out.println("The hasSunroof is: " + refThirteen.hasSunroof);
System.out.println("The hasAirbags is: " + refThirteen.hasAirbags);
System.out.println("The hasABS is: " + refThirteen.hasABS);
System.out.println("The mileage is: " + refThirteen.mileage);
System.out.println("The registrationNumber is: " + refThirteen.registrationNumber);
System.out.println("The ownerName is: " + refThirteen.ownerName);
System.out.println("The insuranceProvider is: " + refThirteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refThirteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refThirteen.tyreType);
System.out.println("The batteryType is: " + refThirteen.batteryType);
System.out.println("The navigationSystem is: " + refThirteen.navigationSystem);
System.out.println("The musicSystem is: " + refThirteen.musicSystem);
System.out.println("The isElectric is: " + refThirteen.isElectric);

refThirteen.carId = 13;
refThirteen.carBrand = "Tata";
refThirteen.carModel = "Harrier";
refThirteen.carColor = "Grey";
refThirteen.manufacturingYear = 2023;
refThirteen.price = 2400000;
refThirteen.fuelType = "Diesel";
refThirteen.seatingCapacity = 5;
refThirteen.engineCapacity = 2.0;
refThirteen.transmissionType = "Manual";
refThirteen.numberOfDoors = 4;
refThirteen.isAutomatic = false;
refThirteen.hasSunroof = true;
refThirteen.hasAirbags = true;
refThirteen.hasABS = true;
refThirteen.mileage = 16.0;
refThirteen.registrationNumber = "KA13YZ7777";
refThirteen.ownerName = "Ganesh";
refThirteen.insuranceProvider = "ICICI";
refThirteen.insuranceExpiryDate = "2027-02-10";
refThirteen.tyreType = "Tubeless";
refThirteen.batteryType = "Lithium";
refThirteen.navigationSystem = "GPS";
refThirteen.musicSystem = "JBL";
refThirteen.isElectric = false;

System.out.println("The carId is: " + refThirteen.carId);
System.out.println("The carBrand is: " + refThirteen.carBrand);
System.out.println("The carModel is: " + refThirteen.carModel);
System.out.println("The carColor is: " + refThirteen.carColor);
System.out.println("The manufacturingYear is: " + refThirteen.manufacturingYear);
System.out.println("The price is: " + refThirteen.price);
System.out.println("The fuelType is: " + refThirteen.fuelType);
System.out.println("The seatingCapacity is: " + refThirteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refThirteen.engineCapacity);
System.out.println("The transmissionType is: " + refThirteen.transmissionType);
System.out.println("The numberOfDoors is: " + refThirteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refThirteen.isAutomatic);
System.out.println("The hasSunroof is: " + refThirteen.hasSunroof);
System.out.println("The hasAirbags is: " + refThirteen.hasAirbags);
System.out.println("The hasABS is: " + refThirteen.hasABS);
System.out.println("The mileage is: " + refThirteen.mileage);
System.out.println("The registrationNumber is: " + refThirteen.registrationNumber);
System.out.println("The ownerName is: " + refThirteen.ownerName);
System.out.println("The insuranceProvider is: " + refThirteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refThirteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refThirteen.tyreType);
System.out.println("The batteryType is: " + refThirteen.batteryType);
System.out.println("The navigationSystem is: " + refThirteen.navigationSystem);
System.out.println("The musicSystem is: " + refThirteen.musicSystem);
System.out.println("The isElectric is: " + refThirteen.isElectric);
Car refFourteen = new Car();

System.out.println("The carModel is: " + refFourteen.carModel);
System.out.println("The carColor is: " + refFourteen.carColor);
System.out.println("The manufacturingYear is: " + refFourteen.manufacturingYear);
System.out.println("The price is: " + refFourteen.price);
System.out.println("The fuelType is: " + refFourteen.fuelType);
System.out.println("The seatingCapacity is: " + refFourteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refFourteen.engineCapacity);
System.out.println("The transmissionType is: " + refFourteen.transmissionType);
System.out.println("The numberOfDoors is: " + refFourteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refFourteen.isAutomatic);
System.out.println("The hasSunroof is: " + refFourteen.hasSunroof);
System.out.println("The hasAirbags is: " + refFourteen.hasAirbags);
System.out.println("The hasABS is: " + refFourteen.hasABS);
System.out.println("The mileage is: " + refFourteen.mileage);
System.out.println("The registrationNumber is: " + refFourteen.registrationNumber);
System.out.println("The ownerName is: " + refFourteen.ownerName);
System.out.println("The insuranceProvider is: " + refFourteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refFourteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refFourteen.tyreType);
System.out.println("The batteryType is: " + refFourteen.batteryType);
System.out.println("The navigationSystem is: " + refFourteen.navigationSystem);
System.out.println("The musicSystem is: " + refFourteen.musicSystem);
System.out.println("The isElectric is: " + refFourteen.isElectric);

refFourteen.carId = 14;
refFourteen.carBrand = "Renault";
refFourteen.carModel = "Kiger";
refFourteen.carColor = "Red";
refFourteen.manufacturingYear = 2022;
refFourteen.price = 1000000;
refFourteen.fuelType = "Petrol";
refFourteen.seatingCapacity = 5;
refFourteen.engineCapacity = 1.0;
refFourteen.transmissionType = "Manual";
refFourteen.numberOfDoors = 4;
refFourteen.isAutomatic = false;
refFourteen.hasSunroof = false;
refFourteen.hasAirbags = true;
refFourteen.hasABS = true;
refFourteen.mileage = 20.5;
refFourteen.registrationNumber = "KA14AB9898";
refFourteen.ownerName = "Harish";
refFourteen.insuranceProvider = "HDFC";
refFourteen.insuranceExpiryDate = "2027-03-15";
refFourteen.tyreType = "Tubeless";
refFourteen.batteryType = "Lithium";
refFourteen.navigationSystem = "GPS";
refFourteen.musicSystem = "Sony";
refFourteen.isElectric = false;

System.out.println("The carId is: " + refFourteen.carId);
System.out.println("The carBrand is: " + refFourteen.carBrand);
System.out.println("The carModel is: " + refFourteen.carModel);
System.out.println("The carColor is: " + refFourteen.carColor);
System.out.println("The manufacturingYear is: " + refFourteen.manufacturingYear);
System.out.println("The price is: " + refFourteen.price);
System.out.println("The fuelType is: " + refFourteen.fuelType);
System.out.println("The seatingCapacity is: " + refFourteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refFourteen.engineCapacity);
System.out.println("The transmissionType is: " + refFourteen.transmissionType);
System.out.println("The numberOfDoors is: " + refFourteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refFourteen.isAutomatic);
System.out.println("The hasSunroof is: " + refFourteen.hasSunroof);
System.out.println("The hasAirbags is: " + refFourteen.hasAirbags);
System.out.println("The hasABS is: " + refFourteen.hasABS);
System.out.println("The mileage is: " + refFourteen.mileage);
System.out.println("The registrationNumber is: " + refFourteen.registrationNumber);
System.out.println("The ownerName is: " + refFourteen.ownerName);
System.out.println("The insuranceProvider is: " + refFourteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refFourteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refFourteen.tyreType);
System.out.println("The batteryType is: " + refFourteen.batteryType);
System.out.println("The navigationSystem is: " + refFourteen.navigationSystem);
System.out.println("The musicSystem is: " + refFourteen.musicSystem);
System.out.println("The isElectric is: " + refFourteen.isElectric);
Car refFifteen = new Car();

System.out.println("The carModel is: " + refFifteen.carModel);
System.out.println("The carColor is: " + refFifteen.carColor);
System.out.println("The manufacturingYear is: " + refFifteen.manufacturingYear);
System.out.println("The price is: " + refFifteen.price);
System.out.println("The fuelType is: " + refFifteen.fuelType);
System.out.println("The seatingCapacity is: " + refFifteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refFifteen.engineCapacity);
System.out.println("The transmissionType is: " + refFifteen.transmissionType);
System.out.println("The numberOfDoors is: " + refFifteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refFifteen.isAutomatic);
System.out.println("The hasSunroof is: " + refFifteen.hasSunroof);
System.out.println("The hasAirbags is: " + refFifteen.hasAirbags);
System.out.println("The hasABS is: " + refFifteen.hasABS);
System.out.println("The mileage is: " + refFifteen.mileage);
System.out.println("The registrationNumber is: " + refFifteen.registrationNumber);
System.out.println("The ownerName is: " + refFifteen.ownerName);
System.out.println("The insuranceProvider is: " + refFifteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refFifteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refFifteen.tyreType);
System.out.println("The batteryType is: " + refFifteen.batteryType);
System.out.println("The navigationSystem is: " + refFifteen.navigationSystem);
System.out.println("The musicSystem is: " + refFifteen.musicSystem);
System.out.println("The isElectric is: " + refFifteen.isElectric);

refFifteen.carId = 15;
refFifteen.carBrand = "Nissan";
refFifteen.carModel = "Magnite";
refFifteen.carColor = "Silver";
refFifteen.manufacturingYear = 2022;
refFifteen.price = 950000;
refFifteen.fuelType = "Petrol";
refFifteen.seatingCapacity = 5;
refFifteen.engineCapacity = 1.0;
refFifteen.transmissionType = "Manual";
refFifteen.numberOfDoors = 4;
refFifteen.isAutomatic = false;
refFifteen.hasSunroof = false;
refFifteen.hasAirbags = true;
refFifteen.hasABS = true;
refFifteen.mileage = 19.7;
refFifteen.registrationNumber = "KA15CD1212";
refFifteen.ownerName = "Karthik";
refFifteen.insuranceProvider = "Bajaj";
refFifteen.insuranceExpiryDate = "2027-04-20";
refFifteen.tyreType = "Tubeless";
refFifteen.batteryType = "Lithium";
refFifteen.navigationSystem = "GPS";
refFifteen.musicSystem = "Sony";
refFifteen.isElectric = false;

System.out.println("The carId is: " + refFifteen.carId);
System.out.println("The carBrand is: " + refFifteen.carBrand);
System.out.println("The carModel is: " + refFifteen.carModel);
System.out.println("The carColor is: " + refFifteen.carColor);
System.out.println("The manufacturingYear is: " + refFifteen.manufacturingYear);
System.out.println("The price is: " + refFifteen.price);
System.out.println("The fuelType is: " + refFifteen.fuelType);
System.out.println("The seatingCapacity is: " + refFifteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refFifteen.engineCapacity);
System.out.println("The transmissionType is: " + refFifteen.transmissionType);
System.out.println("The numberOfDoors is: " + refFifteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refFifteen.isAutomatic);
System.out.println("The hasSunroof is: " + refFifteen.hasSunroof);
System.out.println("The hasAirbags is: " + refFifteen.hasAirbags);
System.out.println("The hasABS is: " + refFifteen.hasABS);
System.out.println("The mileage is: " + refFifteen.mileage);
System.out.println("The registrationNumber is: " + refFifteen.registrationNumber);
System.out.println("The ownerName is: " + refFifteen.ownerName);
System.out.println("The insuranceProvider is: " + refFifteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refFifteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refFifteen.tyreType);
System.out.println("The batteryType is: " + refFifteen.batteryType);
System.out.println("The navigationSystem is: " + refFifteen.navigationSystem);
System.out.println("The musicSystem is: " + refFifteen.musicSystem);
System.out.println("The isElectric is: " + refFifteen.isElectric);
Car refSixteen = new Car();

System.out.println("The carModel is: " + refSixteen.carModel);
System.out.println("The carColor is: " + refSixteen.carColor);
System.out.println("The manufacturingYear is: " + refSixteen.manufacturingYear);
System.out.println("The price is: " + refSixteen.price);
System.out.println("The fuelType is: " + refSixteen.fuelType);
System.out.println("The seatingCapacity is: " + refSixteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refSixteen.engineCapacity);
System.out.println("The transmissionType is: " + refSixteen.transmissionType);
System.out.println("The numberOfDoors is: " + refSixteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refSixteen.isAutomatic);
System.out.println("The hasSunroof is: " + refSixteen.hasSunroof);
System.out.println("The hasAirbags is: " + refSixteen.hasAirbags);
System.out.println("The hasABS is: " + refSixteen.hasABS);
System.out.println("The mileage is: " + refSixteen.mileage);
System.out.println("The registrationNumber is: " + refSixteen.registrationNumber);
System.out.println("The ownerName is: " + refSixteen.ownerName);
System.out.println("The insuranceProvider is: " + refSixteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refSixteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refSixteen.tyreType);
System.out.println("The batteryType is: " + refSixteen.batteryType);
System.out.println("The navigationSystem is: " + refSixteen.navigationSystem);
System.out.println("The musicSystem is: " + refSixteen.musicSystem);
System.out.println("The isElectric is: " + refSixteen.isElectric);

refSixteen.carId = 16;
refSixteen.carBrand = "Ford";
refSixteen.carModel = "EcoSport";
refSixteen.carColor = "Blue";
refSixteen.manufacturingYear = 2021;
refSixteen.price = 1400000;
refSixteen.fuelType = "Diesel";
refSixteen.seatingCapacity = 5;
refSixteen.engineCapacity = 1.5;
refSixteen.transmissionType = "Manual";
refSixteen.numberOfDoors = 4;
refSixteen.isAutomatic = false;
refSixteen.hasSunroof = false;
refSixteen.hasAirbags = true;
refSixteen.hasABS = true;
refSixteen.mileage = 20.0;
refSixteen.registrationNumber = "KA16EF3434";
refSixteen.ownerName = "Ramesh";
refSixteen.insuranceProvider = "HDFC";
refSixteen.insuranceExpiryDate = "2027-05-18";
refSixteen.tyreType = "Tubeless";
refSixteen.batteryType = "Lithium";
refSixteen.navigationSystem = "GPS";
refSixteen.musicSystem = "Sony";
refSixteen.isElectric = false;

System.out.println("The carId is: " + refSixteen.carId);
System.out.println("The carBrand is: " + refSixteen.carBrand);
System.out.println("The carModel is: " + refSixteen.carModel);
System.out.println("The carColor is: " + refSixteen.carColor);
System.out.println("The manufacturingYear is: " + refSixteen.manufacturingYear);
System.out.println("The price is: " + refSixteen.price);
System.out.println("The fuelType is: " + refSixteen.fuelType);
System.out.println("The seatingCapacity is: " + refSixteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refSixteen.engineCapacity);
System.out.println("The transmissionType is: " + refSixteen.transmissionType);
System.out.println("The numberOfDoors is: " + refSixteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refSixteen.isAutomatic);
System.out.println("The hasSunroof is: " + refSixteen.hasSunroof);
System.out.println("The hasAirbags is: " + refSixteen.hasAirbags);
System.out.println("The hasABS is: " + refSixteen.hasABS);
System.out.println("The mileage is: " + refSixteen.mileage);
System.out.println("The registrationNumber is: " + refSixteen.registrationNumber);
System.out.println("The ownerName is: " + refSixteen.ownerName);
System.out.println("The insuranceProvider is: " + refSixteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refSixteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refSixteen.tyreType);
System.out.println("The batteryType is: " + refSixteen.batteryType);
System.out.println("The navigationSystem is: " + refSixteen.navigationSystem);
System.out.println("The musicSystem is: " + refSixteen.musicSystem);
System.out.println("The isElectric is: " + refSixteen.isElectric);
Car refSeventeen = new Car();

System.out.println("The carModel is: " + refSeventeen.carModel);
System.out.println("The carColor is: " + refSeventeen.carColor);
System.out.println("The manufacturingYear is: " + refSeventeen.manufacturingYear);
System.out.println("The price is: " + refSeventeen.price);
System.out.println("The fuelType is: " + refSeventeen.fuelType);
System.out.println("The seatingCapacity is: " + refSeventeen.seatingCapacity);
System.out.println("The engineCapacity is: " + refSeventeen.engineCapacity);
System.out.println("The transmissionType is: " + refSeventeen.transmissionType);
System.out.println("The numberOfDoors is: " + refSeventeen.numberOfDoors);
System.out.println("The isAutomatic is: " + refSeventeen.isAutomatic);
System.out.println("The hasSunroof is: " + refSeventeen.hasSunroof);
System.out.println("The hasAirbags is: " + refSeventeen.hasAirbags);
System.out.println("The hasABS is: " + refSeventeen.hasABS);
System.out.println("The mileage is: " + refSeventeen.mileage);
System.out.println("The registrationNumber is: " + refSeventeen.registrationNumber);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
System.out.println("The insuranceProvider is: " + refSeventeen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refSeventeen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refSeventeen.tyreType);
System.out.println("The batteryType is: " + refSeventeen.batteryType);
System.out.println("The navigationSystem is: " + refSeventeen.navigationSystem);
System.out.println("The musicSystem is: " + refSeventeen.musicSystem);
System.out.println("The isElectric is: " + refSeventeen.isElectric);

refSeventeen.carId = 17;
refSeventeen.carBrand = "Hyundai";
refSeventeen.carModel = "Creta";
refSeventeen.carColor = "White";
refSeventeen.manufacturingYear = 2023;
refSeventeen.price = 1800000;
refSeventeen.fuelType = "Petrol";
refSeventeen.seatingCapacity = 5;
refSeventeen.engineCapacity = 1.5;
refSeventeen.transmissionType = "Automatic";
refSeventeen.numberOfDoors = 4;
refSeventeen.isAutomatic = true;
refSeventeen.hasSunroof = true;
refSeventeen.hasAirbags = true;
refSeventeen.hasABS = true;
refSeventeen.mileage = 17.0;
refSeventeen.registrationNumber = "KA17GH4545";
refSeventeen.ownerName = "Suresh";
refSeventeen.insuranceProvider = "ICICI";
refSeventeen.insuranceExpiryDate = "2028-06-20";
refSeventeen.tyreType = "Tubeless";
refSeventeen.batteryType = "Lithium";
refSeventeen.navigationSystem = "GPS";
refSeventeen.musicSystem = "Bose";
refSeventeen.isElectric = false;

System.out.println("The carId is: " + refSeventeen.carId);
System.out.println("The carBrand is: " + refSeventeen.carBrand);
System.out.println("The carModel is: " + refSeventeen.carModel);
System.out.println("The carColor is: " + refSeventeen.carColor);
System.out.println("The manufacturingYear is: " + refSeventeen.manufacturingYear);
System.out.println("The price is: " + refSeventeen.price);
System.out.println("The fuelType is: " + refSeventeen.fuelType);
System.out.println("The seatingCapacity is: " + refSeventeen.seatingCapacity);
System.out.println("The engineCapacity is: " + refSeventeen.engineCapacity);
System.out.println("The transmissionType is: " + refSeventeen.transmissionType);
System.out.println("The numberOfDoors is: " + refSeventeen.numberOfDoors);
System.out.println("The isAutomatic is: " + refSeventeen.isAutomatic);
System.out.println("The hasSunroof is: " + refSeventeen.hasSunroof);
System.out.println("The hasAirbags is: " + refSeventeen.hasAirbags);
System.out.println("The hasABS is: " + refSeventeen.hasABS);
System.out.println("The mileage is: " + refSeventeen.mileage);
System.out.println("The registrationNumber is: " + refSeventeen.registrationNumber);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
System.out.println("The insuranceProvider is: " + refSeventeen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refSeventeen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refSeventeen.tyreType);
System.out.println("The batteryType is: " + refSeventeen.batteryType);
System.out.println("The navigationSystem is: " + refSeventeen.navigationSystem);
System.out.println("The musicSystem is: " + refSeventeen.musicSystem);
System.out.println("The isElectric is: " + refSeventeen.isElectric);
Car refEighteen = new Car();

System.out.println("The carModel is: " + refEighteen.carModel);
System.out.println("The carColor is: " + refEighteen.carColor);
System.out.println("The manufacturingYear is: " + refEighteen.manufacturingYear);
System.out.println("The price is: " + refEighteen.price);
System.out.println("The fuelType is: " + refEighteen.fuelType);
System.out.println("The seatingCapacity is: " + refEighteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refEighteen.engineCapacity);
System.out.println("The transmissionType is: " + refEighteen.transmissionType);
System.out.println("The numberOfDoors is: " + refEighteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refEighteen.isAutomatic);
System.out.println("The hasSunroof is: " + refEighteen.hasSunroof);
System.out.println("The hasAirbags is: " + refEighteen.hasAirbags);
System.out.println("The hasABS is: " + refEighteen.hasABS);
System.out.println("The mileage is: " + refEighteen.mileage);
System.out.println("The registrationNumber is: " + refEighteen.registrationNumber);
System.out.println("The ownerName is: " + refEighteen.ownerName);
System.out.println("The insuranceProvider is: " + refEighteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refEighteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refEighteen.tyreType);
System.out.println("The batteryType is: " + refEighteen.batteryType);
System.out.println("The navigationSystem is: " + refEighteen.navigationSystem);
System.out.println("The musicSystem is: " + refEighteen.musicSystem);
System.out.println("The isElectric is: " + refEighteen.isElectric);

refEighteen.carId = 18;
refEighteen.carBrand = "Kia";
refEighteen.carModel = "Seltos";
refEighteen.carColor = "Orange";
refEighteen.manufacturingYear = 2023;
refEighteen.price = 1900000;
refEighteen.fuelType = "Diesel";
refEighteen.seatingCapacity = 5;
refEighteen.engineCapacity = 1.5;
refEighteen.transmissionType = "Automatic";
refEighteen.numberOfDoors = 4;
refEighteen.isAutomatic = true;
refEighteen.hasSunroof = true;
refEighteen.hasAirbags = true;
refEighteen.hasABS = true;
refEighteen.mileage = 18.0;
refEighteen.registrationNumber = "KA18JK7878";
refEighteen.ownerName = "Vijay";
refEighteen.insuranceProvider = "Bajaj";
refEighteen.insuranceExpiryDate = "2028-07-25";
refEighteen.tyreType = "Tubeless";
refEighteen.batteryType = "Lithium";
refEighteen.navigationSystem = "GPS";
refEighteen.musicSystem = "Harman";
refEighteen.isElectric = false;

System.out.println("The carId is: " + refEighteen.carId);
System.out.println("The carBrand is: " + refEighteen.carBrand);
System.out.println("The carModel is: " + refEighteen.carModel);
System.out.println("The carColor is: " + refEighteen.carColor);
System.out.println("The manufacturingYear is: " + refEighteen.manufacturingYear);
System.out.println("The price is: " + refEighteen.price);
System.out.println("The fuelType is: " + refEighteen.fuelType);
System.out.println("The seatingCapacity is: " + refEighteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refEighteen.engineCapacity);
System.out.println("The transmissionType is: " + refEighteen.transmissionType);
System.out.println("The numberOfDoors is: " + refEighteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refEighteen.isAutomatic);
System.out.println("The hasSunroof is: " + refEighteen.hasSunroof);
System.out.println("The hasAirbags is: " + refEighteen.hasAirbags);
System.out.println("The hasABS is: " + refEighteen.hasABS);
System.out.println("The mileage is: " + refEighteen.mileage);
System.out.println("The registrationNumber is: " + refEighteen.registrationNumber);
System.out.println("The ownerName is: " + refEighteen.ownerName);
System.out.println("The insuranceProvider is: " + refEighteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refEighteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refEighteen.tyreType);
System.out.println("The batteryType is: " + refEighteen.batteryType);
System.out.println("The navigationSystem is: " + refEighteen.navigationSystem);
System.out.println("The musicSystem is: " + refEighteen.musicSystem);
System.out.println("The isElectric is: " + refEighteen.isElectric);
Car refNineteen = new Car();

System.out.println("The carModel is: " + refNineteen.carModel);
System.out.println("The carColor is: " + refNineteen.carColor);
System.out.println("The manufacturingYear is: " + refNineteen.manufacturingYear);
System.out.println("The price is: " + refNineteen.price);
System.out.println("The fuelType is: " + refNineteen.fuelType);
System.out.println("The seatingCapacity is: " + refNineteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refNineteen.engineCapacity);
System.out.println("The transmissionType is: " + refNineteen.transmissionType);
System.out.println("The numberOfDoors is: " + refNineteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refNineteen.isAutomatic);
System.out.println("The hasSunroof is: " + refNineteen.hasSunroof);
System.out.println("The hasAirbags is: " + refNineteen.hasAirbags);
System.out.println("The hasABS is: " + refNineteen.hasABS);
System.out.println("The mileage is: " + refNineteen.mileage);
System.out.println("The registrationNumber is: " + refNineteen.registrationNumber);
System.out.println("The ownerName is: " + refNineteen.ownerName);
System.out.println("The insuranceProvider is: " + refNineteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refNineteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refNineteen.tyreType);
System.out.println("The batteryType is: " + refNineteen.batteryType);
System.out.println("The navigationSystem is: " + refNineteen.navigationSystem);
System.out.println("The musicSystem is: " + refNineteen.musicSystem);
System.out.println("The isElectric is: " + refNineteen.isElectric);

refNineteen.carId = 19;
refNineteen.carBrand = "Toyota";
refNineteen.carModel = "Fortuner";
refNineteen.carColor = "Black";
refNineteen.manufacturingYear = 2024;
refNineteen.price = 4200000;
refNineteen.fuelType = "Diesel";
refNineteen.seatingCapacity = 7;
refNineteen.engineCapacity = 2.8;
refNineteen.transmissionType = "Automatic";
refNineteen.numberOfDoors = 4;
refNineteen.isAutomatic = true;
refNineteen.hasSunroof = true;
refNineteen.hasAirbags = true;
refNineteen.hasABS = true;
refNineteen.mileage = 14.2;
refNineteen.registrationNumber = "KA19LM9090";
refNineteen.ownerName = "Ajay";
refNineteen.insuranceProvider = "ICICI";
refNineteen.insuranceExpiryDate = "2029-01-15";
refNineteen.tyreType = "Tubeless";
refNineteen.batteryType = "Lithium";
refNineteen.navigationSystem = "GPS";
refNineteen.musicSystem = "JBL";
refNineteen.isElectric = false;

System.out.println("The carId is: " + refNineteen.carId);
System.out.println("The carBrand is: " + refNineteen.carBrand);
System.out.println("The carModel is: " + refNineteen.carModel);
System.out.println("The carColor is: " + refNineteen.carColor);
System.out.println("The manufacturingYear is: " + refNineteen.manufacturingYear);
System.out.println("The price is: " + refNineteen.price);
System.out.println("The fuelType is: " + refNineteen.fuelType);
System.out.println("The seatingCapacity is: " + refNineteen.seatingCapacity);
System.out.println("The engineCapacity is: " + refNineteen.engineCapacity);
System.out.println("The transmissionType is: " + refNineteen.transmissionType);
System.out.println("The numberOfDoors is: " + refNineteen.numberOfDoors);
System.out.println("The isAutomatic is: " + refNineteen.isAutomatic);
System.out.println("The hasSunroof is: " + refNineteen.hasSunroof);
System.out.println("The hasAirbags is: " + refNineteen.hasAirbags);
System.out.println("The hasABS is: " + refNineteen.hasABS);
System.out.println("The mileage is: " + refNineteen.mileage);
System.out.println("The registrationNumber is: " + refNineteen.registrationNumber);
System.out.println("The ownerName is: " + refNineteen.ownerName);
System.out.println("The insuranceProvider is: " + refNineteen.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refNineteen.insuranceExpiryDate);
System.out.println("The tyreType is: " + refNineteen.tyreType);
System.out.println("The batteryType is: " + refNineteen.batteryType);
System.out.println("The navigationSystem is: " + refNineteen.navigationSystem);
System.out.println("The musicSystem is: " + refNineteen.musicSystem);
System.out.println("The isElectric is: " + refNineteen.isElectric);
Car refTwenty = new Car();

System.out.println("The carModel is: " + refTwenty.carModel);
System.out.println("The carColor is: " + refTwenty.carColor);
System.out.println("The manufacturingYear is: " + refTwenty.manufacturingYear);
System.out.println("The price is: " + refTwenty.price);
System.out.println("The fuelType is: " + refTwenty.fuelType);
System.out.println("The seatingCapacity is: " + refTwenty.seatingCapacity);
System.out.println("The engineCapacity is: " + refTwenty.engineCapacity);
System.out.println("The transmissionType is: " + refTwenty.transmissionType);
System.out.println("The numberOfDoors is: " + refTwenty.numberOfDoors);
System.out.println("The isAutomatic is: " + refTwenty.isAutomatic);
System.out.println("The hasSunroof is: " + refTwenty.hasSunroof);
System.out.println("The hasAirbags is: " + refTwenty.hasAirbags);
System.out.println("The hasABS is: " + refTwenty.hasABS);
System.out.println("The mileage is: " + refTwenty.mileage);
System.out.println("The registrationNumber is: " + refTwenty.registrationNumber);
System.out.println("The ownerName is: " + refTwenty.ownerName);
System.out.println("The insuranceProvider is: " + refTwenty.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refTwenty.insuranceExpiryDate);
System.out.println("The tyreType is: " + refTwenty.tyreType);
System.out.println("The batteryType is: " + refTwenty.batteryType);
System.out.println("The navigationSystem is: " + refTwenty.navigationSystem);
System.out.println("The musicSystem is: " + refTwenty.musicSystem);
System.out.println("The isElectric is: " + refTwenty.isElectric);

refTwenty.carId = 20;
refTwenty.carBrand = "Mahindra";
refTwenty.carModel = "XUV700";
refTwenty.carColor = "Blue";
refTwenty.manufacturingYear = 2024;
refTwenty.price = 2500000;
refTwenty.fuelType = "Petrol";
refTwenty.seatingCapacity = 7;
refTwenty.engineCapacity = 2.0;
refTwenty.transmissionType = "Automatic";
refTwenty.numberOfDoors = 4;
refTwenty.isAutomatic = true;
refTwenty.hasSunroof = true;
refTwenty.hasAirbags = true;
refTwenty.hasABS = true;
refTwenty.mileage = 15.0;
refTwenty.registrationNumber = "KA20QR4545";
refTwenty.ownerName = "Ravi";
refTwenty.insuranceProvider = "HDFC";
refTwenty.insuranceExpiryDate = "2029-03-30";
refTwenty.tyreType = "Tubeless";
refTwenty.batteryType = "Lithium";
refTwenty.navigationSystem = "Advanced GPS";
refTwenty.musicSystem = "Sony";
refTwenty.isElectric = false;

System.out.println("The carId is: " + refTwenty.carId);
System.out.println("The carBrand is: " + refTwenty.carBrand);
System.out.println("The carModel is: " + refTwenty.carModel);
System.out.println("The carColor is: " + refTwenty.carColor);
System.out.println("The manufacturingYear is: " + refTwenty.manufacturingYear);
System.out.println("The price is: " + refTwenty.price);
System.out.println("The fuelType is: " + refTwenty.fuelType);
System.out.println("The seatingCapacity is: " + refTwenty.seatingCapacity);
System.out.println("The engineCapacity is: " + refTwenty.engineCapacity);
System.out.println("The transmissionType is: " + refTwenty.transmissionType);
System.out.println("The numberOfDoors is: " + refTwenty.numberOfDoors);
System.out.println("The isAutomatic is: " + refTwenty.isAutomatic);
System.out.println("The hasSunroof is: " + refTwenty.hasSunroof);
System.out.println("The hasAirbags is: " + refTwenty.hasAirbags);
System.out.println("The hasABS is: " + refTwenty.hasABS);
System.out.println("The mileage is: " + refTwenty.mileage);
System.out.println("The registrationNumber is: " + refTwenty.registrationNumber);
System.out.println("The ownerName is: " + refTwenty.ownerName);
System.out.println("The insuranceProvider is: " + refTwenty.insuranceProvider);
System.out.println("The insuranceExpiryDate is: " + refTwenty.insuranceExpiryDate);
System.out.println("The tyreType is: " + refTwenty.tyreType);
System.out.println("The batteryType is: " + refTwenty.batteryType);
System.out.println("The navigationSystem is: " + refTwenty.navigationSystem);
System.out.println("The musicSystem is: " + refTwenty.musicSystem);
System.out.println("The isElectric is: " + refTwenty.isElectric);
	}
}