class CaseEvidenceExecutor {
    public static void main(String[] args) {

        CaseEvidence e1 = new CaseEvidence();
        e1.setEvidenceId(1);
        e1.setCaseName("Case1");
        e1.setEvidenceType("Fingerprint");
        e1.setDescription("Desc1");
        e1.setCollectedBy("Officer1");
        e1.setCollectedDate("2024-01-01");
        e1.setLocation("Location1");
        System.out.println(e1.getEvidenceId());
        System.out.println(e1.getCaseName());
        System.out.println(e1.getEvidenceType());
        System.out.println(e1.getDescription());
        System.out.println(e1.getCollectedBy());
        System.out.println(e1.getCollectedDate());
        System.out.println(e1.getLocation());

        CaseEvidence e2 = new CaseEvidence();
        e2.setEvidenceId(2);
        e2.setCaseName("Case2");
        e2.setEvidenceType("DNA");
        e2.setDescription("Desc2");
        e2.setCollectedBy("Officer2");
        e2.setCollectedDate("2024-01-02");
        e2.setLocation("Location2");
        System.out.println(e2.getEvidenceId());
        System.out.println(e2.getCaseName());
        System.out.println(e2.getEvidenceType());
        System.out.println(e2.getDescription());
        System.out.println(e2.getCollectedBy());
        System.out.println(e2.getCollectedDate());
        System.out.println(e2.getLocation());

        CaseEvidence e3 = new CaseEvidence();
        e3.setEvidenceId(3);
        e3.setCaseName("Case3");
        e3.setEvidenceType("Weapon");
        e3.setDescription("Desc3");
        e3.setCollectedBy("Officer3");
        e3.setCollectedDate("2024-01-03");
        e3.setLocation("Location3");
        System.out.println(e3.getEvidenceId());
        System.out.println(e3.getCaseName());
        System.out.println(e3.getEvidenceType());
        System.out.println(e3.getDescription());
        System.out.println(e3.getCollectedBy());
        System.out.println(e3.getCollectedDate());
        System.out.println(e3.getLocation());

        CaseEvidence e4 = new CaseEvidence();
        e4.setEvidenceId(4);
        e4.setCaseName("Case4");
        e4.setEvidenceType("Fingerprint");
        e4.setDescription("Desc4");
        e4.setCollectedBy("Officer4");
        e4.setCollectedDate("2024-01-04");
        e4.setLocation("Location4");
        System.out.println(e4.getEvidenceId());
        System.out.println(e4.getCaseName());
        System.out.println(e4.getEvidenceType());
        System.out.println(e4.getDescription());
        System.out.println(e4.getCollectedBy());
        System.out.println(e4.getCollectedDate());
        System.out.println(e4.getLocation());

        CaseEvidence e5 = new CaseEvidence();
        e5.setEvidenceId(5);
        e5.setCaseName("Case5");
        e5.setEvidenceType("DNA");
        e5.setDescription("Desc5");
        e5.setCollectedBy("Officer5");
        e5.setCollectedDate("2024-01-05");
        e5.setLocation("Location5");
        System.out.println(e5.getEvidenceId());
        System.out.println(e5.getCaseName());
        System.out.println(e5.getEvidenceType());
        System.out.println(e5.getDescription());
        System.out.println(e5.getCollectedBy());
        System.out.println(e5.getCollectedDate());
        System.out.println(e5.getLocation());

        CaseEvidence e6 = new CaseEvidence();
        e6.setEvidenceId(6);
        e6.setCaseName("Case6");
        e6.setEvidenceType("Weapon");
        e6.setDescription("Desc6");
        e6.setCollectedBy("Officer6");
        e6.setCollectedDate("2024-01-06");
        e6.setLocation("Location6");
        System.out.println(e6.getEvidenceId());
        System.out.println(e6.getCaseName());
        System.out.println(e6.getEvidenceType());
        System.out.println(e6.getDescription());
        System.out.println(e6.getCollectedBy());
        System.out.println(e6.getCollectedDate());
        System.out.println(e6.getLocation());

        CaseEvidence e7 = new CaseEvidence();
        e7.setEvidenceId(7);
        e7.setCaseName("Case7");
        e7.setEvidenceType("Fingerprint");
        e7.setDescription("Desc7");
        e7.setCollectedBy("Officer7");
        e7.setCollectedDate("2024-01-07");
        e7.setLocation("Location7");
        System.out.println(e7.getEvidenceId());
        System.out.println(e7.getCaseName());
        System.out.println(e7.getEvidenceType());
        System.out.println(e7.getDescription());
        System.out.println(e7.getCollectedBy());
        System.out.println(e7.getCollectedDate());
        System.out.println(e7.getLocation());

        CaseEvidence e8 = new CaseEvidence();
        e8.setEvidenceId(8);
        e8.setCaseName("Case8");
        e8.setEvidenceType("DNA");
        e8.setDescription("Desc8");
        e8.setCollectedBy("Officer8");
        e8.setCollectedDate("2024-01-08");
        e8.setLocation("Location8");
        System.out.println(e8.getEvidenceId());
        System.out.println(e8.getCaseName());
        System.out.println(e8.getEvidenceType());
        System.out.println(e8.getDescription());
        System.out.println(e8.getCollectedBy());
        System.out.println(e8.getCollectedDate());
        System.out.println(e8.getLocation());

        CaseEvidence e9 = new CaseEvidence();
        e9.setEvidenceId(9);
        e9.setCaseName("Case9");
        e9.setEvidenceType("Weapon");
        e9.setDescription("Desc9");
        e9.setCollectedBy("Officer9");
        e9.setCollectedDate("2024-01-09");
        e9.setLocation("Location9");
        System.out.println(e9.getEvidenceId());
        System.out.println(e9.getCaseName());
        System.out.println(e9.getEvidenceType());
        System.out.println(e9.getDescription());
        System.out.println(e9.getCollectedBy());
        System.out.println(e9.getCollectedDate());
        System.out.println(e9.getLocation());

        CaseEvidence e10 = new CaseEvidence();
        e10.setEvidenceId(10);
        e10.setCaseName("Case10");
        e10.setEvidenceType("Fingerprint");
        e10.setDescription("Desc10");
        e10.setCollectedBy("Officer10");
        e10.setCollectedDate("2024-01-10");
        e10.setLocation("Location10");
        System.out.println(e10.getEvidenceId());
        System.out.println(e10.getCaseName());
        System.out.println(e10.getEvidenceType());
        System.out.println(e10.getDescription());
        System.out.println(e10.getCollectedBy());
        System.out.println(e10.getCollectedDate());
        System.out.println(e10.getLocation());

        CaseEvidence e11 = new CaseEvidence();
        e11.setEvidenceId(11);
        e11.setCaseName("Case11");
        e11.setEvidenceType("DNA");
        e11.setDescription("Desc11");
        e11.setCollectedBy("Officer11");
        e11.setCollectedDate("2024-01-11");
        e11.setLocation("Location11");
        System.out.println(e11.getEvidenceId());
        System.out.println(e11.getCaseName());
        System.out.println(e11.getEvidenceType());
        System.out.println(e11.getDescription());
        System.out.println(e11.getCollectedBy());
        System.out.println(e11.getCollectedDate());
        System.out.println(e11.getLocation());

        CaseEvidence e12 = new CaseEvidence();
        e12.setEvidenceId(12);
        e12.setCaseName("Case12");
        e12.setEvidenceType("Weapon");
        e12.setDescription("Desc12");
        e12.setCollectedBy("Officer12");
        e12.setCollectedDate("2024-01-12");
        e12.setLocation("Location12");
        System.out.println(e12.getEvidenceId());
        System.out.println(e12.getCaseName());
        System.out.println(e12.getEvidenceType());
        System.out.println(e12.getDescription());
        System.out.println(e12.getCollectedBy());
        System.out.println(e12.getCollectedDate());
        System.out.println(e12.getLocation());

        CaseEvidence e13 = new CaseEvidence();
        e13.setEvidenceId(13);
        e13.setCaseName("Case13");
        e13.setEvidenceType("Fingerprint");
        e13.setDescription("Desc13");
        e13.setCollectedBy("Officer13");
        e13.setCollectedDate("2024-01-13");
        e13.setLocation("Location13");
        System.out.println(e13.getEvidenceId());
        System.out.println(e13.getCaseName());
        System.out.println(e13.getEvidenceType());
        System.out.println(e13.getDescription());
        System.out.println(e13.getCollectedBy());
        System.out.println(e13.getCollectedDate());
        System.out.println(e13.getLocation());

        CaseEvidence e14 = new CaseEvidence();
        e14.setEvidenceId(14);
        e14.setCaseName("Case14");
        e14.setEvidenceType("DNA");
        e14.setDescription("Desc14");
        e14.setCollectedBy("Officer14");
        e14.setCollectedDate("2024-01-14");
        e14.setLocation("Location14");
        System.out.println(e14.getEvidenceId());
        System.out.println(e14.getCaseName());
        System.out.println(e14.getEvidenceType());
        System.out.println(e14.getDescription());
        System.out.println(e14.getCollectedBy());
        System.out.println(e14.getCollectedDate());
        System.out.println(e14.getLocation());

        CaseEvidence e15 = new CaseEvidence();
        e15.setEvidenceId(15);
        e15.setCaseName("Case15");
        e15.setEvidenceType("Weapon");
        e15.setDescription("Desc15");
        e15.setCollectedBy("Officer15");
        e15.setCollectedDate("2024-01-15");
        e15.setLocation("Location15");
        System.out.println(e15.getEvidenceId());
        System.out.println(e15.getCaseName());
        System.out.println(e15.getEvidenceType());
        System.out.println(e15.getDescription());
        System.out.println(e15.getCollectedBy());
        System.out.println(e15.getCollectedDate());
        System.out.println(e15.getLocation());

        CaseEvidence e16 = new CaseEvidence();
        e16.setEvidenceId(16);
        e16.setCaseName("Case16");
        e16.setEvidenceType("Fingerprint");
        e16.setDescription("Desc16");
        e16.setCollectedBy("Officer16");
        e16.setCollectedDate("2024-01-16");
        e16.setLocation("Location16");
        System.out.println(e16.getEvidenceId());
        System.out.println(e16.getCaseName());
        System.out.println(e16.getEvidenceType());
        System.out.println(e16.getDescription());
        System.out.println(e16.getCollectedBy());
        System.out.println(e16.getCollectedDate());
        System.out.println(e16.getLocation());

        CaseEvidence e17 = new CaseEvidence();
        e17.setEvidenceId(17);
        e17.setCaseName("Case17");
        e17.setEvidenceType("DNA");
        e17.setDescription("Desc17");
        e17.setCollectedBy("Officer17");
        e17.setCollectedDate("2024-01-17");
        e17.setLocation("Location17");
        System.out.println(e17.getEvidenceId());
        System.out.println(e17.getCaseName());
        System.out.println(e17.getEvidenceType());
        System.out.println(e17.getDescription());
        System.out.println(e17.getCollectedBy());
        System.out.println(e17.getCollectedDate());
        System.out.println(e17.getLocation());

        CaseEvidence e18 = new CaseEvidence();
        e18.setEvidenceId(18);
        e18.setCaseName("Case18");
        e18.setEvidenceType("Weapon");
        e18.setDescription("Desc18");
        e18.setCollectedBy("Officer18");
        e18.setCollectedDate("2024-01-18");
        e18.setLocation("Location18");
        System.out.println(e18.getEvidenceId());
        System.out.println(e18.getCaseName());
        System.out.println(e18.getEvidenceType());
        System.out.println(e18.getDescription());
        System.out.println(e18.getCollectedBy());
        System.out.println(e18.getCollectedDate());
        System.out.println(e18.getLocation());

        CaseEvidence e19 = new CaseEvidence();
        e19.setEvidenceId(19);
        e19.setCaseName("Case19");
        e19.setEvidenceType("Fingerprint");
        e19.setDescription("Desc19");
        e19.setCollectedBy("Officer19");
        e19.setCollectedDate("2024-01-19");
        e19.setLocation("Location19");
        System.out.println(e19.getEvidenceId());
        System.out.println(e19.getCaseName());
        System.out.println(e19.getEvidenceType());
        System.out.println(e19.getDescription());
        System.out.println(e19.getCollectedBy());
        System.out.println(e19.getCollectedDate());
        System.out.println(e19.getLocation());

        CaseEvidence e20 = new CaseEvidence();
        e20.setEvidenceId(20);
        e20.setCaseName("Case20");
        e20.setEvidenceType("DNA");
        e20.setDescription("Desc20");
        e20.setCollectedBy("Officer20");
        e20.setCollectedDate("2024-01-20");
        e20.setLocation("Location20");
        System.out.println(e20.getEvidenceId());
        System.out.println(e20.getCaseName());
        System.out.println(e20.getEvidenceType());
        System.out.println(e20.getDescription());
        System.out.println(e20.getCollectedBy());
        System.out.println(e20.getCollectedDate());
        System.out.println(e20.getLocation());

        CaseEvidence e21 = new CaseEvidence();
        e21.setEvidenceId(21);
        e21.setCaseName("Case21");
        e21.setEvidenceType("Weapon");
        e21.setDescription("Desc21");
        e21.setCollectedBy("Officer21");
        e21.setCollectedDate("2024-01-21");
        e21.setLocation("Location21");
        System.out.println(e21.getEvidenceId());
        System.out.println(e21.getCaseName());
        System.out.println(e21.getEvidenceType());
        System.out.println(e21.getDescription());
        System.out.println(e21.getCollectedBy());
        System.out.println(e21.getCollectedDate());
        System.out.println(e21.getLocation());

        CaseEvidence e22 = new CaseEvidence();
        e22.setEvidenceId(22);
        e22.setCaseName("Case22");
        e22.setEvidenceType("Fingerprint");
        e22.setDescription("Desc22");
        e22.setCollectedBy("Officer22");
        e22.setCollectedDate("2024-01-22");
        e22.setLocation("Location22");
        System.out.println(e22.getEvidenceId());
        System.out.println(e22.getCaseName());
        System.out.println(e22.getEvidenceType());
        System.out.println(e22.getDescription());
        System.out.println(e22.getCollectedBy());
        System.out.println(e22.getCollectedDate());
        System.out.println(e22.getLocation());

        CaseEvidence e23 = new CaseEvidence();
        e23.setEvidenceId(23);
        e23.setCaseName("Case23");
        e23.setEvidenceType("DNA");
        e23.setDescription("Desc23");
        e23.setCollectedBy("Officer23");
        e23.setCollectedDate("2024-01-23");
        e23.setLocation("Location23");
        System.out.println(e23.getEvidenceId());
        System.out.println(e23.getCaseName());
        System.out.println(e23.getEvidenceType());
        System.out.println(e23.getDescription());
        System.out.println(e23.getCollectedBy());
        System.out.println(e23.getCollectedDate());
        System.out.println(e23.getLocation());

        CaseEvidence e24 = new CaseEvidence();
        e24.setEvidenceId(24);
        e24.setCaseName("Case24");
        e24.setEvidenceType("Weapon");
        e24.setDescription("Desc24");
        e24.setCollectedBy("Officer24");
        e24.setCollectedDate("2024-01-24");
        e24.setLocation("Location24");
        System.out.println(e24.getEvidenceId());
        System.out.println(e24.getCaseName());
        System.out.println(e24.getEvidenceType());
        System.out.println(e24.getDescription());
        System.out.println(e24.getCollectedBy());
        System.out.println(e24.getCollectedDate());
        System.out.println(e24.getLocation());

        CaseEvidence e25 = new CaseEvidence();
        e25.setEvidenceId(25);
        e25.setCaseName("Case25");
        e25.setEvidenceType("Fingerprint");
        e25.setDescription("Desc25");
        e25.setCollectedBy("Officer25");
        e25.setCollectedDate("2024-01-25");
        e25.setLocation("Location25");
        System.out.println(e25.getEvidenceId());
        System.out.println(e25.getCaseName());
        System.out.println(e25.getEvidenceType());
        System.out.println(e25.getDescription());
        System.out.println(e25.getCollectedBy());
        System.out.println(e25.getCollectedDate());
        System.out.println(e25.getLocation());

        CaseEvidence e26 = new CaseEvidence();
        e26.setEvidenceId(26);
        e26.setCaseName("Case26");
        e26.setEvidenceType("DNA");
        e26.setDescription("Desc26");
        e26.setCollectedBy("Officer26");
        e26.setCollectedDate("2024-01-26");
        e26.setLocation("Location26");
        System.out.println(e26.getEvidenceId());
        System.out.println(e26.getCaseName());
        System.out.println(e26.getEvidenceType());
        System.out.println(e26.getDescription());
        System.out.println(e26.getCollectedBy());
        System.out.println(e26.getCollectedDate());
        System.out.println(e26.getLocation());

        CaseEvidence e27 = new CaseEvidence();
        e27.setEvidenceId(27);
        e27.setCaseName("Case27");
        e27.setEvidenceType("Weapon");
        e27.setDescription("Desc27");
        e27.setCollectedBy("Officer27");
        e27.setCollectedDate("2024-01-27");
        e27.setLocation("Location27");
        System.out.println(e27.getEvidenceId());
        System.out.println(e27.getCaseName());
        System.out.println(e27.getEvidenceType());
        System.out.println(e27.getDescription());
        System.out.println(e27.getCollectedBy());
        System.out.println(e27.getCollectedDate());
        System.out.println(e27.getLocation());

        CaseEvidence e28 = new CaseEvidence();
        e28.setEvidenceId(28);
        e28.setCaseName("Case28");
        e28.setEvidenceType("Fingerprint");
        e28.setDescription("Desc28");
        e28.setCollectedBy("Officer28");
        e28.setCollectedDate("2024-01-28");
        e28.setLocation("Location28");
        System.out.println(e28.getEvidenceId());
        System.out.println(e28.getCaseName());
        System.out.println(e28.getEvidenceType());
        System.out.println(e28.getDescription());
        System.out.println(e28.getCollectedBy());
        System.out.println(e28.getCollectedDate());
        System.out.println(e28.getLocation());

        CaseEvidence e29 = new CaseEvidence();
        e29.setEvidenceId(29);
        e29.setCaseName("Case29");
        e29.setEvidenceType("DNA");
        e29.setDescription("Desc29");
        e29.setCollectedBy("Officer29");
        e29.setCollectedDate("2024-01-29");
        e29.setLocation("Location29");
        System.out.println(e29.getEvidenceId());
        System.out.println(e29.getCaseName());
        System.out.println(e29.getEvidenceType());
        System.out.println(e29.getDescription());
        System.out.println(e29.getCollectedBy());
        System.out.println(e29.getCollectedDate());
        System.out.println(e29.getLocation());
    }
}