class CollegeExecutor{
public static void main(String[] args){
College refOne = new College();

System.out.println("The collegeId is: " + refOne.collegeId);
System.out.println("The collegeName is: " + refOne.collegeName);
System.out.println("The principalName is: " + refOne.principalName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfDepartments is: " + refOne.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refOne.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refOne.numberOfFaculty);
System.out.println("The hasLibrary is: " + refOne.hasLibrary);
System.out.println("The hasLaboratory is: " + refOne.hasLaboratory);
System.out.println("The hasHostel is: " + refOne.hasHostel);
System.out.println("The hasCafeteria is: " + refOne.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refOne.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refOne.hasComputerLab);
System.out.println("The hasAuditorium is: " + refOne.hasAuditorium);
System.out.println("The universityAffiliation is: " + refOne.universityAffiliation);
System.out.println("The accreditation is: " + refOne.accreditation);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The collegeType is: " + refOne.collegeType);
System.out.println("The coursesOffered is: " + refOne.coursesOffered);


refOne.collegeId = 1;
refOne.collegeName = "Bapuji Institute of Engineering and Technology";
refOne.principalName = "Dr. H. V. Ravishankar";
refOne.location = "Shamanur Road";
refOne.city = "Davangere";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfDepartments = 12;
refOne.numberOfStudents = 4500;
refOne.numberOfFaculty = 220;
refOne.hasLibrary = true;
refOne.hasLaboratory = true;
refOne.hasHostel = true;
refOne.hasCafeteria = true;
refOne.hasSportsFacility = true;
refOne.hasComputerLab = true;
refOne.hasAuditorium = true;
refOne.universityAffiliation = "VTU";
refOne.accreditation = "NAAC A";
refOne.establishedYear = 1979;
refOne.contactNumber = "08192222333";
refOne.email = "info@bietdvg.edu";
refOne.website = "www.bietdvg.edu";
refOne.collegeType = "Engineering";
refOne.coursesOffered = "CSE, ECE, ME, CIVIL, ISE";

System.out.println("The collegeId is: " + refOne.collegeId);
System.out.println("The collegeName is: " + refOne.collegeName);
System.out.println("The principalName is: " + refOne.principalName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfDepartments is: " + refOne.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refOne.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refOne.numberOfFaculty);
System.out.println("The hasLibrary is: " + refOne.hasLibrary);
System.out.println("The hasLaboratory is: " + refOne.hasLaboratory);
System.out.println("The hasHostel is: " + refOne.hasHostel);
System.out.println("The hasCafeteria is: " + refOne.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refOne.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refOne.hasComputerLab);
System.out.println("The hasAuditorium is: " + refOne.hasAuditorium);
System.out.println("The universityAffiliation is: " + refOne.universityAffiliation);
System.out.println("The accreditation is: " + refOne.accreditation);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The collegeType is: " + refOne.collegeType);
System.out.println("The coursesOffered is: " + refOne.coursesOffered);
College refTwo = new College();

System.out.println("The collegeId is: " + refTwo.collegeId);
System.out.println("The collegeName is: " + refTwo.collegeName);
System.out.println("The principalName is: " + refTwo.principalName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfDepartments is: " + refTwo.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refTwo.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refTwo.numberOfFaculty);
System.out.println("The hasLibrary is: " + refTwo.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwo.hasLaboratory);
System.out.println("The hasHostel is: " + refTwo.hasHostel);
System.out.println("The hasCafeteria is: " + refTwo.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refTwo.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refTwo.hasComputerLab);
System.out.println("The hasAuditorium is: " + refTwo.hasAuditorium);
System.out.println("The universityAffiliation is: " + refTwo.universityAffiliation);
System.out.println("The accreditation is: " + refTwo.accreditation);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The collegeType is: " + refTwo.collegeType);
System.out.println("The coursesOffered is: " + refTwo.coursesOffered);

refTwo.collegeId = 2;
refTwo.collegeName = "National Institute of Technology";
refTwo.principalName = "Dr. Anil Kumar";
refTwo.location = "Surathkal";
refTwo.city = "Mangalore";
refTwo.state = "Karnataka";
refTwo.country = "India";
refTwo.numberOfDepartments = 10;
refTwo.numberOfStudents = 6000;
refTwo.numberOfFaculty = 300;
refTwo.hasLibrary = true;
refTwo.hasLaboratory = true;
refTwo.hasHostel = true;
refTwo.hasCafeteria = true;
refTwo.hasSportsFacility = true;
refTwo.hasComputerLab = true;
refTwo.hasAuditorium = true;
refTwo.universityAffiliation = "Autonomous";
refTwo.accreditation = "NAAC A+";
refTwo.establishedYear = 1960;
refTwo.contactNumber = "08242470000";
refTwo.email = "info@nitk.edu";
refTwo.website = "www.nitk.ac.in";
refTwo.collegeType = "Engineering";
refTwo.coursesOffered = "CSE, ECE, EEE, Mechanical, Civil";

System.out.println("The collegeId is: " + refTwo.collegeId);
System.out.println("The collegeName is: " + refTwo.collegeName);
System.out.println("The principalName is: " + refTwo.principalName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfDepartments is: " + refTwo.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refTwo.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refTwo.numberOfFaculty);
System.out.println("The hasLibrary is: " + refTwo.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwo.hasLaboratory);
System.out.println("The hasHostel is: " + refTwo.hasHostel);
System.out.println("The hasCafeteria is: " + refTwo.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refTwo.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refTwo.hasComputerLab);
System.out.println("The hasAuditorium is: " + refTwo.hasAuditorium);
System.out.println("The universityAffiliation is: " + refTwo.universityAffiliation);
System.out.println("The accreditation is: " + refTwo.accreditation);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The collegeType is: " + refTwo.collegeType);
System.out.println("The coursesOffered is: " + refTwo.coursesOffered);
College refThree = new College();

System.out.println("The collegeId is: " + refThree.collegeId);
System.out.println("The collegeName is: " + refThree.collegeName);
System.out.println("The principalName is: " + refThree.principalName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfDepartments is: " + refThree.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refThree.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refThree.numberOfFaculty);
System.out.println("The hasLibrary is: " + refThree.hasLibrary);
System.out.println("The hasLaboratory is: " + refThree.hasLaboratory);
System.out.println("The hasHostel is: " + refThree.hasHostel);
System.out.println("The hasCafeteria is: " + refThree.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refThree.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refThree.hasComputerLab);
System.out.println("The hasAuditorium is: " + refThree.hasAuditorium);
System.out.println("The universityAffiliation is: " + refThree.universityAffiliation);
System.out.println("The accreditation is: " + refThree.accreditation);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The collegeType is: " + refThree.collegeType);
System.out.println("The coursesOffered is: " + refThree.coursesOffered);

refThree.collegeId = 3;
refThree.collegeName = "RV College of Engineering";
refThree.principalName = "Dr. Ramesh Babu";
refThree.location = "Mysore Road";
refThree.city = "Bengaluru";
refThree.state = "Karnataka";
refThree.country = "India";
refThree.numberOfDepartments = 14;
refThree.numberOfStudents = 5500;
refThree.numberOfFaculty = 250;
refThree.hasLibrary = true;
refThree.hasLaboratory = true;
refThree.hasHostel = true;
refThree.hasCafeteria = true;
refThree.hasSportsFacility = true;
refThree.hasComputerLab = true;
refThree.hasAuditorium = true;
refThree.universityAffiliation = "VTU";
refThree.accreditation = "NAAC A+";
refThree.establishedYear = 1963;
refThree.contactNumber = "08067178000";
refThree.email = "info@rvce.edu";
refThree.website = "www.rvce.edu.in";
refThree.collegeType = "Engineering";
refThree.coursesOffered = "CSE, ISE, ECE, EEE, Mechanical, Civil";

System.out.println("The collegeId is: " + refThree.collegeId);
System.out.println("The collegeName is: " + refThree.collegeName);
System.out.println("The principalName is: " + refThree.principalName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfDepartments is: " + refThree.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refThree.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refThree.numberOfFaculty);
System.out.println("The hasLibrary is: " + refThree.hasLibrary);
System.out.println("The hasLaboratory is: " + refThree.hasLaboratory);
System.out.println("The hasHostel is: " + refThree.hasHostel);
System.out.println("The hasCafeteria is: " + refThree.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refThree.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refThree.hasComputerLab);
System.out.println("The hasAuditorium is: " + refThree.hasAuditorium);
System.out.println("The universityAffiliation is: " + refThree.universityAffiliation);
System.out.println("The accreditation is: " + refThree.accreditation);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The collegeType is: " + refThree.collegeType);
System.out.println("The coursesOffered is: " + refThree.coursesOffered);
College refFour = new College();

System.out.println("The collegeId is: " + refFour.collegeId);
System.out.println("The collegeName is: " + refFour.collegeName);
System.out.println("The principalName is: " + refFour.principalName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfDepartments is: " + refFour.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refFour.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refFour.numberOfFaculty);
System.out.println("The hasLibrary is: " + refFour.hasLibrary);
System.out.println("The hasLaboratory is: " + refFour.hasLaboratory);
System.out.println("The hasHostel is: " + refFour.hasHostel);
System.out.println("The hasCafeteria is: " + refFour.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refFour.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refFour.hasComputerLab);
System.out.println("The hasAuditorium is: " + refFour.hasAuditorium);
System.out.println("The universityAffiliation is: " + refFour.universityAffiliation);
System.out.println("The accreditation is: " + refFour.accreditation);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The collegeType is: " + refFour.collegeType);
System.out.println("The coursesOffered is: " + refFour.coursesOffered);

refFour.collegeId = 4;
refFour.collegeName = "PES University";
refFour.principalName = "Dr. Jawahar Doreswamy";
refFour.location = "Ring Road";
refFour.city = "Bengaluru";
refFour.state = "Karnataka";
refFour.country = "India";
refFour.numberOfDepartments = 15;
refFour.numberOfStudents = 7000;
refFour.numberOfFaculty = 320;
refFour.hasLibrary = true;
refFour.hasLaboratory = true;
refFour.hasHostel = true;
refFour.hasCafeteria = true;
refFour.hasSportsFacility = true;
refFour.hasComputerLab = true;
refFour.hasAuditorium = true;
refFour.universityAffiliation = "Deemed University";
refFour.accreditation = "NAAC A+";
refFour.establishedYear = 1972;
refFour.contactNumber = "08026721983";
refFour.email = "info@pes.edu";
refFour.website = "www.pes.edu";
refFour.collegeType = "Engineering";
refFour.coursesOffered = "CSE, AI, DS, ECE, Mechanical, Civil";

System.out.println("The collegeId is: " + refFour.collegeId);
System.out.println("The collegeName is: " + refFour.collegeName);
System.out.println("The principalName is: " + refFour.principalName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfDepartments is: " + refFour.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refFour.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refFour.numberOfFaculty);
System.out.println("The hasLibrary is: " + refFour.hasLibrary);
System.out.println("The hasLaboratory is: " + refFour.hasLaboratory);
System.out.println("The hasHostel is: " + refFour.hasHostel);
System.out.println("The hasCafeteria is: " + refFour.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refFour.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refFour.hasComputerLab);
System.out.println("The hasAuditorium is: " + refFour.hasAuditorium);
System.out.println("The universityAffiliation is: " + refFour.universityAffiliation);
System.out.println("The accreditation is: " + refFour.accreditation);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The collegeType is: " + refFour.collegeType);
System.out.println("The coursesOffered is: " + refFour.coursesOffered);
College refFive = new College();

System.out.println("The collegeId is: " + refFive.collegeId);
System.out.println("The collegeName is: " + refFive.collegeName);
System.out.println("The principalName is: " + refFive.principalName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfDepartments is: " + refFive.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refFive.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refFive.numberOfFaculty);
System.out.println("The hasLibrary is: " + refFive.hasLibrary);
System.out.println("The hasLaboratory is: " + refFive.hasLaboratory);
System.out.println("The hasHostel is: " + refFive.hasHostel);
System.out.println("The hasCafeteria is: " + refFive.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refFive.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refFive.hasComputerLab);
System.out.println("The hasAuditorium is: " + refFive.hasAuditorium);
System.out.println("The universityAffiliation is: " + refFive.universityAffiliation);
System.out.println("The accreditation is: " + refFive.accreditation);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The collegeType is: " + refFive.collegeType);
System.out.println("The coursesOffered is: " + refFive.coursesOffered);

refFive.collegeId = 5;
refFive.collegeName = "BMS College of Engineering";
refFive.principalName = "Dr. B. G. Sangameshwara";
refFive.location = "Basavanagudi";
refFive.city = "Bengaluru";
refFive.state = "Karnataka";
refFive.country = "India";
refFive.numberOfDepartments = 13;
refFive.numberOfStudents = 5200;
refFive.numberOfFaculty = 240;
refFive.hasLibrary = true;
refFive.hasLaboratory = true;
refFive.hasHostel = true;
refFive.hasCafeteria = true;
refFive.hasSportsFacility = true;
refFive.hasComputerLab = true;
refFive.hasAuditorium = true;
refFive.universityAffiliation = "VTU";
refFive.accreditation = "NAAC A";
refFive.establishedYear = 1946;
refFive.contactNumber = "08026622130";
refFive.email = "info@bmsce.ac.in";
refFive.website = "www.bmsce.ac.in";
refFive.collegeType = "Engineering";
refFive.coursesOffered = "CSE, ISE, ECE, EEE, Mechanical, Civil";

System.out.println("The collegeId is: " + refFive.collegeId);
System.out.println("The collegeName is: " + refFive.collegeName);
System.out.println("The principalName is: " + refFive.principalName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfDepartments is: " + refFive.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refFive.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refFive.numberOfFaculty);
System.out.println("The hasLibrary is: " + refFive.hasLibrary);
System.out.println("The hasLaboratory is: " + refFive.hasLaboratory);
System.out.println("The hasHostel is: " + refFive.hasHostel);
System.out.println("The hasCafeteria is: " + refFive.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refFive.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refFive.hasComputerLab);
System.out.println("The hasAuditorium is: " + refFive.hasAuditorium);
System.out.println("The universityAffiliation is: " + refFive.universityAffiliation);
System.out.println("The accreditation is: " + refFive.accreditation);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The collegeType is: " + refFive.collegeType);
System.out.println("The coursesOffered is: " + refFive.coursesOffered);
College refSix = new College();

System.out.println("The collegeId is: " + refSix.collegeId);
System.out.println("The collegeName is: " + refSix.collegeName);
System.out.println("The principalName is: " + refSix.principalName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfDepartments is: " + refSix.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refSix.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refSix.numberOfFaculty);
System.out.println("The hasLibrary is: " + refSix.hasLibrary);
System.out.println("The hasLaboratory is: " + refSix.hasLaboratory);
System.out.println("The hasHostel is: " + refSix.hasHostel);
System.out.println("The hasCafeteria is: " + refSix.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refSix.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refSix.hasComputerLab);
System.out.println("The hasAuditorium is: " + refSix.hasAuditorium);
System.out.println("The universityAffiliation is: " + refSix.universityAffiliation);
System.out.println("The accreditation is: " + refSix.accreditation);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The collegeType is: " + refSix.collegeType);
System.out.println("The coursesOffered is: " + refSix.coursesOffered);

refSix.collegeId = 6;
refSix.collegeName = "JSS Science and Technology University";
refSix.principalName = "Dr. B. G. Sangameshwara";
refSix.location = "Sri Jayachamarajendra College Campus";
refSix.city = "Mysuru";
refSix.state = "Karnataka";
refSix.country = "India";
refSix.numberOfDepartments = 16;
refSix.numberOfStudents = 6500;
refSix.numberOfFaculty = 280;
refSix.hasLibrary = true;
refSix.hasLaboratory = true;
refSix.hasHostel = true;
refSix.hasCafeteria = true;
refSix.hasSportsFacility = true;
refSix.hasComputerLab = true;
refSix.hasAuditorium = true;
refSix.universityAffiliation = "Autonomous";
refSix.accreditation = "NAAC A+";
refSix.establishedYear = 1963;
refSix.contactNumber = "08212541800";
refSix.email = "info@jssstuniv.in";
refSix.website = "www.jssstuniv.in";
refSix.collegeType = "Engineering";
refSix.coursesOffered = "CSE, ISE, ECE, EEE, Mechanical, Civil, AI";

System.out.println("The collegeId is: " + refSix.collegeId);
System.out.println("The collegeName is: " + refSix.collegeName);
System.out.println("The principalName is: " + refSix.principalName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfDepartments is: " + refSix.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refSix.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refSix.numberOfFaculty);
System.out.println("The hasLibrary is: " + refSix.hasLibrary);
System.out.println("The hasLaboratory is: " + refSix.hasLaboratory);
System.out.println("The hasHostel is: " + refSix.hasHostel);
System.out.println("The hasCafeteria is: " + refSix.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refSix.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refSix.hasComputerLab);
System.out.println("The hasAuditorium is: " + refSix.hasAuditorium);
System.out.println("The universityAffiliation is: " + refSix.universityAffiliation);
System.out.println("The accreditation is: " + refSix.accreditation);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The collegeType is: " + refSix.collegeType);
System.out.println("The coursesOffered is: " + refSix.coursesOffered);
College refSeven = new College();

System.out.println("The collegeId is: " + refSeven.collegeId);
System.out.println("The collegeName is: " + refSeven.collegeName);
System.out.println("The principalName is: " + refSeven.principalName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfDepartments is: " + refSeven.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refSeven.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refSeven.numberOfFaculty);
System.out.println("The hasLibrary is: " + refSeven.hasLibrary);
System.out.println("The hasLaboratory is: " + refSeven.hasLaboratory);
System.out.println("The hasHostel is: " + refSeven.hasHostel);
System.out.println("The hasCafeteria is: " + refSeven.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refSeven.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refSeven.hasComputerLab);
System.out.println("The hasAuditorium is: " + refSeven.hasAuditorium);
System.out.println("The universityAffiliation is: " + refSeven.universityAffiliation);
System.out.println("The accreditation is: " + refSeven.accreditation);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The collegeType is: " + refSeven.collegeType);
System.out.println("The coursesOffered is: " + refSeven.coursesOffered);

refSeven.collegeId = 7;
refSeven.collegeName = "MS Ramaiah Institute of Technology";
refSeven.principalName = "Dr. Kulkarni";
refSeven.location = "MSR Nagar";
refSeven.city = "Bengaluru";
refSeven.state = "Karnataka";
refSeven.country = "India";
refSeven.numberOfDepartments = 17;
refSeven.numberOfStudents = 7500;
refSeven.numberOfFaculty = 350;
refSeven.hasLibrary = true;
refSeven.hasLaboratory = true;
refSeven.hasHostel = true;
refSeven.hasCafeteria = true;
refSeven.hasSportsFacility = true;
refSeven.hasComputerLab = true;
refSeven.hasAuditorium = true;
refSeven.universityAffiliation = "VTU";
refSeven.accreditation = "NAAC A+";
refSeven.establishedYear = 1962;
refSeven.contactNumber = "08023600822";
refSeven.email = "info@msrit.edu";
refSeven.website = "www.msrit.edu";
refSeven.collegeType = "Engineering";
refSeven.coursesOffered = "CSE, ISE, ECE, EEE, Mechanical, Civil, AI";

System.out.println("The collegeId is: " + refSeven.collegeId);
System.out.println("The collegeName is: " + refSeven.collegeName);
System.out.println("The principalName is: " + refSeven.principalName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfDepartments is: " + refSeven.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refSeven.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refSeven.numberOfFaculty);
System.out.println("The hasLibrary is: " + refSeven.hasLibrary);
System.out.println("The hasLaboratory is: " + refSeven.hasLaboratory);
System.out.println("The hasHostel is: " + refSeven.hasHostel);
System.out.println("The hasCafeteria is: " + refSeven.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refSeven.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refSeven.hasComputerLab);
System.out.println("The hasAuditorium is: " + refSeven.hasAuditorium);
System.out.println("The universityAffiliation is: " + refSeven.universityAffiliation);
System.out.println("The accreditation is: " + refSeven.accreditation);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The collegeType is: " + refSeven.collegeType);
System.out.println("The coursesOffered is: " + refSeven.coursesOffered);
College refEight = new College();

System.out.println("The collegeId is: " + refEight.collegeId);
System.out.println("The collegeName is: " + refEight.collegeName);
System.out.println("The principalName is: " + refEight.principalName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfDepartments is: " + refEight.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refEight.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refEight.numberOfFaculty);
System.out.println("The hasLibrary is: " + refEight.hasLibrary);
System.out.println("The hasLaboratory is: " + refEight.hasLaboratory);
System.out.println("The hasHostel is: " + refEight.hasHostel);
System.out.println("The hasCafeteria is: " + refEight.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refEight.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refEight.hasComputerLab);
System.out.println("The hasAuditorium is: " + refEight.hasAuditorium);
System.out.println("The universityAffiliation is: " + refEight.universityAffiliation);
System.out.println("The accreditation is: " + refEight.accreditation);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The collegeType is: " + refEight.collegeType);
System.out.println("The coursesOffered is: " + refEight.coursesOffered);

refEight.collegeId = 8;
refEight.collegeName = "Dayananda Sagar College of Engineering";
refEight.principalName = "Dr. Premachandra Sagar";
refEight.location = "Kumaraswamy Layout";
refEight.city = "Bengaluru";
refEight.state = "Karnataka";
refEight.country = "India";
refEight.numberOfDepartments = 14;
refEight.numberOfStudents = 6000;
refEight.numberOfFaculty = 270;
refEight.hasLibrary = true;
refEight.hasLaboratory = true;
refEight.hasHostel = true;
refEight.hasCafeteria = true;
refEight.hasSportsFacility = true;
refEight.hasComputerLab = true;
refEight.hasAuditorium = true;
refEight.universityAffiliation = "VTU";
refEight.accreditation = "NAAC A";
refEight.establishedYear = 1979;
refEight.contactNumber = "08042161789";
refEight.email = "info@dsce.edu";
refEight.website = "www.dsce.edu.in";
refEight.collegeType = "Engineering";
refEight.coursesOffered = "CSE, ISE, ECE, EEE, Mechanical, Civil";

System.out.println("The collegeId is: " + refEight.collegeId);
System.out.println("The collegeName is: " + refEight.collegeName);
System.out.println("The principalName is: " + refEight.principalName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfDepartments is: " + refEight.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refEight.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refEight.numberOfFaculty);
System.out.println("The hasLibrary is: " + refEight.hasLibrary);
System.out.println("The hasLaboratory is: " + refEight.hasLaboratory);
System.out.println("The hasHostel is: " + refEight.hasHostel);
System.out.println("The hasCafeteria is: " + refEight.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refEight.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refEight.hasComputerLab);
System.out.println("The hasAuditorium is: " + refEight.hasAuditorium);
System.out.println("The universityAffiliation is: " + refEight.universityAffiliation);
System.out.println("The accreditation is: " + refEight.accreditation);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The collegeType is: " + refEight.collegeType);
System.out.println("The coursesOffered is: " + refEight.coursesOffered);
College refNine = new College();

System.out.println("The collegeId is: " + refNine.collegeId);
System.out.println("The collegeName is: " + refNine.collegeName);
System.out.println("The principalName is: " + refNine.principalName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfDepartments is: " + refNine.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refNine.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refNine.numberOfFaculty);
System.out.println("The hasLibrary is: " + refNine.hasLibrary);
System.out.println("The hasLaboratory is: " + refNine.hasLaboratory);
System.out.println("The hasHostel is: " + refNine.hasHostel);
System.out.println("The hasCafeteria is: " + refNine.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refNine.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refNine.hasComputerLab);
System.out.println("The hasAuditorium is: " + refNine.hasAuditorium);
System.out.println("The universityAffiliation is: " + refNine.universityAffiliation);
System.out.println("The accreditation is: " + refNine.accreditation);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The collegeType is: " + refNine.collegeType);
System.out.println("The coursesOffered is: " + refNine.coursesOffered);

refNine.collegeId = 9;
refNine.collegeName = "Siddaganga Institute of Technology";
refNine.principalName = "Dr. H. S. Jayanna";
refNine.location = "BH Road";
refNine.city = "Tumakuru";
refNine.state = "Karnataka";
refNine.country = "India";
refNine.numberOfDepartments = 12;
refNine.numberOfStudents = 4800;
refNine.numberOfFaculty = 210;
refNine.hasLibrary = true;
refNine.hasLaboratory = true;
refNine.hasHostel = true;
refNine.hasCafeteria = true;
refNine.hasSportsFacility = true;
refNine.hasComputerLab = true;
refNine.hasAuditorium = true;
refNine.universityAffiliation = "VTU";
refNine.accreditation = "NAAC A";
refNine.establishedYear = 1963;
refNine.contactNumber = "08162221234";
refNine.email = "info@sit.ac.in";
refNine.website = "www.sit.ac.in";
refNine.collegeType = "Engineering";
refNine.coursesOffered = "CSE, ISE, ECE, EEE, Mechanical, Civil";

System.out.println("The collegeId is: " + refNine.collegeId);
System.out.println("The collegeName is: " + refNine.collegeName);
System.out.println("The principalName is: " + refNine.principalName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfDepartments is: " + refNine.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refNine.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refNine.numberOfFaculty);
System.out.println("The hasLibrary is: " + refNine.hasLibrary);
System.out.println("The hasLaboratory is: " + refNine.hasLaboratory);
System.out.println("The hasHostel is: " + refNine.hasHostel);
System.out.println("The hasCafeteria is: " + refNine.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refNine.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refNine.hasComputerLab);
System.out.println("The hasAuditorium is: " + refNine.hasAuditorium);
System.out.println("The universityAffiliation is: " + refNine.universityAffiliation);
System.out.println("The accreditation is: " + refNine.accreditation);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The collegeType is: " + refNine.collegeType);
System.out.println("The coursesOffered is: " + refNine.coursesOffered);
College refTen = new College();

System.out.println("The collegeId is: " + refTen.collegeId);
System.out.println("The collegeName is: " + refTen.collegeName);
System.out.println("The principalName is: " + refTen.principalName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfDepartments is: " + refTen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refTen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refTen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refTen.hasLibrary);
System.out.println("The hasLaboratory is: " + refTen.hasLaboratory);
System.out.println("The hasHostel is: " + refTen.hasHostel);
System.out.println("The hasCafeteria is: " + refTen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refTen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refTen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refTen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refTen.universityAffiliation);
System.out.println("The accreditation is: " + refTen.accreditation);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The collegeType is: " + refTen.collegeType);
System.out.println("The coursesOffered is: " + refTen.coursesOffered);

refTen.collegeId = 10;
refTen.collegeName = "Christ University";
refTen.principalName = "Dr. Fr. Abraham V.M.";
refTen.location = "Hosur Road";
refTen.city = "Bengaluru";
refTen.state = "Karnataka";
refTen.country = "India";
refTen.numberOfDepartments = 20;
refTen.numberOfStudents = 9000;
refTen.numberOfFaculty = 400;
refTen.hasLibrary = true;
refTen.hasLaboratory = true;
refTen.hasHostel = true;
refTen.hasCafeteria = true;
refTen.hasSportsFacility = true;
refTen.hasComputerLab = true;
refTen.hasAuditorium = true;
refTen.universityAffiliation = "Deemed University";
refTen.accreditation = "NAAC A+";
refTen.establishedYear = 1969;
refTen.contactNumber = "08040129000";
refTen.email = "info@christuniversity.in";
refTen.website = "www.christuniversity.in";
refTen.collegeType = "Private University";
refTen.coursesOffered = "CSE, Commerce, Management, Arts, Law";

System.out.println("The collegeId is: " + refTen.collegeId);
System.out.println("The collegeName is: " + refTen.collegeName);
System.out.println("The principalName is: " + refTen.principalName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfDepartments is: " + refTen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refTen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refTen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refTen.hasLibrary);
System.out.println("The hasLaboratory is: " + refTen.hasLaboratory);
System.out.println("The hasHostel is: " + refTen.hasHostel);
System.out.println("The hasCafeteria is: " + refTen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refTen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refTen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refTen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refTen.universityAffiliation);
System.out.println("The accreditation is: " + refTen.accreditation);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The collegeType is: " + refTen.collegeType);
System.out.println("The coursesOffered is: " + refTen.coursesOffered);
College refEleven = new College();

System.out.println("The collegeId is: " + refEleven.collegeId);
System.out.println("The collegeName is: " + refEleven.collegeName);
System.out.println("The principalName is: " + refEleven.principalName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfDepartments is: " + refEleven.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refEleven.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refEleven.numberOfFaculty);
System.out.println("The hasLibrary is: " + refEleven.hasLibrary);
System.out.println("The hasLaboratory is: " + refEleven.hasLaboratory);
System.out.println("The hasHostel is: " + refEleven.hasHostel);
System.out.println("The hasCafeteria is: " + refEleven.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refEleven.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refEleven.hasComputerLab);
System.out.println("The hasAuditorium is: " + refEleven.hasAuditorium);
System.out.println("The universityAffiliation is: " + refEleven.universityAffiliation);
System.out.println("The accreditation is: " + refEleven.accreditation);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The collegeType is: " + refEleven.collegeType);
System.out.println("The coursesOffered is: " + refEleven.coursesOffered);

refEleven.collegeId = 11;
refEleven.collegeName = "Jain University";
refEleven.principalName = "Dr. Raj Singh";
refEleven.location = "Jayanagar";
refEleven.city = "Bengaluru";
refEleven.state = "Karnataka";
refEleven.country = "India";
refEleven.numberOfDepartments = 18;
refEleven.numberOfStudents = 8500;
refEleven.numberOfFaculty = 380;
refEleven.hasLibrary = true;
refEleven.hasLaboratory = true;
refEleven.hasHostel = true;
refEleven.hasCafeteria = true;
refEleven.hasSportsFacility = true;
refEleven.hasComputerLab = true;
refEleven.hasAuditorium = true;
refEleven.universityAffiliation = "Deemed University";
refEleven.accreditation = "NAAC A+";
refEleven.establishedYear = 1990;
refEleven.contactNumber = "08046840400";
refEleven.email = "info@jainuniversity.ac.in";
refEleven.website = "www.jainuniversity.ac.in";
refEleven.collegeType = "Private University";
refEleven.coursesOffered = "CSE, AI, Data Science, Commerce, Management";

System.out.println("The collegeId is: " + refEleven.collegeId);
System.out.println("The collegeName is: " + refEleven.collegeName);
System.out.println("The principalName is: " + refEleven.principalName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfDepartments is: " + refEleven.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refEleven.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refEleven.numberOfFaculty);
System.out.println("The hasLibrary is: " + refEleven.hasLibrary);
System.out.println("The hasLaboratory is: " + refEleven.hasLaboratory);
System.out.println("The hasHostel is: " + refEleven.hasHostel);
System.out.println("The hasCafeteria is: " + refEleven.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refEleven.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refEleven.hasComputerLab);
System.out.println("The hasAuditorium is: " + refEleven.hasAuditorium);
System.out.println("The universityAffiliation is: " + refEleven.universityAffiliation);
System.out.println("The accreditation is: " + refEleven.accreditation);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The collegeType is: " + refEleven.collegeType);
System.out.println("The coursesOffered is: " + refEleven.coursesOffered);
College refTwelve = new College();

System.out.println("The collegeId is: " + refTwelve.collegeId);
System.out.println("The collegeName is: " + refTwelve.collegeName);
System.out.println("The principalName is: " + refTwelve.principalName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfDepartments is: " + refTwelve.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refTwelve.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refTwelve.numberOfFaculty);
System.out.println("The hasLibrary is: " + refTwelve.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwelve.hasLaboratory);
System.out.println("The hasHostel is: " + refTwelve.hasHostel);
System.out.println("The hasCafeteria is: " + refTwelve.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refTwelve.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refTwelve.hasComputerLab);
System.out.println("The hasAuditorium is: " + refTwelve.hasAuditorium);
System.out.println("The universityAffiliation is: " + refTwelve.universityAffiliation);
System.out.println("The accreditation is: " + refTwelve.accreditation);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The collegeType is: " + refTwelve.collegeType);
System.out.println("The coursesOffered is: " + refTwelve.coursesOffered);

refTwelve.collegeId = 12;
refTwelve.collegeName = "New Horizon College of Engineering";
refTwelve.principalName = "Dr. Manjunatha";
refTwelve.location = "Marathahalli";
refTwelve.city = "Bengaluru";
refTwelve.state = "Karnataka";
refTwelve.country = "India";
refTwelve.numberOfDepartments = 11;
refTwelve.numberOfStudents = 4200;
refTwelve.numberOfFaculty = 200;
refTwelve.hasLibrary = true;
refTwelve.hasLaboratory = true;
refTwelve.hasHostel = true;
refTwelve.hasCafeteria = true;
refTwelve.hasSportsFacility = true;
refTwelve.hasComputerLab = true;
refTwelve.hasAuditorium = true;
refTwelve.universityAffiliation = "VTU";
refTwelve.accreditation = "NAAC A";
refTwelve.establishedYear = 2001;
refTwelve.contactNumber = "08066297777";
refTwelve.email = "info@newhorizonindia.edu";
refTwelve.website = "www.newhorizonindia.edu";
refTwelve.collegeType = "Engineering";
refTwelve.coursesOffered = "CSE, ISE, ECE, Mechanical, Civil";

System.out.println("The collegeId is: " + refTwelve.collegeId);
System.out.println("The collegeName is: " + refTwelve.collegeName);
System.out.println("The principalName is: " + refTwelve.principalName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfDepartments is: " + refTwelve.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refTwelve.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refTwelve.numberOfFaculty);
System.out.println("The hasLibrary is: " + refTwelve.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwelve.hasLaboratory);
System.out.println("The hasHostel is: " + refTwelve.hasHostel);
System.out.println("The hasCafeteria is: " + refTwelve.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refTwelve.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refTwelve.hasComputerLab);
System.out.println("The hasAuditorium is: " + refTwelve.hasAuditorium);
System.out.println("The universityAffiliation is: " + refTwelve.universityAffiliation);
System.out.println("The accreditation is: " + refTwelve.accreditation);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The collegeType is: " + refTwelve.collegeType);
System.out.println("The coursesOffered is: " + refTwelve.coursesOffered);
College refThirteen = new College();

System.out.println("The collegeId is: " + refThirteen.collegeId);
System.out.println("The collegeName is: " + refThirteen.collegeName);
System.out.println("The principalName is: " + refThirteen.principalName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfDepartments is: " + refThirteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refThirteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refThirteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refThirteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refThirteen.hasLaboratory);
System.out.println("The hasHostel is: " + refThirteen.hasHostel);
System.out.println("The hasCafeteria is: " + refThirteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refThirteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refThirteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refThirteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refThirteen.universityAffiliation);
System.out.println("The accreditation is: " + refThirteen.accreditation);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The collegeType is: " + refThirteen.collegeType);
System.out.println("The coursesOffered is: " + refThirteen.coursesOffered);

refThirteen.collegeId = 13;
refThirteen.collegeName = "CMR Institute of Technology";
refThirteen.principalName = "Dr. Sanjay Jain";
refThirteen.location = "ITPL Road";
refThirteen.city = "Bengaluru";
refThirteen.state = "Karnataka";
refThirteen.country = "India";
refThirteen.numberOfDepartments = 10;
refThirteen.numberOfStudents = 3900;
refThirteen.numberOfFaculty = 180;
refThirteen.hasLibrary = true;
refThirteen.hasLaboratory = true;
refThirteen.hasHostel = true;
refThirteen.hasCafeteria = true;
refThirteen.hasSportsFacility = true;
refThirteen.hasComputerLab = true;
refThirteen.hasAuditorium = true;
refThirteen.universityAffiliation = "VTU";
refThirteen.accreditation = "NAAC A";
refThirteen.establishedYear = 2000;
refThirteen.contactNumber = "08028524466";
refThirteen.email = "info@cmrit.ac.in";
refThirteen.website = "www.cmrit.ac.in";
refThirteen.collegeType = "Engineering";
refThirteen.coursesOffered = "CSE, ISE, ECE, Mechanical, Civil";

System.out.println("The collegeId is: " + refThirteen.collegeId);
System.out.println("The collegeName is: " + refThirteen.collegeName);
System.out.println("The principalName is: " + refThirteen.principalName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfDepartments is: " + refThirteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refThirteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refThirteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refThirteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refThirteen.hasLaboratory);
System.out.println("The hasHostel is: " + refThirteen.hasHostel);
System.out.println("The hasCafeteria is: " + refThirteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refThirteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refThirteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refThirteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refThirteen.universityAffiliation);
System.out.println("The accreditation is: " + refThirteen.accreditation);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The collegeType is: " + refThirteen.collegeType);
System.out.println("The coursesOffered is: " + refThirteen.coursesOffered);
College refFourteen = new College();

System.out.println("The collegeId is: " + refFourteen.collegeId);
System.out.println("The collegeName is: " + refFourteen.collegeName);
System.out.println("The principalName is: " + refFourteen.principalName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfDepartments is: " + refFourteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refFourteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refFourteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refFourteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refFourteen.hasLaboratory);
System.out.println("The hasHostel is: " + refFourteen.hasHostel);
System.out.println("The hasCafeteria is: " + refFourteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refFourteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refFourteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refFourteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refFourteen.universityAffiliation);
System.out.println("The accreditation is: " + refFourteen.accreditation);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The collegeType is: " + refFourteen.collegeType);
System.out.println("The coursesOffered is: " + refFourteen.coursesOffered);

refFourteen.collegeId = 14;
refFourteen.collegeName = "Acharya Institute of Technology";
refFourteen.principalName = "Dr. B. Satish";
refFourteen.location = "Soldevanahalli";
refFourteen.city = "Bengaluru";
refFourteen.state = "Karnataka";
refFourteen.country = "India";
refFourteen.numberOfDepartments = 12;
refFourteen.numberOfStudents = 5000;
refFourteen.numberOfFaculty = 210;
refFourteen.hasLibrary = true;
refFourteen.hasLaboratory = true;
refFourteen.hasHostel = true;
refFourteen.hasCafeteria = true;
refFourteen.hasSportsFacility = true;
refFourteen.hasComputerLab = true;
refFourteen.hasAuditorium = true;
refFourteen.universityAffiliation = "VTU";
refFourteen.accreditation = "NAAC A";
refFourteen.establishedYear = 2000;
refFourteen.contactNumber = "08028396011";
refFourteen.email = "info@acharya.ac.in";
refFourteen.website = "www.acharya.ac.in";
refFourteen.collegeType = "Engineering";
refFourteen.coursesOffered = "CSE, ISE, ECE, Mechanical, Civil";

System.out.println("The collegeId is: " + refFourteen.collegeId);
System.out.println("The collegeName is: " + refFourteen.collegeName);
System.out.println("The principalName is: " + refFourteen.principalName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfDepartments is: " + refFourteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refFourteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refFourteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refFourteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refFourteen.hasLaboratory);
System.out.println("The hasHostel is: " + refFourteen.hasHostel);
System.out.println("The hasCafeteria is: " + refFourteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refFourteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refFourteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refFourteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refFourteen.universityAffiliation);
System.out.println("The accreditation is: " + refFourteen.accreditation);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The collegeType is: " + refFourteen.collegeType);
System.out.println("The coursesOffered is: " + refFourteen.coursesOffered);
College refFifteen = new College();

System.out.println("The collegeId is: " + refFifteen.collegeId);
System.out.println("The collegeName is: " + refFifteen.collegeName);
System.out.println("The principalName is: " + refFifteen.principalName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfDepartments is: " + refFifteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refFifteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refFifteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refFifteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refFifteen.hasLaboratory);
System.out.println("The hasHostel is: " + refFifteen.hasHostel);
System.out.println("The hasCafeteria is: " + refFifteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refFifteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refFifteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refFifteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refFifteen.universityAffiliation);
System.out.println("The accreditation is: " + refFifteen.accreditation);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The collegeType is: " + refFifteen.collegeType);
System.out.println("The coursesOffered is: " + refFifteen.coursesOffered);

refFifteen.collegeId = 15;
refFifteen.collegeName = "Reva University";
refFifteen.principalName = "Dr. P. Shyama Raju";
refFifteen.location = "Yelahanka";
refFifteen.city = "Bengaluru";
refFifteen.state = "Karnataka";
refFifteen.country = "India";
refFifteen.numberOfDepartments = 16;
refFifteen.numberOfStudents = 8000;
refFifteen.numberOfFaculty = 350;
refFifteen.hasLibrary = true;
refFifteen.hasLaboratory = true;
refFifteen.hasHostel = true;
refFifteen.hasCafeteria = true;
refFifteen.hasSportsFacility = true;
refFifteen.hasComputerLab = true;
refFifteen.hasAuditorium = true;
refFifteen.universityAffiliation = "Private University";
refFifteen.accreditation = "NAAC A+";
refFifteen.establishedYear = 2012;
refFifteen.contactNumber = "08046966966";
refFifteen.email = "info@reva.edu.in";
refFifteen.website = "www.reva.edu.in";
refFifteen.collegeType = "University";
refFifteen.coursesOffered = "CSE, AI, Data Science, ECE, Mechanical, Civil";

System.out.println("The collegeId is: " + refFifteen.collegeId);
System.out.println("The collegeName is: " + refFifteen.collegeName);
System.out.println("The principalName is: " + refFifteen.principalName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfDepartments is: " + refFifteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refFifteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refFifteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refFifteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refFifteen.hasLaboratory);
System.out.println("The hasHostel is: " + refFifteen.hasHostel);
System.out.println("The hasCafeteria is: " + refFifteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refFifteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refFifteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refFifteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refFifteen.universityAffiliation);
System.out.println("The accreditation is: " + refFifteen.accreditation);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The collegeType is: " + refFifteen.collegeType);
System.out.println("The coursesOffered is: " + refFifteen.coursesOffered);
College refSixteen = new College();

System.out.println("The collegeId is: " + refSixteen.collegeId);
System.out.println("The collegeName is: " + refSixteen.collegeName);
System.out.println("The principalName is: " + refSixteen.principalName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfDepartments is: " + refSixteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refSixteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refSixteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refSixteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refSixteen.hasLaboratory);
System.out.println("The hasHostel is: " + refSixteen.hasHostel);
System.out.println("The hasCafeteria is: " + refSixteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refSixteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refSixteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refSixteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refSixteen.universityAffiliation);
System.out.println("The accreditation is: " + refSixteen.accreditation);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The collegeType is: " + refSixteen.collegeType);
System.out.println("The coursesOffered is: " + refSixteen.coursesOffered);

refSixteen.collegeId = 16;
refSixteen.collegeName = "Garden City University";
refSixteen.principalName = "Dr. Joseph V G";
refSixteen.location = "KR Puram";
refSixteen.city = "Bengaluru";
refSixteen.state = "Karnataka";
refSixteen.country = "India";
refSixteen.numberOfDepartments = 14;
refSixteen.numberOfStudents = 6000;
refSixteen.numberOfFaculty = 260;
refSixteen.hasLibrary = true;
refSixteen.hasLaboratory = true;
refSixteen.hasHostel = true;
refSixteen.hasCafeteria = true;
refSixteen.hasSportsFacility = true;
refSixteen.hasComputerLab = true;
refSixteen.hasAuditorium = true;
refSixteen.universityAffiliation = "Private University";
refSixteen.accreditation = "NAAC A";
refSixteen.establishedYear = 2012;
refSixteen.contactNumber = "08066487600";
refSixteen.email = "info@gardencity.university";
refSixteen.website = "www.gardencity.university";
refSixteen.collegeType = "University";
refSixteen.coursesOffered = "CSE, AI, Data Science, Commerce, Management";

System.out.println("The collegeId is: " + refSixteen.collegeId);
System.out.println("The collegeName is: " + refSixteen.collegeName);
System.out.println("The principalName is: " + refSixteen.principalName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfDepartments is: " + refSixteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refSixteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refSixteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refSixteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refSixteen.hasLaboratory);
System.out.println("The hasHostel is: " + refSixteen.hasHostel);
System.out.println("The hasCafeteria is: " + refSixteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refSixteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refSixteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refSixteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refSixteen.universityAffiliation);
System.out.println("The accreditation is: " + refSixteen.accreditation);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The collegeType is: " + refSixteen.collegeType);
System.out.println("The coursesOffered is: " + refSixteen.coursesOffered);
College refSeventeen = new College();

System.out.println("The collegeId is: " + refSeventeen.collegeId);
System.out.println("The collegeName is: " + refSeventeen.collegeName);
System.out.println("The principalName is: " + refSeventeen.principalName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfDepartments is: " + refSeventeen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refSeventeen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refSeventeen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refSeventeen.hasLibrary);
System.out.println("The hasLaboratory is: " + refSeventeen.hasLaboratory);
System.out.println("The hasHostel is: " + refSeventeen.hasHostel);
System.out.println("The hasCafeteria is: " + refSeventeen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refSeventeen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refSeventeen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refSeventeen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refSeventeen.universityAffiliation);
System.out.println("The accreditation is: " + refSeventeen.accreditation);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The collegeType is: " + refSeventeen.collegeType);
System.out.println("The coursesOffered is: " + refSeventeen.coursesOffered);

refSeventeen.collegeId = 17;
refSeventeen.collegeName = "Alliance University";
refSeventeen.principalName = "Dr. Sudhir Angur";
refSeventeen.location = "Anekal";
refSeventeen.city = "Bengaluru";
refSeventeen.state = "Karnataka";
refSeventeen.country = "India";
refSeventeen.numberOfDepartments = 15;
refSeventeen.numberOfStudents = 7200;
refSeventeen.numberOfFaculty = 300;
refSeventeen.hasLibrary = true;
refSeventeen.hasLaboratory = true;
refSeventeen.hasHostel = true;
refSeventeen.hasCafeteria = true;
refSeventeen.hasSportsFacility = true;
refSeventeen.hasComputerLab = true;
refSeventeen.hasAuditorium = true;
refSeventeen.universityAffiliation = "Private University";
refSeventeen.accreditation = "NAAC A+";
refSeventeen.establishedYear = 2010;
refSeventeen.contactNumber = "08046199000";
refSeventeen.email = "info@alliance.edu.in";
refSeventeen.website = "www.alliance.edu.in";
refSeventeen.collegeType = "University";
refSeventeen.coursesOffered = "CSE, AI, Data Science, Management, Law";

System.out.println("The collegeId is: " + refSeventeen.collegeId);
System.out.println("The collegeName is: " + refSeventeen.collegeName);
System.out.println("The principalName is: " + refSeventeen.principalName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfDepartments is: " + refSeventeen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refSeventeen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refSeventeen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refSeventeen.hasLibrary);
System.out.println("The hasLaboratory is: " + refSeventeen.hasLaboratory);
System.out.println("The hasHostel is: " + refSeventeen.hasHostel);
System.out.println("The hasCafeteria is: " + refSeventeen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refSeventeen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refSeventeen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refSeventeen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refSeventeen.universityAffiliation);
System.out.println("The accreditation is: " + refSeventeen.accreditation);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The collegeType is: " + refSeventeen.collegeType);
System.out.println("The coursesOffered is: " + refSeventeen.coursesOffered);
College refEighteen = new College();

System.out.println("The collegeId is: " + refEighteen.collegeId);
System.out.println("The collegeName is: " + refEighteen.collegeName);
System.out.println("The principalName is: " + refEighteen.principalName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfDepartments is: " + refEighteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refEighteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refEighteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refEighteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refEighteen.hasLaboratory);
System.out.println("The hasHostel is: " + refEighteen.hasHostel);
System.out.println("The hasCafeteria is: " + refEighteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refEighteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refEighteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refEighteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refEighteen.universityAffiliation);
System.out.println("The accreditation is: " + refEighteen.accreditation);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The collegeType is: " + refEighteen.collegeType);
System.out.println("The coursesOffered is: " + refEighteen.coursesOffered);

refEighteen.collegeId = 18;
refEighteen.collegeName = "Presidency University";
refEighteen.principalName = "Dr. Nissar Ahmed";
refEighteen.location = "Yelahanka";
refEighteen.city = "Bengaluru";
refEighteen.state = "Karnataka";
refEighteen.country = "India";
refEighteen.numberOfDepartments = 13;
refEighteen.numberOfStudents = 6500;
refEighteen.numberOfFaculty = 280;
refEighteen.hasLibrary = true;
refEighteen.hasLaboratory = true;
refEighteen.hasHostel = true;
refEighteen.hasCafeteria = true;
refEighteen.hasSportsFacility = true;
refEighteen.hasComputerLab = true;
refEighteen.hasAuditorium = true;
refEighteen.universityAffiliation = "Private University";
refEighteen.accreditation = "NAAC A";
refEighteen.establishedYear = 2013;
refEighteen.contactNumber = "08049049000";
refEighteen.email = "info@presidencyuniversity.in";
refEighteen.website = "www.presidencyuniversity.in";
refEighteen.collegeType = "University";
refEighteen.coursesOffered = "CSE, AI, Data Science, Commerce, Management";

System.out.println("The collegeId is: " + refEighteen.collegeId);
System.out.println("The collegeName is: " + refEighteen.collegeName);
System.out.println("The principalName is: " + refEighteen.principalName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfDepartments is: " + refEighteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refEighteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refEighteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refEighteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refEighteen.hasLaboratory);
System.out.println("The hasHostel is: " + refEighteen.hasHostel);
System.out.println("The hasCafeteria is: " + refEighteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refEighteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refEighteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refEighteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refEighteen.universityAffiliation);
System.out.println("The accreditation is: " + refEighteen.accreditation);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The collegeType is: " + refEighteen.collegeType);
System.out.println("The coursesOffered is: " + refEighteen.coursesOffered);
College refNineteen = new College();

System.out.println("The collegeId is: " + refNineteen.collegeId);
System.out.println("The collegeName is: " + refNineteen.collegeName);
System.out.println("The principalName is: " + refNineteen.principalName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfDepartments is: " + refNineteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refNineteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refNineteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refNineteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refNineteen.hasLaboratory);
System.out.println("The hasHostel is: " + refNineteen.hasHostel);
System.out.println("The hasCafeteria is: " + refNineteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refNineteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refNineteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refNineteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refNineteen.universityAffiliation);
System.out.println("The accreditation is: " + refNineteen.accreditation);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The collegeType is: " + refNineteen.collegeType);
System.out.println("The coursesOffered is: " + refNineteen.coursesOffered);

refNineteen.collegeId = 19;
refNineteen.collegeName = "KLE Technological University";
refNineteen.principalName = "Dr. Ashok Shettar";
refNineteen.location = "Vidyanagar";
refNineteen.city = "Hubballi";
refNineteen.state = "Karnataka";
refNineteen.country = "India";
refNineteen.numberOfDepartments = 14;
refNineteen.numberOfStudents = 7000;
refNineteen.numberOfFaculty = 300;
refNineteen.hasLibrary = true;
refNineteen.hasLaboratory = true;
refNineteen.hasHostel = true;
refNineteen.hasCafeteria = true;
refNineteen.hasSportsFacility = true;
refNineteen.hasComputerLab = true;
refNineteen.hasAuditorium = true;
refNineteen.universityAffiliation = "Private University";
refNineteen.accreditation = "NAAC A+";
refNineteen.establishedYear = 1947;
refNineteen.contactNumber = "08362377777";
refNineteen.email = "info@kletech.ac.in";
refNineteen.website = "www.kletech.ac.in";
refNineteen.collegeType = "University";
refNineteen.coursesOffered = "CSE, AI, Data Science, ECE, Mechanical, Civil";

System.out.println("The collegeId is: " + refNineteen.collegeId);
System.out.println("The collegeName is: " + refNineteen.collegeName);
System.out.println("The principalName is: " + refNineteen.principalName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfDepartments is: " + refNineteen.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refNineteen.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refNineteen.numberOfFaculty);
System.out.println("The hasLibrary is: " + refNineteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refNineteen.hasLaboratory);
System.out.println("The hasHostel is: " + refNineteen.hasHostel);
System.out.println("The hasCafeteria is: " + refNineteen.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refNineteen.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refNineteen.hasComputerLab);
System.out.println("The hasAuditorium is: " + refNineteen.hasAuditorium);
System.out.println("The universityAffiliation is: " + refNineteen.universityAffiliation);
System.out.println("The accreditation is: " + refNineteen.accreditation);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The collegeType is: " + refNineteen.collegeType);
System.out.println("The coursesOffered is: " + refNineteen.coursesOffered);
College refTwenty = new College();

System.out.println("The collegeId is: " + refTwenty.collegeId);
System.out.println("The collegeName is: " + refTwenty.collegeName);
System.out.println("The principalName is: " + refTwenty.principalName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfDepartments is: " + refTwenty.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refTwenty.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refTwenty.numberOfFaculty);
System.out.println("The hasLibrary is: " + refTwenty.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwenty.hasLaboratory);
System.out.println("The hasHostel is: " + refTwenty.hasHostel);
System.out.println("The hasCafeteria is: " + refTwenty.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refTwenty.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refTwenty.hasComputerLab);
System.out.println("The hasAuditorium is: " + refTwenty.hasAuditorium);
System.out.println("The universityAffiliation is: " + refTwenty.universityAffiliation);
System.out.println("The accreditation is: " + refTwenty.accreditation);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The collegeType is: " + refTwenty.collegeType);
System.out.println("The coursesOffered is: " + refTwenty.coursesOffered);

refTwenty.collegeId = 20;
refTwenty.collegeName = "Bapuji Institute of Engineering and Technology";
refTwenty.principalName = "Dr. B. M. Ravishankar";
refTwenty.location = "Shamanur Road";
refTwenty.city = "Davangere";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.numberOfDepartments = 12;
refTwenty.numberOfStudents = 5000;
refTwenty.numberOfFaculty = 230;
refTwenty.hasLibrary = true;
refTwenty.hasLaboratory = true;
refTwenty.hasHostel = true;
refTwenty.hasCafeteria = true;
refTwenty.hasSportsFacility = true;
refTwenty.hasComputerLab = true;
refTwenty.hasAuditorium = true;
refTwenty.universityAffiliation = "VTU";
refTwenty.accreditation = "NAAC A";
refTwenty.establishedYear = 1979;
refTwenty.contactNumber = "08192222222";
refTwenty.email = "info@bietdvg.edu";
refTwenty.website = "www.bietdvg.edu";
refTwenty.collegeType = "Engineering";
refTwenty.coursesOffered = "CSE, ISE, ECE, Mechanical, Civil";

System.out.println("The collegeId is: " + refTwenty.collegeId);
System.out.println("The collegeName is: " + refTwenty.collegeName);
System.out.println("The principalName is: " + refTwenty.principalName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfDepartments is: " + refTwenty.numberOfDepartments);
System.out.println("The numberOfStudents is: " + refTwenty.numberOfStudents);
System.out.println("The numberOfFaculty is: " + refTwenty.numberOfFaculty);
System.out.println("The hasLibrary is: " + refTwenty.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwenty.hasLaboratory);
System.out.println("The hasHostel is: " + refTwenty.hasHostel);
System.out.println("The hasCafeteria is: " + refTwenty.hasCafeteria);
System.out.println("The hasSportsFacility is: " + refTwenty.hasSportsFacility);
System.out.println("The hasComputerLab is: " + refTwenty.hasComputerLab);
System.out.println("The hasAuditorium is: " + refTwenty.hasAuditorium);
System.out.println("The universityAffiliation is: " + refTwenty.universityAffiliation);
System.out.println("The accreditation is: " + refTwenty.accreditation);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The collegeType is: " + refTwenty.collegeType);
System.out.println("The coursesOffered is: " + refTwenty.coursesOffered);
}
}