class CompanyExecutor{
public static void main(String[] args){
Company refOne = new Company();

System.out.println("The companyId is: " + refOne.companyId);
System.out.println("The companyName is: " + refOne.companyName);
System.out.println("The industryType is: " + refOne.industryType);
System.out.println("The ceoName is: " + refOne.ceoName);
System.out.println("The founderName is: " + refOne.founderName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The headquartersLocation is: " + refOne.headquartersLocation);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfEmployees is: " + refOne.numberOfEmployees);
System.out.println("The annualRevenue is: " + refOne.annualRevenue);
System.out.println("The marketCap is: " + refOne.marketCap);
System.out.println("The isPubliclyTraded is: " + refOne.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refOne.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refOne.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refOne.numberOfOffices);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The businessType is: " + refOne.businessType);
System.out.println("The hasRnDDepartment  is: " + refOne.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refOne.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refOne.hasOnlinePresence);
System.out.println("The companyMotto is: " + refOne.companyMotto);

refOne.companyId = 1;
refOne.companyName = "TechNova Solutions";
refOne.industryType = "Information Technology";
refOne.ceoName = "Rohit Sharma";
refOne.founderName = "Anita Desai";
refOne.establishedYear = 2008;
refOne.headquartersLocation = "Electronic City";
refOne.city = "Bengaluru";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfEmployees = 1200;
refOne.annualRevenue = 85.5;
refOne.marketCap = 500.75;
refOne.isPubliclyTraded = true;
refOne.stockSymbol = "TNS";
refOne.hasSubsidiaries = true;
refOne.numberOfOffices = 8;
refOne.contactNumber = "9876543210";
refOne.email = "info@technova.com";
refOne.website = "www.technova.com";
refOne.businessType = "Software Development";
refOne.hasRnDDepartment  = true;
refOne.hasCustomerSupport = true;
refOne.hasOnlinePresence = true;
refOne.companyMotto = "Innovating the Future";

System.out.println("The companyId is: " + refOne.companyId);
System.out.println("The companyName is: " + refOne.companyName);
System.out.println("The industryType is: " + refOne.industryType);
System.out.println("The ceoName is: " + refOne.ceoName);
System.out.println("The founderName is: " + refOne.founderName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The headquartersLocation is: " + refOne.headquartersLocation);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfEmployees is: " + refOne.numberOfEmployees);
System.out.println("The annualRevenue is: " + refOne.annualRevenue);
System.out.println("The marketCap is: " + refOne.marketCap);
System.out.println("The isPubliclyTraded is: " + refOne.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refOne.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refOne.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refOne.numberOfOffices);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The businessType is: " + refOne.businessType);
System.out.println("The hasRnDDepartment  is: " + refOne.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refOne.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refOne.hasOnlinePresence);
System.out.println("The companyMotto is: " + refOne.companyMotto);
Company refTwo = new Company();

System.out.println("The companyId is: " + refTwo.companyId);
System.out.println("The companyName is: " + refTwo.companyName);
System.out.println("The industryType is: " + refTwo.industryType);
System.out.println("The ceoName is: " + refTwo.ceoName);
System.out.println("The founderName is: " + refTwo.founderName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The headquartersLocation is: " + refTwo.headquartersLocation);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfEmployees is: " + refTwo.numberOfEmployees);
System.out.println("The annualRevenue is: " + refTwo.annualRevenue);
System.out.println("The marketCap is: " + refTwo.marketCap);
System.out.println("The isPubliclyTraded is: " + refTwo.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refTwo.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refTwo.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refTwo.numberOfOffices);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The businessType is: " + refTwo.businessType);
System.out.println("The hasRnDDepartment  is: " + refTwo.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refTwo.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refTwo.hasOnlinePresence);
System.out.println("The companyMotto is: " + refTwo.companyMotto);

refTwo.companyId = 2;
refTwo.companyName = "GreenLeaf Industries";
refTwo.industryType = "Agriculture Technology";
refTwo.ceoName = "Karthik Reddy";
refTwo.founderName = "Lakshmi Narayan";
refTwo.establishedYear = 2012;
refTwo.headquartersLocation = "Whitefield";
refTwo.city = "Bengaluru";
refTwo.state = "Karnataka";
refTwo.country = "India";
refTwo.numberOfEmployees = 850;
refTwo.annualRevenue = 45.8;
refTwo.marketCap = 210.4;
refTwo.isPubliclyTraded = false;
refTwo.stockSymbol = "GLI";
refTwo.hasSubsidiaries = true;
refTwo.numberOfOffices = 5;
refTwo.contactNumber = "9123456780";
refTwo.email = "contact@greenleaf.com";
refTwo.website = "www.greenleaf.com";
refTwo.businessType = "Agri Solutions";
refTwo.hasRnDDepartment  = true;
refTwo.hasCustomerSupport = true;
refTwo.hasOnlinePresence = true;
refTwo.companyMotto = "Growing a Greener Future";

System.out.println("The companyId is: " + refTwo.companyId);
System.out.println("The companyName is: " + refTwo.companyName);
System.out.println("The industryType is: " + refTwo.industryType);
System.out.println("The ceoName is: " + refTwo.ceoName);
System.out.println("The founderName is: " + refTwo.founderName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The headquartersLocation is: " + refTwo.headquartersLocation);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfEmployees is: " + refTwo.numberOfEmployees);
System.out.println("The annualRevenue is: " + refTwo.annualRevenue);
System.out.println("The marketCap is: " + refTwo.marketCap);
System.out.println("The isPubliclyTraded is: " + refTwo.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refTwo.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refTwo.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refTwo.numberOfOffices);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The businessType is: " + refTwo.businessType);
System.out.println("The hasRnDDepartment  is: " + refTwo.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refTwo.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refTwo.hasOnlinePresence);
System.out.println("The companyMotto is: " + refTwo.companyMotto);
Company refThree = new Company();

System.out.println("The companyId is: " + refThree.companyId);
System.out.println("The companyName is: " + refThree.companyName);
System.out.println("The industryType is: " + refThree.industryType);
System.out.println("The ceoName is: " + refThree.ceoName);
System.out.println("The founderName is: " + refThree.founderName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The headquartersLocation is: " + refThree.headquartersLocation);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfEmployees is: " + refThree.numberOfEmployees);
System.out.println("The annualRevenue is: " + refThree.annualRevenue);
System.out.println("The marketCap is: " + refThree.marketCap);
System.out.println("The isPubliclyTraded is: " + refThree.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refThree.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refThree.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refThree.numberOfOffices);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The businessType is: " + refThree.businessType);
System.out.println("The hasRnDDepartment  is: " + refThree.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refThree.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refThree.hasOnlinePresence);
System.out.println("The companyMotto is: " + refThree.companyMotto);

refThree.companyId = 3;
refThree.companyName = "SkyNet Technologies";
refThree.industryType = "Artificial Intelligence";
refThree.ceoName = "Vikram Mehta";
refThree.founderName = "Arjun Patel";
refThree.establishedYear = 2015;
refThree.headquartersLocation = "Hitech City";
refThree.city = "Hyderabad";
refThree.state = "Telangana";
refThree.country = "India";
refThree.numberOfEmployees = 650;
refThree.annualRevenue = 38.7;
refThree.marketCap = 150.5;
refThree.isPubliclyTraded = false;
refThree.stockSymbol = "SKY";
refThree.hasSubsidiaries = false;
refThree.numberOfOffices = 4;
refThree.contactNumber = "9012345678";
refThree.email = "info@skynet.com";
refThree.website = "www.skynet.com";
refThree.businessType = "AI Solutions";
refThree.hasRnDDepartment  = true;
refThree.hasCustomerSupport = true;
refThree.hasOnlinePresence = true;
refThree.companyMotto = "Intelligence for Tomorrow";

System.out.println("The companyId is: " + refThree.companyId);
System.out.println("The companyName is: " + refThree.companyName);
System.out.println("The industryType is: " + refThree.industryType);
System.out.println("The ceoName is: " + refThree.ceoName);
System.out.println("The founderName is: " + refThree.founderName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The headquartersLocation is: " + refThree.headquartersLocation);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfEmployees is: " + refThree.numberOfEmployees);
System.out.println("The annualRevenue is: " + refThree.annualRevenue);
System.out.println("The marketCap is: " + refThree.marketCap);
System.out.println("The isPubliclyTraded is: " + refThree.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refThree.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refThree.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refThree.numberOfOffices);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The businessType is: " + refThree.businessType);
System.out.println("The hasRnDDepartment  is: " + refThree.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refThree.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refThree.hasOnlinePresence);
System.out.println("The companyMotto is: " + refThree.companyMotto);
Company refFour = new Company();

System.out.println("The companyId is: " + refFour.companyId);
System.out.println("The companyName is: " + refFour.companyName);
System.out.println("The industryType is: " + refFour.industryType);
System.out.println("The ceoName is: " + refFour.ceoName);
System.out.println("The founderName is: " + refFour.founderName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The headquartersLocation is: " + refFour.headquartersLocation);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfEmployees is: " + refFour.numberOfEmployees);
System.out.println("The annualRevenue is: " + refFour.annualRevenue);
System.out.println("The marketCap is: " + refFour.marketCap);
System.out.println("The isPubliclyTraded is: " + refFour.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refFour.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refFour.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refFour.numberOfOffices);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The businessType is: " + refFour.businessType);
System.out.println("The hasRnDDepartment  is: " + refFour.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refFour.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refFour.hasOnlinePresence);
System.out.println("The companyMotto is: " + refFour.companyMotto);

refFour.companyId = 4;
refFour.companyName = "BlueWave Electronics";
refFour.industryType = "Electronics Manufacturing";
refFour.ceoName = "Neha Kapoor";
refFour.founderName = "Rajesh Khanna";
refFour.establishedYear = 2005;
refFour.headquartersLocation = "Sector 62";
refFour.city = "Noida";
refFour.state = "Uttar Pradesh";
refFour.country = "India";
refFour.numberOfEmployees = 1500;
refFour.annualRevenue = 120.4;
refFour.marketCap = 600.8;
refFour.isPubliclyTraded = true;
refFour.stockSymbol = "BWE";
refFour.hasSubsidiaries = true;
refFour.numberOfOffices = 10;
refFour.contactNumber = "9098765432";
refFour.email = "support@bluewave.com";
refFour.website = "www.bluewave.com";
refFour.businessType = "Consumer Electronics";
refFour.hasRnDDepartment  = true;
refFour.hasCustomerSupport = true;
refFour.hasOnlinePresence = true;
refFour.companyMotto = "Innovation Meets Quality";

System.out.println("The companyId is: " + refFour.companyId);
System.out.println("The companyName is: " + refFour.companyName);
System.out.println("The industryType is: " + refFour.industryType);
System.out.println("The ceoName is: " + refFour.ceoName);
System.out.println("The founderName is: " + refFour.founderName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The headquartersLocation is: " + refFour.headquartersLocation);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfEmployees is: " + refFour.numberOfEmployees);
System.out.println("The annualRevenue is: " + refFour.annualRevenue);
System.out.println("The marketCap is: " + refFour.marketCap);
System.out.println("The isPubliclyTraded is: " + refFour.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refFour.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refFour.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refFour.numberOfOffices);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The businessType is: " + refFour.businessType);
System.out.println("The hasRnDDepartment  is: " + refFour.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refFour.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refFour.hasOnlinePresence);
System.out.println("The companyMotto is: " + refFour.companyMotto);
Company refFive = new Company();

System.out.println("The companyId is: " + refFive.companyId);
System.out.println("The companyName is: " + refFive.companyName);
System.out.println("The industryType is: " + refFive.industryType);
System.out.println("The ceoName is: " + refFive.ceoName);
System.out.println("The founderName is: " + refFive.founderName);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The headquartersLocation is: " + refFive.headquartersLocation);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfEmployees is: " + refFive.numberOfEmployees);
System.out.println("The annualRevenue is: " + refFive.annualRevenue);
System.out.println("The marketCap is: " + refFive.marketCap);
System.out.println("The isPubliclyTraded is: " + refFive.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refFive.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refFive.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refFive.numberOfOffices);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The businessType is: " + refFive.businessType);
System.out.println("The hasRnDDepartment  is: " + refFive.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refFive.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refFive.hasOnlinePresence);
System.out.println("The companyMotto is: " + refFive.companyMotto);

refFive.companyId = 5;
refFive.companyName = "Sunrise Pharmaceuticals";
refFive.industryType = "Pharmaceutical";
refFive.ceoName = "Dr. Kavita Sharma";
refFive.founderName = "Ramesh Gupta";
refFive.establishedYear = 1998;
refFive.headquartersLocation = "Andheri";
refFive.city = "Mumbai";
refFive.state = "Maharashtra";
refFive.country = "India";
refFive.numberOfEmployees = 2200;
refFive.annualRevenue = 310.5;
refFive.marketCap = 1200.75;
refFive.isPubliclyTraded = true;
refFive.stockSymbol = "SRP";
refFive.hasSubsidiaries = true;
refFive.numberOfOffices = 15;
refFive.contactNumber = "9812345670";
refFive.email = "info@sunrisepharma.com";
refFive.website = "www.sunrisepharma.com";
refFive.businessType = "Healthcare Manufacturing";
refFive.hasRnDDepartment  = true;
refFive.hasCustomerSupport = true;
refFive.hasOnlinePresence = true;
refFive.companyMotto = "Health for a Better Life";

System.out.println("The companyId is: " + refFive.companyId);
System.out.println("The companyName is: " + refFive.companyName);
System.out.println("The industryType is: " + refFive.industryType);
System.out.println("The ceoName is: " + refFive.ceoName);
System.out.println("The founderName is: " + refFive.founderName);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The headquartersLocation is: " + refFive.headquartersLocation);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfEmployees is: " + refFive.numberOfEmployees);
System.out.println("The annualRevenue is: " + refFive.annualRevenue);
System.out.println("The marketCap is: " + refFive.marketCap);
System.out.println("The isPubliclyTraded is: " + refFive.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refFive.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refFive.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refFive.numberOfOffices);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The businessType is: " + refFive.businessType);
System.out.println("The hasRnDDepartment  is: " + refFive.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refFive.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refFive.hasOnlinePresence);
System.out.println("The companyMotto is: " + refFive.companyMotto);
Company refSix = new Company();

System.out.println("The companyId is: " + refSix.companyId);
System.out.println("The companyName is: " + refSix.companyName);
System.out.println("The industryType is: " + refSix.industryType);
System.out.println("The ceoName is: " + refSix.ceoName);
System.out.println("The founderName is: " + refSix.founderName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The headquartersLocation is: " + refSix.headquartersLocation);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfEmployees is: " + refSix.numberOfEmployees);
System.out.println("The annualRevenue is: " + refSix.annualRevenue);
System.out.println("The marketCap is: " + refSix.marketCap);
System.out.println("The isPubliclyTraded is: " + refSix.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refSix.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refSix.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refSix.numberOfOffices);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The businessType is: " + refSix.businessType);
System.out.println("The hasRnDDepartment  is: " + refSix.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refSix.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refSix.hasOnlinePresence);
System.out.println("The companyMotto is: " + refSix.companyMotto);

refSix.companyId = 6;
refSix.companyName = "Orbit Logistics";
refSix.industryType = "Logistics & Supply Chain";
refSix.ceoName = "Amit Verma";
refSix.founderName = "Suresh Nair";
refSix.establishedYear = 2010;
refSix.headquartersLocation = "Bandra Kurla Complex";
refSix.city = "Mumbai";
refSix.state = "Maharashtra";
refSix.country = "India";
refSix.numberOfEmployees = 980;
refSix.annualRevenue = 75.6;
refSix.marketCap = 340.25;
refSix.isPubliclyTraded = false;
refSix.stockSymbol = "ORB";
refSix.hasSubsidiaries = true;
refSix.numberOfOffices = 7;
refSix.contactNumber = "9876012345";
refSix.email = "support@orbitlogistics.com";
refSix.website = "www.orbitlogistics.com";
refSix.businessType = "Transportation Services";
refSix.hasRnDDepartment  = false;
refSix.hasCustomerSupport = true;
refSix.hasOnlinePresence = true;
refSix.companyMotto = "Delivering Beyond Boundaries";

System.out.println("The companyId is: " + refSix.companyId);
System.out.println("The companyName is: " + refSix.companyName);
System.out.println("The industryType is: " + refSix.industryType);
System.out.println("The ceoName is: " + refSix.ceoName);
System.out.println("The founderName is: " + refSix.founderName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The headquartersLocation is: " + refSix.headquartersLocation);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfEmployees is: " + refSix.numberOfEmployees);
System.out.println("The annualRevenue is: " + refSix.annualRevenue);
System.out.println("The marketCap is: " + refSix.marketCap);
System.out.println("The isPubliclyTraded is: " + refSix.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refSix.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refSix.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refSix.numberOfOffices);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The businessType is: " + refSix.businessType);
System.out.println("The hasRnDDepartment  is: " + refSix.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refSix.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refSix.hasOnlinePresence);
System.out.println("The companyMotto is: " + refSix.companyMotto);
Company refSeven = new Company();

System.out.println("The companyId is: " + refSeven.companyId);
System.out.println("The companyName is: " + refSeven.companyName);
System.out.println("The industryType is: " + refSeven.industryType);
System.out.println("The ceoName is: " + refSeven.ceoName);
System.out.println("The founderName is: " + refSeven.founderName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The headquartersLocation is: " + refSeven.headquartersLocation);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfEmployees is: " + refSeven.numberOfEmployees);
System.out.println("The annualRevenue is: " + refSeven.annualRevenue);
System.out.println("The marketCap is: " + refSeven.marketCap);
System.out.println("The isPubliclyTraded is: " + refSeven.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refSeven.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refSeven.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refSeven.numberOfOffices);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The businessType is: " + refSeven.businessType);
System.out.println("The hasRnDDepartment  is: " + refSeven.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refSeven.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refSeven.hasOnlinePresence);
System.out.println("The companyMotto is: " + refSeven.companyMotto);

refSeven.companyId = 7;
refSeven.companyName = "AquaPure Water Systems";
refSeven.industryType = "Water Purification";
refSeven.ceoName = "Nikhil Jain";
refSeven.founderName = "Prakash Agarwal";
refSeven.establishedYear = 2011;
refSeven.headquartersLocation = "Salt Lake Sector V";
refSeven.city = "Kolkata";
refSeven.state = "West Bengal";
refSeven.country = "India";
refSeven.numberOfEmployees = 540;
refSeven.annualRevenue = 28.9;
refSeven.marketCap = 110.45;
refSeven.isPubliclyTraded = false;
refSeven.stockSymbol = "APS";
refSeven.hasSubsidiaries = false;
refSeven.numberOfOffices = 3;
refSeven.contactNumber = "9834567120";
refSeven.email = "info@aquapure.com";
refSeven.website = "www.aquapure.com";
refSeven.businessType = "Water Treatment Solutions";
refSeven.hasRnDDepartment  = true;
refSeven.hasCustomerSupport = true;
refSeven.hasOnlinePresence = true;
refSeven.companyMotto = "Pure Water, Pure Life";

System.out.println("The companyId is: " + refSeven.companyId);
System.out.println("The companyName is: " + refSeven.companyName);
System.out.println("The industryType is: " + refSeven.industryType);
System.out.println("The ceoName is: " + refSeven.ceoName);
System.out.println("The founderName is: " + refSeven.founderName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The headquartersLocation is: " + refSeven.headquartersLocation);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfEmployees is: " + refSeven.numberOfEmployees);
System.out.println("The annualRevenue is: " + refSeven.annualRevenue);
System.out.println("The marketCap is: " + refSeven.marketCap);
System.out.println("The isPubliclyTraded is: " + refSeven.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refSeven.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refSeven.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refSeven.numberOfOffices);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The businessType is: " + refSeven.businessType);
System.out.println("The hasRnDDepartment  is: " + refSeven.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refSeven.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refSeven.hasOnlinePresence);
System.out.println("The companyMotto is: " + refSeven.companyMotto);
Company refEight = new Company();

System.out.println("The companyId is: " + refEight.companyId);
System.out.println("The companyName is: " + refEight.companyName);
System.out.println("The industryType is: " + refEight.industryType);
System.out.println("The ceoName is: " + refEight.ceoName);
System.out.println("The founderName is: " + refEight.founderName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The headquartersLocation is: " + refEight.headquartersLocation);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfEmployees is: " + refEight.numberOfEmployees);
System.out.println("The annualRevenue is: " + refEight.annualRevenue);
System.out.println("The marketCap is: " + refEight.marketCap);
System.out.println("The isPubliclyTraded is: " + refEight.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refEight.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refEight.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refEight.numberOfOffices);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The businessType is: " + refEight.businessType);
System.out.println("The hasRnDDepartment  is: " + refEight.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refEight.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refEight.hasOnlinePresence);
System.out.println("The companyMotto is: " + refEight.companyMotto);

refEight.companyId = 8;
refEight.companyName = "NextGen Robotics";
refEight.industryType = "Robotics & Automation";
refEight.ceoName = "Rahul Menon";
refEight.founderName = "Sanjay Kulkarni";
refEight.establishedYear = 2016;
refEight.headquartersLocation = "Infopark";
refEight.city = "Kochi";
refEight.state = "Kerala";
refEight.country = "India";
refEight.numberOfEmployees = 420;
refEight.annualRevenue = 22.5;
refEight.marketCap = 95.8;
refEight.isPubliclyTraded = false;
refEight.stockSymbol = "NGR";
refEight.hasSubsidiaries = false;
refEight.numberOfOffices = 2;
refEight.contactNumber = "9898765432";
refEight.email = "contact@nextgenrobotics.com";
refEight.website = "www.nextgenrobotics.com";
refEight.businessType = "Automation Solutions";
refEight.hasRnDDepartment  = true;
refEight.hasCustomerSupport = true;
refEight.hasOnlinePresence = true;
refEight.companyMotto = "Building the Future with Robots";

System.out.println("The companyId is: " + refEight.companyId);
System.out.println("The companyName is: " + refEight.companyName);
System.out.println("The industryType is: " + refEight.industryType);
System.out.println("The ceoName is: " + refEight.ceoName);
System.out.println("The founderName is: " + refEight.founderName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The headquartersLocation is: " + refEight.headquartersLocation);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfEmployees is: " + refEight.numberOfEmployees);
System.out.println("The annualRevenue is: " + refEight.annualRevenue);
System.out.println("The marketCap is: " + refEight.marketCap);
System.out.println("The isPubliclyTraded is: " + refEight.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refEight.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refEight.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refEight.numberOfOffices);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The businessType is: " + refEight.businessType);
System.out.println("The hasRnDDepartment  is: " + refEight.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refEight.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refEight.hasOnlinePresence);
System.out.println("The companyMotto is: " + refEight.companyMotto);
Company refNine = new Company();

System.out.println("The companyId is: " + refNine.companyId);
System.out.println("The companyName is: " + refNine.companyName);
System.out.println("The industryType is: " + refNine.industryType);
System.out.println("The ceoName is: " + refNine.ceoName);
System.out.println("The founderName is: " + refNine.founderName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The headquartersLocation is: " + refNine.headquartersLocation);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfEmployees is: " + refNine.numberOfEmployees);
System.out.println("The annualRevenue is: " + refNine.annualRevenue);
System.out.println("The marketCap is: " + refNine.marketCap);
System.out.println("The isPubliclyTraded is: " + refNine.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refNine.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refNine.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refNine.numberOfOffices);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The businessType is: " + refNine.businessType);
System.out.println("The hasRnDDepartment  is: " + refNine.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refNine.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refNine.hasOnlinePresence);
System.out.println("The companyMotto is: " + refNine.companyMotto);

refNine.companyId = 9;
refNine.companyName = "BrightPath Education";
refNine.industryType = "Education Technology";
refNine.ceoName = "Sneha Iyer";
refNine.founderName = "Arvind Iyer";
refNine.establishedYear = 2014;
refNine.headquartersLocation = "T Nagar";
refNine.city = "Chennai";
refNine.state = "Tamil Nadu";
refNine.country = "India";
refNine.numberOfEmployees = 300;
refNine.annualRevenue = 15.4;
refNine.marketCap = 70.2;
refNine.isPubliclyTraded = false;
refNine.stockSymbol = "BPE";
refNine.hasSubsidiaries = false;
refNine.numberOfOffices = 2;
refNine.contactNumber = "9845671230";
refNine.email = "info@brightpath.com";
refNine.website = "www.brightpathedu.com";
refNine.businessType = "Online Learning Platform";
refNine.hasRnDDepartment  = true;
refNine.hasCustomerSupport = true;
refNine.hasOnlinePresence = true;
refNine.companyMotto = "Learning for a Brighter Tomorrow";

System.out.println("The companyId is: " + refNine.companyId);
System.out.println("The companyName is: " + refNine.companyName);
System.out.println("The industryType is: " + refNine.industryType);
System.out.println("The ceoName is: " + refNine.ceoName);
System.out.println("The founderName is: " + refNine.founderName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The headquartersLocation is: " + refNine.headquartersLocation);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfEmployees is: " + refNine.numberOfEmployees);
System.out.println("The annualRevenue is: " + refNine.annualRevenue);
System.out.println("The marketCap is: " + refNine.marketCap);
System.out.println("The isPubliclyTraded is: " + refNine.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refNine.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refNine.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refNine.numberOfOffices);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The businessType is: " + refNine.businessType);
System.out.println("The hasRnDDepartment  is: " + refNine.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refNine.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refNine.hasOnlinePresence);
System.out.println("The companyMotto is: " + refNine.companyMotto);
Company refTen = new Company();

System.out.println("The companyId is: " + refTen.companyId);
System.out.println("The companyName is: " + refTen.companyName);
System.out.println("The industryType is: " + refTen.industryType);
System.out.println("The ceoName is: " + refTen.ceoName);
System.out.println("The founderName is: " + refTen.founderName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The headquartersLocation is: " + refTen.headquartersLocation);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfEmployees is: " + refTen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refTen.annualRevenue);
System.out.println("The marketCap is: " + refTen.marketCap);
System.out.println("The isPubliclyTraded is: " + refTen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refTen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refTen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refTen.numberOfOffices);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The businessType is: " + refTen.businessType);
System.out.println("The hasRnDDepartment  is: " + refTen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refTen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refTen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refTen.companyMotto);

refTen.companyId = 10;
refTen.companyName = "EcoBuild Constructions";
refTen.industryType = "Construction";
refTen.ceoName = "Pradeep Shetty";
refTen.founderName = "Mahesh Shetty";
refTen.establishedYear = 2003;
refTen.headquartersLocation = "Yeshwanthpur";
refTen.city = "Bengaluru";
refTen.state = "Karnataka";
refTen.country = "India";
refTen.numberOfEmployees = 1400;
refTen.annualRevenue = 210.8;
refTen.marketCap = 780.6;
refTen.isPubliclyTraded = false;
refTen.stockSymbol = "EBC";
refTen.hasSubsidiaries = true;
refTen.numberOfOffices = 6;
refTen.contactNumber = "9876541203";
refTen.email = "contact@ecobuild.com";
refTen.website = "www.ecobuild.com";
refTen.businessType = "Infrastructure Development";
refTen.hasRnDDepartment  = false;
refTen.hasCustomerSupport = true;
refTen.hasOnlinePresence = true;
refTen.companyMotto = "Building a Sustainable Future";

System.out.println("The companyId is: " + refTen.companyId);
System.out.println("The companyName is: " + refTen.companyName);
System.out.println("The industryType is: " + refTen.industryType);
System.out.println("The ceoName is: " + refTen.ceoName);
System.out.println("The founderName is: " + refTen.founderName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The headquartersLocation is: " + refTen.headquartersLocation);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfEmployees is: " + refTen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refTen.annualRevenue);
System.out.println("The marketCap is: " + refTen.marketCap);
System.out.println("The isPubliclyTraded is: " + refTen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refTen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refTen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refTen.numberOfOffices);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The businessType is: " + refTen.businessType);
System.out.println("The hasRnDDepartment  is: " + refTen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refTen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refTen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refTen.companyMotto);
Company refEleven = new Company();

System.out.println("The companyId is: " + refEleven.companyId);
System.out.println("The companyName is: " + refEleven.companyName);
System.out.println("The industryType is: " + refEleven.industryType);
System.out.println("The ceoName is: " + refEleven.ceoName);
System.out.println("The founderName is: " + refEleven.founderName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The headquartersLocation is: " + refEleven.headquartersLocation);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfEmployees is: " + refEleven.numberOfEmployees);
System.out.println("The annualRevenue is: " + refEleven.annualRevenue);
System.out.println("The marketCap is: " + refEleven.marketCap);
System.out.println("The isPubliclyTraded is: " + refEleven.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refEleven.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refEleven.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refEleven.numberOfOffices);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The businessType is: " + refEleven.businessType);
System.out.println("The hasRnDDepartment  is: " + refEleven.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refEleven.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refEleven.hasOnlinePresence);
System.out.println("The companyMotto is: " + refEleven.companyMotto);

refEleven.companyId = 11;
refEleven.companyName = "FreshFarm Foods";
refEleven.industryType = "Food Processing";
refEleven.ceoName = "Anil Kumar";
refEleven.founderName = "Ravi Kumar";
refEleven.establishedYear = 2007;
refEleven.headquartersLocation = "Peenya Industrial Area";
refEleven.city = "Bengaluru";
refEleven.state = "Karnataka";
refEleven.country = "India";
refEleven.numberOfEmployees = 670;
refEleven.annualRevenue = 52.3;
refEleven.marketCap = 190.7;
refEleven.isPubliclyTraded = false;
refEleven.stockSymbol = "FFF";
refEleven.hasSubsidiaries = true;
refEleven.numberOfOffices = 4;
refEleven.contactNumber = "9887654321";
refEleven.email = "info@freshfarmfoods.com";
refEleven.website = "www.freshfarmfoods.com";
refEleven.businessType = "Food Production";
refEleven.hasRnDDepartment  = true;
refEleven.hasCustomerSupport = true;
refEleven.hasOnlinePresence = true;
refEleven.companyMotto = "Freshness in Every Bite";

System.out.println("The companyId is: " + refEleven.companyId);
System.out.println("The companyName is: " + refEleven.companyName);
System.out.println("The industryType is: " + refEleven.industryType);
System.out.println("The ceoName is: " + refEleven.ceoName);
System.out.println("The founderName is: " + refEleven.founderName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The headquartersLocation is: " + refEleven.headquartersLocation);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfEmployees is: " + refEleven.numberOfEmployees);
System.out.println("The annualRevenue is: " + refEleven.annualRevenue);
System.out.println("The marketCap is: " + refEleven.marketCap);
System.out.println("The isPubliclyTraded is: " + refEleven.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refEleven.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refEleven.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refEleven.numberOfOffices);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The businessType is: " + refEleven.businessType);
System.out.println("The hasRnDDepartment  is: " + refEleven.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refEleven.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refEleven.hasOnlinePresence);
System.out.println("The companyMotto is: " + refEleven.companyMotto);
Company refTwelve = new Company();

System.out.println("The companyId is: " + refTwelve.companyId);
System.out.println("The companyName is: " + refTwelve.companyName);
System.out.println("The industryType is: " + refTwelve.industryType);
System.out.println("The ceoName is: " + refTwelve.ceoName);
System.out.println("The founderName is: " + refTwelve.founderName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The headquartersLocation is: " + refTwelve.headquartersLocation);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfEmployees is: " + refTwelve.numberOfEmployees);
System.out.println("The annualRevenue is: " + refTwelve.annualRevenue);
System.out.println("The marketCap is: " + refTwelve.marketCap);
System.out.println("The isPubliclyTraded is: " + refTwelve.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refTwelve.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refTwelve.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refTwelve.numberOfOffices);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The businessType is: " + refTwelve.businessType);
System.out.println("The hasRnDDepartment  is: " + refTwelve.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refTwelve.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refTwelve.hasOnlinePresence);
System.out.println("The companyMotto is: " + refTwelve.companyMotto);

refTwelve.companyId = 12;
refTwelve.companyName = "UrbanStyle Fashion";
refTwelve.industryType = "Fashion & Apparel";
refTwelve.ceoName = "Pooja Mehra";
refTwelve.founderName = "Rohit Mehra";
refTwelve.establishedYear = 2013;
refTwelve.headquartersLocation = "Connaught Place";
refTwelve.city = "New Delhi";
refTwelve.state = "Delhi";
refTwelve.country = "India";
refTwelve.numberOfEmployees = 480;
refTwelve.annualRevenue = 35.7;
refTwelve.marketCap = 150.9;
refTwelve.isPubliclyTraded = false;
refTwelve.stockSymbol = "USF";
refTwelve.hasSubsidiaries = false;
refTwelve.numberOfOffices = 3;
refTwelve.contactNumber = "9811122233";
refTwelve.email = "info@urbanstyle.com";
refTwelve.website = "www.urbanstyle.com";
refTwelve.businessType = "Retail Fashion";
refTwelve.hasRnDDepartment  = false;
refTwelve.hasCustomerSupport = true;
refTwelve.hasOnlinePresence = true;
refTwelve.companyMotto = "Style that Defines You";

System.out.println("The companyId is: " + refTwelve.companyId);
System.out.println("The companyName is: " + refTwelve.companyName);
System.out.println("The industryType is: " + refTwelve.industryType);
System.out.println("The ceoName is: " + refTwelve.ceoName);
System.out.println("The founderName is: " + refTwelve.founderName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The headquartersLocation is: " + refTwelve.headquartersLocation);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfEmployees is: " + refTwelve.numberOfEmployees);
System.out.println("The annualRevenue is: " + refTwelve.annualRevenue);
System.out.println("The marketCap is: " + refTwelve.marketCap);
System.out.println("The isPubliclyTraded is: " + refTwelve.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refTwelve.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refTwelve.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refTwelve.numberOfOffices);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The businessType is: " + refTwelve.businessType);
System.out.println("The hasRnDDepartment  is: " + refTwelve.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refTwelve.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refTwelve.hasOnlinePresence);
System.out.println("The companyMotto is: " + refTwelve.companyMotto);
Company refThirteen = new Company();

System.out.println("The companyId is: " + refThirteen.companyId);
System.out.println("The companyName is: " + refThirteen.companyName);
System.out.println("The industryType is: " + refThirteen.industryType);
System.out.println("The ceoName is: " + refThirteen.ceoName);
System.out.println("The founderName is: " + refThirteen.founderName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The headquartersLocation is: " + refThirteen.headquartersLocation);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfEmployees is: " + refThirteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refThirteen.annualRevenue);
System.out.println("The marketCap is: " + refThirteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refThirteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refThirteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refThirteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refThirteen.numberOfOffices);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The businessType is: " + refThirteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refThirteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refThirteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refThirteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refThirteen.companyMotto);

refThirteen.companyId = 13;
refThirteen.companyName = "TravelNest Tours";
refThirteen.industryType = "Travel & Tourism";
refThirteen.ceoName = "Aditya Singh";
refThirteen.founderName = "Meera Singh";
refThirteen.establishedYear = 2011;
refThirteen.headquartersLocation = "MG Road";
refThirteen.city = "Pune";
refThirteen.state = "Maharashtra";
refThirteen.country = "India";
refThirteen.numberOfEmployees = 260;
refThirteen.annualRevenue = 18.5;
refThirteen.marketCap = 75.4;
refThirteen.isPubliclyTraded = false;
refThirteen.stockSymbol = "TNT";
refThirteen.hasSubsidiaries = false;
refThirteen.numberOfOffices = 2;
refThirteen.contactNumber = "9823456712";
refThirteen.email = "info@travelnest.com";
refThirteen.website = "www.travelnest.com";
refThirteen.businessType = "Tour Packages";
refThirteen.hasRnDDepartment  = false;
refThirteen.hasCustomerSupport = true;
refThirteen.hasOnlinePresence = true;
refThirteen.companyMotto = "Explore the World with Us";

System.out.println("The companyId is: " + refThirteen.companyId);
System.out.println("The companyName is: " + refThirteen.companyName);
System.out.println("The industryType is: " + refThirteen.industryType);
System.out.println("The ceoName is: " + refThirteen.ceoName);
System.out.println("The founderName is: " + refThirteen.founderName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The headquartersLocation is: " + refThirteen.headquartersLocation);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfEmployees is: " + refThirteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refThirteen.annualRevenue);
System.out.println("The marketCap is: " + refThirteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refThirteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refThirteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refThirteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refThirteen.numberOfOffices);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The businessType is: " + refThirteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refThirteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refThirteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refThirteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refThirteen.companyMotto);
Company refFourteen = new Company();

System.out.println("The companyId is: " + refFourteen.companyId);
System.out.println("The companyName is: " + refFourteen.companyName);
System.out.println("The industryType is: " + refFourteen.industryType);
System.out.println("The ceoName is: " + refFourteen.ceoName);
System.out.println("The founderName is: " + refFourteen.founderName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The headquartersLocation is: " + refFourteen.headquartersLocation);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfEmployees is: " + refFourteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refFourteen.annualRevenue);
System.out.println("The marketCap is: " + refFourteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refFourteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refFourteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refFourteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refFourteen.numberOfOffices);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The businessType is: " + refFourteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refFourteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refFourteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refFourteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refFourteen.companyMotto);

refFourteen.companyId = 14;
refFourteen.companyName = "MediCare Hospitals";
refFourteen.industryType = "Healthcare";
refFourteen.ceoName = "Dr. Arvind Rao";
refFourteen.founderName = "Dr. Meena Rao";
refFourteen.establishedYear = 2001;
refFourteen.headquartersLocation = "Banjara Hills";
refFourteen.city = "Hyderabad";
refFourteen.state = "Telangana";
refFourteen.country = "India";
refFourteen.numberOfEmployees = 3200;
refFourteen.annualRevenue = 420.6;
refFourteen.marketCap = 1500.3;
refFourteen.isPubliclyTraded = true;
refFourteen.stockSymbol = "MCH";
refFourteen.hasSubsidiaries = true;
refFourteen.numberOfOffices = 12;
refFourteen.contactNumber = "9845012345";
refFourteen.email = "contact@medicare.com";
refFourteen.website = "www.medicarehospitals.com";
refFourteen.businessType = "Hospital Services";
refFourteen.hasRnDDepartment  = true;
refFourteen.hasCustomerSupport = true;
refFourteen.hasOnlinePresence = true;
refFourteen.companyMotto = "Caring for Life";

System.out.println("The companyId is: " + refFourteen.companyId);
System.out.println("The companyName is: " + refFourteen.companyName);
System.out.println("The industryType is: " + refFourteen.industryType);
System.out.println("The ceoName is: " + refFourteen.ceoName);
System.out.println("The founderName is: " + refFourteen.founderName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The headquartersLocation is: " + refFourteen.headquartersLocation);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfEmployees is: " + refFourteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refFourteen.annualRevenue);
System.out.println("The marketCap is: " + refFourteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refFourteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refFourteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refFourteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refFourteen.numberOfOffices);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The businessType is: " + refFourteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refFourteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refFourteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refFourteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refFourteen.companyMotto);
Company refFifteen = new Company();

System.out.println("The companyId is: " + refFifteen.companyId);
System.out.println("The companyName is: " + refFifteen.companyName);
System.out.println("The industryType is: " + refFifteen.industryType);
System.out.println("The ceoName is: " + refFifteen.ceoName);
System.out.println("The founderName is: " + refFifteen.founderName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The headquartersLocation is: " + refFifteen.headquartersLocation);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfEmployees is: " + refFifteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refFifteen.annualRevenue);
System.out.println("The marketCap is: " + refFifteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refFifteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refFifteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refFifteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refFifteen.numberOfOffices);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The businessType is: " + refFifteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refFifteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refFifteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refFifteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refFifteen.companyMotto);

refFifteen.companyId = 15;
refFifteen.companyName = "SmartHome Innovations";
refFifteen.industryType = "Home Automation";
refFifteen.ceoName = "Kiran Patel";
refFifteen.founderName = "Vishal Shah";
refFifteen.establishedYear = 2017;
refFifteen.headquartersLocation = "Satellite Road";
refFifteen.city = "Ahmedabad";
refFifteen.state = "Gujarat";
refFifteen.country = "India";
refFifteen.numberOfEmployees = 210;
refFifteen.annualRevenue = 12.9;
refFifteen.marketCap = 60.4;
refFifteen.isPubliclyTraded = false;
refFifteen.stockSymbol = "SHI";
refFifteen.hasSubsidiaries = false;
refFifteen.numberOfOffices = 2;
refFifteen.contactNumber = "9890012345";
refFifteen.email = "info@smarthomeinnovations.com";
refFifteen.website = "www.smarthomeinnovations.com";
refFifteen.businessType = "IoT Products";
refFifteen.hasRnDDepartment  = true;
refFifteen.hasCustomerSupport = true;
refFifteen.hasOnlinePresence = true;
refFifteen.companyMotto = "Smart Living Made Simple";

System.out.println("The companyId is: " + refFifteen.companyId);
System.out.println("The companyName is: " + refFifteen.companyName);
System.out.println("The industryType is: " + refFifteen.industryType);
System.out.println("The ceoName is: " + refFifteen.ceoName);
System.out.println("The founderName is: " + refFifteen.founderName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The headquartersLocation is: " + refFifteen.headquartersLocation);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfEmployees is: " + refFifteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refFifteen.annualRevenue);
System.out.println("The marketCap is: " + refFifteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refFifteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refFifteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refFifteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refFifteen.numberOfOffices);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The businessType is: " + refFifteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refFifteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refFifteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refFifteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refFifteen.companyMotto);
Company refSixteen = new Company();

System.out.println("The companyId is: " + refSixteen.companyId);
System.out.println("The companyName is: " + refSixteen.companyName);
System.out.println("The industryType is: " + refSixteen.industryType);
System.out.println("The ceoName is: " + refSixteen.ceoName);
System.out.println("The founderName is: " + refSixteen.founderName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The headquartersLocation is: " + refSixteen.headquartersLocation);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfEmployees is: " + refSixteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refSixteen.annualRevenue);
System.out.println("The marketCap is: " + refSixteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refSixteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refSixteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refSixteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refSixteen.numberOfOffices);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The businessType is: " + refSixteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refSixteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refSixteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refSixteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refSixteen.companyMotto);

refSixteen.companyId = 16;
refSixteen.companyName = "GreenEnergy Power";
refSixteen.industryType = "Renewable Energy";
refSixteen.ceoName = "Sanjay Verma";
refSixteen.founderName = "Deepak Verma";
refSixteen.establishedYear = 2012;
refSixteen.headquartersLocation = "Sector 18";
refSixteen.city = "Chandigarh";
refSixteen.state = "Punjab";
refSixteen.country = "India";
refSixteen.numberOfEmployees = 530;
refSixteen.annualRevenue = 48.2;
refSixteen.marketCap = 175.6;
refSixteen.isPubliclyTraded = true;
refSixteen.stockSymbol = "GEP";
refSixteen.hasSubsidiaries = true;
refSixteen.numberOfOffices = 5;
refSixteen.contactNumber = "9873401234";
refSixteen.email = "info@greenenergy.com";
refSixteen.website = "www.greenenergy.com";
refSixteen.businessType = "Solar & Wind Energy";
refSixteen.hasRnDDepartment  = true;
refSixteen.hasCustomerSupport = true;
refSixteen.hasOnlinePresence = true;
refSixteen.companyMotto = "Powering a Greener Tomorrow";

System.out.println("The companyId is: " + refSixteen.companyId);
System.out.println("The companyName is: " + refSixteen.companyName);
System.out.println("The industryType is: " + refSixteen.industryType);
System.out.println("The ceoName is: " + refSixteen.ceoName);
System.out.println("The founderName is: " + refSixteen.founderName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The headquartersLocation is: " + refSixteen.headquartersLocation);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfEmployees is: " + refSixteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refSixteen.annualRevenue);
System.out.println("The marketCap is: " + refSixteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refSixteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refSixteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refSixteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refSixteen.numberOfOffices);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The businessType is: " + refSixteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refSixteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refSixteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refSixteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refSixteen.companyMotto);
Company refSeventeen = new Company();

System.out.println("The companyId is: " + refSeventeen.companyId);
System.out.println("The companyName is: " + refSeventeen.companyName);
System.out.println("The industryType is: " + refSeventeen.industryType);
System.out.println("The ceoName is: " + refSeventeen.ceoName);
System.out.println("The founderName is: " + refSeventeen.founderName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The headquartersLocation is: " + refSeventeen.headquartersLocation);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfEmployees is: " + refSeventeen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refSeventeen.annualRevenue);
System.out.println("The marketCap is: " + refSeventeen.marketCap);
System.out.println("The isPubliclyTraded is: " + refSeventeen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refSeventeen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refSeventeen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refSeventeen.numberOfOffices);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The businessType is: " + refSeventeen.businessType);
System.out.println("The hasRnDDepartment  is: " + refSeventeen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refSeventeen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refSeventeen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refSeventeen.companyMotto);

refSeventeen.companyId = 17;
refSeventeen.companyName = "FutureTech Labs";
refSeventeen.industryType = "Software Development";
refSeventeen.ceoName = "Rahul Sharma";
refSeventeen.founderName = "Ankit Sharma";
refSeventeen.establishedYear = 2018;
refSeventeen.headquartersLocation = "Cyber City";
refSeventeen.city = "Gurgaon";
refSeventeen.state = "Haryana";
refSeventeen.country = "India";
refSeventeen.numberOfEmployees = 390;
refSeventeen.annualRevenue = 25.6;
refSeventeen.marketCap = 120.4;
refSeventeen.isPubliclyTraded = false;
refSeventeen.stockSymbol = "FTL";
refSeventeen.hasSubsidiaries = false;
refSeventeen.numberOfOffices = 3;
refSeventeen.contactNumber = "9898761200";
refSeventeen.email = "info@futuretechlabs.com";
refSeventeen.website = "www.futuretechlabs.com";
refSeventeen.businessType = "AI & Software Solutions";
refSeventeen.hasRnDDepartment  = true;
refSeventeen.hasCustomerSupport = true;
refSeventeen.hasOnlinePresence = true;
refSeventeen.companyMotto = "Technology for Tomorrow";

System.out.println("The companyId is: " + refSeventeen.companyId);
System.out.println("The companyName is: " + refSeventeen.companyName);
System.out.println("The industryType is: " + refSeventeen.industryType);
System.out.println("The ceoName is: " + refSeventeen.ceoName);
System.out.println("The founderName is: " + refSeventeen.founderName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The headquartersLocation is: " + refSeventeen.headquartersLocation);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfEmployees is: " + refSeventeen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refSeventeen.annualRevenue);
System.out.println("The marketCap is: " + refSeventeen.marketCap);
System.out.println("The isPubliclyTraded is: " + refSeventeen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refSeventeen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refSeventeen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refSeventeen.numberOfOffices);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The businessType is: " + refSeventeen.businessType);
System.out.println("The hasRnDDepartment  is: " + refSeventeen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refSeventeen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refSeventeen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refSeventeen.companyMotto);
Company refEighteen = new Company();

System.out.println("The companyId is: " + refEighteen.companyId);
System.out.println("The companyName is: " + refEighteen.companyName);
System.out.println("The industryType is: " + refEighteen.industryType);
System.out.println("The ceoName is: " + refEighteen.ceoName);
System.out.println("The founderName is: " + refEighteen.founderName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The headquartersLocation is: " + refEighteen.headquartersLocation);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfEmployees is: " + refEighteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refEighteen.annualRevenue);
System.out.println("The marketCap is: " + refEighteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refEighteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refEighteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refEighteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refEighteen.numberOfOffices);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The businessType is: " + refEighteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refEighteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refEighteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refEighteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refEighteen.companyMotto);

refEighteen.companyId = 18;
refEighteen.companyName = "DigitalWave Media";
refEighteen.industryType = "Digital Marketing";
refEighteen.ceoName = "Priya Nair";
refEighteen.founderName = "Rohan Nair";
refEighteen.establishedYear = 2016;
refEighteen.headquartersLocation = "Koramangala";
refEighteen.city = "Bengaluru";
refEighteen.state = "Karnataka";
refEighteen.country = "India";
refEighteen.numberOfEmployees = 310;
refEighteen.annualRevenue = 21.4;
refEighteen.marketCap = 95.7;
refEighteen.isPubliclyTraded = false;
refEighteen.stockSymbol = "DWM";
refEighteen.hasSubsidiaries = false;
refEighteen.numberOfOffices = 2;
refEighteen.contactNumber = "9876547890";
refEighteen.email = "contact@digitalwave.com";
refEighteen.website = "www.digitalwave.com";
refEighteen.businessType = "Marketing Services";
refEighteen.hasRnDDepartment  = false;
refEighteen.hasCustomerSupport = true;
refEighteen.hasOnlinePresence = true;
refEighteen.companyMotto = "Your Growth, Our Strategy";

System.out.println("The companyId is: " + refEighteen.companyId);
System.out.println("The companyName is: " + refEighteen.companyName);
System.out.println("The industryType is: " + refEighteen.industryType);
System.out.println("The ceoName is: " + refEighteen.ceoName);
System.out.println("The founderName is: " + refEighteen.founderName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The headquartersLocation is: " + refEighteen.headquartersLocation);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfEmployees is: " + refEighteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refEighteen.annualRevenue);
System.out.println("The marketCap is: " + refEighteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refEighteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refEighteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refEighteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refEighteen.numberOfOffices);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The businessType is: " + refEighteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refEighteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refEighteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refEighteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refEighteen.companyMotto);
Company refNineteen = new Company();

System.out.println("The companyId is: " + refNineteen.companyId);
System.out.println("The companyName is: " + refNineteen.companyName);
System.out.println("The industryType is: " + refNineteen.industryType);
System.out.println("The ceoName is: " + refNineteen.ceoName);
System.out.println("The founderName is: " + refNineteen.founderName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The headquartersLocation is: " + refNineteen.headquartersLocation);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfEmployees is: " + refNineteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refNineteen.annualRevenue);
System.out.println("The marketCap is: " + refNineteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refNineteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refNineteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refNineteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refNineteen.numberOfOffices);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The businessType is: " + refNineteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refNineteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refNineteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refNineteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refNineteen.companyMotto);

refNineteen.companyId = 19;
refNineteen.companyName = "AutoDrive Motors";
refNineteen.industryType = "Automobile Manufacturing";
refNineteen.ceoName = "Rajiv Malhotra";
refNineteen.founderName = "Sanjay Malhotra";
refNineteen.establishedYear = 2009;
refNineteen.headquartersLocation = "Manesar";
refNineteen.city = "Gurgaon";
refNineteen.state = "Haryana";
refNineteen.country = "India";
refNineteen.numberOfEmployees = 2100;
refNineteen.annualRevenue = 350.7;
refNineteen.marketCap = 980.3;
refNineteen.isPubliclyTraded = true;
refNineteen.stockSymbol = "ADM";
refNineteen.hasSubsidiaries = true;
refNineteen.numberOfOffices = 9;
refNineteen.contactNumber = "9873214560";
refNineteen.email = "info@autodrive.com";
refNineteen.website = "www.autodrive.com";
refNineteen.businessType = "Vehicle Manufacturing";
refNineteen.hasRnDDepartment  = true;
refNineteen.hasCustomerSupport = true;
refNineteen.hasOnlinePresence = true;
refNineteen.companyMotto = "Driving the Future";

System.out.println("The companyId is: " + refNineteen.companyId);
System.out.println("The companyName is: " + refNineteen.companyName);
System.out.println("The industryType is: " + refNineteen.industryType);
System.out.println("The ceoName is: " + refNineteen.ceoName);
System.out.println("The founderName is: " + refNineteen.founderName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The headquartersLocation is: " + refNineteen.headquartersLocation);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfEmployees is: " + refNineteen.numberOfEmployees);
System.out.println("The annualRevenue is: " + refNineteen.annualRevenue);
System.out.println("The marketCap is: " + refNineteen.marketCap);
System.out.println("The isPubliclyTraded is: " + refNineteen.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refNineteen.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refNineteen.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refNineteen.numberOfOffices);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The businessType is: " + refNineteen.businessType);
System.out.println("The hasRnDDepartment  is: " + refNineteen.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refNineteen.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refNineteen.hasOnlinePresence);
System.out.println("The companyMotto is: " + refNineteen.companyMotto);
Company refTwenty = new Company();

System.out.println("The companyId is: " + refTwenty.companyId);
System.out.println("The companyName is: " + refTwenty.companyName);
System.out.println("The industryType is: " + refTwenty.industryType);
System.out.println("The ceoName is: " + refTwenty.ceoName);
System.out.println("The founderName is: " + refTwenty.founderName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The headquartersLocation is: " + refTwenty.headquartersLocation);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfEmployees is: " + refTwenty.numberOfEmployees);
System.out.println("The annualRevenue is: " + refTwenty.annualRevenue);
System.out.println("The marketCap is: " + refTwenty.marketCap);
System.out.println("The isPubliclyTraded is: " + refTwenty.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refTwenty.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refTwenty.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refTwenty.numberOfOffices);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The businessType is: " + refTwenty.businessType);
System.out.println("The hasRnDDepartment  is: " + refTwenty.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refTwenty.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refTwenty.hasOnlinePresence);
System.out.println("The companyMotto is: " + refTwenty.companyMotto);

refTwenty.companyId = 20;
refTwenty.companyName = "Skyline Infrastructure";
refTwenty.industryType = "Real Estate & Infrastructure";
refTwenty.ceoName = "Manoj Bansal";
refTwenty.founderName = "Rakesh Bansal";
refTwenty.establishedYear = 2004;
refTwenty.headquartersLocation = "DLF Phase 3";
refTwenty.city = "Gurgaon";
refTwenty.state = "Haryana";
refTwenty.country = "India";
refTwenty.numberOfEmployees = 1700;
refTwenty.annualRevenue = 280.9;
refTwenty.marketCap = 860.5;
refTwenty.isPubliclyTraded = true;
refTwenty.stockSymbol = "SKI";
refTwenty.hasSubsidiaries = true;
refTwenty.numberOfOffices = 8;
refTwenty.contactNumber = "9812340098";
refTwenty.email = "info@skylineinfra.com";
refTwenty.website = "www.skylineinfra.com";
refTwenty.businessType = "Construction & Real Estate";
refTwenty.hasRnDDepartment  = false;
refTwenty.hasCustomerSupport = true;
refTwenty.hasOnlinePresence = true;
refTwenty.companyMotto = "Building Cities, Building Future";

System.out.println("The companyId is: " + refTwenty.companyId);
System.out.println("The companyName is: " + refTwenty.companyName);
System.out.println("The industryType is: " + refTwenty.industryType);
System.out.println("The ceoName is: " + refTwenty.ceoName);
System.out.println("The founderName is: " + refTwenty.founderName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The headquartersLocation is: " + refTwenty.headquartersLocation);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfEmployees is: " + refTwenty.numberOfEmployees);
System.out.println("The annualRevenue is: " + refTwenty.annualRevenue);
System.out.println("The marketCap is: " + refTwenty.marketCap);
System.out.println("The isPubliclyTraded is: " + refTwenty.isPubliclyTraded);
System.out.println("The stockSymbol is: " + refTwenty.stockSymbol);
System.out.println("The hasSubsidiaries is: " + refTwenty.hasSubsidiaries);
System.out.println("The numberOfOffices is: " + refTwenty.numberOfOffices);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The businessType is: " + refTwenty.businessType);
System.out.println("The hasRnDDepartment  is: " + refTwenty.hasRnDDepartment );
System.out.println("The hasCustomerSupport is: " + refTwenty.hasCustomerSupport);
System.out.println("The hasOnlinePresence is: " + refTwenty.hasOnlinePresence);
System.out.println("The companyMotto is: " + refTwenty.companyMotto);
}
}