class EmployeeExecutor{
public static void main(String[] args){
Employee refOne = new Employee();

System.out.println("The employeeId is: " + refOne.employeeId);
System.out.println("The firstName is: " + refOne.firstName);
System.out.println("The lastName is: " + refOne.lastName);
System.out.println("The gender is: " + refOne.gender);
System.out.println("The age is: " + refOne.age);
System.out.println("The department is: " + refOne.department);
System.out.println("The designation is: " + refOne.designation);
System.out.println("The salary is: " + refOne.salary);
System.out.println("The email is: " + refOne.email);
System.out.println("The phoneNumber is: " + refOne.phoneNumber);
System.out.println("The address is: " + refOne.address);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The dateOfJoining is: " + refOne.dateOfJoining);
System.out.println("The managerName is: " + refOne.managerName);
System.out.println("The isPermanent is: " + refOne.isPermanent);
System.out.println("The isRemote is: " + refOne.isRemote);
System.out.println("The experienceYears is: " + refOne.experienceYears);
System.out.println("The highestQualification is: " + refOne.highestQualification);
System.out.println("The bloodGroup is: " + refOne.bloodGroup);
System.out.println("The maritalStatus is: " + refOne.maritalStatus);
System.out.println("The nationality is: " + refOne.nationality);
System.out.println("The employeeType is: " + refOne.employeeType);
System.out.println("The workShift is: " + refOne.workShift);


refOne.employeeId = 1;
refOne.firstName = "Rahul";
refOne.lastName = "Sharma";
refOne.gender = "Male";
refOne.age = 28;
refOne.department = "Software Development";
refOne.designation = "Software Engineer";
refOne.salary = 65000.00;
refOne.email = "rahul.sharma@example.com";
refOne.phoneNumber = "9876543210";
refOne.address = "MG Road";
refOne.city = "Bengaluru";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.dateOfJoining = "12-06-2022";
refOne.managerName = "Anita Rao";
refOne.isPermanent = true;
refOne.isRemote = false;
refOne.experienceYears = 4;
refOne.highestQualification = "B.Tech Computer Science";
refOne.bloodGroup = "O+";
refOne.maritalStatus = "Single";
refOne.nationality = "Indian";
refOne.employeeType = "Full Time";
refOne.workShift = "Day";


System.out.println("The employeeId is: " + refOne.employeeId);
System.out.println("The firstName is: " + refOne.firstName);
System.out.println("The lastName is: " + refOne.lastName);
System.out.println("The gender is: " + refOne.gender);
System.out.println("The age is: " + refOne.age);
System.out.println("The department is: " + refOne.department);
System.out.println("The designation is: " + refOne.designation);
System.out.println("The salary is: " + refOne.salary);
System.out.println("The email is: " + refOne.email);
System.out.println("The phoneNumber is: " + refOne.phoneNumber);
System.out.println("The address is: " + refOne.address);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The dateOfJoining is: " + refOne.dateOfJoining);
System.out.println("The managerName is: " + refOne.managerName);
System.out.println("The isPermanent is: " + refOne.isPermanent);
System.out.println("The isRemote is: " + refOne.isRemote);
System.out.println("The experienceYears is: " + refOne.experienceYears);
System.out.println("The highestQualification is: " + refOne.highestQualification);
System.out.println("The bloodGroup is: " + refOne.bloodGroup);
System.out.println("The maritalStatus is: " + refOne.maritalStatus);
System.out.println("The nationality is: " + refOne.nationality);
System.out.println("The employeeType is: " + refOne.employeeType);
System.out.println("The workShift is: " + refOne.workShift);
Employee refTwo = new Employee();

System.out.println("The employeeId is: " + refTwo.employeeId);
System.out.println("The firstName is: " + refTwo.firstName);
System.out.println("The lastName is: " + refTwo.lastName);
System.out.println("The gender is: " + refTwo.gender);
System.out.println("The age is: " + refTwo.age);
System.out.println("The department is: " + refTwo.department);
System.out.println("The designation is: " + refTwo.designation);
System.out.println("The salary is: " + refTwo.salary);
System.out.println("The email is: " + refTwo.email);
System.out.println("The phoneNumber is: " + refTwo.phoneNumber);
System.out.println("The address is: " + refTwo.address);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The dateOfJoining is: " + refTwo.dateOfJoining);
System.out.println("The managerName is: " + refTwo.managerName);
System.out.println("The isPermanent is: " + refTwo.isPermanent);
System.out.println("The isRemote is: " + refTwo.isRemote);
System.out.println("The experienceYears is: " + refTwo.experienceYears);
System.out.println("The highestQualification is: " + refTwo.highestQualification);
System.out.println("The bloodGroup is: " + refTwo.bloodGroup);
System.out.println("The maritalStatus is: " + refTwo.maritalStatus);
System.out.println("The nationality is: " + refTwo.nationality);
System.out.println("The employeeType is: " + refTwo.employeeType);
System.out.println("The workShift is: " + refTwo.workShift);


refTwo.employeeId = 2;
refTwo.firstName = "Priya";
refTwo.lastName = "Nair";
refTwo.gender = "Female";
refTwo.age = 30;
refTwo.department = "Human Resources";
refTwo.designation = "HR Manager";
refTwo.salary = 72000.00;
refTwo.email = "priya.nair@example.com";
refTwo.phoneNumber = "9876501234";
refTwo.address = "Indiranagar";
refTwo.city = "Bengaluru";
refTwo.state = "Karnataka";
refTwo.country = "India";
refTwo.dateOfJoining = "15-03-2021";
refTwo.managerName = "Rakesh Menon";
refTwo.isPermanent = true;
refTwo.isRemote = true;
refTwo.experienceYears = 6;
refTwo.highestQualification = "MBA HR";
refTwo.bloodGroup = "A+";
refTwo.maritalStatus = "Married";
refTwo.nationality = "Indian";
refTwo.employeeType = "Full Time";
refTwo.workShift = "Day";


System.out.println("The employeeId is: " + refTwo.employeeId);
System.out.println("The firstName is: " + refTwo.firstName);
System.out.println("The lastName is: " + refTwo.lastName);
System.out.println("The gender is: " + refTwo.gender);
System.out.println("The age is: " + refTwo.age);
System.out.println("The department is: " + refTwo.department);
System.out.println("The designation is: " + refTwo.designation);
System.out.println("The salary is: " + refTwo.salary);
System.out.println("The email is: " + refTwo.email);
System.out.println("The phoneNumber is: " + refTwo.phoneNumber);
System.out.println("The address is: " + refTwo.address);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The dateOfJoining is: " + refTwo.dateOfJoining);
System.out.println("The managerName is: " + refTwo.managerName);
System.out.println("The isPermanent is: " + refTwo.isPermanent);
System.out.println("The isRemote is: " + refTwo.isRemote);
System.out.println("The experienceYears is: " + refTwo.experienceYears);
System.out.println("The highestQualification is: " + refTwo.highestQualification);
System.out.println("The bloodGroup is: " + refTwo.bloodGroup);
System.out.println("The maritalStatus is: " + refTwo.maritalStatus);
System.out.println("The nationality is: " + refTwo.nationality);
System.out.println("The employeeType is: " + refTwo.employeeType);
System.out.println("The workShift is: " + refTwo.workShift);
Employee refThree = new Employee();

System.out.println("The employeeId is: " + refThree.employeeId);
System.out.println("The firstName is: " + refThree.firstName);
System.out.println("The lastName is: " + refThree.lastName);
System.out.println("The gender is: " + refThree.gender);
System.out.println("The age is: " + refThree.age);
System.out.println("The department is: " + refThree.department);
System.out.println("The designation is: " + refThree.designation);
System.out.println("The salary is: " + refThree.salary);
System.out.println("The email is: " + refThree.email);
System.out.println("The phoneNumber is: " + refThree.phoneNumber);
System.out.println("The address is: " + refThree.address);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The dateOfJoining is: " + refThree.dateOfJoining);
System.out.println("The managerName is: " + refThree.managerName);
System.out.println("The isPermanent is: " + refThree.isPermanent);
System.out.println("The isRemote is: " + refThree.isRemote);
System.out.println("The experienceYears is: " + refThree.experienceYears);
System.out.println("The highestQualification is: " + refThree.highestQualification);
System.out.println("The bloodGroup is: " + refThree.bloodGroup);
System.out.println("The maritalStatus is: " + refThree.maritalStatus);
System.out.println("The nationality is: " + refThree.nationality);
System.out.println("The employeeType is: " + refThree.employeeType);
System.out.println("The workShift is: " + refThree.workShift);


refThree.employeeId = 3;
refThree.firstName = "Arjun";
refThree.lastName = "Reddy";
refThree.gender = "Male";
refThree.age = 27;
refThree.department = "Testing";
refThree.designation = "QA Engineer";
refThree.salary = 58000.00;
refThree.email = "arjun.reddy@example.com";
refThree.phoneNumber = "9123456780";
refThree.address = "Whitefield";
refThree.city = "Bengaluru";
refThree.state = "Karnataka";
refThree.country = "India";
refThree.dateOfJoining = "10-01-2023";
refThree.managerName = "Suresh Kumar";
refThree.isPermanent = true;
refThree.isRemote = false;
refThree.experienceYears = 3;
refThree.highestQualification = "B.Tech IT";
refThree.bloodGroup = "B+";
refThree.maritalStatus = "Single";
refThree.nationality = "Indian";
refThree.employeeType = "Full Time";
refThree.workShift = "Day";


System.out.println("The employeeId is: " + refThree.employeeId);
System.out.println("The firstName is: " + refThree.firstName);
System.out.println("The lastName is: " + refThree.lastName);
System.out.println("The gender is: " + refThree.gender);
System.out.println("The age is: " + refThree.age);
System.out.println("The department is: " + refThree.department);
System.out.println("The designation is: " + refThree.designation);
System.out.println("The salary is: " + refThree.salary);
System.out.println("The email is: " + refThree.email);
System.out.println("The phoneNumber is: " + refThree.phoneNumber);
System.out.println("The address is: " + refThree.address);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The dateOfJoining is: " + refThree.dateOfJoining);
System.out.println("The managerName is: " + refThree.managerName);
System.out.println("The isPermanent is: " + refThree.isPermanent);
System.out.println("The isRemote is: " + refThree.isRemote);
System.out.println("The experienceYears is: " + refThree.experienceYears);
System.out.println("The highestQualification is: " + refThree.highestQualification);
System.out.println("The bloodGroup is: " + refThree.bloodGroup);
System.out.println("The maritalStatus is: " + refThree.maritalStatus);
System.out.println("The nationality is: " + refThree.nationality);
System.out.println("The employeeType is: " + refThree.employeeType);
System.out.println("The workShift is: " + refThree.workShift);
Employee refFour = new Employee();

System.out.println("The employeeId is: " + refFour.employeeId);
System.out.println("The firstName is: " + refFour.firstName);
System.out.println("The lastName is: " + refFour.lastName);
System.out.println("The gender is: " + refFour.gender);
System.out.println("The age is: " + refFour.age);
System.out.println("The department is: " + refFour.department);
System.out.println("The designation is: " + refFour.designation);
System.out.println("The salary is: " + refFour.salary);
System.out.println("The email is: " + refFour.email);
System.out.println("The phoneNumber is: " + refFour.phoneNumber);
System.out.println("The address is: " + refFour.address);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The dateOfJoining is: " + refFour.dateOfJoining);
System.out.println("The managerName is: " + refFour.managerName);
System.out.println("The isPermanent is: " + refFour.isPermanent);
System.out.println("The isRemote is: " + refFour.isRemote);
System.out.println("The experienceYears is: " + refFour.experienceYears);
System.out.println("The highestQualification is: " + refFour.highestQualification);
System.out.println("The bloodGroup is: " + refFour.bloodGroup);
System.out.println("The maritalStatus is: " + refFour.maritalStatus);
System.out.println("The nationality is: " + refFour.nationality);
System.out.println("The employeeType is: " + refFour.employeeType);
System.out.println("The workShift is: " + refFour.workShift);


refFour.employeeId = 4;
refFour.firstName = "Sneha";
refFour.lastName = "Patil";
refFour.gender = "Female";
refFour.age = 26;
refFour.department = "Marketing";
refFour.designation = "Marketing Executive";
refFour.salary = 52000.00;
refFour.email = "sneha.patil@example.com";
refFour.phoneNumber = "9871234560";
refFour.address = "BTM Layout";
refFour.city = "Bengaluru";
refFour.state = "Karnataka";
refFour.country = "India";
refFour.dateOfJoining = "20-07-2022";
refFour.managerName = "Rohit Sharma";
refFour.isPermanent = true;
refFour.isRemote = false;
refFour.experienceYears = 2;
refFour.highestQualification = "MBA Marketing";
refFour.bloodGroup = "AB+";
refFour.maritalStatus = "Single";
refFour.nationality = "Indian";
refFour.employeeType = "Full Time";
refFour.workShift = "Day";


System.out.println("The employeeId is: " + refFour.employeeId);
System.out.println("The firstName is: " + refFour.firstName);
System.out.println("The lastName is: " + refFour.lastName);
System.out.println("The gender is: " + refFour.gender);
System.out.println("The age is: " + refFour.age);
System.out.println("The department is: " + refFour.department);
System.out.println("The designation is: " + refFour.designation);
System.out.println("The salary is: " + refFour.salary);
System.out.println("The email is: " + refFour.email);
System.out.println("The phoneNumber is: " + refFour.phoneNumber);
System.out.println("The address is: " + refFour.address);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The dateOfJoining is: " + refFour.dateOfJoining);
System.out.println("The managerName is: " + refFour.managerName);
System.out.println("The isPermanent is: " + refFour.isPermanent);
System.out.println("The isRemote is: " + refFour.isRemote);
System.out.println("The experienceYears is: " + refFour.experienceYears);
System.out.println("The highestQualification is: " + refFour.highestQualification);
System.out.println("The bloodGroup is: " + refFour.bloodGroup);
System.out.println("The maritalStatus is: " + refFour.maritalStatus);
System.out.println("The nationality is: " + refFour.nationality);
System.out.println("The employeeType is: " + refFour.employeeType);
System.out.println("The workShift is: " + refFour.workShift);
Employee refFive = new Employee();

System.out.println("The employeeId is: " + refFive.employeeId);
System.out.println("The firstName is: " + refFive.firstName);
System.out.println("The lastName is: " + refFive.lastName);
System.out.println("The gender is: " + refFive.gender);
System.out.println("The age is: " + refFive.age);
System.out.println("The department is: " + refFive.department);
System.out.println("The designation is: " + refFive.designation);
System.out.println("The salary is: " + refFive.salary);
System.out.println("The email is: " + refFive.email);
System.out.println("The phoneNumber is: " + refFive.phoneNumber);
System.out.println("The address is: " + refFive.address);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The dateOfJoining is: " + refFive.dateOfJoining);
System.out.println("The managerName is: " + refFive.managerName);
System.out.println("The isPermanent is: " + refFive.isPermanent);
System.out.println("The isRemote is: " + refFive.isRemote);
System.out.println("The experienceYears is: " + refFive.experienceYears);
System.out.println("The highestQualification is: " + refFive.highestQualification);
System.out.println("The bloodGroup is: " + refFive.bloodGroup);
System.out.println("The maritalStatus is: " + refFive.maritalStatus);
System.out.println("The nationality is: " + refFive.nationality);
System.out.println("The employeeType is: " + refFive.employeeType);
System.out.println("The workShift is: " + refFive.workShift);


refFive.employeeId = 5;
refFive.firstName = "Kiran";
refFive.lastName = "Shetty";
refFive.gender = "Male";
refFive.age = 32;
refFive.department = "Finance";
refFive.designation = "Accountant";
refFive.salary = 60000.00;
refFive.email = "kiran.shetty@example.com";
refFive.phoneNumber = "9812345678";
refFive.address = "Jayanagar";
refFive.city = "Bengaluru";
refFive.state = "Karnataka";
refFive.country = "India";
refFive.dateOfJoining = "05-09-2020";
refFive.managerName = "Meena Iyer";
refFive.isPermanent = true;
refFive.isRemote = false;
refFive.experienceYears = 7;
refFive.highestQualification = "M.Com";
refFive.bloodGroup = "O+";
refFive.maritalStatus = "Married";
refFive.nationality = "Indian";
refFive.employeeType = "Full Time";
refFive.workShift = "Day";


System.out.println("The employeeId is: " + refFive.employeeId);
System.out.println("The firstName is: " + refFive.firstName);
System.out.println("The lastName is: " + refFive.lastName);
System.out.println("The gender is: " + refFive.gender);
System.out.println("The age is: " + refFive.age);
System.out.println("The department is: " + refFive.department);
System.out.println("The designation is: " + refFive.designation);
System.out.println("The salary is: " + refFive.salary);
System.out.println("The email is: " + refFive.email);
System.out.println("The phoneNumber is: " + refFive.phoneNumber);
System.out.println("The address is: " + refFive.address);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The dateOfJoining is: " + refFive.dateOfJoining);
System.out.println("The managerName is: " + refFive.managerName);
System.out.println("The isPermanent is: " + refFive.isPermanent);
System.out.println("The isRemote is: " + refFive.isRemote);
System.out.println("The experienceYears is: " + refFive.experienceYears);
System.out.println("The highestQualification is: " + refFive.highestQualification);
System.out.println("The bloodGroup is: " + refFive.bloodGroup);
System.out.println("The maritalStatus is: " + refFive.maritalStatus);
System.out.println("The nationality is: " + refFive.nationality);
System.out.println("The employeeType is: " + refFive.employeeType);
System.out.println("The workShift is: " + refFive.workShift);
Employee refSix = new Employee();

System.out.println("The employeeId is: " + refSix.employeeId);
System.out.println("The firstName is: " + refSix.firstName);
System.out.println("The lastName is: " + refSix.lastName);
System.out.println("The gender is: " + refSix.gender);
System.out.println("The age is: " + refSix.age);
System.out.println("The department is: " + refSix.department);
System.out.println("The designation is: " + refSix.designation);
System.out.println("The salary is: " + refSix.salary);
System.out.println("The email is: " + refSix.email);
System.out.println("The phoneNumber is: " + refSix.phoneNumber);
System.out.println("The address is: " + refSix.address);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The dateOfJoining is: " + refSix.dateOfJoining);
System.out.println("The managerName is: " + refSix.managerName);
System.out.println("The isPermanent is: " + refSix.isPermanent);
System.out.println("The isRemote is: " + refSix.isRemote);
System.out.println("The experienceYears is: " + refSix.experienceYears);
System.out.println("The highestQualification is: " + refSix.highestQualification);
System.out.println("The bloodGroup is: " + refSix.bloodGroup);
System.out.println("The maritalStatus is: " + refSix.maritalStatus);
System.out.println("The nationality is: " + refSix.nationality);
System.out.println("The employeeType is: " + refSix.employeeType);
System.out.println("The workShift is: " + refSix.workShift);


refSix.employeeId = 6;
refSix.firstName = "Anjali";
refSix.lastName = "Verma";
refSix.gender = "Female";
refSix.age = 29;
refSix.department = "Customer Support";
refSix.designation = "Support Executive";
refSix.salary = 48000.00;
refSix.email = "anjali.verma@example.com";
refSix.phoneNumber = "9765432101";
refSix.address = "HSR Layout";
refSix.city = "Bengaluru";
refSix.state = "Karnataka";
refSix.country = "India";
refSix.dateOfJoining = "18-11-2021";
refSix.managerName = "Deepak Joshi";
refSix.isPermanent = true;
refSix.isRemote = true;
refSix.experienceYears = 5;
refSix.highestQualification = "BBA";
refSix.bloodGroup = "A+";
refSix.maritalStatus = "Single";
refSix.nationality = "Indian";
refSix.employeeType = "Full Time";
refSix.workShift = "Evening";


System.out.println("The employeeId is: " + refSix.employeeId);
System.out.println("The firstName is: " + refSix.firstName);
System.out.println("The lastName is: " + refSix.lastName);
System.out.println("The gender is: " + refSix.gender);
System.out.println("The age is: " + refSix.age);
System.out.println("The department is: " + refSix.department);
System.out.println("The designation is: " + refSix.designation);
System.out.println("The salary is: " + refSix.salary);
System.out.println("The email is: " + refSix.email);
System.out.println("The phoneNumber is: " + refSix.phoneNumber);
System.out.println("The address is: " + refSix.address);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The dateOfJoining is: " + refSix.dateOfJoining);
System.out.println("The managerName is: " + refSix.managerName);
System.out.println("The isPermanent is: " + refSix.isPermanent);
System.out.println("The isRemote is: " + refSix.isRemote);
System.out.println("The experienceYears is: " + refSix.experienceYears);
System.out.println("The highestQualification is: " + refSix.highestQualification);
System.out.println("The bloodGroup is: " + refSix.bloodGroup);
System.out.println("The maritalStatus is: " + refSix.maritalStatus);
System.out.println("The nationality is: " + refSix.nationality);
System.out.println("The employeeType is: " + refSix.employeeType);
System.out.println("The workShift is: " + refSix.workShift);
Employee refSeven = new Employee();

System.out.println("The employeeId is: " + refSeven.employeeId);
System.out.println("The firstName is: " + refSeven.firstName);
System.out.println("The lastName is: " + refSeven.lastName);
System.out.println("The gender is: " + refSeven.gender);
System.out.println("The age is: " + refSeven.age);
System.out.println("The department is: " + refSeven.department);
System.out.println("The designation is: " + refSeven.designation);
System.out.println("The salary is: " + refSeven.salary);
System.out.println("The email is: " + refSeven.email);
System.out.println("The phoneNumber is: " + refSeven.phoneNumber);
System.out.println("The address is: " + refSeven.address);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The dateOfJoining is: " + refSeven.dateOfJoining);
System.out.println("The managerName is: " + refSeven.managerName);
System.out.println("The isPermanent is: " + refSeven.isPermanent);
System.out.println("The isRemote is: " + refSeven.isRemote);
System.out.println("The experienceYears is: " + refSeven.experienceYears);
System.out.println("The highestQualification is: " + refSeven.highestQualification);
System.out.println("The bloodGroup is: " + refSeven.bloodGroup);
System.out.println("The maritalStatus is: " + refSeven.maritalStatus);
System.out.println("The nationality is: " + refSeven.nationality);
System.out.println("The employeeType is: " + refSeven.employeeType);
System.out.println("The workShift is: " + refSeven.workShift);


refSeven.employeeId = 7;
refSeven.firstName = "Vikram";
refSeven.lastName = "Kulkarni";
refSeven.gender = "Male";
refSeven.age = 35;
refSeven.department = "IT Support";
refSeven.designation = "System Administrator";
refSeven.salary = 70000.00;
refSeven.email = "vikram.kulkarni@example.com";
refSeven.phoneNumber = "9845012345";
refSeven.address = "Rajajinagar";
refSeven.city = "Bengaluru";
refSeven.state = "Karnataka";
refSeven.country = "India";
refSeven.dateOfJoining = "08-02-2019";
refSeven.managerName = "Mahesh Bhat";
refSeven.isPermanent = true;
refSeven.isRemote = false;
refSeven.experienceYears = 10;
refSeven.highestQualification = "B.Tech Computer Science";
refSeven.bloodGroup = "B+";
refSeven.maritalStatus = "Married";
refSeven.nationality = "Indian";
refSeven.employeeType = "Full Time";
refSeven.workShift = "Day";


System.out.println("The employeeId is: " + refSeven.employeeId);
System.out.println("The firstName is: " + refSeven.firstName);
System.out.println("The lastName is: " + refSeven.lastName);
System.out.println("The gender is: " + refSeven.gender);
System.out.println("The age is: " + refSeven.age);
System.out.println("The department is: " + refSeven.department);
System.out.println("The designation is: " + refSeven.designation);
System.out.println("The salary is: " + refSeven.salary);
System.out.println("The email is: " + refSeven.email);
System.out.println("The phoneNumber is: " + refSeven.phoneNumber);
System.out.println("The address is: " + refSeven.address);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The dateOfJoining is: " + refSeven.dateOfJoining);
System.out.println("The managerName is: " + refSeven.managerName);
System.out.println("The isPermanent is: " + refSeven.isPermanent);
System.out.println("The isRemote is: " + refSeven.isRemote);
System.out.println("The experienceYears is: " + refSeven.experienceYears);
System.out.println("The highestQualification is: " + refSeven.highestQualification);
System.out.println("The bloodGroup is: " + refSeven.bloodGroup);
System.out.println("The maritalStatus is: " + refSeven.maritalStatus);
System.out.println("The nationality is: " + refSeven.nationality);
System.out.println("The employeeType is: " + refSeven.employeeType);
System.out.println("The workShift is: " + refSeven.workShift);
Employee refEight = new Employee();

System.out.println("The employeeId is: " + refEight.employeeId);
System.out.println("The firstName is: " + refEight.firstName);
System.out.println("The lastName is: " + refEight.lastName);
System.out.println("The gender is: " + refEight.gender);
System.out.println("The age is: " + refEight.age);
System.out.println("The department is: " + refEight.department);
System.out.println("The designation is: " + refEight.designation);
System.out.println("The salary is: " + refEight.salary);
System.out.println("The email is: " + refEight.email);
System.out.println("The phoneNumber is: " + refEight.phoneNumber);
System.out.println("The address is: " + refEight.address);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The dateOfJoining is: " + refEight.dateOfJoining);
System.out.println("The managerName is: " + refEight.managerName);
System.out.println("The isPermanent is: " + refEight.isPermanent);
System.out.println("The isRemote is: " + refEight.isRemote);
System.out.println("The experienceYears is: " + refEight.experienceYears);
System.out.println("The highestQualification is: " + refEight.highestQualification);
System.out.println("The bloodGroup is: " + refEight.bloodGroup);
System.out.println("The maritalStatus is: " + refEight.maritalStatus);
System.out.println("The nationality is: " + refEight.nationality);
System.out.println("The employeeType is: " + refEight.employeeType);
System.out.println("The workShift is: " + refEight.workShift);


refEight.employeeId = 8;
refEight.firstName = "Pooja";
refEight.lastName = "Singh";
refEight.gender = "Female";
refEight.age = 31;
refEight.department = "Sales";
refEight.designation = "Sales Manager";
refEight.salary = 68000.00;
refEight.email = "pooja.singh@example.com";
refEight.phoneNumber = "9901122334";
refEight.address = "Koramangala";
refEight.city = "Bengaluru";
refEight.state = "Karnataka";
refEight.country = "India";
refEight.dateOfJoining = "22-05-2020";
refEight.managerName = "Rajat Malhotra";
refEight.isPermanent = true;
refEight.isRemote = false;
refEight.experienceYears = 8;
refEight.highestQualification = "MBA Sales";
refEight.bloodGroup = "A-";
refEight.maritalStatus = "Married";
refEight.nationality = "Indian";
refEight.employeeType = "Full Time";
refEight.workShift = "Day";


System.out.println("The employeeId is: " + refEight.employeeId);
System.out.println("The firstName is: " + refEight.firstName);
System.out.println("The lastName is: " + refEight.lastName);
System.out.println("The gender is: " + refEight.gender);
System.out.println("The age is: " + refEight.age);
System.out.println("The department is: " + refEight.department);
System.out.println("The designation is: " + refEight.designation);
System.out.println("The salary is: " + refEight.salary);
System.out.println("The email is: " + refEight.email);
System.out.println("The phoneNumber is: " + refEight.phoneNumber);
System.out.println("The address is: " + refEight.address);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The dateOfJoining is: " + refEight.dateOfJoining);
System.out.println("The managerName is: " + refEight.managerName);
System.out.println("The isPermanent is: " + refEight.isPermanent);
System.out.println("The isRemote is: " + refEight.isRemote);
System.out.println("The experienceYears is: " + refEight.experienceYears);
System.out.println("The highestQualification is: " + refEight.highestQualification);
System.out.println("The bloodGroup is: " + refEight.bloodGroup);
System.out.println("The maritalStatus is: " + refEight.maritalStatus);
System.out.println("The nationality is: " + refEight.nationality);
System.out.println("The employeeType is: " + refEight.employeeType);
System.out.println("The workShift is: " + refEight.workShift);
Employee refNine = new Employee();

System.out.println("The employeeId is: " + refNine.employeeId);
System.out.println("The firstName is: " + refNine.firstName);
System.out.println("The lastName is: " + refNine.lastName);
System.out.println("The gender is: " + refNine.gender);
System.out.println("The age is: " + refNine.age);
System.out.println("The department is: " + refNine.department);
System.out.println("The designation is: " + refNine.designation);
System.out.println("The salary is: " + refNine.salary);
System.out.println("The email is: " + refNine.email);
System.out.println("The phoneNumber is: " + refNine.phoneNumber);
System.out.println("The address is: " + refNine.address);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The dateOfJoining is: " + refNine.dateOfJoining);
System.out.println("The managerName is: " + refNine.managerName);
System.out.println("The isPermanent is: " + refNine.isPermanent);
System.out.println("The isRemote is: " + refNine.isRemote);
System.out.println("The experienceYears is: " + refNine.experienceYears);
System.out.println("The highestQualification is: " + refNine.highestQualification);
System.out.println("The bloodGroup is: " + refNine.bloodGroup);
System.out.println("The maritalStatus is: " + refNine.maritalStatus);
System.out.println("The nationality is: " + refNine.nationality);
System.out.println("The employeeType is: " + refNine.employeeType);
System.out.println("The workShift is: " + refNine.workShift);


refNine.employeeId = 9;
refNine.firstName = "Rohit";
refNine.lastName = "Agarwal";
refNine.gender = "Male";
refNine.age = 33;
refNine.department = "Operations";
refNine.designation = "Operations Manager";
refNine.salary = 75000.00;
refNine.email = "rohit.agarwal@example.com";
refNine.phoneNumber = "9898765432";
refNine.address = "Yelahanka";
refNine.city = "Bengaluru";
refNine.state = "Karnataka";
refNine.country = "India";
refNine.dateOfJoining = "14-04-2018";
refNine.managerName = "Sanjay Gupta";
refNine.isPermanent = true;
refNine.isRemote = false;
refNine.experienceYears = 9;
refNine.highestQualification = "MBA Operations";
refNine.bloodGroup = "O-";
refNine.maritalStatus = "Married";
refNine.nationality = "Indian";
refNine.employeeType = "Full Time";
refNine.workShift = "Day";


System.out.println("The employeeId is: " + refNine.employeeId);
System.out.println("The firstName is: " + refNine.firstName);
System.out.println("The lastName is: " + refNine.lastName);
System.out.println("The gender is: " + refNine.gender);
System.out.println("The age is: " + refNine.age);
System.out.println("The department is: " + refNine.department);
System.out.println("The designation is: " + refNine.designation);
System.out.println("The salary is: " + refNine.salary);
System.out.println("The email is: " + refNine.email);
System.out.println("The phoneNumber is: " + refNine.phoneNumber);
System.out.println("The address is: " + refNine.address);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The dateOfJoining is: " + refNine.dateOfJoining);
System.out.println("The managerName is: " + refNine.managerName);
System.out.println("The isPermanent is: " + refNine.isPermanent);
System.out.println("The isRemote is: " + refNine.isRemote);
System.out.println("The experienceYears is: " + refNine.experienceYears);
System.out.println("The highestQualification is: " + refNine.highestQualification);
System.out.println("The bloodGroup is: " + refNine.bloodGroup);
System.out.println("The maritalStatus is: " + refNine.maritalStatus);
System.out.println("The nationality is: " + refNine.nationality);
System.out.println("The employeeType is: " + refNine.employeeType);
System.out.println("The workShift is: " + refNine.workShift);
Employee refTen = new Employee();

System.out.println("The employeeId is: " + refTen.employeeId);
System.out.println("The firstName is: " + refTen.firstName);
System.out.println("The lastName is: " + refTen.lastName);
System.out.println("The gender is: " + refTen.gender);
System.out.println("The age is: " + refTen.age);
System.out.println("The department is: " + refTen.department);
System.out.println("The designation is: " + refTen.designation);
System.out.println("The salary is: " + refTen.salary);
System.out.println("The email is: " + refTen.email);
System.out.println("The phoneNumber is: " + refTen.phoneNumber);
System.out.println("The address is: " + refTen.address);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The dateOfJoining is: " + refTen.dateOfJoining);
System.out.println("The managerName is: " + refTen.managerName);
System.out.println("The isPermanent is: " + refTen.isPermanent);
System.out.println("The isRemote is: " + refTen.isRemote);
System.out.println("The experienceYears is: " + refTen.experienceYears);
System.out.println("The highestQualification is: " + refTen.highestQualification);
System.out.println("The bloodGroup is: " + refTen.bloodGroup);
System.out.println("The maritalStatus is: " + refTen.maritalStatus);
System.out.println("The nationality is: " + refTen.nationality);
System.out.println("The employeeType is: " + refTen.employeeType);
System.out.println("The workShift is: " + refTen.workShift);


refTen.employeeId = 10;
refTen.firstName = "Neha";
refTen.lastName = "Gupta";
refTen.gender = "Female";
refTen.age = 28;
refTen.department = "Design";
refTen.designation = "UI Designer";
refTen.salary = 62000.00;
refTen.email = "neha.gupta@example.com";
refTen.phoneNumber = "9874501236";
refTen.address = "Malleshwaram";
refTen.city = "Bengaluru";
refTen.state = "Karnataka";
refTen.country = "India";
refTen.dateOfJoining = "11-08-2021";
refTen.managerName = "Rahul Mehta";
refTen.isPermanent = true;
refTen.isRemote = true;
refTen.experienceYears = 4;
refTen.highestQualification = "B.Des";
refTen.bloodGroup = "B-";
refTen.maritalStatus = "Single";
refTen.nationality = "Indian";
refTen.employeeType = "Full Time";
refTen.workShift = "Day";


System.out.println("The employeeId is: " + refTen.employeeId);
System.out.println("The firstName is: " + refTen.firstName);
System.out.println("The lastName is: " + refTen.lastName);
System.out.println("The gender is: " + refTen.gender);
System.out.println("The age is: " + refTen.age);
System.out.println("The department is: " + refTen.department);
System.out.println("The designation is: " + refTen.designation);
System.out.println("The salary is: " + refTen.salary);
System.out.println("The email is: " + refTen.email);
System.out.println("The phoneNumber is: " + refTen.phoneNumber);
System.out.println("The address is: " + refTen.address);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The dateOfJoining is: " + refTen.dateOfJoining);
System.out.println("The managerName is: " + refTen.managerName);
System.out.println("The isPermanent is: " + refTen.isPermanent);
System.out.println("The isRemote is: " + refTen.isRemote);
System.out.println("The experienceYears is: " + refTen.experienceYears);
System.out.println("The highestQualification is: " + refTen.highestQualification);
System.out.println("The bloodGroup is: " + refTen.bloodGroup);
System.out.println("The maritalStatus is: " + refTen.maritalStatus);
System.out.println("The nationality is: " + refTen.nationality);
System.out.println("The employeeType is: " + refTen.employeeType);
System.out.println("The workShift is: " + refTen.workShift);
Employee refEleven = new Employee();

System.out.println("The employeeId is: " + refEleven.employeeId);
System.out.println("The firstName is: " + refEleven.firstName);
System.out.println("The lastName is: " + refEleven.lastName);
System.out.println("The gender is: " + refEleven.gender);
System.out.println("The age is: " + refEleven.age);
System.out.println("The department is: " + refEleven.department);
System.out.println("The designation is: " + refEleven.designation);
System.out.println("The salary is: " + refEleven.salary);
System.out.println("The email is: " + refEleven.email);
System.out.println("The phoneNumber is: " + refEleven.phoneNumber);
System.out.println("The address is: " + refEleven.address);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The dateOfJoining is: " + refEleven.dateOfJoining);
System.out.println("The managerName is: " + refEleven.managerName);
System.out.println("The isPermanent is: " + refEleven.isPermanent);
System.out.println("The isRemote is: " + refEleven.isRemote);
System.out.println("The experienceYears is: " + refEleven.experienceYears);
System.out.println("The highestQualification is: " + refEleven.highestQualification);
System.out.println("The bloodGroup is: " + refEleven.bloodGroup);
System.out.println("The maritalStatus is: " + refEleven.maritalStatus);
System.out.println("The nationality is: " + refEleven.nationality);
System.out.println("The employeeType is: " + refEleven.employeeType);
System.out.println("The workShift is: " + refEleven.workShift);


refEleven.employeeId = 11;
refEleven.firstName = "Amit";
refEleven.lastName = "Das";
refEleven.gender = "Male";
refEleven.age = 34;
refEleven.department = "Logistics";
refEleven.designation = "Logistics Manager";
refEleven.salary = 67000.00;
refEleven.email = "amit.das@example.com";
refEleven.phoneNumber = "9812345670";
refEleven.address = "Electronic City";
refEleven.city = "Bengaluru";
refEleven.state = "Karnataka";
refEleven.country = "India";
refEleven.dateOfJoining = "17-03-2019";
refEleven.managerName = "Ramesh Nair";
refEleven.isPermanent = true;
refEleven.isRemote = false;
refEleven.experienceYears = 8;
refEleven.highestQualification = "MBA Logistics";
refEleven.bloodGroup = "A+";
refEleven.maritalStatus = "Married";
refEleven.nationality = "Indian";
refEleven.employeeType = "Full Time";
refEleven.workShift = "Day";


System.out.println("The employeeId is: " + refEleven.employeeId);
System.out.println("The firstName is: " + refEleven.firstName);
System.out.println("The lastName is: " + refEleven.lastName);
System.out.println("The gender is: " + refEleven.gender);
System.out.println("The age is: " + refEleven.age);
System.out.println("The department is: " + refEleven.department);
System.out.println("The designation is: " + refEleven.designation);
System.out.println("The salary is: " + refEleven.salary);
System.out.println("The email is: " + refEleven.email);
System.out.println("The phoneNumber is: " + refEleven.phoneNumber);
System.out.println("The address is: " + refEleven.address);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The dateOfJoining is: " + refEleven.dateOfJoining);
System.out.println("The managerName is: " + refEleven.managerName);
System.out.println("The isPermanent is: " + refEleven.isPermanent);
System.out.println("The isRemote is: " + refEleven.isRemote);
System.out.println("The experienceYears is: " + refEleven.experienceYears);
System.out.println("The highestQualification is: " + refEleven.highestQualification);
System.out.println("The bloodGroup is: " + refEleven.bloodGroup);
System.out.println("The maritalStatus is: " + refEleven.maritalStatus);
System.out.println("The nationality is: " + refEleven.nationality);
System.out.println("The employeeType is: " + refEleven.employeeType);
System.out.println("The workShift is: " + refEleven.workShift);
Employee refTwelve = new Employee();

System.out.println("The employeeId is: " + refTwelve.employeeId);
System.out.println("The firstName is: " + refTwelve.firstName);
System.out.println("The lastName is: " + refTwelve.lastName);
System.out.println("The gender is: " + refTwelve.gender);
System.out.println("The age is: " + refTwelve.age);
System.out.println("The department is: " + refTwelve.department);
System.out.println("The designation is: " + refTwelve.designation);
System.out.println("The salary is: " + refTwelve.salary);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The phoneNumber is: " + refTwelve.phoneNumber);
System.out.println("The address is: " + refTwelve.address);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The dateOfJoining is: " + refTwelve.dateOfJoining);
System.out.println("The managerName is: " + refTwelve.managerName);
System.out.println("The isPermanent is: " + refTwelve.isPermanent);
System.out.println("The isRemote is: " + refTwelve.isRemote);
System.out.println("The experienceYears is: " + refTwelve.experienceYears);
System.out.println("The highestQualification is: " + refTwelve.highestQualification);
System.out.println("The bloodGroup is: " + refTwelve.bloodGroup);
System.out.println("The maritalStatus is: " + refTwelve.maritalStatus);
System.out.println("The nationality is: " + refTwelve.nationality);
System.out.println("The employeeType is: " + refTwelve.employeeType);
System.out.println("The workShift is: " + refTwelve.workShift);


refTwelve.employeeId = 12;
refTwelve.firstName = "Deepika";
refTwelve.lastName = "Rao";
refTwelve.gender = "Female";
refTwelve.age = 29;
refTwelve.department = "Content";
refTwelve.designation = "Content Writer";
refTwelve.salary = 50000.00;
refTwelve.email = "deepika.rao@example.com";
refTwelve.phoneNumber = "9890011223";
refTwelve.address = "Banashankari";
refTwelve.city = "Bengaluru";
refTwelve.state = "Karnataka";
refTwelve.country = "India";
refTwelve.dateOfJoining = "06-06-2022";
refTwelve.managerName = "Anil Kumar";
refTwelve.isPermanent = true;
refTwelve.isRemote = true;
refTwelve.experienceYears = 4;
refTwelve.highestQualification = "MA English";
refTwelve.bloodGroup = "AB+";
refTwelve.maritalStatus = "Single";
refTwelve.nationality = "Indian";
refTwelve.employeeType = "Full Time";
refTwelve.workShift = "Day";


System.out.println("The employeeId is: " + refTwelve.employeeId);
System.out.println("The firstName is: " + refTwelve.firstName);
System.out.println("The lastName is: " + refTwelve.lastName);
System.out.println("The gender is: " + refTwelve.gender);
System.out.println("The age is: " + refTwelve.age);
System.out.println("The department is: " + refTwelve.department);
System.out.println("The designation is: " + refTwelve.designation);
System.out.println("The salary is: " + refTwelve.salary);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The phoneNumber is: " + refTwelve.phoneNumber);
System.out.println("The address is: " + refTwelve.address);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The dateOfJoining is: " + refTwelve.dateOfJoining);
System.out.println("The managerName is: " + refTwelve.managerName);
System.out.println("The isPermanent is: " + refTwelve.isPermanent);
System.out.println("The isRemote is: " + refTwelve.isRemote);
System.out.println("The experienceYears is: " + refTwelve.experienceYears);
System.out.println("The highestQualification is: " + refTwelve.highestQualification);
System.out.println("The bloodGroup is: " + refTwelve.bloodGroup);
System.out.println("The maritalStatus is: " + refTwelve.maritalStatus);
System.out.println("The nationality is: " + refTwelve.nationality);
System.out.println("The employeeType is: " + refTwelve.employeeType);
System.out.println("The workShift is: " + refTwelve.workShift);
Employee refThirteen = new Employee();

System.out.println("The employeeId is: " + refThirteen.employeeId);
System.out.println("The firstName is: " + refThirteen.firstName);
System.out.println("The lastName is: " + refThirteen.lastName);
System.out.println("The gender is: " + refThirteen.gender);
System.out.println("The age is: " + refThirteen.age);
System.out.println("The department is: " + refThirteen.department);
System.out.println("The designation is: " + refThirteen.designation);
System.out.println("The salary is: " + refThirteen.salary);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The phoneNumber is: " + refThirteen.phoneNumber);
System.out.println("The address is: " + refThirteen.address);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The dateOfJoining is: " + refThirteen.dateOfJoining);
System.out.println("The managerName is: " + refThirteen.managerName);
System.out.println("The isPermanent is: " + refThirteen.isPermanent);
System.out.println("The isRemote is: " + refThirteen.isRemote);
System.out.println("The experienceYears is: " + refThirteen.experienceYears);
System.out.println("The highestQualification is: " + refThirteen.highestQualification);
System.out.println("The bloodGroup is: " + refThirteen.bloodGroup);
System.out.println("The maritalStatus is: " + refThirteen.maritalStatus);
System.out.println("The nationality is: " + refThirteen.nationality);
System.out.println("The employeeType is: " + refThirteen.employeeType);
System.out.println("The workShift is: " + refThirteen.workShift);


refThirteen.employeeId = 13;
refThirteen.firstName = "Sandeep";
refThirteen.lastName = "Joshi";
refThirteen.gender = "Male";
refThirteen.age = 36;
refThirteen.department = "Administration";
refThirteen.designation = "Admin Officer";
refThirteen.salary = 56000.00;
refThirteen.email = "sandeep.joshi@example.com";
refThirteen.phoneNumber = "9887766554";
refThirteen.address = "Hebbal";
refThirteen.city = "Bengaluru";
refThirteen.state = "Karnataka";
refThirteen.country = "India";
refThirteen.dateOfJoining = "12-10-2017";
refThirteen.managerName = "Ravi Shankar";
refThirteen.isPermanent = true;
refThirteen.isRemote = false;
refThirteen.experienceYears = 11;
refThirteen.highestQualification = "MBA Administration";
refThirteen.bloodGroup = "O+";
refThirteen.maritalStatus = "Married";
refThirteen.nationality = "Indian";
refThirteen.employeeType = "Full Time";
refThirteen.workShift = "Day";


System.out.println("The employeeId is: " + refThirteen.employeeId);
System.out.println("The firstName is: " + refThirteen.firstName);
System.out.println("The lastName is: " + refThirteen.lastName);
System.out.println("The gender is: " + refThirteen.gender);
System.out.println("The age is: " + refThirteen.age);
System.out.println("The department is: " + refThirteen.department);
System.out.println("The designation is: " + refThirteen.designation);
System.out.println("The salary is: " + refThirteen.salary);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The phoneNumber is: " + refThirteen.phoneNumber);
System.out.println("The address is: " + refThirteen.address);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The dateOfJoining is: " + refThirteen.dateOfJoining);
System.out.println("The managerName is: " + refThirteen.managerName);
System.out.println("The isPermanent is: " + refThirteen.isPermanent);
System.out.println("The isRemote is: " + refThirteen.isRemote);
System.out.println("The experienceYears is: " + refThirteen.experienceYears);
System.out.println("The highestQualification is: " + refThirteen.highestQualification);
System.out.println("The bloodGroup is: " + refThirteen.bloodGroup);
System.out.println("The maritalStatus is: " + refThirteen.maritalStatus);
System.out.println("The nationality is: " + refThirteen.nationality);
System.out.println("The employeeType is: " + refThirteen.employeeType);
System.out.println("The workShift is: " + refThirteen.workShift);
Employee refFourteen = new Employee();

System.out.println("The employeeId is: " + refFourteen.employeeId);
System.out.println("The firstName is: " + refFourteen.firstName);
System.out.println("The lastName is: " + refFourteen.lastName);
System.out.println("The gender is: " + refFourteen.gender);
System.out.println("The age is: " + refFourteen.age);
System.out.println("The department is: " + refFourteen.department);
System.out.println("The designation is: " + refFourteen.designation);
System.out.println("The salary is: " + refFourteen.salary);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The phoneNumber is: " + refFourteen.phoneNumber);
System.out.println("The address is: " + refFourteen.address);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The dateOfJoining is: " + refFourteen.dateOfJoining);
System.out.println("The managerName is: " + refFourteen.managerName);
System.out.println("The isPermanent is: " + refFourteen.isPermanent);
System.out.println("The isRemote is: " + refFourteen.isRemote);
System.out.println("The experienceYears is: " + refFourteen.experienceYears);
System.out.println("The highestQualification is: " + refFourteen.highestQualification);
System.out.println("The bloodGroup is: " + refFourteen.bloodGroup);
System.out.println("The maritalStatus is: " + refFourteen.maritalStatus);
System.out.println("The nationality is: " + refFourteen.nationality);
System.out.println("The employeeType is: " + refFourteen.employeeType);
System.out.println("The workShift is: " + refFourteen.workShift);


refFourteen.employeeId = 14;
refFourteen.firstName = "Lakshmi";
refFourteen.lastName = "Iyer";
refFourteen.gender = "Female";
refFourteen.age = 37;
refFourteen.department = "Legal";
refFourteen.designation = "Legal Advisor";
refFourteen.salary = 82000.00;
refFourteen.email = "lakshmi.iyer@example.com";
refFourteen.phoneNumber = "9845671234";
refFourteen.address = "Sadashivanagar";
refFourteen.city = "Bengaluru";
refFourteen.state = "Karnataka";
refFourteen.country = "India";
refFourteen.dateOfJoining = "19-09-2016";
refFourteen.managerName = "Venkatesh Rao";
refFourteen.isPermanent = true;
refFourteen.isRemote = false;
refFourteen.experienceYears = 12;
refFourteen.highestQualification = "LLB";
refFourteen.bloodGroup = "B+";
refFourteen.maritalStatus = "Married";
refFourteen.nationality = "Indian";
refFourteen.employeeType = "Full Time";
refFourteen.workShift = "Day";


System.out.println("The employeeId is: " + refFourteen.employeeId);
System.out.println("The firstName is: " + refFourteen.firstName);
System.out.println("The lastName is: " + refFourteen.lastName);
System.out.println("The gender is: " + refFourteen.gender);
System.out.println("The age is: " + refFourteen.age);
System.out.println("The department is: " + refFourteen.department);
System.out.println("The designation is: " + refFourteen.designation);
System.out.println("The salary is: " + refFourteen.salary);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The phoneNumber is: " + refFourteen.phoneNumber);
System.out.println("The address is: " + refFourteen.address);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The dateOfJoining is: " + refFourteen.dateOfJoining);
System.out.println("The managerName is: " + refFourteen.managerName);
System.out.println("The isPermanent is: " + refFourteen.isPermanent);
System.out.println("The isRemote is: " + refFourteen.isRemote);
System.out.println("The experienceYears is: " + refFourteen.experienceYears);
System.out.println("The highestQualification is: " + refFourteen.highestQualification);
System.out.println("The bloodGroup is: " + refFourteen.bloodGroup);
System.out.println("The maritalStatus is: " + refFourteen.maritalStatus);
System.out.println("The nationality is: " + refFourteen.nationality);
System.out.println("The employeeType is: " + refFourteen.employeeType);
System.out.println("The workShift is: " + refFourteen.workShift);
Employee refFifteen = new Employee();

System.out.println("The employeeId is: " + refFifteen.employeeId);
System.out.println("The firstName is: " + refFifteen.firstName);
System.out.println("The lastName is: " + refFifteen.lastName);
System.out.println("The gender is: " + refFifteen.gender);
System.out.println("The age is: " + refFifteen.age);
System.out.println("The department is: " + refFifteen.department);
System.out.println("The designation is: " + refFifteen.designation);
System.out.println("The salary is: " + refFifteen.salary);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The phoneNumber is: " + refFifteen.phoneNumber);
System.out.println("The address is: " + refFifteen.address);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The dateOfJoining is: " + refFifteen.dateOfJoining);
System.out.println("The managerName is: " + refFifteen.managerName);
System.out.println("The isPermanent is: " + refFifteen.isPermanent);
System.out.println("The isRemote is: " + refFifteen.isRemote);
System.out.println("The experienceYears is: " + refFifteen.experienceYears);
System.out.println("The highestQualification is: " + refFifteen.highestQualification);
System.out.println("The bloodGroup is: " + refFifteen.bloodGroup);
System.out.println("The maritalStatus is: " + refFifteen.maritalStatus);
System.out.println("The nationality is: " + refFifteen.nationality);
System.out.println("The employeeType is: " + refFifteen.employeeType);
System.out.println("The workShift is: " + refFifteen.workShift);


refFifteen.employeeId = 15;
refFifteen.firstName = "Manoj";
refFifteen.lastName = "Kumar";
refFifteen.gender = "Male";
refFifteen.age = 40;
refFifteen.department = "Security";
refFifteen.designation = "Security Supervisor";
refFifteen.salary = 42000.00;
refFifteen.email = "manoj.kumar@example.com";
refFifteen.phoneNumber = "9734567812";
refFifteen.address = "Peenya";
refFifteen.city = "Bengaluru";
refFifteen.state = "Karnataka";
refFifteen.country = "India";
refFifteen.dateOfJoining = "03-01-2015";
refFifteen.managerName = "Prakash Shetty";
refFifteen.isPermanent = true;
refFifteen.isRemote = false;
refFifteen.experienceYears = 15;
refFifteen.highestQualification = "PUC";
refFifteen.bloodGroup = "O+";
refFifteen.maritalStatus = "Married";
refFifteen.nationality = "Indian";
refFifteen.employeeType = "Full Time";
refFifteen.workShift = "Night";


System.out.println("The employeeId is: " + refFifteen.employeeId);
System.out.println("The firstName is: " + refFifteen.firstName);
System.out.println("The lastName is: " + refFifteen.lastName);
System.out.println("The gender is: " + refFifteen.gender);
System.out.println("The age is: " + refFifteen.age);
System.out.println("The department is: " + refFifteen.department);
System.out.println("The designation is: " + refFifteen.designation);
System.out.println("The salary is: " + refFifteen.salary);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The phoneNumber is: " + refFifteen.phoneNumber);
System.out.println("The address is: " + refFifteen.address);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The dateOfJoining is: " + refFifteen.dateOfJoining);
System.out.println("The managerName is: " + refFifteen.managerName);
System.out.println("The isPermanent is: " + refFifteen.isPermanent);
System.out.println("The isRemote is: " + refFifteen.isRemote);
System.out.println("The experienceYears is: " + refFifteen.experienceYears);
System.out.println("The highestQualification is: " + refFifteen.highestQualification);
System.out.println("The bloodGroup is: " + refFifteen.bloodGroup);
System.out.println("The maritalStatus is: " + refFifteen.maritalStatus);
System.out.println("The nationality is: " + refFifteen.nationality);
System.out.println("The employeeType is: " + refFifteen.employeeType);
System.out.println("The workShift is: " + refFifteen.workShift);
Employee refSixteen = new Employee();

System.out.println("The employeeId is: " + refSixteen.employeeId);
System.out.println("The firstName is: " + refSixteen.firstName);
System.out.println("The lastName is: " + refSixteen.lastName);
System.out.println("The gender is: " + refSixteen.gender);
System.out.println("The age is: " + refSixteen.age);
System.out.println("The department is: " + refSixteen.department);
System.out.println("The designation is: " + refSixteen.designation);
System.out.println("The salary is: " + refSixteen.salary);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The phoneNumber is: " + refSixteen.phoneNumber);
System.out.println("The address is: " + refSixteen.address);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The dateOfJoining is: " + refSixteen.dateOfJoining);
System.out.println("The managerName is: " + refSixteen.managerName);
System.out.println("The isPermanent is: " + refSixteen.isPermanent);
System.out.println("The isRemote is: " + refSixteen.isRemote);
System.out.println("The experienceYears is: " + refSixteen.experienceYears);
System.out.println("The highestQualification is: " + refSixteen.highestQualification);
System.out.println("The bloodGroup is: " + refSixteen.bloodGroup);
System.out.println("The maritalStatus is: " + refSixteen.maritalStatus);
System.out.println("The nationality is: " + refSixteen.nationality);
System.out.println("The employeeType is: " + refSixteen.employeeType);
System.out.println("The workShift is: " + refSixteen.workShift);


refSixteen.employeeId = 16;
refSixteen.firstName = "Kavya";
refSixteen.lastName = "Nair";
refSixteen.gender = "Female";
refSixteen.age = 27;
refSixteen.department = "Research";
refSixteen.designation = "Research Analyst";
refSixteen.salary = 61000.00;
refSixteen.email = "kavya.nair@example.com";
refSixteen.phoneNumber = "9823456710";
refSixteen.address = "Marathahalli";
refSixteen.city = "Bengaluru";
refSixteen.state = "Karnataka";
refSixteen.country = "India";
refSixteen.dateOfJoining = "14-02-2023";
refSixteen.managerName = "Arvind Menon";
refSixteen.isPermanent = true;
refSixteen.isRemote = true;
refSixteen.experienceYears = 3;
refSixteen.highestQualification = "M.Sc Data Science";
refSixteen.bloodGroup = "A+";
refSixteen.maritalStatus = "Single";
refSixteen.nationality = "Indian";
refSixteen.employeeType = "Full Time";
refSixteen.workShift = "Day";


System.out.println("The employeeId is: " + refSixteen.employeeId);
System.out.println("The firstName is: " + refSixteen.firstName);
System.out.println("The lastName is: " + refSixteen.lastName);
System.out.println("The gender is: " + refSixteen.gender);
System.out.println("The age is: " + refSixteen.age);
System.out.println("The department is: " + refSixteen.department);
System.out.println("The designation is: " + refSixteen.designation);
System.out.println("The salary is: " + refSixteen.salary);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The phoneNumber is: " + refSixteen.phoneNumber);
System.out.println("The address is: " + refSixteen.address);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The dateOfJoining is: " + refSixteen.dateOfJoining);
System.out.println("The managerName is: " + refSixteen.managerName);
System.out.println("The isPermanent is: " + refSixteen.isPermanent);
System.out.println("The isRemote is: " + refSixteen.isRemote);
System.out.println("The experienceYears is: " + refSixteen.experienceYears);
System.out.println("The highestQualification is: " + refSixteen.highestQualification);
System.out.println("The bloodGroup is: " + refSixteen.bloodGroup);
System.out.println("The maritalStatus is: " + refSixteen.maritalStatus);
System.out.println("The nationality is: " + refSixteen.nationality);
System.out.println("The employeeType is: " + refSixteen.employeeType);
System.out.println("The workShift is: " + refSixteen.workShift);
Employee refSeventeen = new Employee();

System.out.println("The employeeId is: " + refSeventeen.employeeId);
System.out.println("The firstName is: " + refSeventeen.firstName);
System.out.println("The lastName is: " + refSeventeen.lastName);
System.out.println("The gender is: " + refSeventeen.gender);
System.out.println("The age is: " + refSeventeen.age);
System.out.println("The department is: " + refSeventeen.department);
System.out.println("The designation is: " + refSeventeen.designation);
System.out.println("The salary is: " + refSeventeen.salary);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The phoneNumber is: " + refSeventeen.phoneNumber);
System.out.println("The address is: " + refSeventeen.address);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The dateOfJoining is: " + refSeventeen.dateOfJoining);
System.out.println("The managerName is: " + refSeventeen.managerName);
System.out.println("The isPermanent is: " + refSeventeen.isPermanent);
System.out.println("The isRemote is: " + refSeventeen.isRemote);
System.out.println("The experienceYears is: " + refSeventeen.experienceYears);
System.out.println("The highestQualification is: " + refSeventeen.highestQualification);
System.out.println("The bloodGroup is: " + refSeventeen.bloodGroup);
System.out.println("The maritalStatus is: " + refSeventeen.maritalStatus);
System.out.println("The nationality is: " + refSeventeen.nationality);
System.out.println("The employeeType is: " + refSeventeen.employeeType);
System.out.println("The workShift is: " + refSeventeen.workShift);


refSeventeen.employeeId = 17;
refSeventeen.firstName = "Harish";
refSeventeen.lastName = "Gowda";
refSeventeen.gender = "Male";
refSeventeen.age = 38;
refSeventeen.department = "Production";
refSeventeen.designation = "Production Supervisor";
refSeventeen.salary = 64000.00;
refSeventeen.email = "harish.gowda@example.com";
refSeventeen.phoneNumber = "9845123678";
refSeventeen.address = "Tumkur Road";
refSeventeen.city = "Bengaluru";
refSeventeen.state = "Karnataka";
refSeventeen.country = "India";
refSeventeen.dateOfJoining = "25-05-2018";
refSeventeen.managerName = "Nagaraj Hegde";
refSeventeen.isPermanent = true;
refSeventeen.isRemote = false;
refSeventeen.experienceYears = 10;
refSeventeen.highestQualification = "Diploma Mechanical";
refSeventeen.bloodGroup = "B+";
refSeventeen.maritalStatus = "Married";
refSeventeen.nationality = "Indian";
refSeventeen.employeeType = "Full Time";
refSeventeen.workShift = "Morning";


System.out.println("The employeeId is: " + refSeventeen.employeeId);
System.out.println("The firstName is: " + refSeventeen.firstName);
System.out.println("The lastName is: " + refSeventeen.lastName);
System.out.println("The gender is: " + refSeventeen.gender);
System.out.println("The age is: " + refSeventeen.age);
System.out.println("The department is: " + refSeventeen.department);
System.out.println("The designation is: " + refSeventeen.designation);
System.out.println("The salary is: " + refSeventeen.salary);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The phoneNumber is: " + refSeventeen.phoneNumber);
System.out.println("The address is: " + refSeventeen.address);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The dateOfJoining is: " + refSeventeen.dateOfJoining);
System.out.println("The managerName is: " + refSeventeen.managerName);
System.out.println("The isPermanent is: " + refSeventeen.isPermanent);
System.out.println("The isRemote is: " + refSeventeen.isRemote);
System.out.println("The experienceYears is: " + refSeventeen.experienceYears);
System.out.println("The highestQualification is: " + refSeventeen.highestQualification);
System.out.println("The bloodGroup is: " + refSeventeen.bloodGroup);
System.out.println("The maritalStatus is: " + refSeventeen.maritalStatus);
System.out.println("The nationality is: " + refSeventeen.nationality);
System.out.println("The employeeType is: " + refSeventeen.employeeType);
System.out.println("The workShift is: " + refSeventeen.workShift);
Employee refEighteen = new Employee();

System.out.println("The employeeId is: " + refEighteen.employeeId);
System.out.println("The firstName is: " + refEighteen.firstName);
System.out.println("The lastName is: " + refEighteen.lastName);
System.out.println("The gender is: " + refEighteen.gender);
System.out.println("The age is: " + refEighteen.age);
System.out.println("The department is: " + refEighteen.department);
System.out.println("The designation is: " + refEighteen.designation);
System.out.println("The salary is: " + refEighteen.salary);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The phoneNumber is: " + refEighteen.phoneNumber);
System.out.println("The address is: " + refEighteen.address);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The dateOfJoining is: " + refEighteen.dateOfJoining);
System.out.println("The managerName is: " + refEighteen.managerName);
System.out.println("The isPermanent is: " + refEighteen.isPermanent);
System.out.println("The isRemote is: " + refEighteen.isRemote);
System.out.println("The experienceYears is: " + refEighteen.experienceYears);
System.out.println("The highestQualification is: " + refEighteen.highestQualification);
System.out.println("The bloodGroup is: " + refEighteen.bloodGroup);
System.out.println("The maritalStatus is: " + refEighteen.maritalStatus);
System.out.println("The nationality is: " + refEighteen.nationality);
System.out.println("The employeeType is: " + refEighteen.employeeType);
System.out.println("The workShift is: " + refEighteen.workShift);


refEighteen.employeeId = 18;
refEighteen.firstName = "Meera";
refEighteen.lastName = "Krishnan";
refEighteen.gender = "Female";
refEighteen.age = 33;
refEighteen.department = "Training";
refEighteen.designation = "Training Coordinator";
refEighteen.salary = 59000.00;
refEighteen.email = "meera.krishnan@example.com";
refEighteen.phoneNumber = "9876123450";
refEighteen.address = "Basavanagudi";
refEighteen.city = "Bengaluru";
refEighteen.state = "Karnataka";
refEighteen.country = "India";
refEighteen.dateOfJoining = "30-08-2019";
refEighteen.managerName = "Shankar Iyer";
refEighteen.isPermanent = true;
refEighteen.isRemote = true;
refEighteen.experienceYears = 7;
refEighteen.highestQualification = "MBA HR";
refEighteen.bloodGroup = "A+";
refEighteen.maritalStatus = "Married";
refEighteen.nationality = "Indian";
refEighteen.employeeType = "Full Time";
refEighteen.workShift = "Day";


System.out.println("The employeeId is: " + refEighteen.employeeId);
System.out.println("The firstName is: " + refEighteen.firstName);
System.out.println("The lastName is: " + refEighteen.lastName);
System.out.println("The gender is: " + refEighteen.gender);
System.out.println("The age is: " + refEighteen.age);
System.out.println("The department is: " + refEighteen.department);
System.out.println("The designation is: " + refEighteen.designation);
System.out.println("The salary is: " + refEighteen.salary);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The phoneNumber is: " + refEighteen.phoneNumber);
System.out.println("The address is: " + refEighteen.address);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The dateOfJoining is: " + refEighteen.dateOfJoining);
System.out.println("The managerName is: " + refEighteen.managerName);
System.out.println("The isPermanent is: " + refEighteen.isPermanent);
System.out.println("The isRemote is: " + refEighteen.isRemote);
System.out.println("The experienceYears is: " + refEighteen.experienceYears);
System.out.println("The highestQualification is: " + refEighteen.highestQualification);
System.out.println("The bloodGroup is: " + refEighteen.bloodGroup);
System.out.println("The maritalStatus is: " + refEighteen.maritalStatus);
System.out.println("The nationality is: " + refEighteen.nationality);
System.out.println("The employeeType is: " + refEighteen.employeeType);
System.out.println("The workShift is: " + refEighteen.workShift);
Employee refNineteen = new Employee();

System.out.println("The employeeId is: " + refNineteen.employeeId);
System.out.println("The firstName is: " + refNineteen.firstName);
System.out.println("The lastName is: " + refNineteen.lastName);
System.out.println("The gender is: " + refNineteen.gender);
System.out.println("The age is: " + refNineteen.age);
System.out.println("The department is: " + refNineteen.department);
System.out.println("The designation is: " + refNineteen.designation);
System.out.println("The salary is: " + refNineteen.salary);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The phoneNumber is: " + refNineteen.phoneNumber);
System.out.println("The address is: " + refNineteen.address);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The dateOfJoining is: " + refNineteen.dateOfJoining);
System.out.println("The managerName is: " + refNineteen.managerName);
System.out.println("The isPermanent is: " + refNineteen.isPermanent);
System.out.println("The isRemote is: " + refNineteen.isRemote);
System.out.println("The experienceYears is: " + refNineteen.experienceYears);
System.out.println("The highestQualification is: " + refNineteen.highestQualification);
System.out.println("The bloodGroup is: " + refNineteen.bloodGroup);
System.out.println("The maritalStatus is: " + refNineteen.maritalStatus);
System.out.println("The nationality is: " + refNineteen.nationality);
System.out.println("The employeeType is: " + refNineteen.employeeType);
System.out.println("The workShift is: " + refNineteen.workShift);


refNineteen.employeeId = 19;
refNineteen.firstName = "Rajesh";
refNineteen.lastName = "Bhat";
refNineteen.gender = "Male";
refNineteen.age = 41;
refNineteen.department = "Maintenance";
refNineteen.designation = "Maintenance Engineer";
refNineteen.salary = 67000.00;
refNineteen.email = "rajesh.bhat@example.com";
refNineteen.phoneNumber = "9845011122";
refNineteen.address = "Yeshwanthpur";
refNineteen.city = "Bengaluru";
refNineteen.state = "Karnataka";
refNineteen.country = "India";
refNineteen.dateOfJoining = "07-07-2014";
refNineteen.managerName = "Suresh Rao";
refNineteen.isPermanent = true;
refNineteen.isRemote = false;
refNineteen.experienceYears = 16;
refNineteen.highestQualification = "B.E Mechanical";
refNineteen.bloodGroup = "O+";
refNineteen.maritalStatus = "Married";
refNineteen.nationality = "Indian";
refNineteen.employeeType = "Full Time";
refNineteen.workShift = "Morning";


System.out.println("The employeeId is: " + refNineteen.employeeId);
System.out.println("The firstName is: " + refNineteen.firstName);
System.out.println("The lastName is: " + refNineteen.lastName);
System.out.println("The gender is: " + refNineteen.gender);
System.out.println("The age is: " + refNineteen.age);
System.out.println("The department is: " + refNineteen.department);
System.out.println("The designation is: " + refNineteen.designation);
System.out.println("The salary is: " + refNineteen.salary);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The phoneNumber is: " + refNineteen.phoneNumber);
System.out.println("The address is: " + refNineteen.address);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The dateOfJoining is: " + refNineteen.dateOfJoining);
System.out.println("The managerName is: " + refNineteen.managerName);
System.out.println("The isPermanent is: " + refNineteen.isPermanent);
System.out.println("The isRemote is: " + refNineteen.isRemote);
System.out.println("The experienceYears is: " + refNineteen.experienceYears);
System.out.println("The highestQualification is: " + refNineteen.highestQualification);
System.out.println("The bloodGroup is: " + refNineteen.bloodGroup);
System.out.println("The maritalStatus is: " + refNineteen.maritalStatus);
System.out.println("The nationality is: " + refNineteen.nationality);
System.out.println("The employeeType is: " + refNineteen.employeeType);
System.out.println("The workShift is: " + refNineteen.workShift);
Employee refTwenty = new Employee();

System.out.println("The employeeId is: " + refTwenty.employeeId);
System.out.println("The firstName is: " + refTwenty.firstName);
System.out.println("The lastName is: " + refTwenty.lastName);
System.out.println("The gender is: " + refTwenty.gender);
System.out.println("The age is: " + refTwenty.age);
System.out.println("The department is: " + refTwenty.department);
System.out.println("The designation is: " + refTwenty.designation);
System.out.println("The salary is: " + refTwenty.salary);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The phoneNumber is: " + refTwenty.phoneNumber);
System.out.println("The address is: " + refTwenty.address);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The dateOfJoining is: " + refTwenty.dateOfJoining);
System.out.println("The managerName is: " + refTwenty.managerName);
System.out.println("The isPermanent is: " + refTwenty.isPermanent);
System.out.println("The isRemote is: " + refTwenty.isRemote);
System.out.println("The experienceYears is: " + refTwenty.experienceYears);
System.out.println("The highestQualification is: " + refTwenty.highestQualification);
System.out.println("The bloodGroup is: " + refTwenty.bloodGroup);
System.out.println("The maritalStatus is: " + refTwenty.maritalStatus);
System.out.println("The nationality is: " + refTwenty.nationality);
System.out.println("The employeeType is: " + refTwenty.employeeType);
System.out.println("The workShift is: " + refTwenty.workShift);


refTwenty.employeeId = 20;
refTwenty.firstName = "Divya";
refTwenty.lastName = "Sharma";
refTwenty.gender = "Female";
refTwenty.age = 30;
refTwenty.department = "Public Relations";
refTwenty.designation = "PR Manager";
refTwenty.salary = 69000.00;
refTwenty.email = "divya.sharma@example.com";
refTwenty.phoneNumber = "9876541200";
refTwenty.address = "JP Nagar";
refTwenty.city = "Bengaluru";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.dateOfJoining = "09-09-2020";
refTwenty.managerName = "Karthik Reddy";
refTwenty.isPermanent = true;
refTwenty.isRemote = true;
refTwenty.experienceYears = 6;
refTwenty.highestQualification = "MBA Communications";
refTwenty.bloodGroup = "B+";
refTwenty.maritalStatus = "Single";
refTwenty.nationality = "Indian";
refTwenty.employeeType = "Full Time";
refTwenty.workShift = "Day";


System.out.println("The employeeId is: " + refTwenty.employeeId);
System.out.println("The firstName is: " + refTwenty.firstName);
System.out.println("The lastName is: " + refTwenty.lastName);
System.out.println("The gender is: " + refTwenty.gender);
System.out.println("The age is: " + refTwenty.age);
System.out.println("The department is: " + refTwenty.department);
System.out.println("The designation is: " + refTwenty.designation);
System.out.println("The salary is: " + refTwenty.salary);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The phoneNumber is: " + refTwenty.phoneNumber);
System.out.println("The address is: " + refTwenty.address);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The dateOfJoining is: " + refTwenty.dateOfJoining);
System.out.println("The managerName is: " + refTwenty.managerName);
System.out.println("The isPermanent is: " + refTwenty.isPermanent);
System.out.println("The isRemote is: " + refTwenty.isRemote);
System.out.println("The experienceYears is: " + refTwenty.experienceYears);
System.out.println("The highestQualification is: " + refTwenty.highestQualification);
System.out.println("The bloodGroup is: " + refTwenty.bloodGroup);
System.out.println("The maritalStatus is: " + refTwenty.maritalStatus);
System.out.println("The nationality is: " + refTwenty.nationality);
System.out.println("The employeeType is: " + refTwenty.employeeType);
System.out.println("The workShift is: " + refTwenty.workShift);
}
}