class GymExecutor{
public static void main(String[] args){
Gym refOne = new Gym();

System.out.println("The gymId is: " + refOne.gymId);
System.out.println("The gymName is: " + refOne.gymName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfTrainers is: " + refOne.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refOne.numberOfMembers);
System.out.println("The numberOfMachines is: " + refOne.numberOfMachines);
System.out.println("The hasCardioZone is: " + refOne.hasCardioZone);
System.out.println("The hasWeightZone is: " + refOne.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refOne.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refOne.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refOne.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refOne.hasSwimmingPool);
System.out.println("The hasSauna is: " + refOne.hasSauna);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasLockerRooms is: " + refOne.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refOne.hasCafeteria);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The managerName is: " + refOne.managerName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);


refOne.gymId = 1;
refOne.gymName = "FitZone Gym";
refOne.location = "MG Road";
refOne.city = "Bengaluru";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfTrainers = 8;
refOne.numberOfMembers = 250;
refOne.numberOfMachines = 60;
refOne.hasCardioZone = true;
refOne.hasWeightZone = true;
refOne.hasYogaClasses = true;
refOne.hasAerobicsClasses = true;
refOne.hasPersonalTraining = true;
refOne.hasSwimmingPool = false;
refOne.hasSauna = true;
refOne.hasParking = true;
refOne.hasLockerRooms = true;
refOne.hasCafeteria = false;
refOne.hasWifi = true;
refOne.managerName = "Rahul Sharma";
refOne.establishedYear = 2015;
refOne.contactNumber = "9876543210";
refOne.email = "info@fitzonegym.com";
refOne.website = "www.fitzonegym.com";


System.out.println("The gymId is: " + refOne.gymId);
System.out.println("The gymName is: " + refOne.gymName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfTrainers is: " + refOne.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refOne.numberOfMembers);
System.out.println("The numberOfMachines is: " + refOne.numberOfMachines);
System.out.println("The hasCardioZone is: " + refOne.hasCardioZone);
System.out.println("The hasWeightZone is: " + refOne.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refOne.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refOne.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refOne.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refOne.hasSwimmingPool);
System.out.println("The hasSauna is: " + refOne.hasSauna);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasLockerRooms is: " + refOne.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refOne.hasCafeteria);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The managerName is: " + refOne.managerName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
Gym refTwo = new Gym();

System.out.println("The gymId is: " + refTwo.gymId);
System.out.println("The gymName is: " + refTwo.gymName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfTrainers is: " + refTwo.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refTwo.numberOfMembers);
System.out.println("The numberOfMachines is: " + refTwo.numberOfMachines);
System.out.println("The hasCardioZone is: " + refTwo.hasCardioZone);
System.out.println("The hasWeightZone is: " + refTwo.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refTwo.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refTwo.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refTwo.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refTwo.hasSwimmingPool);
System.out.println("The hasSauna is: " + refTwo.hasSauna);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasLockerRooms is: " + refTwo.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refTwo.hasCafeteria);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The managerName is: " + refTwo.managerName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);


refTwo.gymId = 2;
refTwo.gymName = "PowerHouse Fitness";
refTwo.location = "Indiranagar";
refTwo.city = "Bengaluru";
refTwo.state = "Karnataka";
refTwo.country = "India";
refTwo.numberOfTrainers = 10;
refTwo.numberOfMembers = 320;
refTwo.numberOfMachines = 75;
refTwo.hasCardioZone = true;
refTwo.hasWeightZone = true;
refTwo.hasYogaClasses = true;
refTwo.hasAerobicsClasses = false;
refTwo.hasPersonalTraining = true;
refTwo.hasSwimmingPool = true;
refTwo.hasSauna = true;
refTwo.hasParking = true;
refTwo.hasLockerRooms = true;
refTwo.hasCafeteria = true;
refTwo.hasWifi = true;
refTwo.managerName = "Arjun Mehta";
refTwo.establishedYear = 2018;
refTwo.contactNumber = "9123456780";
refTwo.email = "contact@powerhousefitness.com";
refTwo.website = "www.powerhousefitness.com";


System.out.println("The gymId is: " + refTwo.gymId);
System.out.println("The gymName is: " + refTwo.gymName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfTrainers is: " + refTwo.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refTwo.numberOfMembers);
System.out.println("The numberOfMachines is: " + refTwo.numberOfMachines);
System.out.println("The hasCardioZone is: " + refTwo.hasCardioZone);
System.out.println("The hasWeightZone is: " + refTwo.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refTwo.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refTwo.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refTwo.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refTwo.hasSwimmingPool);
System.out.println("The hasSauna is: " + refTwo.hasSauna);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasLockerRooms is: " + refTwo.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refTwo.hasCafeteria);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The managerName is: " + refTwo.managerName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
Gym refThree = new Gym();

System.out.println("The gymId is: " + refThree.gymId);
System.out.println("The gymName is: " + refThree.gymName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfTrainers is: " + refThree.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refThree.numberOfMembers);
System.out.println("The numberOfMachines is: " + refThree.numberOfMachines);
System.out.println("The hasCardioZone is: " + refThree.hasCardioZone);
System.out.println("The hasWeightZone is: " + refThree.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refThree.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refThree.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refThree.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refThree.hasSwimmingPool);
System.out.println("The hasSauna is: " + refThree.hasSauna);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasLockerRooms is: " + refThree.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refThree.hasCafeteria);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The managerName is: " + refThree.managerName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);


refThree.gymId = 3;
refThree.gymName = "Muscle Factory Gym";
refThree.location = "BTM Layout";
refThree.city = "Bengaluru";
refThree.state = "Karnataka";
refThree.country = "India";
refThree.numberOfTrainers = 6;
refThree.numberOfMembers = 180;
refThree.numberOfMachines = 55;
refThree.hasCardioZone = true;
refThree.hasWeightZone = true;
refThree.hasYogaClasses = false;
refThree.hasAerobicsClasses = true;
refThree.hasPersonalTraining = true;
refThree.hasSwimmingPool = false;
refThree.hasSauna = false;
refThree.hasParking = true;
refThree.hasLockerRooms = true;
refThree.hasCafeteria = false;
refThree.hasWifi = true;
refThree.managerName = "Karan Singh";
refThree.establishedYear = 2016;
refThree.contactNumber = "9012345678";
refThree.email = "info@musclefactory.com";
refThree.website = "www.musclefactorygym.com";


System.out.println("The gymId is: " + refThree.gymId);
System.out.println("The gymName is: " + refThree.gymName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfTrainers is: " + refThree.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refThree.numberOfMembers);
System.out.println("The numberOfMachines is: " + refThree.numberOfMachines);
System.out.println("The hasCardioZone is: " + refThree.hasCardioZone);
System.out.println("The hasWeightZone is: " + refThree.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refThree.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refThree.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refThree.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refThree.hasSwimmingPool);
System.out.println("The hasSauna is: " + refThree.hasSauna);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasLockerRooms is: " + refThree.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refThree.hasCafeteria);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The managerName is: " + refThree.managerName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
Gym refFour = new Gym();

System.out.println("The gymId is: " + refFour.gymId);
System.out.println("The gymName is: " + refFour.gymName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfTrainers is: " + refFour.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refFour.numberOfMembers);
System.out.println("The numberOfMachines is: " + refFour.numberOfMachines);
System.out.println("The hasCardioZone is: " + refFour.hasCardioZone);
System.out.println("The hasWeightZone is: " + refFour.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refFour.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refFour.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refFour.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refFour.hasSwimmingPool);
System.out.println("The hasSauna is: " + refFour.hasSauna);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasLockerRooms is: " + refFour.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refFour.hasCafeteria);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The managerName is: " + refFour.managerName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);


refFour.gymId = 4;
refFour.gymName = "Iron Temple Gym";
refFour.location = "Jayanagar";
refFour.city = "Bengaluru";
refFour.state = "Karnataka";
refFour.country = "India";
refFour.numberOfTrainers = 7;
refFour.numberOfMembers = 210;
refFour.numberOfMachines = 65;
refFour.hasCardioZone = true;
refFour.hasWeightZone = true;
refFour.hasYogaClasses = true;
refFour.hasAerobicsClasses = false;
refFour.hasPersonalTraining = true;
refFour.hasSwimmingPool = false;
refFour.hasSauna = true;
refFour.hasParking = true;
refFour.hasLockerRooms = true;
refFour.hasCafeteria = false;
refFour.hasWifi = true;
refFour.managerName = "Vikram Patel";
refFour.establishedYear = 2017;
refFour.contactNumber = "9345678120";
refFour.email = "info@irontemplegym.com";
refFour.website = "www.irontemplegym.com";


System.out.println("The gymId is: " + refFour.gymId);
System.out.println("The gymName is: " + refFour.gymName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfTrainers is: " + refFour.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refFour.numberOfMembers);
System.out.println("The numberOfMachines is: " + refFour.numberOfMachines);
System.out.println("The hasCardioZone is: " + refFour.hasCardioZone);
System.out.println("The hasWeightZone is: " + refFour.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refFour.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refFour.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refFour.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refFour.hasSwimmingPool);
System.out.println("The hasSauna is: " + refFour.hasSauna);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasLockerRooms is: " + refFour.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refFour.hasCafeteria);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The managerName is: " + refFour.managerName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
Gym refFive = new Gym();

System.out.println("The gymId is: " + refFive.gymId);
System.out.println("The gymName is: " + refFive.gymName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfTrainers is: " + refFive.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refFive.numberOfMembers);
System.out.println("The numberOfMachines is: " + refFive.numberOfMachines);
System.out.println("The hasCardioZone is: " + refFive.hasCardioZone);
System.out.println("The hasWeightZone is: " + refFive.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refFive.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refFive.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refFive.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refFive.hasSwimmingPool);
System.out.println("The hasSauna is: " + refFive.hasSauna);
System.out.println("The hasParking is: " + refFive.hasParking);
System.out.println("The hasLockerRooms is: " + refFive.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refFive.hasCafeteria);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The managerName is: " + refFive.managerName);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);


refFive.gymId = 5;
refFive.gymName = "Titan Fitness";
refFive.location = "Whitefield";
refFive.city = "Bengaluru";
refFive.state = "Karnataka";
refFive.country = "India";
refFive.numberOfTrainers = 9;
refFive.numberOfMembers = 300;
refFive.numberOfMachines = 70;
refFive.hasCardioZone = true;
refFive.hasWeightZone = true;
refFive.hasYogaClasses = true;
refFive.hasAerobicsClasses = true;
refFive.hasPersonalTraining = true;
refFive.hasSwimmingPool = false;
refFive.hasSauna = true;
refFive.hasParking = true;
refFive.hasLockerRooms = true;
refFive.hasCafeteria = true;
refFive.hasWifi = true;
refFive.managerName = "Rohit Verma";
refFive.establishedYear = 2020;
refFive.contactNumber = "9567812340";
refFive.email = "info@titanfitness.com";
refFive.website = "www.titanfitness.com";


System.out.println("The gymId is: " + refFive.gymId);
System.out.println("The gymName is: " + refFive.gymName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfTrainers is: " + refFive.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refFive.numberOfMembers);
System.out.println("The numberOfMachines is: " + refFive.numberOfMachines);
System.out.println("The hasCardioZone is: " + refFive.hasCardioZone);
System.out.println("The hasWeightZone is: " + refFive.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refFive.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refFive.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refFive.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refFive.hasSwimmingPool);
System.out.println("The hasSauna is: " + refFive.hasSauna);
System.out.println("The hasParking is: " + refFive.hasParking);
System.out.println("The hasLockerRooms is: " + refFive.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refFive.hasCafeteria);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The managerName is: " + refFive.managerName);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
Gym refSix = new Gym();

System.out.println("The gymId is: " + refSix.gymId);
System.out.println("The gymName is: " + refSix.gymName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfTrainers is: " + refSix.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refSix.numberOfMembers);
System.out.println("The numberOfMachines is: " + refSix.numberOfMachines);
System.out.println("The hasCardioZone is: " + refSix.hasCardioZone);
System.out.println("The hasWeightZone is: " + refSix.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refSix.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refSix.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refSix.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refSix.hasSwimmingPool);
System.out.println("The hasSauna is: " + refSix.hasSauna);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasLockerRooms is: " + refSix.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refSix.hasCafeteria);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The managerName is: " + refSix.managerName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);


refSix.gymId = 6;
refSix.gymName = "Elite Fitness Club";
refSix.location = "Koramangala";
refSix.city = "Bengaluru";
refSix.state = "Karnataka";
refSix.country = "India";
refSix.numberOfTrainers = 11;
refSix.numberOfMembers = 350;
refSix.numberOfMachines = 80;
refSix.hasCardioZone = true;
refSix.hasWeightZone = true;
refSix.hasYogaClasses = true;
refSix.hasAerobicsClasses = true;
refSix.hasPersonalTraining = true;
refSix.hasSwimmingPool = true;
refSix.hasSauna = true;
refSix.hasParking = true;
refSix.hasLockerRooms = true;
refSix.hasCafeteria = true;
refSix.hasWifi = true;
refSix.managerName = "Ankit Sharma";
refSix.establishedYear = 2014;
refSix.contactNumber = "9898765432";
refSix.email = "contact@elitefitness.com";
refSix.website = "www.elitefitnessclub.com";


System.out.println("The gymId is: " + refSix.gymId);
System.out.println("The gymName is: " + refSix.gymName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfTrainers is: " + refSix.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refSix.numberOfMembers);
System.out.println("The numberOfMachines is: " + refSix.numberOfMachines);
System.out.println("The hasCardioZone is: " + refSix.hasCardioZone);
System.out.println("The hasWeightZone is: " + refSix.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refSix.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refSix.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refSix.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refSix.hasSwimmingPool);
System.out.println("The hasSauna is: " + refSix.hasSauna);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasLockerRooms is: " + refSix.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refSix.hasCafeteria);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The managerName is: " + refSix.managerName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
Gym refSeven = new Gym();

System.out.println("The gymId is: " + refSeven.gymId);
System.out.println("The gymName is: " + refSeven.gymName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfTrainers is: " + refSeven.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refSeven.numberOfMembers);
System.out.println("The numberOfMachines is: " + refSeven.numberOfMachines);
System.out.println("The hasCardioZone is: " + refSeven.hasCardioZone);
System.out.println("The hasWeightZone is: " + refSeven.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refSeven.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refSeven.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refSeven.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refSeven.hasSwimmingPool);
System.out.println("The hasSauna is: " + refSeven.hasSauna);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasLockerRooms is: " + refSeven.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refSeven.hasCafeteria);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The managerName is: " + refSeven.managerName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);


refSeven.gymId = 7;
refSeven.gymName = "BodyCraft Gym";
refSeven.location = "HSR Layout";
refSeven.city = "Bengaluru";
refSeven.state = "Karnataka";
refSeven.country = "India";
refSeven.numberOfTrainers = 8;
refSeven.numberOfMembers = 270;
refSeven.numberOfMachines = 68;
refSeven.hasCardioZone = true;
refSeven.hasWeightZone = true;
refSeven.hasYogaClasses = true;
refSeven.hasAerobicsClasses = true;
refSeven.hasPersonalTraining = true;
refSeven.hasSwimmingPool = false;
refSeven.hasSauna = true;
refSeven.hasParking = true;
refSeven.hasLockerRooms = true;
refSeven.hasCafeteria = false;
refSeven.hasWifi = true;
refSeven.managerName = "Deepak Kumar";
refSeven.establishedYear = 2019;
refSeven.contactNumber = "9786543210";
refSeven.email = "info@bodycraftgym.com";
refSeven.website = "www.bodycraftgym.com";


System.out.println("The gymId is: " + refSeven.gymId);
System.out.println("The gymName is: " + refSeven.gymName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfTrainers is: " + refSeven.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refSeven.numberOfMembers);
System.out.println("The numberOfMachines is: " + refSeven.numberOfMachines);
System.out.println("The hasCardioZone is: " + refSeven.hasCardioZone);
System.out.println("The hasWeightZone is: " + refSeven.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refSeven.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refSeven.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refSeven.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refSeven.hasSwimmingPool);
System.out.println("The hasSauna is: " + refSeven.hasSauna);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasLockerRooms is: " + refSeven.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refSeven.hasCafeteria);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The managerName is: " + refSeven.managerName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
Gym refEight = new Gym();

System.out.println("The gymId is: " + refEight.gymId);
System.out.println("The gymName is: " + refEight.gymName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfTrainers is: " + refEight.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refEight.numberOfMembers);
System.out.println("The numberOfMachines is: " + refEight.numberOfMachines);
System.out.println("The hasCardioZone is: " + refEight.hasCardioZone);
System.out.println("The hasWeightZone is: " + refEight.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refEight.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refEight.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refEight.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refEight.hasSwimmingPool);
System.out.println("The hasSauna is: " + refEight.hasSauna);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasLockerRooms is: " + refEight.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refEight.hasCafeteria);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The managerName is: " + refEight.managerName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);


refEight.gymId = 8;
refEight.gymName = "Peak Performance Gym";
refEight.location = "Electronic City";
refEight.city = "Bengaluru";
refEight.state = "Karnataka";
refEight.country = "India";
refEight.numberOfTrainers = 5;
refEight.numberOfMembers = 150;
refEight.numberOfMachines = 50;
refEight.hasCardioZone = true;
refEight.hasWeightZone = true;
refEight.hasYogaClasses = false;
refEight.hasAerobicsClasses = true;
refEight.hasPersonalTraining = true;
refEight.hasSwimmingPool = false;
refEight.hasSauna = false;
refEight.hasParking = true;
refEight.hasLockerRooms = true;
refEight.hasCafeteria = false;
refEight.hasWifi = true;
refEight.managerName = "Sandeep Reddy";
refEight.establishedYear = 2013;
refEight.contactNumber = "9871203456";
refEight.email = "info@peakperformance.com";
refEight.website = "www.peakperformancegym.com";


System.out.println("The gymId is: " + refEight.gymId);
System.out.println("The gymName is: " + refEight.gymName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfTrainers is: " + refEight.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refEight.numberOfMembers);
System.out.println("The numberOfMachines is: " + refEight.numberOfMachines);
System.out.println("The hasCardioZone is: " + refEight.hasCardioZone);
System.out.println("The hasWeightZone is: " + refEight.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refEight.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refEight.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refEight.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refEight.hasSwimmingPool);
System.out.println("The hasSauna is: " + refEight.hasSauna);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasLockerRooms is: " + refEight.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refEight.hasCafeteria);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The managerName is: " + refEight.managerName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
Gym refNine = new Gym();

System.out.println("The gymId is: " + refNine.gymId);
System.out.println("The gymName is: " + refNine.gymName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfTrainers is: " + refNine.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refNine.numberOfMembers);
System.out.println("The numberOfMachines is: " + refNine.numberOfMachines);
System.out.println("The hasCardioZone is: " + refNine.hasCardioZone);
System.out.println("The hasWeightZone is: " + refNine.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refNine.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refNine.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refNine.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refNine.hasSwimmingPool);
System.out.println("The hasSauna is: " + refNine.hasSauna);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasLockerRooms is: " + refNine.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refNine.hasCafeteria);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The managerName is: " + refNine.managerName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);


refNine.gymId = 9;
refNine.gymName = "StrongFit Gym";
refNine.location = "Rajajinagar";
refNine.city = "Bengaluru";
refNine.state = "Karnataka";
refNine.country = "India";
refNine.numberOfTrainers = 7;
refNine.numberOfMembers = 220;
refNine.numberOfMachines = 58;
refNine.hasCardioZone = true;
refNine.hasWeightZone = true;
refNine.hasYogaClasses = true;
refNine.hasAerobicsClasses = false;
refNine.hasPersonalTraining = true;
refNine.hasSwimmingPool = false;
refNine.hasSauna = false;
refNine.hasParking = true;
refNine.hasLockerRooms = true;
refNine.hasCafeteria = false;
refNine.hasWifi = true;
refNine.managerName = "Rakesh Nair";
refNine.establishedYear = 2012;
refNine.contactNumber = "9845123678";
refNine.email = "contact@strongfitgym.com";
refNine.website = "www.strongfitgym.com";


System.out.println("The gymId is: " + refNine.gymId);
System.out.println("The gymName is: " + refNine.gymName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfTrainers is: " + refNine.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refNine.numberOfMembers);
System.out.println("The numberOfMachines is: " + refNine.numberOfMachines);
System.out.println("The hasCardioZone is: " + refNine.hasCardioZone);
System.out.println("The hasWeightZone is: " + refNine.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refNine.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refNine.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refNine.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refNine.hasSwimmingPool);
System.out.println("The hasSauna is: " + refNine.hasSauna);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasLockerRooms is: " + refNine.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refNine.hasCafeteria);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The managerName is: " + refNine.managerName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
Gym refTen = new Gym();

System.out.println("The gymId is: " + refTen.gymId);
System.out.println("The gymName is: " + refTen.gymName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfTrainers is: " + refTen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refTen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refTen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refTen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refTen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refTen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refTen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refTen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refTen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refTen.hasSauna);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasLockerRooms is: " + refTen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refTen.hasCafeteria);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The managerName is: " + refTen.managerName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);


refTen.gymId = 10;
refTen.gymName = "FlexFit Gym";
refTen.location = "Malleshwaram";
refTen.city = "Bengaluru";
refTen.state = "Karnataka";
refTen.country = "India";
refTen.numberOfTrainers = 6;
refTen.numberOfMembers = 190;
refTen.numberOfMachines = 52;
refTen.hasCardioZone = true;
refTen.hasWeightZone = true;
refTen.hasYogaClasses = false;
refTen.hasAerobicsClasses = true;
refTen.hasPersonalTraining = true;
refTen.hasSwimmingPool = false;
refTen.hasSauna = false;
refTen.hasParking = true;
refTen.hasLockerRooms = true;
refTen.hasCafeteria = false;
refTen.hasWifi = true;
refTen.managerName = "Suresh Kumar";
refTen.establishedYear = 2011;
refTen.contactNumber = "9876541203";
refTen.email = "info@flexfitgym.com";
refTen.website = "www.flexfitgym.com";


System.out.println("The gymId is: " + refTen.gymId);
System.out.println("The gymName is: " + refTen.gymName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfTrainers is: " + refTen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refTen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refTen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refTen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refTen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refTen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refTen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refTen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refTen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refTen.hasSauna);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasLockerRooms is: " + refTen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refTen.hasCafeteria);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The managerName is: " + refTen.managerName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
Gym refEleven = new Gym();

System.out.println("The gymId is: " + refEleven.gymId);
System.out.println("The gymName is: " + refEleven.gymName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfTrainers is: " + refEleven.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refEleven.numberOfMembers);
System.out.println("The numberOfMachines is: " + refEleven.numberOfMachines);
System.out.println("The hasCardioZone is: " + refEleven.hasCardioZone);
System.out.println("The hasWeightZone is: " + refEleven.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refEleven.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refEleven.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refEleven.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refEleven.hasSwimmingPool);
System.out.println("The hasSauna is: " + refEleven.hasSauna);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasLockerRooms is: " + refEleven.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refEleven.hasCafeteria);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The managerName is: " + refEleven.managerName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);


refEleven.gymId = 11;
refEleven.gymName = "Power Pulse Gym";
refEleven.location = "Yelahanka";
refEleven.city = "Bengaluru";
refEleven.state = "Karnataka";
refEleven.country = "India";
refEleven.numberOfTrainers = 9;
refEleven.numberOfMembers = 260;
refEleven.numberOfMachines = 64;
refEleven.hasCardioZone = true;
refEleven.hasWeightZone = true;
refEleven.hasYogaClasses = true;
refEleven.hasAerobicsClasses = true;
refEleven.hasPersonalTraining = true;
refEleven.hasSwimmingPool = false;
refEleven.hasSauna = true;
refEleven.hasParking = true;
refEleven.hasLockerRooms = true;
refEleven.hasCafeteria = false;
refEleven.hasWifi = true;
refEleven.managerName = "Amit Joshi";
refEleven.establishedYear = 2016;
refEleven.contactNumber = "9812345670";
refEleven.email = "info@powerpulsegym.com";
refEleven.website = "www.powerpulsegym.com";


System.out.println("The gymId is: " + refEleven.gymId);
System.out.println("The gymName is: " + refEleven.gymName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfTrainers is: " + refEleven.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refEleven.numberOfMembers);
System.out.println("The numberOfMachines is: " + refEleven.numberOfMachines);
System.out.println("The hasCardioZone is: " + refEleven.hasCardioZone);
System.out.println("The hasWeightZone is: " + refEleven.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refEleven.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refEleven.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refEleven.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refEleven.hasSwimmingPool);
System.out.println("The hasSauna is: " + refEleven.hasSauna);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasLockerRooms is: " + refEleven.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refEleven.hasCafeteria);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The managerName is: " + refEleven.managerName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
Gym refTwelve = new Gym();

System.out.println("The gymId is: " + refTwelve.gymId);
System.out.println("The gymName is: " + refTwelve.gymName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfTrainers is: " + refTwelve.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refTwelve.numberOfMembers);
System.out.println("The numberOfMachines is: " + refTwelve.numberOfMachines);
System.out.println("The hasCardioZone is: " + refTwelve.hasCardioZone);
System.out.println("The hasWeightZone is: " + refTwelve.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refTwelve.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refTwelve.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refTwelve.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refTwelve.hasSwimmingPool);
System.out.println("The hasSauna is: " + refTwelve.hasSauna);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasLockerRooms is: " + refTwelve.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refTwelve.hasCafeteria);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The managerName is: " + refTwelve.managerName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);


refTwelve.gymId = 12;
refTwelve.gymName = "Fit Arena Gym";
refTwelve.location = "Banashankari";
refTwelve.city = "Bengaluru";
refTwelve.state = "Karnataka";
refTwelve.country = "India";
refTwelve.numberOfTrainers = 8;
refTwelve.numberOfMembers = 230;
refTwelve.numberOfMachines = 62;
refTwelve.hasCardioZone = true;
refTwelve.hasWeightZone = true;
refTwelve.hasYogaClasses = true;
refTwelve.hasAerobicsClasses = true;
refTwelve.hasPersonalTraining = true;
refTwelve.hasSwimmingPool = false;
refTwelve.hasSauna = false;
refTwelve.hasParking = true;
refTwelve.hasLockerRooms = true;
refTwelve.hasCafeteria = true;
refTwelve.hasWifi = true;
refTwelve.managerName = "Naveen Kumar";
refTwelve.establishedYear = 2017;
refTwelve.contactNumber = "9874512360";
refTwelve.email = "info@fitarena.com";
refTwelve.website = "www.fitarenagym.com";


System.out.println("The gymId is: " + refTwelve.gymId);
System.out.println("The gymName is: " + refTwelve.gymName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfTrainers is: " + refTwelve.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refTwelve.numberOfMembers);
System.out.println("The numberOfMachines is: " + refTwelve.numberOfMachines);
System.out.println("The hasCardioZone is: " + refTwelve.hasCardioZone);
System.out.println("The hasWeightZone is: " + refTwelve.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refTwelve.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refTwelve.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refTwelve.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refTwelve.hasSwimmingPool);
System.out.println("The hasSauna is: " + refTwelve.hasSauna);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasLockerRooms is: " + refTwelve.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refTwelve.hasCafeteria);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The managerName is: " + refTwelve.managerName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
Gym refThirteen = new Gym();

System.out.println("The gymId is: " + refThirteen.gymId);
System.out.println("The gymName is: " + refThirteen.gymName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfTrainers is: " + refThirteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refThirteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refThirteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refThirteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refThirteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refThirteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refThirteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refThirteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refThirteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refThirteen.hasSauna);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasLockerRooms is: " + refThirteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refThirteen.hasCafeteria);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The managerName is: " + refThirteen.managerName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);


refThirteen.gymId = 13;
refThirteen.gymName = "Ultimate Fitness";
refThirteen.location = "Marathahalli";
refThirteen.city = "Bengaluru";
refThirteen.state = "Karnataka";
refThirteen.country = "India";
refThirteen.numberOfTrainers = 10;
refThirteen.numberOfMembers = 310;
refThirteen.numberOfMachines = 72;
refThirteen.hasCardioZone = true;
refThirteen.hasWeightZone = true;
refThirteen.hasYogaClasses = true;
refThirteen.hasAerobicsClasses = true;
refThirteen.hasPersonalTraining = true;
refThirteen.hasSwimmingPool = false;
refThirteen.hasSauna = true;
refThirteen.hasParking = true;
refThirteen.hasLockerRooms = true;
refThirteen.hasCafeteria = true;
refThirteen.hasWifi = true;
refThirteen.managerName = "Vishal Gupta";
refThirteen.establishedYear = 2018;
refThirteen.contactNumber = "9887612345";
refThirteen.email = "contact@ultimatefitness.com";
refThirteen.website = "www.ultimatefitnessgym.com";


System.out.println("The gymId is: " + refThirteen.gymId);
System.out.println("The gymName is: " + refThirteen.gymName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfTrainers is: " + refThirteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refThirteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refThirteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refThirteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refThirteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refThirteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refThirteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refThirteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refThirteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refThirteen.hasSauna);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasLockerRooms is: " + refThirteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refThirteen.hasCafeteria);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The managerName is: " + refThirteen.managerName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
Gym refFourteen = new Gym();

System.out.println("The gymId is: " + refFourteen.gymId);
System.out.println("The gymName is: " + refFourteen.gymName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfTrainers is: " + refFourteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refFourteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refFourteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refFourteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refFourteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refFourteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refFourteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refFourteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refFourteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refFourteen.hasSauna);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasLockerRooms is: " + refFourteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refFourteen.hasCafeteria);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The managerName is: " + refFourteen.managerName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);


refFourteen.gymId = 14;
refFourteen.gymName = "Urban Fit Gym";
refFourteen.location = "Hebbal";
refFourteen.city = "Bengaluru";
refFourteen.state = "Karnataka";
refFourteen.country = "India";
refFourteen.numberOfTrainers = 7;
refFourteen.numberOfMembers = 210;
refFourteen.numberOfMachines = 60;
refFourteen.hasCardioZone = true;
refFourteen.hasWeightZone = true;
refFourteen.hasYogaClasses = false;
refFourteen.hasAerobicsClasses = true;
refFourteen.hasPersonalTraining = true;
refFourteen.hasSwimmingPool = false;
refFourteen.hasSauna = false;
refFourteen.hasParking = true;
refFourteen.hasLockerRooms = true;
refFourteen.hasCafeteria = false;
refFourteen.hasWifi = true;
refFourteen.managerName = "Karthik Reddy";
refFourteen.establishedYear = 2015;
refFourteen.contactNumber = "9898123456";
refFourteen.email = "info@urbanfitgym.com";
refFourteen.website = "www.urbanfitgym.com";


System.out.println("The gymId is: " + refFourteen.gymId);
System.out.println("The gymName is: " + refFourteen.gymName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfTrainers is: " + refFourteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refFourteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refFourteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refFourteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refFourteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refFourteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refFourteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refFourteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refFourteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refFourteen.hasSauna);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasLockerRooms is: " + refFourteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refFourteen.hasCafeteria);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The managerName is: " + refFourteen.managerName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
Gym refFifteen = new Gym();

System.out.println("The gymId is: " + refFifteen.gymId);
System.out.println("The gymName is: " + refFifteen.gymName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfTrainers is: " + refFifteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refFifteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refFifteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refFifteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refFifteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refFifteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refFifteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refFifteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refFifteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refFifteen.hasSauna);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasLockerRooms is: " + refFifteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refFifteen.hasCafeteria);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The managerName is: " + refFifteen.managerName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);


refFifteen.gymId = 15;
refFifteen.gymName = "IronCore Fitness";
refFifteen.location = "JP Nagar";
refFifteen.city = "Bengaluru";
refFifteen.state = "Karnataka";
refFifteen.country = "India";
refFifteen.numberOfTrainers = 9;
refFifteen.numberOfMembers = 280;
refFifteen.numberOfMachines = 66;
refFifteen.hasCardioZone = true;
refFifteen.hasWeightZone = true;
refFifteen.hasYogaClasses = true;
refFifteen.hasAerobicsClasses = true;
refFifteen.hasPersonalTraining = true;
refFifteen.hasSwimmingPool = false;
refFifteen.hasSauna = true;
refFifteen.hasParking = true;
refFifteen.hasLockerRooms = true;
refFifteen.hasCafeteria = true;
refFifteen.hasWifi = true;
refFifteen.managerName = "Pradeep Shetty";
refFifteen.establishedYear = 2019;
refFifteen.contactNumber = "9765432180";
refFifteen.email = "info@ironcorefitness.com";
refFifteen.website = "www.ironcorefitness.com";


System.out.println("The gymId is: " + refFifteen.gymId);
System.out.println("The gymName is: " + refFifteen.gymName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfTrainers is: " + refFifteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refFifteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refFifteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refFifteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refFifteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refFifteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refFifteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refFifteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refFifteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refFifteen.hasSauna);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasLockerRooms is: " + refFifteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refFifteen.hasCafeteria);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The managerName is: " + refFifteen.managerName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
Gym refSixteen = new Gym();

System.out.println("The gymId is: " + refSixteen.gymId);
System.out.println("The gymName is: " + refSixteen.gymName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfTrainers is: " + refSixteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refSixteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refSixteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refSixteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refSixteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refSixteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refSixteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refSixteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refSixteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refSixteen.hasSauna);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasLockerRooms is: " + refSixteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refSixteen.hasCafeteria);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The managerName is: " + refSixteen.managerName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);


refSixteen.gymId = 16;
refSixteen.gymName = "MaxBurn Gym";
refSixteen.location = "Kalyan Nagar";
refSixteen.city = "Bengaluru";
refSixteen.state = "Karnataka";
refSixteen.country = "India";
refSixteen.numberOfTrainers = 6;
refSixteen.numberOfMembers = 200;
refSixteen.numberOfMachines = 54;
refSixteen.hasCardioZone = true;
refSixteen.hasWeightZone = true;
refSixteen.hasYogaClasses = false;
refSixteen.hasAerobicsClasses = true;
refSixteen.hasPersonalTraining = true;
refSixteen.hasSwimmingPool = false;
refSixteen.hasSauna = false;
refSixteen.hasParking = true;
refSixteen.hasLockerRooms = true;
refSixteen.hasCafeteria = false;
refSixteen.hasWifi = true;
refSixteen.managerName = "Manoj Bhat";
refSixteen.establishedYear = 2014;
refSixteen.contactNumber = "9823456712";
refSixteen.email = "info@maxburngym.com";
refSixteen.website = "www.maxburngym.com";


System.out.println("The gymId is: " + refSixteen.gymId);
System.out.println("The gymName is: " + refSixteen.gymName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfTrainers is: " + refSixteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refSixteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refSixteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refSixteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refSixteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refSixteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refSixteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refSixteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refSixteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refSixteen.hasSauna);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasLockerRooms is: " + refSixteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refSixteen.hasCafeteria);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The managerName is: " + refSixteen.managerName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
Gym refSeventeen = new Gym();

System.out.println("The gymId is: " + refSeventeen.gymId);
System.out.println("The gymName is: " + refSeventeen.gymName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfTrainers is: " + refSeventeen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refSeventeen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refSeventeen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refSeventeen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refSeventeen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refSeventeen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refSeventeen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refSeventeen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refSeventeen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refSeventeen.hasSauna);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasLockerRooms is: " + refSeventeen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refSeventeen.hasCafeteria);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The managerName is: " + refSeventeen.managerName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);


refSeventeen.gymId = 17;
refSeventeen.gymName = "ProFit Gym";
refSeventeen.location = "KR Puram";
refSeventeen.city = "Bengaluru";
refSeventeen.state = "Karnataka";
refSeventeen.country = "India";
refSeventeen.numberOfTrainers = 8;
refSeventeen.numberOfMembers = 240;
refSeventeen.numberOfMachines = 61;
refSeventeen.hasCardioZone = true;
refSeventeen.hasWeightZone = true;
refSeventeen.hasYogaClasses = true;
refSeventeen.hasAerobicsClasses = false;
refSeventeen.hasPersonalTraining = true;
refSeventeen.hasSwimmingPool = false;
refSeventeen.hasSauna = true;
refSeventeen.hasParking = true;
refSeventeen.hasLockerRooms = true;
refSeventeen.hasCafeteria = false;
refSeventeen.hasWifi = true;
refSeventeen.managerName = "Ajay Kumar";
refSeventeen.establishedYear = 2016;
refSeventeen.contactNumber = "9845612378";
refSeventeen.email = "info@profitgym.com";
refSeventeen.website = "www.profitgym.com";


System.out.println("The gymId is: " + refSeventeen.gymId);
System.out.println("The gymName is: " + refSeventeen.gymName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfTrainers is: " + refSeventeen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refSeventeen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refSeventeen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refSeventeen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refSeventeen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refSeventeen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refSeventeen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refSeventeen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refSeventeen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refSeventeen.hasSauna);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasLockerRooms is: " + refSeventeen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refSeventeen.hasCafeteria);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The managerName is: " + refSeventeen.managerName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
Gym refEighteen = new Gym();

System.out.println("The gymId is: " + refEighteen.gymId);
System.out.println("The gymName is: " + refEighteen.gymName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfTrainers is: " + refEighteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refEighteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refEighteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refEighteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refEighteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refEighteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refEighteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refEighteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refEighteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refEighteen.hasSauna);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasLockerRooms is: " + refEighteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refEighteen.hasCafeteria);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The managerName is: " + refEighteen.managerName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);


refEighteen.gymId = 18;
refEighteen.gymName = "Fitness Edge";
refEighteen.location = "Sarjapur Road";
refEighteen.city = "Bengaluru";
refEighteen.state = "Karnataka";
refEighteen.country = "India";
refEighteen.numberOfTrainers = 7;
refEighteen.numberOfMembers = 220;
refEighteen.numberOfMachines = 58;
refEighteen.hasCardioZone = true;
refEighteen.hasWeightZone = true;
refEighteen.hasYogaClasses = true;
refEighteen.hasAerobicsClasses = true;
refEighteen.hasPersonalTraining = true;
refEighteen.hasSwimmingPool = false;
refEighteen.hasSauna = false;
refEighteen.hasParking = true;
refEighteen.hasLockerRooms = true;
refEighteen.hasCafeteria = false;
refEighteen.hasWifi = true;
refEighteen.managerName = "Rohit Sharma";
refEighteen.establishedYear = 2013;
refEighteen.contactNumber = "9812765430";
refEighteen.email = "info@fitnessedge.com";
refEighteen.website = "www.fitnessedgegym.com";


System.out.println("The gymId is: " + refEighteen.gymId);
System.out.println("The gymName is: " + refEighteen.gymName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfTrainers is: " + refEighteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refEighteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refEighteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refEighteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refEighteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refEighteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refEighteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refEighteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refEighteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refEighteen.hasSauna);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasLockerRooms is: " + refEighteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refEighteen.hasCafeteria);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The managerName is: " + refEighteen.managerName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
Gym refNineteen = new Gym();

System.out.println("The gymId is: " + refNineteen.gymId);
System.out.println("The gymName is: " + refNineteen.gymName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfTrainers is: " + refNineteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refNineteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refNineteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refNineteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refNineteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refNineteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refNineteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refNineteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refNineteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refNineteen.hasSauna);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasLockerRooms is: " + refNineteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refNineteen.hasCafeteria);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The managerName is: " + refNineteen.managerName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);


refNineteen.gymId = 19;
refNineteen.gymName = "PowerLift Gym";
refNineteen.location = "Bellandur";
refNineteen.city = "Bengaluru";
refNineteen.state = "Karnataka";
refNineteen.country = "India";
refNineteen.numberOfTrainers = 8;
refNineteen.numberOfMembers = 260;
refNineteen.numberOfMachines = 67;
refNineteen.hasCardioZone = true;
refNineteen.hasWeightZone = true;
refNineteen.hasYogaClasses = true;
refNineteen.hasAerobicsClasses = false;
refNineteen.hasPersonalTraining = true;
refNineteen.hasSwimmingPool = false;
refNineteen.hasSauna = true;
refNineteen.hasParking = true;
refNineteen.hasLockerRooms = true;
refNineteen.hasCafeteria = false;
refNineteen.hasWifi = true;
refNineteen.managerName = "Sanjay Rao";
refNineteen.establishedYear = 2017;
refNineteen.contactNumber = "9898761204";
refNineteen.email = "info@powerliftgym.com";
refNineteen.website = "www.powerliftgym.com";


System.out.println("The gymId is: " + refNineteen.gymId);
System.out.println("The gymName is: " + refNineteen.gymName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfTrainers is: " + refNineteen.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refNineteen.numberOfMembers);
System.out.println("The numberOfMachines is: " + refNineteen.numberOfMachines);
System.out.println("The hasCardioZone is: " + refNineteen.hasCardioZone);
System.out.println("The hasWeightZone is: " + refNineteen.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refNineteen.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refNineteen.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refNineteen.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refNineteen.hasSwimmingPool);
System.out.println("The hasSauna is: " + refNineteen.hasSauna);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasLockerRooms is: " + refNineteen.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refNineteen.hasCafeteria);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The managerName is: " + refNineteen.managerName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
Gym refTwenty = new Gym();

System.out.println("The gymId is: " + refTwenty.gymId);
System.out.println("The gymName is: " + refTwenty.gymName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfTrainers is: " + refTwenty.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refTwenty.numberOfMembers);
System.out.println("The numberOfMachines is: " + refTwenty.numberOfMachines);
System.out.println("The hasCardioZone is: " + refTwenty.hasCardioZone);
System.out.println("The hasWeightZone is: " + refTwenty.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refTwenty.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refTwenty.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refTwenty.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refTwenty.hasSwimmingPool);
System.out.println("The hasSauna is: " + refTwenty.hasSauna);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasLockerRooms is: " + refTwenty.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refTwenty.hasCafeteria);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The managerName is: " + refTwenty.managerName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);


refTwenty.gymId = 20;
refTwenty.gymName = "FitHub Gym";
refTwenty.location = "BTM 2nd Stage";
refTwenty.city = "Bengaluru";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.numberOfTrainers = 9;
refTwenty.numberOfMembers = 300;
refTwenty.numberOfMachines = 75;
refTwenty.hasCardioZone = true;
refTwenty.hasWeightZone = true;
refTwenty.hasYogaClasses = true;
refTwenty.hasAerobicsClasses = true;
refTwenty.hasPersonalTraining = true;
refTwenty.hasSwimmingPool = false;
refTwenty.hasSauna = true;
refTwenty.hasParking = true;
refTwenty.hasLockerRooms = true;
refTwenty.hasCafeteria = true;
refTwenty.hasWifi = true;
refTwenty.managerName = "Vivek Sharma";
refTwenty.establishedYear = 2020;
refTwenty.contactNumber = "9876543211";
refTwenty.email = "info@fithubgym.com";
refTwenty.website = "www.fithubgym.com";


System.out.println("The gymId is: " + refTwenty.gymId);
System.out.println("The gymName is: " + refTwenty.gymName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfTrainers is: " + refTwenty.numberOfTrainers);
System.out.println("The numberOfMembers is: " + refTwenty.numberOfMembers);
System.out.println("The numberOfMachines is: " + refTwenty.numberOfMachines);
System.out.println("The hasCardioZone is: " + refTwenty.hasCardioZone);
System.out.println("The hasWeightZone is: " + refTwenty.hasWeightZone);
System.out.println("The hasYogaClasses is: " + refTwenty.hasYogaClasses);
System.out.println("The hasAerobicsClasses is: " + refTwenty.hasAerobicsClasses);
System.out.println("The hasPersonalTraining is: " + refTwenty.hasPersonalTraining);
System.out.println("The hasSwimmingPool is: " + refTwenty.hasSwimmingPool);
System.out.println("The hasSauna is: " + refTwenty.hasSauna);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasLockerRooms is: " + refTwenty.hasLockerRooms);
System.out.println("The hasCafeteria is: " + refTwenty.hasCafeteria);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The managerName is: " + refTwenty.managerName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
}
}