class HospitalExecutor{
public static void main(String[] args){
Hospital refOne = new Hospital();

System.out.println("The hospitalId is: " + refOne.hospitalId);
System.out.println("The hospitalName is: " + refOne.hospitalName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfDoctors is: " + refOne.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refOne.numberOfNurses);
System.out.println("The numberOfBeds is: " + refOne.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refOne.hasEmergencyWard);
System.out.println("The hasICU is: " + refOne.hasICU);
System.out.println("The hasPharmacy is: " + refOne.hasPharmacy);
System.out.println("The hasAmbulance is: " + refOne.hasAmbulance);
System.out.println("The hospitalType is: " + refOne.hospitalType);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The ownerName is: " + refOne.ownerName);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The hasLaboratory is: " + refOne.hasLaboratory);
System.out.println("The hasRadiology is: " + refOne.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refOne.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refOne.parkingCapacity);
System.out.println("The accreditation is: " + refOne.accreditation);
System.out.println("The speciality is: " + refOne.speciality);


refOne.hospitalId = 1;
refOne.hospitalName = "Apollo Hospital";
refOne.location = "Bannerghatta Road";
refOne.city = "Bangalore";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfDoctors = 250;
refOne.numberOfNurses = 400;
refOne.numberOfBeds = 600;
refOne.hasEmergencyWard = true;
refOne.hasICU = true;
refOne.hasPharmacy = true;
refOne.hasAmbulance = true;
refOne.hospitalType = "Private";
refOne.establishedYear = 1995;
refOne.ownerName = "Apollo Group";
refOne.contactNumber = "08012345678";
refOne.email = "info@apollo.com";
refOne.website = "www.apollo.com";
refOne.hasLaboratory = true;
refOne.hasRadiology = true;
refOne.hasOperationTheatre = true;
refOne.parkingCapacity = 200;
refOne.accreditation = "NABH";
refOne.speciality = "Multi Speciality";


System.out.println("The hospitalId is: " + refOne.hospitalId);
System.out.println("The hospitalName is: " + refOne.hospitalName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfDoctors is: " + refOne.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refOne.numberOfNurses);
System.out.println("The numberOfBeds is: " + refOne.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refOne.hasEmergencyWard);
System.out.println("The hasICU is: " + refOne.hasICU);
System.out.println("The hasPharmacy is: " + refOne.hasPharmacy);
System.out.println("The hasAmbulance is: " + refOne.hasAmbulance);
System.out.println("The hospitalType is: " + refOne.hospitalType);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The ownerName is: " + refOne.ownerName);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The hasLaboratory is: " + refOne.hasLaboratory);
System.out.println("The hasRadiology is: " + refOne.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refOne.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refOne.parkingCapacity);
System.out.println("The accreditation is: " + refOne.accreditation);
System.out.println("The speciality is: " + refOne.speciality);
Hospital refTwo = new Hospital();

System.out.println("The hospitalId is: " + refTwo.hospitalId);
System.out.println("The hospitalName is: " + refTwo.hospitalName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfDoctors is: " + refTwo.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refTwo.numberOfNurses);
System.out.println("The numberOfBeds is: " + refTwo.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refTwo.hasEmergencyWard);
System.out.println("The hasICU is: " + refTwo.hasICU);
System.out.println("The hasPharmacy is: " + refTwo.hasPharmacy);
System.out.println("The hasAmbulance is: " + refTwo.hasAmbulance);
System.out.println("The hospitalType is: " + refTwo.hospitalType);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The ownerName is: " + refTwo.ownerName);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The hasLaboratory is: " + refTwo.hasLaboratory);
System.out.println("The hasRadiology is: " + refTwo.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refTwo.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refTwo.parkingCapacity);
System.out.println("The accreditation is: " + refTwo.accreditation);
System.out.println("The speciality is: " + refTwo.speciality);


refTwo.hospitalId = 2;
refTwo.hospitalName = "Fortis Hospital";
refTwo.location = "MG Road";
refTwo.city = "Bangalore";
refTwo.state = "Karnataka";
refTwo.country = "India";
refTwo.numberOfDoctors = 180;
refTwo.numberOfNurses = 300;
refTwo.numberOfBeds = 450;
refTwo.hasEmergencyWard = true;
refTwo.hasICU = true;
refTwo.hasPharmacy = true;
refTwo.hasAmbulance = true;
refTwo.hospitalType = "Private";
refTwo.establishedYear = 2001;
refTwo.ownerName = "Fortis Healthcare";
refTwo.contactNumber = "08098765432";
refTwo.email = "contact@fortis.com";
refTwo.website = "www.fortis.com";
refTwo.hasLaboratory = true;
refTwo.hasRadiology = true;
refTwo.hasOperationTheatre = true;
refTwo.parkingCapacity = 150;
refTwo.accreditation = "NABH";
refTwo.speciality = "Cardiology";


System.out.println("The hospitalId is: " + refTwo.hospitalId);
System.out.println("The hospitalName is: " + refTwo.hospitalName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfDoctors is: " + refTwo.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refTwo.numberOfNurses);
System.out.println("The numberOfBeds is: " + refTwo.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refTwo.hasEmergencyWard);
System.out.println("The hasICU is: " + refTwo.hasICU);
System.out.println("The hasPharmacy is: " + refTwo.hasPharmacy);
System.out.println("The hasAmbulance is: " + refTwo.hasAmbulance);
System.out.println("The hospitalType is: " + refTwo.hospitalType);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The ownerName is: " + refTwo.ownerName);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The hasLaboratory is: " + refTwo.hasLaboratory);
System.out.println("The hasRadiology is: " + refTwo.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refTwo.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refTwo.parkingCapacity);
System.out.println("The accreditation is: " + refTwo.accreditation);
System.out.println("The speciality is: " + refTwo.speciality);
Hospital refThree = new Hospital();

System.out.println("The hospitalId is: " + refThree.hospitalId);
System.out.println("The hospitalName is: " + refThree.hospitalName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfDoctors is: " + refThree.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refThree.numberOfNurses);
System.out.println("The numberOfBeds is: " + refThree.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refThree.hasEmergencyWard);
System.out.println("The hasICU is: " + refThree.hasICU);
System.out.println("The hasPharmacy is: " + refThree.hasPharmacy);
System.out.println("The hasAmbulance is: " + refThree.hasAmbulance);
System.out.println("The hospitalType is: " + refThree.hospitalType);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The ownerName is: " + refThree.ownerName);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The hasLaboratory is: " + refThree.hasLaboratory);
System.out.println("The hasRadiology is: " + refThree.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refThree.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refThree.parkingCapacity);
System.out.println("The accreditation is: " + refThree.accreditation);
System.out.println("The speciality is: " + refThree.speciality);


refThree.hospitalId = 3;
refThree.hospitalName = "Manipal Hospital";
refThree.location = "Old Airport Road";
refThree.city = "Bangalore";
refThree.state = "Karnataka";
refThree.country = "India";
refThree.numberOfDoctors = 220;
refThree.numberOfNurses = 350;
refThree.numberOfBeds = 500;
refThree.hasEmergencyWard = true;
refThree.hasICU = true;
refThree.hasPharmacy = true;
refThree.hasAmbulance = true;
refThree.hospitalType = "Private";
refThree.establishedYear = 1991;
refThree.ownerName = "Manipal Group";
refThree.contactNumber = "08044556677";
refThree.email = "info@manipal.com";
refThree.website = "www.manipalhospitals.com";
refThree.hasLaboratory = true;
refThree.hasRadiology = true;
refThree.hasOperationTheatre = true;
refThree.parkingCapacity = 180;
refThree.accreditation = "NABH";
refThree.speciality = "Neurology";


System.out.println("The hospitalId is: " + refThree.hospitalId);
System.out.println("The hospitalName is: " + refThree.hospitalName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfDoctors is: " + refThree.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refThree.numberOfNurses);
System.out.println("The numberOfBeds is: " + refThree.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refThree.hasEmergencyWard);
System.out.println("The hasICU is: " + refThree.hasICU);
System.out.println("The hasPharmacy is: " + refThree.hasPharmacy);
System.out.println("The hasAmbulance is: " + refThree.hasAmbulance);
System.out.println("The hospitalType is: " + refThree.hospitalType);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The ownerName is: " + refThree.ownerName);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The hasLaboratory is: " + refThree.hasLaboratory);
System.out.println("The hasRadiology is: " + refThree.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refThree.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refThree.parkingCapacity);
System.out.println("The accreditation is: " + refThree.accreditation);
System.out.println("The speciality is: " + refThree.speciality);
Hospital refFour = new Hospital();

System.out.println("The hospitalId is: " + refFour.hospitalId);
System.out.println("The hospitalName is: " + refFour.hospitalName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfDoctors is: " + refFour.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refFour.numberOfNurses);
System.out.println("The numberOfBeds is: " + refFour.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refFour.hasEmergencyWard);
System.out.println("The hasICU is: " + refFour.hasICU);
System.out.println("The hasPharmacy is: " + refFour.hasPharmacy);
System.out.println("The hasAmbulance is: " + refFour.hasAmbulance);
System.out.println("The hospitalType is: " + refFour.hospitalType);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The ownerName is: " + refFour.ownerName);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The hasLaboratory is: " + refFour.hasLaboratory);
System.out.println("The hasRadiology is: " + refFour.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refFour.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refFour.parkingCapacity);
System.out.println("The accreditation is: " + refFour.accreditation);
System.out.println("The speciality is: " + refFour.speciality);


refFour.hospitalId = 4;
refFour.hospitalName = "Columbia Asia Hospital";
refFour.location = "Hebbal";
refFour.city = "Bangalore";
refFour.state = "Karnataka";
refFour.country = "India";
refFour.numberOfDoctors = 160;
refFour.numberOfNurses = 280;
refFour.numberOfBeds = 350;
refFour.hasEmergencyWard = true;
refFour.hasICU = true;
refFour.hasPharmacy = true;
refFour.hasAmbulance = true;
refFour.hospitalType = "Private";
refFour.establishedYear = 2005;
refFour.ownerName = "Columbia Asia Group";
refFour.contactNumber = "08066778899";
refFour.email = "contact@columbiaasia.com";
refFour.website = "www.columbiaasia.com";
refFour.hasLaboratory = true;
refFour.hasRadiology = true;
refFour.hasOperationTheatre = true;
refFour.parkingCapacity = 120;
refFour.accreditation = "NABH";
refFour.speciality = "Orthopedics";


System.out.println("The hospitalId is: " + refFour.hospitalId);
System.out.println("The hospitalName is: " + refFour.hospitalName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfDoctors is: " + refFour.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refFour.numberOfNurses);
System.out.println("The numberOfBeds is: " + refFour.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refFour.hasEmergencyWard);
System.out.println("The hasICU is: " + refFour.hasICU);
System.out.println("The hasPharmacy is: " + refFour.hasPharmacy);
System.out.println("The hasAmbulance is: " + refFour.hasAmbulance);
System.out.println("The hospitalType is: " + refFour.hospitalType);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The ownerName is: " + refFour.ownerName);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The hasLaboratory is: " + refFour.hasLaboratory);
System.out.println("The hasRadiology is: " + refFour.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refFour.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refFour.parkingCapacity);
System.out.println("The accreditation is: " + refFour.accreditation);
System.out.println("The speciality is: " + refFour.speciality);
Hospital refFive = new Hospital();

System.out.println("The hospitalId is: " + refFive.hospitalId);
System.out.println("The hospitalName is: " + refFive.hospitalName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfDoctors is: " + refFive.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refFive.numberOfNurses);
System.out.println("The numberOfBeds is: " + refFive.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refFive.hasEmergencyWard);
System.out.println("The hasICU is: " + refFive.hasICU);
System.out.println("The hasPharmacy is: " + refFive.hasPharmacy);
System.out.println("The hasAmbulance is: " + refFive.hasAmbulance);
System.out.println("The hospitalType is: " + refFive.hospitalType);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The ownerName is: " + refFive.ownerName);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The hasLaboratory is: " + refFive.hasLaboratory);
System.out.println("The hasRadiology is: " + refFive.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refFive.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refFive.parkingCapacity);
System.out.println("The accreditation is: " + refFive.accreditation);
System.out.println("The speciality is: " + refFive.speciality);


refFive.hospitalId = 5;
refFive.hospitalName = "Narayana Health Hospital";
refFive.location = "Bommasandra";
refFive.city = "Bangalore";
refFive.state = "Karnataka";
refFive.country = "India";
refFive.numberOfDoctors = 300;
refFive.numberOfNurses = 500;
refFive.numberOfBeds = 800;
refFive.hasEmergencyWard = true;
refFive.hasICU = true;
refFive.hasPharmacy = true;
refFive.hasAmbulance = true;
refFive.hospitalType = "Private";
refFive.establishedYear = 2000;
refFive.ownerName = "Dr. Devi Shetty";
refFive.contactNumber = "08011223344";
refFive.email = "info@narayanahealth.org";
refFive.website = "www.narayanahealth.org";
refFive.hasLaboratory = true;
refFive.hasRadiology = true;
refFive.hasOperationTheatre = true;
refFive.parkingCapacity = 300;
refFive.accreditation = "NABH";
refFive.speciality = "Cardiac Care";


System.out.println("The hospitalId is: " + refFive.hospitalId);
System.out.println("The hospitalName is: " + refFive.hospitalName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfDoctors is: " + refFive.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refFive.numberOfNurses);
System.out.println("The numberOfBeds is: " + refFive.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refFive.hasEmergencyWard);
System.out.println("The hasICU is: " + refFive.hasICU);
System.out.println("The hasPharmacy is: " + refFive.hasPharmacy);
System.out.println("The hasAmbulance is: " + refFive.hasAmbulance);
System.out.println("The hospitalType is: " + refFive.hospitalType);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The ownerName is: " + refFive.ownerName);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The hasLaboratory is: " + refFive.hasLaboratory);
System.out.println("The hasRadiology is: " + refFive.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refFive.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refFive.parkingCapacity);
System.out.println("The accreditation is: " + refFive.accreditation);
System.out.println("The speciality is: " + refFive.speciality);
Hospital refSix = new Hospital();

System.out.println("The hospitalId is: " + refSix.hospitalId);
System.out.println("The hospitalName is: " + refSix.hospitalName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfDoctors is: " + refSix.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refSix.numberOfNurses);
System.out.println("The numberOfBeds is: " + refSix.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refSix.hasEmergencyWard);
System.out.println("The hasICU is: " + refSix.hasICU);
System.out.println("The hasPharmacy is: " + refSix.hasPharmacy);
System.out.println("The hasAmbulance is: " + refSix.hasAmbulance);
System.out.println("The hospitalType is: " + refSix.hospitalType);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The ownerName is: " + refSix.ownerName);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The hasLaboratory is: " + refSix.hasLaboratory);
System.out.println("The hasRadiology is: " + refSix.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refSix.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refSix.parkingCapacity);
System.out.println("The accreditation is: " + refSix.accreditation);
System.out.println("The speciality is: " + refSix.speciality);


refSix.hospitalId = 6;
refSix.hospitalName = "St. John's Medical College Hospital";
refSix.location = "Koramangala";
refSix.city = "Bangalore";
refSix.state = "Karnataka";
refSix.country = "India";
refSix.numberOfDoctors = 200;
refSix.numberOfNurses = 320;
refSix.numberOfBeds = 600;
refSix.hasEmergencyWard = true;
refSix.hasICU = true;
refSix.hasPharmacy = true;
refSix.hasAmbulance = true;
refSix.hospitalType = "Teaching Hospital";
refSix.establishedYear = 1963;
refSix.ownerName = "Catholic Bishops' Conference of India";
refSix.contactNumber = "08022334455";
refSix.email = "info@stjohns.in";
refSix.website = "www.stjohns.in";
refSix.hasLaboratory = true;
refSix.hasRadiology = true;
refSix.hasOperationTheatre = true;
refSix.parkingCapacity = 220;
refSix.accreditation = "NABH";
refSix.speciality = "General Medicine";


System.out.println("The hospitalId is: " + refSix.hospitalId);
System.out.println("The hospitalName is: " + refSix.hospitalName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfDoctors is: " + refSix.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refSix.numberOfNurses);
System.out.println("The numberOfBeds is: " + refSix.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refSix.hasEmergencyWard);
System.out.println("The hasICU is: " + refSix.hasICU);
System.out.println("The hasPharmacy is: " + refSix.hasPharmacy);
System.out.println("The hasAmbulance is: " + refSix.hasAmbulance);
System.out.println("The hospitalType is: " + refSix.hospitalType);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The ownerName is: " + refSix.ownerName);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The hasLaboratory is: " + refSix.hasLaboratory);
System.out.println("The hasRadiology is: " + refSix.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refSix.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refSix.parkingCapacity);
System.out.println("The accreditation is: " + refSix.accreditation);
System.out.println("The speciality is: " + refSix.speciality);
Hospital refSeven = new Hospital();

System.out.println("The hospitalId is: " + refSeven.hospitalId);
System.out.println("The hospitalName is: " + refSeven.hospitalName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfDoctors is: " + refSeven.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refSeven.numberOfNurses);
System.out.println("The numberOfBeds is: " + refSeven.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refSeven.hasEmergencyWard);
System.out.println("The hasICU is: " + refSeven.hasICU);
System.out.println("The hasPharmacy is: " + refSeven.hasPharmacy);
System.out.println("The hasAmbulance is: " + refSeven.hasAmbulance);
System.out.println("The hospitalType is: " + refSeven.hospitalType);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The ownerName is: " + refSeven.ownerName);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The hasLaboratory is: " + refSeven.hasLaboratory);
System.out.println("The hasRadiology is: " + refSeven.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refSeven.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refSeven.parkingCapacity);
System.out.println("The accreditation is: " + refSeven.accreditation);
System.out.println("The speciality is: " + refSeven.speciality);


refSeven.hospitalId = 7;
refSeven.hospitalName = "Aster CMI Hospital";
refSeven.location = "Hebbal";
refSeven.city = "Bangalore";
refSeven.state = "Karnataka";
refSeven.country = "India";
refSeven.numberOfDoctors = 210;
refSeven.numberOfNurses = 330;
refSeven.numberOfBeds = 450;
refSeven.hasEmergencyWard = true;
refSeven.hasICU = true;
refSeven.hasPharmacy = true;
refSeven.hasAmbulance = true;
refSeven.hospitalType = "Private";
refSeven.establishedYear = 2013;
refSeven.ownerName = "Aster DM Healthcare";
refSeven.contactNumber = "08055667788";
refSeven.email = "info@asterhospital.com";
refSeven.website = "www.asterhospitals.in";
refSeven.hasLaboratory = true;
refSeven.hasRadiology = true;
refSeven.hasOperationTheatre = true;
refSeven.parkingCapacity = 180;
refSeven.accreditation = "NABH";
refSeven.speciality = "Cardiology";


System.out.println("The hospitalId is: " + refSeven.hospitalId);
System.out.println("The hospitalName is: " + refSeven.hospitalName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfDoctors is: " + refSeven.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refSeven.numberOfNurses);
System.out.println("The numberOfBeds is: " + refSeven.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refSeven.hasEmergencyWard);
System.out.println("The hasICU is: " + refSeven.hasICU);
System.out.println("The hasPharmacy is: " + refSeven.hasPharmacy);
System.out.println("The hasAmbulance is: " + refSeven.hasAmbulance);
System.out.println("The hospitalType is: " + refSeven.hospitalType);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The ownerName is: " + refSeven.ownerName);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The hasLaboratory is: " + refSeven.hasLaboratory);
System.out.println("The hasRadiology is: " + refSeven.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refSeven.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refSeven.parkingCapacity);
System.out.println("The accreditation is: " + refSeven.accreditation);
System.out.println("The speciality is: " + refSeven.speciality);
Hospital refEight = new Hospital();

System.out.println("The hospitalId is: " + refEight.hospitalId);
System.out.println("The hospitalName is: " + refEight.hospitalName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfDoctors is: " + refEight.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refEight.numberOfNurses);
System.out.println("The numberOfBeds is: " + refEight.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refEight.hasEmergencyWard);
System.out.println("The hasICU is: " + refEight.hasICU);
System.out.println("The hasPharmacy is: " + refEight.hasPharmacy);
System.out.println("The hasAmbulance is: " + refEight.hasAmbulance);
System.out.println("The hospitalType is: " + refEight.hospitalType);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The ownerName is: " + refEight.ownerName);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The hasLaboratory is: " + refEight.hasLaboratory);
System.out.println("The hasRadiology is: " + refEight.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refEight.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refEight.parkingCapacity);
System.out.println("The accreditation is: " + refEight.accreditation);
System.out.println("The speciality is: " + refEight.speciality);


refEight.hospitalId = 8;
refEight.hospitalName = "Sakra World Hospital";
refEight.location = "Marathahalli";
refEight.city = "Bangalore";
refEight.state = "Karnataka";
refEight.country = "India";
refEight.numberOfDoctors = 190;
refEight.numberOfNurses = 300;
refEight.numberOfBeds = 400;
refEight.hasEmergencyWard = true;
refEight.hasICU = true;
refEight.hasPharmacy = true;
refEight.hasAmbulance = true;
refEight.hospitalType = "Private";
refEight.establishedYear = 2014;
refEight.ownerName = "Sakra Group";
refEight.contactNumber = "08077889966";
refEight.email = "info@sakrahospital.com";
refEight.website = "www.sakrahospital.com";
refEight.hasLaboratory = true;
refEight.hasRadiology = true;
refEight.hasOperationTheatre = true;
refEight.parkingCapacity = 160;
refEight.accreditation = "NABH";
refEight.speciality = "Orthopedics";


System.out.println("The hospitalId is: " + refEight.hospitalId);
System.out.println("The hospitalName is: " + refEight.hospitalName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfDoctors is: " + refEight.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refEight.numberOfNurses);
System.out.println("The numberOfBeds is: " + refEight.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refEight.hasEmergencyWard);
System.out.println("The hasICU is: " + refEight.hasICU);
System.out.println("The hasPharmacy is: " + refEight.hasPharmacy);
System.out.println("The hasAmbulance is: " + refEight.hasAmbulance);
System.out.println("The hospitalType is: " + refEight.hospitalType);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The ownerName is: " + refEight.ownerName);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The hasLaboratory is: " + refEight.hasLaboratory);
System.out.println("The hasRadiology is: " + refEight.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refEight.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refEight.parkingCapacity);
System.out.println("The accreditation is: " + refEight.accreditation);
System.out.println("The speciality is: " + refEight.speciality);
Hospital refNine = new Hospital();

System.out.println("The hospitalId is: " + refNine.hospitalId);
System.out.println("The hospitalName is: " + refNine.hospitalName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfDoctors is: " + refNine.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refNine.numberOfNurses);
System.out.println("The numberOfBeds is: " + refNine.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refNine.hasEmergencyWard);
System.out.println("The hasICU is: " + refNine.hasICU);
System.out.println("The hasPharmacy is: " + refNine.hasPharmacy);
System.out.println("The hasAmbulance is: " + refNine.hasAmbulance);
System.out.println("The hospitalType is: " + refNine.hospitalType);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The ownerName is: " + refNine.ownerName);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The hasLaboratory is: " + refNine.hasLaboratory);
System.out.println("The hasRadiology is: " + refNine.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refNine.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refNine.parkingCapacity);
System.out.println("The accreditation is: " + refNine.accreditation);
System.out.println("The speciality is: " + refNine.speciality);


refNine.hospitalId = 9;
refNine.hospitalName = "Rainbow Children's Hospital";
refNine.location = "Sarjapur Road";
refNine.city = "Bangalore";
refNine.state = "Karnataka";
refNine.country = "India";
refNine.numberOfDoctors = 140;
refNine.numberOfNurses = 250;
refNine.numberOfBeds = 300;
refNine.hasEmergencyWard = true;
refNine.hasICU = true;
refNine.hasPharmacy = true;
refNine.hasAmbulance = true;
refNine.hospitalType = "Private";
refNine.establishedYear = 2010;
refNine.ownerName = "Rainbow Hospitals Group";
refNine.contactNumber = "08088997766";
refNine.email = "info@rainbowhospitals.in";
refNine.website = "www.rainbowhospitals.in";
refNine.hasLaboratory = true;
refNine.hasRadiology = true;
refNine.hasOperationTheatre = true;
refNine.parkingCapacity = 130;
refNine.accreditation = "NABH";
refNine.speciality = "Pediatrics";


System.out.println("The hospitalId is: " + refNine.hospitalId);
System.out.println("The hospitalName is: " + refNine.hospitalName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfDoctors is: " + refNine.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refNine.numberOfNurses);
System.out.println("The numberOfBeds is: " + refNine.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refNine.hasEmergencyWard);
System.out.println("The hasICU is: " + refNine.hasICU);
System.out.println("The hasPharmacy is: " + refNine.hasPharmacy);
System.out.println("The hasAmbulance is: " + refNine.hasAmbulance);
System.out.println("The hospitalType is: " + refNine.hospitalType);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The ownerName is: " + refNine.ownerName);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The hasLaboratory is: " + refNine.hasLaboratory);
System.out.println("The hasRadiology is: " + refNine.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refNine.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refNine.parkingCapacity);
System.out.println("The accreditation is: " + refNine.accreditation);
System.out.println("The speciality is: " + refNine.speciality);
Hospital refTen = new Hospital();

System.out.println("The hospitalId is: " + refTen.hospitalId);
System.out.println("The hospitalName is: " + refTen.hospitalName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfDoctors is: " + refTen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refTen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refTen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refTen.hasEmergencyWard);
System.out.println("The hasICU is: " + refTen.hasICU);
System.out.println("The hasPharmacy is: " + refTen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refTen.hasAmbulance);
System.out.println("The hospitalType is: " + refTen.hospitalType);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The ownerName is: " + refTen.ownerName);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The hasLaboratory is: " + refTen.hasLaboratory);
System.out.println("The hasRadiology is: " + refTen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refTen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refTen.parkingCapacity);
System.out.println("The accreditation is: " + refTen.accreditation);
System.out.println("The speciality is: " + refTen.speciality);


refTen.hospitalId = 10;
refTen.hospitalName = "Victoria Hospital";
refTen.location = "KR Market";
refTen.city = "Bangalore";
refTen.state = "Karnataka";
refTen.country = "India";
refTen.numberOfDoctors = 170;
refTen.numberOfNurses = 290;
refTen.numberOfBeds = 550;
refTen.hasEmergencyWard = true;
refTen.hasICU = true;
refTen.hasPharmacy = true;
refTen.hasAmbulance = true;
refTen.hospitalType = "Government";
refTen.establishedYear = 1900;
refTen.ownerName = "Government of Karnataka";
refTen.contactNumber = "08033445566";
refTen.email = "info@victoriahospital.in";
refTen.website = "www.victoriahospital.in";
refTen.hasLaboratory = true;
refTen.hasRadiology = true;
refTen.hasOperationTheatre = true;
refTen.parkingCapacity = 250;
refTen.accreditation = "Government Approved";
refTen.speciality = "General Surgery";


System.out.println("The hospitalId is: " + refTen.hospitalId);
System.out.println("The hospitalName is: " + refTen.hospitalName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfDoctors is: " + refTen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refTen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refTen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refTen.hasEmergencyWard);
System.out.println("The hasICU is: " + refTen.hasICU);
System.out.println("The hasPharmacy is: " + refTen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refTen.hasAmbulance);
System.out.println("The hospitalType is: " + refTen.hospitalType);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The ownerName is: " + refTen.ownerName);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The hasLaboratory is: " + refTen.hasLaboratory);
System.out.println("The hasRadiology is: " + refTen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refTen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refTen.parkingCapacity);
System.out.println("The accreditation is: " + refTen.accreditation);
System.out.println("The speciality is: " + refTen.speciality);
Hospital refEleven = new Hospital();

System.out.println("The hospitalId is: " + refEleven.hospitalId);
System.out.println("The hospitalName is: " + refEleven.hospitalName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfDoctors is: " + refEleven.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refEleven.numberOfNurses);
System.out.println("The numberOfBeds is: " + refEleven.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refEleven.hasEmergencyWard);
System.out.println("The hasICU is: " + refEleven.hasICU);
System.out.println("The hasPharmacy is: " + refEleven.hasPharmacy);
System.out.println("The hasAmbulance is: " + refEleven.hasAmbulance);
System.out.println("The hospitalType is: " + refEleven.hospitalType);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The ownerName is: " + refEleven.ownerName);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The hasLaboratory is: " + refEleven.hasLaboratory);
System.out.println("The hasRadiology is: " + refEleven.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refEleven.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refEleven.parkingCapacity);
System.out.println("The accreditation is: " + refEleven.accreditation);
System.out.println("The speciality is: " + refEleven.speciality);


refEleven.hospitalId = 11;
refEleven.hospitalName = "Cloudnine Hospital";
refEleven.location = "Jayanagar";
refEleven.city = "Bangalore";
refEleven.state = "Karnataka";
refEleven.country = "India";
refEleven.numberOfDoctors = 120;
refEleven.numberOfNurses = 210;
refEleven.numberOfBeds = 250;
refEleven.hasEmergencyWard = true;
refEleven.hasICU = true;
refEleven.hasPharmacy = true;
refEleven.hasAmbulance = true;
refEleven.hospitalType = "Private";
refEleven.establishedYear = 2007;
refEleven.ownerName = "Cloudnine Group";
refEleven.contactNumber = "08099887766";
refEleven.email = "info@cloudninecare.com";
refEleven.website = "www.cloudninecare.com";
refEleven.hasLaboratory = true;
refEleven.hasRadiology = true;
refEleven.hasOperationTheatre = true;
refEleven.parkingCapacity = 110;
refEleven.accreditation = "NABH";
refEleven.speciality = "Maternity";


System.out.println("The hospitalId is: " + refEleven.hospitalId);
System.out.println("The hospitalName is: " + refEleven.hospitalName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfDoctors is: " + refEleven.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refEleven.numberOfNurses);
System.out.println("The numberOfBeds is: " + refEleven.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refEleven.hasEmergencyWard);
System.out.println("The hasICU is: " + refEleven.hasICU);
System.out.println("The hasPharmacy is: " + refEleven.hasPharmacy);
System.out.println("The hasAmbulance is: " + refEleven.hasAmbulance);
System.out.println("The hospitalType is: " + refEleven.hospitalType);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The ownerName is: " + refEleven.ownerName);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The hasLaboratory is: " + refEleven.hasLaboratory);
System.out.println("The hasRadiology is: " + refEleven.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refEleven.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refEleven.parkingCapacity);
System.out.println("The accreditation is: " + refEleven.accreditation);
System.out.println("The speciality is: " + refEleven.speciality);
Hospital refTwelve = new Hospital();

System.out.println("The hospitalId is: " + refTwelve.hospitalId);
System.out.println("The hospitalName is: " + refTwelve.hospitalName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfDoctors is: " + refTwelve.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refTwelve.numberOfNurses);
System.out.println("The numberOfBeds is: " + refTwelve.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refTwelve.hasEmergencyWard);
System.out.println("The hasICU is: " + refTwelve.hasICU);
System.out.println("The hasPharmacy is: " + refTwelve.hasPharmacy);
System.out.println("The hasAmbulance is: " + refTwelve.hasAmbulance);
System.out.println("The hospitalType is: " + refTwelve.hospitalType);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The ownerName is: " + refTwelve.ownerName);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The hasLaboratory is: " + refTwelve.hasLaboratory);
System.out.println("The hasRadiology is: " + refTwelve.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refTwelve.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refTwelve.parkingCapacity);
System.out.println("The accreditation is: " + refTwelve.accreditation);
System.out.println("The speciality is: " + refTwelve.speciality);


refTwelve.hospitalId = 12;
refTwelve.hospitalName = "BGS Global Hospital";
refTwelve.location = "Kengeri";
refTwelve.city = "Bangalore";
refTwelve.state = "Karnataka";
refTwelve.country = "India";
refTwelve.numberOfDoctors = 175;
refTwelve.numberOfNurses = 295;
refTwelve.numberOfBeds = 420;
refTwelve.hasEmergencyWard = true;
refTwelve.hasICU = true;
refTwelve.hasPharmacy = true;
refTwelve.hasAmbulance = true;
refTwelve.hospitalType = "Private";
refTwelve.establishedYear = 2007;
refTwelve.ownerName = "BGS Group";
refTwelve.contactNumber = "08066554433";
refTwelve.email = "info@bgshospital.com";
refTwelve.website = "www.bgsglobalhospital.com";
refTwelve.hasLaboratory = true;
refTwelve.hasRadiology = true;
refTwelve.hasOperationTheatre = true;
refTwelve.parkingCapacity = 170;
refTwelve.accreditation = "NABH";
refTwelve.speciality = "Gastroenterology";


System.out.println("The hospitalId is: " + refTwelve.hospitalId);
System.out.println("The hospitalName is: " + refTwelve.hospitalName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfDoctors is: " + refTwelve.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refTwelve.numberOfNurses);
System.out.println("The numberOfBeds is: " + refTwelve.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refTwelve.hasEmergencyWard);
System.out.println("The hasICU is: " + refTwelve.hasICU);
System.out.println("The hasPharmacy is: " + refTwelve.hasPharmacy);
System.out.println("The hasAmbulance is: " + refTwelve.hasAmbulance);
System.out.println("The hospitalType is: " + refTwelve.hospitalType);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The ownerName is: " + refTwelve.ownerName);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The hasLaboratory is: " + refTwelve.hasLaboratory);
System.out.println("The hasRadiology is: " + refTwelve.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refTwelve.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refTwelve.parkingCapacity);
System.out.println("The accreditation is: " + refTwelve.accreditation);
System.out.println("The speciality is: " + refTwelve.speciality);
Hospital refThirteen = new Hospital();

System.out.println("The hospitalId is: " + refThirteen.hospitalId);
System.out.println("The hospitalName is: " + refThirteen.hospitalName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfDoctors is: " + refThirteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refThirteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refThirteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refThirteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refThirteen.hasICU);
System.out.println("The hasPharmacy is: " + refThirteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refThirteen.hasAmbulance);
System.out.println("The hospitalType is: " + refThirteen.hospitalType);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The ownerName is: " + refThirteen.ownerName);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The hasLaboratory is: " + refThirteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refThirteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refThirteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refThirteen.parkingCapacity);
System.out.println("The accreditation is: " + refThirteen.accreditation);
System.out.println("The speciality is: " + refThirteen.speciality);


refThirteen.hospitalId = 13;
refThirteen.hospitalName = "Sri Jayadeva Institute of Cardiology";
refThirteen.location = "Jayanagar";
refThirteen.city = "Bangalore";
refThirteen.state = "Karnataka";
refThirteen.country = "India";
refThirteen.numberOfDoctors = 210;
refThirteen.numberOfNurses = 350;
refThirteen.numberOfBeds = 700;
refThirteen.hasEmergencyWard = true;
refThirteen.hasICU = true;
refThirteen.hasPharmacy = true;
refThirteen.hasAmbulance = true;
refThirteen.hospitalType = "Government";
refThirteen.establishedYear = 1975;
refThirteen.ownerName = "Government of Karnataka";
refThirteen.contactNumber = "08044443333";
refThirteen.email = "info@jayadevahospital.in";
refThirteen.website = "www.jayadevahospital.in";
refThirteen.hasLaboratory = true;
refThirteen.hasRadiology = true;
refThirteen.hasOperationTheatre = true;
refThirteen.parkingCapacity = 220;
refThirteen.accreditation = "Government Approved";
refThirteen.speciality = "Cardiology";


System.out.println("The hospitalId is: " + refThirteen.hospitalId);
System.out.println("The hospitalName is: " + refThirteen.hospitalName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfDoctors is: " + refThirteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refThirteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refThirteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refThirteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refThirteen.hasICU);
System.out.println("The hasPharmacy is: " + refThirteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refThirteen.hasAmbulance);
System.out.println("The hospitalType is: " + refThirteen.hospitalType);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The ownerName is: " + refThirteen.ownerName);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The hasLaboratory is: " + refThirteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refThirteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refThirteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refThirteen.parkingCapacity);
System.out.println("The accreditation is: " + refThirteen.accreditation);
System.out.println("The speciality is: " + refThirteen.speciality);
Hospital refFourteen = new Hospital();

System.out.println("The hospitalId is: " + refFourteen.hospitalId);
System.out.println("The hospitalName is: " + refFourteen.hospitalName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfDoctors is: " + refFourteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refFourteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refFourteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refFourteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refFourteen.hasICU);
System.out.println("The hasPharmacy is: " + refFourteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refFourteen.hasAmbulance);
System.out.println("The hospitalType is: " + refFourteen.hospitalType);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The ownerName is: " + refFourteen.ownerName);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The hasLaboratory is: " + refFourteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refFourteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refFourteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refFourteen.parkingCapacity);
System.out.println("The accreditation is: " + refFourteen.accreditation);
System.out.println("The speciality is: " + refFourteen.speciality);


refFourteen.hospitalId = 14;
refFourteen.hospitalName = "Bowring and Lady Curzon Hospital";
refFourteen.location = "Shivajinagar";
refFourteen.city = "Bangalore";
refFourteen.state = "Karnataka";
refFourteen.country = "India";
refFourteen.numberOfDoctors = 150;
refFourteen.numberOfNurses = 270;
refFourteen.numberOfBeds = 500;
refFourteen.hasEmergencyWard = true;
refFourteen.hasICU = true;
refFourteen.hasPharmacy = true;
refFourteen.hasAmbulance = true;
refFourteen.hospitalType = "Government";
refFourteen.establishedYear = 1867;
refFourteen.ownerName = "Government of Karnataka";
refFourteen.contactNumber = "08022112233";
refFourteen.email = "info@bowringhospital.in";
refFourteen.website = "www.bowringhospital.in";
refFourteen.hasLaboratory = true;
refFourteen.hasRadiology = true;
refFourteen.hasOperationTheatre = true;
refFourteen.parkingCapacity = 200;
refFourteen.accreditation = "Government Approved";
refFourteen.speciality = "General Medicine";


System.out.println("The hospitalId is: " + refFourteen.hospitalId);
System.out.println("The hospitalName is: " + refFourteen.hospitalName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfDoctors is: " + refFourteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refFourteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refFourteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refFourteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refFourteen.hasICU);
System.out.println("The hasPharmacy is: " + refFourteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refFourteen.hasAmbulance);
System.out.println("The hospitalType is: " + refFourteen.hospitalType);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The ownerName is: " + refFourteen.ownerName);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The hasLaboratory is: " + refFourteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refFourteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refFourteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refFourteen.parkingCapacity);
System.out.println("The accreditation is: " + refFourteen.accreditation);
System.out.println("The speciality is: " + refFourteen.speciality);
Hospital refFifteen = new Hospital();

System.out.println("The hospitalId is: " + refFifteen.hospitalId);
System.out.println("The hospitalName is: " + refFifteen.hospitalName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfDoctors is: " + refFifteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refFifteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refFifteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refFifteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refFifteen.hasICU);
System.out.println("The hasPharmacy is: " + refFifteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refFifteen.hasAmbulance);
System.out.println("The hospitalType is: " + refFifteen.hospitalType);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The ownerName is: " + refFifteen.ownerName);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The hasLaboratory is: " + refFifteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refFifteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refFifteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refFifteen.parkingCapacity);
System.out.println("The accreditation is: " + refFifteen.accreditation);
System.out.println("The speciality is: " + refFifteen.speciality);


refFifteen.hospitalId = 15;
refFifteen.hospitalName = "Mallya Hospital";
refFifteen.location = "Vittal Mallya Road";
refFifteen.city = "Bangalore";
refFifteen.state = "Karnataka";
refFifteen.country = "India";
refFifteen.numberOfDoctors = 130;
refFifteen.numberOfNurses = 240;
refFifteen.numberOfBeds = 320;
refFifteen.hasEmergencyWard = true;
refFifteen.hasICU = true;
refFifteen.hasPharmacy = true;
refFifteen.hasAmbulance = true;
refFifteen.hospitalType = "Private";
refFifteen.establishedYear = 1991;
refFifteen.ownerName = "Mallya Group";
refFifteen.contactNumber = "08044551234";
refFifteen.email = "info@mallyahospital.in";
refFifteen.website = "www.mallyahospital.in";
refFifteen.hasLaboratory = true;
refFifteen.hasRadiology = true;
refFifteen.hasOperationTheatre = true;
refFifteen.parkingCapacity = 140;
refFifteen.accreditation = "NABH";
refFifteen.speciality = "Multi Speciality";


System.out.println("The hospitalId is: " + refFifteen.hospitalId);
System.out.println("The hospitalName is: " + refFifteen.hospitalName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfDoctors is: " + refFifteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refFifteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refFifteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refFifteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refFifteen.hasICU);
System.out.println("The hasPharmacy is: " + refFifteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refFifteen.hasAmbulance);
System.out.println("The hospitalType is: " + refFifteen.hospitalType);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The ownerName is: " + refFifteen.ownerName);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The hasLaboratory is: " + refFifteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refFifteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refFifteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refFifteen.parkingCapacity);
System.out.println("The accreditation is: " + refFifteen.accreditation);
System.out.println("The speciality is: " + refFifteen.speciality);
Hospital refSixteen = new Hospital();

System.out.println("The hospitalId is: " + refSixteen.hospitalId);
System.out.println("The hospitalName is: " + refSixteen.hospitalName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfDoctors is: " + refSixteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refSixteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refSixteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refSixteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refSixteen.hasICU);
System.out.println("The hasPharmacy is: " + refSixteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refSixteen.hasAmbulance);
System.out.println("The hospitalType is: " + refSixteen.hospitalType);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The ownerName is: " + refSixteen.ownerName);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The hasLaboratory is: " + refSixteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refSixteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refSixteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refSixteen.parkingCapacity);
System.out.println("The accreditation is: " + refSixteen.accreditation);
System.out.println("The speciality is: " + refSixteen.speciality);


refSixteen.hospitalId = 16;
refSixteen.hospitalName = "People Tree Hospital";
refSixteen.location = "Yeshwanthpur";
refSixteen.city = "Bangalore";
refSixteen.state = "Karnataka";
refSixteen.country = "India";
refSixteen.numberOfDoctors = 110;
refSixteen.numberOfNurses = 200;
refSixteen.numberOfBeds = 280;
refSixteen.hasEmergencyWard = true;
refSixteen.hasICU = true;
refSixteen.hasPharmacy = true;
refSixteen.hasAmbulance = true;
refSixteen.hospitalType = "Private";
refSixteen.establishedYear = 2013;
refSixteen.ownerName = "People Tree Group";
refSixteen.contactNumber = "08055664422";
refSixteen.email = "info@peopletreehospitals.com";
refSixteen.website = "www.peopletreehospitals.com";
refSixteen.hasLaboratory = true;
refSixteen.hasRadiology = true;
refSixteen.hasOperationTheatre = true;
refSixteen.parkingCapacity = 120;
refSixteen.accreditation = "NABH";
refSixteen.speciality = "General Surgery";


System.out.println("The hospitalId is: " + refSixteen.hospitalId);
System.out.println("The hospitalName is: " + refSixteen.hospitalName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfDoctors is: " + refSixteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refSixteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refSixteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refSixteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refSixteen.hasICU);
System.out.println("The hasPharmacy is: " + refSixteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refSixteen.hasAmbulance);
System.out.println("The hospitalType is: " + refSixteen.hospitalType);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The ownerName is: " + refSixteen.ownerName);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The hasLaboratory is: " + refSixteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refSixteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refSixteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refSixteen.parkingCapacity);
System.out.println("The accreditation is: " + refSixteen.accreditation);
System.out.println("The speciality is: " + refSixteen.speciality);
Hospital refSeventeen = new Hospital();

System.out.println("The hospitalId is: " + refSeventeen.hospitalId);
System.out.println("The hospitalName is: " + refSeventeen.hospitalName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfDoctors is: " + refSeventeen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refSeventeen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refSeventeen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refSeventeen.hasEmergencyWard);
System.out.println("The hasICU is: " + refSeventeen.hasICU);
System.out.println("The hasPharmacy is: " + refSeventeen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refSeventeen.hasAmbulance);
System.out.println("The hospitalType is: " + refSeventeen.hospitalType);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The hasLaboratory is: " + refSeventeen.hasLaboratory);
System.out.println("The hasRadiology is: " + refSeventeen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refSeventeen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refSeventeen.parkingCapacity);
System.out.println("The accreditation is: " + refSeventeen.accreditation);
System.out.println("The speciality is: " + refSeventeen.speciality);


refSeventeen.hospitalId = 17;
refSeventeen.hospitalName = "Ramaiah Memorial Hospital";
refSeventeen.location = "MSR Nagar";
refSeventeen.city = "Bangalore";
refSeventeen.state = "Karnataka";
refSeventeen.country = "India";
refSeventeen.numberOfDoctors = 190;
refSeventeen.numberOfNurses = 310;
refSeventeen.numberOfBeds = 420;
refSeventeen.hasEmergencyWard = true;
refSeventeen.hasICU = true;
refSeventeen.hasPharmacy = true;
refSeventeen.hasAmbulance = true;
refSeventeen.hospitalType = "Teaching Hospital";
refSeventeen.establishedYear = 1985;
refSeventeen.ownerName = "Ramaiah Group";
refSeventeen.contactNumber = "08066775544";
refSeventeen.email = "info@ramaiahhospital.in";
refSeventeen.website = "www.ramaiahhospital.in";
refSeventeen.hasLaboratory = true;
refSeventeen.hasRadiology = true;
refSeventeen.hasOperationTheatre = true;
refSeventeen.parkingCapacity = 180;
refSeventeen.accreditation = "NABH";
refSeventeen.speciality = "Multi Speciality";


System.out.println("The hospitalId is: " + refSeventeen.hospitalId);
System.out.println("The hospitalName is: " + refSeventeen.hospitalName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfDoctors is: " + refSeventeen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refSeventeen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refSeventeen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refSeventeen.hasEmergencyWard);
System.out.println("The hasICU is: " + refSeventeen.hasICU);
System.out.println("The hasPharmacy is: " + refSeventeen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refSeventeen.hasAmbulance);
System.out.println("The hospitalType is: " + refSeventeen.hospitalType);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The hasLaboratory is: " + refSeventeen.hasLaboratory);
System.out.println("The hasRadiology is: " + refSeventeen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refSeventeen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refSeventeen.parkingCapacity);
System.out.println("The accreditation is: " + refSeventeen.accreditation);
System.out.println("The speciality is: " + refSeventeen.speciality);
Hospital refEighteen = new Hospital();

System.out.println("The hospitalId is: " + refEighteen.hospitalId);
System.out.println("The hospitalName is: " + refEighteen.hospitalName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfDoctors is: " + refEighteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refEighteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refEighteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refEighteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refEighteen.hasICU);
System.out.println("The hasPharmacy is: " + refEighteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refEighteen.hasAmbulance);
System.out.println("The hospitalType is: " + refEighteen.hospitalType);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The ownerName is: " + refEighteen.ownerName);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The hasLaboratory is: " + refEighteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refEighteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refEighteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refEighteen.parkingCapacity);
System.out.println("The accreditation is: " + refEighteen.accreditation);
System.out.println("The speciality is: " + refEighteen.speciality);


refEighteen.hospitalId = 18;
refEighteen.hospitalName = "Kidwai Memorial Institute of Oncology";
refEighteen.location = "Hosakerehalli";
refEighteen.city = "Bangalore";
refEighteen.state = "Karnataka";
refEighteen.country = "India";
refEighteen.numberOfDoctors = 160;
refEighteen.numberOfNurses = 280;
refEighteen.numberOfBeds = 450;
refEighteen.hasEmergencyWard = true;
refEighteen.hasICU = true;
refEighteen.hasPharmacy = true;
refEighteen.hasAmbulance = true;
refEighteen.hospitalType = "Government";
refEighteen.establishedYear = 1973;
refEighteen.ownerName = "Government of Karnataka";
refEighteen.contactNumber = "08077886655";
refEighteen.email = "info@kidwai.karnataka.gov.in";
refEighteen.website = "www.kidwai.karnataka.gov.in";
refEighteen.hasLaboratory = true;
refEighteen.hasRadiology = true;
refEighteen.hasOperationTheatre = true;
refEighteen.parkingCapacity = 210;
refEighteen.accreditation = "Government Approved";
refEighteen.speciality = "Oncology";


System.out.println("The hospitalId is: " + refEighteen.hospitalId);
System.out.println("The hospitalName is: " + refEighteen.hospitalName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfDoctors is: " + refEighteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refEighteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refEighteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refEighteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refEighteen.hasICU);
System.out.println("The hasPharmacy is: " + refEighteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refEighteen.hasAmbulance);
System.out.println("The hospitalType is: " + refEighteen.hospitalType);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The ownerName is: " + refEighteen.ownerName);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The hasLaboratory is: " + refEighteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refEighteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refEighteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refEighteen.parkingCapacity);
System.out.println("The accreditation is: " + refEighteen.accreditation);
System.out.println("The speciality is: " + refEighteen.speciality);
Hospital refNineteen = new Hospital();

System.out.println("The hospitalId is: " + refNineteen.hospitalId);
System.out.println("The hospitalName is: " + refNineteen.hospitalName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfDoctors is: " + refNineteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refNineteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refNineteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refNineteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refNineteen.hasICU);
System.out.println("The hasPharmacy is: " + refNineteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refNineteen.hasAmbulance);
System.out.println("The hospitalType is: " + refNineteen.hospitalType);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The ownerName is: " + refNineteen.ownerName);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The hasLaboratory is: " + refNineteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refNineteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refNineteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refNineteen.parkingCapacity);
System.out.println("The accreditation is: " + refNineteen.accreditation);
System.out.println("The speciality is: " + refNineteen.speciality);


refNineteen.hospitalId = 19;
refNineteen.hospitalName = "Bangalore Baptist Hospital";
refNineteen.location = "Bellary Road";
refNineteen.city = "Bangalore";
refNineteen.state = "Karnataka";
refNineteen.country = "India";
refNineteen.numberOfDoctors = 140;
refNineteen.numberOfNurses = 260;
refNineteen.numberOfBeds = 350;
refNineteen.hasEmergencyWard = true;
refNineteen.hasICU = true;
refNineteen.hasPharmacy = true;
refNineteen.hasAmbulance = true;
refNineteen.hospitalType = "Private";
refNineteen.establishedYear = 1973;
refNineteen.ownerName = "Baptist Church";
refNineteen.contactNumber = "08033442211";
refNineteen.email = "info@bbh.org.in";
refNineteen.website = "www.bbh.org.in";
refNineteen.hasLaboratory = true;
refNineteen.hasRadiology = true;
refNineteen.hasOperationTheatre = true;
refNineteen.parkingCapacity = 150;
refNineteen.accreditation = "NABH";
refNineteen.speciality = "Multi Speciality";


System.out.println("The hospitalId is: " + refNineteen.hospitalId);
System.out.println("The hospitalName is: " + refNineteen.hospitalName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfDoctors is: " + refNineteen.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refNineteen.numberOfNurses);
System.out.println("The numberOfBeds is: " + refNineteen.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refNineteen.hasEmergencyWard);
System.out.println("The hasICU is: " + refNineteen.hasICU);
System.out.println("The hasPharmacy is: " + refNineteen.hasPharmacy);
System.out.println("The hasAmbulance is: " + refNineteen.hasAmbulance);
System.out.println("The hospitalType is: " + refNineteen.hospitalType);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The ownerName is: " + refNineteen.ownerName);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The hasLaboratory is: " + refNineteen.hasLaboratory);
System.out.println("The hasRadiology is: " + refNineteen.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refNineteen.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refNineteen.parkingCapacity);
System.out.println("The accreditation is: " + refNineteen.accreditation);
System.out.println("The speciality is: " + refNineteen.speciality);
Hospital refTwenty = new Hospital();

System.out.println("The hospitalId is: " + refTwenty.hospitalId);
System.out.println("The hospitalName is: " + refTwenty.hospitalName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfDoctors is: " + refTwenty.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refTwenty.numberOfNurses);
System.out.println("The numberOfBeds is: " + refTwenty.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refTwenty.hasEmergencyWard);
System.out.println("The hasICU is: " + refTwenty.hasICU);
System.out.println("The hasPharmacy is: " + refTwenty.hasPharmacy);
System.out.println("The hasAmbulance is: " + refTwenty.hasAmbulance);
System.out.println("The hospitalType is: " + refTwenty.hospitalType);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The ownerName is: " + refTwenty.ownerName);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The hasLaboratory is: " + refTwenty.hasLaboratory);
System.out.println("The hasRadiology is: " + refTwenty.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refTwenty.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refTwenty.parkingCapacity);
System.out.println("The accreditation is: " + refTwenty.accreditation);
System.out.println("The speciality is: " + refTwenty.speciality);


refTwenty.hospitalId = 20;
refTwenty.hospitalName = "Apollo Speciality Hospital";
refTwenty.location = "Bannerghatta Road";
refTwenty.city = "Bangalore";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.numberOfDoctors = 240;
refTwenty.numberOfNurses = 380;
refTwenty.numberOfBeds = 500;
refTwenty.hasEmergencyWard = true;
refTwenty.hasICU = true;
refTwenty.hasPharmacy = true;
refTwenty.hasAmbulance = true;
refTwenty.hospitalType = "Private";
refTwenty.establishedYear = 2007;
refTwenty.ownerName = "Apollo Hospitals Group";
refTwenty.contactNumber = "08044556677";
refTwenty.email = "info@apollohospitals.com";
refTwenty.website = "www.apollohospitals.com";
refTwenty.hasLaboratory = true;
refTwenty.hasRadiology = true;
refTwenty.hasOperationTheatre = true;
refTwenty.parkingCapacity = 220;
refTwenty.accreditation = "NABH";
refTwenty.speciality = "Multi Speciality";


System.out.println("The hospitalId is: " + refTwenty.hospitalId);
System.out.println("The hospitalName is: " + refTwenty.hospitalName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfDoctors is: " + refTwenty.numberOfDoctors);
System.out.println("The numberOfNurses is: " + refTwenty.numberOfNurses);
System.out.println("The numberOfBeds is: " + refTwenty.numberOfBeds);
System.out.println("The hasEmergencyWard is: " + refTwenty.hasEmergencyWard);
System.out.println("The hasICU is: " + refTwenty.hasICU);
System.out.println("The hasPharmacy is: " + refTwenty.hasPharmacy);
System.out.println("The hasAmbulance is: " + refTwenty.hasAmbulance);
System.out.println("The hospitalType is: " + refTwenty.hospitalType);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The ownerName is: " + refTwenty.ownerName);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The hasLaboratory is: " + refTwenty.hasLaboratory);
System.out.println("The hasRadiology is: " + refTwenty.hasRadiology);
System.out.println("The hasOperationTheatre is: " + refTwenty.hasOperationTheatre);
System.out.println("The parkingCapacity is: " + refTwenty.parkingCapacity);
System.out.println("The accreditation is: " + refTwenty.accreditation);
System.out.println("The speciality is: " + refTwenty.speciality);
}
}