class HotelChainExecutor{
public static void main(String[] args){
// Step 1: Create an object of HotelChain
HotelChain refOne = new HotelChain();

// Step 2: Print default values
System.out.println("The chainId is: " + refOne.chainId);
System.out.println("The chainName is: " + refOne.chainName);
System.out.println("The ceoName is: " + refOne.ceoName);
System.out.println("The headquartersLocation is: " + refOne.headquartersLocation);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfHotels is: " + refOne.numberOfHotels);
System.out.println("The totalRooms is: " + refOne.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refOne.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refOne.hasBudgetHotels);
System.out.println("The hasResorts is: " + refOne.hasResorts);
System.out.println("The hasRestaurants is: " + refOne.hasRestaurants);
System.out.println("The hasSpas is: " + refOne.hasSpas);
System.out.println("The hasSwimmingPools is: " + refOne.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refOne.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refOne.hasParkingFacilities);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasGym is: " + refOne.hasGym);
System.out.println("The hasLaundryService is: " + refOne.hasLaundryService);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The chainType is: " + refOne.chainType);

// Step 3: Assign meaningful values
refOne.chainId = 1;
refOne.chainName = "GrandStay Hotels";
refOne.ceoName = "Rohit Sharma";
refOne.headquartersLocation = "MG Road";
refOne.city = "Bengaluru";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfHotels = 15;
refOne.totalRooms = 1200;
refOne.hasLuxuryHotels = true;
refOne.hasBudgetHotels = true;
refOne.hasResorts = true;
refOne.hasRestaurants = true;
refOne.hasSpas = true;
refOne.hasSwimmingPools = true;
refOne.hasConferenceHalls = true;
refOne.hasParkingFacilities = true;
refOne.hasWifi = true;
refOne.hasGym = true;
refOne.hasLaundryService = true;
refOne.contactNumber = "9876543210";
refOne.email = "info@grandstay.com";
refOne.website = "www.grandstay.com";
refOne.establishedYear = 2005;
refOne.chainType = "Luxury & Business";

// Step 4: Print assigned values
System.out.println("\nAfter assigning values:");
System.out.println("The chainId is: " + refOne.chainId);
System.out.println("The chainName is: " + refOne.chainName);
System.out.println("The ceoName is: " + refOne.ceoName);
System.out.println("The headquartersLocation is: " + refOne.headquartersLocation);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfHotels is: " + refOne.numberOfHotels);
System.out.println("The totalRooms is: " + refOne.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refOne.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refOne.hasBudgetHotels);
System.out.println("The hasResorts is: " + refOne.hasResorts);
System.out.println("The hasRestaurants is: " + refOne.hasRestaurants);
System.out.println("The hasSpas is: " + refOne.hasSpas);
System.out.println("The hasSwimmingPools is: " + refOne.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refOne.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refOne.hasParkingFacilities);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasGym is: " + refOne.hasGym);
System.out.println("The hasLaundryService is: " + refOne.hasLaundryService);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The chainType is: " + refOne.chainType);
HotelChain refTwo = new HotelChain();

System.out.println("The chainId is: " + refTwo.chainId);
System.out.println("The chainName is: " + refTwo.chainName);
System.out.println("The ceoName is: " + refTwo.ceoName);
System.out.println("The headquartersLocation is: " + refTwo.headquartersLocation);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfHotels is: " + refTwo.numberOfHotels);
System.out.println("The totalRooms is: " + refTwo.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refTwo.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refTwo.hasBudgetHotels);
System.out.println("The hasResorts is: " + refTwo.hasResorts);
System.out.println("The hasRestaurants is: " + refTwo.hasRestaurants);
System.out.println("The hasSpas is: " + refTwo.hasSpas);
System.out.println("The hasSwimmingPools is: " + refTwo.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refTwo.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refTwo.hasParkingFacilities);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasGym is: " + refTwo.hasGym);
System.out.println("The hasLaundryService is: " + refTwo.hasLaundryService);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The chainType is: " + refTwo.chainType);

refTwo.chainId = 2;
refTwo.chainName = "Skyline Hotels";
refTwo.ceoName = "Anita Deshmukh";
refTwo.headquartersLocation = "Connaught Place";
refTwo.city = "New Delhi";
refTwo.state = "Delhi";
refTwo.country = "India";
refTwo.numberOfHotels = 20;
refTwo.totalRooms = 1800;
refTwo.hasLuxuryHotels = true;
refTwo.hasBudgetHotels = true;
refTwo.hasResorts = false;
refTwo.hasRestaurants = true;
refTwo.hasSpas = true;
refTwo.hasSwimmingPools = true;
refTwo.hasConferenceHalls = true;
refTwo.hasParkingFacilities = true;
refTwo.hasWifi = true;
refTwo.hasGym = true;
refTwo.hasLaundryService = true;
refTwo.contactNumber = "9123456780";
refTwo.email = "contact@skylinehotels.com";
refTwo.website = "www.skylinehotels.com";
refTwo.establishedYear = 2010;
refTwo.chainType = "Luxury & Business";

System.out.println("The chainId is: " + refTwo.chainId);
System.out.println("The chainName is: " + refTwo.chainName);
System.out.println("The ceoName is: " + refTwo.ceoName);
System.out.println("The headquartersLocation is: " + refTwo.headquartersLocation);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfHotels is: " + refTwo.numberOfHotels);
System.out.println("The totalRooms is: " + refTwo.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refTwo.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refTwo.hasBudgetHotels);
System.out.println("The hasResorts is: " + refTwo.hasResorts);
System.out.println("The hasRestaurants is: " + refTwo.hasRestaurants);
System.out.println("The hasSpas is: " + refTwo.hasSpas);
System.out.println("The hasSwimmingPools is: " + refTwo.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refTwo.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refTwo.hasParkingFacilities);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasGym is: " + refTwo.hasGym);
System.out.println("The hasLaundryService is: " + refTwo.hasLaundryService);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The chainType is: " + refTwo.chainType);
HotelChain refThree = new HotelChain();

System.out.println("The chainId is: " + refThree.chainId);
System.out.println("The chainName is: " + refThree.chainName);
System.out.println("The ceoName is: " + refThree.ceoName);
System.out.println("The headquartersLocation is: " + refThree.headquartersLocation);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfHotels is: " + refThree.numberOfHotels);
System.out.println("The totalRooms is: " + refThree.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refThree.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refThree.hasBudgetHotels);
System.out.println("The hasResorts is: " + refThree.hasResorts);
System.out.println("The hasRestaurants is: " + refThree.hasRestaurants);
System.out.println("The hasSpas is: " + refThree.hasSpas);
System.out.println("The hasSwimmingPools is: " + refThree.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refThree.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refThree.hasParkingFacilities);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasGym is: " + refThree.hasGym);
System.out.println("The hasLaundryService is: " + refThree.hasLaundryService);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The chainType is: " + refThree.chainType);

refThree.chainId = 3;
refThree.chainName = "Oceanic Resorts";
refThree.ceoName = "Priya Nair";
refThree.headquartersLocation = "Marine Drive";
refThree.city = "Mumbai";
refThree.state = "Maharashtra";
refThree.country = "India";
refThree.numberOfHotels = 12;
refThree.totalRooms = 900;
refThree.hasLuxuryHotels = true;
refThree.hasBudgetHotels = false;
refThree.hasResorts = true;
refThree.hasRestaurants = true;
refThree.hasSpas = true;
refThree.hasSwimmingPools = true;
refThree.hasConferenceHalls = true;
refThree.hasParkingFacilities = true;
refThree.hasWifi = true;
refThree.hasGym = true;
refThree.hasLaundryService = true;
refThree.contactNumber = "9988776655";
refThree.email = "info@oceanicresorts.com";
refThree.website = "www.oceanicresorts.com";
refThree.establishedYear = 2012;
refThree.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refThree.chainId);
System.out.println("The chainName is: " + refThree.chainName);
System.out.println("The ceoName is: " + refThree.ceoName);
System.out.println("The headquartersLocation is: " + refThree.headquartersLocation);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfHotels is: " + refThree.numberOfHotels);
System.out.println("The totalRooms is: " + refThree.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refThree.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refThree.hasBudgetHotels);
System.out.println("The hasResorts is: " + refThree.hasResorts);
System.out.println("The hasRestaurants is: " + refThree.hasRestaurants);
System.out.println("The hasSpas is: " + refThree.hasSpas);
System.out.println("The hasSwimmingPools is: " + refThree.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refThree.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refThree.hasParkingFacilities);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasGym is: " + refThree.hasGym);
System.out.println("The hasLaundryService is: " + refThree.hasLaundryService);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The chainType is: " + refThree.chainType);
HotelChain refFour = new HotelChain();

System.out.println("The chainId is: " + refFour.chainId);
System.out.println("The chainName is: " + refFour.chainName);
System.out.println("The ceoName is: " + refFour.ceoName);
System.out.println("The headquartersLocation is: " + refFour.headquartersLocation);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfHotels is: " + refFour.numberOfHotels);
System.out.println("The totalRooms is: " + refFour.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refFour.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refFour.hasBudgetHotels);
System.out.println("The hasResorts is: " + refFour.hasResorts);
System.out.println("The hasRestaurants is: " + refFour.hasRestaurants);
System.out.println("The hasSpas is: " + refFour.hasSpas);
System.out.println("The hasSwimmingPools is: " + refFour.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refFour.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refFour.hasParkingFacilities);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasGym is: " + refFour.hasGym);
System.out.println("The hasLaundryService is: " + refFour.hasLaundryService);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The chainType is: " + refFour.chainType);

refFour.chainId = 4;
refFour.chainName = "Heritage Stays";
refFour.ceoName = "Vikram Singh";
refFour.headquartersLocation = "Rajpath";
refFour.city = "Jaipur";
refFour.state = "Rajasthan";
refFour.country = "India";
refFour.numberOfHotels = 8;
refFour.totalRooms = 650;
refFour.hasLuxuryHotels = true;
refFour.hasBudgetHotels = true;
refFour.hasResorts = true;
refFour.hasRestaurants = true;
refFour.hasSpas = true;
refFour.hasSwimmingPools = false;
refFour.hasConferenceHalls = true;
refFour.hasParkingFacilities = true;
refFour.hasWifi = true;
refFour.hasGym = false;
refFour.hasLaundryService = true;
refFour.contactNumber = "9876123450";
refFour.email = "info@heritagestays.com";
refFour.website = "www.heritagestays.com";
refFour.establishedYear = 2008;
refFour.chainType = "Luxury & Heritage";

System.out.println("The chainId is: " + refFour.chainId);
System.out.println("The chainName is: " + refFour.chainName);
System.out.println("The ceoName is: " + refFour.ceoName);
System.out.println("The headquartersLocation is: " + refFour.headquartersLocation);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfHotels is: " + refFour.numberOfHotels);
System.out.println("The totalRooms is: " + refFour.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refFour.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refFour.hasBudgetHotels);
System.out.println("The hasResorts is: " + refFour.hasResorts);
System.out.println("The hasRestaurants is: " + refFour.hasRestaurants);
System.out.println("The hasSpas is: " + refFour.hasSpas);
System.out.println("The hasSwimmingPools is: " + refFour.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refFour.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refFour.hasParkingFacilities);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasGym is: " + refFour.hasGym);
System.out.println("The hasLaundryService is: " + refFour.hasLaundryService);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The chainType is: " + refFour.chainType);
HotelChain refFive = new HotelChain();

System.out.println("The chainId is: " + refFive.chainId);
System.out.println("The chainName is: " + refFive.chainName);
System.out.println("The ceoName is: " + refFive.ceoName);
System.out.println("The headquartersLocation is: " + refFive.headquartersLocation);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfHotels is: " + refFive.numberOfHotels);
System.out.println("The totalRooms is: " + refFive.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refFive.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refFive.hasBudgetHotels);
System.out.println("The hasResorts is: " + refFive.hasResorts);
System.out.println("The hasRestaurants is: " + refFive.hasRestaurants);
System.out.println("The hasSpas is: " + refFive.hasSpas);
System.out.println("The hasSwimmingPools is: " + refFive.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refFive.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refFive.hasParkingFacilities);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The hasGym is: " + refFive.hasGym);
System.out.println("The hasLaundryService is: " + refFive.hasLaundryService);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The chainType is: " + refFive.chainType);

refFive.chainId = 5;
refFive.chainName = "Continental Suites";
refFive.ceoName = "Suresh Menon";
refFive.headquartersLocation = "Park Street";
refFive.city = "Kolkata";
refFive.state = "West Bengal";
refFive.country = "India";
refFive.numberOfHotels = 10;
refFive.totalRooms = 800;
refFive.hasLuxuryHotels = true;
refFive.hasBudgetHotels = true;
refFive.hasResorts = false;
refFive.hasRestaurants = true;
refFive.hasSpas = false;
refFive.hasSwimmingPools = true;
refFive.hasConferenceHalls = true;
refFive.hasParkingFacilities = true;
refFive.hasWifi = true;
refFive.hasGym = true;
refFive.hasLaundryService = true;
refFive.contactNumber = "9001122334";
refFive.email = "contact@continentalsuites.com";
refFive.website = "www.continentalsuites.com";
refFive.establishedYear = 2011;
refFive.chainType = "Luxury & Business";

System.out.println("The chainId is: " + refFive.chainId);
System.out.println("The chainName is: " + refFive.chainName);
System.out.println("The ceoName is: " + refFive.ceoName);
System.out.println("The headquartersLocation is: " + refFive.headquartersLocation);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfHotels is: " + refFive.numberOfHotels);
System.out.println("The totalRooms is: " + refFive.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refFive.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refFive.hasBudgetHotels);
System.out.println("The hasResorts is: " + refFive.hasResorts);
System.out.println("The hasRestaurants is: " + refFive.hasRestaurants);
System.out.println("The hasSpas is: " + refFive.hasSpas);
System.out.println("The hasSwimmingPools is: " + refFive.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refFive.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refFive.hasParkingFacilities);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The hasGym is: " + refFive.hasGym);
System.out.println("The hasLaundryService is: " + refFive.hasLaundryService);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The chainType is: " + refFive.chainType);
HotelChain refSix = new HotelChain();

System.out.println("The chainId is: " + refSix.chainId);
System.out.println("The chainName is: " + refSix.chainName);
System.out.println("The ceoName is: " + refSix.ceoName);
System.out.println("The headquartersLocation is: " + refSix.headquartersLocation);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfHotels is: " + refSix.numberOfHotels);
System.out.println("The totalRooms is: " + refSix.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refSix.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refSix.hasBudgetHotels);
System.out.println("The hasResorts is: " + refSix.hasResorts);
System.out.println("The hasRestaurants is: " + refSix.hasRestaurants);
System.out.println("The hasSpas is: " + refSix.hasSpas);
System.out.println("The hasSwimmingPools is: " + refSix.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refSix.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refSix.hasParkingFacilities);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasGym is: " + refSix.hasGym);
System.out.println("The hasLaundryService is: " + refSix.hasLaundryService);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The chainType is: " + refSix.chainType);

refSix.chainId = 6;
refSix.chainName = "Mountain View Hotels";
refSix.ceoName = "Deepak Choudhary";
refSix.headquartersLocation = "Hilltop Road";
refSix.city = "Shimla";
refSix.state = "Himachal Pradesh";
refSix.country = "India";
refSix.numberOfHotels = 6;
refSix.totalRooms = 400;
refSix.hasLuxuryHotels = true;
refSix.hasBudgetHotels = false;
refSix.hasResorts = true;
refSix.hasRestaurants = true;
refSix.hasSpas = false;
refSix.hasSwimmingPools = true;
refSix.hasConferenceHalls = false;
refSix.hasParkingFacilities = true;
refSix.hasWifi = true;
refSix.hasGym = false;
refSix.hasLaundryService = true;
refSix.contactNumber = "9876001234";
refSix.email = "info@mountainviewhotels.com";
refSix.website = "www.mountainviewhotels.com";
refSix.establishedYear = 2015;
refSix.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refSix.chainId);
System.out.println("The chainName is: " + refSix.chainName);
System.out.println("The ceoName is: " + refSix.ceoName);
System.out.println("The headquartersLocation is: " + refSix.headquartersLocation);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfHotels is: " + refSix.numberOfHotels);
System.out.println("The totalRooms is: " + refSix.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refSix.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refSix.hasBudgetHotels);
System.out.println("The hasResorts is: " + refSix.hasResorts);
System.out.println("The hasRestaurants is: " + refSix.hasRestaurants);
System.out.println("The hasSpas is: " + refSix.hasSpas);
System.out.println("The hasSwimmingPools is: " + refSix.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refSix.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refSix.hasParkingFacilities);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasGym is: " + refSix.hasGym);
System.out.println("The hasLaundryService is: " + refSix.hasLaundryService);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The chainType is: " + refSix.chainType);
HotelChain refSeven = new HotelChain();

System.out.println("The chainId is: " + refSeven.chainId);
System.out.println("The chainName is: " + refSeven.chainName);
System.out.println("The ceoName is: " + refSeven.ceoName);
System.out.println("The headquartersLocation is: " + refSeven.headquartersLocation);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfHotels is: " + refSeven.numberOfHotels);
System.out.println("The totalRooms is: " + refSeven.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refSeven.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refSeven.hasBudgetHotels);
System.out.println("The hasResorts is: " + refSeven.hasResorts);
System.out.println("The hasRestaurants is: " + refSeven.hasRestaurants);
System.out.println("The hasSpas is: " + refSeven.hasSpas);
System.out.println("The hasSwimmingPools is: " + refSeven.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refSeven.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refSeven.hasParkingFacilities);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasGym is: " + refSeven.hasGym);
System.out.println("The hasLaundryService is: " + refSeven.hasLaundryService);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The chainType is: " + refSeven.chainType);

refSeven.chainId = 7;
refSeven.chainName = "Desert Oasis Hotels";
refSeven.ceoName = "Alok Verma";
refSeven.headquartersLocation = "Bikaner Road";
refSeven.city = "Jaisalmer";
refSeven.state = "Rajasthan";
refSeven.country = "India";
refSeven.numberOfHotels = 5;
refSeven.totalRooms = 300;
refSeven.hasLuxuryHotels = true;
refSeven.hasBudgetHotels = false;
refSeven.hasResorts = true;
refSeven.hasRestaurants = true;
refSeven.hasSpas = true;
refSeven.hasSwimmingPools = true;
refSeven.hasConferenceHalls = false;
refSeven.hasParkingFacilities = true;
refSeven.hasWifi = true;
refSeven.hasGym = false;
refSeven.hasLaundryService = true;
refSeven.contactNumber = "9988112233";
refSeven.email = "info@desertoasishotels.com";
refSeven.website = "www.desertoasishotels.com";
refSeven.establishedYear = 2016;
refSeven.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refSeven.chainId);
System.out.println("The chainName is: " + refSeven.chainName);
System.out.println("The ceoName is: " + refSeven.ceoName);
System.out.println("The headquartersLocation is: " + refSeven.headquartersLocation);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfHotels is: " + refSeven.numberOfHotels);
System.out.println("The totalRooms is: " + refSeven.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refSeven.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refSeven.hasBudgetHotels);
System.out.println("The hasResorts is: " + refSeven.hasResorts);
System.out.println("The hasRestaurants is: " + refSeven.hasRestaurants);
System.out.println("The hasSpas is: " + refSeven.hasSpas);
System.out.println("The hasSwimmingPools is: " + refSeven.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refSeven.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refSeven.hasParkingFacilities);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasGym is: " + refSeven.hasGym);
System.out.println("The hasLaundryService is: " + refSeven.hasLaundryService);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The chainType is: " + refSeven.chainType);
HotelChain refEight = new HotelChain();

System.out.println("The chainId is: " + refEight.chainId);
System.out.println("The chainName is: " + refEight.chainName);
System.out.println("The ceoName is: " + refEight.ceoName);
System.out.println("The headquartersLocation is: " + refEight.headquartersLocation);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfHotels is: " + refEight.numberOfHotels);
System.out.println("The totalRooms is: " + refEight.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refEight.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refEight.hasBudgetHotels);
System.out.println("The hasResorts is: " + refEight.hasResorts);
System.out.println("The hasRestaurants is: " + refEight.hasRestaurants);
System.out.println("The hasSpas is: " + refEight.hasSpas);
System.out.println("The hasSwimmingPools is: " + refEight.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refEight.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refEight.hasParkingFacilities);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasGym is: " + refEight.hasGym);
System.out.println("The hasLaundryService is: " + refEight.hasLaundryService);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The chainType is: " + refEight.chainType);

refEight.chainId = 8;
refEight.chainName = "Riverfront Hotels";
refEight.ceoName = "Meena Kapoor";
refEight.headquartersLocation = "Riverside Avenue";
refEight.city = "Kochi";
refEight.state = "Kerala";
refEight.country = "India";
refEight.numberOfHotels = 7;
refEight.totalRooms = 500;
refEight.hasLuxuryHotels = true;
refEight.hasBudgetHotels = true;
refEight.hasResorts = true;
refEight.hasRestaurants = true;
refEight.hasSpas = true;
refEight.hasSwimmingPools = true;
refEight.hasConferenceHalls = true;
refEight.hasParkingFacilities = true;
refEight.hasWifi = true;
refEight.hasGym = true;
refEight.hasLaundryService = true;
refEight.contactNumber = "9898765432";
refEight.email = "info@riverfronthotels.com";
refEight.website = "www.riverfronthotels.com";
refEight.establishedYear = 2013;
refEight.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refEight.chainId);
System.out.println("The chainName is: " + refEight.chainName);
System.out.println("The ceoName is: " + refEight.ceoName);
System.out.println("The headquartersLocation is: " + refEight.headquartersLocation);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfHotels is: " + refEight.numberOfHotels);
System.out.println("The totalRooms is: " + refEight.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refEight.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refEight.hasBudgetHotels);
System.out.println("The hasResorts is: " + refEight.hasResorts);
System.out.println("The hasRestaurants is: " + refEight.hasRestaurants);
System.out.println("The hasSpas is: " + refEight.hasSpas);
System.out.println("The hasSwimmingPools is: " + refEight.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refEight.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refEight.hasParkingFacilities);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasGym is: " + refEight.hasGym);
System.out.println("The hasLaundryService is: " + refEight.hasLaundryService);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The chainType is: " + refEight.chainType);
HotelChain refNine = new HotelChain();

System.out.println("The chainId is: " + refNine.chainId);
System.out.println("The chainName is: " + refNine.chainName);
System.out.println("The ceoName is: " + refNine.ceoName);
System.out.println("The headquartersLocation is: " + refNine.headquartersLocation);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfHotels is: " + refNine.numberOfHotels);
System.out.println("The totalRooms is: " + refNine.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refNine.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refNine.hasBudgetHotels);
System.out.println("The hasResorts is: " + refNine.hasResorts);
System.out.println("The hasRestaurants is: " + refNine.hasRestaurants);
System.out.println("The hasSpas is: " + refNine.hasSpas);
System.out.println("The hasSwimmingPools is: " + refNine.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refNine.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refNine.hasParkingFacilities);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasGym is: " + refNine.hasGym);
System.out.println("The hasLaundryService is: " + refNine.hasLaundryService);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The chainType is: " + refNine.chainType);

refNine.chainId = 9;
refNine.chainName = "CityLights Hotels";
refNine.ceoName = "Ramesh Iyer";
refNine.headquartersLocation = "MG Marg";
refNine.city = "Pune";
refNine.state = "Maharashtra";
refNine.country = "India";
refNine.numberOfHotels = 9;
refNine.totalRooms = 750;
refNine.hasLuxuryHotels = true;
refNine.hasBudgetHotels = true;
refNine.hasResorts = false;
refNine.hasRestaurants = true;
refNine.hasSpas = false;
refNine.hasSwimmingPools = true;
refNine.hasConferenceHalls = true;
refNine.hasParkingFacilities = true;
refNine.hasWifi = true;
refNine.hasGym = true;
refNine.hasLaundryService = true;
refNine.contactNumber = "9876541200";
refNine.email = "info@citylightshotels.com";
refNine.website = "www.citylightshotels.com";
refNine.establishedYear = 2012;
refNine.chainType = "Luxury & Business";

System.out.println("The chainId is: " + refNine.chainId);
System.out.println("The chainName is: " + refNine.chainName);
System.out.println("The ceoName is: " + refNine.ceoName);
System.out.println("The headquartersLocation is: " + refNine.headquartersLocation);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfHotels is: " + refNine.numberOfHotels);
System.out.println("The totalRooms is: " + refNine.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refNine.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refNine.hasBudgetHotels);
System.out.println("The hasResorts is: " + refNine.hasResorts);
System.out.println("The hasRestaurants is: " + refNine.hasRestaurants);
System.out.println("The hasSpas is: " + refNine.hasSpas);
System.out.println("The hasSwimmingPools is: " + refNine.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refNine.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refNine.hasParkingFacilities);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasGym is: " + refNine.hasGym);
System.out.println("The hasLaundryService is: " + refNine.hasLaundryService);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The chainType is: " + refNine.chainType);
HotelChain refTen = new HotelChain();

System.out.println("The chainId is: " + refTen.chainId);
System.out.println("The chainName is: " + refTen.chainName);
System.out.println("The ceoName is: " + refTen.ceoName);
System.out.println("The headquartersLocation is: " + refTen.headquartersLocation);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfHotels is: " + refTen.numberOfHotels);
System.out.println("The totalRooms is: " + refTen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refTen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refTen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refTen.hasResorts);
System.out.println("The hasRestaurants is: " + refTen.hasRestaurants);
System.out.println("The hasSpas is: " + refTen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refTen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refTen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refTen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasGym is: " + refTen.hasGym);
System.out.println("The hasLaundryService is: " + refTen.hasLaundryService);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The chainType is: " + refTen.chainType);

refTen.chainId = 10;
refTen.chainName = "Blue Horizon Hotels";
refTen.ceoName = "Anand Iyer";
refTen.headquartersLocation = "Marine Circle";
refTen.city = "Goa";
refTen.state = "Goa";
refTen.country = "India";
refTen.numberOfHotels = 11;
refTen.totalRooms = 950;
refTen.hasLuxuryHotels = true;
refTen.hasBudgetHotels = true;
refTen.hasResorts = true;
refTen.hasRestaurants = true;
refTen.hasSpas = true;
refTen.hasSwimmingPools = true;
refTen.hasConferenceHalls = true;
refTen.hasParkingFacilities = true;
refTen.hasWifi = true;
refTen.hasGym = true;
refTen.hasLaundryService = true;
refTen.contactNumber = "9988223344";
refTen.email = "info@bluehorizonhotels.com";
refTen.website = "www.bluehorizonhotels.com";
refTen.establishedYear = 2014;
refTen.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refTen.chainId);
System.out.println("The chainName is: " + refTen.chainName);
System.out.println("The ceoName is: " + refTen.ceoName);
System.out.println("The headquartersLocation is: " + refTen.headquartersLocation);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfHotels is: " + refTen.numberOfHotels);
System.out.println("The totalRooms is: " + refTen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refTen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refTen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refTen.hasResorts);
System.out.println("The hasRestaurants is: " + refTen.hasRestaurants);
System.out.println("The hasSpas is: " + refTen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refTen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refTen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refTen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasGym is: " + refTen.hasGym);
System.out.println("The hasLaundryService is: " + refTen.hasLaundryService);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The chainType is: " + refTen.chainType);
HotelChain refEleven = new HotelChain();

System.out.println("The chainId is: " + refEleven.chainId);
System.out.println("The chainName is: " + refEleven.chainName);
System.out.println("The ceoName is: " + refEleven.ceoName);
System.out.println("The headquartersLocation is: " + refEleven.headquartersLocation);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfHotels is: " + refEleven.numberOfHotels);
System.out.println("The totalRooms is: " + refEleven.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refEleven.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refEleven.hasBudgetHotels);
System.out.println("The hasResorts is: " + refEleven.hasResorts);
System.out.println("The hasRestaurants is: " + refEleven.hasRestaurants);
System.out.println("The hasSpas is: " + refEleven.hasSpas);
System.out.println("The hasSwimmingPools is: " + refEleven.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refEleven.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refEleven.hasParkingFacilities);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasGym is: " + refEleven.hasGym);
System.out.println("The hasLaundryService is: " + refEleven.hasLaundryService);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The chainType is: " + refEleven.chainType);

refEleven.chainId = 11;
refEleven.chainName = "Golden Sands Hotels";
refEleven.ceoName = "Vikash Malhotra";
refEleven.headquartersLocation = "Beach Road";
refEleven.city = "Chennai";
refEleven.state = "Tamil Nadu";
refEleven.country = "India";
refEleven.numberOfHotels = 10;
refEleven.totalRooms = 850;
refEleven.hasLuxuryHotels = true;
refEleven.hasBudgetHotels = true;
refEleven.hasResorts = true;
refEleven.hasRestaurants = true;
refEleven.hasSpas = true;
refEleven.hasSwimmingPools = true;
refEleven.hasConferenceHalls = true;
refEleven.hasParkingFacilities = true;
refEleven.hasWifi = true;
refEleven.hasGym = true;
refEleven.hasLaundryService = true;
refEleven.contactNumber = "9876543211";
refEleven.email = "info@goldensandshotels.com";
refEleven.website = "www.goldensandshotels.com";
refEleven.establishedYear = 2010;
refEleven.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refEleven.chainId);
System.out.println("The chainName is: " + refEleven.chainName);
System.out.println("The ceoName is: " + refEleven.ceoName);
System.out.println("The headquartersLocation is: " + refEleven.headquartersLocation);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfHotels is: " + refEleven.numberOfHotels);
System.out.println("The totalRooms is: " + refEleven.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refEleven.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refEleven.hasBudgetHotels);
System.out.println("The hasResorts is: " + refEleven.hasResorts);
System.out.println("The hasRestaurants is: " + refEleven.hasRestaurants);
System.out.println("The hasSpas is: " + refEleven.hasSpas);
System.out.println("The hasSwimmingPools is: " + refEleven.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refEleven.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refEleven.hasParkingFacilities);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasGym is: " + refEleven.hasGym);
System.out.println("The hasLaundryService is: " + refEleven.hasLaundryService);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The chainType is: " + refEleven.chainType);
HotelChain refTwelve = new HotelChain();

System.out.println("The chainId is: " + refTwelve.chainId);
System.out.println("The chainName is: " + refTwelve.chainName);
System.out.println("The ceoName is: " + refTwelve.ceoName);
System.out.println("The headquartersLocation is: " + refTwelve.headquartersLocation);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfHotels is: " + refTwelve.numberOfHotels);
System.out.println("The totalRooms is: " + refTwelve.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refTwelve.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refTwelve.hasBudgetHotels);
System.out.println("The hasResorts is: " + refTwelve.hasResorts);
System.out.println("The hasRestaurants is: " + refTwelve.hasRestaurants);
System.out.println("The hasSpas is: " + refTwelve.hasSpas);
System.out.println("The hasSwimmingPools is: " + refTwelve.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refTwelve.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refTwelve.hasParkingFacilities);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasGym is: " + refTwelve.hasGym);
System.out.println("The hasLaundryService is: " + refTwelve.hasLaundryService);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The chainType is: " + refTwelve.chainType);

refTwelve.chainId = 12;
refTwelve.chainName = "Emerald Retreats";
refTwelve.ceoName = "Rohini Sharma";
refTwelve.headquartersLocation = "Lakeview Road";
refTwelve.city = "Udaipur";
refTwelve.state = "Rajasthan";
refTwelve.country = "India";
refTwelve.numberOfHotels = 6;
refTwelve.totalRooms = 420;
refTwelve.hasLuxuryHotels = true;
refTwelve.hasBudgetHotels = false;
refTwelve.hasResorts = true;
refTwelve.hasRestaurants = true;
refTwelve.hasSpas = true;
refTwelve.hasSwimmingPools = true;
refTwelve.hasConferenceHalls = true;
refTwelve.hasParkingFacilities = true;
refTwelve.hasWifi = true;
refTwelve.hasGym = true;
refTwelve.hasLaundryService = true;
refTwelve.contactNumber = "9876012345";
refTwelve.email = "info@emeraldretreats.com";
refTwelve.website = "www.emeraldretreats.com";
refTwelve.establishedYear = 2016;
refTwelve.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refTwelve.chainId);
System.out.println("The chainName is: " + refTwelve.chainName);
System.out.println("The ceoName is: " + refTwelve.ceoName);
System.out.println("The headquartersLocation is: " + refTwelve.headquartersLocation);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfHotels is: " + refTwelve.numberOfHotels);
System.out.println("The totalRooms is: " + refTwelve.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refTwelve.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refTwelve.hasBudgetHotels);
System.out.println("The hasResorts is: " + refTwelve.hasResorts);
System.out.println("The hasRestaurants is: " + refTwelve.hasRestaurants);
System.out.println("The hasSpas is: " + refTwelve.hasSpas);
System.out.println("The hasSwimmingPools is: " + refTwelve.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refTwelve.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refTwelve.hasParkingFacilities);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasGym is: " + refTwelve.hasGym);
System.out.println("The hasLaundryService is: " + refTwelve.hasLaundryService);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The chainType is: " + refTwelve.chainType);
HotelChain refThirteen = new HotelChain();

System.out.println("The chainId is: " + refThirteen.chainId);
System.out.println("The chainName is: " + refThirteen.chainName);
System.out.println("The ceoName is: " + refThirteen.ceoName);
System.out.println("The headquartersLocation is: " + refThirteen.headquartersLocation);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfHotels is: " + refThirteen.numberOfHotels);
System.out.println("The totalRooms is: " + refThirteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refThirteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refThirteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refThirteen.hasResorts);
System.out.println("The hasRestaurants is: " + refThirteen.hasRestaurants);
System.out.println("The hasSpas is: " + refThirteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refThirteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refThirteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refThirteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasGym is: " + refThirteen.hasGym);
System.out.println("The hasLaundryService is: " + refThirteen.hasLaundryService);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The chainType is: " + refThirteen.chainType);

refThirteen.chainId = 13;
refThirteen.chainName = "Pearl Horizon Hotels";
refThirteen.ceoName = "Arjun Reddy";
refThirteen.headquartersLocation = "Seaside Avenue";
refThirteen.city = "Visakhapatnam";
refThirteen.state = "Andhra Pradesh";
refThirteen.country = "India";
refThirteen.numberOfHotels = 7;
refThirteen.totalRooms = 550;
refThirteen.hasLuxuryHotels = true;
refThirteen.hasBudgetHotels = true;
refThirteen.hasResorts = true;
refThirteen.hasRestaurants = true;
refThirteen.hasSpas = true;
refThirteen.hasSwimmingPools = true;
refThirteen.hasConferenceHalls = true;
refThirteen.hasParkingFacilities = true;
refThirteen.hasWifi = true;
refThirteen.hasGym = true;
refThirteen.hasLaundryService = true;
refThirteen.contactNumber = "9988776650";
refThirteen.email = "info@pearlhorizon.com";
refThirteen.website = "www.pearlhorizon.com";
refThirteen.establishedYear = 2015;
refThirteen.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refThirteen.chainId);
System.out.println("The chainName is: " + refThirteen.chainName);
System.out.println("The ceoName is: " + refThirteen.ceoName);
System.out.println("The headquartersLocation is: " + refThirteen.headquartersLocation);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfHotels is: " + refThirteen.numberOfHotels);
System.out.println("The totalRooms is: " + refThirteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refThirteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refThirteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refThirteen.hasResorts);
System.out.println("The hasRestaurants is: " + refThirteen.hasRestaurants);
System.out.println("The hasSpas is: " + refThirteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refThirteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refThirteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refThirteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasGym is: " + refThirteen.hasGym);
System.out.println("The hasLaundryService is: " + refThirteen.hasLaundryService);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The chainType is: " + refThirteen.chainType);
HotelChain refFourteen = new HotelChain();

System.out.println("The chainId is: " + refFourteen.chainId);
System.out.println("The chainName is: " + refFourteen.chainName);
System.out.println("The ceoName is: " + refFourteen.ceoName);
System.out.println("The headquartersLocation is: " + refFourteen.headquartersLocation);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfHotels is: " + refFourteen.numberOfHotels);
System.out.println("The totalRooms is: " + refFourteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refFourteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refFourteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refFourteen.hasResorts);
System.out.println("The hasRestaurants is: " + refFourteen.hasRestaurants);
System.out.println("The hasSpas is: " + refFourteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refFourteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refFourteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refFourteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasGym is: " + refFourteen.hasGym);
System.out.println("The hasLaundryService is: " + refFourteen.hasLaundryService);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The chainType is: " + refFourteen.chainType);

refFourteen.chainId = 14;
refFourteen.chainName = "Sunrise Hospitality";
refFourteen.ceoName = "Manoj Kumar";
refFourteen.headquartersLocation = "Sunset Boulevard";
refFourteen.city = "Hyderabad";
refFourteen.state = "Telangana";
refFourteen.country = "India";
refFourteen.numberOfHotels = 8;
refFourteen.totalRooms = 600;
refFourteen.hasLuxuryHotels = true;
refFourteen.hasBudgetHotels = true;
refFourteen.hasResorts = true;
refFourteen.hasRestaurants = true;
refFourteen.hasSpas = true;
refFourteen.hasSwimmingPools = true;
refFourteen.hasConferenceHalls = true;
refFourteen.hasParkingFacilities = true;
refFourteen.hasWifi = true;
refFourteen.hasGym = true;
refFourteen.hasLaundryService = true;
refFourteen.contactNumber = "9988771122";
refFourteen.email = "info@sunrisehospitality.com";
refFourteen.website = "www.sunrisehospitality.com";
refFourteen.establishedYear = 2013;
refFourteen.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refFourteen.chainId);
System.out.println("The chainName is: " + refFourteen.chainName);
System.out.println("The ceoName is: " + refFourteen.ceoName);
System.out.println("The headquartersLocation is: " + refFourteen.headquartersLocation);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfHotels is: " + refFourteen.numberOfHotels);
System.out.println("The totalRooms is: " + refFourteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refFourteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refFourteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refFourteen.hasResorts);
System.out.println("The hasRestaurants is: " + refFourteen.hasRestaurants);
System.out.println("The hasSpas is: " + refFourteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refFourteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refFourteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refFourteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasGym is: " + refFourteen.hasGym);
System.out.println("The hasLaundryService is: " + refFourteen.hasLaundryService);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The chainType is: " + refFourteen.chainType);
HotelChain refFifteen = new HotelChain();

System.out.println("The chainId is: " + refFifteen.chainId);
System.out.println("The chainName is: " + refFifteen.chainName);
System.out.println("The ceoName is: " + refFifteen.ceoName);
System.out.println("The headquartersLocation is: " + refFifteen.headquartersLocation);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfHotels is: " + refFifteen.numberOfHotels);
System.out.println("The totalRooms is: " + refFifteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refFifteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refFifteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refFifteen.hasResorts);
System.out.println("The hasRestaurants is: " + refFifteen.hasRestaurants);
System.out.println("The hasSpas is: " + refFifteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refFifteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refFifteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refFifteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasGym is: " + refFifteen.hasGym);
System.out.println("The hasLaundryService is: " + refFifteen.hasLaundryService);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The chainType is: " + refFifteen.chainType);

refFifteen.chainId = 15;
refFifteen.chainName = "Crystal Bay Hotels";
refFifteen.ceoName = "Sneha Reddy";
refFifteen.headquartersLocation = "Bay Street";
refFifteen.city = "Mangalore";
refFifteen.state = "Karnataka";
refFifteen.country = "India";
refFifteen.numberOfHotels = 5;
refFifteen.totalRooms = 350;
refFifteen.hasLuxuryHotels = true;
refFifteen.hasBudgetHotels = true;
refFifteen.hasResorts = true;
refFifteen.hasRestaurants = true;
refFifteen.hasSpas = true;
refFifteen.hasSwimmingPools = true;
refFifteen.hasConferenceHalls = true;
refFifteen.hasParkingFacilities = true;
refFifteen.hasWifi = true;
refFifteen.hasGym = true;
refFifteen.hasLaundryService = true;
refFifteen.contactNumber = "9988774433";
refFifteen.email = "info@crystalbayhotels.com";
refFifteen.website = "www.crystalbayhotels.com";
refFifteen.establishedYear = 2017;
refFifteen.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refFifteen.chainId);
System.out.println("The chainName is: " + refFifteen.chainName);
System.out.println("The ceoName is: " + refFifteen.ceoName);
System.out.println("The headquartersLocation is: " + refFifteen.headquartersLocation);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfHotels is: " + refFifteen.numberOfHotels);
System.out.println("The totalRooms is: " + refFifteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refFifteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refFifteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refFifteen.hasResorts);
System.out.println("The hasRestaurants is: " + refFifteen.hasRestaurants);
System.out.println("The hasSpas is: " + refFifteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refFifteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refFifteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refFifteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasGym is: " + refFifteen.hasGym);
System.out.println("The hasLaundryService is: " + refFifteen.hasLaundryService);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The chainType is: " + refFifteen.chainType);
HotelChain refSixteen = new HotelChain();

System.out.println("The chainId is: " + refSixteen.chainId);
System.out.println("The chainName is: " + refSixteen.chainName);
System.out.println("The ceoName is: " + refSixteen.ceoName);
System.out.println("The headquartersLocation is: " + refSixteen.headquartersLocation);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfHotels is: " + refSixteen.numberOfHotels);
System.out.println("The totalRooms is: " + refSixteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refSixteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refSixteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refSixteen.hasResorts);
System.out.println("The hasRestaurants is: " + refSixteen.hasRestaurants);
System.out.println("The hasSpas is: " + refSixteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refSixteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refSixteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refSixteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasGym is: " + refSixteen.hasGym);
System.out.println("The hasLaundryService is: " + refSixteen.hasLaundryService);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The chainType is: " + refSixteen.chainType);

refSixteen.chainId = 16;
refSixteen.chainName = "Emerald Bay Resorts";
refSixteen.ceoName = "Nikhil Rao";
refSixteen.headquartersLocation = "Coastal Road";
refSixteen.city = "Goa";
refSixteen.state = "Goa";
refSixteen.country = "India";
refSixteen.numberOfHotels = 6;
refSixteen.totalRooms = 480;
refSixteen.hasLuxuryHotels = true;
refSixteen.hasBudgetHotels = false;
refSixteen.hasResorts = true;
refSixteen.hasRestaurants = true;
refSixteen.hasSpas = true;
refSixteen.hasSwimmingPools = true;
refSixteen.hasConferenceHalls = true;
refSixteen.hasParkingFacilities = true;
refSixteen.hasWifi = true;
refSixteen.hasGym = true;
refSixteen.hasLaundryService = true;
refSixteen.contactNumber = "9988775566";
refSixteen.email = "info@emeraldbayresorts.com";
refSixteen.website = "www.emeraldbayresorts.com";
refSixteen.establishedYear = 2018;
refSixteen.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refSixteen.chainId);
System.out.println("The chainName is: " + refSixteen.chainName);
System.out.println("The ceoName is: " + refSixteen.ceoName);
System.out.println("The headquartersLocation is: " + refSixteen.headquartersLocation);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfHotels is: " + refSixteen.numberOfHotels);
System.out.println("The totalRooms is: " + refSixteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refSixteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refSixteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refSixteen.hasResorts);
System.out.println("The hasRestaurants is: " + refSixteen.hasRestaurants);
System.out.println("The hasSpas is: " + refSixteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refSixteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refSixteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refSixteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasGym is: " + refSixteen.hasGym);
System.out.println("The hasLaundryService is: " + refSixteen.hasLaundryService);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The chainType is: " + refSixteen.chainType);
HotelChain refSeventeen = new HotelChain();

System.out.println("The chainId is: " + refSeventeen.chainId);
System.out.println("The chainName is: " + refSeventeen.chainName);
System.out.println("The ceoName is: " + refSeventeen.ceoName);
System.out.println("The headquartersLocation is: " + refSeventeen.headquartersLocation);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfHotels is: " + refSeventeen.numberOfHotels);
System.out.println("The totalRooms is: " + refSeventeen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refSeventeen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refSeventeen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refSeventeen.hasResorts);
System.out.println("The hasRestaurants is: " + refSeventeen.hasRestaurants);
System.out.println("The hasSpas is: " + refSeventeen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refSeventeen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refSeventeen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refSeventeen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasGym is: " + refSeventeen.hasGym);
System.out.println("The hasLaundryService is: " + refSeventeen.hasLaundryService);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The chainType is: " + refSeventeen.chainType);

refSeventeen.chainId = 17;
refSeventeen.chainName = "Orchid Resorts";
refSeventeen.ceoName = "Vijay Prakash";
refSeventeen.headquartersLocation = "Garden Lane";
refSeventeen.city = "Kumarakom";
refSeventeen.state = "Kerala";
refSeventeen.country = "India";
refSeventeen.numberOfHotels = 5;
refSeventeen.totalRooms = 400;
refSeventeen.hasLuxuryHotels = true;
refSeventeen.hasBudgetHotels = false;
refSeventeen.hasResorts = true;
refSeventeen.hasRestaurants = true;
refSeventeen.hasSpas = true;
refSeventeen.hasSwimmingPools = true;
refSeventeen.hasConferenceHalls = false;
refSeventeen.hasParkingFacilities = true;
refSeventeen.hasWifi = true;
refSeventeen.hasGym = true;
refSeventeen.hasLaundryService = true;
refSeventeen.contactNumber = "9988445566";
refSeventeen.email = "info@orchidresorts.com";
refSeventeen.website = "www.orchidresorts.com";
refSeventeen.establishedYear = 2019;
refSeventeen.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refSeventeen.chainId);
System.out.println("The chainName is: " + refSeventeen.chainName);
System.out.println("The ceoName is: " + refSeventeen.ceoName);
System.out.println("The headquartersLocation is: " + refSeventeen.headquartersLocation);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfHotels is: " + refSeventeen.numberOfHotels);
System.out.println("The totalRooms is: " + refSeventeen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refSeventeen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refSeventeen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refSeventeen.hasResorts);
System.out.println("The hasRestaurants is: " + refSeventeen.hasRestaurants);
System.out.println("The hasSpas is: " + refSeventeen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refSeventeen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refSeventeen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refSeventeen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasGym is: " + refSeventeen.hasGym);
System.out.println("The hasLaundryService is: " + refSeventeen.hasLaundryService);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The chainType is: " + refSeventeen.chainType);
HotelChain refEighteen = new HotelChain();

System.out.println("The chainId is: " + refEighteen.chainId);
System.out.println("The chainName is: " + refEighteen.chainName);
System.out.println("The ceoName is: " + refEighteen.ceoName);
System.out.println("The headquartersLocation is: " + refEighteen.headquartersLocation);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfHotels is: " + refEighteen.numberOfHotels);
System.out.println("The totalRooms is: " + refEighteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refEighteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refEighteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refEighteen.hasResorts);
System.out.println("The hasRestaurants is: " + refEighteen.hasRestaurants);
System.out.println("The hasSpas is: " + refEighteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refEighteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refEighteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refEighteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasGym is: " + refEighteen.hasGym);
System.out.println("The hasLaundryService is: " + refEighteen.hasLaundryService);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The chainType is: " + refEighteen.chainType);

refEighteen.chainId = 18;
refEighteen.chainName = "Silver Palm Hotels";
refEighteen.ceoName = "Kiran Desai";
refEighteen.headquartersLocation = "Palm Avenue";
refEighteen.city = "Kochi";
refEighteen.state = "Kerala";
refEighteen.country = "India";
refEighteen.numberOfHotels = 7;
refEighteen.totalRooms = 520;
refEighteen.hasLuxuryHotels = true;
refEighteen.hasBudgetHotels = true;
refEighteen.hasResorts = true;
refEighteen.hasRestaurants = true;
refEighteen.hasSpas = true;
refEighteen.hasSwimmingPools = true;
refEighteen.hasConferenceHalls = true;
refEighteen.hasParkingFacilities = true;
refEighteen.hasWifi = true;
refEighteen.hasGym = true;
refEighteen.hasLaundryService = true;
refEighteen.contactNumber = "9988779900";
refEighteen.email = "info@silverpalmhotels.com";
refEighteen.website = "www.silverpalmhotels.com";
refEighteen.establishedYear = 2014;
refEighteen.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refEighteen.chainId);
System.out.println("The chainName is: " + refEighteen.chainName);
System.out.println("The ceoName is: " + refEighteen.ceoName);
System.out.println("The headquartersLocation is: " + refEighteen.headquartersLocation);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfHotels is: " + refEighteen.numberOfHotels);
System.out.println("The totalRooms is: " + refEighteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refEighteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refEighteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refEighteen.hasResorts);
System.out.println("The hasRestaurants is: " + refEighteen.hasRestaurants);
System.out.println("The hasSpas is: " + refEighteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refEighteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refEighteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refEighteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasGym is: " + refEighteen.hasGym);
System.out.println("The hasLaundryService is: " + refEighteen.hasLaundryService);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The chainType is: " + refEighteen.chainType);
HotelChain refNineteen = new HotelChain();

System.out.println("The chainId is: " + refNineteen.chainId);
System.out.println("The chainName is: " + refNineteen.chainName);
System.out.println("The ceoName is: " + refNineteen.ceoName);
System.out.println("The headquartersLocation is: " + refNineteen.headquartersLocation);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfHotels is: " + refNineteen.numberOfHotels);
System.out.println("The totalRooms is: " + refNineteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refNineteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refNineteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refNineteen.hasResorts);
System.out.println("The hasRestaurants is: " + refNineteen.hasRestaurants);
System.out.println("The hasSpas is: " + refNineteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refNineteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refNineteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refNineteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasGym is: " + refNineteen.hasGym);
System.out.println("The hasLaundryService is: " + refNineteen.hasLaundryService);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The chainType is: " + refNineteen.chainType);

refNineteen.chainId = 19;
refNineteen.chainName = "Paradise Retreats";
refNineteen.ceoName = "Sanjay Mehta";
refNineteen.headquartersLocation = "Ocean Drive";
refNineteen.city = "Alleppey";
refNineteen.state = "Kerala";
refNineteen.country = "India";
refNineteen.numberOfHotels = 6;
refNineteen.totalRooms = 450;
refNineteen.hasLuxuryHotels = true;
refNineteen.hasBudgetHotels = false;
refNineteen.hasResorts = true;
refNineteen.hasRestaurants = true;
refNineteen.hasSpas = true;
refNineteen.hasSwimmingPools = true;
refNineteen.hasConferenceHalls = true;
refNineteen.hasParkingFacilities = true;
refNineteen.hasWifi = true;
refNineteen.hasGym = true;
refNineteen.hasLaundryService = true;
refNineteen.contactNumber = "9988775544";
refNineteen.email = "info@paradiseretreats.com";
refNineteen.website = "www.paradiseretreats.com";
refNineteen.establishedYear = 2016;
refNineteen.chainType = "Luxury & Resort";

System.out.println("The chainId is: " + refNineteen.chainId);
System.out.println("The chainName is: " + refNineteen.chainName);
System.out.println("The ceoName is: " + refNineteen.ceoName);
System.out.println("The headquartersLocation is: " + refNineteen.headquartersLocation);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfHotels is: " + refNineteen.numberOfHotels);
System.out.println("The totalRooms is: " + refNineteen.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refNineteen.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refNineteen.hasBudgetHotels);
System.out.println("The hasResorts is: " + refNineteen.hasResorts);
System.out.println("The hasRestaurants is: " + refNineteen.hasRestaurants);
System.out.println("The hasSpas is: " + refNineteen.hasSpas);
System.out.println("The hasSwimmingPools is: " + refNineteen.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refNineteen.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refNineteen.hasParkingFacilities);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasGym is: " + refNineteen.hasGym);
System.out.println("The hasLaundryService is: " + refNineteen.hasLaundryService);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The chainType is: " + refNineteen.chainType);
HotelChain refTwenty = new HotelChain();

System.out.println("The chainId is: " + refTwenty.chainId);
System.out.println("The chainName is: " + refTwenty.chainName);
System.out.println("The ceoName is: " + refTwenty.ceoName);
System.out.println("The headquartersLocation is: " + refTwenty.headquartersLocation);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfHotels is: " + refTwenty.numberOfHotels);
System.out.println("The totalRooms is: " + refTwenty.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refTwenty.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refTwenty.hasBudgetHotels);
System.out.println("The hasResorts is: " + refTwenty.hasResorts);
System.out.println("The hasRestaurants is: " + refTwenty.hasRestaurants);
System.out.println("The hasSpas is: " + refTwenty.hasSpas);
System.out.println("The hasSwimmingPools is: " + refTwenty.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refTwenty.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refTwenty.hasParkingFacilities);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasGym is: " + refTwenty.hasGym);
System.out.println("The hasLaundryService is: " + refTwenty.hasLaundryService);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The chainType is: " + refTwenty.chainType);

refTwenty.chainId = 20;
refTwenty.chainName = "Lotus Grand Hotels";
refTwenty.ceoName = "Raghav Menon";
refTwenty.headquartersLocation = "Central Plaza";
refTwenty.city = "Bengaluru";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.numberOfHotels = 12;
refTwenty.totalRooms = 950;
refTwenty.hasLuxuryHotels = true;
refTwenty.hasBudgetHotels = true;
refTwenty.hasResorts = true;
refTwenty.hasRestaurants = true;
refTwenty.hasSpas = true;
refTwenty.hasSwimmingPools = true;
refTwenty.hasConferenceHalls = true;
refTwenty.hasParkingFacilities = true;
refTwenty.hasWifi = true;
refTwenty.hasGym = true;
refTwenty.hasLaundryService = true;
refTwenty.contactNumber = "9988776655";
refTwenty.email = "info@lotusgrand.com";
refTwenty.website = "www.lotusgrand.com";
refTwenty.establishedYear = 2011;
refTwenty.chainType = "Luxury & Business";

System.out.println("The chainId is: " + refTwenty.chainId);
System.out.println("The chainName is: " + refTwenty.chainName);
System.out.println("The ceoName is: " + refTwenty.ceoName);
System.out.println("The headquartersLocation is: " + refTwenty.headquartersLocation);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfHotels is: " + refTwenty.numberOfHotels);
System.out.println("The totalRooms is: " + refTwenty.totalRooms);
System.out.println("The hasLuxuryHotels is: " + refTwenty.hasLuxuryHotels);
System.out.println("The hasBudgetHotels is: " + refTwenty.hasBudgetHotels);
System.out.println("The hasResorts is: " + refTwenty.hasResorts);
System.out.println("The hasRestaurants is: " + refTwenty.hasRestaurants);
System.out.println("The hasSpas is: " + refTwenty.hasSpas);
System.out.println("The hasSwimmingPools is: " + refTwenty.hasSwimmingPools);
System.out.println("The hasConferenceHalls is: " + refTwenty.hasConferenceHalls);
System.out.println("The hasParkingFacilities is: " + refTwenty.hasParkingFacilities);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasGym is: " + refTwenty.hasGym);
System.out.println("The hasLaundryService is: " + refTwenty.hasLaundryService);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The chainType is: " + refTwenty.chainType);
}
}