class HotelExecutor{
public static void main(String[] args){
Hotel refOne = new Hotel();

System.out.println("The hotelId is: " + refOne.hotelId);
System.out.println("The hotelName is: " + refOne.hotelName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfRooms is: " + refOne.numberOfRooms);
System.out.println("The numberOfFloors is: " + refOne.numberOfFloors);
System.out.println("The hasRestaurant is: " + refOne.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refOne.hasSwimmingPool);
System.out.println("The hasGym is: " + refOne.hasGym);
System.out.println("The hasSpa is: " + refOne.hasSpa);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasBar is: " + refOne.hasBar);
System.out.println("The rating is: " + refOne.rating);
System.out.println("The ownerName is: " + refOne.ownerName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The hotelType is: " + refOne.hotelType);
System.out.println("The pricePerNight is: " + refOne.pricePerNight);
System.out.println("The hasConferenceHall is: " + refOne.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refOne.hasLaundryService);


refOne.hotelId = 1;
refOne.hotelName = "Grand Palace";
refOne.location = "MG Road";
refOne.city = "Bangalore";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfRooms = 120;
refOne.numberOfFloors = 10;
refOne.hasRestaurant = true;
refOne.hasSwimmingPool = true;
refOne.hasGym = true;
refOne.hasSpa = false;
refOne.hasParking = true;
refOne.hasWifi = true;
refOne.hasBar = true;
refOne.rating = 5;
refOne.ownerName = "Ramesh Kumar";
refOne.establishedYear = 2015;
refOne.contactNumber = "9876543210";
refOne.email = "info@grandpalace.com";
refOne.website = "www.grandpalace.com";
refOne.hotelType = "Luxury";
refOne.pricePerNight = 6500;
refOne.hasConferenceHall = true;
refOne.hasLaundryService = true;


System.out.println("The hotelId is: " + refOne.hotelId);
System.out.println("The hotelName is: " + refOne.hotelName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfRooms is: " + refOne.numberOfRooms);
System.out.println("The numberOfFloors is: " + refOne.numberOfFloors);
System.out.println("The hasRestaurant is: " + refOne.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refOne.hasSwimmingPool);
System.out.println("The hasGym is: " + refOne.hasGym);
System.out.println("The hasSpa is: " + refOne.hasSpa);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasBar is: " + refOne.hasBar);
System.out.println("The rating is: " + refOne.rating);
System.out.println("The ownerName is: " + refOne.ownerName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The hotelType is: " + refOne.hotelType);
System.out.println("The pricePerNight is: " + refOne.pricePerNight);
System.out.println("The hasConferenceHall is: " + refOne.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refOne.hasLaundryService);
Hotel refTwo = new Hotel();

System.out.println("The hotelId is: " + refTwo.hotelId);
System.out.println("The hotelName is: " + refTwo.hotelName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfRooms is: " + refTwo.numberOfRooms);
System.out.println("The numberOfFloors is: " + refTwo.numberOfFloors);
System.out.println("The hasRestaurant is: " + refTwo.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refTwo.hasSwimmingPool);
System.out.println("The hasGym is: " + refTwo.hasGym);
System.out.println("The hasSpa is: " + refTwo.hasSpa);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasBar is: " + refTwo.hasBar);
System.out.println("The rating is: " + refTwo.rating);
System.out.println("The ownerName is: " + refTwo.ownerName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The hotelType is: " + refTwo.hotelType);
System.out.println("The pricePerNight is: " + refTwo.pricePerNight);
System.out.println("The hasConferenceHall is: " + refTwo.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refTwo.hasLaundryService);


refTwo.hotelId = 2;
refTwo.hotelName = "Sea View Resort";
refTwo.location = "Beach Road";
refTwo.city = "Chennai";
refTwo.state = "Tamil Nadu";
refTwo.country = "India";
refTwo.numberOfRooms = 80;
refTwo.numberOfFloors = 6;
refTwo.hasRestaurant = true;
refTwo.hasSwimmingPool = true;
refTwo.hasGym = false;
refTwo.hasSpa = true;
refTwo.hasParking = true;
refTwo.hasWifi = true;
refTwo.hasBar = false;
refTwo.rating = 4;
refTwo.ownerName = "Suresh Kumar";
refTwo.establishedYear = 2012;
refTwo.contactNumber = "9123456780";
refTwo.email = "contact@seaview.com";
refTwo.website = "www.seaviewresort.com";
refTwo.hotelType = "Resort";
refTwo.pricePerNight = 4200;
refTwo.hasConferenceHall = false;
refTwo.hasLaundryService = true;


System.out.println("The hotelId is: " + refTwo.hotelId);
System.out.println("The hotelName is: " + refTwo.hotelName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfRooms is: " + refTwo.numberOfRooms);
System.out.println("The numberOfFloors is: " + refTwo.numberOfFloors);
System.out.println("The hasRestaurant is: " + refTwo.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refTwo.hasSwimmingPool);
System.out.println("The hasGym is: " + refTwo.hasGym);
System.out.println("The hasSpa is: " + refTwo.hasSpa);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasBar is: " + refTwo.hasBar);
System.out.println("The rating is: " + refTwo.rating);
System.out.println("The ownerName is: " + refTwo.ownerName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The hotelType is: " + refTwo.hotelType);
System.out.println("The pricePerNight is: " + refTwo.pricePerNight);
System.out.println("The hasConferenceHall is: " + refTwo.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refTwo.hasLaundryService);
Hotel refThree = new Hotel();

System.out.println("The hotelId is: " + refThree.hotelId);
System.out.println("The hotelName is: " + refThree.hotelName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfRooms is: " + refThree.numberOfRooms);
System.out.println("The numberOfFloors is: " + refThree.numberOfFloors);
System.out.println("The hasRestaurant is: " + refThree.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refThree.hasSwimmingPool);
System.out.println("The hasGym is: " + refThree.hasGym);
System.out.println("The hasSpa is: " + refThree.hasSpa);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasBar is: " + refThree.hasBar);
System.out.println("The rating is: " + refThree.rating);
System.out.println("The ownerName is: " + refThree.ownerName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The hotelType is: " + refThree.hotelType);
System.out.println("The pricePerNight is: " + refThree.pricePerNight);
System.out.println("The hasConferenceHall is: " + refThree.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refThree.hasLaundryService);


refThree.hotelId = 3;
refThree.hotelName = "Royal Comfort";
refThree.location = "Brigade Road";
refThree.city = "Bangalore";
refThree.state = "Karnataka";
refThree.country = "India";
refThree.numberOfRooms = 95;
refThree.numberOfFloors = 8;
refThree.hasRestaurant = true;
refThree.hasSwimmingPool = false;
refThree.hasGym = true;
refThree.hasSpa = false;
refThree.hasParking = true;
refThree.hasWifi = true;
refThree.hasBar = true;
refThree.rating = 4;
refThree.ownerName = "Anil Sharma";
refThree.establishedYear = 2018;
refThree.contactNumber = "9345678123";
refThree.email = "info@royalcomfort.com";
refThree.website = "www.royalcomfort.com";
refThree.hotelType = "Business";
refThree.pricePerNight = 3500;
refThree.hasConferenceHall = true;
refThree.hasLaundryService = true;


System.out.println("The hotelId is: " + refThree.hotelId);
System.out.println("The hotelName is: " + refThree.hotelName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfRooms is: " + refThree.numberOfRooms);
System.out.println("The numberOfFloors is: " + refThree.numberOfFloors);
System.out.println("The hasRestaurant is: " + refThree.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refThree.hasSwimmingPool);
System.out.println("The hasGym is: " + refThree.hasGym);
System.out.println("The hasSpa is: " + refThree.hasSpa);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasBar is: " + refThree.hasBar);
System.out.println("The rating is: " + refThree.rating);
System.out.println("The ownerName is: " + refThree.ownerName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The hotelType is: " + refThree.hotelType);
System.out.println("The pricePerNight is: " + refThree.pricePerNight);
System.out.println("The hasConferenceHall is: " + refThree.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refThree.hasLaundryService);
Hotel refFour = new Hotel();

System.out.println("The hotelId is: " + refFour.hotelId);
System.out.println("The hotelName is: " + refFour.hotelName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfRooms is: " + refFour.numberOfRooms);
System.out.println("The numberOfFloors is: " + refFour.numberOfFloors);
System.out.println("The hasRestaurant is: " + refFour.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refFour.hasSwimmingPool);
System.out.println("The hasGym is: " + refFour.hasGym);
System.out.println("The hasSpa is: " + refFour.hasSpa);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasBar is: " + refFour.hasBar);
System.out.println("The rating is: " + refFour.rating);
System.out.println("The ownerName is: " + refFour.ownerName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The hotelType is: " + refFour.hotelType);
System.out.println("The pricePerNight is: " + refFour.pricePerNight);
System.out.println("The hasConferenceHall is: " + refFour.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refFour.hasLaundryService);


refFour.hotelId = 4;
refFour.hotelName = "City Central Hotel";
refFour.location = "Main Street";
refFour.city = "Hyderabad";
refFour.state = "Telangana";
refFour.country = "India";
refFour.numberOfRooms = 110;
refFour.numberOfFloors = 9;
refFour.hasRestaurant = true;
refFour.hasSwimmingPool = false;
refFour.hasGym = true;
refFour.hasSpa = false;
refFour.hasParking = true;
refFour.hasWifi = true;
refFour.hasBar = true;
refFour.rating = 4;
refFour.ownerName = "Kiran Reddy";
refFour.establishedYear = 2016;
refFour.contactNumber = "9988776655";
refFour.email = "info@citycentral.com";
refFour.website = "www.citycentralhotel.com";
refFour.hotelType = "Business";
refFour.pricePerNight = 3800;
refFour.hasConferenceHall = true;
refFour.hasLaundryService = true;


System.out.println("The hotelId is: " + refFour.hotelId);
System.out.println("The hotelName is: " + refFour.hotelName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfRooms is: " + refFour.numberOfRooms);
System.out.println("The numberOfFloors is: " + refFour.numberOfFloors);
System.out.println("The hasRestaurant is: " + refFour.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refFour.hasSwimmingPool);
System.out.println("The hasGym is: " + refFour.hasGym);
System.out.println("The hasSpa is: " + refFour.hasSpa);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasBar is: " + refFour.hasBar);
System.out.println("The rating is: " + refFour.rating);
System.out.println("The ownerName is: " + refFour.ownerName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The hotelType is: " + refFour.hotelType);
System.out.println("The pricePerNight is: " + refFour.pricePerNight);
System.out.println("The hasConferenceHall is: " + refFour.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refFour.hasLaundryService);
Hotel refFive = new Hotel();

System.out.println("The hotelId is: " + refFive.hotelId);
System.out.println("The hotelName is: " + refFive.hotelName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfRooms is: " + refFive.numberOfRooms);
System.out.println("The numberOfFloors is: " + refFive.numberOfFloors);
System.out.println("The hasRestaurant is: " + refFive.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refFive.hasSwimmingPool);
System.out.println("The hasGym is: " + refFive.hasGym);
System.out.println("The hasSpa is: " + refFive.hasSpa);
System.out.println("The hasParking is: " + refFive.hasParking);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The hasBar is: " + refFive.hasBar);
System.out.println("The rating is: " + refFive.rating);
System.out.println("The ownerName is: " + refFive.ownerName);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The hotelType is: " + refFive.hotelType);
System.out.println("The pricePerNight is: " + refFive.pricePerNight);
System.out.println("The hasConferenceHall is: " + refFive.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refFive.hasLaundryService);


refFive.hotelId = 5;
refFive.hotelName = "Sunrise Inn";
refFive.location = "Lake View Road";
refFive.city = "Mysore";
refFive.state = "Karnataka";
refFive.country = "India";
refFive.numberOfRooms = 70;
refFive.numberOfFloors = 5;
refFive.hasRestaurant = true;
refFive.hasSwimmingPool = false;
refFive.hasGym = false;
refFive.hasSpa = false;
refFive.hasParking = true;
refFive.hasWifi = true;
refFive.hasBar = false;
refFive.rating = 3;
refFive.ownerName = "Mahesh Gowda";
refFive.establishedYear = 2010;
refFive.contactNumber = "9876501234";
refFive.email = "info@sunriseinn.com";
refFive.website = "www.sunriseinn.com";
refFive.hotelType = "Budget";
refFive.pricePerNight = 2200;
refFive.hasConferenceHall = false;
refFive.hasLaundryService = true;


System.out.println("The hotelId is: " + refFive.hotelId);
System.out.println("The hotelName is: " + refFive.hotelName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfRooms is: " + refFive.numberOfRooms);
System.out.println("The numberOfFloors is: " + refFive.numberOfFloors);
System.out.println("The hasRestaurant is: " + refFive.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refFive.hasSwimmingPool);
System.out.println("The hasGym is: " + refFive.hasGym);
System.out.println("The hasSpa is: " + refFive.hasSpa);
System.out.println("The hasParking is: " + refFive.hasParking);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The hasBar is: " + refFive.hasBar);
System.out.println("The rating is: " + refFive.rating);
System.out.println("The ownerName is: " + refFive.ownerName);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The hotelType is: " + refFive.hotelType);
System.out.println("The pricePerNight is: " + refFive.pricePerNight);
System.out.println("The hasConferenceHall is: " + refFive.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refFive.hasLaundryService);
Hotel refSix = new Hotel();

System.out.println("The hotelId is: " + refSix.hotelId);
System.out.println("The hotelName is: " + refSix.hotelName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfRooms is: " + refSix.numberOfRooms);
System.out.println("The numberOfFloors is: " + refSix.numberOfFloors);
System.out.println("The hasRestaurant is: " + refSix.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refSix.hasSwimmingPool);
System.out.println("The hasGym is: " + refSix.hasGym);
System.out.println("The hasSpa is: " + refSix.hasSpa);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasBar is: " + refSix.hasBar);
System.out.println("The rating is: " + refSix.rating);
System.out.println("The ownerName is: " + refSix.ownerName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The hotelType is: " + refSix.hotelType);
System.out.println("The pricePerNight is: " + refSix.pricePerNight);
System.out.println("The hasConferenceHall is: " + refSix.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refSix.hasLaundryService);


refSix.hotelId = 6;
refSix.hotelName = "Blue Orchid Hotel";
refSix.location = "Airport Road";
refSix.city = "Bangalore";
refSix.state = "Karnataka";
refSix.country = "India";
refSix.numberOfRooms = 140;
refSix.numberOfFloors = 12;
refSix.hasRestaurant = true;
refSix.hasSwimmingPool = true;
refSix.hasGym = true;
refSix.hasSpa = true;
refSix.hasParking = true;
refSix.hasWifi = true;
refSix.hasBar = true;
refSix.rating = 5;
refSix.ownerName = "Vikram Shetty";
refSix.establishedYear = 2019;
refSix.contactNumber = "9012345678";
refSix.email = "info@blueorchid.com";
refSix.website = "www.blueorchidhotel.com";
refSix.hotelType = "Luxury";
refSix.pricePerNight = 7200;
refSix.hasConferenceHall = true;
refSix.hasLaundryService = true;


System.out.println("The hotelId is: " + refSix.hotelId);
System.out.println("The hotelName is: " + refSix.hotelName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfRooms is: " + refSix.numberOfRooms);
System.out.println("The numberOfFloors is: " + refSix.numberOfFloors);
System.out.println("The hasRestaurant is: " + refSix.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refSix.hasSwimmingPool);
System.out.println("The hasGym is: " + refSix.hasGym);
System.out.println("The hasSpa is: " + refSix.hasSpa);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasBar is: " + refSix.hasBar);
System.out.println("The rating is: " + refSix.rating);
System.out.println("The ownerName is: " + refSix.ownerName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The hotelType is: " + refSix.hotelType);
System.out.println("The pricePerNight is: " + refSix.pricePerNight);
System.out.println("The hasConferenceHall is: " + refSix.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refSix.hasLaundryService);
Hotel refSeven = new Hotel();

System.out.println("The hotelId is: " + refSeven.hotelId);
System.out.println("The hotelName is: " + refSeven.hotelName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfRooms is: " + refSeven.numberOfRooms);
System.out.println("The numberOfFloors is: " + refSeven.numberOfFloors);
System.out.println("The hasRestaurant is: " + refSeven.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refSeven.hasSwimmingPool);
System.out.println("The hasGym is: " + refSeven.hasGym);
System.out.println("The hasSpa is: " + refSeven.hasSpa);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasBar is: " + refSeven.hasBar);
System.out.println("The rating is: " + refSeven.rating);
System.out.println("The ownerName is: " + refSeven.ownerName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The hotelType is: " + refSeven.hotelType);
System.out.println("The pricePerNight is: " + refSeven.pricePerNight);
System.out.println("The hasConferenceHall is: " + refSeven.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refSeven.hasLaundryService);


refSeven.hotelId = 7;
refSeven.hotelName = "Green Valley Hotel";
refSeven.location = "Hill Road";
refSeven.city = "Ooty";
refSeven.state = "Tamil Nadu";
refSeven.country = "India";
refSeven.numberOfRooms = 60;
refSeven.numberOfFloors = 4;
refSeven.hasRestaurant = true;
refSeven.hasSwimmingPool = false;
refSeven.hasGym = false;
refSeven.hasSpa = true;
refSeven.hasParking = true;
refSeven.hasWifi = true;
refSeven.hasBar = false;
refSeven.rating = 4;
refSeven.ownerName = "Prakash Nair";
refSeven.establishedYear = 2014;
refSeven.contactNumber = "9874563210";
refSeven.email = "info@greenvalley.com";
refSeven.website = "www.greenvalleyhotel.com";
refSeven.hotelType = "Resort";
refSeven.pricePerNight = 4100;
refSeven.hasConferenceHall = false;
refSeven.hasLaundryService = true;


System.out.println("The hotelId is: " + refSeven.hotelId);
System.out.println("The hotelName is: " + refSeven.hotelName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfRooms is: " + refSeven.numberOfRooms);
System.out.println("The numberOfFloors is: " + refSeven.numberOfFloors);
System.out.println("The hasRestaurant is: " + refSeven.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refSeven.hasSwimmingPool);
System.out.println("The hasGym is: " + refSeven.hasGym);
System.out.println("The hasSpa is: " + refSeven.hasSpa);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasBar is: " + refSeven.hasBar);
System.out.println("The rating is: " + refSeven.rating);
System.out.println("The ownerName is: " + refSeven.ownerName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The hotelType is: " + refSeven.hotelType);
System.out.println("The pricePerNight is: " + refSeven.pricePerNight);
System.out.println("The hasConferenceHall is: " + refSeven.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refSeven.hasLaundryService);
Hotel refEight = new Hotel();

System.out.println("The hotelId is: " + refEight.hotelId);
System.out.println("The hotelName is: " + refEight.hotelName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfRooms is: " + refEight.numberOfRooms);
System.out.println("The numberOfFloors is: " + refEight.numberOfFloors);
System.out.println("The hasRestaurant is: " + refEight.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refEight.hasSwimmingPool);
System.out.println("The hasGym is: " + refEight.hasGym);
System.out.println("The hasSpa is: " + refEight.hasSpa);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasBar is: " + refEight.hasBar);
System.out.println("The rating is: " + refEight.rating);
System.out.println("The ownerName is: " + refEight.ownerName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The hotelType is: " + refEight.hotelType);
System.out.println("The pricePerNight is: " + refEight.pricePerNight);
System.out.println("The hasConferenceHall is: " + refEight.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refEight.hasLaundryService);


refEight.hotelId = 8;
refEight.hotelName = "Ocean Breeze Hotel";
refEight.location = "Marine Drive";
refEight.city = "Kochi";
refEight.state = "Kerala";
refEight.country = "India";
refEight.numberOfRooms = 85;
refEight.numberOfFloors = 7;
refEight.hasRestaurant = true;
refEight.hasSwimmingPool = true;
refEight.hasGym = true;
refEight.hasSpa = false;
refEight.hasParking = true;
refEight.hasWifi = true;
refEight.hasBar = true;
refEight.rating = 4;
refEight.ownerName = "Joseph Mathew";
refEight.establishedYear = 2017;
refEight.contactNumber = "9873216540";
refEight.email = "info@oceanbreeze.com";
refEight.website = "www.oceanbreezehotel.com";
refEight.hotelType = "Luxury";
refEight.pricePerNight = 5400;
refEight.hasConferenceHall = true;
refEight.hasLaundryService = true;


System.out.println("The hotelId is: " + refEight.hotelId);
System.out.println("The hotelName is: " + refEight.hotelName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfRooms is: " + refEight.numberOfRooms);
System.out.println("The numberOfFloors is: " + refEight.numberOfFloors);
System.out.println("The hasRestaurant is: " + refEight.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refEight.hasSwimmingPool);
System.out.println("The hasGym is: " + refEight.hasGym);
System.out.println("The hasSpa is: " + refEight.hasSpa);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasBar is: " + refEight.hasBar);
System.out.println("The rating is: " + refEight.rating);
System.out.println("The ownerName is: " + refEight.ownerName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The hotelType is: " + refEight.hotelType);
System.out.println("The pricePerNight is: " + refEight.pricePerNight);
System.out.println("The hasConferenceHall is: " + refEight.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refEight.hasLaundryService);
Hotel refNine = new Hotel();

System.out.println("The hotelId is: " + refNine.hotelId);
System.out.println("The hotelName is: " + refNine.hotelName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfRooms is: " + refNine.numberOfRooms);
System.out.println("The numberOfFloors is: " + refNine.numberOfFloors);
System.out.println("The hasRestaurant is: " + refNine.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refNine.hasSwimmingPool);
System.out.println("The hasGym is: " + refNine.hasGym);
System.out.println("The hasSpa is: " + refNine.hasSpa);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasBar is: " + refNine.hasBar);
System.out.println("The rating is: " + refNine.rating);
System.out.println("The ownerName is: " + refNine.ownerName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The hotelType is: " + refNine.hotelType);
System.out.println("The pricePerNight is: " + refNine.pricePerNight);
System.out.println("The hasConferenceHall is: " + refNine.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refNine.hasLaundryService);


refNine.hotelId = 9;
refNine.hotelName = "Golden Crown Hotel";
refNine.location = "Central Avenue";
refNine.city = "Pune";
refNine.state = "Maharashtra";
refNine.country = "India";
refNine.numberOfRooms = 100;
refNine.numberOfFloors = 9;
refNine.hasRestaurant = true;
refNine.hasSwimmingPool = true;
refNine.hasGym = true;
refNine.hasSpa = true;
refNine.hasParking = true;
refNine.hasWifi = true;
refNine.hasBar = true;
refNine.rating = 5;
refNine.ownerName = "Amit Desai";
refNine.establishedYear = 2020;
refNine.contactNumber = "9988123456";
refNine.email = "info@goldencrown.com";
refNine.website = "www.goldencrownhotel.com";
refNine.hotelType = "Luxury";
refNine.pricePerNight = 6800;
refNine.hasConferenceHall = true;
refNine.hasLaundryService = true;


System.out.println("The hotelId is: " + refNine.hotelId);
System.out.println("The hotelName is: " + refNine.hotelName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfRooms is: " + refNine.numberOfRooms);
System.out.println("The numberOfFloors is: " + refNine.numberOfFloors);
System.out.println("The hasRestaurant is: " + refNine.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refNine.hasSwimmingPool);
System.out.println("The hasGym is: " + refNine.hasGym);
System.out.println("The hasSpa is: " + refNine.hasSpa);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasBar is: " + refNine.hasBar);
System.out.println("The rating is: " + refNine.rating);
System.out.println("The ownerName is: " + refNine.ownerName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The hotelType is: " + refNine.hotelType);
System.out.println("The pricePerNight is: " + refNine.pricePerNight);
System.out.println("The hasConferenceHall is: " + refNine.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refNine.hasLaundryService);
Hotel refTen = new Hotel();

System.out.println("The hotelId is: " + refTen.hotelId);
System.out.println("The hotelName is: " + refTen.hotelName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfRooms is: " + refTen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refTen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refTen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refTen.hasSwimmingPool);
System.out.println("The hasGym is: " + refTen.hasGym);
System.out.println("The hasSpa is: " + refTen.hasSpa);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasBar is: " + refTen.hasBar);
System.out.println("The rating is: " + refTen.rating);
System.out.println("The ownerName is: " + refTen.ownerName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The hotelType is: " + refTen.hotelType);
System.out.println("The pricePerNight is: " + refTen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refTen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refTen.hasLaundryService);


refTen.hotelId = 10;
refTen.hotelName = "Silver Star Hotel";
refTen.location = "Station Road";
refTen.city = "Delhi";
refTen.state = "Delhi";
refTen.country = "India";
refTen.numberOfRooms = 90;
refTen.numberOfFloors = 8;
refTen.hasRestaurant = true;
refTen.hasSwimmingPool = false;
refTen.hasGym = true;
refTen.hasSpa = false;
refTen.hasParking = true;
refTen.hasWifi = true;
refTen.hasBar = true;
refTen.rating = 4;
refTen.ownerName = "Rahul Kapoor";
refTen.establishedYear = 2013;
refTen.contactNumber = "9876541230";
refTen.email = "info@silverstar.com";
refTen.website = "www.silverstarhotel.com";
refTen.hotelType = "Business";
refTen.pricePerNight = 3600;
refTen.hasConferenceHall = true;
refTen.hasLaundryService = true;


System.out.println("The hotelId is: " + refTen.hotelId);
System.out.println("The hotelName is: " + refTen.hotelName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfRooms is: " + refTen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refTen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refTen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refTen.hasSwimmingPool);
System.out.println("The hasGym is: " + refTen.hasGym);
System.out.println("The hasSpa is: " + refTen.hasSpa);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasBar is: " + refTen.hasBar);
System.out.println("The rating is: " + refTen.rating);
System.out.println("The ownerName is: " + refTen.ownerName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The hotelType is: " + refTen.hotelType);
System.out.println("The pricePerNight is: " + refTen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refTen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refTen.hasLaundryService);
Hotel refEleven = new Hotel();

System.out.println("The hotelId is: " + refEleven.hotelId);
System.out.println("The hotelName is: " + refEleven.hotelName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfRooms is: " + refEleven.numberOfRooms);
System.out.println("The numberOfFloors is: " + refEleven.numberOfFloors);
System.out.println("The hasRestaurant is: " + refEleven.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refEleven.hasSwimmingPool);
System.out.println("The hasGym is: " + refEleven.hasGym);
System.out.println("The hasSpa is: " + refEleven.hasSpa);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasBar is: " + refEleven.hasBar);
System.out.println("The rating is: " + refEleven.rating);
System.out.println("The ownerName is: " + refEleven.ownerName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The hotelType is: " + refEleven.hotelType);
System.out.println("The pricePerNight is: " + refEleven.pricePerNight);
System.out.println("The hasConferenceHall is: " + refEleven.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refEleven.hasLaundryService);


refEleven.hotelId = 11;
refEleven.hotelName = "Emerald Grand Hotel";
refEleven.location = "Park Street";
refEleven.city = "Kolkata";
refEleven.state = "West Bengal";
refEleven.country = "India";
refEleven.numberOfRooms = 130;
refEleven.numberOfFloors = 11;
refEleven.hasRestaurant = true;
refEleven.hasSwimmingPool = true;
refEleven.hasGym = true;
refEleven.hasSpa = true;
refEleven.hasParking = true;
refEleven.hasWifi = true;
refEleven.hasBar = true;
refEleven.rating = 5;
refEleven.ownerName = "Arjun Mehta";
refEleven.establishedYear = 2021;
refEleven.contactNumber = "9123456789";
refEleven.email = "info@emeraldgrand.com";
refEleven.website = "www.emeraldgrandhotel.com";
refEleven.hotelType = "Luxury";
refEleven.pricePerNight = 7500;
refEleven.hasConferenceHall = true;
refEleven.hasLaundryService = true;


System.out.println("The hotelId is: " + refEleven.hotelId);
System.out.println("The hotelName is: " + refEleven.hotelName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfRooms is: " + refEleven.numberOfRooms);
System.out.println("The numberOfFloors is: " + refEleven.numberOfFloors);
System.out.println("The hasRestaurant is: " + refEleven.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refEleven.hasSwimmingPool);
System.out.println("The hasGym is: " + refEleven.hasGym);
System.out.println("The hasSpa is: " + refEleven.hasSpa);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasBar is: " + refEleven.hasBar);
System.out.println("The rating is: " + refEleven.rating);
System.out.println("The ownerName is: " + refEleven.ownerName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The hotelType is: " + refEleven.hotelType);
System.out.println("The pricePerNight is: " + refEleven.pricePerNight);
System.out.println("The hasConferenceHall is: " + refEleven.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refEleven.hasLaundryService);
Hotel refTwelve = new Hotel();

System.out.println("The hotelId is: " + refTwelve.hotelId);
System.out.println("The hotelName is: " + refTwelve.hotelName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfRooms is: " + refTwelve.numberOfRooms);
System.out.println("The numberOfFloors is: " + refTwelve.numberOfFloors);
System.out.println("The hasRestaurant is: " + refTwelve.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refTwelve.hasSwimmingPool);
System.out.println("The hasGym is: " + refTwelve.hasGym);
System.out.println("The hasSpa is: " + refTwelve.hasSpa);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasBar is: " + refTwelve.hasBar);
System.out.println("The rating is: " + refTwelve.rating);
System.out.println("The ownerName is: " + refTwelve.ownerName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The hotelType is: " + refTwelve.hotelType);
System.out.println("The pricePerNight is: " + refTwelve.pricePerNight);
System.out.println("The hasConferenceHall is: " + refTwelve.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refTwelve.hasLaundryService);


refTwelve.hotelId = 12;
refTwelve.hotelName = "Palm Tree Hotel";
refTwelve.location = "Ring Road";
refTwelve.city = "Ahmedabad";
refTwelve.state = "Gujarat";
refTwelve.country = "India";
refTwelve.numberOfRooms = 75;
refTwelve.numberOfFloors = 6;
refTwelve.hasRestaurant = true;
refTwelve.hasSwimmingPool = false;
refTwelve.hasGym = true;
refTwelve.hasSpa = false;
refTwelve.hasParking = true;
refTwelve.hasWifi = true;
refTwelve.hasBar = false;
refTwelve.rating = 3;
refTwelve.ownerName = "Raj Patel";
refTwelve.establishedYear = 2011;
refTwelve.contactNumber = "9011223344";
refTwelve.email = "info@palmtreehotel.com";
refTwelve.website = "www.palmtreehotel.com";
refTwelve.hotelType = "Budget";
refTwelve.pricePerNight = 2400;
refTwelve.hasConferenceHall = true;
refTwelve.hasLaundryService = true;


System.out.println("The hotelId is: " + refTwelve.hotelId);
System.out.println("The hotelName is: " + refTwelve.hotelName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfRooms is: " + refTwelve.numberOfRooms);
System.out.println("The numberOfFloors is: " + refTwelve.numberOfFloors);
System.out.println("The hasRestaurant is: " + refTwelve.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refTwelve.hasSwimmingPool);
System.out.println("The hasGym is: " + refTwelve.hasGym);
System.out.println("The hasSpa is: " + refTwelve.hasSpa);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasBar is: " + refTwelve.hasBar);
System.out.println("The rating is: " + refTwelve.rating);
System.out.println("The ownerName is: " + refTwelve.ownerName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The hotelType is: " + refTwelve.hotelType);
System.out.println("The pricePerNight is: " + refTwelve.pricePerNight);
System.out.println("The hasConferenceHall is: " + refTwelve.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refTwelve.hasLaundryService);
Hotel refThirteen = new Hotel();

System.out.println("The hotelId is: " + refThirteen.hotelId);
System.out.println("The hotelName is: " + refThirteen.hotelName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfRooms is: " + refThirteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refThirteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refThirteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refThirteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refThirteen.hasGym);
System.out.println("The hasSpa is: " + refThirteen.hasSpa);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasBar is: " + refThirteen.hasBar);
System.out.println("The rating is: " + refThirteen.rating);
System.out.println("The ownerName is: " + refThirteen.ownerName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The hotelType is: " + refThirteen.hotelType);
System.out.println("The pricePerNight is: " + refThirteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refThirteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refThirteen.hasLaundryService);


refThirteen.hotelId = 13;
refThirteen.hotelName = "Crystal Lake Hotel";
refThirteen.location = "Lake Road";
refThirteen.city = "Udaipur";
refThirteen.state = "Rajasthan";
refThirteen.country = "India";
refThirteen.numberOfRooms = 65;
refThirteen.numberOfFloors = 5;
refThirteen.hasRestaurant = true;
refThirteen.hasSwimmingPool = true;
refThirteen.hasGym = false;
refThirteen.hasSpa = true;
refThirteen.hasParking = true;
refThirteen.hasWifi = true;
refThirteen.hasBar = false;
refThirteen.rating = 4;
refThirteen.ownerName = "Vikram Singh";
refThirteen.establishedYear = 2016;
refThirteen.contactNumber = "9871234560";
refThirteen.email = "info@crystallakehotel.com";
refThirteen.website = "www.crystallakehotel.com";
refThirteen.hotelType = "Resort";
refThirteen.pricePerNight = 4300;
refThirteen.hasConferenceHall = true;
refThirteen.hasLaundryService = true;


System.out.println("The hotelId is: " + refThirteen.hotelId);
System.out.println("The hotelName is: " + refThirteen.hotelName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfRooms is: " + refThirteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refThirteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refThirteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refThirteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refThirteen.hasGym);
System.out.println("The hasSpa is: " + refThirteen.hasSpa);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasBar is: " + refThirteen.hasBar);
System.out.println("The rating is: " + refThirteen.rating);
System.out.println("The ownerName is: " + refThirteen.ownerName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The hotelType is: " + refThirteen.hotelType);
System.out.println("The pricePerNight is: " + refThirteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refThirteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refThirteen.hasLaundryService);
Hotel refFourteen = new Hotel();

System.out.println("The hotelId is: " + refFourteen.hotelId);
System.out.println("The hotelName is: " + refFourteen.hotelName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfRooms is: " + refFourteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refFourteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refFourteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refFourteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refFourteen.hasGym);
System.out.println("The hasSpa is: " + refFourteen.hasSpa);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasBar is: " + refFourteen.hasBar);
System.out.println("The rating is: " + refFourteen.rating);
System.out.println("The ownerName is: " + refFourteen.ownerName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The hotelType is: " + refFourteen.hotelType);
System.out.println("The pricePerNight is: " + refFourteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refFourteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refFourteen.hasLaundryService);


refFourteen.hotelId = 14;
refFourteen.hotelName = "Mountain View Hotel";
refFourteen.location = "Hill Top Road";
refFourteen.city = "Manali";
refFourteen.state = "Himachal Pradesh";
refFourteen.country = "India";
refFourteen.numberOfRooms = 55;
refFourteen.numberOfFloors = 4;
refFourteen.hasRestaurant = true;
refFourteen.hasSwimmingPool = false;
refFourteen.hasGym = false;
refFourteen.hasSpa = true;
refFourteen.hasParking = true;
refFourteen.hasWifi = true;
refFourteen.hasBar = false;
refFourteen.rating = 4;
refFourteen.ownerName = "Rohit Sharma";
refFourteen.establishedYear = 2015;
refFourteen.contactNumber = "9898989898";
refFourteen.email = "info@mountainview.com";
refFourteen.website = "www.mountainviewhotel.com";
refFourteen.hotelType = "Resort";
refFourteen.pricePerNight = 3900;
refFourteen.hasConferenceHall = false;
refFourteen.hasLaundryService = true;


System.out.println("The hotelId is: " + refFourteen.hotelId);
System.out.println("The hotelName is: " + refFourteen.hotelName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfRooms is: " + refFourteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refFourteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refFourteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refFourteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refFourteen.hasGym);
System.out.println("The hasSpa is: " + refFourteen.hasSpa);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasBar is: " + refFourteen.hasBar);
System.out.println("The rating is: " + refFourteen.rating);
System.out.println("The ownerName is: " + refFourteen.ownerName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The hotelType is: " + refFourteen.hotelType);
System.out.println("The pricePerNight is: " + refFourteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refFourteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refFourteen.hasLaundryService);
Hotel refFifteen = new Hotel();

System.out.println("The hotelId is: " + refFifteen.hotelId);
System.out.println("The hotelName is: " + refFifteen.hotelName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfRooms is: " + refFifteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refFifteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refFifteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refFifteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refFifteen.hasGym);
System.out.println("The hasSpa is: " + refFifteen.hasSpa);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasBar is: " + refFifteen.hasBar);
System.out.println("The rating is: " + refFifteen.rating);
System.out.println("The ownerName is: " + refFifteen.ownerName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The hotelType is: " + refFifteen.hotelType);
System.out.println("The pricePerNight is: " + refFifteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refFifteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refFifteen.hasLaundryService);


refFifteen.hotelId = 15;
refFifteen.hotelName = "Sunset Paradise Hotel";
refFifteen.location = "Beach Avenue";
refFifteen.city = "Goa";
refFifteen.state = "Goa";
refFifteen.country = "India";
refFifteen.numberOfRooms = 120;
refFifteen.numberOfFloors = 10;
refFifteen.hasRestaurant = true;
refFifteen.hasSwimmingPool = true;
refFifteen.hasGym = true;
refFifteen.hasSpa = true;
refFifteen.hasParking = true;
refFifteen.hasWifi = true;
refFifteen.hasBar = true;
refFifteen.rating = 5;
refFifteen.ownerName = "Anthony Dsouza";
refFifteen.establishedYear = 2019;
refFifteen.contactNumber = "9001122334";
refFifteen.email = "info@sunsetparadise.com";
refFifteen.website = "www.sunsetparadisehotel.com";
refFifteen.hotelType = "Luxury";
refFifteen.pricePerNight = 8200;
refFifteen.hasConferenceHall = true;
refFifteen.hasLaundryService = true;


System.out.println("The hotelId is: " + refFifteen.hotelId);
System.out.println("The hotelName is: " + refFifteen.hotelName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfRooms is: " + refFifteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refFifteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refFifteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refFifteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refFifteen.hasGym);
System.out.println("The hasSpa is: " + refFifteen.hasSpa);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasBar is: " + refFifteen.hasBar);
System.out.println("The rating is: " + refFifteen.rating);
System.out.println("The ownerName is: " + refFifteen.ownerName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The hotelType is: " + refFifteen.hotelType);
System.out.println("The pricePerNight is: " + refFifteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refFifteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refFifteen.hasLaundryService);
Hotel refSixteen = new Hotel();

System.out.println("The hotelId is: " + refSixteen.hotelId);
System.out.println("The hotelName is: " + refSixteen.hotelName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfRooms is: " + refSixteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refSixteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refSixteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refSixteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refSixteen.hasGym);
System.out.println("The hasSpa is: " + refSixteen.hasSpa);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasBar is: " + refSixteen.hasBar);
System.out.println("The rating is: " + refSixteen.rating);
System.out.println("The ownerName is: " + refSixteen.ownerName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The hotelType is: " + refSixteen.hotelType);
System.out.println("The pricePerNight is: " + refSixteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refSixteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refSixteen.hasLaundryService);


refSixteen.hotelId = 16;
refSixteen.hotelName = "River Side Hotel";
refSixteen.location = "River Bank Road";
refSixteen.city = "Varanasi";
refSixteen.state = "Uttar Pradesh";
refSixteen.country = "India";
refSixteen.numberOfRooms = 68;
refSixteen.numberOfFloors = 6;
refSixteen.hasRestaurant = true;
refSixteen.hasSwimmingPool = false;
refSixteen.hasGym = false;
refSixteen.hasSpa = false;
refSixteen.hasParking = true;
refSixteen.hasWifi = true;
refSixteen.hasBar = false;
refSixteen.rating = 3;
refSixteen.ownerName = "Sanjay Mishra";
refSixteen.establishedYear = 2012;
refSixteen.contactNumber = "9123456700";
refSixteen.email = "info@riversidehotel.com";
refSixteen.website = "www.riversidehotel.com";
refSixteen.hotelType = "Budget";
refSixteen.pricePerNight = 2100;
refSixteen.hasConferenceHall = true;
refSixteen.hasLaundryService = true;


System.out.println("The hotelId is: " + refSixteen.hotelId);
System.out.println("The hotelName is: " + refSixteen.hotelName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfRooms is: " + refSixteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refSixteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refSixteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refSixteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refSixteen.hasGym);
System.out.println("The hasSpa is: " + refSixteen.hasSpa);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasBar is: " + refSixteen.hasBar);
System.out.println("The rating is: " + refSixteen.rating);
System.out.println("The ownerName is: " + refSixteen.ownerName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The hotelType is: " + refSixteen.hotelType);
System.out.println("The pricePerNight is: " + refSixteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refSixteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refSixteen.hasLaundryService);
Hotel refSeventeen = new Hotel();

System.out.println("The hotelId is: " + refSeventeen.hotelId);
System.out.println("The hotelName is: " + refSeventeen.hotelName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfRooms is: " + refSeventeen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refSeventeen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refSeventeen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refSeventeen.hasSwimmingPool);
System.out.println("The hasGym is: " + refSeventeen.hasGym);
System.out.println("The hasSpa is: " + refSeventeen.hasSpa);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasBar is: " + refSeventeen.hasBar);
System.out.println("The rating is: " + refSeventeen.rating);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The hotelType is: " + refSeventeen.hotelType);
System.out.println("The pricePerNight is: " + refSeventeen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refSeventeen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refSeventeen.hasLaundryService);


refSeventeen.hotelId = 17;
refSeventeen.hotelName = "City Lights Hotel";
refSeventeen.location = "Downtown Street";
refSeventeen.city = "Mumbai";
refSeventeen.state = "Maharashtra";
refSeventeen.country = "India";
refSeventeen.numberOfRooms = 150;
refSeventeen.numberOfFloors = 14;
refSeventeen.hasRestaurant = true;
refSeventeen.hasSwimmingPool = true;
refSeventeen.hasGym = true;
refSeventeen.hasSpa = false;
refSeventeen.hasParking = true;
refSeventeen.hasWifi = true;
refSeventeen.hasBar = true;
refSeventeen.rating = 5;
refSeventeen.ownerName = "Rakesh Shah";
refSeventeen.establishedYear = 2018;
refSeventeen.contactNumber = "9876547890";
refSeventeen.email = "info@citylightshotel.com";
refSeventeen.website = "www.citylightshotel.com";
refSeventeen.hotelType = "Luxury";
refSeventeen.pricePerNight = 6900;
refSeventeen.hasConferenceHall = true;
refSeventeen.hasLaundryService = true;


System.out.println("The hotelId is: " + refSeventeen.hotelId);
System.out.println("The hotelName is: " + refSeventeen.hotelName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfRooms is: " + refSeventeen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refSeventeen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refSeventeen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refSeventeen.hasSwimmingPool);
System.out.println("The hasGym is: " + refSeventeen.hasGym);
System.out.println("The hasSpa is: " + refSeventeen.hasSpa);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasBar is: " + refSeventeen.hasBar);
System.out.println("The rating is: " + refSeventeen.rating);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The hotelType is: " + refSeventeen.hotelType);
System.out.println("The pricePerNight is: " + refSeventeen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refSeventeen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refSeventeen.hasLaundryService);
Hotel refEighteen = new Hotel();

System.out.println("The hotelId is: " + refEighteen.hotelId);
System.out.println("The hotelName is: " + refEighteen.hotelName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfRooms is: " + refEighteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refEighteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refEighteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refEighteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refEighteen.hasGym);
System.out.println("The hasSpa is: " + refEighteen.hasSpa);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasBar is: " + refEighteen.hasBar);
System.out.println("The rating is: " + refEighteen.rating);
System.out.println("The ownerName is: " + refEighteen.ownerName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The hotelType is: " + refEighteen.hotelType);
System.out.println("The pricePerNight is: " + refEighteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refEighteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refEighteen.hasLaundryService);


refEighteen.hotelId = 18;
refEighteen.hotelName = "Royal Heritage Hotel";
refEighteen.location = "Fort Road";
refEighteen.city = "Jaipur";
refEighteen.state = "Rajasthan";
refEighteen.country = "India";
refEighteen.numberOfRooms = 90;
refEighteen.numberOfFloors = 7;
refEighteen.hasRestaurant = true;
refEighteen.hasSwimmingPool = true;
refEighteen.hasGym = false;
refEighteen.hasSpa = true;
refEighteen.hasParking = true;
refEighteen.hasWifi = true;
refEighteen.hasBar = true;
refEighteen.rating = 4;
refEighteen.ownerName = "Rajveer Singh";
refEighteen.establishedYear = 2014;
refEighteen.contactNumber = "9786543210";
refEighteen.email = "info@royalheritage.com";
refEighteen.website = "www.royalheritagehotel.com";
refEighteen.hotelType = "Heritage";
refEighteen.pricePerNight = 4700;
refEighteen.hasConferenceHall = true;
refEighteen.hasLaundryService = true;


System.out.println("The hotelId is: " + refEighteen.hotelId);
System.out.println("The hotelName is: " + refEighteen.hotelName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfRooms is: " + refEighteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refEighteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refEighteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refEighteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refEighteen.hasGym);
System.out.println("The hasSpa is: " + refEighteen.hasSpa);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasBar is: " + refEighteen.hasBar);
System.out.println("The rating is: " + refEighteen.rating);
System.out.println("The ownerName is: " + refEighteen.ownerName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The hotelType is: " + refEighteen.hotelType);
System.out.println("The pricePerNight is: " + refEighteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refEighteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refEighteen.hasLaundryService);
Hotel refNineteen = new Hotel();

System.out.println("The hotelId is: " + refNineteen.hotelId);
System.out.println("The hotelName is: " + refNineteen.hotelName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfRooms is: " + refNineteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refNineteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refNineteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refNineteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refNineteen.hasGym);
System.out.println("The hasSpa is: " + refNineteen.hasSpa);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasBar is: " + refNineteen.hasBar);
System.out.println("The rating is: " + refNineteen.rating);
System.out.println("The ownerName is: " + refNineteen.ownerName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The hotelType is: " + refNineteen.hotelType);
System.out.println("The pricePerNight is: " + refNineteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refNineteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refNineteen.hasLaundryService);


refNineteen.hotelId = 19;
refNineteen.hotelName = "Skyline Tower Hotel";
refNineteen.location = "Business Park";
refNineteen.city = "Gurgaon";
refNineteen.state = "Haryana";
refNineteen.country = "India";
refNineteen.numberOfRooms = 140;
refNineteen.numberOfFloors = 13;
refNineteen.hasRestaurant = true;
refNineteen.hasSwimmingPool = true;
refNineteen.hasGym = true;
refNineteen.hasSpa = false;
refNineteen.hasParking = true;
refNineteen.hasWifi = true;
refNineteen.hasBar = true;
refNineteen.rating = 5;
refNineteen.ownerName = "Vikash Gupta";
refNineteen.establishedYear = 2017;
refNineteen.contactNumber = "9890011223";
refNineteen.email = "info@skylinetower.com";
refNineteen.website = "www.skylinetowerhotel.com";
refNineteen.hotelType = "Business";
refNineteen.pricePerNight = 6400;
refNineteen.hasConferenceHall = true;
refNineteen.hasLaundryService = true;


System.out.println("The hotelId is: " + refNineteen.hotelId);
System.out.println("The hotelName is: " + refNineteen.hotelName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfRooms is: " + refNineteen.numberOfRooms);
System.out.println("The numberOfFloors is: " + refNineteen.numberOfFloors);
System.out.println("The hasRestaurant is: " + refNineteen.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refNineteen.hasSwimmingPool);
System.out.println("The hasGym is: " + refNineteen.hasGym);
System.out.println("The hasSpa is: " + refNineteen.hasSpa);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasBar is: " + refNineteen.hasBar);
System.out.println("The rating is: " + refNineteen.rating);
System.out.println("The ownerName is: " + refNineteen.ownerName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The hotelType is: " + refNineteen.hotelType);
System.out.println("The pricePerNight is: " + refNineteen.pricePerNight);
System.out.println("The hasConferenceHall is: " + refNineteen.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refNineteen.hasLaundryService);
Hotel refTwenty = new Hotel();

System.out.println("The hotelId is: " + refTwenty.hotelId);
System.out.println("The hotelName is: " + refTwenty.hotelName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfRooms is: " + refTwenty.numberOfRooms);
System.out.println("The numberOfFloors is: " + refTwenty.numberOfFloors);
System.out.println("The hasRestaurant is: " + refTwenty.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refTwenty.hasSwimmingPool);
System.out.println("The hasGym is: " + refTwenty.hasGym);
System.out.println("The hasSpa is: " + refTwenty.hasSpa);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasBar is: " + refTwenty.hasBar);
System.out.println("The rating is: " + refTwenty.rating);
System.out.println("The ownerName is: " + refTwenty.ownerName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The hotelType is: " + refTwenty.hotelType);
System.out.println("The pricePerNight is: " + refTwenty.pricePerNight);
System.out.println("The hasConferenceHall is: " + refTwenty.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refTwenty.hasLaundryService);


refTwenty.hotelId = 20;
refTwenty.hotelName = "Grand Horizon Hotel";
refTwenty.location = "IT Park Road";
refTwenty.city = "Bangalore";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.numberOfRooms = 160;
refTwenty.numberOfFloors = 15;
refTwenty.hasRestaurant = true;
refTwenty.hasSwimmingPool = true;
refTwenty.hasGym = true;
refTwenty.hasSpa = true;
refTwenty.hasParking = true;
refTwenty.hasWifi = true;
refTwenty.hasBar = true;
refTwenty.rating = 5;
refTwenty.ownerName = "Arvind Rao";
refTwenty.establishedYear = 2022;
refTwenty.contactNumber = "9876001122";
refTwenty.email = "info@grandhorizon.com";
refTwenty.website = "www.grandhorizonhotel.com";
refTwenty.hotelType = "Luxury";
refTwenty.pricePerNight = 9000;
refTwenty.hasConferenceHall = true;
refTwenty.hasLaundryService = true;


System.out.println("The hotelId is: " + refTwenty.hotelId);
System.out.println("The hotelName is: " + refTwenty.hotelName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfRooms is: " + refTwenty.numberOfRooms);
System.out.println("The numberOfFloors is: " + refTwenty.numberOfFloors);
System.out.println("The hasRestaurant is: " + refTwenty.hasRestaurant);
System.out.println("The hasSwimmingPool is: " + refTwenty.hasSwimmingPool);
System.out.println("The hasGym is: " + refTwenty.hasGym);
System.out.println("The hasSpa is: " + refTwenty.hasSpa);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasBar is: " + refTwenty.hasBar);
System.out.println("The rating is: " + refTwenty.rating);
System.out.println("The ownerName is: " + refTwenty.ownerName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The hotelType is: " + refTwenty.hotelType);
System.out.println("The pricePerNight is: " + refTwenty.pricePerNight);
System.out.println("The hasConferenceHall is: " + refTwenty.hasConferenceHall);
System.out.println("The hasLaundryService is: " + refTwenty.hasLaundryService);
}
}