class LaptopExecutor{
public static void main(String[] args){
Laptop refOne = new Laptop();

System.out.println("The brand is: " + refOne.brand);
System.out.println("The model is: " + refOne.model);
System.out.println("The color is: " + refOne.color);
System.out.println("The price is: " + refOne.price);
System.out.println("The ram is: " + refOne.ram);
System.out.println("The storage is: " + refOne.storage);
System.out.println("The processor is: " + refOne.processor);
System.out.println("The screenSize is: " + refOne.screenSize);
System.out.println("The operatingSystem is: " + refOne.operatingSystem);
System.out.println("The batteryCapacity is: " + refOne.batteryCapacity);
System.out.println("The hasFingerprint is: " + refOne.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refOne.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refOne.hasTouchScreen);
System.out.println("The hasWebcam is: " + refOne.hasWebcam);
System.out.println("The hasBluetooth is: " + refOne.hasBluetooth);
System.out.println("The hasWiFi is: " + refOne.hasWiFi);
System.out.println("The usbPorts is: " + refOne.usbPorts);
System.out.println("The hdmiPorts is: " + refOne.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refOne.hasEthernetPort);
System.out.println("The weight is: " + refOne.weight);
System.out.println("The graphicsCard is: " + refOne.graphicsCard);
System.out.println("The launchYear is: " + refOne.launchYear);
System.out.println("The manufacturerCountry is: " + refOne.manufacturerCountry);
System.out.println("The ownerName is: " + refOne.ownerName);

refOne.laptopId = 1;
refOne.brand = "Dell";
refOne.model = "XPS 13";
refOne.color = "Silver";
refOne.price = 120000;
refOne.ram = 16;
refOne.storage = 512;
refOne.processor = "Intel i7";
refOne.screenSize = 13.4;
refOne.operatingSystem = "Windows 11";
refOne.batteryCapacity = 5000;
refOne.hasFingerprint = true;
refOne.hasBacklitKeyboard = true;
refOne.hasTouchScreen = true;
refOne.hasWebcam = true;
refOne.hasBluetooth = true;
refOne.hasWiFi = true;
refOne.usbPorts = 3;
refOne.hdmiPorts = 1;
refOne.hasEthernetPort = false;
refOne.weight = 1;
refOne.graphicsCard = "Intel Iris Xe";
refOne.launchYear = 2023;
refOne.manufacturerCountry = "USA";
refOne.ownerName = "Rahul";

System.out.println("The laptopId is: " + refOne.laptopId);
System.out.println("The brand is: " + refOne.brand);
System.out.println("The model is: " + refOne.model);
System.out.println("The color is: " + refOne.color);
System.out.println("The price is: " + refOne.price);
System.out.println("The ram is: " + refOne.ram);
System.out.println("The storage is: " + refOne.storage);
System.out.println("The processor is: " + refOne.processor);
System.out.println("The screenSize is: " + refOne.screenSize);
System.out.println("The operatingSystem is: " + refOne.operatingSystem);
System.out.println("The batteryCapacity is: " + refOne.batteryCapacity);
System.out.println("The hasFingerprint is: " + refOne.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refOne.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refOne.hasTouchScreen);
System.out.println("The hasWebcam is: " + refOne.hasWebcam);
System.out.println("The hasBluetooth is: " + refOne.hasBluetooth);
System.out.println("The hasWiFi is: " + refOne.hasWiFi);
System.out.println("The usbPorts is: " + refOne.usbPorts);
System.out.println("The hdmiPorts is: " + refOne.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refOne.hasEthernetPort);
System.out.println("The weight is: " + refOne.weight);
System.out.println("The graphicsCard is: " + refOne.graphicsCard);
System.out.println("The launchYear is: " + refOne.launchYear);
System.out.println("The manufacturerCountry is: " + refOne.manufacturerCountry);
System.out.println("The ownerName is: " + refOne.ownerName);
Laptop refTwo = new Laptop();

System.out.println("The brand is: " + refTwo.brand);
System.out.println("The model is: " + refTwo.model);
System.out.println("The color is: " + refTwo.color);
System.out.println("The price is: " + refTwo.price);
System.out.println("The ram is: " + refTwo.ram);
System.out.println("The storage is: " + refTwo.storage);
System.out.println("The processor is: " + refTwo.processor);
System.out.println("The screenSize is: " + refTwo.screenSize);
System.out.println("The operatingSystem is: " + refTwo.operatingSystem);
System.out.println("The batteryCapacity is: " + refTwo.batteryCapacity);
System.out.println("The hasFingerprint is: " + refTwo.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refTwo.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refTwo.hasTouchScreen);
System.out.println("The hasWebcam is: " + refTwo.hasWebcam);
System.out.println("The hasBluetooth is: " + refTwo.hasBluetooth);
System.out.println("The hasWiFi is: " + refTwo.hasWiFi);
System.out.println("The usbPorts is: " + refTwo.usbPorts);
System.out.println("The hdmiPorts is: " + refTwo.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refTwo.hasEthernetPort);
System.out.println("The weight is: " + refTwo.weight);
System.out.println("The graphicsCard is: " + refTwo.graphicsCard);
System.out.println("The launchYear is: " + refTwo.launchYear);
System.out.println("The manufacturerCountry is: " + refTwo.manufacturerCountry);
System.out.println("The ownerName is: " + refTwo.ownerName);

refTwo.laptopId = 2;
refTwo.brand = "HP";
refTwo.model = "Pavilion 15";
refTwo.color = "Black";
refTwo.price = 65000;
refTwo.ram = 16;
refTwo.storage = 512;
refTwo.processor = "Intel i5";
refTwo.screenSize = 15.6;
refTwo.operatingSystem = "Windows 11";
refTwo.batteryCapacity = 4500;
refTwo.hasFingerprint = true;
refTwo.hasBacklitKeyboard = true;
refTwo.hasTouchScreen = false;
refTwo.hasWebcam = true;
refTwo.hasBluetooth = true;
refTwo.hasWiFi = true;
refTwo.usbPorts = 3;
refTwo.hdmiPorts = 1;
refTwo.hasEthernetPort = true;
refTwo.weight = 2;
refTwo.graphicsCard = "NVIDIA GTX 1650";
refTwo.launchYear = 2022;
refTwo.manufacturerCountry = "USA";
refTwo.ownerName = "Arjun";

System.out.println("The laptopId is: " + refTwo.laptopId);
System.out.println("The brand is: " + refTwo.brand);
System.out.println("The model is: " + refTwo.model);
System.out.println("The color is: " + refTwo.color);
System.out.println("The price is: " + refTwo.price);
System.out.println("The ram is: " + refTwo.ram);
System.out.println("The storage is: " + refTwo.storage);
System.out.println("The processor is: " + refTwo.processor);
System.out.println("The screenSize is: " + refTwo.screenSize);
System.out.println("The operatingSystem is: " + refTwo.operatingSystem);
System.out.println("The batteryCapacity is: " + refTwo.batteryCapacity);
System.out.println("The hasFingerprint is: " + refTwo.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refTwo.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refTwo.hasTouchScreen);
System.out.println("The hasWebcam is: " + refTwo.hasWebcam);
System.out.println("The hasBluetooth is: " + refTwo.hasBluetooth);
System.out.println("The hasWiFi is: " + refTwo.hasWiFi);
System.out.println("The usbPorts is: " + refTwo.usbPorts);
System.out.println("The hdmiPorts is: " + refTwo.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refTwo.hasEthernetPort);
System.out.println("The weight is: " + refTwo.weight);
System.out.println("The graphicsCard is: " + refTwo.graphicsCard);
System.out.println("The launchYear is: " + refTwo.launchYear);
System.out.println("The manufacturerCountry is: " + refTwo.manufacturerCountry);
System.out.println("The ownerName is: " + refTwo.ownerName);
Laptop refThree = new Laptop();

System.out.println("The brand is: " + refThree.brand);
System.out.println("The model is: " + refThree.model);
System.out.println("The color is: " + refThree.color);
System.out.println("The price is: " + refThree.price);
System.out.println("The ram is: " + refThree.ram);
System.out.println("The storage is: " + refThree.storage);
System.out.println("The processor is: " + refThree.processor);
System.out.println("The screenSize is: " + refThree.screenSize);
System.out.println("The operatingSystem is: " + refThree.operatingSystem);
System.out.println("The batteryCapacity is: " + refThree.batteryCapacity);
System.out.println("The hasFingerprint is: " + refThree.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refThree.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refThree.hasTouchScreen);
System.out.println("The hasWebcam is: " + refThree.hasWebcam);
System.out.println("The hasBluetooth is: " + refThree.hasBluetooth);
System.out.println("The hasWiFi is: " + refThree.hasWiFi);
System.out.println("The usbPorts is: " + refThree.usbPorts);
System.out.println("The hdmiPorts is: " + refThree.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refThree.hasEthernetPort);
System.out.println("The weight is: " + refThree.weight);
System.out.println("The graphicsCard is: " + refThree.graphicsCard);
System.out.println("The launchYear is: " + refThree.launchYear);
System.out.println("The manufacturerCountry is: " + refThree.manufacturerCountry);
System.out.println("The ownerName is: " + refThree.ownerName);

refThree.laptopId = 3;
refThree.brand = "Lenovo";
refThree.model = "ThinkPad E14";
refThree.color = "Black";
refThree.price = 70000;
refThree.ram = 16;
refThree.storage = 512;
refThree.processor = "Intel i7";
refThree.screenSize = 14.0;
refThree.operatingSystem = "Windows 11";
refThree.batteryCapacity = 4700;
refThree.hasFingerprint = true;
refThree.hasBacklitKeyboard = true;
refThree.hasTouchScreen = false;
refThree.hasWebcam = true;
refThree.hasBluetooth = true;
refThree.hasWiFi = true;
refThree.usbPorts = 3;
refThree.hdmiPorts = 1;
refThree.hasEthernetPort = true;
refThree.weight = 2;
refThree.graphicsCard = "Intel UHD Graphics";
refThree.launchYear = 2023;
refThree.manufacturerCountry = "China";
refThree.ownerName = "Suresh";

System.out.println("The laptopId is: " + refThree.laptopId);
System.out.println("The brand is: " + refThree.brand);
System.out.println("The model is: " + refThree.model);
System.out.println("The color is: " + refThree.color);
System.out.println("The price is: " + refThree.price);
System.out.println("The ram is: " + refThree.ram);
System.out.println("The storage is: " + refThree.storage);
System.out.println("The processor is: " + refThree.processor);
System.out.println("The screenSize is: " + refThree.screenSize);
System.out.println("The operatingSystem is: " + refThree.operatingSystem);
System.out.println("The batteryCapacity is: " + refThree.batteryCapacity);
System.out.println("The hasFingerprint is: " + refThree.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refThree.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refThree.hasTouchScreen);
System.out.println("The hasWebcam is: " + refThree.hasWebcam);
System.out.println("The hasBluetooth is: " + refThree.hasBluetooth);
System.out.println("The hasWiFi is: " + refThree.hasWiFi);
System.out.println("The usbPorts is: " + refThree.usbPorts);
System.out.println("The hdmiPorts is: " + refThree.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refThree.hasEthernetPort);
System.out.println("The weight is: " + refThree.weight);
System.out.println("The graphicsCard is: " + refThree.graphicsCard);
System.out.println("The launchYear is: " + refThree.launchYear);
System.out.println("The manufacturerCountry is: " + refThree.manufacturerCountry);
System.out.println("The ownerName is: " + refThree.ownerName);
Laptop refFour = new Laptop();

System.out.println("The brand is: " + refFour.brand);
System.out.println("The model is: " + refFour.model);
System.out.println("The color is: " + refFour.color);
System.out.println("The price is: " + refFour.price);
System.out.println("The ram is: " + refFour.ram);
System.out.println("The storage is: " + refFour.storage);
System.out.println("The processor is: " + refFour.processor);
System.out.println("The screenSize is: " + refFour.screenSize);
System.out.println("The operatingSystem is: " + refFour.operatingSystem);
System.out.println("The batteryCapacity is: " + refFour.batteryCapacity);
System.out.println("The hasFingerprint is: " + refFour.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refFour.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refFour.hasTouchScreen);
System.out.println("The hasWebcam is: " + refFour.hasWebcam);
System.out.println("The hasBluetooth is: " + refFour.hasBluetooth);
System.out.println("The hasWiFi is: " + refFour.hasWiFi);
System.out.println("The usbPorts is: " + refFour.usbPorts);
System.out.println("The hdmiPorts is: " + refFour.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refFour.hasEthernetPort);
System.out.println("The weight is: " + refFour.weight);
System.out.println("The graphicsCard is: " + refFour.graphicsCard);
System.out.println("The launchYear is: " + refFour.launchYear);
System.out.println("The manufacturerCountry is: " + refFour.manufacturerCountry);
System.out.println("The ownerName is: " + refFour.ownerName);

refFour.laptopId = 4;
refFour.brand = "Apple";
refFour.model = "MacBook Air M2";
refFour.color = "Space Gray";
refFour.price = 140000;
refFour.ram = 16;
refFour.storage = 512;
refFour.processor = "Apple M2";
refFour.screenSize = 13.6;
refFour.operatingSystem = "macOS";
refFour.batteryCapacity = 5000;
refFour.hasFingerprint = true;
refFour.hasBacklitKeyboard = true;
refFour.hasTouchScreen = false;
refFour.hasWebcam = true;
refFour.hasBluetooth = true;
refFour.hasWiFi = true;
refFour.usbPorts = 2;
refFour.hdmiPorts = 0;
refFour.hasEthernetPort = false;
refFour.weight = 1;
refFour.graphicsCard = "Apple Integrated GPU";
refFour.launchYear = 2023;
refFour.manufacturerCountry = "USA";
refFour.ownerName = "Kiran";

System.out.println("The laptopId is: " + refFour.laptopId);
System.out.println("The brand is: " + refFour.brand);
System.out.println("The model is: " + refFour.model);
System.out.println("The color is: " + refFour.color);
System.out.println("The price is: " + refFour.price);
System.out.println("The ram is: " + refFour.ram);
System.out.println("The storage is: " + refFour.storage);
System.out.println("The processor is: " + refFour.processor);
System.out.println("The screenSize is: " + refFour.screenSize);
System.out.println("The operatingSystem is: " + refFour.operatingSystem);
System.out.println("The batteryCapacity is: " + refFour.batteryCapacity);
System.out.println("The hasFingerprint is: " + refFour.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refFour.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refFour.hasTouchScreen);
System.out.println("The hasWebcam is: " + refFour.hasWebcam);
System.out.println("The hasBluetooth is: " + refFour.hasBluetooth);
System.out.println("The hasWiFi is: " + refFour.hasWiFi);
System.out.println("The usbPorts is: " + refFour.usbPorts);
System.out.println("The hdmiPorts is: " + refFour.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refFour.hasEthernetPort);
System.out.println("The weight is: " + refFour.weight);
System.out.println("The graphicsCard is: " + refFour.graphicsCard);
System.out.println("The launchYear is: " + refFour.launchYear);
System.out.println("The manufacturerCountry is: " + refFour.manufacturerCountry);
System.out.println("The ownerName is: " + refFour.ownerName);
Laptop refFive = new Laptop();

System.out.println("The brand is: " + refFive.brand);
System.out.println("The model is: " + refFive.model);
System.out.println("The color is: " + refFive.color);
System.out.println("The price is: " + refFive.price);
System.out.println("The ram is: " + refFive.ram);
System.out.println("The storage is: " + refFive.storage);
System.out.println("The processor is: " + refFive.processor);
System.out.println("The screenSize is: " + refFive.screenSize);
System.out.println("The operatingSystem is: " + refFive.operatingSystem);
System.out.println("The batteryCapacity is: " + refFive.batteryCapacity);
System.out.println("The hasFingerprint is: " + refFive.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refFive.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refFive.hasTouchScreen);
System.out.println("The hasWebcam is: " + refFive.hasWebcam);
System.out.println("The hasBluetooth is: " + refFive.hasBluetooth);
System.out.println("The hasWiFi is: " + refFive.hasWiFi);
System.out.println("The usbPorts is: " + refFive.usbPorts);
System.out.println("The hdmiPorts is: " + refFive.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refFive.hasEthernetPort);
System.out.println("The weight is: " + refFive.weight);
System.out.println("The graphicsCard is: " + refFive.graphicsCard);
System.out.println("The launchYear is: " + refFive.launchYear);
System.out.println("The manufacturerCountry is: " + refFive.manufacturerCountry);
System.out.println("The ownerName is: " + refFive.ownerName);

refFive.laptopId = 5;
refFive.brand = "Asus";
refFive.model = "ROG Zephyrus G14";
refFive.color = "Gray";
refFive.price = 150000;
refFive.ram = 16;
refFive.storage = 1024;
refFive.processor = "AMD Ryzen 9";
refFive.screenSize = 14.0;
refFive.operatingSystem = "Windows 11";
refFive.batteryCapacity = 4800;
refFive.hasFingerprint = true;
refFive.hasBacklitKeyboard = true;
refFive.hasTouchScreen = false;
refFive.hasWebcam = true;
refFive.hasBluetooth = true;
refFive.hasWiFi = true;
refFive.usbPorts = 4;
refFive.hdmiPorts = 1;
refFive.hasEthernetPort = false;
refFive.weight = 2;
refFive.graphicsCard = "NVIDIA RTX 4060";
refFive.launchYear = 2023;
refFive.manufacturerCountry = "Taiwan";
refFive.ownerName = "Deepak";

System.out.println("The laptopId is: " + refFive.laptopId);
System.out.println("The brand is: " + refFive.brand);
System.out.println("The model is: " + refFive.model);
System.out.println("The color is: " + refFive.color);
System.out.println("The price is: " + refFive.price);
System.out.println("The ram is: " + refFive.ram);
System.out.println("The storage is: " + refFive.storage);
System.out.println("The processor is: " + refFive.processor);
System.out.println("The screenSize is: " + refFive.screenSize);
System.out.println("The operatingSystem is: " + refFive.operatingSystem);
System.out.println("The batteryCapacity is: " + refFive.batteryCapacity);
System.out.println("The hasFingerprint is: " + refFive.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refFive.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refFive.hasTouchScreen);
System.out.println("The hasWebcam is: " + refFive.hasWebcam);
System.out.println("The hasBluetooth is: " + refFive.hasBluetooth);
System.out.println("The hasWiFi is: " + refFive.hasWiFi);
System.out.println("The usbPorts is: " + refFive.usbPorts);
System.out.println("The hdmiPorts is: " + refFive.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refFive.hasEthernetPort);
System.out.println("The weight is: " + refFive.weight);
System.out.println("The graphicsCard is: " + refFive.graphicsCard);
System.out.println("The launchYear is: " + refFive.launchYear);
System.out.println("The manufacturerCountry is: " + refFive.manufacturerCountry);
System.out.println("The ownerName is: " + refFive.ownerName);
Laptop refSix = new Laptop();

System.out.println("The brand is: " + refSix.brand);
System.out.println("The model is: " + refSix.model);
System.out.println("The color is: " + refSix.color);
System.out.println("The price is: " + refSix.price);
System.out.println("The ram is: " + refSix.ram);
System.out.println("The storage is: " + refSix.storage);
System.out.println("The processor is: " + refSix.processor);
System.out.println("The screenSize is: " + refSix.screenSize);
System.out.println("The operatingSystem is: " + refSix.operatingSystem);
System.out.println("The batteryCapacity is: " + refSix.batteryCapacity);
System.out.println("The hasFingerprint is: " + refSix.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refSix.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refSix.hasTouchScreen);
System.out.println("The hasWebcam is: " + refSix.hasWebcam);
System.out.println("The hasBluetooth is: " + refSix.hasBluetooth);
System.out.println("The hasWiFi is: " + refSix.hasWiFi);
System.out.println("The usbPorts is: " + refSix.usbPorts);
System.out.println("The hdmiPorts is: " + refSix.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refSix.hasEthernetPort);
System.out.println("The weight is: " + refSix.weight);
System.out.println("The graphicsCard is: " + refSix.graphicsCard);
System.out.println("The launchYear is: " + refSix.launchYear);
System.out.println("The manufacturerCountry is: " + refSix.manufacturerCountry);
System.out.println("The ownerName is: " + refSix.ownerName);

refSix.laptopId = 6;
refSix.brand = "Acer";
refSix.model = "Aspire 7";
refSix.color = "Black";
refSix.price = 75000;
refSix.ram = 16;
refSix.storage = 512;
refSix.processor = "AMD Ryzen 7";
refSix.screenSize = 15.6;
refSix.operatingSystem = "Windows 11";
refSix.batteryCapacity = 4600;
refSix.hasFingerprint = true;
refSix.hasBacklitKeyboard = true;
refSix.hasTouchScreen = false;
refSix.hasWebcam = true;
refSix.hasBluetooth = true;
refSix.hasWiFi = true;
refSix.usbPorts = 3;
refSix.hdmiPorts = 1;
refSix.hasEthernetPort = true;
refSix.weight = 2;
refSix.graphicsCard = "NVIDIA GTX 1650";
refSix.launchYear = 2022;
refSix.manufacturerCountry = "Taiwan";
refSix.ownerName = "Ravi";

System.out.println("The laptopId is: " + refSix.laptopId);
System.out.println("The brand is: " + refSix.brand);
System.out.println("The model is: " + refSix.model);
System.out.println("The color is: " + refSix.color);
System.out.println("The price is: " + refSix.price);
System.out.println("The ram is: " + refSix.ram);
System.out.println("The storage is: " + refSix.storage);
System.out.println("The processor is: " + refSix.processor);
System.out.println("The screenSize is: " + refSix.screenSize);
System.out.println("The operatingSystem is: " + refSix.operatingSystem);
System.out.println("The batteryCapacity is: " + refSix.batteryCapacity);
System.out.println("The hasFingerprint is: " + refSix.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refSix.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refSix.hasTouchScreen);
System.out.println("The hasWebcam is: " + refSix.hasWebcam);
System.out.println("The hasBluetooth is: " + refSix.hasBluetooth);
System.out.println("The hasWiFi is: " + refSix.hasWiFi);
System.out.println("The usbPorts is: " + refSix.usbPorts);
System.out.println("The hdmiPorts is: " + refSix.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refSix.hasEthernetPort);
System.out.println("The weight is: " + refSix.weight);
System.out.println("The graphicsCard is: " + refSix.graphicsCard);
System.out.println("The launchYear is: " + refSix.launchYear);
System.out.println("The manufacturerCountry is: " + refSix.manufacturerCountry);
System.out.println("The ownerName is: " + refSix.ownerName);
Laptop refSeven = new Laptop();

System.out.println("The brand is: " + refSeven.brand);
System.out.println("The model is: " + refSeven.model);
System.out.println("The color is: " + refSeven.color);
System.out.println("The price is: " + refSeven.price);
System.out.println("The ram is: " + refSeven.ram);
System.out.println("The storage is: " + refSeven.storage);
System.out.println("The processor is: " + refSeven.processor);
System.out.println("The screenSize is: " + refSeven.screenSize);
System.out.println("The operatingSystem is: " + refSeven.operatingSystem);
System.out.println("The batteryCapacity is: " + refSeven.batteryCapacity);
System.out.println("The hasFingerprint is: " + refSeven.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refSeven.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refSeven.hasTouchScreen);
System.out.println("The hasWebcam is: " + refSeven.hasWebcam);
System.out.println("The hasBluetooth is: " + refSeven.hasBluetooth);
System.out.println("The hasWiFi is: " + refSeven.hasWiFi);
System.out.println("The usbPorts is: " + refSeven.usbPorts);
System.out.println("The hdmiPorts is: " + refSeven.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refSeven.hasEthernetPort);
System.out.println("The weight is: " + refSeven.weight);
System.out.println("The graphicsCard is: " + refSeven.graphicsCard);
System.out.println("The launchYear is: " + refSeven.launchYear);
System.out.println("The manufacturerCountry is: " + refSeven.manufacturerCountry);
System.out.println("The ownerName is: " + refSeven.ownerName);

refSeven.laptopId = 7;
refSeven.brand = "MSI";
refSeven.model = "Katana GF66";
refSeven.color = "Black";
refSeven.price = 110000;
refSeven.ram = 16;
refSeven.storage = 1024;
refSeven.processor = "Intel i7";
refSeven.screenSize = 15.6;
refSeven.operatingSystem = "Windows 11";
refSeven.batteryCapacity = 4700;
refSeven.hasFingerprint = false;
refSeven.hasBacklitKeyboard = true;
refSeven.hasTouchScreen = false;
refSeven.hasWebcam = true;
refSeven.hasBluetooth = true;
refSeven.hasWiFi = true;
refSeven.usbPorts = 4;
refSeven.hdmiPorts = 1;
refSeven.hasEthernetPort = true;
refSeven.weight = 2;
refSeven.graphicsCard = "NVIDIA RTX 3060";
refSeven.launchYear = 2023;
refSeven.manufacturerCountry = "Taiwan";
refSeven.ownerName = "Naveen";

System.out.println("The laptopId is: " + refSeven.laptopId);
System.out.println("The brand is: " + refSeven.brand);
System.out.println("The model is: " + refSeven.model);
System.out.println("The color is: " + refSeven.color);
System.out.println("The price is: " + refSeven.price);
System.out.println("The ram is: " + refSeven.ram);
System.out.println("The storage is: " + refSeven.storage);
System.out.println("The processor is: " + refSeven.processor);
System.out.println("The screenSize is: " + refSeven.screenSize);
System.out.println("The operatingSystem is: " + refSeven.operatingSystem);
System.out.println("The batteryCapacity is: " + refSeven.batteryCapacity);
System.out.println("The hasFingerprint is: " + refSeven.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refSeven.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refSeven.hasTouchScreen);
System.out.println("The hasWebcam is: " + refSeven.hasWebcam);
System.out.println("The hasBluetooth is: " + refSeven.hasBluetooth);
System.out.println("The hasWiFi is: " + refSeven.hasWiFi);
System.out.println("The usbPorts is: " + refSeven.usbPorts);
System.out.println("The hdmiPorts is: " + refSeven.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refSeven.hasEthernetPort);
System.out.println("The weight is: " + refSeven.weight);
System.out.println("The graphicsCard is: " + refSeven.graphicsCard);
System.out.println("The launchYear is: " + refSeven.launchYear);
System.out.println("The manufacturerCountry is: " + refSeven.manufacturerCountry);
System.out.println("The ownerName is: " + refSeven.ownerName);
Laptop refEight = new Laptop();

System.out.println("The brand is: " + refEight.brand);
System.out.println("The model is: " + refEight.model);
System.out.println("The color is: " + refEight.color);
System.out.println("The price is: " + refEight.price);
System.out.println("The ram is: " + refEight.ram);
System.out.println("The storage is: " + refEight.storage);
System.out.println("The processor is: " + refEight.processor);
System.out.println("The screenSize is: " + refEight.screenSize);
System.out.println("The operatingSystem is: " + refEight.operatingSystem);
System.out.println("The batteryCapacity is: " + refEight.batteryCapacity);
System.out.println("The hasFingerprint is: " + refEight.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refEight.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refEight.hasTouchScreen);
System.out.println("The hasWebcam is: " + refEight.hasWebcam);
System.out.println("The hasBluetooth is: " + refEight.hasBluetooth);
System.out.println("The hasWiFi is: " + refEight.hasWiFi);
System.out.println("The usbPorts is: " + refEight.usbPorts);
System.out.println("The hdmiPorts is: " + refEight.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refEight.hasEthernetPort);
System.out.println("The weight is: " + refEight.weight);
System.out.println("The graphicsCard is: " + refEight.graphicsCard);
System.out.println("The launchYear is: " + refEight.launchYear);
System.out.println("The manufacturerCountry is: " + refEight.manufacturerCountry);
System.out.println("The ownerName is: " + refEight.ownerName);

refEight.laptopId = 8;
refEight.brand = "Samsung";
refEight.model = "Galaxy Book 3";
refEight.color = "Silver";
refEight.price = 95000;
refEight.ram = 16;
refEight.storage = 512;
refEight.processor = "Intel i7";
refEight.screenSize = 15.6;
refEight.operatingSystem = "Windows 11";
refEight.batteryCapacity = 4800;
refEight.hasFingerprint = true;
refEight.hasBacklitKeyboard = true;
refEight.hasTouchScreen = true;
refEight.hasWebcam = true;
refEight.hasBluetooth = true;
refEight.hasWiFi = true;
refEight.usbPorts = 3;
refEight.hdmiPorts = 1;
refEight.hasEthernetPort = false;
refEight.weight = 2;
refEight.graphicsCard = "Intel Iris Xe";
refEight.launchYear = 2023;
refEight.manufacturerCountry = "South Korea";
refEight.ownerName = "Arjun";

System.out.println("The laptopId is: " + refEight.laptopId);
System.out.println("The brand is: " + refEight.brand);
System.out.println("The model is: " + refEight.model);
System.out.println("The color is: " + refEight.color);
System.out.println("The price is: " + refEight.price);
System.out.println("The ram is: " + refEight.ram);
System.out.println("The storage is: " + refEight.storage);
System.out.println("The processor is: " + refEight.processor);
System.out.println("The screenSize is: " + refEight.screenSize);
System.out.println("The operatingSystem is: " + refEight.operatingSystem);
System.out.println("The batteryCapacity is: " + refEight.batteryCapacity);
System.out.println("The hasFingerprint is: " + refEight.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refEight.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refEight.hasTouchScreen);
System.out.println("The hasWebcam is: " + refEight.hasWebcam);
System.out.println("The hasBluetooth is: " + refEight.hasBluetooth);
System.out.println("The hasWiFi is: " + refEight.hasWiFi);
System.out.println("The usbPorts is: " + refEight.usbPorts);
System.out.println("The hdmiPorts is: " + refEight.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refEight.hasEthernetPort);
System.out.println("The weight is: " + refEight.weight);
System.out.println("The graphicsCard is: " + refEight.graphicsCard);
System.out.println("The launchYear is: " + refEight.launchYear);
System.out.println("The manufacturerCountry is: " + refEight.manufacturerCountry);
System.out.println("The ownerName is: " + refEight.ownerName);
Laptop refNine = new Laptop();

System.out.println("The brand is: " + refNine.brand);
System.out.println("The model is: " + refNine.model);
System.out.println("The color is: " + refNine.color);
System.out.println("The price is: " + refNine.price);
System.out.println("The ram is: " + refNine.ram);
System.out.println("The storage is: " + refNine.storage);
System.out.println("The processor is: " + refNine.processor);
System.out.println("The screenSize is: " + refNine.screenSize);
System.out.println("The operatingSystem is: " + refNine.operatingSystem);
System.out.println("The batteryCapacity is: " + refNine.batteryCapacity);
System.out.println("The hasFingerprint is: " + refNine.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refNine.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refNine.hasTouchScreen);
System.out.println("The hasWebcam is: " + refNine.hasWebcam);
System.out.println("The hasBluetooth is: " + refNine.hasBluetooth);
System.out.println("The hasWiFi is: " + refNine.hasWiFi);
System.out.println("The usbPorts is: " + refNine.usbPorts);
System.out.println("The hdmiPorts is: " + refNine.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refNine.hasEthernetPort);
System.out.println("The weight is: " + refNine.weight);
System.out.println("The graphicsCard is: " + refNine.graphicsCard);
System.out.println("The launchYear is: " + refNine.launchYear);
System.out.println("The manufacturerCountry is: " + refNine.manufacturerCountry);
System.out.println("The ownerName is: " + refNine.ownerName);

refNine.laptopId = 9;
refNine.brand = "LG";
refNine.model = "Gram 16";
refNine.color = "White";
refNine.price = 130000;
refNine.ram = 16;
refNine.storage = 1024;
refNine.processor = "Intel i7";
refNine.screenSize = 16.0;
refNine.operatingSystem = "Windows 11";
refNine.batteryCapacity = 5000;
refNine.hasFingerprint = true;
refNine.hasBacklitKeyboard = true;
refNine.hasTouchScreen = false;
refNine.hasWebcam = true;
refNine.hasBluetooth = true;
refNine.hasWiFi = true;
refNine.usbPorts = 3;
refNine.hdmiPorts = 1;
refNine.hasEthernetPort = false;
refNine.weight = 1;
refNine.graphicsCard = "Intel Iris Xe";
refNine.launchYear = 2023;
refNine.manufacturerCountry = "South Korea";
refNine.ownerName = "Vijay";

System.out.println("The laptopId is: " + refNine.laptopId);
System.out.println("The brand is: " + refNine.brand);
System.out.println("The model is: " + refNine.model);
System.out.println("The color is: " + refNine.color);
System.out.println("The price is: " + refNine.price);
System.out.println("The ram is: " + refNine.ram);
System.out.println("The storage is: " + refNine.storage);
System.out.println("The processor is: " + refNine.processor);
System.out.println("The screenSize is: " + refNine.screenSize);
System.out.println("The operatingSystem is: " + refNine.operatingSystem);
System.out.println("The batteryCapacity is: " + refNine.batteryCapacity);
System.out.println("The hasFingerprint is: " + refNine.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refNine.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refNine.hasTouchScreen);
System.out.println("The hasWebcam is: " + refNine.hasWebcam);
System.out.println("The hasBluetooth is: " + refNine.hasBluetooth);
System.out.println("The hasWiFi is: " + refNine.hasWiFi);
System.out.println("The usbPorts is: " + refNine.usbPorts);
System.out.println("The hdmiPorts is: " + refNine.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refNine.hasEthernetPort);
System.out.println("The weight is: " + refNine.weight);
System.out.println("The graphicsCard is: " + refNine.graphicsCard);
System.out.println("The launchYear is: " + refNine.launchYear);
System.out.println("The manufacturerCountry is: " + refNine.manufacturerCountry);
System.out.println("The ownerName is: " + refNine.ownerName);
Laptop refTen = new Laptop();

System.out.println("The brand is: " + refTen.brand);
System.out.println("The model is: " + refTen.model);
System.out.println("The color is: " + refTen.color);
System.out.println("The price is: " + refTen.price);
System.out.println("The ram is: " + refTen.ram);
System.out.println("The storage is: " + refTen.storage);
System.out.println("The processor is: " + refTen.processor);
System.out.println("The screenSize is: " + refTen.screenSize);
System.out.println("The operatingSystem is: " + refTen.operatingSystem);
System.out.println("The batteryCapacity is: " + refTen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refTen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refTen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refTen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refTen.hasWebcam);
System.out.println("The hasBluetooth is: " + refTen.hasBluetooth);
System.out.println("The hasWiFi is: " + refTen.hasWiFi);
System.out.println("The usbPorts is: " + refTen.usbPorts);
System.out.println("The hdmiPorts is: " + refTen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refTen.hasEthernetPort);
System.out.println("The weight is: " + refTen.weight);
System.out.println("The graphicsCard is: " + refTen.graphicsCard);
System.out.println("The launchYear is: " + refTen.launchYear);
System.out.println("The manufacturerCountry is: " + refTen.manufacturerCountry);
System.out.println("The ownerName is: " + refTen.ownerName);

refTen.laptopId = 10;
refTen.brand = "Huawei";
refTen.model = "MateBook X Pro";
refTen.color = "Space Gray";
refTen.price = 125000;
refTen.ram = 16;
refTen.storage = 1024;
refTen.processor = "Intel i7";
refTen.screenSize = 14.2;
refTen.operatingSystem = "Windows 11";
refTen.batteryCapacity = 4800;
refTen.hasFingerprint = true;
refTen.hasBacklitKeyboard = true;
refTen.hasTouchScreen = true;
refTen.hasWebcam = true;
refTen.hasBluetooth = true;
refTen.hasWiFi = true;
refTen.usbPorts = 3;
refTen.hdmiPorts = 1;
refTen.hasEthernetPort = false;
refTen.weight = 1;
refTen.graphicsCard = "Intel Iris Xe";
refTen.launchYear = 2023;
refTen.manufacturerCountry = "China";
refTen.ownerName = "Karthik";

System.out.println("The laptopId is: " + refTen.laptopId);
System.out.println("The brand is: " + refTen.brand);
System.out.println("The model is: " + refTen.model);
System.out.println("The color is: " + refTen.color);
System.out.println("The price is: " + refTen.price);
System.out.println("The ram is: " + refTen.ram);
System.out.println("The storage is: " + refTen.storage);
System.out.println("The processor is: " + refTen.processor);
System.out.println("The screenSize is: " + refTen.screenSize);
System.out.println("The operatingSystem is: " + refTen.operatingSystem);
System.out.println("The batteryCapacity is: " + refTen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refTen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refTen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refTen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refTen.hasWebcam);
System.out.println("The hasBluetooth is: " + refTen.hasBluetooth);
System.out.println("The hasWiFi is: " + refTen.hasWiFi);
System.out.println("The usbPorts is: " + refTen.usbPorts);
System.out.println("The hdmiPorts is: " + refTen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refTen.hasEthernetPort);
System.out.println("The weight is: " + refTen.weight);
System.out.println("The graphicsCard is: " + refTen.graphicsCard);
System.out.println("The launchYear is: " + refTen.launchYear);
System.out.println("The manufacturerCountry is: " + refTen.manufacturerCountry);
System.out.println("The ownerName is: " + refTen.ownerName);
Laptop refEleven = new Laptop();

System.out.println("The brand is: " + refEleven.brand);
System.out.println("The model is: " + refEleven.model);
System.out.println("The color is: " + refEleven.color);
System.out.println("The price is: " + refEleven.price);
System.out.println("The ram is: " + refEleven.ram);
System.out.println("The storage is: " + refEleven.storage);
System.out.println("The processor is: " + refEleven.processor);
System.out.println("The screenSize is: " + refEleven.screenSize);
System.out.println("The operatingSystem is: " + refEleven.operatingSystem);
System.out.println("The batteryCapacity is: " + refEleven.batteryCapacity);
System.out.println("The hasFingerprint is: " + refEleven.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refEleven.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refEleven.hasTouchScreen);
System.out.println("The hasWebcam is: " + refEleven.hasWebcam);
System.out.println("The hasBluetooth is: " + refEleven.hasBluetooth);
System.out.println("The hasWiFi is: " + refEleven.hasWiFi);
System.out.println("The usbPorts is: " + refEleven.usbPorts);
System.out.println("The hdmiPorts is: " + refEleven.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refEleven.hasEthernetPort);
System.out.println("The weight is: " + refEleven.weight);
System.out.println("The graphicsCard is: " + refEleven.graphicsCard);
System.out.println("The launchYear is: " + refEleven.launchYear);
System.out.println("The manufacturerCountry is: " + refEleven.manufacturerCountry);
System.out.println("The ownerName is: " + refEleven.ownerName);

refEleven.laptopId = 11;
refEleven.brand = "Razer";
refEleven.model = "Blade 15";
refEleven.color = "Black";
refEleven.price = 180000;
refEleven.ram = 32;
refEleven.storage = 1024;
refEleven.processor = "Intel i9";
refEleven.screenSize = 15.6;
refEleven.operatingSystem = "Windows 11";
refEleven.batteryCapacity = 5200;
refEleven.hasFingerprint = true;
refEleven.hasBacklitKeyboard = true;
refEleven.hasTouchScreen = false;
refEleven.hasWebcam = true;
refEleven.hasBluetooth = true;
refEleven.hasWiFi = true;
refEleven.usbPorts = 4;
refEleven.hdmiPorts = 1;
refEleven.hasEthernetPort = true;
refEleven.weight = 2;
refEleven.graphicsCard = "NVIDIA RTX 4070";
refEleven.launchYear = 2024;
refEleven.manufacturerCountry = "USA";
refEleven.ownerName = "Rahul";

System.out.println("The laptopId is: " + refEleven.laptopId);
System.out.println("The brand is: " + refEleven.brand);
System.out.println("The model is: " + refEleven.model);
System.out.println("The color is: " + refEleven.color);
System.out.println("The price is: " + refEleven.price);
System.out.println("The ram is: " + refEleven.ram);
System.out.println("The storage is: " + refEleven.storage);
System.out.println("The processor is: " + refEleven.processor);
System.out.println("The screenSize is: " + refEleven.screenSize);
System.out.println("The operatingSystem is: " + refEleven.operatingSystem);
System.out.println("The batteryCapacity is: " + refEleven.batteryCapacity);
System.out.println("The hasFingerprint is: " + refEleven.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refEleven.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refEleven.hasTouchScreen);
System.out.println("The hasWebcam is: " + refEleven.hasWebcam);
System.out.println("The hasBluetooth is: " + refEleven.hasBluetooth);
System.out.println("The hasWiFi is: " + refEleven.hasWiFi);
System.out.println("The usbPorts is: " + refEleven.usbPorts);
System.out.println("The hdmiPorts is: " + refEleven.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refEleven.hasEthernetPort);
System.out.println("The weight is: " + refEleven.weight);
System.out.println("The graphicsCard is: " + refEleven.graphicsCard);
System.out.println("The launchYear is: " + refEleven.launchYear);
System.out.println("The manufacturerCountry is: " + refEleven.manufacturerCountry);
System.out.println("The ownerName is: " + refEleven.ownerName);
Laptop refTwelve = new Laptop();

System.out.println("The brand is: " + refTwelve.brand);
System.out.println("The model is: " + refTwelve.model);
System.out.println("The color is: " + refTwelve.color);
System.out.println("The price is: " + refTwelve.price);
System.out.println("The ram is: " + refTwelve.ram);
System.out.println("The storage is: " + refTwelve.storage);
System.out.println("The processor is: " + refTwelve.processor);
System.out.println("The screenSize is: " + refTwelve.screenSize);
System.out.println("The operatingSystem is: " + refTwelve.operatingSystem);
System.out.println("The batteryCapacity is: " + refTwelve.batteryCapacity);
System.out.println("The hasFingerprint is: " + refTwelve.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refTwelve.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refTwelve.hasTouchScreen);
System.out.println("The hasWebcam is: " + refTwelve.hasWebcam);
System.out.println("The hasBluetooth is: " + refTwelve.hasBluetooth);
System.out.println("The hasWiFi is: " + refTwelve.hasWiFi);
System.out.println("The usbPorts is: " + refTwelve.usbPorts);
System.out.println("The hdmiPorts is: " + refTwelve.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refTwelve.hasEthernetPort);
System.out.println("The weight is: " + refTwelve.weight);
System.out.println("The graphicsCard is: " + refTwelve.graphicsCard);
System.out.println("The launchYear is: " + refTwelve.launchYear);
System.out.println("The manufacturerCountry is: " + refTwelve.manufacturerCountry);
System.out.println("The ownerName is: " + refTwelve.ownerName);

refTwelve.laptopId = 12;
refTwelve.brand = "Sony";
refTwelve.model = "Vaio Z";
refTwelve.color = "Black";
refTwelve.price = 160000;
refTwelve.ram = 16;
refTwelve.storage = 1024;
refTwelve.processor = "Intel i7";
refTwelve.screenSize = 14.0;
refTwelve.operatingSystem = "Windows 11";
refTwelve.batteryCapacity = 4800;
refTwelve.hasFingerprint = true;
refTwelve.hasBacklitKeyboard = true;
refTwelve.hasTouchScreen = false;
refTwelve.hasWebcam = true;
refTwelve.hasBluetooth = true;
refTwelve.hasWiFi = true;
refTwelve.usbPorts = 3;
refTwelve.hdmiPorts = 1;
refTwelve.hasEthernetPort = false;
refTwelve.weight = 1;
refTwelve.graphicsCard = "Intel Iris Xe";
refTwelve.launchYear = 2023;
refTwelve.manufacturerCountry = "Japan";
refTwelve.ownerName = "Arun";

System.out.println("The laptopId is: " + refTwelve.laptopId);
System.out.println("The brand is: " + refTwelve.brand);
System.out.println("The model is: " + refTwelve.model);
System.out.println("The color is: " + refTwelve.color);
System.out.println("The price is: " + refTwelve.price);
System.out.println("The ram is: " + refTwelve.ram);
System.out.println("The storage is: " + refTwelve.storage);
System.out.println("The processor is: " + refTwelve.processor);
System.out.println("The screenSize is: " + refTwelve.screenSize);
System.out.println("The operatingSystem is: " + refTwelve.operatingSystem);
System.out.println("The batteryCapacity is: " + refTwelve.batteryCapacity);
System.out.println("The hasFingerprint is: " + refTwelve.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refTwelve.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refTwelve.hasTouchScreen);
System.out.println("The hasWebcam is: " + refTwelve.hasWebcam);
System.out.println("The hasBluetooth is: " + refTwelve.hasBluetooth);
System.out.println("The hasWiFi is: " + refTwelve.hasWiFi);
System.out.println("The usbPorts is: " + refTwelve.usbPorts);
System.out.println("The hdmiPorts is: " + refTwelve.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refTwelve.hasEthernetPort);
System.out.println("The weight is: " + refTwelve.weight);
System.out.println("The graphicsCard is: " + refTwelve.graphicsCard);
System.out.println("The launchYear is: " + refTwelve.launchYear);
System.out.println("The manufacturerCountry is: " + refTwelve.manufacturerCountry);
System.out.println("The ownerName is: " + refTwelve.ownerName);
Laptop refThirteen = new Laptop();

System.out.println("The brand is: " + refThirteen.brand);
System.out.println("The model is: " + refThirteen.model);
System.out.println("The color is: " + refThirteen.color);
System.out.println("The price is: " + refThirteen.price);
System.out.println("The ram is: " + refThirteen.ram);
System.out.println("The storage is: " + refThirteen.storage);
System.out.println("The processor is: " + refThirteen.processor);
System.out.println("The screenSize is: " + refThirteen.screenSize);
System.out.println("The operatingSystem is: " + refThirteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refThirteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refThirteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refThirteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refThirteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refThirteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refThirteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refThirteen.hasWiFi);
System.out.println("The usbPorts is: " + refThirteen.usbPorts);
System.out.println("The hdmiPorts is: " + refThirteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refThirteen.hasEthernetPort);
System.out.println("The weight is: " + refThirteen.weight);
System.out.println("The graphicsCard is: " + refThirteen.graphicsCard);
System.out.println("The launchYear is: " + refThirteen.launchYear);
System.out.println("The manufacturerCountry is: " + refThirteen.manufacturerCountry);
System.out.println("The ownerName is: " + refThirteen.ownerName);

refThirteen.laptopId = 13;
refThirteen.brand = "Toshiba";
refThirteen.model = "Dynabook Tecra";
refThirteen.color = "Dark Blue";
refThirteen.price = 90000;
refThirteen.ram = 16;
refThirteen.storage = 512;
refThirteen.processor = "Intel i7";
refThirteen.screenSize = 14.0;
refThirteen.operatingSystem = "Windows 11";
refThirteen.batteryCapacity = 4700;
refThirteen.hasFingerprint = true;
refThirteen.hasBacklitKeyboard = true;
refThirteen.hasTouchScreen = false;
refThirteen.hasWebcam = true;
refThirteen.hasBluetooth = true;
refThirteen.hasWiFi = true;
refThirteen.usbPorts = 3;
refThirteen.hdmiPorts = 1;
refThirteen.hasEthernetPort = true;
refThirteen.weight = 2;
refThirteen.graphicsCard = "Intel Iris Xe";
refThirteen.launchYear = 2023;
refThirteen.manufacturerCountry = "Japan";
refThirteen.ownerName = "Manoj";

System.out.println("The laptopId is: " + refThirteen.laptopId);
System.out.println("The brand is: " + refThirteen.brand);
System.out.println("The model is: " + refThirteen.model);
System.out.println("The color is: " + refThirteen.color);
System.out.println("The price is: " + refThirteen.price);
System.out.println("The ram is: " + refThirteen.ram);
System.out.println("The storage is: " + refThirteen.storage);
System.out.println("The processor is: " + refThirteen.processor);
System.out.println("The screenSize is: " + refThirteen.screenSize);
System.out.println("The operatingSystem is: " + refThirteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refThirteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refThirteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refThirteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refThirteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refThirteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refThirteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refThirteen.hasWiFi);
System.out.println("The usbPorts is: " + refThirteen.usbPorts);
System.out.println("The hdmiPorts is: " + refThirteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refThirteen.hasEthernetPort);
System.out.println("The weight is: " + refThirteen.weight);
System.out.println("The graphicsCard is: " + refThirteen.graphicsCard);
System.out.println("The launchYear is: " + refThirteen.launchYear);
System.out.println("The manufacturerCountry is: " + refThirteen.manufacturerCountry);
System.out.println("The ownerName is: " + refThirteen.ownerName);
Laptop refFourteen = new Laptop();

System.out.println("The brand is: " + refFourteen.brand);
System.out.println("The model is: " + refFourteen.model);
System.out.println("The color is: " + refFourteen.color);
System.out.println("The price is: " + refFourteen.price);
System.out.println("The ram is: " + refFourteen.ram);
System.out.println("The storage is: " + refFourteen.storage);
System.out.println("The processor is: " + refFourteen.processor);
System.out.println("The screenSize is: " + refFourteen.screenSize);
System.out.println("The operatingSystem is: " + refFourteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refFourteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refFourteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refFourteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refFourteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refFourteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refFourteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refFourteen.hasWiFi);
System.out.println("The usbPorts is: " + refFourteen.usbPorts);
System.out.println("The hdmiPorts is: " + refFourteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refFourteen.hasEthernetPort);
System.out.println("The weight is: " + refFourteen.weight);
System.out.println("The graphicsCard is: " + refFourteen.graphicsCard);
System.out.println("The launchYear is: " + refFourteen.launchYear);
System.out.println("The manufacturerCountry is: " + refFourteen.manufacturerCountry);
System.out.println("The ownerName is: " + refFourteen.ownerName);

refFourteen.laptopId = 14;
refFourteen.brand = "Microsoft";
refFourteen.model = "Surface Laptop 5";
refFourteen.color = "Platinum";
refFourteen.price = 135000;
refFourteen.ram = 16;
refFourteen.storage = 512;
refFourteen.processor = "Intel i7";
refFourteen.screenSize = 15.0;
refFourteen.operatingSystem = "Windows 11";
refFourteen.batteryCapacity = 4900;
refFourteen.hasFingerprint = true;
refFourteen.hasBacklitKeyboard = true;
refFourteen.hasTouchScreen = true;
refFourteen.hasWebcam = true;
refFourteen.hasBluetooth = true;
refFourteen.hasWiFi = true;
refFourteen.usbPorts = 2;
refFourteen.hdmiPorts = 1;
refFourteen.hasEthernetPort = false;
refFourteen.weight = 1;
refFourteen.graphicsCard = "Intel Iris Xe";
refFourteen.launchYear = 2023;
refFourteen.manufacturerCountry = "USA";
refFourteen.ownerName = "Karthik";

System.out.println("The laptopId is: " + refFourteen.laptopId);
System.out.println("The brand is: " + refFourteen.brand);
System.out.println("The model is: " + refFourteen.model);
System.out.println("The color is: " + refFourteen.color);
System.out.println("The price is: " + refFourteen.price);
System.out.println("The ram is: " + refFourteen.ram);
System.out.println("The storage is: " + refFourteen.storage);
System.out.println("The processor is: " + refFourteen.processor);
System.out.println("The screenSize is: " + refFourteen.screenSize);
System.out.println("The operatingSystem is: " + refFourteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refFourteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refFourteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refFourteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refFourteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refFourteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refFourteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refFourteen.hasWiFi);
System.out.println("The usbPorts is: " + refFourteen.usbPorts);
System.out.println("The hdmiPorts is: " + refFourteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refFourteen.hasEthernetPort);
System.out.println("The weight is: " + refFourteen.weight);
System.out.println("The graphicsCard is: " + refFourteen.graphicsCard);
System.out.println("The launchYear is: " + refFourteen.launchYear);
System.out.println("The manufacturerCountry is: " + refFourteen.manufacturerCountry);
System.out.println("The ownerName is: " + refFourteen.ownerName);
Laptop refFifteen = new Laptop();

System.out.println("The brand is: " + refFifteen.brand);
System.out.println("The model is: " + refFifteen.model);
System.out.println("The color is: " + refFifteen.color);
System.out.println("The price is: " + refFifteen.price);
System.out.println("The ram is: " + refFifteen.ram);
System.out.println("The storage is: " + refFifteen.storage);
System.out.println("The processor is: " + refFifteen.processor);
System.out.println("The screenSize is: " + refFifteen.screenSize);
System.out.println("The operatingSystem is: " + refFifteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refFifteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refFifteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refFifteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refFifteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refFifteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refFifteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refFifteen.hasWiFi);
System.out.println("The usbPorts is: " + refFifteen.usbPorts);
System.out.println("The hdmiPorts is: " + refFifteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refFifteen.hasEthernetPort);
System.out.println("The weight is: " + refFifteen.weight);
System.out.println("The graphicsCard is: " + refFifteen.graphicsCard);
System.out.println("The launchYear is: " + refFifteen.launchYear);
System.out.println("The manufacturerCountry is: " + refFifteen.manufacturerCountry);
System.out.println("The ownerName is: " + refFifteen.ownerName);

refFifteen.laptopId = 15;
refFifteen.brand = "Gigabyte";
refFifteen.model = "Aero 16";
refFifteen.color = "Black";
refFifteen.price = 170000;
refFifteen.ram = 32;
refFifteen.storage = 1024;
refFifteen.processor = "Intel i9";
refFifteen.screenSize = 16.0;
refFifteen.operatingSystem = "Windows 11";
refFifteen.batteryCapacity = 5200;
refFifteen.hasFingerprint = true;
refFifteen.hasBacklitKeyboard = true;
refFifteen.hasTouchScreen = false;
refFifteen.hasWebcam = true;
refFifteen.hasBluetooth = true;
refFifteen.hasWiFi = true;
refFifteen.usbPorts = 4;
refFifteen.hdmiPorts = 1;
refFifteen.hasEthernetPort = true;
refFifteen.weight = 2;
refFifteen.graphicsCard = "NVIDIA RTX 4080";
refFifteen.launchYear = 2024;
refFifteen.manufacturerCountry = "Taiwan";
refFifteen.ownerName = "Aravind";

System.out.println("The laptopId is: " + refFifteen.laptopId);
System.out.println("The brand is: " + refFifteen.brand);
System.out.println("The model is: " + refFifteen.model);
System.out.println("The color is: " + refFifteen.color);
System.out.println("The price is: " + refFifteen.price);
System.out.println("The ram is: " + refFifteen.ram);
System.out.println("The storage is: " + refFifteen.storage);
System.out.println("The processor is: " + refFifteen.processor);
System.out.println("The screenSize is: " + refFifteen.screenSize);
System.out.println("The operatingSystem is: " + refFifteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refFifteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refFifteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refFifteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refFifteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refFifteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refFifteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refFifteen.hasWiFi);
System.out.println("The usbPorts is: " + refFifteen.usbPorts);
System.out.println("The hdmiPorts is: " + refFifteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refFifteen.hasEthernetPort);
System.out.println("The weight is: " + refFifteen.weight);
System.out.println("The graphicsCard is: " + refFifteen.graphicsCard);
System.out.println("The launchYear is: " + refFifteen.launchYear);
System.out.println("The manufacturerCountry is: " + refFifteen.manufacturerCountry);
System.out.println("The ownerName is: " + refFifteen.ownerName);
Laptop refSixteen = new Laptop();

System.out.println("The brand is: " + refSixteen.brand);
System.out.println("The model is: " + refSixteen.model);
System.out.println("The color is: " + refSixteen.color);
System.out.println("The price is: " + refSixteen.price);
System.out.println("The ram is: " + refSixteen.ram);
System.out.println("The storage is: " + refSixteen.storage);
System.out.println("The processor is: " + refSixteen.processor);
System.out.println("The screenSize is: " + refSixteen.screenSize);
System.out.println("The operatingSystem is: " + refSixteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refSixteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refSixteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refSixteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refSixteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refSixteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refSixteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refSixteen.hasWiFi);
System.out.println("The usbPorts is: " + refSixteen.usbPorts);
System.out.println("The hdmiPorts is: " + refSixteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refSixteen.hasEthernetPort);
System.out.println("The weight is: " + refSixteen.weight);
System.out.println("The graphicsCard is: " + refSixteen.graphicsCard);
System.out.println("The launchYear is: " + refSixteen.launchYear);
System.out.println("The manufacturerCountry is: " + refSixteen.manufacturerCountry);
System.out.println("The ownerName is: " + refSixteen.ownerName);

refSixteen.laptopId = 16;
refSixteen.brand = "Alienware";
refSixteen.model = "m15 R7";
refSixteen.color = "Dark Gray";
refSixteen.price = 190000;
refSixteen.ram = 32;
refSixteen.storage = 1024;
refSixteen.processor = "Intel i9";
refSixteen.screenSize = 15.6;
refSixteen.operatingSystem = "Windows 11";
refSixteen.batteryCapacity = 5400;
refSixteen.hasFingerprint = true;
refSixteen.hasBacklitKeyboard = true;
refSixteen.hasTouchScreen = false;
refSixteen.hasWebcam = true;
refSixteen.hasBluetooth = true;
refSixteen.hasWiFi = true;
refSixteen.usbPorts = 4;
refSixteen.hdmiPorts = 1;
refSixteen.hasEthernetPort = true;
refSixteen.weight = 3;
refSixteen.graphicsCard = "NVIDIA RTX 4090";
refSixteen.launchYear = 2024;
refSixteen.manufacturerCountry = "USA";
refSixteen.ownerName = "Rohit";

System.out.println("The laptopId is: " + refSixteen.laptopId);
System.out.println("The brand is: " + refSixteen.brand);
System.out.println("The model is: " + refSixteen.model);
System.out.println("The color is: " + refSixteen.color);
System.out.println("The price is: " + refSixteen.price);
System.out.println("The ram is: " + refSixteen.ram);
System.out.println("The storage is: " + refSixteen.storage);
System.out.println("The processor is: " + refSixteen.processor);
System.out.println("The screenSize is: " + refSixteen.screenSize);
System.out.println("The operatingSystem is: " + refSixteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refSixteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refSixteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refSixteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refSixteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refSixteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refSixteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refSixteen.hasWiFi);
System.out.println("The usbPorts is: " + refSixteen.usbPorts);
System.out.println("The hdmiPorts is: " + refSixteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refSixteen.hasEthernetPort);
System.out.println("The weight is: " + refSixteen.weight);
System.out.println("The graphicsCard is: " + refSixteen.graphicsCard);
System.out.println("The launchYear is: " + refSixteen.launchYear);
System.out.println("The manufacturerCountry is: " + refSixteen.manufacturerCountry);
System.out.println("The ownerName is: " + refSixteen.ownerName);
Laptop refSeventeen = new Laptop();

System.out.println("The brand is: " + refSeventeen.brand);
System.out.println("The model is: " + refSeventeen.model);
System.out.println("The color is: " + refSeventeen.color);
System.out.println("The price is: " + refSeventeen.price);
System.out.println("The ram is: " + refSeventeen.ram);
System.out.println("The storage is: " + refSeventeen.storage);
System.out.println("The processor is: " + refSeventeen.processor);
System.out.println("The screenSize is: " + refSeventeen.screenSize);
System.out.println("The operatingSystem is: " + refSeventeen.operatingSystem);
System.out.println("The batteryCapacity is: " + refSeventeen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refSeventeen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refSeventeen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refSeventeen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refSeventeen.hasWebcam);
System.out.println("The hasBluetooth is: " + refSeventeen.hasBluetooth);
System.out.println("The hasWiFi is: " + refSeventeen.hasWiFi);
System.out.println("The usbPorts is: " + refSeventeen.usbPorts);
System.out.println("The hdmiPorts is: " + refSeventeen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refSeventeen.hasEthernetPort);
System.out.println("The weight is: " + refSeventeen.weight);
System.out.println("The graphicsCard is: " + refSeventeen.graphicsCard);
System.out.println("The launchYear is: " + refSeventeen.launchYear);
System.out.println("The manufacturerCountry is: " + refSeventeen.manufacturerCountry);
System.out.println("The ownerName is: " + refSeventeen.ownerName);

refSeventeen.laptopId = 17;
refSeventeen.brand = "Panasonic";
refSeventeen.model = "Toughbook 40";
refSeventeen.color = "Black";
refSeventeen.price = 210000;
refSeventeen.ram = 32;
refSeventeen.storage = 1024;
refSeventeen.processor = "Intel i7";
refSeventeen.screenSize = 14.0;
refSeventeen.operatingSystem = "Windows 11";
refSeventeen.batteryCapacity = 5500;
refSeventeen.hasFingerprint = true;
refSeventeen.hasBacklitKeyboard = true;
refSeventeen.hasTouchScreen = true;
refSeventeen.hasWebcam = true;
refSeventeen.hasBluetooth = true;
refSeventeen.hasWiFi = true;
refSeventeen.usbPorts = 4;
refSeventeen.hdmiPorts = 1;
refSeventeen.hasEthernetPort = true;
refSeventeen.weight = 3;
refSeventeen.graphicsCard = "Intel UHD Graphics";
refSeventeen.launchYear = 2024;
refSeventeen.manufacturerCountry = "Japan";
refSeventeen.ownerName = "Sanjay";

System.out.println("The laptopId is: " + refSeventeen.laptopId);
System.out.println("The brand is: " + refSeventeen.brand);
System.out.println("The model is: " + refSeventeen.model);
System.out.println("The color is: " + refSeventeen.color);
System.out.println("The price is: " + refSeventeen.price);
System.out.println("The ram is: " + refSeventeen.ram);
System.out.println("The storage is: " + refSeventeen.storage);
System.out.println("The processor is: " + refSeventeen.processor);
System.out.println("The screenSize is: " + refSeventeen.screenSize);
System.out.println("The operatingSystem is: " + refSeventeen.operatingSystem);
System.out.println("The batteryCapacity is: " + refSeventeen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refSeventeen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refSeventeen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refSeventeen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refSeventeen.hasWebcam);
System.out.println("The hasBluetooth is: " + refSeventeen.hasBluetooth);
System.out.println("The hasWiFi is: " + refSeventeen.hasWiFi);
System.out.println("The usbPorts is: " + refSeventeen.usbPorts);
System.out.println("The hdmiPorts is: " + refSeventeen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refSeventeen.hasEthernetPort);
System.out.println("The weight is: " + refSeventeen.weight);
System.out.println("The graphicsCard is: " + refSeventeen.graphicsCard);
System.out.println("The launchYear is: " + refSeventeen.launchYear);
System.out.println("The manufacturerCountry is: " + refSeventeen.manufacturerCountry);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
Laptop refEighteen = new Laptop();

System.out.println("The brand is: " + refEighteen.brand);
System.out.println("The model is: " + refEighteen.model);
System.out.println("The color is: " + refEighteen.color);
System.out.println("The price is: " + refEighteen.price);
System.out.println("The ram is: " + refEighteen.ram);
System.out.println("The storage is: " + refEighteen.storage);
System.out.println("The processor is: " + refEighteen.processor);
System.out.println("The screenSize is: " + refEighteen.screenSize);
System.out.println("The operatingSystem is: " + refEighteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refEighteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refEighteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refEighteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refEighteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refEighteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refEighteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refEighteen.hasWiFi);
System.out.println("The usbPorts is: " + refEighteen.usbPorts);
System.out.println("The hdmiPorts is: " + refEighteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refEighteen.hasEthernetPort);
System.out.println("The weight is: " + refEighteen.weight);
System.out.println("The graphicsCard is: " + refEighteen.graphicsCard);
System.out.println("The launchYear is: " + refEighteen.launchYear);
System.out.println("The manufacturerCountry is: " + refEighteen.manufacturerCountry);
System.out.println("The ownerName is: " + refEighteen.ownerName);

refEighteen.laptopId = 18;
refEighteen.brand = "Framework";
refEighteen.model = "Framework Laptop 13";
refEighteen.color = "Silver";
refEighteen.price = 120000;
refEighteen.ram = 16;
refEighteen.storage = 512;
refEighteen.processor = "Intel i7";
refEighteen.screenSize = 13.5;
refEighteen.operatingSystem = "Windows 11";
refEighteen.batteryCapacity = 4700;
refEighteen.hasFingerprint = true;
refEighteen.hasBacklitKeyboard = true;
refEighteen.hasTouchScreen = false;
refEighteen.hasWebcam = true;
refEighteen.hasBluetooth = true;
refEighteen.hasWiFi = true;
refEighteen.usbPorts = 4;
refEighteen.hdmiPorts = 1;
refEighteen.hasEthernetPort = false;
refEighteen.weight = 1;
refEighteen.graphicsCard = "Intel Iris Xe";
refEighteen.launchYear = 2023;
refEighteen.manufacturerCountry = "USA";
refEighteen.ownerName = "Kiran";

System.out.println("The laptopId is: " + refEighteen.laptopId);
System.out.println("The brand is: " + refEighteen.brand);
System.out.println("The model is: " + refEighteen.model);
System.out.println("The color is: " + refEighteen.color);
System.out.println("The price is: " + refEighteen.price);
System.out.println("The ram is: " + refEighteen.ram);
System.out.println("The storage is: " + refEighteen.storage);
System.out.println("The processor is: " + refEighteen.processor);
System.out.println("The screenSize is: " + refEighteen.screenSize);
System.out.println("The operatingSystem is: " + refEighteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refEighteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refEighteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refEighteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refEighteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refEighteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refEighteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refEighteen.hasWiFi);
System.out.println("The usbPorts is: " + refEighteen.usbPorts);
System.out.println("The hdmiPorts is: " + refEighteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refEighteen.hasEthernetPort);
System.out.println("The weight is: " + refEighteen.weight);
System.out.println("The graphicsCard is: " + refEighteen.graphicsCard);
System.out.println("The launchYear is: " + refEighteen.launchYear);
System.out.println("The manufacturerCountry is: " + refEighteen.manufacturerCountry);
System.out.println("The ownerName is: " + refEighteen.ownerName);
Laptop refNineteen = new Laptop();

System.out.println("The brand is: " + refNineteen.brand);
System.out.println("The model is: " + refNineteen.model);
System.out.println("The color is: " + refNineteen.color);
System.out.println("The price is: " + refNineteen.price);
System.out.println("The ram is: " + refNineteen.ram);
System.out.println("The storage is: " + refNineteen.storage);
System.out.println("The processor is: " + refNineteen.processor);
System.out.println("The screenSize is: " + refNineteen.screenSize);
System.out.println("The operatingSystem is: " + refNineteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refNineteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refNineteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refNineteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refNineteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refNineteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refNineteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refNineteen.hasWiFi);
System.out.println("The usbPorts is: " + refNineteen.usbPorts);
System.out.println("The hdmiPorts is: " + refNineteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refNineteen.hasEthernetPort);
System.out.println("The weight is: " + refNineteen.weight);
System.out.println("The graphicsCard is: " + refNineteen.graphicsCard);
System.out.println("The launchYear is: " + refNineteen.launchYear);
System.out.println("The manufacturerCountry is: " + refNineteen.manufacturerCountry);
System.out.println("The ownerName is: " + refNineteen.ownerName);

refNineteen.laptopId = 19;
refNineteen.brand = "Chuwi";
refNineteen.model = "CoreBook X";
refNineteen.color = "Gray";
refNineteen.price = 65000;
refNineteen.ram = 16;
refNineteen.storage = 512;
refNineteen.processor = "Intel i5";
refNineteen.screenSize = 14.0;
refNineteen.operatingSystem = "Windows 11";
refNineteen.batteryCapacity = 4400;
refNineteen.hasFingerprint = false;
refNineteen.hasBacklitKeyboard = true;
refNineteen.hasTouchScreen = false;
refNineteen.hasWebcam = true;
refNineteen.hasBluetooth = true;
refNineteen.hasWiFi = true;
refNineteen.usbPorts = 3;
refNineteen.hdmiPorts = 1;
refNineteen.hasEthernetPort = false;
refNineteen.weight = 2;
refNineteen.graphicsCard = "Intel UHD Graphics";
refNineteen.launchYear = 2022;
refNineteen.manufacturerCountry = "China";
refNineteen.ownerName = "Deepak";

System.out.println("The laptopId is: " + refNineteen.laptopId);
System.out.println("The brand is: " + refNineteen.brand);
System.out.println("The model is: " + refNineteen.model);
System.out.println("The color is: " + refNineteen.color);
System.out.println("The price is: " + refNineteen.price);
System.out.println("The ram is: " + refNineteen.ram);
System.out.println("The storage is: " + refNineteen.storage);
System.out.println("The processor is: " + refNineteen.processor);
System.out.println("The screenSize is: " + refNineteen.screenSize);
System.out.println("The operatingSystem is: " + refNineteen.operatingSystem);
System.out.println("The batteryCapacity is: " + refNineteen.batteryCapacity);
System.out.println("The hasFingerprint is: " + refNineteen.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refNineteen.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refNineteen.hasTouchScreen);
System.out.println("The hasWebcam is: " + refNineteen.hasWebcam);
System.out.println("The hasBluetooth is: " + refNineteen.hasBluetooth);
System.out.println("The hasWiFi is: " + refNineteen.hasWiFi);
System.out.println("The usbPorts is: " + refNineteen.usbPorts);
System.out.println("The hdmiPorts is: " + refNineteen.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refNineteen.hasEthernetPort);
System.out.println("The weight is: " + refNineteen.weight);
System.out.println("The graphicsCard is: " + refNineteen.graphicsCard);
System.out.println("The launchYear is: " + refNineteen.launchYear);
System.out.println("The manufacturerCountry is: " + refNineteen.manufacturerCountry);
System.out.println("The ownerName is: " + refNineteen.ownerName);
Laptop refTwenty = new Laptop();

System.out.println("The brand is: " + refTwenty.brand);
System.out.println("The model is: " + refTwenty.model);
System.out.println("The color is: " + refTwenty.color);
System.out.println("The price is: " + refTwenty.price);
System.out.println("The ram is: " + refTwenty.ram);
System.out.println("The storage is: " + refTwenty.storage);
System.out.println("The processor is: " + refTwenty.processor);
System.out.println("The screenSize is: " + refTwenty.screenSize);
System.out.println("The operatingSystem is: " + refTwenty.operatingSystem);
System.out.println("The batteryCapacity is: " + refTwenty.batteryCapacity);
System.out.println("The hasFingerprint is: " + refTwenty.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refTwenty.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refTwenty.hasTouchScreen);
System.out.println("The hasWebcam is: " + refTwenty.hasWebcam);
System.out.println("The hasBluetooth is: " + refTwenty.hasBluetooth);
System.out.println("The hasWiFi is: " + refTwenty.hasWiFi);
System.out.println("The usbPorts is: " + refTwenty.usbPorts);
System.out.println("The hdmiPorts is: " + refTwenty.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refTwenty.hasEthernetPort);
System.out.println("The weight is: " + refTwenty.weight);
System.out.println("The graphicsCard is: " + refTwenty.graphicsCard);
System.out.println("The launchYear is: " + refTwenty.launchYear);
System.out.println("The manufacturerCountry is: " + refTwenty.manufacturerCountry);
System.out.println("The ownerName is: " + refTwenty.ownerName);

refTwenty.laptopId = 20;
refTwenty.brand = "Realme";
refTwenty.model = "Realme Book Prime";
refTwenty.color = "Blue";
refTwenty.price = 75000;
refTwenty.ram = 16;
refTwenty.storage = 512;
refTwenty.processor = "Intel i5";
refTwenty.screenSize = 14.0;
refTwenty.operatingSystem = "Windows 11";
refTwenty.batteryCapacity = 4700;
refTwenty.hasFingerprint = true;
refTwenty.hasBacklitKeyboard = true;
refTwenty.hasTouchScreen = false;
refTwenty.hasWebcam = true;
refTwenty.hasBluetooth = true;
refTwenty.hasWiFi = true;
refTwenty.usbPorts = 3;
refTwenty.hdmiPorts = 1;
refTwenty.hasEthernetPort = false;
refTwenty.weight = 1;
refTwenty.graphicsCard = "Intel Iris Xe";
refTwenty.launchYear = 2023;
refTwenty.manufacturerCountry = "China";
refTwenty.ownerName = "Karthik";

System.out.println("The laptopId is: " + refTwenty.laptopId);
System.out.println("The brand is: " + refTwenty.brand);
System.out.println("The model is: " + refTwenty.model);
System.out.println("The color is: " + refTwenty.color);
System.out.println("The price is: " + refTwenty.price);
System.out.println("The ram is: " + refTwenty.ram);
System.out.println("The storage is: " + refTwenty.storage);
System.out.println("The processor is: " + refTwenty.processor);
System.out.println("The screenSize is: " + refTwenty.screenSize);
System.out.println("The operatingSystem is: " + refTwenty.operatingSystem);
System.out.println("The batteryCapacity is: " + refTwenty.batteryCapacity);
System.out.println("The hasFingerprint is: " + refTwenty.hasFingerprint);
System.out.println("The hasBacklitKeyboard is: " + refTwenty.hasBacklitKeyboard);
System.out.println("The hasTouchScreen is: " + refTwenty.hasTouchScreen);
System.out.println("The hasWebcam is: " + refTwenty.hasWebcam);
System.out.println("The hasBluetooth is: " + refTwenty.hasBluetooth);
System.out.println("The hasWiFi is: " + refTwenty.hasWiFi);
System.out.println("The usbPorts is: " + refTwenty.usbPorts);
System.out.println("The hdmiPorts is: " + refTwenty.hdmiPorts);
System.out.println("The hasEthernetPort is: " + refTwenty.hasEthernetPort);
System.out.println("The weight is: " + refTwenty.weight);
System.out.println("The graphicsCard is: " + refTwenty.graphicsCard);
System.out.println("The launchYear is: " + refTwenty.launchYear);
System.out.println("The manufacturerCountry is: " + refTwenty.manufacturerCountry);
System.out.println("The ownerName is: " + refTwenty.ownerName);
}
}
