class LensKartExecutor {
    public static void main(String[] args) {
	
        Frame f1 = new Frame(101, "Air Flex", "Full Rim", "Titanium", "Black", 3500, "LensKart", "Medium", "Rectangle", "Unisex", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Full Rim", "Premium", "India", "Available");
        Frame f2 = new Frame(102, "Urban Flex", "Half Rim", "Metal", "Silver", 2800, "LensKart", "Medium", "Oval", "Unisex", "Anti Glare", "1 Year", "Light", "Yes", "Yes", "No", "Half Rim", "Standard", "India", "Available");
        Frame f4 = new Frame(104, "Classic Rim", "Full Rim", "Plastic", "Brown", 2200, "LensKart", "Medium", "Rectangle", "Unisex", "Normal", "1 Year", "Light", "No", "Yes", "No", "Full Rim", "Standard", "India", "Available");
        Frame f5 = new Frame(105, "Urban Style", "Half Rim", "Metal", "Black", 3000, "LensKart", "Large", "Round", "Men", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Half Rim", "Premium", "India", "Available");
        Frame f6 = new Frame(106, "Flex Lite", "Full Rim", "Titanium", "Silver", 3800, "LensKart", "Medium", "Rectangle", "Unisex", "Anti Glare", "1 Year", "Light", "Yes", "Yes", "No", "Full Rim", "Premium", "India", "Available");
        Frame f7 = new Frame(107, "Urban Fit", "Full Rim", "Plastic", "Blue", 2500, "LensKart", "Medium", "Square", "Unisex", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Full Rim", "Standard", "India", "Available");
        Frame f8 = new Frame(108, "Flex Classic", "Full Rim", "Plastic", "Black", 2600, "LensKart", "Medium", "Rectangle", "Unisex", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Full Rim", "Standard", "India", "Available");
        Frame f9 = new Frame(109, "Urban Rim", "Half Rim", "Metal", "Grey", 3200, "LensKart", "Large", "Round", "Men", "Anti Glare", "1 Year", "Light", "Yes", "Yes", "No", "Half Rim", "Premium", "India", "Available");
        Frame f10 = new Frame(110, "Flex Square", "Full Rim", "Titanium", "Silver", 4000, "LensKart", "Medium", "Square", "Unisex", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Full Rim", "Premium", "India", "Available");
        Frame f11 = new Frame(111, "Classic Flex", "Full Rim", "Plastic", "Brown", 2400, "LensKart", "Medium", "Rectangle", "Unisex", "Normal", "1 Year", "Light", "No", "Yes", "No", "Full Rim", "Standard", "India", "Available");
        Frame f12 = new Frame(112, "Urban Flex", "Half Rim", "Metal", "Black", 2900, "LensKart", "Medium", "Oval", "Unisex", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Half Rim", "Premium", "India", "Available");
        Frame f13 = new Frame(113, "Flex Vision", "Full Rim", "Titanium", "Grey", 4100, "LensKart", "Large", "Rectangle", "Men", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Full Rim", "Premium", "India", "Available");
        Frame f14 = new Frame(114, "Urban Style", "Half Rim", "Metal", "Silver", 3100, "LensKart", "Medium", "Round", "Unisex", "Anti Glare", "1 Year", "Light", "Yes", "Yes", "No", "Half Rim", "Standard", "India", "Available");
        Frame f15 = new Frame(115, "Classic Pro", "Full Rim", "Plastic", "Black", 2300, "LensKart", "Medium", "Rectangle", "Unisex", "Normal", "1 Year", "Light", "No", "Yes", "No", "Full Rim", "Standard", "India", "Available");
        Frame f16 = new Frame(116, "Flex Vision", "Full Rim", "Titanium", "Grey", 3900, "LensKart", "Large", "Square", "Unisex", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Full Rim", "Premium", "India", "Available");
        Frame f17 = new Frame(117, "Urban Lite", "Half Rim", "Metal", "Silver", 3000, "LensKart", "Medium", "Oval", "Unisex", "Anti Glare", "1 Year", "Light", "Yes", "Yes", "No", "Half Rim", "Standard", "India", "Available");
        Frame f18 = new Frame(118, "Classic Rim", "Full Rim", "Plastic", "Black", 2400, "LensKart", "Medium", "Rectangle", "Unisex", "Normal", "1 Year", "Light", "No", "Yes", "No", "Full Rim", "Standard", "India", "Available");
        Frame f19 = new Frame(119, "Flex Style", "Full Rim", "Titanium", "Grey", 4100, "LensKart", "Large", "Square", "Men", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Full Rim", "Premium", "India", "Available");
        Frame f20 = new Frame(120, "Premium Flex", "Full Rim", "Titanium", "Black", 4500, "LensKart", "Large", "Rectangle", "Unisex", "Blue Cut", "1 Year", "Light", "Yes", "Yes", "Yes", "Full Rim", "Premium", "India", "Available");

        LensKart l1 = new LensKart(1, "LensKart Store", "Bangalore", "Peyush Bansal", 2, 25, "10 AM", "10 PM", "Eyewear", 20, "www.lenskart.com", 2010, "Open", "Blue", "Smart Glasses", 1000, "Available", "Yes", "Available", "India", f1);
        LensKart l2 = new LensKart(2, "LensKart Store", "Chennai", "Peyush Bansal", 2, 20, "10 AM", "9 PM", "Eyewear", 15, "www.lenskart.com", 2011, "Open", "Blue", "Vincent Chase", 1000, "Available", "Yes", "Available", "India", f2);
        LensKart l4 = new LensKart(4, "LensKart Store", "Hyderabad", "Peyush Bansal", 2, 22, "10 AM", "9 PM", "Eyewear", 18, "www.lenskart.com", 2013, "Open", "Blue", "Air Flex", 1000, "Available", "Yes", "Available", "India", f4);
        LensKart l5 = new LensKart(5, "LensKart Store", "Mumbai", "Peyush Bansal", 3, 35, "10 AM", "10 PM", "Eyewear", 30, "www.lenskart.com", 2014, "Open", "Blue", "Vincent Chase", 1000, "Available", "Yes", "Available", "India", f5);
        LensKart l6 = new LensKart(6, "LensKart Store", "Pune", "Peyush Bansal", 2, 24, "10 AM", "9 PM", "Eyewear", 16, "www.lenskart.com", 2015, "Open", "Blue", "Air Flex", 1000, "Available", "Yes", "Available", "India", f6);
        LensKart l7 = new LensKart(7, "LensKart Store", "Kolkata", "Peyush Bansal", 2, 21, "10 AM", "9 PM", "Eyewear", 14, "www.lenskart.com", 2016, "Open", "Blue", "John Jacobs", 1000, "Available", "Yes", "Available", "India", f7);
        LensKart l8 = new LensKart(8, "LensKart Store", "Mysore", "Peyush Bansal", 2, 18, "10 AM", "9 PM", "Eyewear", 12, "www.lenskart.com", 2017, "Open", "Blue", "Air Flex", 1000, "Available", "Yes", "Available", "India", f8);
        LensKart l9 = new LensKart(9, "LensKart Store", "Coimbatore", "Peyush Bansal", 2, 19, "10 AM", "9 PM", "Eyewear", 15, "www.lenskart.com", 2018, "Open", "Blue", "Vincent Chase", 1000, "Available", "Yes", "Available", "India", f9);
        LensKart l1 = new LensKart(10, "LensKart Store", "Madurai", "Peyush Bansal", 1, 15, "10 AM", "9 PM", "Eyewear", 10, "www.lenskart.com", 2019, "Open", "Blue", "John Jacobs", 1000, "Available", "Yes", "Available", "India", f10);
        LensKart l1 = new LensKart(11, "LensKart Store", "Trichy", "Peyush Bansal", 2, 20, "10 AM", "9 PM", "Eyewear", 13, "www.lenskart.com", 2020, "Open", "Blue", "Air Flex", 1000, "Available", "Yes", "Available", "India", f11);
        LensKart l2 = new LensKart(12, "LensKart Store", "Salem", "Peyush Bansal", 2, 17, "10 AM", "9 PM", "Eyewear", 12, "www.lenskart.com", 2020, "Open", "Blue", "Vincent Chase", 1000, "Available", "Yes", "Available", "India", f12);
        LensKart 13 = new LensKart(13, "LensKart Store", "Erode", "Peyush Bansal", 1, 14, "10 AM", "9 PM", "Eyewear", 8, "www.lenskart.com", 2021, "Open", "Blue", "Air Flex", 1000, "Available", "Yes", "Available", "India", f13);
        LensKart 14 = new LensKart(14, "LensKart Store", "Vellore", "Peyush Bansal", 2, 16, "10 AM", "9 PM", "Eyewear", 10, "www.lenskart.com", 2021, "Open", "Blue", "John Jacobs", 1000, "Available", "Yes", "Available", "India", f14);
        LensKart l5 = new LensKart(15, "LensKart Store", "Tirunelveli", "Peyush Bansal", 1, 13, "10 AM", "9 PM", "Eyewear", 7, "www.lenskart.com", 2022, "Open", "Blue", "Vincent Chase", 1000, "Available", "Yes", "Available", "India", f15);
        LensKart 16 = new LensKart(16, "LensKart Store", "Thanjavur", "Peyush Bansal", 2, 18, "10 AM", "9 PM", "Eyewear", 12, "www.lenskart.com", 2022, "Open", "Blue", "Air Flex", 1000, "Available", "Yes", "Available", "India", f16);
        LensKart 17 = new LensKart(17, "LensKart Store", "Karur", "Peyush Bansal", 1, 12, "10 AM", "9 PM", "Eyewear", 6, "www.lenskart.com", 2023, "Open", "Blue", "Vincent Chase", 1000, "Available", "Yes", "Available", "India", f17);
        LensKart 18 = new LensKart(18, "LensKart Store", "Hosur", "Peyush Bansal", 2, 19, "10 AM", "9 PM", "Eyewear", 14, "www.lenskart.com", 2023, "Open", "Blue", "John Jacobs", 1000, "Available", "Yes", "Available", "India", f18);
        LensKart 19 = new LensKart(19, "LensKart Store", "Kanchipuram", "Peyush Bansal", 2, 16, "10 AM", "9 PM", "Eyewear", 11, "www.lenskart.com", 2024, "Open", "Blue", "Air Flex", 1000, "Available", "Yes", "Available", "India", f19);
        LensKart 20 = new LensKart(20, "LensKart Store", "Tirupati", "Peyush Bansal", 2, 20, "10 AM", "10 PM", "Eyewear", 18, "www.lenskart.com", 2024, "Open", "Blue", "Vincent Chase", 1000, "Available", "Yes", "Available", "India", f20);

        l1.getLensKartDetails();
        System.out.println("====================================================");
        l2.getLensKartDetails();
        System.out.println("====================================================");
        l4.getLensKartDetails();
        System.out.println("====================================================");
        l5.getLensKartDetails();
        System.out.println("====================================================");
        l6.getLensKartDetails();
        System.out.println("====================================================");
        l7.getLensKartDetails();
        System.out.println("====================================================");
        l8.getLensKartDetails();
        System.out.println("====================================================");
        l9.getLensKartDetails();
        System.out.println("====================================================");
        l10.getLensKartDetails();
        System.out.println("====================================================");
        l11.getLensKartDetails();
        System.out.println("====================================================");
        l12.getLensKartDetails();
        System.out.println("====================================================");
        l13.getLensKartDetails();
        System.out.println("====================================================");
        l14.getLensKartDetails();
        System.out.println("====================================================");
        l15.getLensKartDetails();
        System.out.println("====================================================");
        l16.getLensKartDetails();
        System.out.println("====================================================");
        l17.getLensKartDetails();
        System.out.println("====================================================");
        l18.getLensKartDetails();
        System.out.println("====================================================");
        l19.getLensKartDetails();
        System.out.println("====================================================");
        l20.getLensKartDetails();
        System.out.println("====================================================");
    }
}
