class LibraryExecutor{
public static void main(String[] args){
Library refOne = new Library();

System.out.println("The libraryId is: " + refOne.libraryId);
System.out.println("The libraryName is: " + refOne.libraryName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfBooks is: " + refOne.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refOne.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refOne.numberOfJournals);
System.out.println("The numberOfComputers is: " + refOne.numberOfComputers);
System.out.println("The numberOfMembers is: " + refOne.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refOne.hasReadingRoom);
System.out.println("The hasEbooks is: " + refOne.hasEbooks);
System.out.println("The hasAudiobooks is: " + refOne.hasAudiobooks);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasCafeteria is: " + refOne.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refOne.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refOne.hasPrintingFacility);
System.out.println("The librarianName is: " + refOne.librarianName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The libraryType is: " + refOne.libraryType);

refOne.libraryId = 1;
refOne.libraryName = "City Central Library";
refOne.location = "MG Road";
refOne.city = "Bengaluru";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfBooks = 50000;
refOne.numberOfMagazines = 200;
refOne.numberOfJournals = 150;
refOne.numberOfComputers = 40;
refOne.numberOfMembers = 1200;
refOne.hasReadingRoom = true;
refOne.hasEbooks = true;
refOne.hasAudiobooks = true;
refOne.hasWifi = true;
refOne.hasParking = true;
refOne.hasCafeteria = true;
refOne.hasStudyRooms = true;
refOne.hasPrintingFacility = true;
refOne.librarianName = "Ramesh Kumar";
refOne.establishedYear = 1995;
refOne.contactNumber = "9876543210";
refOne.email = "info@citylibrary.com";
refOne.website = "www.citylibrary.com";
refOne.libraryType = "Public Library";

System.out.println("The libraryId is: " + refOne.libraryId);
System.out.println("The libraryName is: " + refOne.libraryName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfBooks is: " + refOne.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refOne.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refOne.numberOfJournals);
System.out.println("The numberOfComputers is: " + refOne.numberOfComputers);
System.out.println("The numberOfMembers is: " + refOne.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refOne.hasReadingRoom);
System.out.println("The hasEbooks is: " + refOne.hasEbooks);
System.out.println("The hasAudiobooks is: " + refOne.hasAudiobooks);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasCafeteria is: " + refOne.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refOne.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refOne.hasPrintingFacility);
System.out.println("The librarianName is: " + refOne.librarianName);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The libraryType is: " + refOne.libraryType);
Library refTwo = new Library();

System.out.println("The libraryId is: " + refTwo.libraryId);
System.out.println("The libraryName is: " + refTwo.libraryName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfBooks is: " + refTwo.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refTwo.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refTwo.numberOfJournals);
System.out.println("The numberOfComputers is: " + refTwo.numberOfComputers);
System.out.println("The numberOfMembers is: " + refTwo.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refTwo.hasReadingRoom);
System.out.println("The hasEbooks is: " + refTwo.hasEbooks);
System.out.println("The hasAudiobooks is: " + refTwo.hasAudiobooks);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasCafeteria is: " + refTwo.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refTwo.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refTwo.hasPrintingFacility);
System.out.println("The librarianName is: " + refTwo.librarianName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The libraryType is: " + refTwo.libraryType);

refTwo.libraryId = 2;
refTwo.libraryName = "National Knowledge Library";
refTwo.location = "Connaught Place";
refTwo.city = "New Delhi";
refTwo.state = "Delhi";
refTwo.country = "India";
refTwo.numberOfBooks = 75000;
refTwo.numberOfMagazines = 300;
refTwo.numberOfJournals = 220;
refTwo.numberOfComputers = 60;
refTwo.numberOfMembers = 2500;
refTwo.hasReadingRoom = true;
refTwo.hasEbooks = true;
refTwo.hasAudiobooks = true;
refTwo.hasWifi = true;
refTwo.hasParking = true;
refTwo.hasCafeteria = true;
refTwo.hasStudyRooms = true;
refTwo.hasPrintingFacility = true;
refTwo.librarianName = "Anita Sharma";
refTwo.establishedYear = 2005;
refTwo.contactNumber = "9871234560";
refTwo.email = "contact@nationallibrary.com";
refTwo.website = "www.nationallibrary.com";
refTwo.libraryType = "Public Library";

System.out.println("The libraryId is: " + refTwo.libraryId);
System.out.println("The libraryName is: " + refTwo.libraryName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfBooks is: " + refTwo.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refTwo.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refTwo.numberOfJournals);
System.out.println("The numberOfComputers is: " + refTwo.numberOfComputers);
System.out.println("The numberOfMembers is: " + refTwo.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refTwo.hasReadingRoom);
System.out.println("The hasEbooks is: " + refTwo.hasEbooks);
System.out.println("The hasAudiobooks is: " + refTwo.hasAudiobooks);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasCafeteria is: " + refTwo.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refTwo.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refTwo.hasPrintingFacility);
System.out.println("The librarianName is: " + refTwo.librarianName);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The libraryType is: " + refTwo.libraryType);
Library refThree = new Library();

System.out.println("The libraryId is: " + refThree.libraryId);
System.out.println("The libraryName is: " + refThree.libraryName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfBooks is: " + refThree.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refThree.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refThree.numberOfJournals);
System.out.println("The numberOfComputers is: " + refThree.numberOfComputers);
System.out.println("The numberOfMembers is: " + refThree.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refThree.hasReadingRoom);
System.out.println("The hasEbooks is: " + refThree.hasEbooks);
System.out.println("The hasAudiobooks is: " + refThree.hasAudiobooks);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasCafeteria is: " + refThree.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refThree.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refThree.hasPrintingFacility);
System.out.println("The librarianName is: " + refThree.librarianName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The libraryType is: " + refThree.libraryType);

refThree.libraryId = 3;
refThree.libraryName = "State Knowledge Center";
refThree.location = "Anna Salai";
refThree.city = "Chennai";
refThree.state = "Tamil Nadu";
refThree.country = "India";
refThree.numberOfBooks = 60000;
refThree.numberOfMagazines = 250;
refThree.numberOfJournals = 180;
refThree.numberOfComputers = 35;
refThree.numberOfMembers = 1800;
refThree.hasReadingRoom = true;
refThree.hasEbooks = true;
refThree.hasAudiobooks = false;
refThree.hasWifi = true;
refThree.hasParking = true;
refThree.hasCafeteria = false;
refThree.hasStudyRooms = true;
refThree.hasPrintingFacility = true;
refThree.librarianName = "Suresh Iyer";
refThree.establishedYear = 1998;
refThree.contactNumber = "9887766554";
refThree.email = "info@stateknowledge.org";
refThree.website = "www.stateknowledge.org";
refThree.libraryType = "Government Library";

System.out.println("The libraryId is: " + refThree.libraryId);
System.out.println("The libraryName is: " + refThree.libraryName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfBooks is: " + refThree.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refThree.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refThree.numberOfJournals);
System.out.println("The numberOfComputers is: " + refThree.numberOfComputers);
System.out.println("The numberOfMembers is: " + refThree.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refThree.hasReadingRoom);
System.out.println("The hasEbooks is: " + refThree.hasEbooks);
System.out.println("The hasAudiobooks is: " + refThree.hasAudiobooks);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasCafeteria is: " + refThree.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refThree.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refThree.hasPrintingFacility);
System.out.println("The librarianName is: " + refThree.librarianName);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The libraryType is: " + refThree.libraryType);
Library refFour = new Library();

System.out.println("The libraryId is: " + refFour.libraryId);
System.out.println("The libraryName is: " + refFour.libraryName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfBooks is: " + refFour.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refFour.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refFour.numberOfJournals);
System.out.println("The numberOfComputers is: " + refFour.numberOfComputers);
System.out.println("The numberOfMembers is: " + refFour.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refFour.hasReadingRoom);
System.out.println("The hasEbooks is: " + refFour.hasEbooks);
System.out.println("The hasAudiobooks is: " + refFour.hasAudiobooks);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasCafeteria is: " + refFour.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refFour.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refFour.hasPrintingFacility);
System.out.println("The librarianName is: " + refFour.librarianName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The libraryType is: " + refFour.libraryType);

refFour.libraryId = 4;
refFour.libraryName = "Green Valley Library";
refFour.location = "Park Street";
refFour.city = "Kolkata";
refFour.state = "West Bengal";
refFour.country = "India";
refFour.numberOfBooks = 42000;
refFour.numberOfMagazines = 180;
refFour.numberOfJournals = 120;
refFour.numberOfComputers = 25;
refFour.numberOfMembers = 950;
refFour.hasReadingRoom = true;
refFour.hasEbooks = false;
refFour.hasAudiobooks = false;
refFour.hasWifi = true;
refFour.hasParking = true;
refFour.hasCafeteria = false;
refFour.hasStudyRooms = true;
refFour.hasPrintingFacility = true;
refFour.librarianName = "Priya Sen";
refFour.establishedYear = 2002;
refFour.contactNumber = "9874501236";
refFour.email = "contact@greenvalleylibrary.org";
refFour.website = "www.greenvalleylibrary.org";
refFour.libraryType = "Community Library";

System.out.println("The libraryId is: " + refFour.libraryId);
System.out.println("The libraryName is: " + refFour.libraryName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfBooks is: " + refFour.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refFour.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refFour.numberOfJournals);
System.out.println("The numberOfComputers is: " + refFour.numberOfComputers);
System.out.println("The numberOfMembers is: " + refFour.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refFour.hasReadingRoom);
System.out.println("The hasEbooks is: " + refFour.hasEbooks);
System.out.println("The hasAudiobooks is: " + refFour.hasAudiobooks);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasCafeteria is: " + refFour.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refFour.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refFour.hasPrintingFacility);
System.out.println("The librarianName is: " + refFour.librarianName);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The libraryType is: " + refFour.libraryType);
Library refSix = new Library();

System.out.println("The libraryId is: " + refSix.libraryId);
System.out.println("The libraryName is: " + refSix.libraryName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfBooks is: " + refSix.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refSix.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refSix.numberOfJournals);
System.out.println("The numberOfComputers is: " + refSix.numberOfComputers);
System.out.println("The numberOfMembers is: " + refSix.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refSix.hasReadingRoom);
System.out.println("The hasEbooks is: " + refSix.hasEbooks);
System.out.println("The hasAudiobooks is: " + refSix.hasAudiobooks);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasCafeteria is: " + refSix.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refSix.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refSix.hasPrintingFacility);
System.out.println("The librarianName is: " + refSix.librarianName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The libraryType is: " + refSix.libraryType);

refSix.libraryId = 6;
refSix.libraryName = "Knowledge Hub Library";
refSix.location = "Banjara Hills";
refSix.city = "Hyderabad";
refSix.state = "Telangana";
refSix.country = "India";
refSix.numberOfBooks = 68000;
refSix.numberOfMagazines = 210;
refSix.numberOfJournals = 160;
refSix.numberOfComputers = 45;
refSix.numberOfMembers = 2100;
refSix.hasReadingRoom = true;
refSix.hasEbooks = true;
refSix.hasAudiobooks = true;
refSix.hasWifi = true;
refSix.hasParking = true;
refSix.hasCafeteria = true;
refSix.hasStudyRooms = true;
refSix.hasPrintingFacility = true;
refSix.librarianName = "Rahul Verma";
refSix.establishedYear = 2010;
refSix.contactNumber = "9876654321";
refSix.email = "info@knowledgehub.org";
refSix.website = "www.knowledgehub.org";
refSix.libraryType = "Digital Library";

System.out.println("The libraryId is: " + refSix.libraryId);
System.out.println("The libraryName is: " + refSix.libraryName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfBooks is: " + refSix.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refSix.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refSix.numberOfJournals);
System.out.println("The numberOfComputers is: " + refSix.numberOfComputers);
System.out.println("The numberOfMembers is: " + refSix.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refSix.hasReadingRoom);
System.out.println("The hasEbooks is: " + refSix.hasEbooks);
System.out.println("The hasAudiobooks is: " + refSix.hasAudiobooks);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasCafeteria is: " + refSix.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refSix.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refSix.hasPrintingFacility);
System.out.println("The librarianName is: " + refSix.librarianName);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The libraryType is: " + refSix.libraryType);
Library refSeven = new Library();

System.out.println("The libraryId is: " + refSeven.libraryId);
System.out.println("The libraryName is: " + refSeven.libraryName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfBooks is: " + refSeven.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refSeven.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refSeven.numberOfJournals);
System.out.println("The numberOfComputers is: " + refSeven.numberOfComputers);
System.out.println("The numberOfMembers is: " + refSeven.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refSeven.hasReadingRoom);
System.out.println("The hasEbooks is: " + refSeven.hasEbooks);
System.out.println("The hasAudiobooks is: " + refSeven.hasAudiobooks);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasCafeteria is: " + refSeven.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refSeven.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refSeven.hasPrintingFacility);
System.out.println("The librarianName is: " + refSeven.librarianName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The libraryType is: " + refSeven.libraryType);

refSeven.libraryId = 7;
refSeven.libraryName = "Scholars Resource Library";
refSeven.location = "Sector 17";
refSeven.city = "Chandigarh";
refSeven.state = "Punjab";
refSeven.country = "India";
refSeven.numberOfBooks = 54000;
refSeven.numberOfMagazines = 190;
refSeven.numberOfJournals = 140;
refSeven.numberOfComputers = 30;
refSeven.numberOfMembers = 1300;
refSeven.hasReadingRoom = true;
refSeven.hasEbooks = true;
refSeven.hasAudiobooks = false;
refSeven.hasWifi = true;
refSeven.hasParking = true;
refSeven.hasCafeteria = false;
refSeven.hasStudyRooms = true;
refSeven.hasPrintingFacility = true;
refSeven.librarianName = "Neha Kapoor";
refSeven.establishedYear = 2008;
refSeven.contactNumber = "9898989898";
refSeven.email = "info@scholarslibrary.org";
refSeven.website = "www.scholarslibrary.org";
refSeven.libraryType = "Academic Library";

System.out.println("The libraryId is: " + refSeven.libraryId);
System.out.println("The libraryName is: " + refSeven.libraryName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfBooks is: " + refSeven.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refSeven.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refSeven.numberOfJournals);
System.out.println("The numberOfComputers is: " + refSeven.numberOfComputers);
System.out.println("The numberOfMembers is: " + refSeven.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refSeven.hasReadingRoom);
System.out.println("The hasEbooks is: " + refSeven.hasEbooks);
System.out.println("The hasAudiobooks is: " + refSeven.hasAudiobooks);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasCafeteria is: " + refSeven.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refSeven.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refSeven.hasPrintingFacility);
System.out.println("The librarianName is: " + refSeven.librarianName);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The libraryType is: " + refSeven.libraryType);
Library refEight = new Library();

System.out.println("The libraryId is: " + refEight.libraryId);
System.out.println("The libraryName is: " + refEight.libraryName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfBooks is: " + refEight.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refEight.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refEight.numberOfJournals);
System.out.println("The numberOfComputers is: " + refEight.numberOfComputers);
System.out.println("The numberOfMembers is: " + refEight.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refEight.hasReadingRoom);
System.out.println("The hasEbooks is: " + refEight.hasEbooks);
System.out.println("The hasAudiobooks is: " + refEight.hasAudiobooks);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasCafeteria is: " + refEight.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refEight.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refEight.hasPrintingFacility);
System.out.println("The librarianName is: " + refEight.librarianName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The libraryType is: " + refEight.libraryType);

refEight.libraryId = 8;
refEight.libraryName = "Riverdale Public Library";
refEight.location = "River Road";
refEight.city = "Pune";
refEight.state = "Maharashtra";
refEight.country = "India";
refEight.numberOfBooks = 48000;
refEight.numberOfMagazines = 170;
refEight.numberOfJournals = 110;
refEight.numberOfComputers = 28;
refEight.numberOfMembers = 1100;
refEight.hasReadingRoom = true;
refEight.hasEbooks = true;
refEight.hasAudiobooks = false;
refEight.hasWifi = true;
refEight.hasParking = true;
refEight.hasCafeteria = false;
refEight.hasStudyRooms = true;
refEight.hasPrintingFacility = true;
refEight.librarianName = "Arjun Deshmukh";
refEight.establishedYear = 2001;
refEight.contactNumber = "9867543210";
refEight.email = "contact@riverdalelibrary.org";
refEight.website = "www.riverdalelibrary.org";
refEight.libraryType = "Public Library";

System.out.println("The libraryId is: " + refEight.libraryId);
System.out.println("The libraryName is: " + refEight.libraryName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfBooks is: " + refEight.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refEight.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refEight.numberOfJournals);
System.out.println("The numberOfComputers is: " + refEight.numberOfComputers);
System.out.println("The numberOfMembers is: " + refEight.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refEight.hasReadingRoom);
System.out.println("The hasEbooks is: " + refEight.hasEbooks);
System.out.println("The hasAudiobooks is: " + refEight.hasAudiobooks);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasCafeteria is: " + refEight.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refEight.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refEight.hasPrintingFacility);
System.out.println("The librarianName is: " + refEight.librarianName);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The libraryType is: " + refEight.libraryType);
Library refNine = new Library();

System.out.println("The libraryId is: " + refNine.libraryId);
System.out.println("The libraryName is: " + refNine.libraryName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfBooks is: " + refNine.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refNine.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refNine.numberOfJournals);
System.out.println("The numberOfComputers is: " + refNine.numberOfComputers);
System.out.println("The numberOfMembers is: " + refNine.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refNine.hasReadingRoom);
System.out.println("The hasEbooks is: " + refNine.hasEbooks);
System.out.println("The hasAudiobooks is: " + refNine.hasAudiobooks);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasCafeteria is: " + refNine.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refNine.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refNine.hasPrintingFacility);
System.out.println("The librarianName is: " + refNine.librarianName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The libraryType is: " + refNine.libraryType);

refNine.libraryId = 9;
refNine.libraryName = "Wisdom Tree Library";
refNine.location = "Civil Lines";
refNine.city = "Jaipur";
refNine.state = "Rajasthan";
refNine.country = "India";
refNine.numberOfBooks = 52000;
refNine.numberOfMagazines = 160;
refNine.numberOfJournals = 130;
refNine.numberOfComputers = 32;
refNine.numberOfMembers = 1400;
refNine.hasReadingRoom = true;
refNine.hasEbooks = true;
refNine.hasAudiobooks = false;
refNine.hasWifi = true;
refNine.hasParking = true;
refNine.hasCafeteria = false;
refNine.hasStudyRooms = true;
refNine.hasPrintingFacility = true;
refNine.librarianName = "Rohit Mehta";
refNine.establishedYear = 2003;
refNine.contactNumber = "9812345678";
refNine.email = "info@wisdomtree.org";
refNine.website = "www.wisdomtree.org";
refNine.libraryType = "Public Library";

System.out.println("The libraryId is: " + refNine.libraryId);
System.out.println("The libraryName is: " + refNine.libraryName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfBooks is: " + refNine.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refNine.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refNine.numberOfJournals);
System.out.println("The numberOfComputers is: " + refNine.numberOfComputers);
System.out.println("The numberOfMembers is: " + refNine.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refNine.hasReadingRoom);
System.out.println("The hasEbooks is: " + refNine.hasEbooks);
System.out.println("The hasAudiobooks is: " + refNine.hasAudiobooks);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasCafeteria is: " + refNine.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refNine.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refNine.hasPrintingFacility);
System.out.println("The librarianName is: " + refNine.librarianName);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The libraryType is: " + refNine.libraryType);
Library refTen = new Library();

System.out.println("The libraryId is: " + refTen.libraryId);
System.out.println("The libraryName is: " + refTen.libraryName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfBooks is: " + refTen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refTen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refTen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refTen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refTen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refTen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refTen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refTen.hasAudiobooks);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasCafeteria is: " + refTen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refTen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refTen.hasPrintingFacility);
System.out.println("The librarianName is: " + refTen.librarianName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The libraryType is: " + refTen.libraryType);

refTen.libraryId = 10;
refTen.libraryName = "Bright Future Library";
refTen.location = "University Road";
refTen.city = "Mysuru";
refTen.state = "Karnataka";
refTen.country = "India";
refTen.numberOfBooks = 45000;
refTen.numberOfMagazines = 140;
refTen.numberOfJournals = 100;
refTen.numberOfComputers = 20;
refTen.numberOfMembers = 900;
refTen.hasReadingRoom = true;
refTen.hasEbooks = true;
refTen.hasAudiobooks = false;
refTen.hasWifi = true;
refTen.hasParking = true;
refTen.hasCafeteria = false;
refTen.hasStudyRooms = true;
refTen.hasPrintingFacility = true;
refTen.librarianName = "Lakshmi Narayan";
refTen.establishedYear = 2007;
refTen.contactNumber = "9845123456";
refTen.email = "contact@brightfuturelibrary.com";
refTen.website = "www.brightfuturelibrary.com";
refTen.libraryType = "Educational Library";

System.out.println("The libraryId is: " + refTen.libraryId);
System.out.println("The libraryName is: " + refTen.libraryName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfBooks is: " + refTen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refTen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refTen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refTen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refTen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refTen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refTen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refTen.hasAudiobooks);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasCafeteria is: " + refTen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refTen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refTen.hasPrintingFacility);
System.out.println("The librarianName is: " + refTen.librarianName);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The libraryType is: " + refTen.libraryType);
Library refEleven = new Library();

System.out.println("The libraryId is: " + refEleven.libraryId);
System.out.println("The libraryName is: " + refEleven.libraryName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfBooks is: " + refEleven.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refEleven.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refEleven.numberOfJournals);
System.out.println("The numberOfComputers is: " + refEleven.numberOfComputers);
System.out.println("The numberOfMembers is: " + refEleven.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refEleven.hasReadingRoom);
System.out.println("The hasEbooks is: " + refEleven.hasEbooks);
System.out.println("The hasAudiobooks is: " + refEleven.hasAudiobooks);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasCafeteria is: " + refEleven.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refEleven.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refEleven.hasPrintingFacility);
System.out.println("The librarianName is: " + refEleven.librarianName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The libraryType is: " + refEleven.libraryType);

refEleven.libraryId = 11;
refEleven.libraryName = "Sunrise Knowledge Library";
refEleven.location = "Sector 10";
refEleven.city = "Noida";
refEleven.state = "Uttar Pradesh";
refEleven.country = "India";
refEleven.numberOfBooks = 39000;
refEleven.numberOfMagazines = 120;
refEleven.numberOfJournals = 95;
refEleven.numberOfComputers = 18;
refEleven.numberOfMembers = 800;
refEleven.hasReadingRoom = true;
refEleven.hasEbooks = true;
refEleven.hasAudiobooks = false;
refEleven.hasWifi = true;
refEleven.hasParking = true;
refEleven.hasCafeteria = false;
refEleven.hasStudyRooms = true;
refEleven.hasPrintingFacility = true;
refEleven.librarianName = "Kavita Sharma";
refEleven.establishedYear = 2009;
refEleven.contactNumber = "9890011223";
refEleven.email = "info@sunriselibrary.org";
refEleven.website = "www.sunriselibrary.org";
refEleven.libraryType = "Community Library";

System.out.println("The libraryId is: " + refEleven.libraryId);
System.out.println("The libraryName is: " + refEleven.libraryName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfBooks is: " + refEleven.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refEleven.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refEleven.numberOfJournals);
System.out.println("The numberOfComputers is: " + refEleven.numberOfComputers);
System.out.println("The numberOfMembers is: " + refEleven.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refEleven.hasReadingRoom);
System.out.println("The hasEbooks is: " + refEleven.hasEbooks);
System.out.println("The hasAudiobooks is: " + refEleven.hasAudiobooks);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasCafeteria is: " + refEleven.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refEleven.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refEleven.hasPrintingFacility);
System.out.println("The librarianName is: " + refEleven.librarianName);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The libraryType is: " + refEleven.libraryType);
Library refTwelve = new Library();

System.out.println("The libraryId is: " + refTwelve.libraryId);
System.out.println("The libraryName is: " + refTwelve.libraryName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfBooks is: " + refTwelve.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refTwelve.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refTwelve.numberOfJournals);
System.out.println("The numberOfComputers is: " + refTwelve.numberOfComputers);
System.out.println("The numberOfMembers is: " + refTwelve.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refTwelve.hasReadingRoom);
System.out.println("The hasEbooks is: " + refTwelve.hasEbooks);
System.out.println("The hasAudiobooks is: " + refTwelve.hasAudiobooks);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasCafeteria is: " + refTwelve.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refTwelve.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refTwelve.hasPrintingFacility);
System.out.println("The librarianName is: " + refTwelve.librarianName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The libraryType is: " + refTwelve.libraryType);

refTwelve.libraryId = 12;
refTwelve.libraryName = "Harmony Learning Library";
refTwelve.location = "Station Road";
refTwelve.city = "Coimbatore";
refTwelve.state = "Tamil Nadu";
refTwelve.country = "India";
refTwelve.numberOfBooks = 41000;
refTwelve.numberOfMagazines = 150;
refTwelve.numberOfJournals = 105;
refTwelve.numberOfComputers = 22;
refTwelve.numberOfMembers = 950;
refTwelve.hasReadingRoom = true;
refTwelve.hasEbooks = true;
refTwelve.hasAudiobooks = false;
refTwelve.hasWifi = true;
refTwelve.hasParking = true;
refTwelve.hasCafeteria = false;
refTwelve.hasStudyRooms = true;
refTwelve.hasPrintingFacility = true;
refTwelve.librarianName = "Meena Krishnan";
refTwelve.establishedYear = 2004;
refTwelve.contactNumber = "9843012345";
refTwelve.email = "contact@harmonylibrary.org";
refTwelve.website = "www.harmonylibrary.org";
refTwelve.libraryType = "Public Library";

System.out.println("The libraryId is: " + refTwelve.libraryId);
System.out.println("The libraryName is: " + refTwelve.libraryName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfBooks is: " + refTwelve.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refTwelve.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refTwelve.numberOfJournals);
System.out.println("The numberOfComputers is: " + refTwelve.numberOfComputers);
System.out.println("The numberOfMembers is: " + refTwelve.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refTwelve.hasReadingRoom);
System.out.println("The hasEbooks is: " + refTwelve.hasEbooks);
System.out.println("The hasAudiobooks is: " + refTwelve.hasAudiobooks);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasCafeteria is: " + refTwelve.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refTwelve.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refTwelve.hasPrintingFacility);
System.out.println("The librarianName is: " + refTwelve.librarianName);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The libraryType is: " + refTwelve.libraryType);
Library refThirteen = new Library();

System.out.println("The libraryId is: " + refThirteen.libraryId);
System.out.println("The libraryName is: " + refThirteen.libraryName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfBooks is: " + refThirteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refThirteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refThirteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refThirteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refThirteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refThirteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refThirteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refThirteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasCafeteria is: " + refThirteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refThirteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refThirteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refThirteen.librarianName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The libraryType is: " + refThirteen.libraryType);

refThirteen.libraryId = 13;
refThirteen.libraryName = "Infinity Knowledge Library";
refThirteen.location = "Lake View Road";
refThirteen.city = "Udaipur";
refThirteen.state = "Rajasthan";
refThirteen.country = "India";
refThirteen.numberOfBooks = 37000;
refThirteen.numberOfMagazines = 110;
refThirteen.numberOfJournals = 90;
refThirteen.numberOfComputers = 15;
refThirteen.numberOfMembers = 720;
refThirteen.hasReadingRoom = true;
refThirteen.hasEbooks = true;
refThirteen.hasAudiobooks = false;
refThirteen.hasWifi = true;
refThirteen.hasParking = false;
refThirteen.hasCafeteria = false;
refThirteen.hasStudyRooms = true;
refThirteen.hasPrintingFacility = true;
refThirteen.librarianName = "Vikram Singh";
refThirteen.establishedYear = 2012;
refThirteen.contactNumber = "9876540987";
refThirteen.email = "info@infinitylibrary.org";
refThirteen.website = "www.infinitylibrary.org";
refThirteen.libraryType = "Community Library";

System.out.println("The libraryId is: " + refThirteen.libraryId);
System.out.println("The libraryName is: " + refThirteen.libraryName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfBooks is: " + refThirteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refThirteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refThirteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refThirteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refThirteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refThirteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refThirteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refThirteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasCafeteria is: " + refThirteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refThirteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refThirteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refThirteen.librarianName);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The libraryType is: " + refThirteen.libraryType);
Library refFourteen = new Library();

System.out.println("The libraryId is: " + refFourteen.libraryId);
System.out.println("The libraryName is: " + refFourteen.libraryName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfBooks is: " + refFourteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refFourteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refFourteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refFourteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refFourteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refFourteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refFourteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refFourteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasCafeteria is: " + refFourteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refFourteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refFourteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refFourteen.librarianName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The libraryType is: " + refFourteen.libraryType);

refFourteen.libraryId = 14;
refFourteen.libraryName = "Golden Pages Library";
refFourteen.location = "Mall Road";
refFourteen.city = "Shimla";
refFourteen.state = "Himachal Pradesh";
refFourteen.country = "India";
refFourteen.numberOfBooks = 35000;
refFourteen.numberOfMagazines = 100;
refFourteen.numberOfJournals = 85;
refFourteen.numberOfComputers = 12;
refFourteen.numberOfMembers = 650;
refFourteen.hasReadingRoom = true;
refFourteen.hasEbooks = false;
refFourteen.hasAudiobooks = false;
refFourteen.hasWifi = true;
refFourteen.hasParking = false;
refFourteen.hasCafeteria = false;
refFourteen.hasStudyRooms = true;
refFourteen.hasPrintingFacility = true;
refFourteen.librarianName = "Anjali Thakur";
refFourteen.establishedYear = 1999;
refFourteen.contactNumber = "9816001234";
refFourteen.email = "contact@goldenpageslibrary.org";
refFourteen.website = "www.goldenpageslibrary.org";
refFourteen.libraryType = "Public Library";

System.out.println("The libraryId is: " + refFourteen.libraryId);
System.out.println("The libraryName is: " + refFourteen.libraryName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfBooks is: " + refFourteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refFourteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refFourteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refFourteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refFourteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refFourteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refFourteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refFourteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasCafeteria is: " + refFourteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refFourteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refFourteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refFourteen.librarianName);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The libraryType is: " + refFourteen.libraryType);
Library refFifteen = new Library();

System.out.println("The libraryId is: " + refFifteen.libraryId);
System.out.println("The libraryName is: " + refFifteen.libraryName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfBooks is: " + refFifteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refFifteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refFifteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refFifteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refFifteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refFifteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refFifteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refFifteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasCafeteria is: " + refFifteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refFifteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refFifteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refFifteen.librarianName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The libraryType is: " + refFifteen.libraryType);

refFifteen.libraryId = 15;
refFifteen.libraryName = "Silver Leaf Library";
refFifteen.location = "Ring Road";
refFifteen.city = "Ahmedabad";
refFifteen.state = "Gujarat";
refFifteen.country = "India";
refFifteen.numberOfBooks = 46000;
refFifteen.numberOfMagazines = 150;
refFifteen.numberOfJournals = 110;
refFifteen.numberOfComputers = 24;
refFifteen.numberOfMembers = 1050;
refFifteen.hasReadingRoom = true;
refFifteen.hasEbooks = true;
refFifteen.hasAudiobooks = false;
refFifteen.hasWifi = true;
refFifteen.hasParking = true;
refFifteen.hasCafeteria = true;
refFifteen.hasStudyRooms = true;
refFifteen.hasPrintingFacility = true;
refFifteen.librarianName = "Nirav Patel";
refFifteen.establishedYear = 2006;
refFifteen.contactNumber = "9825012345";
refFifteen.email = "info@silverleaflibrary.org";
refFifteen.website = "www.silverleaflibrary.org";
refFifteen.libraryType = "Public Library";

System.out.println("The libraryId is: " + refFifteen.libraryId);
System.out.println("The libraryName is: " + refFifteen.libraryName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfBooks is: " + refFifteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refFifteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refFifteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refFifteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refFifteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refFifteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refFifteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refFifteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasCafeteria is: " + refFifteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refFifteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refFifteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refFifteen.librarianName);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The libraryType is: " + refFifteen.libraryType);
Library refSixteen = new Library();

System.out.println("The libraryId is: " + refSixteen.libraryId);
System.out.println("The libraryName is: " + refSixteen.libraryName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfBooks is: " + refSixteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refSixteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refSixteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refSixteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refSixteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refSixteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refSixteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refSixteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasCafeteria is: " + refSixteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refSixteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refSixteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refSixteen.librarianName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The libraryType is: " + refSixteen.libraryType);

refSixteen.libraryId = 16;
refSixteen.libraryName = "Galaxy Learning Library";
refSixteen.location = "Main Market Road";
refSixteen.city = "Indore";
refSixteen.state = "Madhya Pradesh";
refSixteen.country = "India";
refSixteen.numberOfBooks = 43000;
refSixteen.numberOfMagazines = 135;
refSixteen.numberOfJournals = 98;
refSixteen.numberOfComputers = 21;
refSixteen.numberOfMembers = 970;
refSixteen.hasReadingRoom = true;
refSixteen.hasEbooks = true;
refSixteen.hasAudiobooks = false;
refSixteen.hasWifi = true;
refSixteen.hasParking = true;
refSixteen.hasCafeteria = false;
refSixteen.hasStudyRooms = true;
refSixteen.hasPrintingFacility = true;
refSixteen.librarianName = "Amit Sharma";
refSixteen.establishedYear = 2011;
refSixteen.contactNumber = "9893004567";
refSixteen.email = "contact@galaxylibrary.org";
refSixteen.website = "www.galaxylibrary.org";
refSixteen.libraryType = "Public Library";

System.out.println("The libraryId is: " + refSixteen.libraryId);
System.out.println("The libraryName is: " + refSixteen.libraryName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfBooks is: " + refSixteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refSixteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refSixteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refSixteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refSixteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refSixteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refSixteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refSixteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasCafeteria is: " + refSixteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refSixteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refSixteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refSixteen.librarianName);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The libraryType is: " + refSixteen.libraryType);
Library refSeventeen = new Library();

System.out.println("The libraryId is: " + refSeventeen.libraryId);
System.out.println("The libraryName is: " + refSeventeen.libraryName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfBooks is: " + refSeventeen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refSeventeen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refSeventeen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refSeventeen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refSeventeen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refSeventeen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refSeventeen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refSeventeen.hasAudiobooks);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasCafeteria is: " + refSeventeen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refSeventeen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refSeventeen.hasPrintingFacility);
System.out.println("The librarianName is: " + refSeventeen.librarianName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The libraryType is: " + refSeventeen.libraryType);

refSeventeen.libraryId = 17;
refSeventeen.libraryName = "Ocean View Library";
refSeventeen.location = "Beach Road";
refSeventeen.city = "Visakhapatnam";
refSeventeen.state = "Andhra Pradesh";
refSeventeen.country = "India";
refSeventeen.numberOfBooks = 39000;
refSeventeen.numberOfMagazines = 120;
refSeventeen.numberOfJournals = 95;
refSeventeen.numberOfComputers = 18;
refSeventeen.numberOfMembers = 820;
refSeventeen.hasReadingRoom = true;
refSeventeen.hasEbooks = true;
refSeventeen.hasAudiobooks = false;
refSeventeen.hasWifi = true;
refSeventeen.hasParking = true;
refSeventeen.hasCafeteria = false;
refSeventeen.hasStudyRooms = true;
refSeventeen.hasPrintingFacility = true;
refSeventeen.librarianName = "Ravi Kumar";
refSeventeen.establishedYear = 2013;
refSeventeen.contactNumber = "9880011223";
refSeventeen.email = "info@oceanviewlibrary.org";
refSeventeen.website = "www.oceanviewlibrary.org";
refSeventeen.libraryType = "Public Library";

System.out.println("The libraryId is: " + refSeventeen.libraryId);
System.out.println("The libraryName is: " + refSeventeen.libraryName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfBooks is: " + refSeventeen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refSeventeen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refSeventeen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refSeventeen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refSeventeen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refSeventeen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refSeventeen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refSeventeen.hasAudiobooks);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasCafeteria is: " + refSeventeen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refSeventeen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refSeventeen.hasPrintingFacility);
System.out.println("The librarianName is: " + refSeventeen.librarianName);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The libraryType is: " + refSeventeen.libraryType);
Library refEighteen = new Library();

System.out.println("The libraryId is: " + refEighteen.libraryId);
System.out.println("The libraryName is: " + refEighteen.libraryName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfBooks is: " + refEighteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refEighteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refEighteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refEighteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refEighteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refEighteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refEighteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refEighteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasCafeteria is: " + refEighteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refEighteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refEighteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refEighteen.librarianName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The libraryType is: " + refEighteen.libraryType);

refEighteen.libraryId = 18;
refEighteen.libraryName = "Skyline Study Library";
refEighteen.location = "City Center";
refEighteen.city = "Bhopal";
refEighteen.state = "Madhya Pradesh";
refEighteen.country = "India";
refEighteen.numberOfBooks = 41000;
refEighteen.numberOfMagazines = 140;
refEighteen.numberOfJournals = 102;
refEighteen.numberOfComputers = 20;
refEighteen.numberOfMembers = 900;
refEighteen.hasReadingRoom = true;
refEighteen.hasEbooks = true;
refEighteen.hasAudiobooks = false;
refEighteen.hasWifi = true;
refEighteen.hasParking = true;
refEighteen.hasCafeteria = false;
refEighteen.hasStudyRooms = true;
refEighteen.hasPrintingFacility = true;
refEighteen.librarianName = "Sunita Verma";
refEighteen.establishedYear = 2014;
refEighteen.contactNumber = "9898765432";
refEighteen.email = "contact@skylinelibrary.org";
refEighteen.website = "www.skylinelibrary.org";
refEighteen.libraryType = "Public Library";

System.out.println("The libraryId is: " + refEighteen.libraryId);
System.out.println("The libraryName is: " + refEighteen.libraryName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfBooks is: " + refEighteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refEighteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refEighteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refEighteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refEighteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refEighteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refEighteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refEighteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasCafeteria is: " + refEighteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refEighteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refEighteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refEighteen.librarianName);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The libraryType is: " + refEighteen.libraryType);
Library refNineteen = new Library();

System.out.println("The libraryId is: " + refNineteen.libraryId);
System.out.println("The libraryName is: " + refNineteen.libraryName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfBooks is: " + refNineteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refNineteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refNineteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refNineteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refNineteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refNineteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refNineteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refNineteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasCafeteria is: " + refNineteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refNineteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refNineteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refNineteen.librarianName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The libraryType is: " + refNineteen.libraryType);

refNineteen.libraryId = 19;
refNineteen.libraryName = "Heritage Knowledge Library";
refNineteen.location = "Temple Street";
refNineteen.city = "Madurai";
refNineteen.state = "Tamil Nadu";
refNineteen.country = "India";
refNineteen.numberOfBooks = 38000;
refNineteen.numberOfMagazines = 130;
refNineteen.numberOfJournals = 97;
refNineteen.numberOfComputers = 17;
refNineteen.numberOfMembers = 860;
refNineteen.hasReadingRoom = true;
refNineteen.hasEbooks = true;
refNineteen.hasAudiobooks = false;
refNineteen.hasWifi = true;
refNineteen.hasParking = false;
refNineteen.hasCafeteria = false;
refNineteen.hasStudyRooms = true;
refNineteen.hasPrintingFacility = true;
refNineteen.librarianName = "S. Raghavan";
refNineteen.establishedYear = 2000;
refNineteen.contactNumber = "9894455667";
refNineteen.email = "info@heritagelibrary.org";
refNineteen.website = "www.heritagelibrary.org";
refNineteen.libraryType = "Public Library";

System.out.println("The libraryId is: " + refNineteen.libraryId);
System.out.println("The libraryName is: " + refNineteen.libraryName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfBooks is: " + refNineteen.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refNineteen.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refNineteen.numberOfJournals);
System.out.println("The numberOfComputers is: " + refNineteen.numberOfComputers);
System.out.println("The numberOfMembers is: " + refNineteen.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refNineteen.hasReadingRoom);
System.out.println("The hasEbooks is: " + refNineteen.hasEbooks);
System.out.println("The hasAudiobooks is: " + refNineteen.hasAudiobooks);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasCafeteria is: " + refNineteen.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refNineteen.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refNineteen.hasPrintingFacility);
System.out.println("The librarianName is: " + refNineteen.librarianName);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The libraryType is: " + refNineteen.libraryType);
Library refTwenty = new Library();

System.out.println("The libraryId is: " + refTwenty.libraryId);
System.out.println("The libraryName is: " + refTwenty.libraryName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfBooks is: " + refTwenty.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refTwenty.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refTwenty.numberOfJournals);
System.out.println("The numberOfComputers is: " + refTwenty.numberOfComputers);
System.out.println("The numberOfMembers is: " + refTwenty.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refTwenty.hasReadingRoom);
System.out.println("The hasEbooks is: " + refTwenty.hasEbooks);
System.out.println("The hasAudiobooks is: " + refTwenty.hasAudiobooks);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasCafeteria is: " + refTwenty.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refTwenty.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refTwenty.hasPrintingFacility);
System.out.println("The librarianName is: " + refTwenty.librarianName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The libraryType is: " + refTwenty.libraryType);

refTwenty.libraryId = 20;
refTwenty.libraryName = "Future Minds Library";
refTwenty.location = "IT Park Road";
refTwenty.city = "Bengaluru";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.numberOfBooks = 52000;
refTwenty.numberOfMagazines = 180;
refTwenty.numberOfJournals = 130;
refTwenty.numberOfComputers = 35;
refTwenty.numberOfMembers = 1500;
refTwenty.hasReadingRoom = true;
refTwenty.hasEbooks = true;
refTwenty.hasAudiobooks = true;
refTwenty.hasWifi = true;
refTwenty.hasParking = true;
refTwenty.hasCafeteria = true;
refTwenty.hasStudyRooms = true;
refTwenty.hasPrintingFacility = true;
refTwenty.librarianName = "Ananya Rao";
refTwenty.establishedYear = 2015;
refTwenty.contactNumber = "9876501234";
refTwenty.email = "contact@futuremindslibrary.org";
refTwenty.website = "www.futuremindslibrary.org";
refTwenty.libraryType = "Digital & Public Library";

System.out.println("The libraryId is: " + refTwenty.libraryId);
System.out.println("The libraryName is: " + refTwenty.libraryName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfBooks is: " + refTwenty.numberOfBooks);
System.out.println("The numberOfMagazines is: " + refTwenty.numberOfMagazines);
System.out.println("The numberOfJournals is: " + refTwenty.numberOfJournals);
System.out.println("The numberOfComputers is: " + refTwenty.numberOfComputers);
System.out.println("The numberOfMembers is: " + refTwenty.numberOfMembers);
System.out.println("The hasReadingRoom is: " + refTwenty.hasReadingRoom);
System.out.println("The hasEbooks is: " + refTwenty.hasEbooks);
System.out.println("The hasAudiobooks is: " + refTwenty.hasAudiobooks);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasCafeteria is: " + refTwenty.hasCafeteria);
System.out.println("The hasStudyRooms is: " + refTwenty.hasStudyRooms);
System.out.println("The hasPrintingFacility is: " + refTwenty.hasPrintingFacility);
System.out.println("The librarianName is: " + refTwenty.librarianName);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The libraryType is: " + refTwenty.libraryType);
}
}