class MarvelExecutor {
    public static void main(String[] args) {

        Marvel m1 = new Marvel();
        m1.setHeroId(1);
        m1.setHeroName("IronMan");
        m1.setRealName("Tony Stark");
        m1.setPower("Intelligence");
        m1.setWeapon("Suit");
        m1.setTeam("Avengers");
        m1.setDebutYear("2008");
        System.out.println(m1.getHeroId());
        System.out.println(m1.getHeroName());
        System.out.println(m1.getRealName());
        System.out.println(m1.getPower());
        System.out.println(m1.getWeapon());
        System.out.println(m1.getTeam());
        System.out.println(m1.getDebutYear());

        Marvel m2 = new Marvel();
        m2.setHeroId(2);
        m2.setHeroName("Captain America");
        m2.setRealName("Steve Rogers");
        m2.setPower("Strength");
        m2.setWeapon("Shield");
        m2.setTeam("Avengers");
        m2.setDebutYear("2011");
        System.out.println(m2.getHeroId());
        System.out.println(m2.getHeroName());
        System.out.println(m2.getRealName());
        System.out.println(m2.getPower());
        System.out.println(m2.getWeapon());
        System.out.println(m2.getTeam());
        System.out.println(m2.getDebutYear());

        Marvel m3 = new Marvel();
        m3.setHeroId(3);
        m3.setHeroName("Thor");
        m3.setRealName("Thor Odinson");
        m3.setPower("Thunder");
        m3.setWeapon("Mjolnir");
        m3.setTeam("Avengers");
        m3.setDebutYear("2011");
        System.out.println(m3.getHeroId());
        System.out.println(m3.getHeroName());
        System.out.println(m3.getRealName());
        System.out.println(m3.getPower());
        System.out.println(m3.getWeapon());
        System.out.println(m3.getTeam());
        System.out.println(m3.getDebutYear());

        Marvel m4 = new Marvel();
        m4.setHeroId(4);
        m4.setHeroName("Hulk");
        m4.setRealName("Bruce Banner");
        m4.setPower("Strength");
        m4.setWeapon("Fist");
        m4.setTeam("Avengers");
        m4.setDebutYear("2012");
        System.out.println(m4.getHeroId());
        System.out.println(m4.getHeroName());
        System.out.println(m4.getRealName());
        System.out.println(m4.getPower());
        System.out.println(m4.getWeapon());
        System.out.println(m4.getTeam());
        System.out.println(m4.getDebutYear());

        Marvel m5 = new Marvel();
        m5.setHeroId(5);
        m5.setHeroName("Black Widow");
        m5.setRealName("Natasha Romanoff");
        m5.setPower("Spy Skills");
        m5.setWeapon("Guns");
        m5.setTeam("Avengers");
        m5.setDebutYear("2010");
        System.out.println(m5.getHeroId());
        System.out.println(m5.getHeroName());
        System.out.println(m5.getRealName());
        System.out.println(m5.getPower());
        System.out.println(m5.getWeapon());
        System.out.println(m5.getTeam());
        System.out.println(m5.getDebutYear());

        Marvel m6 = new Marvel();
        m6.setHeroId(6);
        m6.setHeroName("Hawkeye");
        m6.setRealName("Clint Barton");
        m6.setPower("Accuracy");
        m6.setWeapon("Bow");
        m6.setTeam("Avengers");
        m6.setDebutYear("2012");
        System.out.println(m6.getHeroId());
        System.out.println(m6.getHeroName());
        System.out.println(m6.getRealName());
        System.out.println(m6.getPower());
        System.out.println(m6.getWeapon());
        System.out.println(m6.getTeam());
        System.out.println(m6.getDebutYear());

        Marvel m7 = new Marvel();
        m7.setHeroId(7);
        m7.setHeroName("SpiderMan");
        m7.setRealName("Peter Parker");
        m7.setPower("Spider Sense");
        m7.setWeapon("Web");
        m7.setTeam("Avengers");
        m7.setDebutYear("2016");
        System.out.println(m7.getHeroId());
        System.out.println(m7.getHeroName());
        System.out.println(m7.getRealName());
        System.out.println(m7.getPower());
        System.out.println(m7.getWeapon());
        System.out.println(m7.getTeam());
        System.out.println(m7.getDebutYear());

        Marvel m8 = new Marvel();
        m8.setHeroId(8);
        m8.setHeroName("Black Panther");
        m8.setRealName("TChalla");
        m8.setPower("Enhanced Strength");
        m8.setWeapon("Claws");
        m8.setTeam("Avengers");
        m8.setDebutYear("2018");
        System.out.println(m8.getHeroId());
        System.out.println(m8.getHeroName());
        System.out.println(m8.getRealName());
        System.out.println(m8.getPower());
        System.out.println(m8.getWeapon());
        System.out.println(m8.getTeam());
        System.out.println(m8.getDebutYear());

        Marvel m9 = new Marvel();
        m9.setHeroId(9);
        m9.setHeroName("Doctor Strange");
        m9.setRealName("Stephen Strange");
        m9.setPower("Magic");
        m9.setWeapon("Spells");
        m9.setTeam("Avengers");
        m9.setDebutYear("2016");
        System.out.println(m9.getHeroId());
        System.out.println(m9.getHeroName());
        System.out.println(m9.getRealName());
        System.out.println(m9.getPower());
        System.out.println(m9.getWeapon());
        System.out.println(m9.getTeam());
        System.out.println(m9.getDebutYear());

        Marvel m10 = new Marvel();
        m10.setHeroId(10);
        m10.setHeroName("Captain Marvel");
        m10.setRealName("Carol Danvers");
        m10.setPower("Energy");
        m10.setWeapon("Photon Blast");
        m10.setTeam("Avengers");
        m10.setDebutYear("2019");
        System.out.println(m10.getHeroId());
        System.out.println(m10.getHeroName());
        System.out.println(m10.getRealName());
        System.out.println(m10.getPower());
        System.out.println(m10.getWeapon());
        System.out.println(m10.getTeam());
        System.out.println(m10.getDebutYear());
		
		        Marvel m11 = new Marvel();
        m11.setHeroId(11);
        m11.setHeroName("AntMan");
        m11.setRealName("Scott Lang");
        m11.setPower("Size Change");
        m11.setWeapon("Suit");
        m11.setTeam("Avengers");
        m11.setDebutYear("2015");
        System.out.println(m11.getHeroId());
        System.out.println(m11.getHeroName());
        System.out.println(m11.getRealName());
        System.out.println(m11.getPower());
        System.out.println(m11.getWeapon());
        System.out.println(m11.getTeam());
        System.out.println(m11.getDebutYear());

        Marvel m12 = new Marvel();
        m12.setHeroId(12);
        m12.setHeroName("Wasp");
        m12.setRealName("Hope Van Dyne");
        m12.setPower("Flight");
        m12.setWeapon("Stings");
        m12.setTeam("Avengers");
        m12.setDebutYear("2018");
        System.out.println(m12.getHeroId());
        System.out.println(m12.getHeroName());
        System.out.println(m12.getRealName());
        System.out.println(m12.getPower());
        System.out.println(m12.getWeapon());
        System.out.println(m12.getTeam());
        System.out.println(m12.getDebutYear());

        Marvel m13 = new Marvel();
        m13.setHeroId(13);
        m13.setHeroName("Vision");
        m13.setRealName("Vision");
        m13.setPower("Mind Stone");
        m13.setWeapon("Energy Beam");
        m13.setTeam("Avengers");
        m13.setDebutYear("2015");
        System.out.println(m13.getHeroId());
        System.out.println(m13.getHeroName());
        System.out.println(m13.getRealName());
        System.out.println(m13.getPower());
        System.out.println(m13.getWeapon());
        System.out.println(m13.getTeam());
        System.out.println(m13.getDebutYear());

        Marvel m14 = new Marvel();
        m14.setHeroId(14);
        m14.setHeroName("Scarlet Witch");
        m14.setRealName("Wanda Maximoff");
        m14.setPower("Chaos Magic");
        m14.setWeapon("Magic");
        m14.setTeam("Avengers");
        m14.setDebutYear("2015");
        System.out.println(m14.getHeroId());
        System.out.println(m14.getHeroName());
        System.out.println(m14.getRealName());
        System.out.println(m14.getPower());
        System.out.println(m14.getWeapon());
        System.out.println(m14.getTeam());
        System.out.println(m14.getDebutYear());

        Marvel m15 = new Marvel();
        m15.setHeroId(15);
        m15.setHeroName("Falcon");
        m15.setRealName("Sam Wilson");
        m15.setPower("Flight");
        m15.setWeapon("Wings");
        m15.setTeam("Avengers");
        m15.setDebutYear("2014");
        System.out.println(m15.getHeroId());
        System.out.println(m15.getHeroName());
        System.out.println(m15.getRealName());
        System.out.println(m15.getPower());
        System.out.println(m15.getWeapon());
        System.out.println(m15.getTeam());
        System.out.println(m15.getDebutYear());

        Marvel m16 = new Marvel();
        m16.setHeroId(16);
        m16.setHeroName("Winter Soldier");
        m16.setRealName("Bucky Barnes");
        m16.setPower("Strength");
        m16.setWeapon("Arm");
        m16.setTeam("Avengers");
        m16.setDebutYear("2014");
        System.out.println(m16.getHeroId());
        System.out.println(m16.getHeroName());
        System.out.println(m16.getRealName());
        System.out.println(m16.getPower());
        System.out.println(m16.getWeapon());
        System.out.println(m16.getTeam());
        System.out.println(m16.getDebutYear());

        Marvel m17 = new Marvel();
        m17.setHeroId(17);
        m17.setHeroName("Star Lord");
        m17.setRealName("Peter Quill");
        m17.setPower("Leadership");
        m17.setWeapon("Gun");
        m17.setTeam("Guardians");
        m17.setDebutYear("2014");
        System.out.println(m17.getHeroId());
        System.out.println(m17.getHeroName());
        System.out.println(m17.getRealName());
        System.out.println(m17.getPower());
        System.out.println(m17.getWeapon());
        System.out.println(m17.getTeam());
        System.out.println(m17.getDebutYear());

        Marvel m18 = new Marvel();
        m18.setHeroId(18);
        m18.setHeroName("Gamora");
        m18.setRealName("Gamora");
        m18.setPower("Strength");
        m18.setWeapon("Sword");
        m18.setTeam("Guardians");
        m18.setDebutYear("2014");
        System.out.println(m18.getHeroId());
        System.out.println(m18.getHeroName());
        System.out.println(m18.getRealName());
        System.out.println(m18.getPower());
        System.out.println(m18.getWeapon());
        System.out.println(m18.getTeam());
        System.out.println(m18.getDebutYear());

        Marvel m19 = new Marvel();
        m19.setHeroId(19);
        m19.setHeroName("Groot");
        m19.setRealName("Groot");
        m19.setPower("Regeneration");
        m19.setWeapon("Body");
        m19.setTeam("Guardians");
        m19.setDebutYear("2014");
        System.out.println(m19.getHeroId());
        System.out.println(m19.getHeroName());
        System.out.println(m19.getRealName());
        System.out.println(m19.getPower());
        System.out.println(m19.getWeapon());
        System.out.println(m19.getTeam());
        System.out.println(m19.getDebutYear());

        Marvel m20 = new Marvel();
        m20.setHeroId(20);
        m20.setHeroName("Rocket");
        m20.setRealName("Rocket");
        m20.setPower("Intelligence");
        m20.setWeapon("Gun");
        m20.setTeam("Guardians");
        m20.setDebutYear("2014");
        System.out.println(m20.getHeroId());
        System.out.println(m20.getHeroName());
        System.out.println(m20.getRealName());
        System.out.println(m20.getPower());
        System.out.println(m20.getWeapon());
        System.out.println(m20.getTeam());
        System.out.println(m20.getDebutYear());

        Marvel m21 = new Marvel();
        m21.setHeroId(21);
        m21.setHeroName("Drax");
        m21.setRealName("Drax");
        m21.setPower("Strength");
        m21.setWeapon("Blades");
        m21.setTeam("Guardians");
        m21.setDebutYear("2014");
        System.out.println(m21.getHeroId());
        System.out.println(m21.getHeroName());
        System.out.println(m21.getRealName());
        System.out.println(m21.getPower());
        System.out.println(m21.getWeapon());
        System.out.println(m21.getTeam());
        System.out.println(m21.getDebutYear());

        Marvel m22 = new Marvel();
        m22.setHeroId(22);
        m22.setHeroName("Loki");
        m22.setRealName("Loki");
        m22.setPower("Magic");
        m22.setWeapon("Illusions");
        m22.setTeam("Villain");
        m22.setDebutYear("2011");
        System.out.println(m22.getHeroId());
        System.out.println(m22.getHeroName());
        System.out.println(m22.getRealName());
        System.out.println(m22.getPower());
        System.out.println(m22.getWeapon());
        System.out.println(m22.getTeam());
        System.out.println(m22.getDebutYear());

        Marvel m23 = new Marvel();
        m23.setHeroId(23);
        m23.setHeroName("Deadpool");
        m23.setRealName("Wade Wilson");
        m23.setPower("Regeneration");
        m23.setWeapon("Swords");
        m23.setTeam("XForce");
        m23.setDebutYear("2016");
        System.out.println(m23.getHeroId());
        System.out.println(m23.getHeroName());
        System.out.println(m23.getRealName());
        System.out.println(m23.getPower());
        System.out.println(m23.getWeapon());
        System.out.println(m23.getTeam());
        System.out.println(m23.getDebutYear());

        Marvel m24 = new Marvel();
        m24.setHeroId(24);
        m24.setHeroName("Wolverine");
        m24.setRealName("Logan");
        m24.setPower("Healing");
        m24.setWeapon("Claws");
        m24.setTeam("XMen");
        m24.setDebutYear("2000");
        System.out.println(m24.getHeroId());
        System.out.println(m24.getHeroName());
        System.out.println(m24.getRealName());
        System.out.println(m24.getPower());
        System.out.println(m24.getWeapon());
        System.out.println(m24.getTeam());
        System.out.println(m24.getDebutYear());

        Marvel m25 = new Marvel();
        m25.setHeroId(25);
        m25.setHeroName("Storm");
        m25.setRealName("Ororo Munroe");
        m25.setPower("Weather");
        m25.setWeapon("Lightning");
        m25.setTeam("XMen");
        m25.setDebutYear("2000");
        System.out.println(m25.getHeroId());
        System.out.println(m25.getHeroName());
        System.out.println(m25.getRealName());
        System.out.println(m25.getPower());
        System.out.println(m25.getWeapon());
        System.out.println(m25.getTeam());
        System.out.println(m25.getDebutYear());

        Marvel m26 = new Marvel();
        m26.setHeroId(26);
        m26.setHeroName("Cyclops");
        m26.setRealName("Scott Summers");
        m26.setPower("Optic Blast");
        m26.setWeapon("Eyes");
        m26.setTeam("XMen");
        m26.setDebutYear("2000");
        System.out.println(m26.getHeroId());
        System.out.println(m26.getHeroName());
        System.out.println(m26.getRealName());
        System.out.println(m26.getPower());
        System.out.println(m26.getWeapon());
        System.out.println(m26.getTeam());
        System.out.println(m26.getDebutYear());

        Marvel m27 = new Marvel();
        m27.setHeroId(27);
        m27.setHeroName("Jean Grey");
        m27.setRealName("Jean Grey");
        m27.setPower("Telepathy");
        m27.setWeapon("Mind");
        m27.setTeam("XMen");
        m27.setDebutYear("2000");
        System.out.println(m27.getHeroId());
        System.out.println(m27.getHeroName());
        System.out.println(m27.getRealName());
        System.out.println(m27.getPower());
        System.out.println(m27.getWeapon());
        System.out.println(m27.getTeam());
        System.out.println(m27.getDebutYear());

        Marvel m28 = new Marvel();
        m28.setHeroId(28);
        m28.setHeroName("Professor X");
        m28.setRealName("Charles Xavier");
        m28.setPower("Mind Control");
        m28.setWeapon("Brain");
        m28.setTeam("XMen");
        m28.setDebutYear("2000");
        System.out.println(m28.getHeroId());
        System.out.println(m28.getHeroName());
        System.out.println(m28.getRealName());
        System.out.println(m28.getPower());
        System.out.println(m28.getWeapon());
        System.out.println(m28.getTeam());
        System.out.println(m28.getDebutYear());

        Marvel m29 = new Marvel();
        m29.setHeroId(29);
        m29.setHeroName("Daredevil");
        m29.setRealName("Matt Murdock");
        m29.setPower("Senses");
        m29.setWeapon("Stick");
        m29.setTeam("Defenders");
        m29.setDebutYear("2015");
        System.out.println(m29.getHeroId());
        System.out.println(m29.getHeroName());
        System.out.println(m29.getRealName());
        System.out.println(m29.getPower());
        System.out.println(m29.getWeapon());
        System.out.println(m29.getTeam());
        System.out.println(m29.getDebutYear());
		}
	}