class MedicineExecutor {
    public static void main(String[] args) {

        Medicine m1 = new Medicine();
        m1.setMedicineId(1);
        m1.setName("Medicine1");
        m1.setManufacturer("Company1");
        m1.setPrice(10.0);
        m1.setExpiryDate("2026-01-01");
        m1.setDosage("100mg");
        m1.setType("Tablet");
        System.out.println(m1.getMedicineId());
        System.out.println(m1.getName());
        System.out.println(m1.getManufacturer());
        System.out.println(m1.getPrice());
        System.out.println(m1.getExpiryDate());
        System.out.println(m1.getDosage());
        System.out.println(m1.getType());

        Medicine m2 = new Medicine();
        m2.setMedicineId(2);
        m2.setName("Medicine2");
        m2.setManufacturer("Company2");
        m2.setPrice(20.0);
        m2.setExpiryDate("2026-02-01");
        m2.setDosage("200mg");
        m2.setType("Syrup");
        System.out.println(m2.getMedicineId());
        System.out.println(m2.getName());
        System.out.println(m2.getManufacturer());
        System.out.println(m2.getPrice());
        System.out.println(m2.getExpiryDate());
        System.out.println(m2.getDosage());
        System.out.println(m2.getType());

        Medicine m3 = new Medicine();
        m3.setMedicineId(3);
        m3.setName("Medicine3");
        m3.setManufacturer("Company3");
        m3.setPrice(30.0);
        m3.setExpiryDate("2026-03-01");
        m3.setDosage("300mg");
        m3.setType("Injection");
        System.out.println(m3.getMedicineId());
        System.out.println(m3.getName());
        System.out.println(m3.getManufacturer());
        System.out.println(m3.getPrice());
        System.out.println(m3.getExpiryDate());
        System.out.println(m3.getDosage());
        System.out.println(m3.getType());

        Medicine m4 = new Medicine();
        m4.setMedicineId(4);
        m4.setName("Medicine4");
        m4.setManufacturer("Company4");
        m4.setPrice(40.0);
        m4.setExpiryDate("2026-04-01");
        m4.setDosage("400mg");
        m4.setType("Tablet");
        System.out.println(m4.getMedicineId());
        System.out.println(m4.getName());
        System.out.println(m4.getManufacturer());
        System.out.println(m4.getPrice());
        System.out.println(m4.getExpiryDate());
        System.out.println(m4.getDosage());
        System.out.println(m4.getType());

        Medicine m5 = new Medicine();
        m5.setMedicineId(5);
        m5.setName("Medicine5");
        m5.setManufacturer("Company5");
        m5.setPrice(50.0);
        m5.setExpiryDate("2026-05-01");
        m5.setDosage("500mg");
        m5.setType("Syrup");
        System.out.println(m5.getMedicineId());
        System.out.println(m5.getName());
        System.out.println(m5.getManufacturer());
        System.out.println(m5.getPrice());
        System.out.println(m5.getExpiryDate());
        System.out.println(m5.getDosage());
        System.out.println(m5.getType());

        Medicine m6 = new Medicine();
        m6.setMedicineId(6);
        m6.setName("Medicine6");
        m6.setManufacturer("Company6");
        m6.setPrice(60.0);
        m6.setExpiryDate("2026-06-01");
        m6.setDosage("600mg");
        m6.setType("Injection");
        System.out.println(m6.getMedicineId());
        System.out.println(m6.getName());
        System.out.println(m6.getManufacturer());
        System.out.println(m6.getPrice());
        System.out.println(m6.getExpiryDate());
        System.out.println(m6.getDosage());
        System.out.println(m6.getType());

        Medicine m7 = new Medicine();
        m7.setMedicineId(7);
        m7.setName("Medicine7");
        m7.setManufacturer("Company7");
        m7.setPrice(70.0);
        m7.setExpiryDate("2026-07-01");
        m7.setDosage("700mg");
        m7.setType("Tablet");
        System.out.println(m7.getMedicineId());
        System.out.println(m7.getName());
        System.out.println(m7.getManufacturer());
        System.out.println(m7.getPrice());
        System.out.println(m7.getExpiryDate());
        System.out.println(m7.getDosage());
        System.out.println(m7.getType());

        Medicine m8 = new Medicine();
        m8.setMedicineId(8);
        m8.setName("Medicine8");
        m8.setManufacturer("Company8");
        m8.setPrice(80.0);
        m8.setExpiryDate("2026-08-01");
        m8.setDosage("800mg");
        m8.setType("Syrup");
        System.out.println(m8.getMedicineId());
        System.out.println(m8.getName());
        System.out.println(m8.getManufacturer());
        System.out.println(m8.getPrice());
        System.out.println(m8.getExpiryDate());
        System.out.println(m8.getDosage());
        System.out.println(m8.getType());

        Medicine m9 = new Medicine();
        m9.setMedicineId(9);
        m9.setName("Medicine9");
        m9.setManufacturer("Company9");
        m9.setPrice(90.0);
        m9.setExpiryDate("2026-09-01");
        m9.setDosage("900mg");
        m9.setType("Injection");
        System.out.println(m9.getMedicineId());
        System.out.println(m9.getName());
        System.out.println(m9.getManufacturer());
        System.out.println(m9.getPrice());
        System.out.println(m9.getExpiryDate());
        System.out.println(m9.getDosage());
        System.out.println(m9.getType());

        Medicine m10 = new Medicine();
        m10.setMedicineId(10);
        m10.setName("Medicine10");
        m10.setManufacturer("Company10");
        m10.setPrice(100.0);
        m10.setExpiryDate("2026-10-01");
        m10.setDosage("1000mg");
        m10.setType("Tablet");
        System.out.println(m10.getMedicineId());
        System.out.println(m10.getName());
        System.out.println(m10.getManufacturer());
        System.out.println(m10.getPrice());
        System.out.println(m10.getExpiryDate());
        System.out.println(m10.getDosage());
        System.out.println(m10.getType());

        Medicine m11 = new Medicine();
        m11.setMedicineId(11);
        m11.setName("Medicine11");
        m11.setManufacturer("Company11");
        m11.setPrice(110.0);
        m11.setExpiryDate("2026-11-01");
        m11.setDosage("1100mg");
        m11.setType("Syrup");
        System.out.println(m11.getMedicineId());
        System.out.println(m11.getName());
        System.out.println(m11.getManufacturer());
        System.out.println(m11.getPrice());
        System.out.println(m11.getExpiryDate());
        System.out.println(m11.getDosage());
        System.out.println(m11.getType());

        Medicine m12 = new Medicine();
        m12.setMedicineId(12);
        m12.setName("Medicine12");
        m12.setManufacturer("Company12");
        m12.setPrice(120.0);
        m12.setExpiryDate("2026-12-01");
        m12.setDosage("1200mg");
        m12.setType("Injection");
        System.out.println(m12.getMedicineId());
        System.out.println(m12.getName());
        System.out.println(m12.getManufacturer());
        System.out.println(m12.getPrice());
        System.out.println(m12.getExpiryDate());
        System.out.println(m12.getDosage());
        System.out.println(m12.getType());

        Medicine m13 = new Medicine();
        m13.setMedicineId(13);
        m13.setName("Medicine13");
        m13.setManufacturer("Company13");
        m13.setPrice(130.0);
        m13.setExpiryDate("2027-01-01");
        m13.setDosage("1300mg");
        m13.setType("Tablet");
        System.out.println(m13.getMedicineId());
        System.out.println(m13.getName());
        System.out.println(m13.getManufacturer());
        System.out.println(m13.getPrice());
        System.out.println(m13.getExpiryDate());
        System.out.println(m13.getDosage());
        System.out.println(m13.getType());

        Medicine m14 = new Medicine();
        m14.setMedicineId(14);
        m14.setName("Medicine14");
        m14.setManufacturer("Company14");
        m14.setPrice(140.0);
        m14.setExpiryDate("2027-02-01");
        m14.setDosage("1400mg");
        m14.setType("Syrup");
        System.out.println(m14.getMedicineId());
        System.out.println(m14.getName());
        System.out.println(m14.getManufacturer());
        System.out.println(m14.getPrice());
        System.out.println(m14.getExpiryDate());
        System.out.println(m14.getDosage());
        System.out.println(m14.getType());

        Medicine m15 = new Medicine();
        m15.setMedicineId(15);
        m15.setName("Medicine15");
        m15.setManufacturer("Company15");
        m15.setPrice(150.0);
        m15.setExpiryDate("2027-03-01");
        m15.setDosage("1500mg");
        m15.setType("Injection");
        System.out.println(m15.getMedicineId());
        System.out.println(m15.getName());
        System.out.println(m15.getManufacturer());
        System.out.println(m15.getPrice());
        System.out.println(m15.getExpiryDate());
        System.out.println(m15.getDosage());
        System.out.println(m15.getType());

        Medicine m16 = new Medicine();
        m16.setMedicineId(16);
        m16.setName("Medicine16");
        m16.setManufacturer("Company16");
        m16.setPrice(160.0);
        m16.setExpiryDate("2027-04-01");
        m16.setDosage("1600mg");
        m16.setType("Tablet");
        System.out.println(m16.getMedicineId());
        System.out.println(m16.getName());
        System.out.println(m16.getManufacturer());
        System.out.println(m16.getPrice());
        System.out.println(m16.getExpiryDate());
        System.out.println(m16.getDosage());
        System.out.println(m16.getType());

        Medicine m17 = new Medicine();
        m17.setMedicineId(17);
        m17.setName("Medicine17");
        m17.setManufacturer("Company17");
        m17.setPrice(170.0);
        m17.setExpiryDate("2027-05-01");
        m17.setDosage("1700mg");
        m17.setType("Syrup");
        System.out.println(m17.getMedicineId());
        System.out.println(m17.getName());
        System.out.println(m17.getManufacturer());
        System.out.println(m17.getPrice());
        System.out.println(m17.getExpiryDate());
        System.out.println(m17.getDosage());
        System.out.println(m17.getType());

        Medicine m18 = new Medicine();
        m18.setMedicineId(18);
        m18.setName("Medicine18");
        m18.setManufacturer("Company18");
        m18.setPrice(180.0);
        m18.setExpiryDate("2027-06-01");
        m18.setDosage("1800mg");
        m18.setType("Injection");
        System.out.println(m18.getMedicineId());
        System.out.println(m18.getName());
        System.out.println(m18.getManufacturer());
        System.out.println(m18.getPrice());
        System.out.println(m18.getExpiryDate());
        System.out.println(m18.getDosage());
        System.out.println(m18.getType());

        Medicine m19 = new Medicine();
        m19.setMedicineId(19);
        m19.setName("Medicine19");
        m19.setManufacturer("Company19");
        m19.setPrice(190.0);
        m19.setExpiryDate("2027-07-01");
        m19.setDosage("1900mg");
        m19.setType("Tablet");
        System.out.println(m19.getMedicineId());
        System.out.println(m19.getName());
        System.out.println(m19.getManufacturer());
        System.out.println(m19.getPrice());
        System.out.println(m19.getExpiryDate());
        System.out.println(m19.getDosage());
        System.out.println(m19.getType());

        Medicine m20 = new Medicine();
        m20.setMedicineId(20);
        m20.setName("Medicine20");
        m20.setManufacturer("Company20");
        m20.setPrice(200.0);
        m20.setExpiryDate("2027-08-01");
        m20.setDosage("2000mg");
        m20.setType("Syrup");
        System.out.println(m20.getMedicineId());
        System.out.println(m20.getName());
        System.out.println(m20.getManufacturer());
        System.out.println(m20.getPrice());
        System.out.println(m20.getExpiryDate());
        System.out.println(m20.getDosage());
        System.out.println(m20.getType());

        Medicine m21 = new Medicine();
        m21.setMedicineId(21);
        m21.setName("Medicine21");
        m21.setManufacturer("Company21");
        m21.setPrice(210.0);
        m21.setExpiryDate("2027-09-01");
        m21.setDosage("2100mg");
        m21.setType("Injection");
        System.out.println(m21.getMedicineId());
        System.out.println(m21.getName());
        System.out.println(m21.getManufacturer());
        System.out.println(m21.getPrice());
        System.out.println(m21.getExpiryDate());
        System.out.println(m21.getDosage());
        System.out.println(m21.getType());

        Medicine m22 = new Medicine();
        m22.setMedicineId(22);
        m22.setName("Medicine22");
        m22.setManufacturer("Company22");
        m22.setPrice(220.0);
        m22.setExpiryDate("2027-10-01");
        m22.setDosage("2200mg");
        m22.setType("Tablet");
        System.out.println(m22.getMedicineId());
        System.out.println(m22.getName());
        System.out.println(m22.getManufacturer());
        System.out.println(m22.getPrice());
        System.out.println(m22.getExpiryDate());
        System.out.println(m22.getDosage());
        System.out.println(m22.getType());

        Medicine m23 = new Medicine();
        m23.setMedicineId(23);
        m23.setName("Medicine23");
        m23.setManufacturer("Company23");
        m23.setPrice(230.0);
        m23.setExpiryDate("2027-11-01");
        m23.setDosage("2300mg");
        m23.setType("Syrup");
        System.out.println(m23.getMedicineId());
        System.out.println(m23.getName());
        System.out.println(m23.getManufacturer());
        System.out.println(m23.getPrice());
        System.out.println(m23.getExpiryDate());
        System.out.println(m23.getDosage());
        System.out.println(m23.getType());

        Medicine m24 = new Medicine();
        m24.setMedicineId(24);
        m24.setName("Medicine24");
        m24.setManufacturer("Company24");
        m24.setPrice(240.0);
        m24.setExpiryDate("2027-12-01");
        m24.setDosage("2400mg");
        m24.setType("Injection");
        System.out.println(m24.getMedicineId());
        System.out.println(m24.getName());
        System.out.println(m24.getManufacturer());
        System.out.println(m24.getPrice());
        System.out.println(m24.getExpiryDate());
        System.out.println(m24.getDosage());
        System.out.println(m24.getType());

        Medicine m25 = new Medicine();
        m25.setMedicineId(25);
        m25.setName("Medicine25");
        m25.setManufacturer("Company25");
        m25.setPrice(250.0);
        m25.setExpiryDate("2028-01-01");
        m25.setDosage("2500mg");
        m25.setType("Tablet");
        System.out.println(m25.getMedicineId());
        System.out.println(m25.getName());
        System.out.println(m25.getManufacturer());
        System.out.println(m25.getPrice());
        System.out.println(m25.getExpiryDate());
        System.out.println(m25.getDosage());
        System.out.println(m25.getType());

        Medicine m26 = new Medicine();
        m26.setMedicineId(26);
        m26.setName("Medicine26");
        m26.setManufacturer("Company26");
        m26.setPrice(260.0);
        m26.setExpiryDate("2028-02-01");
        m26.setDosage("2600mg");
        m26.setType("Syrup");
        System.out.println(m26.getMedicineId());
        System.out.println(m26.getName());
        System.out.println(m26.getManufacturer());
        System.out.println(m26.getPrice());
        System.out.println(m26.getExpiryDate());
        System.out.println(m26.getDosage());
        System.out.println(m26.getType());

        Medicine m27 = new Medicine();
        m27.setMedicineId(27);
        m27.setName("Medicine27");
        m27.setManufacturer("Company27");
        m27.setPrice(270.0);
        m27.setExpiryDate("2028-03-01");
        m27.setDosage("2700mg");
        m27.setType("Injection");
        System.out.println(m27.getMedicineId());
        System.out.println(m27.getName());
        System.out.println(m27.getManufacturer());
        System.out.println(m27.getPrice());
        System.out.println(m27.getExpiryDate());
        System.out.println(m27.getDosage());
        System.out.println(m27.getType());

        Medicine m28 = new Medicine();
        m28.setMedicineId(28);
        m28.setName("Medicine28");
        m28.setManufacturer("Company28");
        m28.setPrice(280.0);
        m28.setExpiryDate("2028-04-01");
        m28.setDosage("2800mg");
        m28.setType("Tablet");
        System.out.println(m28.getMedicineId());
        System.out.println(m28.getName());
        System.out.println(m28.getManufacturer());
        System.out.println(m28.getPrice());
        System.out.println(m28.getExpiryDate());
        System.out.println(m28.getDosage());
        System.out.println(m28.getType());

        Medicine m29 = new Medicine();
        m29.setMedicineId(29);
        m29.setName("Medicine29");
        m29.setManufacturer("Company29");
        m29.setPrice(290.0);
        m29.setExpiryDate("2028-05-01");
        m29.setDosage("2900mg");
        m29.setType("Syrup");
        System.out.println(m29.getMedicineId());
        System.out.println(m29.getName());
        System.out.println(m29.getManufacturer());
        System.out.println(m29.getPrice());
        System.out.println(m29.getExpiryDate());
        System.out.println(m29.getDosage());
        System.out.println(m29.getType());
    }
}