class MobileExecutor{
public static void main(String[] args){
Mobile refOne = new Mobile();

System.out.println("The brand is: " + refOne.brand);
System.out.println("The model is: " + refOne.model);
System.out.println("The color is: " + refOne.color);
System.out.println("The price is: " + refOne.price);
System.out.println("The storage is: " + refOne.storage);
System.out.println("The ram is: " + refOne.ram);
System.out.println("The processor is: " + refOne.processor);
System.out.println("The screenSize is: " + refOne.screenSize);
System.out.println("The batteryCapacity is: " + refOne.batteryCapacity);
System.out.println("The has5G is: " + refOne.has5G);
System.out.println("The hasFingerprint is: " + refOne.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refOne.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refOne.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refOne.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refOne.rearCameraMP);
System.out.println("The frontCameraMP is: " + refOne.frontCameraMP);
System.out.println("The operatingSystem is: " + refOne.operatingSystem);
System.out.println("The launchYear is: " + refOne.launchYear);
System.out.println("The networkType is: " + refOne.networkType);
System.out.println("The dualSIM is: " + refOne.dualSIM);
System.out.println("The chargerType is: " + refOne.chargerType);
System.out.println("The waterproof is: " + refOne.waterproof);
System.out.println("The manufacturerCountry is: " + refOne.manufacturerCountry);
System.out.println("The ownerName is: " + refOne.ownerName);

refOne.mobileId = 1;
refOne.brand = "Samsung";
refOne.model = "Galaxy S23";
refOne.color = "Black";
refOne.price = 85000;
refOne.storage = 256;
refOne.ram = 12;
refOne.processor = "Snapdragon 8 Gen 2";
refOne.screenSize = 6.1;
refOne.batteryCapacity = 3900;
refOne.has5G = true;
refOne.hasFingerprint = true;
refOne.hasFaceUnlock = true;
refOne.hasFastCharging = true;
refOne.hasWirelessCharging = true;
refOne.rearCameraMP = 50;
refOne.frontCameraMP = 12;
refOne.operatingSystem = "Android";
refOne.launchYear = 2023;
refOne.networkType = "5G";
refOne.dualSIM = true;
refOne.chargerType = "USB-C";
refOne.waterproof = true;
refOne.manufacturerCountry = "South Korea";
refOne.ownerName = "Rahul";

System.out.println("The mobileId is: " + refOne.mobileId);
System.out.println("The brand is: " + refOne.brand);
System.out.println("The model is: " + refOne.model);
System.out.println("The color is: " + refOne.color);
System.out.println("The price is: " + refOne.price);
System.out.println("The storage is: " + refOne.storage);
System.out.println("The ram is: " + refOne.ram);
System.out.println("The processor is: " + refOne.processor);
System.out.println("The screenSize is: " + refOne.screenSize);
System.out.println("The batteryCapacity is: " + refOne.batteryCapacity);
System.out.println("The has5G is: " + refOne.has5G);
System.out.println("The hasFingerprint is: " + refOne.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refOne.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refOne.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refOne.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refOne.rearCameraMP);
System.out.println("The frontCameraMP is: " + refOne.frontCameraMP);
System.out.println("The operatingSystem is: " + refOne.operatingSystem);
System.out.println("The launchYear is: " + refOne.launchYear);
System.out.println("The networkType is: " + refOne.networkType);
System.out.println("The dualSIM is: " + refOne.dualSIM);
System.out.println("The chargerType is: " + refOne.chargerType);
System.out.println("The waterproof is: " + refOne.waterproof);
System.out.println("The manufacturerCountry is: " + refOne.manufacturerCountry);
System.out.println("The ownerName is: " + refOne.ownerName);
Mobile refTwo = new Mobile();

System.out.println("The brand is: " + refTwo.brand);
System.out.println("The model is: " + refTwo.model);
System.out.println("The color is: " + refTwo.color);
System.out.println("The price is: " + refTwo.price);
System.out.println("The storage is: " + refTwo.storage);
System.out.println("The ram is: " + refTwo.ram);
System.out.println("The processor is: " + refTwo.processor);
System.out.println("The screenSize is: " + refTwo.screenSize);
System.out.println("The batteryCapacity is: " + refTwo.batteryCapacity);
System.out.println("The has5G is: " + refTwo.has5G);
System.out.println("The hasFingerprint is: " + refTwo.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refTwo.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refTwo.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refTwo.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refTwo.rearCameraMP);
System.out.println("The frontCameraMP is: " + refTwo.frontCameraMP);
System.out.println("The operatingSystem is: " + refTwo.operatingSystem);
System.out.println("The launchYear is: " + refTwo.launchYear);
System.out.println("The networkType is: " + refTwo.networkType);
System.out.println("The dualSIM is: " + refTwo.dualSIM);
System.out.println("The chargerType is: " + refTwo.chargerType);
System.out.println("The waterproof is: " + refTwo.waterproof);
System.out.println("The manufacturerCountry is: " + refTwo.manufacturerCountry);
System.out.println("The ownerName is: " + refTwo.ownerName);

refTwo.mobileId = 2;
refTwo.brand = "Apple";
refTwo.model = "iPhone 14";
refTwo.color = "Blue";
refTwo.price = 95000;
refTwo.storage = 256;
refTwo.ram = 6;
refTwo.processor = "A15 Bionic";
refTwo.screenSize = 6.1;
refTwo.batteryCapacity = 3279;
refTwo.has5G = true;
refTwo.hasFingerprint = false;
refTwo.hasFaceUnlock = true;
refTwo.hasFastCharging = true;
refTwo.hasWirelessCharging = true;
refTwo.rearCameraMP = 48;
refTwo.frontCameraMP = 12;
refTwo.operatingSystem = "iOS";
refTwo.launchYear = 2022;
refTwo.networkType = "5G";
refTwo.dualSIM = true;
refTwo.chargerType = "Lightning";
refTwo.waterproof = true;
refTwo.manufacturerCountry = "USA";
refTwo.ownerName = "Arjun";

System.out.println("The mobileId is: " + refTwo.mobileId);
System.out.println("The brand is: " + refTwo.brand);
System.out.println("The model is: " + refTwo.model);
System.out.println("The color is: " + refTwo.color);
System.out.println("The price is: " + refTwo.price);
System.out.println("The storage is: " + refTwo.storage);
System.out.println("The ram is: " + refTwo.ram);
System.out.println("The processor is: " + refTwo.processor);
System.out.println("The screenSize is: " + refTwo.screenSize);
System.out.println("The batteryCapacity is: " + refTwo.batteryCapacity);
System.out.println("The has5G is: " + refTwo.has5G);
System.out.println("The hasFingerprint is: " + refTwo.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refTwo.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refTwo.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refTwo.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refTwo.rearCameraMP);
System.out.println("The frontCameraMP is: " + refTwo.frontCameraMP);
System.out.println("The operatingSystem is: " + refTwo.operatingSystem);
System.out.println("The launchYear is: " + refTwo.launchYear);
System.out.println("The networkType is: " + refTwo.networkType);
System.out.println("The dualSIM is: " + refTwo.dualSIM);
System.out.println("The chargerType is: " + refTwo.chargerType);
System.out.println("The waterproof is: " + refTwo.waterproof);
System.out.println("The manufacturerCountry is: " + refTwo.manufacturerCountry);
System.out.println("The ownerName is: " + refTwo.ownerName);
Mobile refThree = new Mobile();

System.out.println("The brand is: " + refThree.brand);
System.out.println("The model is: " + refThree.model);
System.out.println("The color is: " + refThree.color);
System.out.println("The price is: " + refThree.price);
System.out.println("The storage is: " + refThree.storage);
System.out.println("The ram is: " + refThree.ram);
System.out.println("The processor is: " + refThree.processor);
System.out.println("The screenSize is: " + refThree.screenSize);
System.out.println("The batteryCapacity is: " + refThree.batteryCapacity);
System.out.println("The has5G is: " + refThree.has5G);
System.out.println("The hasFingerprint is: " + refThree.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refThree.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refThree.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refThree.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refThree.rearCameraMP);
System.out.println("The frontCameraMP is: " + refThree.frontCameraMP);
System.out.println("The operatingSystem is: " + refThree.operatingSystem);
System.out.println("The launchYear is: " + refThree.launchYear);
System.out.println("The networkType is: " + refThree.networkType);
System.out.println("The dualSIM is: " + refThree.dualSIM);
System.out.println("The chargerType is: " + refThree.chargerType);
System.out.println("The waterproof is: " + refThree.waterproof);
System.out.println("The manufacturerCountry is: " + refThree.manufacturerCountry);
System.out.println("The ownerName is: " + refThree.ownerName);

refThree.mobileId = 3;
refThree.brand = "OnePlus";
refThree.model = "OnePlus 11";
refThree.color = "Green";
refThree.price = 62000;
refThree.storage = 256;
refThree.ram = 16;
refThree.processor = "Snapdragon 8 Gen 2";
refThree.screenSize = 6.7;
refThree.batteryCapacity = 5000;
refThree.has5G = true;
refThree.hasFingerprint = true;
refThree.hasFaceUnlock = true;
refThree.hasFastCharging = true;
refThree.hasWirelessCharging = false;
refThree.rearCameraMP = 50;
refThree.frontCameraMP = 16;
refThree.operatingSystem = "Android";
refThree.launchYear = 2023;
refThree.networkType = "5G";
refThree.dualSIM = true;
refThree.chargerType = "USB-C";
refThree.waterproof = false;
refThree.manufacturerCountry = "China";
refThree.ownerName = "Kiran";

System.out.println("The mobileId is: " + refThree.mobileId);
System.out.println("The brand is: " + refThree.brand);
System.out.println("The model is: " + refThree.model);
System.out.println("The color is: " + refThree.color);
System.out.println("The price is: " + refThree.price);
System.out.println("The storage is: " + refThree.storage);
System.out.println("The ram is: " + refThree.ram);
System.out.println("The processor is: " + refThree.processor);
System.out.println("The screenSize is: " + refThree.screenSize);
System.out.println("The batteryCapacity is: " + refThree.batteryCapacity);
System.out.println("The has5G is: " + refThree.has5G);
System.out.println("The hasFingerprint is: " + refThree.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refThree.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refThree.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refThree.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refThree.rearCameraMP);
System.out.println("The frontCameraMP is: " + refThree.frontCameraMP);
System.out.println("The operatingSystem is: " + refThree.operatingSystem);
System.out.println("The launchYear is: " + refThree.launchYear);
System.out.println("The networkType is: " + refThree.networkType);
System.out.println("The dualSIM is: " + refThree.dualSIM);
System.out.println("The chargerType is: " + refThree.chargerType);
System.out.println("The waterproof is: " + refThree.waterproof);
System.out.println("The manufacturerCountry is: " + refThree.manufacturerCountry);
System.out.println("The ownerName is: " + refThree.ownerName);
Mobile refFour = new Mobile();

System.out.println("The brand is: " + refFour.brand);
System.out.println("The model is: " + refFour.model);
System.out.println("The color is: " + refFour.color);
System.out.println("The price is: " + refFour.price);
System.out.println("The storage is: " + refFour.storage);
System.out.println("The ram is: " + refFour.ram);
System.out.println("The processor is: " + refFour.processor);
System.out.println("The screenSize is: " + refFour.screenSize);
System.out.println("The batteryCapacity is: " + refFour.batteryCapacity);
System.out.println("The has5G is: " + refFour.has5G);
System.out.println("The hasFingerprint is: " + refFour.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refFour.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refFour.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refFour.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refFour.rearCameraMP);
System.out.println("The frontCameraMP is: " + refFour.frontCameraMP);
System.out.println("The operatingSystem is: " + refFour.operatingSystem);
System.out.println("The launchYear is: " + refFour.launchYear);
System.out.println("The networkType is: " + refFour.networkType);
System.out.println("The dualSIM is: " + refFour.dualSIM);
System.out.println("The chargerType is: " + refFour.chargerType);
System.out.println("The waterproof is: " + refFour.waterproof);
System.out.println("The manufacturerCountry is: " + refFour.manufacturerCountry);
System.out.println("The ownerName is: " + refFour.ownerName);

refFour.mobileId = 4;
refFour.brand = "Xiaomi";
refFour.model = "Mi 12";
refFour.color = "Silver";
refFour.price = 48000;
refFour.storage = 256;
refFour.ram = 12;
refFour.processor = "Snapdragon 8 Gen 1";
refFour.screenSize = 6.3;
refFour.batteryCapacity = 4500;
refFour.has5G = true;
refFour.hasFingerprint = true;
refFour.hasFaceUnlock = true;
refFour.hasFastCharging = true;
refFour.hasWirelessCharging = true;
refFour.rearCameraMP = 50;
refFour.frontCameraMP = 32;
refFour.operatingSystem = "Android";
refFour.launchYear = 2022;
refFour.networkType = "5G";
refFour.dualSIM = true;
refFour.chargerType = "USB-C";
refFour.waterproof = false;
refFour.manufacturerCountry = "China";
refFour.ownerName = "Rohit";

System.out.println("The mobileId is: " + refFour.mobileId);
System.out.println("The brand is: " + refFour.brand);
System.out.println("The model is: " + refFour.model);
System.out.println("The color is: " + refFour.color);
System.out.println("The price is: " + refFour.price);
System.out.println("The storage is: " + refFour.storage);
System.out.println("The ram is: " + refFour.ram);
System.out.println("The processor is: " + refFour.processor);
System.out.println("The screenSize is: " + refFour.screenSize);
System.out.println("The batteryCapacity is: " + refFour.batteryCapacity);
System.out.println("The has5G is: " + refFour.has5G);
System.out.println("The hasFingerprint is: " + refFour.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refFour.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refFour.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refFour.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refFour.rearCameraMP);
System.out.println("The frontCameraMP is: " + refFour.frontCameraMP);
System.out.println("The operatingSystem is: " + refFour.operatingSystem);
System.out.println("The launchYear is: " + refFour.launchYear);
System.out.println("The networkType is: " + refFour.networkType);
System.out.println("The dualSIM is: " + refFour.dualSIM);
System.out.println("The chargerType is: " + refFour.chargerType);
System.out.println("The waterproof is: " + refFour.waterproof);
System.out.println("The manufacturerCountry is: " + refFour.manufacturerCountry);
System.out.println("The ownerName is: " + refFour.ownerName);
Mobile refFive = new Mobile();

System.out.println("The brand is: " + refFive.brand);
System.out.println("The model is: " + refFive.model);
System.out.println("The color is: " + refFive.color);
System.out.println("The price is: " + refFive.price);
System.out.println("The storage is: " + refFive.storage);
System.out.println("The ram is: " + refFive.ram);
System.out.println("The processor is: " + refFive.processor);
System.out.println("The screenSize is: " + refFive.screenSize);
System.out.println("The batteryCapacity is: " + refFive.batteryCapacity);
System.out.println("The has5G is: " + refFive.has5G);
System.out.println("The hasFingerprint is: " + refFive.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refFive.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refFive.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refFive.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refFive.rearCameraMP);
System.out.println("The frontCameraMP is: " + refFive.frontCameraMP);
System.out.println("The operatingSystem is: " + refFive.operatingSystem);
System.out.println("The launchYear is: " + refFive.launchYear);
System.out.println("The networkType is: " + refFive.networkType);
System.out.println("The dualSIM is: " + refFive.dualSIM);
System.out.println("The chargerType is: " + refFive.chargerType);
System.out.println("The waterproof is: " + refFive.waterproof);
System.out.println("The manufacturerCountry is: " + refFive.manufacturerCountry);
System.out.println("The ownerName is: " + refFive.ownerName);

refFive.mobileId = 5;
refFive.brand = "Google";
refFive.model = "Pixel 7";
refFive.color = "Black";
refFive.price = 60000;
refFive.storage = 128;
refFive.ram = 8;
refFive.processor = "Google Tensor G2";
refFive.screenSize = 6.3;
refFive.batteryCapacity = 4355;
refFive.has5G = true;
refFive.hasFingerprint = true;
refFive.hasFaceUnlock = true;
refFive.hasFastCharging = true;
refFive.hasWirelessCharging = true;
refFive.rearCameraMP = 50;
refFive.frontCameraMP = 10;
refFive.operatingSystem = "Android";
refFive.launchYear = 2022;
refFive.networkType = "5G";
refFive.dualSIM = true;
refFive.chargerType = "USB-C";
refFive.waterproof = true;
refFive.manufacturerCountry = "USA";
refFive.ownerName = "Arun";

System.out.println("The mobileId is: " + refFive.mobileId);
System.out.println("The brand is: " + refFive.brand);
System.out.println("The model is: " + refFive.model);
System.out.println("The color is: " + refFive.color);
System.out.println("The price is: " + refFive.price);
System.out.println("The storage is: " + refFive.storage);
System.out.println("The ram is: " + refFive.ram);
System.out.println("The processor is: " + refFive.processor);
System.out.println("The screenSize is: " + refFive.screenSize);
System.out.println("The batteryCapacity is: " + refFive.batteryCapacity);
System.out.println("The has5G is: " + refFive.has5G);
System.out.println("The hasFingerprint is: " + refFive.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refFive.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refFive.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refFive.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refFive.rearCameraMP);
System.out.println("The frontCameraMP is: " + refFive.frontCameraMP);
System.out.println("The operatingSystem is: " + refFive.operatingSystem);
System.out.println("The launchYear is: " + refFive.launchYear);
System.out.println("The networkType is: " + refFive.networkType);
System.out.println("The dualSIM is: " + refFive.dualSIM);
System.out.println("The chargerType is: " + refFive.chargerType);
System.out.println("The waterproof is: " + refFive.waterproof);
System.out.println("The manufacturerCountry is: " + refFive.manufacturerCountry);
System.out.println("The ownerName is: " + refFive.ownerName);
Mobile refSix = new Mobile();

System.out.println("The brand is: " + refSix.brand);
System.out.println("The model is: " + refSix.model);
System.out.println("The color is: " + refSix.color);
System.out.println("The price is: " + refSix.price);
System.out.println("The storage is: " + refSix.storage);
System.out.println("The ram is: " + refSix.ram);
System.out.println("The processor is: " + refSix.processor);
System.out.println("The screenSize is: " + refSix.screenSize);
System.out.println("The batteryCapacity is: " + refSix.batteryCapacity);
System.out.println("The has5G is: " + refSix.has5G);
System.out.println("The hasFingerprint is: " + refSix.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refSix.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refSix.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refSix.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refSix.rearCameraMP);
System.out.println("The frontCameraMP is: " + refSix.frontCameraMP);
System.out.println("The operatingSystem is: " + refSix.operatingSystem);
System.out.println("The launchYear is: " + refSix.launchYear);
System.out.println("The networkType is: " + refSix.networkType);
System.out.println("The dualSIM is: " + refSix.dualSIM);
System.out.println("The chargerType is: " + refSix.chargerType);
System.out.println("The waterproof is: " + refSix.waterproof);
System.out.println("The manufacturerCountry is: " + refSix.manufacturerCountry);
System.out.println("The ownerName is: " + refSix.ownerName);

refSix.mobileId = 6;
refSix.brand = "Vivo";
refSix.model = "V27";
refSix.color = "Purple";
refSix.price = 38000;
refSix.storage = 128;
refSix.ram = 8;
refSix.processor = "MediaTek Dimensity 7200";
refSix.screenSize = 6.78;
refSix.batteryCapacity = 4600;
refSix.has5G = true;
refSix.hasFingerprint = true;
refSix.hasFaceUnlock = true;
refSix.hasFastCharging = true;
refSix.hasWirelessCharging = false;
refSix.rearCameraMP = 50;
refSix.frontCameraMP = 32;
refSix.operatingSystem = "Android";
refSix.launchYear = 2023;
refSix.networkType = "5G";
refSix.dualSIM = true;
refSix.chargerType = "USB-C";
refSix.waterproof = false;
refSix.manufacturerCountry = "China";
refSix.ownerName = "Manoj";

System.out.println("The mobileId is: " + refSix.mobileId);
System.out.println("The brand is: " + refSix.brand);
System.out.println("The model is: " + refSix.model);
System.out.println("The color is: " + refSix.color);
System.out.println("The price is: " + refSix.price);
System.out.println("The storage is: " + refSix.storage);
System.out.println("The ram is: " + refSix.ram);
System.out.println("The processor is: " + refSix.processor);
System.out.println("The screenSize is: " + refSix.screenSize);
System.out.println("The batteryCapacity is: " + refSix.batteryCapacity);
System.out.println("The has5G is: " + refSix.has5G);
System.out.println("The hasFingerprint is: " + refSix.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refSix.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refSix.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refSix.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refSix.rearCameraMP);
System.out.println("The frontCameraMP is: " + refSix.frontCameraMP);
System.out.println("The operatingSystem is: " + refSix.operatingSystem);
System.out.println("The launchYear is: " + refSix.launchYear);
System.out.println("The networkType is: " + refSix.networkType);
System.out.println("The dualSIM is: " + refSix.dualSIM);
System.out.println("The chargerType is: " + refSix.chargerType);
System.out.println("The waterproof is: " + refSix.waterproof);
System.out.println("The manufacturerCountry is: " + refSix.manufacturerCountry);
System.out.println("The ownerName is: " + refSix.ownerName);
Mobile refSeven = new Mobile();

System.out.println("The brand is: " + refSeven.brand);
System.out.println("The model is: " + refSeven.model);
System.out.println("The color is: " + refSeven.color);
System.out.println("The price is: " + refSeven.price);
System.out.println("The storage is: " + refSeven.storage);
System.out.println("The ram is: " + refSeven.ram);
System.out.println("The processor is: " + refSeven.processor);
System.out.println("The screenSize is: " + refSeven.screenSize);
System.out.println("The batteryCapacity is: " + refSeven.batteryCapacity);
System.out.println("The has5G is: " + refSeven.has5G);
System.out.println("The hasFingerprint is: " + refSeven.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refSeven.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refSeven.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refSeven.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refSeven.rearCameraMP);
System.out.println("The frontCameraMP is: " + refSeven.frontCameraMP);
System.out.println("The operatingSystem is: " + refSeven.operatingSystem);
System.out.println("The launchYear is: " + refSeven.launchYear);
System.out.println("The networkType is: " + refSeven.networkType);
System.out.println("The dualSIM is: " + refSeven.dualSIM);
System.out.println("The chargerType is: " + refSeven.chargerType);
System.out.println("The waterproof is: " + refSeven.waterproof);
System.out.println("The manufacturerCountry is: " + refSeven.manufacturerCountry);
System.out.println("The ownerName is: " + refSeven.ownerName);

refSeven.mobileId = 7;
refSeven.brand = "Oppo";
refSeven.model = "Reno 10";
refSeven.color = "Gold";
refSeven.price = 42000;
refSeven.storage = 256;
refSeven.ram = 12;
refSeven.processor = "MediaTek Dimensity 7050";
refSeven.screenSize = 6.7;
refSeven.batteryCapacity = 4600;
refSeven.has5G = true;
refSeven.hasFingerprint = true;
refSeven.hasFaceUnlock = true;
refSeven.hasFastCharging = true;
refSeven.hasWirelessCharging = false;
refSeven.rearCameraMP = 64;
refSeven.frontCameraMP = 32;
refSeven.operatingSystem = "Android";
refSeven.launchYear = 2023;
refSeven.networkType = "5G";
refSeven.dualSIM = true;
refSeven.chargerType = "USB-C";
refSeven.waterproof = false;
refSeven.manufacturerCountry = "China";
refSeven.ownerName = "Sanjay";

System.out.println("The mobileId is: " + refSeven.mobileId);
System.out.println("The brand is: " + refSeven.brand);
System.out.println("The model is: " + refSeven.model);
System.out.println("The color is: " + refSeven.color);
System.out.println("The price is: " + refSeven.price);
System.out.println("The storage is: " + refSeven.storage);
System.out.println("The ram is: " + refSeven.ram);
System.out.println("The processor is: " + refSeven.processor);
System.out.println("The screenSize is: " + refSeven.screenSize);
System.out.println("The batteryCapacity is: " + refSeven.batteryCapacity);
System.out.println("The has5G is: " + refSeven.has5G);
System.out.println("The hasFingerprint is: " + refSeven.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refSeven.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refSeven.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refSeven.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refSeven.rearCameraMP);
System.out.println("The frontCameraMP is: " + refSeven.frontCameraMP);
System.out.println("The operatingSystem is: " + refSeven.operatingSystem);
System.out.println("The launchYear is: " + refSeven.launchYear);
System.out.println("The networkType is: " + refSeven.networkType);
System.out.println("The dualSIM is: " + refSeven.dualSIM);
System.out.println("The chargerType is: " + refSeven.chargerType);
System.out.println("The waterproof is: " + refSeven.waterproof);
System.out.println("The manufacturerCountry is: " + refSeven.manufacturerCountry);
System.out.println("The ownerName is: " + refSeven.ownerName);
Mobile refEight = new Mobile();

System.out.println("The brand is: " + refEight.brand);
System.out.println("The model is: " + refEight.model);
System.out.println("The color is: " + refEight.color);
System.out.println("The price is: " + refEight.price);
System.out.println("The storage is: " + refEight.storage);
System.out.println("The ram is: " + refEight.ram);
System.out.println("The processor is: " + refEight.processor);
System.out.println("The screenSize is: " + refEight.screenSize);
System.out.println("The batteryCapacity is: " + refEight.batteryCapacity);
System.out.println("The has5G is: " + refEight.has5G);
System.out.println("The hasFingerprint is: " + refEight.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refEight.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refEight.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refEight.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refEight.rearCameraMP);
System.out.println("The frontCameraMP is: " + refEight.frontCameraMP);
System.out.println("The operatingSystem is: " + refEight.operatingSystem);
System.out.println("The launchYear is: " + refEight.launchYear);
System.out.println("The networkType is: " + refEight.networkType);
System.out.println("The dualSIM is: " + refEight.dualSIM);
System.out.println("The chargerType is: " + refEight.chargerType);
System.out.println("The waterproof is: " + refEight.waterproof);
System.out.println("The manufacturerCountry is: " + refEight.manufacturerCountry);
System.out.println("The ownerName is: " + refEight.ownerName);

refEight.mobileId = 8;
refEight.brand = "Realme";
refEight.model = "GT Neo 3";
refEight.color = "Blue";
refEight.price = 36000;
refEight.storage = 256;
refEight.ram = 12;
refEight.processor = "MediaTek Dimensity 8100";
refEight.screenSize = 6.7;
refEight.batteryCapacity = 5000;
refEight.has5G = true;
refEight.hasFingerprint = true;
refEight.hasFaceUnlock = true;
refEight.hasFastCharging = true;
refEight.hasWirelessCharging = false;
refEight.rearCameraMP = 50;
refEight.frontCameraMP = 16;
refEight.operatingSystem = "Android";
refEight.launchYear = 2022;
refEight.networkType = "5G";
refEight.dualSIM = true;
refEight.chargerType = "USB-C";
refEight.waterproof = false;
refEight.manufacturerCountry = "China";
refEight.ownerName = "Deepak";

System.out.println("The mobileId is: " + refEight.mobileId);
System.out.println("The brand is: " + refEight.brand);
System.out.println("The model is: " + refEight.model);
System.out.println("The color is: " + refEight.color);
System.out.println("The price is: " + refEight.price);
System.out.println("The storage is: " + refEight.storage);
System.out.println("The ram is: " + refEight.ram);
System.out.println("The processor is: " + refEight.processor);
System.out.println("The screenSize is: " + refEight.screenSize);
System.out.println("The batteryCapacity is: " + refEight.batteryCapacity);
System.out.println("The has5G is: " + refEight.has5G);
System.out.println("The hasFingerprint is: " + refEight.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refEight.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refEight.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refEight.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refEight.rearCameraMP);
System.out.println("The frontCameraMP is: " + refEight.frontCameraMP);
System.out.println("The operatingSystem is: " + refEight.operatingSystem);
System.out.println("The launchYear is: " + refEight.launchYear);
System.out.println("The networkType is: " + refEight.networkType);
System.out.println("The dualSIM is: " + refEight.dualSIM);
System.out.println("The chargerType is: " + refEight.chargerType);
System.out.println("The waterproof is: " + refEight.waterproof);
System.out.println("The manufacturerCountry is: " + refEight.manufacturerCountry);
System.out.println("The ownerName is: " + refEight.ownerName);
Mobile refNine = new Mobile();

System.out.println("The brand is: " + refNine.brand);
System.out.println("The model is: " + refNine.model);
System.out.println("The color is: " + refNine.color);
System.out.println("The price is: " + refNine.price);
System.out.println("The storage is: " + refNine.storage);
System.out.println("The ram is: " + refNine.ram);
System.out.println("The processor is: " + refNine.processor);
System.out.println("The screenSize is: " + refNine.screenSize);
System.out.println("The batteryCapacity is: " + refNine.batteryCapacity);
System.out.println("The has5G is: " + refNine.has5G);
System.out.println("The hasFingerprint is: " + refNine.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refNine.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refNine.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refNine.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refNine.rearCameraMP);
System.out.println("The frontCameraMP is: " + refNine.frontCameraMP);
System.out.println("The operatingSystem is: " + refNine.operatingSystem);
System.out.println("The launchYear is: " + refNine.launchYear);
System.out.println("The networkType is: " + refNine.networkType);
System.out.println("The dualSIM is: " + refNine.dualSIM);
System.out.println("The chargerType is: " + refNine.chargerType);
System.out.println("The waterproof is: " + refNine.waterproof);
System.out.println("The manufacturerCountry is: " + refNine.manufacturerCountry);
System.out.println("The ownerName is: " + refNine.ownerName);

refNine.mobileId = 9;
refNine.brand = "Samsung";
refNine.model = "Galaxy S23";
refNine.color = "Black";
refNine.price = 75000;
refNine.storage = 256;
refNine.ram = 12;
refNine.processor = "Snapdragon 8 Gen 2";
refNine.screenSize = 6.1;
refNine.batteryCapacity = 3900;
refNine.has5G = true;
refNine.hasFingerprint = true;
refNine.hasFaceUnlock = true;
refNine.hasFastCharging = true;
refNine.hasWirelessCharging = true;
refNine.rearCameraMP = 50;
refNine.frontCameraMP = 12;
refNine.operatingSystem = "Android";
refNine.launchYear = 2023;
refNine.networkType = "5G";
refNine.dualSIM = true;
refNine.chargerType = "USB-C";
refNine.waterproof = true;
refNine.manufacturerCountry = "South Korea";
refNine.ownerName = "Arjun";

System.out.println("The mobileId is: " + refNine.mobileId);
System.out.println("The brand is: " + refNine.brand);
System.out.println("The model is: " + refNine.model);
System.out.println("The color is: " + refNine.color);
System.out.println("The price is: " + refNine.price);
System.out.println("The storage is: " + refNine.storage);
System.out.println("The ram is: " + refNine.ram);
System.out.println("The processor is: " + refNine.processor);
System.out.println("The screenSize is: " + refNine.screenSize);
System.out.println("The batteryCapacity is: " + refNine.batteryCapacity);
System.out.println("The has5G is: " + refNine.has5G);
System.out.println("The hasFingerprint is: " + refNine.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refNine.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refNine.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refNine.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refNine.rearCameraMP);
System.out.println("The frontCameraMP is: " + refNine.frontCameraMP);
System.out.println("The operatingSystem is: " + refNine.operatingSystem);
System.out.println("The launchYear is: " + refNine.launchYear);
System.out.println("The networkType is: " + refNine.networkType);
System.out.println("The dualSIM is: " + refNine.dualSIM);
System.out.println("The chargerType is: " + refNine.chargerType);
System.out.println("The waterproof is: " + refNine.waterproof);
System.out.println("The manufacturerCountry is: " + refNine.manufacturerCountry);
System.out.println("The ownerName is: " + refNine.ownerName);
Mobile refTen = new Mobile();

System.out.println("The brand is: " + refTen.brand);
System.out.println("The model is: " + refTen.model);
System.out.println("The color is: " + refTen.color);
System.out.println("The price is: " + refTen.price);
System.out.println("The storage is: " + refTen.storage);
System.out.println("The ram is: " + refTen.ram);
System.out.println("The processor is: " + refTen.processor);
System.out.println("The screenSize is: " + refTen.screenSize);
System.out.println("The batteryCapacity is: " + refTen.batteryCapacity);
System.out.println("The has5G is: " + refTen.has5G);
System.out.println("The hasFingerprint is: " + refTen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refTen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refTen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refTen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refTen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refTen.frontCameraMP);
System.out.println("The operatingSystem is: " + refTen.operatingSystem);
System.out.println("The launchYear is: " + refTen.launchYear);
System.out.println("The networkType is: " + refTen.networkType);
System.out.println("The dualSIM is: " + refTen.dualSIM);
System.out.println("The chargerType is: " + refTen.chargerType);
System.out.println("The waterproof is: " + refTen.waterproof);
System.out.println("The manufacturerCountry is: " + refTen.manufacturerCountry);
System.out.println("The ownerName is: " + refTen.ownerName);

refTen.mobileId = 10;
refTen.brand = "OnePlus";
refTen.model = "OnePlus 11";
refTen.color = "Green";
refTen.price = 65000;
refTen.storage = 256;
refTen.ram = 16;
refTen.processor = "Snapdragon 8 Gen 2";
refTen.screenSize = 6.7;
refTen.batteryCapacity = 5000;
refTen.has5G = true;
refTen.hasFingerprint = true;
refTen.hasFaceUnlock = true;
refTen.hasFastCharging = true;
refTen.hasWirelessCharging = false;
refTen.rearCameraMP = 50;
refTen.frontCameraMP = 16;
refTen.operatingSystem = "Android";
refTen.launchYear = 2023;
refTen.networkType = "5G";
refTen.dualSIM = true;
refTen.chargerType = "USB-C";
refTen.waterproof = true;
refTen.manufacturerCountry = "China";
refTen.ownerName = "Rahul";

System.out.println("The mobileId is: " + refTen.mobileId);
System.out.println("The brand is: " + refTen.brand);
System.out.println("The model is: " + refTen.model);
System.out.println("The color is: " + refTen.color);
System.out.println("The price is: " + refTen.price);
System.out.println("The storage is: " + refTen.storage);
System.out.println("The ram is: " + refTen.ram);
System.out.println("The processor is: " + refTen.processor);
System.out.println("The screenSize is: " + refTen.screenSize);
System.out.println("The batteryCapacity is: " + refTen.batteryCapacity);
System.out.println("The has5G is: " + refTen.has5G);
System.out.println("The hasFingerprint is: " + refTen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refTen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refTen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refTen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refTen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refTen.frontCameraMP);
System.out.println("The operatingSystem is: " + refTen.operatingSystem);
System.out.println("The launchYear is: " + refTen.launchYear);
System.out.println("The networkType is: " + refTen.networkType);
System.out.println("The dualSIM is: " + refTen.dualSIM);
System.out.println("The chargerType is: " + refTen.chargerType);
System.out.println("The waterproof is: " + refTen.waterproof);
System.out.println("The manufacturerCountry is: " + refTen.manufacturerCountry);
System.out.println("The ownerName is: " + refTen.ownerName);
Mobile refEleven = new Mobile();

System.out.println("The brand is: " + refEleven.brand);
System.out.println("The model is: " + refEleven.model);
System.out.println("The color is: " + refEleven.color);
System.out.println("The price is: " + refEleven.price);
System.out.println("The storage is: " + refEleven.storage);
System.out.println("The ram is: " + refEleven.ram);
System.out.println("The processor is: " + refEleven.processor);
System.out.println("The screenSize is: " + refEleven.screenSize);
System.out.println("The batteryCapacity is: " + refEleven.batteryCapacity);
System.out.println("The has5G is: " + refEleven.has5G);
System.out.println("The hasFingerprint is: " + refEleven.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refEleven.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refEleven.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refEleven.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refEleven.rearCameraMP);
System.out.println("The frontCameraMP is: " + refEleven.frontCameraMP);
System.out.println("The operatingSystem is: " + refEleven.operatingSystem);
System.out.println("The launchYear is: " + refEleven.launchYear);
System.out.println("The networkType is: " + refEleven.networkType);
System.out.println("The dualSIM is: " + refEleven.dualSIM);
System.out.println("The chargerType is: " + refEleven.chargerType);
System.out.println("The waterproof is: " + refEleven.waterproof);
System.out.println("The manufacturerCountry is: " + refEleven.manufacturerCountry);
System.out.println("The ownerName is: " + refEleven.ownerName);

refEleven.mobileId = 11;
refEleven.brand = "Apple";
refEleven.model = "iPhone 14";
refEleven.color = "Midnight";
refEleven.price = 80000;
refEleven.storage = 128;
refEleven.ram = 6;
refEleven.processor = "A15 Bionic";
refEleven.screenSize = 6.1;
refEleven.batteryCapacity = 3279;
refEleven.has5G = true;
refEleven.hasFingerprint = false;
refEleven.hasFaceUnlock = true;
refEleven.hasFastCharging = true;
refEleven.hasWirelessCharging = true;
refEleven.rearCameraMP = 12;
refEleven.frontCameraMP = 12;
refEleven.operatingSystem = "iOS";
refEleven.launchYear = 2022;
refEleven.networkType = "5G";
refEleven.dualSIM = true;
refEleven.chargerType = "Lightning";
refEleven.waterproof = true;
refEleven.manufacturerCountry = "USA";
refEleven.ownerName = "Kiran";

System.out.println("The mobileId is: " + refEleven.mobileId);
System.out.println("The brand is: " + refEleven.brand);
System.out.println("The model is: " + refEleven.model);
System.out.println("The color is: " + refEleven.color);
System.out.println("The price is: " + refEleven.price);
System.out.println("The storage is: " + refEleven.storage);
System.out.println("The ram is: " + refEleven.ram);
System.out.println("The processor is: " + refEleven.processor);
System.out.println("The screenSize is: " + refEleven.screenSize);
System.out.println("The batteryCapacity is: " + refEleven.batteryCapacity);
System.out.println("The has5G is: " + refEleven.has5G);
System.out.println("The hasFingerprint is: " + refEleven.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refEleven.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refEleven.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refEleven.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refEleven.rearCameraMP);
System.out.println("The frontCameraMP is: " + refEleven.frontCameraMP);
System.out.println("The operatingSystem is: " + refEleven.operatingSystem);
System.out.println("The launchYear is: " + refEleven.launchYear);
System.out.println("The networkType is: " + refEleven.networkType);
System.out.println("The dualSIM is: " + refEleven.dualSIM);
System.out.println("The chargerType is: " + refEleven.chargerType);
System.out.println("The waterproof is: " + refEleven.waterproof);
System.out.println("The manufacturerCountry is: " + refEleven.manufacturerCountry);
System.out.println("The ownerName is: " + refEleven.ownerName);
Mobile refTwelve = new Mobile();

System.out.println("The brand is: " + refTwelve.brand);
System.out.println("The model is: " + refTwelve.model);
System.out.println("The color is: " + refTwelve.color);
System.out.println("The price is: " + refTwelve.price);
System.out.println("The storage is: " + refTwelve.storage);
System.out.println("The ram is: " + refTwelve.ram);
System.out.println("The processor is: " + refTwelve.processor);
System.out.println("The screenSize is: " + refTwelve.screenSize);
System.out.println("The batteryCapacity is: " + refTwelve.batteryCapacity);
System.out.println("The has5G is: " + refTwelve.has5G);
System.out.println("The hasFingerprint is: " + refTwelve.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refTwelve.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refTwelve.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refTwelve.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refTwelve.rearCameraMP);
System.out.println("The frontCameraMP is: " + refTwelve.frontCameraMP);
System.out.println("The operatingSystem is: " + refTwelve.operatingSystem);
System.out.println("The launchYear is: " + refTwelve.launchYear);
System.out.println("The networkType is: " + refTwelve.networkType);
System.out.println("The dualSIM is: " + refTwelve.dualSIM);
System.out.println("The chargerType is: " + refTwelve.chargerType);
System.out.println("The waterproof is: " + refTwelve.waterproof);
System.out.println("The manufacturerCountry is: " + refTwelve.manufacturerCountry);
System.out.println("The ownerName is: " + refTwelve.ownerName);

refTwelve.mobileId = 12;
refTwelve.brand = "Vivo";
refTwelve.model = "Vivo V27";
refTwelve.color = "Purple";
refTwelve.price = 33000;
refTwelve.storage = 256;
refTwelve.ram = 8;
refTwelve.processor = "MediaTek Dimensity 7200";
refTwelve.screenSize = 6.78;
refTwelve.batteryCapacity = 4600;
refTwelve.has5G = true;
refTwelve.hasFingerprint = true;
refTwelve.hasFaceUnlock = true;
refTwelve.hasFastCharging = true;
refTwelve.hasWirelessCharging = false;
refTwelve.rearCameraMP = 50;
refTwelve.frontCameraMP = 50;
refTwelve.operatingSystem = "Android";
refTwelve.launchYear = 2023;
refTwelve.networkType = "5G";
refTwelve.dualSIM = true;
refTwelve.chargerType = "USB-C";
refTwelve.waterproof = false;
refTwelve.manufacturerCountry = "China";
refTwelve.ownerName = "Rohit";

System.out.println("The mobileId is: " + refTwelve.mobileId);
System.out.println("The brand is: " + refTwelve.brand);
System.out.println("The model is: " + refTwelve.model);
System.out.println("The color is: " + refTwelve.color);
System.out.println("The price is: " + refTwelve.price);
System.out.println("The storage is: " + refTwelve.storage);
System.out.println("The ram is: " + refTwelve.ram);
System.out.println("The processor is: " + refTwelve.processor);
System.out.println("The screenSize is: " + refTwelve.screenSize);
System.out.println("The batteryCapacity is: " + refTwelve.batteryCapacity);
System.out.println("The has5G is: " + refTwelve.has5G);
System.out.println("The hasFingerprint is: " + refTwelve.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refTwelve.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refTwelve.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refTwelve.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refTwelve.rearCameraMP);
System.out.println("The frontCameraMP is: " + refTwelve.frontCameraMP);
System.out.println("The operatingSystem is: " + refTwelve.operatingSystem);
System.out.println("The launchYear is: " + refTwelve.launchYear);
System.out.println("The networkType is: " + refTwelve.networkType);
System.out.println("The dualSIM is: " + refTwelve.dualSIM);
System.out.println("The chargerType is: " + refTwelve.chargerType);
System.out.println("The waterproof is: " + refTwelve.waterproof);
System.out.println("The manufacturerCountry is: " + refTwelve.manufacturerCountry);
System.out.println("The ownerName is: " + refTwelve.ownerName);
Mobile refThirteen = new Mobile();

System.out.println("The brand is: " + refThirteen.brand);
System.out.println("The model is: " + refThirteen.model);
System.out.println("The color is: " + refThirteen.color);
System.out.println("The price is: " + refThirteen.price);
System.out.println("The storage is: " + refThirteen.storage);
System.out.println("The ram is: " + refThirteen.ram);
System.out.println("The processor is: " + refThirteen.processor);
System.out.println("The screenSize is: " + refThirteen.screenSize);
System.out.println("The batteryCapacity is: " + refThirteen.batteryCapacity);
System.out.println("The has5G is: " + refThirteen.has5G);
System.out.println("The hasFingerprint is: " + refThirteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refThirteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refThirteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refThirteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refThirteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refThirteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refThirteen.operatingSystem);
System.out.println("The launchYear is: " + refThirteen.launchYear);
System.out.println("The networkType is: " + refThirteen.networkType);
System.out.println("The dualSIM is: " + refThirteen.dualSIM);
System.out.println("The chargerType is: " + refThirteen.chargerType);
System.out.println("The waterproof is: " + refThirteen.waterproof);
System.out.println("The manufacturerCountry is: " + refThirteen.manufacturerCountry);
System.out.println("The ownerName is: " + refThirteen.ownerName);

refThirteen.mobileId = 13;
refThirteen.brand = "Xiaomi";
refThirteen.model = "Redmi Note 12 Pro";
refThirteen.color = "Sky Blue";
refThirteen.price = 28000;
refThirteen.storage = 128;
refThirteen.ram = 8;
refThirteen.processor = "MediaTek Dimensity 1080";
refThirteen.screenSize = 6.67;
refThirteen.batteryCapacity = 5000;
refThirteen.has5G = true;
refThirteen.hasFingerprint = true;
refThirteen.hasFaceUnlock = true;
refThirteen.hasFastCharging = true;
refThirteen.hasWirelessCharging = false;
refThirteen.rearCameraMP = 50;
refThirteen.frontCameraMP = 16;
refThirteen.operatingSystem = "Android";
refThirteen.launchYear = 2023;
refThirteen.networkType = "5G";
refThirteen.dualSIM = true;
refThirteen.chargerType = "USB-C";
refThirteen.waterproof = false;
refThirteen.manufacturerCountry = "China";
refThirteen.ownerName = "Sandeep";

System.out.println("The mobileId is: " + refThirteen.mobileId);
System.out.println("The brand is: " + refThirteen.brand);
System.out.println("The model is: " + refThirteen.model);
System.out.println("The color is: " + refThirteen.color);
System.out.println("The price is: " + refThirteen.price);
System.out.println("The storage is: " + refThirteen.storage);
System.out.println("The ram is: " + refThirteen.ram);
System.out.println("The processor is: " + refThirteen.processor);
System.out.println("The screenSize is: " + refThirteen.screenSize);
System.out.println("The batteryCapacity is: " + refThirteen.batteryCapacity);
System.out.println("The has5G is: " + refThirteen.has5G);
System.out.println("The hasFingerprint is: " + refThirteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refThirteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refThirteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refThirteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refThirteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refThirteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refThirteen.operatingSystem);
System.out.println("The launchYear is: " + refThirteen.launchYear);
System.out.println("The networkType is: " + refThirteen.networkType);
System.out.println("The dualSIM is: " + refThirteen.dualSIM);
System.out.println("The chargerType is: " + refThirteen.chargerType);
System.out.println("The waterproof is: " + refThirteen.waterproof);
System.out.println("The manufacturerCountry is: " + refThirteen.manufacturerCountry);
System.out.println("The ownerName is: " + refThirteen.ownerName);
Mobile refFourteen = new Mobile();

System.out.println("The brand is: " + refFourteen.brand);
System.out.println("The model is: " + refFourteen.model);
System.out.println("The color is: " + refFourteen.color);
System.out.println("The price is: " + refFourteen.price);
System.out.println("The storage is: " + refFourteen.storage);
System.out.println("The ram is: " + refFourteen.ram);
System.out.println("The processor is: " + refFourteen.processor);
System.out.println("The screenSize is: " + refFourteen.screenSize);
System.out.println("The batteryCapacity is: " + refFourteen.batteryCapacity);
System.out.println("The has5G is: " + refFourteen.has5G);
System.out.println("The hasFingerprint is: " + refFourteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refFourteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refFourteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refFourteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refFourteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refFourteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refFourteen.operatingSystem);
System.out.println("The launchYear is: " + refFourteen.launchYear);
System.out.println("The networkType is: " + refFourteen.networkType);
System.out.println("The dualSIM is: " + refFourteen.dualSIM);
System.out.println("The chargerType is: " + refFourteen.chargerType);
System.out.println("The waterproof is: " + refFourteen.waterproof);
System.out.println("The manufacturerCountry is: " + refFourteen.manufacturerCountry);
System.out.println("The ownerName is: " + refFourteen.ownerName);

refFourteen.mobileId = 14;
refFourteen.brand = "Oppo";
refFourteen.model = "Oppo Reno 10";
refFourteen.color = "Silver";
refFourteen.price = 32000;
refFourteen.storage = 256;
refFourteen.ram = 12;
refFourteen.processor = "MediaTek Dimensity 7050";
refFourteen.screenSize = 6.7;
refFourteen.batteryCapacity = 4600;
refFourteen.has5G = true;
refFourteen.hasFingerprint = true;
refFourteen.hasFaceUnlock = true;
refFourteen.hasFastCharging = true;
refFourteen.hasWirelessCharging = false;
refFourteen.rearCameraMP = 64;
refFourteen.frontCameraMP = 32;
refFourteen.operatingSystem = "Android";
refFourteen.launchYear = 2023;
refFourteen.networkType = "5G";
refFourteen.dualSIM = true;
refFourteen.chargerType = "USB-C";
refFourteen.waterproof = false;
refFourteen.manufacturerCountry = "China";
refFourteen.ownerName = "Manoj";

System.out.println("The mobileId is: " + refFourteen.mobileId);
System.out.println("The brand is: " + refFourteen.brand);
System.out.println("The model is: " + refFourteen.model);
System.out.println("The color is: " + refFourteen.color);
System.out.println("The price is: " + refFourteen.price);
System.out.println("The storage is: " + refFourteen.storage);
System.out.println("The ram is: " + refFourteen.ram);
System.out.println("The processor is: " + refFourteen.processor);
System.out.println("The screenSize is: " + refFourteen.screenSize);
System.out.println("The batteryCapacity is: " + refFourteen.batteryCapacity);
System.out.println("The has5G is: " + refFourteen.has5G);
System.out.println("The hasFingerprint is: " + refFourteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refFourteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refFourteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refFourteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refFourteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refFourteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refFourteen.operatingSystem);
System.out.println("The launchYear is: " + refFourteen.launchYear);
System.out.println("The networkType is: " + refFourteen.networkType);
System.out.println("The dualSIM is: " + refFourteen.dualSIM);
System.out.println("The chargerType is: " + refFourteen.chargerType);
System.out.println("The waterproof is: " + refFourteen.waterproof);
System.out.println("The manufacturerCountry is: " + refFourteen.manufacturerCountry);
System.out.println("The ownerName is: " + refFourteen.ownerName);
Mobile refFifteen = new Mobile();

System.out.println("The brand is: " + refFifteen.brand);
System.out.println("The model is: " + refFifteen.model);
System.out.println("The color is: " + refFifteen.color);
System.out.println("The price is: " + refFifteen.price);
System.out.println("The storage is: " + refFifteen.storage);
System.out.println("The ram is: " + refFifteen.ram);
System.out.println("The processor is: " + refFifteen.processor);
System.out.println("The screenSize is: " + refFifteen.screenSize);
System.out.println("The batteryCapacity is: " + refFifteen.batteryCapacity);
System.out.println("The has5G is: " + refFifteen.has5G);
System.out.println("The hasFingerprint is: " + refFifteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refFifteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refFifteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refFifteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refFifteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refFifteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refFifteen.operatingSystem);
System.out.println("The launchYear is: " + refFifteen.launchYear);
System.out.println("The networkType is: " + refFifteen.networkType);
System.out.println("The dualSIM is: " + refFifteen.dualSIM);
System.out.println("The chargerType is: " + refFifteen.chargerType);
System.out.println("The waterproof is: " + refFifteen.waterproof);
System.out.println("The manufacturerCountry is: " + refFifteen.manufacturerCountry);
System.out.println("The ownerName is: " + refFifteen.ownerName);

refFifteen.mobileId = 15;
refFifteen.brand = "Google";
refFifteen.model = "Pixel 7";
refFifteen.color = "Obsidian";
refFifteen.price = 60000;
refFifteen.storage = 128;
refFifteen.ram = 8;
refFifteen.processor = "Google Tensor G2";
refFifteen.screenSize = 6.3;
refFifteen.batteryCapacity = 4355;
refFifteen.has5G = true;
refFifteen.hasFingerprint = true;
refFifteen.hasFaceUnlock = true;
refFifteen.hasFastCharging = true;
refFifteen.hasWirelessCharging = true;
refFifteen.rearCameraMP = 50;
refFifteen.frontCameraMP = 10;
refFifteen.operatingSystem = "Android";
refFifteen.launchYear = 2022;
refFifteen.networkType = "5G";
refFifteen.dualSIM = true;
refFifteen.chargerType = "USB-C";
refFifteen.waterproof = true;
refFifteen.manufacturerCountry = "USA";
refFifteen.ownerName = "Amit";

System.out.println("The mobileId is: " + refFifteen.mobileId);
System.out.println("The brand is: " + refFifteen.brand);
System.out.println("The model is: " + refFifteen.model);
System.out.println("The color is: " + refFifteen.color);
System.out.println("The price is: " + refFifteen.price);
System.out.println("The storage is: " + refFifteen.storage);
System.out.println("The ram is: " + refFifteen.ram);
System.out.println("The processor is: " + refFifteen.processor);
System.out.println("The screenSize is: " + refFifteen.screenSize);
System.out.println("The batteryCapacity is: " + refFifteen.batteryCapacity);
System.out.println("The has5G is: " + refFifteen.has5G);
System.out.println("The hasFingerprint is: " + refFifteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refFifteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refFifteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refFifteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refFifteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refFifteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refFifteen.operatingSystem);
System.out.println("The launchYear is: " + refFifteen.launchYear);
System.out.println("The networkType is: " + refFifteen.networkType);
System.out.println("The dualSIM is: " + refFifteen.dualSIM);
System.out.println("The chargerType is: " + refFifteen.chargerType);
System.out.println("The waterproof is: " + refFifteen.waterproof);
System.out.println("The manufacturerCountry is: " + refFifteen.manufacturerCountry);
System.out.println("The ownerName is: " + refFifteen.ownerName);
Mobile refSixteen = new Mobile();

System.out.println("The brand is: " + refSixteen.brand);
System.out.println("The model is: " + refSixteen.model);
System.out.println("The color is: " + refSixteen.color);
System.out.println("The price is: " + refSixteen.price);
System.out.println("The storage is: " + refSixteen.storage);
System.out.println("The ram is: " + refSixteen.ram);
System.out.println("The processor is: " + refSixteen.processor);
System.out.println("The screenSize is: " + refSixteen.screenSize);
System.out.println("The batteryCapacity is: " + refSixteen.batteryCapacity);
System.out.println("The has5G is: " + refSixteen.has5G);
System.out.println("The hasFingerprint is: " + refSixteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refSixteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refSixteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refSixteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refSixteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refSixteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refSixteen.operatingSystem);
System.out.println("The launchYear is: " + refSixteen.launchYear);
System.out.println("The networkType is: " + refSixteen.networkType);
System.out.println("The dualSIM is: " + refSixteen.dualSIM);
System.out.println("The chargerType is: " + refSixteen.chargerType);
System.out.println("The waterproof is: " + refSixteen.waterproof);
System.out.println("The manufacturerCountry is: " + refSixteen.manufacturerCountry);
System.out.println("The ownerName is: " + refSixteen.ownerName);

refSixteen.mobileId = 16;
refSixteen.brand = "Motorola";
refSixteen.model = "Moto Edge 40";
refSixteen.color = "Black";
refSixteen.price = 35000;
refSixteen.storage = 256;
refSixteen.ram = 8;
refSixteen.processor = "MediaTek Dimensity 8020";
refSixteen.screenSize = 6.55;
refSixteen.batteryCapacity = 4400;
refSixteen.has5G = true;
refSixteen.hasFingerprint = true;
refSixteen.hasFaceUnlock = true;
refSixteen.hasFastCharging = true;
refSixteen.hasWirelessCharging = true;
refSixteen.rearCameraMP = 50;
refSixteen.frontCameraMP = 32;
refSixteen.operatingSystem = "Android";
refSixteen.launchYear = 2023;
refSixteen.networkType = "5G";
refSixteen.dualSIM = true;
refSixteen.chargerType = "USB-C";
refSixteen.waterproof = true;
refSixteen.manufacturerCountry = "USA";
refSixteen.ownerName = "Rakesh";

System.out.println("The mobileId is: " + refSixteen.mobileId);
System.out.println("The brand is: " + refSixteen.brand);
System.out.println("The model is: " + refSixteen.model);
System.out.println("The color is: " + refSixteen.color);
System.out.println("The price is: " + refSixteen.price);
System.out.println("The storage is: " + refSixteen.storage);
System.out.println("The ram is: " + refSixteen.ram);
System.out.println("The processor is: " + refSixteen.processor);
System.out.println("The screenSize is: " + refSixteen.screenSize);
System.out.println("The batteryCapacity is: " + refSixteen.batteryCapacity);
System.out.println("The has5G is: " + refSixteen.has5G);
System.out.println("The hasFingerprint is: " + refSixteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refSixteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refSixteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refSixteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refSixteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refSixteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refSixteen.operatingSystem);
System.out.println("The launchYear is: " + refSixteen.launchYear);
System.out.println("The networkType is: " + refSixteen.networkType);
System.out.println("The dualSIM is: " + refSixteen.dualSIM);
System.out.println("The chargerType is: " + refSixteen.chargerType);
System.out.println("The waterproof is: " + refSixteen.waterproof);
System.out.println("The manufacturerCountry is: " + refSixteen.manufacturerCountry);
System.out.println("The ownerName is: " + refSixteen.ownerName);
Mobile refSeventeen = new Mobile();

System.out.println("The brand is: " + refSeventeen.brand);
System.out.println("The model is: " + refSeventeen.model);
System.out.println("The color is: " + refSeventeen.color);
System.out.println("The price is: " + refSeventeen.price);
System.out.println("The storage is: " + refSeventeen.storage);
System.out.println("The ram is: " + refSeventeen.ram);
System.out.println("The processor is: " + refSeventeen.processor);
System.out.println("The screenSize is: " + refSeventeen.screenSize);
System.out.println("The batteryCapacity is: " + refSeventeen.batteryCapacity);
System.out.println("The has5G is: " + refSeventeen.has5G);
System.out.println("The hasFingerprint is: " + refSeventeen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refSeventeen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refSeventeen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refSeventeen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refSeventeen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refSeventeen.frontCameraMP);
System.out.println("The operatingSystem is: " + refSeventeen.operatingSystem);
System.out.println("The launchYear is: " + refSeventeen.launchYear);
System.out.println("The networkType is: " + refSeventeen.networkType);
System.out.println("The dualSIM is: " + refSeventeen.dualSIM);
System.out.println("The chargerType is: " + refSeventeen.chargerType);
System.out.println("The waterproof is: " + refSeventeen.waterproof);
System.out.println("The manufacturerCountry is: " + refSeventeen.manufacturerCountry);
System.out.println("The ownerName is: " + refSeventeen.ownerName);

refSeventeen.mobileId = 17;
refSeventeen.brand = "Nokia";
refSeventeen.model = "Nokia X30";
refSeventeen.color = "Ice White";
refSeventeen.price = 30000;
refSeventeen.storage = 128;
refSeventeen.ram = 8;
refSeventeen.processor = "Snapdragon 695";
refSeventeen.screenSize = 6.43;
refSeventeen.batteryCapacity = 4200;
refSeventeen.has5G = true;
refSeventeen.hasFingerprint = true;
refSeventeen.hasFaceUnlock = true;
refSeventeen.hasFastCharging = true;
refSeventeen.hasWirelessCharging = false;
refSeventeen.rearCameraMP = 50;
refSeventeen.frontCameraMP = 16;
refSeventeen.operatingSystem = "Android";
refSeventeen.launchYear = 2023;
refSeventeen.networkType = "5G";
refSeventeen.dualSIM = true;
refSeventeen.chargerType = "USB-C";
refSeventeen.waterproof = true;
refSeventeen.manufacturerCountry = "Finland";
refSeventeen.ownerName = "Vikram";

System.out.println("The mobileId is: " + refSeventeen.mobileId);
System.out.println("The brand is: " + refSeventeen.brand);
System.out.println("The model is: " + refSeventeen.model);
System.out.println("The color is: " + refSeventeen.color);
System.out.println("The price is: " + refSeventeen.price);
System.out.println("The storage is: " + refSeventeen.storage);
System.out.println("The ram is: " + refSeventeen.ram);
System.out.println("The processor is: " + refSeventeen.processor);
System.out.println("The screenSize is: " + refSeventeen.screenSize);
System.out.println("The batteryCapacity is: " + refSeventeen.batteryCapacity);
System.out.println("The has5G is: " + refSeventeen.has5G);
System.out.println("The hasFingerprint is: " + refSeventeen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refSeventeen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refSeventeen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refSeventeen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refSeventeen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refSeventeen.frontCameraMP);
System.out.println("The operatingSystem is: " + refSeventeen.operatingSystem);
System.out.println("The launchYear is: " + refSeventeen.launchYear);
System.out.println("The networkType is: " + refSeventeen.networkType);
System.out.println("The dualSIM is: " + refSeventeen.dualSIM);
System.out.println("The chargerType is: " + refSeventeen.chargerType);
System.out.println("The waterproof is: " + refSeventeen.waterproof);
System.out.println("The manufacturerCountry is: " + refSeventeen.manufacturerCountry);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
Mobile refEighteen = new Mobile();

System.out.println("The brand is: " + refEighteen.brand);
System.out.println("The model is: " + refEighteen.model);
System.out.println("The color is: " + refEighteen.color);
System.out.println("The price is: " + refEighteen.price);
System.out.println("The storage is: " + refEighteen.storage);
System.out.println("The ram is: " + refEighteen.ram);
System.out.println("The processor is: " + refEighteen.processor);
System.out.println("The screenSize is: " + refEighteen.screenSize);
System.out.println("The batteryCapacity is: " + refEighteen.batteryCapacity);
System.out.println("The has5G is: " + refEighteen.has5G);
System.out.println("The hasFingerprint is: " + refEighteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refEighteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refEighteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refEighteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refEighteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refEighteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refEighteen.operatingSystem);
System.out.println("The launchYear is: " + refEighteen.launchYear);
System.out.println("The networkType is: " + refEighteen.networkType);
System.out.println("The dualSIM is: " + refEighteen.dualSIM);
System.out.println("The chargerType is: " + refEighteen.chargerType);
System.out.println("The waterproof is: " + refEighteen.waterproof);
System.out.println("The manufacturerCountry is: " + refEighteen.manufacturerCountry);
System.out.println("The ownerName is: " + refEighteen.ownerName);

refEighteen.mobileId = 18;
refEighteen.brand = "Asus";
refEighteen.model = "ROG Phone 7";
refEighteen.color = "Phantom Black";
refEighteen.price = 75000;
refEighteen.storage = 512;
refEighteen.ram = 16;
refEighteen.processor = "Snapdragon 8 Gen 2";
refEighteen.screenSize = 6.78;
refEighteen.batteryCapacity = 6000;
refEighteen.has5G = true;
refEighteen.hasFingerprint = true;
refEighteen.hasFaceUnlock = true;
refEighteen.hasFastCharging = true;
refEighteen.hasWirelessCharging = false;
refEighteen.rearCameraMP = 50;
refEighteen.frontCameraMP = 32;
refEighteen.operatingSystem = "Android";
refEighteen.launchYear = 2023;
refEighteen.networkType = "5G";
refEighteen.dualSIM = true;
refEighteen.chargerType = "USB-C";
refEighteen.waterproof = false;
refEighteen.manufacturerCountry = "Taiwan";
refEighteen.ownerName = "Naveen";

System.out.println("The mobileId is: " + refEighteen.mobileId);
System.out.println("The brand is: " + refEighteen.brand);
System.out.println("The model is: " + refEighteen.model);
System.out.println("The color is: " + refEighteen.color);
System.out.println("The price is: " + refEighteen.price);
System.out.println("The storage is: " + refEighteen.storage);
System.out.println("The ram is: " + refEighteen.ram);
System.out.println("The processor is: " + refEighteen.processor);
System.out.println("The screenSize is: " + refEighteen.screenSize);
System.out.println("The batteryCapacity is: " + refEighteen.batteryCapacity);
System.out.println("The has5G is: " + refEighteen.has5G);
System.out.println("The hasFingerprint is: " + refEighteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refEighteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refEighteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refEighteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refEighteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refEighteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refEighteen.operatingSystem);
System.out.println("The launchYear is: " + refEighteen.launchYear);
System.out.println("The networkType is: " + refEighteen.networkType);
System.out.println("The dualSIM is: " + refEighteen.dualSIM);
System.out.println("The chargerType is: " + refEighteen.chargerType);
System.out.println("The waterproof is: " + refEighteen.waterproof);
System.out.println("The manufacturerCountry is: " + refEighteen.manufacturerCountry);
System.out.println("The ownerName is: " + refEighteen.ownerName);
Mobile refNineteen = new Mobile();

System.out.println("The brand is: " + refNineteen.brand);
System.out.println("The model is: " + refNineteen.model);
System.out.println("The color is: " + refNineteen.color);
System.out.println("The price is: " + refNineteen.price);
System.out.println("The storage is: " + refNineteen.storage);
System.out.println("The ram is: " + refNineteen.ram);
System.out.println("The processor is: " + refNineteen.processor);
System.out.println("The screenSize is: " + refNineteen.screenSize);
System.out.println("The batteryCapacity is: " + refNineteen.batteryCapacity);
System.out.println("The has5G is: " + refNineteen.has5G);
System.out.println("The hasFingerprint is: " + refNineteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refNineteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refNineteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refNineteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refNineteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refNineteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refNineteen.operatingSystem);
System.out.println("The launchYear is: " + refNineteen.launchYear);
System.out.println("The networkType is: " + refNineteen.networkType);
System.out.println("The dualSIM is: " + refNineteen.dualSIM);
System.out.println("The chargerType is: " + refNineteen.chargerType);
System.out.println("The waterproof is: " + refNineteen.waterproof);
System.out.println("The manufacturerCountry is: " + refNineteen.manufacturerCountry);
System.out.println("The ownerName is: " + refNineteen.ownerName);

refNineteen.mobileId = 19;
refNineteen.brand = "Sony";
refNineteen.model = "Xperia 1 V";
refNineteen.color = "Black";
refNineteen.price = 90000;
refNineteen.storage = 256;
refNineteen.ram = 12;
refNineteen.processor = "Snapdragon 8 Gen 2";
refNineteen.screenSize = 6.5;
refNineteen.batteryCapacity = 5000;
refNineteen.has5G = true;
refNineteen.hasFingerprint = true;
refNineteen.hasFaceUnlock = false;
refNineteen.hasFastCharging = true;
refNineteen.hasWirelessCharging = true;
refNineteen.rearCameraMP = 48;
refNineteen.frontCameraMP = 12;
refNineteen.operatingSystem = "Android";
refNineteen.launchYear = 2023;
refNineteen.networkType = "5G";
refNineteen.dualSIM = true;
refNineteen.chargerType = "USB-C";
refNineteen.waterproof = true;
refNineteen.manufacturerCountry = "Japan";
refNineteen.ownerName = "Harish";

System.out.println("The mobileId is: " + refNineteen.mobileId);
System.out.println("The brand is: " + refNineteen.brand);
System.out.println("The model is: " + refNineteen.model);
System.out.println("The color is: " + refNineteen.color);
System.out.println("The price is: " + refNineteen.price);
System.out.println("The storage is: " + refNineteen.storage);
System.out.println("The ram is: " + refNineteen.ram);
System.out.println("The processor is: " + refNineteen.processor);
System.out.println("The screenSize is: " + refNineteen.screenSize);
System.out.println("The batteryCapacity is: " + refNineteen.batteryCapacity);
System.out.println("The has5G is: " + refNineteen.has5G);
System.out.println("The hasFingerprint is: " + refNineteen.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refNineteen.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refNineteen.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refNineteen.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refNineteen.rearCameraMP);
System.out.println("The frontCameraMP is: " + refNineteen.frontCameraMP);
System.out.println("The operatingSystem is: " + refNineteen.operatingSystem);
System.out.println("The launchYear is: " + refNineteen.launchYear);
System.out.println("The networkType is: " + refNineteen.networkType);
System.out.println("The dualSIM is: " + refNineteen.dualSIM);
System.out.println("The chargerType is: " + refNineteen.chargerType);
System.out.println("The waterproof is: " + refNineteen.waterproof);
System.out.println("The manufacturerCountry is: " + refNineteen.manufacturerCountry);
System.out.println("The ownerName is: " + refNineteen.ownerName);
Mobile refTwenty = new Mobile();

System.out.println("The brand is: " + refTwenty.brand);
System.out.println("The model is: " + refTwenty.model);
System.out.println("The color is: " + refTwenty.color);
System.out.println("The price is: " + refTwenty.price);
System.out.println("The storage is: " + refTwenty.storage);
System.out.println("The ram is: " + refTwenty.ram);
System.out.println("The processor is: " + refTwenty.processor);
System.out.println("The screenSize is: " + refTwenty.screenSize);
System.out.println("The batteryCapacity is: " + refTwenty.batteryCapacity);
System.out.println("The has5G is: " + refTwenty.has5G);
System.out.println("The hasFingerprint is: " + refTwenty.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refTwenty.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refTwenty.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refTwenty.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refTwenty.rearCameraMP);
System.out.println("The frontCameraMP is: " + refTwenty.frontCameraMP);
System.out.println("The operatingSystem is: " + refTwenty.operatingSystem);
System.out.println("The launchYear is: " + refTwenty.launchYear);
System.out.println("The networkType is: " + refTwenty.networkType);
System.out.println("The dualSIM is: " + refTwenty.dualSIM);
System.out.println("The chargerType is: " + refTwenty.chargerType);
System.out.println("The waterproof is: " + refTwenty.waterproof);
System.out.println("The manufacturerCountry is: " + refTwenty.manufacturerCountry);
System.out.println("The ownerName is: " + refTwenty.ownerName);

refTwenty.mobileId = 20;
refTwenty.brand = "Honor";
refTwenty.model = "Honor Magic5";
refTwenty.color = "Emerald Green";
refTwenty.price = 68000;
refTwenty.storage = 256;
refTwenty.ram = 12;
refTwenty.processor = "Snapdragon 8 Gen 2";
refTwenty.screenSize = 6.73;
refTwenty.batteryCapacity = 5100;
refTwenty.has5G = true;
refTwenty.hasFingerprint = true;
refTwenty.hasFaceUnlock = true;
refTwenty.hasFastCharging = true;
refTwenty.hasWirelessCharging = true;
refTwenty.rearCameraMP = 54;
refTwenty.frontCameraMP = 12;
refTwenty.operatingSystem = "Android";
refTwenty.launchYear = 2023;
refTwenty.networkType = "5G";
refTwenty.dualSIM = true;
refTwenty.chargerType = "USB-C";
refTwenty.waterproof = true;
refTwenty.manufacturerCountry = "China";
refTwenty.ownerName = "Karthik";

System.out.println("The mobileId is: " + refTwenty.mobileId);
System.out.println("The brand is: " + refTwenty.brand);
System.out.println("The model is: " + refTwenty.model);
System.out.println("The color is: " + refTwenty.color);
System.out.println("The price is: " + refTwenty.price);
System.out.println("The storage is: " + refTwenty.storage);
System.out.println("The ram is: " + refTwenty.ram);
System.out.println("The processor is: " + refTwenty.processor);
System.out.println("The screenSize is: " + refTwenty.screenSize);
System.out.println("The batteryCapacity is: " + refTwenty.batteryCapacity);
System.out.println("The has5G is: " + refTwenty.has5G);
System.out.println("The hasFingerprint is: " + refTwenty.hasFingerprint);
System.out.println("The hasFaceUnlock is: " + refTwenty.hasFaceUnlock);
System.out.println("The hasFastCharging is: " + refTwenty.hasFastCharging);
System.out.println("The hasWirelessCharging is: " + refTwenty.hasWirelessCharging);
System.out.println("The rearCameraMP is: " + refTwenty.rearCameraMP);
System.out.println("The frontCameraMP is: " + refTwenty.frontCameraMP);
System.out.println("The operatingSystem is: " + refTwenty.operatingSystem);
System.out.println("The launchYear is: " + refTwenty.launchYear);
System.out.println("The networkType is: " + refTwenty.networkType);
System.out.println("The dualSIM is: " + refTwenty.dualSIM);
System.out.println("The chargerType is: " + refTwenty.chargerType);
System.out.println("The waterproof is: " + refTwenty.waterproof);
System.out.println("The manufacturerCountry is: " + refTwenty.manufacturerCountry);
System.out.println("The ownerName is: " + refTwenty.ownerName);
}
}