class MovieExecutor{
public static void main(String[] args){
Movie refOne = new Movie();

System.out.println("The movieId is: " + refOne.movieId);
System.out.println("The title is: " + refOne.title);
System.out.println("The director is: " + refOne.director);
System.out.println("The producer is: " + refOne.producer);
System.out.println("The productionCompany is: " + refOne.productionCompany);
System.out.println("The releaseYear is: " + refOne.releaseYear);
System.out.println("The language is: " + refOne.language);
System.out.println("The genre is: " + refOne.genre);
System.out.println("The duration is: " + refOne.duration);
System.out.println("The budget is: " + refOne.budget);
System.out.println("The boxOfficeCollection is: " + refOne.boxOfficeCollection);
System.out.println("The leadActor is: " + refOne.leadActor);
System.out.println("The leadActress is: " + refOne.leadActress);
System.out.println("The supportingActor is: " + refOne.supportingActor);
System.out.println("The supportingActress is: " + refOne.supportingActress);
System.out.println("The musicDirector is: " + refOne.musicDirector);
System.out.println("The cinematographer is: " + refOne.cinematographer);
System.out.println("The editor is: " + refOne.editor);
System.out.println("The distributor is: " + refOne.distributor);
System.out.println("The hasSequel is: " + refOne.hasSequel);
System.out.println("The hasPrequel is: " + refOne.hasPrequel);
System.out.println("The wonAwards is: " + refOne.wonAwards);
System.out.println("The rating is: " + refOne.rating);
System.out.println("The countryOfOrigin is: " + refOne.countryOfOrigin);
System.out.println("The audienceType is: " + refOne.audienceType);

refOne.movieId = 1;
refOne.title = "Master";
refOne.director = "Lokesh Kanagaraj";
refOne.producer = "Xavier Britto";
refOne.productionCompany = "XB Film Creators";
refOne.releaseYear = 2021;
refOne.language = "Tamil";
refOne.genre = "Action Thriller";
refOne.duration = 2.58;
refOne.budget = 135.0;
refOne.boxOfficeCollection = 300.0;
refOne.leadActor = "Vijay";
refOne.leadActress = "Malavika Mohanan";
refOne.supportingActor = "Vijay Sethupathi";
refOne.supportingActress = "Andrea Jeremiah";
refOne.musicDirector = "Anirudh Ravichander";
refOne.cinematographer = "Sathyan Sooryan";
refOne.editor = "Philomin Raj";
refOne.distributor = "Seven Screen Studio";
refOne.hasSequel = false;
refOne.hasPrequel = false;
refOne.wonAwards = true;
refOne.rating = "4.5/5";
refOne.countryOfOrigin = "India";
refOne.audienceType = "U/A";

System.out.println("The movieId is: " + refOne.movieId);
System.out.println("The title is: " + refOne.title);
System.out.println("The director is: " + refOne.director);
System.out.println("The producer is: " + refOne.producer);
System.out.println("The productionCompany is: " + refOne.productionCompany);
System.out.println("The releaseYear is: " + refOne.releaseYear);
System.out.println("The language is: " + refOne.language);
System.out.println("The genre is: " + refOne.genre);
System.out.println("The duration is: " + refOne.duration);
System.out.println("The budget is: " + refOne.budget);
System.out.println("The boxOfficeCollection is: " + refOne.boxOfficeCollection);
System.out.println("The leadActor is: " + refOne.leadActor);
System.out.println("The leadActress is: " + refOne.leadActress);
System.out.println("The supportingActor is: " + refOne.supportingActor);
System.out.println("The supportingActress is: " + refOne.supportingActress);
System.out.println("The musicDirector is: " + refOne.musicDirector);
System.out.println("The cinematographer is: " + refOne.cinematographer);
System.out.println("The editor is: " + refOne.editor);
System.out.println("The distributor is: " + refOne.distributor);
System.out.println("The hasSequel is: " + refOne.hasSequel);
System.out.println("The hasPrequel is: " + refOne.hasPrequel);
System.out.println("The wonAwards is: " + refOne.wonAwards);
System.out.println("The rating is: " + refOne.rating);
System.out.println("The countryOfOrigin is: " + refOne.countryOfOrigin);
System.out.println("The audienceType is: " + refOne.audienceType);
Movie refTwo = new Movie();

System.out.println("The movieId is: " + refTwo.movieId);
System.out.println("The title is: " + refTwo.title);
System.out.println("The director is: " + refTwo.director);
System.out.println("The producer is: " + refTwo.producer);
System.out.println("The productionCompany is: " + refTwo.productionCompany);
System.out.println("The releaseYear is: " + refTwo.releaseYear);
System.out.println("The language is: " + refTwo.language);
System.out.println("The genre is: " + refTwo.genre);
System.out.println("The duration is: " + refTwo.duration);
System.out.println("The budget is: " + refTwo.budget);
System.out.println("The boxOfficeCollection is: " + refTwo.boxOfficeCollection);
System.out.println("The leadActor is: " + refTwo.leadActor);
System.out.println("The leadActress is: " + refTwo.leadActress);
System.out.println("The supportingActor is: " + refTwo.supportingActor);
System.out.println("The supportingActress is: " + refTwo.supportingActress);
System.out.println("The musicDirector is: " + refTwo.musicDirector);
System.out.println("The cinematographer is: " + refTwo.cinematographer);
System.out.println("The editor is: " + refTwo.editor);
System.out.println("The distributor is: " + refTwo.distributor);
System.out.println("The hasSequel is: " + refTwo.hasSequel);
System.out.println("The hasPrequel is: " + refTwo.hasPrequel);
System.out.println("The wonAwards is: " + refTwo.wonAwards);
System.out.println("The rating is: " + refTwo.rating);
System.out.println("The countryOfOrigin is: " + refTwo.countryOfOrigin);
System.out.println("The audienceType is: " + refTwo.audienceType);

refTwo.movieId = 2;
refTwo.title = "Baahubali: The Beginning";
refTwo.director = "S. S. Rajamouli";
refTwo.producer = "Shobu Yarlagadda";
refTwo.productionCompany = "Arka Media Works";
refTwo.releaseYear = 2015;
refTwo.language = "Telugu";
refTwo.genre = "Epic Action";
refTwo.duration = 2.39;
refTwo.budget = 180.0;
refTwo.boxOfficeCollection = 650.0;
refTwo.leadActor = "Prabhas";
refTwo.leadActress = "Tamannaah";
refTwo.supportingActor = "Rana Daggubati";
refTwo.supportingActress = "Anushka Shetty";
refTwo.musicDirector = "M. M. Keeravani";
refTwo.cinematographer = "K. K. Senthil Kumar";
refTwo.editor = "Kotagiri Venkateswara Rao";
refTwo.distributor = "Dharma Productions";
refTwo.hasSequel = true;
refTwo.hasPrequel = false;
refTwo.wonAwards = true;
refTwo.rating = "4.7/5";
refTwo.countryOfOrigin = "India";
refTwo.audienceType = "U/A";

System.out.println("The movieId is: " + refTwo.movieId);
System.out.println("The title is: " + refTwo.title);
System.out.println("The director is: " + refTwo.director);
System.out.println("The producer is: " + refTwo.producer);
System.out.println("The productionCompany is: " + refTwo.productionCompany);
System.out.println("The releaseYear is: " + refTwo.releaseYear);
System.out.println("The language is: " + refTwo.language);
System.out.println("The genre is: " + refTwo.genre);
System.out.println("The duration is: " + refTwo.duration);
System.out.println("The budget is: " + refTwo.budget);
System.out.println("The boxOfficeCollection is: " + refTwo.boxOfficeCollection);
System.out.println("The leadActor is: " + refTwo.leadActor);
System.out.println("The leadActress is: " + refTwo.leadActress);
System.out.println("The supportingActor is: " + refTwo.supportingActor);
System.out.println("The supportingActress is: " + refTwo.supportingActress);
System.out.println("The musicDirector is: " + refTwo.musicDirector);
System.out.println("The cinematographer is: " + refTwo.cinematographer);
System.out.println("The editor is: " + refTwo.editor);
System.out.println("The distributor is: " + refTwo.distributor);
System.out.println("The hasSequel is: " + refTwo.hasSequel);
System.out.println("The hasPrequel is: " + refTwo.hasPrequel);
System.out.println("The wonAwards is: " + refTwo.wonAwards);
System.out.println("The rating is: " + refTwo.rating);
System.out.println("The countryOfOrigin is: " + refTwo.countryOfOrigin);
System.out.println("The audienceType is: " + refTwo.audienceType);
Movie refThree = new Movie();

System.out.println("The movieId is: " + refThree.movieId);
System.out.println("The title is: " + refThree.title);
System.out.println("The director is: " + refThree.director);
System.out.println("The producer is: " + refThree.producer);
System.out.println("The productionCompany is: " + refThree.productionCompany);
System.out.println("The releaseYear is: " + refThree.releaseYear);
System.out.println("The language is: " + refThree.language);
System.out.println("The genre is: " + refThree.genre);
System.out.println("The duration is: " + refThree.duration);
System.out.println("The budget is: " + refThree.budget);
System.out.println("The boxOfficeCollection is: " + refThree.boxOfficeCollection);
System.out.println("The leadActor is: " + refThree.leadActor);
System.out.println("The leadActress is: " + refThree.leadActress);
System.out.println("The supportingActor is: " + refThree.supportingActor);
System.out.println("The supportingActress is: " + refThree.supportingActress);
System.out.println("The musicDirector is: " + refThree.musicDirector);
System.out.println("The cinematographer is: " + refThree.cinematographer);
System.out.println("The editor is: " + refThree.editor);
System.out.println("The distributor is: " + refThree.distributor);
System.out.println("The hasSequel is: " + refThree.hasSequel);
System.out.println("The hasPrequel is: " + refThree.hasPrequel);
System.out.println("The wonAwards is: " + refThree.wonAwards);
System.out.println("The rating is: " + refThree.rating);
System.out.println("The countryOfOrigin is: " + refThree.countryOfOrigin);
System.out.println("The audienceType is: " + refThree.audienceType);

refThree.movieId = 3;
refThree.title = "KGF Chapter 1";
refThree.director = "Prashanth Neel";
refThree.producer = "Vijay Kiragandur";
refThree.productionCompany = "Hombale Films";
refThree.releaseYear = 2018;
refThree.language = "Kannada";
refThree.genre = "Action";
refThree.duration = 2.35;
refThree.budget = 80.0;
refThree.boxOfficeCollection = 250.0;
refThree.leadActor = "Yash";
refThree.leadActress = "Srinidhi Shetty";
refThree.supportingActor = "Anant Nag";
refThree.supportingActress = "Archana Jois";
refThree.musicDirector = "Ravi Basrur";
refThree.cinematographer = "Bhuvan Gowda";
refThree.editor = "Srikanth";
refThree.distributor = "Excel Entertainment";
refThree.hasSequel = true;
refThree.hasPrequel = false;
refThree.wonAwards = true;
refThree.rating = "4.6/5";
refThree.countryOfOrigin = "India";
refThree.audienceType = "U/A";

System.out.println("The movieId is: " + refThree.movieId);
System.out.println("The title is: " + refThree.title);
System.out.println("The director is: " + refThree.director);
System.out.println("The producer is: " + refThree.producer);
System.out.println("The productionCompany is: " + refThree.productionCompany);
System.out.println("The releaseYear is: " + refThree.releaseYear);
System.out.println("The language is: " + refThree.language);
System.out.println("The genre is: " + refThree.genre);
System.out.println("The duration is: " + refThree.duration);
System.out.println("The budget is: " + refThree.budget);
System.out.println("The boxOfficeCollection is: " + refThree.boxOfficeCollection);
System.out.println("The leadActor is: " + refThree.leadActor);
System.out.println("The leadActress is: " + refThree.leadActress);
System.out.println("The supportingActor is: " + refThree.supportingActor);
System.out.println("The supportingActress is: " + refThree.supportingActress);
System.out.println("The musicDirector is: " + refThree.musicDirector);
System.out.println("The cinematographer is: " + refThree.cinematographer);
System.out.println("The editor is: " + refThree.editor);
System.out.println("The distributor is: " + refThree.distributor);
System.out.println("The hasSequel is: " + refThree.hasSequel);
System.out.println("The hasPrequel is: " + refThree.hasPrequel);
System.out.println("The wonAwards is: " + refThree.wonAwards);
System.out.println("The rating is: " + refThree.rating);
System.out.println("The countryOfOrigin is: " + refThree.countryOfOrigin);
System.out.println("The audienceType is: " + refThree.audienceType);
Movie refFour = new Movie();

System.out.println("The movieId is: " + refFour.movieId);
System.out.println("The title is: " + refFour.title);
System.out.println("The director is: " + refFour.director);
System.out.println("The producer is: " + refFour.producer);
System.out.println("The productionCompany is: " + refFour.productionCompany);
System.out.println("The releaseYear is: " + refFour.releaseYear);
System.out.println("The language is: " + refFour.language);
System.out.println("The genre is: " + refFour.genre);
System.out.println("The duration is: " + refFour.duration);
System.out.println("The budget is: " + refFour.budget);
System.out.println("The boxOfficeCollection is: " + refFour.boxOfficeCollection);
System.out.println("The leadActor is: " + refFour.leadActor);
System.out.println("The leadActress is: " + refFour.leadActress);
System.out.println("The supportingActor is: " + refFour.supportingActor);
System.out.println("The supportingActress is: " + refFour.supportingActress);
System.out.println("The musicDirector is: " + refFour.musicDirector);
System.out.println("The cinematographer is: " + refFour.cinematographer);
System.out.println("The editor is: " + refFour.editor);
System.out.println("The distributor is: " + refFour.distributor);
System.out.println("The hasSequel is: " + refFour.hasSequel);
System.out.println("The hasPrequel is: " + refFour.hasPrequel);
System.out.println("The wonAwards is: " + refFour.wonAwards);
System.out.println("The rating is: " + refFour.rating);
System.out.println("The countryOfOrigin is: " + refFour.countryOfOrigin);
System.out.println("The audienceType is: " + refFour.audienceType);

refFour.movieId = 4;
refFour.title = "RRR";
refFour.director = "S. S. Rajamouli";
refFour.producer = "D. V. V. Danayya";
refFour.productionCompany = "DVV Entertainment";
refFour.releaseYear = 2022;
refFour.language = "Telugu";
refFour.genre = "Action Drama";
refFour.duration = 3.07;
refFour.budget = 550.0;
refFour.boxOfficeCollection = 1200.0;
refFour.leadActor = "N. T. Rama Rao Jr.";
refFour.leadActress = "Alia Bhatt";
refFour.supportingActor = "Ram Charan";
refFour.supportingActress = "Olivia Morris";
refFour.musicDirector = "M. M. Keeravani";
refFour.cinematographer = "K. K. Senthil Kumar";
refFour.editor = "A. Sreekar Prasad";
refFour.distributor = "Pen Studios";
refFour.hasSequel = false;
refFour.hasPrequel = false;
refFour.wonAwards = true;
refFour.rating = "4.8/5";
refFour.countryOfOrigin = "India";
refFour.audienceType = "U/A";

System.out.println("The movieId is: " + refFour.movieId);
System.out.println("The title is: " + refFour.title);
System.out.println("The director is: " + refFour.director);
System.out.println("The producer is: " + refFour.producer);
System.out.println("The productionCompany is: " + refFour.productionCompany);
System.out.println("The releaseYear is: " + refFour.releaseYear);
System.out.println("The language is: " + refFour.language);
System.out.println("The genre is: " + refFour.genre);
System.out.println("The duration is: " + refFour.duration);
System.out.println("The budget is: " + refFour.budget);
System.out.println("The boxOfficeCollection is: " + refFour.boxOfficeCollection);
System.out.println("The leadActor is: " + refFour.leadActor);
System.out.println("The leadActress is: " + refFour.leadActress);
System.out.println("The supportingActor is: " + refFour.supportingActor);
System.out.println("The supportingActress is: " + refFour.supportingActress);
System.out.println("The musicDirector is: " + refFour.musicDirector);
System.out.println("The cinematographer is: " + refFour.cinematographer);
System.out.println("The editor is: " + refFour.editor);
System.out.println("The distributor is: " + refFour.distributor);
System.out.println("The hasSequel is: " + refFour.hasSequel);
System.out.println("The hasPrequel is: " + refFour.hasPrequel);
System.out.println("The wonAwards is: " + refFour.wonAwards);
System.out.println("The rating is: " + refFour.rating);
System.out.println("The countryOfOrigin is: " + refFour.countryOfOrigin);
System.out.println("The audienceType is: " + refFour.audienceType);
Movie refFive = new Movie();

System.out.println("The movieId is: " + refFive.movieId);
System.out.println("The title is: " + refFive.title);
System.out.println("The director is: " + refFive.director);
System.out.println("The producer is: " + refFive.producer);
System.out.println("The productionCompany is: " + refFive.productionCompany);
System.out.println("The releaseYear is: " + refFive.releaseYear);
System.out.println("The language is: " + refFive.language);
System.out.println("The genre is: " + refFive.genre);
System.out.println("The duration is: " + refFive.duration);
System.out.println("The budget is: " + refFive.budget);
System.out.println("The boxOfficeCollection is: " + refFive.boxOfficeCollection);
System.out.println("The leadActor is: " + refFive.leadActor);
System.out.println("The leadActress is: " + refFive.leadActress);
System.out.println("The supportingActor is: " + refFive.supportingActor);
System.out.println("The supportingActress is: " + refFive.supportingActress);
System.out.println("The musicDirector is: " + refFive.musicDirector);
System.out.println("The cinematographer is: " + refFive.cinematographer);
System.out.println("The editor is: " + refFive.editor);
System.out.println("The distributor is: " + refFive.distributor);
System.out.println("The hasSequel is: " + refFive.hasSequel);
System.out.println("The hasPrequel is: " + refFive.hasPrequel);
System.out.println("The wonAwards is: " + refFive.wonAwards);
System.out.println("The rating is: " + refFive.rating);
System.out.println("The countryOfOrigin is: " + refFive.countryOfOrigin);
System.out.println("The audienceType is: " + refFive.audienceType);

refFive.movieId = 5;
refFive.title = "Pushpa: The Rise";
refFive.director = "Sukumar";
refFive.producer = "Naveen Yerneni";
refFive.productionCompany = "Mythri Movie Makers";
refFive.releaseYear = 2021;
refFive.language = "Telugu";
refFive.genre = "Action Drama";
refFive.duration = 2.59;
refFive.budget = 200.0;
refFive.boxOfficeCollection = 350.0;
refFive.leadActor = "Allu Arjun";
refFive.leadActress = "Rashmika Mandanna";
refFive.supportingActor = "Fahadh Faasil";
refFive.supportingActress = "Anasuya Bharadwaj";
refFive.musicDirector = "Devi Sri Prasad";
refFive.cinematographer = "Miroslaw Kuba Brozek";
refFive.editor = "Karthika Srinivas";
refFive.distributor = "AA Films";
refFive.hasSequel = true;
refFive.hasPrequel = false;
refFive.wonAwards = true;
refFive.rating = "4.4/5";
refFive.countryOfOrigin = "India";
refFive.audienceType = "U/A";

System.out.println("The movieId is: " + refFive.movieId);
System.out.println("The title is: " + refFive.title);
System.out.println("The director is: " + refFive.director);
System.out.println("The producer is: " + refFive.producer);
System.out.println("The productionCompany is: " + refFive.productionCompany);
System.out.println("The releaseYear is: " + refFive.releaseYear);
System.out.println("The language is: " + refFive.language);
System.out.println("The genre is: " + refFive.genre);
System.out.println("The duration is: " + refFive.duration);
System.out.println("The budget is: " + refFive.budget);
System.out.println("The boxOfficeCollection is: " + refFive.boxOfficeCollection);
System.out.println("The leadActor is: " + refFive.leadActor);
System.out.println("The leadActress is: " + refFive.leadActress);
System.out.println("The supportingActor is: " + refFive.supportingActor);
System.out.println("The supportingActress is: " + refFive.supportingActress);
System.out.println("The musicDirector is: " + refFive.musicDirector);
System.out.println("The cinematographer is: " + refFive.cinematographer);
System.out.println("The editor is: " + refFive.editor);
System.out.println("The distributor is: " + refFive.distributor);
System.out.println("The hasSequel is: " + refFive.hasSequel);
System.out.println("The hasPrequel is: " + refFive.hasPrequel);
System.out.println("The wonAwards is: " + refFive.wonAwards);
System.out.println("The rating is: " + refFive.rating);
System.out.println("The countryOfOrigin is: " + refFive.countryOfOrigin);
System.out.println("The audienceType is: " + refFive.audienceType);
Movie refSix = new Movie();

System.out.println("The movieId is: " + refSix.movieId);
System.out.println("The title is: " + refSix.title);
System.out.println("The director is: " + refSix.director);
System.out.println("The producer is: " + refSix.producer);
System.out.println("The productionCompany is: " + refSix.productionCompany);
System.out.println("The releaseYear is: " + refSix.releaseYear);
System.out.println("The language is: " + refSix.language);
System.out.println("The genre is: " + refSix.genre);
System.out.println("The duration is: " + refSix.duration);
System.out.println("The budget is: " + refSix.budget);
System.out.println("The boxOfficeCollection is: " + refSix.boxOfficeCollection);
System.out.println("The leadActor is: " + refSix.leadActor);
System.out.println("The leadActress is: " + refSix.leadActress);
System.out.println("The supportingActor is: " + refSix.supportingActor);
System.out.println("The supportingActress is: " + refSix.supportingActress);
System.out.println("The musicDirector is: " + refSix.musicDirector);
System.out.println("The cinematographer is: " + refSix.cinematographer);
System.out.println("The editor is: " + refSix.editor);
System.out.println("The distributor is: " + refSix.distributor);
System.out.println("The hasSequel is: " + refSix.hasSequel);
System.out.println("The hasPrequel is: " + refSix.hasPrequel);
System.out.println("The wonAwards is: " + refSix.wonAwards);
System.out.println("The rating is: " + refSix.rating);
System.out.println("The countryOfOrigin is: " + refSix.countryOfOrigin);
System.out.println("The audienceType is: " + refSix.audienceType);

refSix.movieId = 6;
refSix.title = "Leo";
refSix.director = "Lokesh Kanagaraj";
refSix.producer = "S. S. Lalit Kumar";
refSix.productionCompany = "Seven Screen Studio";
refSix.releaseYear = 2023;
refSix.language = "Tamil";
refSix.genre = "Action Thriller";
refSix.duration = 2.44;
refSix.budget = 250.0;
refSix.boxOfficeCollection = 620.0;
refSix.leadActor = "Vijay";
refSix.leadActress = "Trisha Krishnan";
refSix.supportingActor = "Sanjay Dutt";
refSix.supportingActress = "Madonna Sebastian";
refSix.musicDirector = "Anirudh Ravichander";
refSix.cinematographer = "Manoj Paramahamsa";
refSix.editor = "Philomin Raj";
refSix.distributor = "Red Giant Movies";
refSix.hasSequel = false;
refSix.hasPrequel = false;
refSix.wonAwards = true;
refSix.rating = "4.3/5";
refSix.countryOfOrigin = "India";
refSix.audienceType = "U/A";

System.out.println("The movieId is: " + refSix.movieId);
System.out.println("The title is: " + refSix.title);
System.out.println("The director is: " + refSix.director);
System.out.println("The producer is: " + refSix.producer);
System.out.println("The productionCompany is: " + refSix.productionCompany);
System.out.println("The releaseYear is: " + refSix.releaseYear);
System.out.println("The language is: " + refSix.language);
System.out.println("The genre is: " + refSix.genre);
System.out.println("The duration is: " + refSix.duration);
System.out.println("The budget is: " + refSix.budget);
System.out.println("The boxOfficeCollection is: " + refSix.boxOfficeCollection);
System.out.println("The leadActor is: " + refSix.leadActor);
System.out.println("The leadActress is: " + refSix.leadActress);
System.out.println("The supportingActor is: " + refSix.supportingActor);
System.out.println("The supportingActress is: " + refSix.supportingActress);
System.out.println("The musicDirector is: " + refSix.musicDirector);
System.out.println("The cinematographer is: " + refSix.cinematographer);
System.out.println("The editor is: " + refSix.editor);
System.out.println("The distributor is: " + refSix.distributor);
System.out.println("The hasSequel is: " + refSix.hasSequel);
System.out.println("The hasPrequel is: " + refSix.hasPrequel);
System.out.println("The wonAwards is: " + refSix.wonAwards);
System.out.println("The rating is: " + refSix.rating);
System.out.println("The countryOfOrigin is: " + refSix.countryOfOrigin);
System.out.println("The audienceType is: " + refSix.audienceType);
Movie refSeven = new Movie();

System.out.println("The movieId is: " + refSeven.movieId);
System.out.println("The title is: " + refSeven.title);
System.out.println("The director is: " + refSeven.director);
System.out.println("The producer is: " + refSeven.producer);
System.out.println("The productionCompany is: " + refSeven.productionCompany);
System.out.println("The releaseYear is: " + refSeven.releaseYear);
System.out.println("The language is: " + refSeven.language);
System.out.println("The genre is: " + refSeven.genre);
System.out.println("The duration is: " + refSeven.duration);
System.out.println("The budget is: " + refSeven.budget);
System.out.println("The boxOfficeCollection is: " + refSeven.boxOfficeCollection);
System.out.println("The leadActor is: " + refSeven.leadActor);
System.out.println("The leadActress is: " + refSeven.leadActress);
System.out.println("The supportingActor is: " + refSeven.supportingActor);
System.out.println("The supportingActress is: " + refSeven.supportingActress);
System.out.println("The musicDirector is: " + refSeven.musicDirector);
System.out.println("The cinematographer is: " + refSeven.cinematographer);
System.out.println("The editor is: " + refSeven.editor);
System.out.println("The distributor is: " + refSeven.distributor);
System.out.println("The hasSequel is: " + refSeven.hasSequel);
System.out.println("The hasPrequel is: " + refSeven.hasPrequel);
System.out.println("The wonAwards is: " + refSeven.wonAwards);
System.out.println("The rating is: " + refSeven.rating);
System.out.println("The countryOfOrigin is: " + refSeven.countryOfOrigin);
System.out.println("The audienceType is: " + refSeven.audienceType);

refSeven.movieId = 7;
refSeven.title = "Jailer";
refSeven.director = "Nelson Dilipkumar";
refSeven.producer = "Kalanithi Maran";
refSeven.productionCompany = "Sun Pictures";
refSeven.releaseYear = 2023;
refSeven.language = "Tamil";
refSeven.genre = "Action Comedy";
refSeven.duration = 2.48;
refSeven.budget = 200.0;
refSeven.boxOfficeCollection = 650.0;
refSeven.leadActor = "Rajinikanth";
refSeven.leadActress = "Ramya Krishnan";
refSeven.supportingActor = "Shiva Rajkumar";
refSeven.supportingActress = "Tamannaah";
refSeven.musicDirector = "Anirudh Ravichander";
refSeven.cinematographer = "Vijay Kartik Kannan";
refSeven.editor = "R. Nirmal";
refSeven.distributor = "Red Giant Movies";
refSeven.hasSequel = false;
refSeven.hasPrequel = false;
refSeven.wonAwards = true;
refSeven.rating = "4.4/5";
refSeven.countryOfOrigin = "India";
refSeven.audienceType = "U/A";

System.out.println("The movieId is: " + refSeven.movieId);
System.out.println("The title is: " + refSeven.title);
System.out.println("The director is: " + refSeven.director);
System.out.println("The producer is: " + refSeven.producer);
System.out.println("The productionCompany is: " + refSeven.productionCompany);
System.out.println("The releaseYear is: " + refSeven.releaseYear);
System.out.println("The language is: " + refSeven.language);
System.out.println("The genre is: " + refSeven.genre);
System.out.println("The duration is: " + refSeven.duration);
System.out.println("The budget is: " + refSeven.budget);
System.out.println("The boxOfficeCollection is: " + refSeven.boxOfficeCollection);
System.out.println("The leadActor is: " + refSeven.leadActor);
System.out.println("The leadActress is: " + refSeven.leadActress);
System.out.println("The supportingActor is: " + refSeven.supportingActor);
System.out.println("The supportingActress is: " + refSeven.supportingActress);
System.out.println("The musicDirector is: " + refSeven.musicDirector);
System.out.println("The cinematographer is: " + refSeven.cinematographer);
System.out.println("The editor is: " + refSeven.editor);
System.out.println("The distributor is: " + refSeven.distributor);
System.out.println("The hasSequel is: " + refSeven.hasSequel);
System.out.println("The hasPrequel is: " + refSeven.hasPrequel);
System.out.println("The wonAwards is: " + refSeven.wonAwards);
System.out.println("The rating is: " + refSeven.rating);
System.out.println("The countryOfOrigin is: " + refSeven.countryOfOrigin);
System.out.println("The audienceType is: " + refSeven.audienceType);
Movie refEight = new Movie();

System.out.println("The movieId is: " + refEight.movieId);
System.out.println("The title is: " + refEight.title);
System.out.println("The director is: " + refEight.director);
System.out.println("The producer is: " + refEight.producer);
System.out.println("The productionCompany is: " + refEight.productionCompany);
System.out.println("The releaseYear is: " + refEight.releaseYear);
System.out.println("The language is: " + refEight.language);
System.out.println("The genre is: " + refEight.genre);
System.out.println("The duration is: " + refEight.duration);
System.out.println("The budget is: " + refEight.budget);
System.out.println("The boxOfficeCollection is: " + refEight.boxOfficeCollection);
System.out.println("The leadActor is: " + refEight.leadActor);
System.out.println("The leadActress is: " + refEight.leadActress);
System.out.println("The supportingActor is: " + refEight.supportingActor);
System.out.println("The supportingActress is: " + refEight.supportingActress);
System.out.println("The musicDirector is: " + refEight.musicDirector);
System.out.println("The cinematographer is: " + refEight.cinematographer);
System.out.println("The editor is: " + refEight.editor);
System.out.println("The distributor is: " + refEight.distributor);
System.out.println("The hasSequel is: " + refEight.hasSequel);
System.out.println("The hasPrequel is: " + refEight.hasPrequel);
System.out.println("The wonAwards is: " + refEight.wonAwards);
System.out.println("The rating is: " + refEight.rating);
System.out.println("The countryOfOrigin is: " + refEight.countryOfOrigin);
System.out.println("The audienceType is: " + refEight.audienceType);

refEight.movieId = 8;
refEight.title = "Vikram";
refEight.director = "Lokesh Kanagaraj";
refEight.producer = "Kamal Haasan";
refEight.productionCompany = "Raaj Kamal Films International";
refEight.releaseYear = 2022;
refEight.language = "Tamil";
refEight.genre = "Action Thriller";
refEight.duration = 2.53;
refEight.budget = 150.0;
refEight.boxOfficeCollection = 500.0;
refEight.leadActor = "Kamal Haasan";
refEight.leadActress = "Gayathrie";
refEight.supportingActor = "Vijay Sethupathi";
refEight.supportingActress = "Kalidas Jayaram";
refEight.musicDirector = "Anirudh Ravichander";
refEight.cinematographer = "Girish Gangadharan";
refEight.editor = "Philomin Raj";
refEight.distributor = "Red Giant Movies";
refEight.hasSequel = true;
refEight.hasPrequel = false;
refEight.wonAwards = true;
refEight.rating = "4.6/5";
refEight.countryOfOrigin = "India";
refEight.audienceType = "U/A";

System.out.println("The movieId is: " + refEight.movieId);
System.out.println("The title is: " + refEight.title);
System.out.println("The director is: " + refEight.director);
System.out.println("The producer is: " + refEight.producer);
System.out.println("The productionCompany is: " + refEight.productionCompany);
System.out.println("The releaseYear is: " + refEight.releaseYear);
System.out.println("The language is: " + refEight.language);
System.out.println("The genre is: " + refEight.genre);
System.out.println("The duration is: " + refEight.duration);
System.out.println("The budget is: " + refEight.budget);
System.out.println("The boxOfficeCollection is: " + refEight.boxOfficeCollection);
System.out.println("The leadActor is: " + refEight.leadActor);
System.out.println("The leadActress is: " + refEight.leadActress);
System.out.println("The supportingActor is: " + refEight.supportingActor);
System.out.println("The supportingActress is: " + refEight.supportingActress);
System.out.println("The musicDirector is: " + refEight.musicDirector);
System.out.println("The cinematographer is: " + refEight.cinematographer);
System.out.println("The editor is: " + refEight.editor);
System.out.println("The distributor is: " + refEight.distributor);
System.out.println("The hasSequel is: " + refEight.hasSequel);
System.out.println("The hasPrequel is: " + refEight.hasPrequel);
System.out.println("The wonAwards is: " + refEight.wonAwards);
System.out.println("The rating is: " + refEight.rating);
System.out.println("The countryOfOrigin is: " + refEight.countryOfOrigin);
System.out.println("The audienceType is: " + refEight.audienceType);
Movie refNine = new Movie();

System.out.println("The movieId is: " + refNine.movieId);
System.out.println("The title is: " + refNine.title);
System.out.println("The director is: " + refNine.director);
System.out.println("The producer is: " + refNine.producer);
System.out.println("The productionCompany is: " + refNine.productionCompany);
System.out.println("The releaseYear is: " + refNine.releaseYear);
System.out.println("The language is: " + refNine.language);
System.out.println("The genre is: " + refNine.genre);
System.out.println("The duration is: " + refNine.duration);
System.out.println("The budget is: " + refNine.budget);
System.out.println("The boxOfficeCollection is: " + refNine.boxOfficeCollection);
System.out.println("The leadActor is: " + refNine.leadActor);
System.out.println("The leadActress is: " + refNine.leadActress);
System.out.println("The supportingActor is: " + refNine.supportingActor);
System.out.println("The supportingActress is: " + refNine.supportingActress);
System.out.println("The musicDirector is: " + refNine.musicDirector);
System.out.println("The cinematographer is: " + refNine.cinematographer);
System.out.println("The editor is: " + refNine.editor);
System.out.println("The distributor is: " + refNine.distributor);
System.out.println("The hasSequel is: " + refNine.hasSequel);
System.out.println("The hasPrequel is: " + refNine.hasPrequel);
System.out.println("The wonAwards is: " + refNine.wonAwards);
System.out.println("The rating is: " + refNine.rating);
System.out.println("The countryOfOrigin is: " + refNine.countryOfOrigin);
System.out.println("The audienceType is: " + refNine.audienceType);

refNine.movieId = 9;
refNine.title = "Beast";
refNine.director = "Nelson Dilipkumar";
refNine.producer = "Kalanithi Maran";
refNine.productionCompany = "Sun Pictures";
refNine.releaseYear = 2022;
refNine.language = "Tamil";
refNine.genre = "Action";
refNine.duration = 2.35;
refNine.budget = 150.0;
refNine.boxOfficeCollection = 300.0;
refNine.leadActor = "Vijay";
refNine.leadActress = "Pooja Hegde";
refNine.supportingActor = "Selvaraghavan";
refNine.supportingActress = "Aparna Das";
refNine.musicDirector = "Anirudh Ravichander";
refNine.cinematographer = "Manoj Paramahamsa";
refNine.editor = "R. Nirmal";
refNine.distributor = "Red Giant Movies";
refNine.hasSequel = false;
refNine.hasPrequel = false;
refNine.wonAwards = false;
refNine.rating = "4.0/5";
refNine.countryOfOrigin = "India";
refNine.audienceType = "U/A";

System.out.println("The movieId is: " + refNine.movieId);
System.out.println("The title is: " + refNine.title);
System.out.println("The director is: " + refNine.director);
System.out.println("The producer is: " + refNine.producer);
System.out.println("The productionCompany is: " + refNine.productionCompany);
System.out.println("The releaseYear is: " + refNine.releaseYear);
System.out.println("The language is: " + refNine.language);
System.out.println("The genre is: " + refNine.genre);
System.out.println("The duration is: " + refNine.duration);
System.out.println("The budget is: " + refNine.budget);
System.out.println("The boxOfficeCollection is: " + refNine.boxOfficeCollection);
System.out.println("The leadActor is: " + refNine.leadActor);
System.out.println("The leadActress is: " + refNine.leadActress);
System.out.println("The supportingActor is: " + refNine.supportingActor);
System.out.println("The supportingActress is: " + refNine.supportingActress);
System.out.println("The musicDirector is: " + refNine.musicDirector);
System.out.println("The cinematographer is: " + refNine.cinematographer);
System.out.println("The editor is: " + refNine.editor);
System.out.println("The distributor is: " + refNine.distributor);
System.out.println("The hasSequel is: " + refNine.hasSequel);
System.out.println("The hasPrequel is: " + refNine.hasPrequel);
System.out.println("The wonAwards is: " + refNine.wonAwards);
System.out.println("The rating is: " + refNine.rating);
System.out.println("The countryOfOrigin is: " + refNine.countryOfOrigin);
System.out.println("The audienceType is: " + refNine.audienceType);
Movie refTen = new Movie();

System.out.println("The movieId is: " + refTen.movieId);
System.out.println("The title is: " + refTen.title);
System.out.println("The director is: " + refTen.director);
System.out.println("The producer is: " + refTen.producer);
System.out.println("The productionCompany is: " + refTen.productionCompany);
System.out.println("The releaseYear is: " + refTen.releaseYear);
System.out.println("The language is: " + refTen.language);
System.out.println("The genre is: " + refTen.genre);
System.out.println("The duration is: " + refTen.duration);
System.out.println("The budget is: " + refTen.budget);
System.out.println("The boxOfficeCollection is: " + refTen.boxOfficeCollection);
System.out.println("The leadActor is: " + refTen.leadActor);
System.out.println("The leadActress is: " + refTen.leadActress);
System.out.println("The supportingActor is: " + refTen.supportingActor);
System.out.println("The supportingActress is: " + refTen.supportingActress);
System.out.println("The musicDirector is: " + refTen.musicDirector);
System.out.println("The cinematographer is: " + refTen.cinematographer);
System.out.println("The editor is: " + refTen.editor);
System.out.println("The distributor is: " + refTen.distributor);
System.out.println("The hasSequel is: " + refTen.hasSequel);
System.out.println("The hasPrequel is: " + refTen.hasPrequel);
System.out.println("The wonAwards is: " + refTen.wonAwards);
System.out.println("The rating is: " + refTen.rating);
System.out.println("The countryOfOrigin is: " + refTen.countryOfOrigin);
System.out.println("The audienceType is: " + refTen.audienceType);

refTen.movieId = 10;
refTen.title = "KGF Chapter 2";
refTen.director = "Prashanth Neel";
refTen.producer = "Vijay Kiragandur";
refTen.productionCompany = "Hombale Films";
refTen.releaseYear = 2022;
refTen.language = "Kannada";
refTen.genre = "Action";
refTen.duration = 2.48;
refTen.budget = 100.0;
refTen.boxOfficeCollection = 1200.0;
refTen.leadActor = "Yash";
refTen.leadActress = "Srinidhi Shetty";
refTen.supportingActor = "Sanjay Dutt";
refTen.supportingActress = "Raveena Tandon";
refTen.musicDirector = "Ravi Basrur";
refTen.cinematographer = "Bhuvan Gowda";
refTen.editor = "Ujwal Kulkarni";
refTen.distributor = "Excel Entertainment";
refTen.hasSequel = false;
refTen.hasPrequel = true;
refTen.wonAwards = true;
refTen.rating = "4.7/5";
refTen.countryOfOrigin = "India";
refTen.audienceType = "U/A";

System.out.println("The movieId is: " + refTen.movieId);
System.out.println("The title is: " + refTen.title);
System.out.println("The director is: " + refTen.director);
System.out.println("The producer is: " + refTen.producer);
System.out.println("The productionCompany is: " + refTen.productionCompany);
System.out.println("The releaseYear is: " + refTen.releaseYear);
System.out.println("The language is: " + refTen.language);
System.out.println("The genre is: " + refTen.genre);
System.out.println("The duration is: " + refTen.duration);
System.out.println("The budget is: " + refTen.budget);
System.out.println("The boxOfficeCollection is: " + refTen.boxOfficeCollection);
System.out.println("The leadActor is: " + refTen.leadActor);
System.out.println("The leadActress is: " + refTen.leadActress);
System.out.println("The supportingActor is: " + refTen.supportingActor);
System.out.println("The supportingActress is: " + refTen.supportingActress);
System.out.println("The musicDirector is: " + refTen.musicDirector);
System.out.println("The cinematographer is: " + refTen.cinematographer);
System.out.println("The editor is: " + refTen.editor);
System.out.println("The distributor is: " + refTen.distributor);
System.out.println("The hasSequel is: " + refTen.hasSequel);
System.out.println("The hasPrequel is: " + refTen.hasPrequel);
System.out.println("The wonAwards is: " + refTen.wonAwards);
System.out.println("The rating is: " + refTen.rating);
System.out.println("The countryOfOrigin is: " + refTen.countryOfOrigin);
System.out.println("The audienceType is: " + refTen.audienceType);
Movie refEleven = new Movie();

System.out.println("The movieId is: " + refEleven.movieId);
System.out.println("The title is: " + refEleven.title);
System.out.println("The director is: " + refEleven.director);
System.out.println("The producer is: " + refEleven.producer);
System.out.println("The productionCompany is: " + refEleven.productionCompany);
System.out.println("The releaseYear is: " + refEleven.releaseYear);
System.out.println("The language is: " + refEleven.language);
System.out.println("The genre is: " + refEleven.genre);
System.out.println("The duration is: " + refEleven.duration);
System.out.println("The budget is: " + refEleven.budget);
System.out.println("The boxOfficeCollection is: " + refEleven.boxOfficeCollection);
System.out.println("The leadActor is: " + refEleven.leadActor);
System.out.println("The leadActress is: " + refEleven.leadActress);
System.out.println("The supportingActor is: " + refEleven.supportingActor);
System.out.println("The supportingActress is: " + refEleven.supportingActress);
System.out.println("The musicDirector is: " + refEleven.musicDirector);
System.out.println("The cinematographer is: " + refEleven.cinematographer);
System.out.println("The editor is: " + refEleven.editor);
System.out.println("The distributor is: " + refEleven.distributor);
System.out.println("The hasSequel is: " + refEleven.hasSequel);
System.out.println("The hasPrequel is: " + refEleven.hasPrequel);
System.out.println("The wonAwards is: " + refEleven.wonAwards);
System.out.println("The rating is: " + refEleven.rating);
System.out.println("The countryOfOrigin is: " + refEleven.countryOfOrigin);
System.out.println("The audienceType is: " + refEleven.audienceType);

refEleven.movieId = 11;
refEleven.title = "Drishyam";
refEleven.director = "Jeethu Joseph";
refEleven.producer = "Antony Perumbavoor";
refEleven.productionCompany = "Aashirvad Cinemas";
refEleven.releaseYear = 2013;
refEleven.language = "Malayalam";
refEleven.genre = "Thriller";
refEleven.duration = 2.40;
refEleven.budget = 5.0;
refEleven.boxOfficeCollection = 75.0;
refEleven.leadActor = "Mohanlal";
refEleven.leadActress = "Meena";
refEleven.supportingActor = "Asha Sharath";
refEleven.supportingActress = "Ansiba Hassan";
refEleven.musicDirector = "Anil Johnson";
refEleven.cinematographer = "Sujith Vaassudev";
refEleven.editor = "Ranjan Abraham";
refEleven.distributor = "Maxlab Cinemas";
refEleven.hasSequel = true;
refEleven.hasPrequel = false;
refEleven.wonAwards = true;
refEleven.rating = "4.8/5";
refEleven.countryOfOrigin = "India";
refEleven.audienceType = "U";

System.out.println("The movieId is: " + refEleven.movieId);
System.out.println("The title is: " + refEleven.title);
System.out.println("The director is: " + refEleven.director);
System.out.println("The producer is: " + refEleven.producer);
System.out.println("The productionCompany is: " + refEleven.productionCompany);
System.out.println("The releaseYear is: " + refEleven.releaseYear);
System.out.println("The language is: " + refEleven.language);
System.out.println("The genre is: " + refEleven.genre);
System.out.println("The duration is: " + refEleven.duration);
System.out.println("The budget is: " + refEleven.budget);
System.out.println("The boxOfficeCollection is: " + refEleven.boxOfficeCollection);
System.out.println("The leadActor is: " + refEleven.leadActor);
System.out.println("The leadActress is: " + refEleven.leadActress);
System.out.println("The supportingActor is: " + refEleven.supportingActor);
System.out.println("The supportingActress is: " + refEleven.supportingActress);
System.out.println("The musicDirector is: " + refEleven.musicDirector);
System.out.println("The cinematographer is: " + refEleven.cinematographer);
System.out.println("The editor is: " + refEleven.editor);
System.out.println("The distributor is: " + refEleven.distributor);
System.out.println("The hasSequel is: " + refEleven.hasSequel);
System.out.println("The hasPrequel is: " + refEleven.hasPrequel);
System.out.println("The wonAwards is: " + refEleven.wonAwards);
System.out.println("The rating is: " + refEleven.rating);
System.out.println("The countryOfOrigin is: " + refEleven.countryOfOrigin);
System.out.println("The audienceType is: " + refEleven.audienceType);
Movie refTwelve = new Movie();

System.out.println("The movieId is: " + refTwelve.movieId);
System.out.println("The title is: " + refTwelve.title);
System.out.println("The director is: " + refTwelve.director);
System.out.println("The producer is: " + refTwelve.producer);
System.out.println("The productionCompany is: " + refTwelve.productionCompany);
System.out.println("The releaseYear is: " + refTwelve.releaseYear);
System.out.println("The language is: " + refTwelve.language);
System.out.println("The genre is: " + refTwelve.genre);
System.out.println("The duration is: " + refTwelve.duration);
System.out.println("The budget is: " + refTwelve.budget);
System.out.println("The boxOfficeCollection is: " + refTwelve.boxOfficeCollection);
System.out.println("The leadActor is: " + refTwelve.leadActor);
System.out.println("The leadActress is: " + refTwelve.leadActress);
System.out.println("The supportingActor is: " + refTwelve.supportingActor);
System.out.println("The supportingActress is: " + refTwelve.supportingActress);
System.out.println("The musicDirector is: " + refTwelve.musicDirector);
System.out.println("The cinematographer is: " + refTwelve.cinematographer);
System.out.println("The editor is: " + refTwelve.editor);
System.out.println("The distributor is: " + refTwelve.distributor);
System.out.println("The hasSequel is: " + refTwelve.hasSequel);
System.out.println("The hasPrequel is: " + refTwelve.hasPrequel);
System.out.println("The wonAwards is: " + refTwelve.wonAwards);
System.out.println("The rating is: " + refTwelve.rating);
System.out.println("The countryOfOrigin is: " + refTwelve.countryOfOrigin);
System.out.println("The audienceType is: " + refTwelve.audienceType);

refTwelve.movieId = 12;
refTwelve.title = "3 Idiots";
refTwelve.director = "Rajkumar Hirani";
refTwelve.producer = "Vidhu Vinod Chopra";
refTwelve.productionCompany = "Vinod Chopra Films";
refTwelve.releaseYear = 2009;
refTwelve.language = "Hindi";
refTwelve.genre = "Comedy Drama";
refTwelve.duration = 2.50;
refTwelve.budget = 55.0;
refTwelve.boxOfficeCollection = 460.0;
refTwelve.leadActor = "Aamir Khan";
refTwelve.leadActress = "Kareena Kapoor";
refTwelve.supportingActor = "R. Madhavan";
refTwelve.supportingActress = "Mona Singh";
refTwelve.musicDirector = "Shantanu Moitra";
refTwelve.cinematographer = "C. K. Muraleedharan";
refTwelve.editor = "Ranjan Abraham";
refTwelve.distributor = "Reliance Entertainment";
refTwelve.hasSequel = false;
refTwelve.hasPrequel = false;
refTwelve.wonAwards = true;
refTwelve.rating = "4.9/5";
refTwelve.countryOfOrigin = "India";
refTwelve.audienceType = "U/A";

System.out.println("The movieId is: " + refTwelve.movieId);
System.out.println("The title is: " + refTwelve.title);
System.out.println("The director is: " + refTwelve.director);
System.out.println("The producer is: " + refTwelve.producer);
System.out.println("The productionCompany is: " + refTwelve.productionCompany);
System.out.println("The releaseYear is: " + refTwelve.releaseYear);
System.out.println("The language is: " + refTwelve.language);
System.out.println("The genre is: " + refTwelve.genre);
System.out.println("The duration is: " + refTwelve.duration);
System.out.println("The budget is: " + refTwelve.budget);
System.out.println("The boxOfficeCollection is: " + refTwelve.boxOfficeCollection);
System.out.println("The leadActor is: " + refTwelve.leadActor);
System.out.println("The leadActress is: " + refTwelve.leadActress);
System.out.println("The supportingActor is: " + refTwelve.supportingActor);
System.out.println("The supportingActress is: " + refTwelve.supportingActress);
System.out.println("The musicDirector is: " + refTwelve.musicDirector);
System.out.println("The cinematographer is: " + refTwelve.cinematographer);
System.out.println("The editor is: " + refTwelve.editor);
System.out.println("The distributor is: " + refTwelve.distributor);
System.out.println("The hasSequel is: " + refTwelve.hasSequel);
System.out.println("The hasPrequel is: " + refTwelve.hasPrequel);
System.out.println("The wonAwards is: " + refTwelve.wonAwards);
System.out.println("The rating is: " + refTwelve.rating);
System.out.println("The countryOfOrigin is: " + refTwelve.countryOfOrigin);
System.out.println("The audienceType is: " + refTwelve.audienceType);
Movie refThirteen = new Movie();

System.out.println("The movieId is: " + refThirteen.movieId);
System.out.println("The title is: " + refThirteen.title);
System.out.println("The director is: " + refThirteen.director);
System.out.println("The producer is: " + refThirteen.producer);
System.out.println("The productionCompany is: " + refThirteen.productionCompany);
System.out.println("The releaseYear is: " + refThirteen.releaseYear);
System.out.println("The language is: " + refThirteen.language);
System.out.println("The genre is: " + refThirteen.genre);
System.out.println("The duration is: " + refThirteen.duration);
System.out.println("The budget is: " + refThirteen.budget);
System.out.println("The boxOfficeCollection is: " + refThirteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refThirteen.leadActor);
System.out.println("The leadActress is: " + refThirteen.leadActress);
System.out.println("The supportingActor is: " + refThirteen.supportingActor);
System.out.println("The supportingActress is: " + refThirteen.supportingActress);
System.out.println("The musicDirector is: " + refThirteen.musicDirector);
System.out.println("The cinematographer is: " + refThirteen.cinematographer);
System.out.println("The editor is: " + refThirteen.editor);
System.out.println("The distributor is: " + refThirteen.distributor);
System.out.println("The hasSequel is: " + refThirteen.hasSequel);
System.out.println("The hasPrequel is: " + refThirteen.hasPrequel);
System.out.println("The wonAwards is: " + refThirteen.wonAwards);
System.out.println("The rating is: " + refThirteen.rating);
System.out.println("The countryOfOrigin is: " + refThirteen.countryOfOrigin);
System.out.println("The audienceType is: " + refThirteen.audienceType);

refThirteen.movieId = 13;
refThirteen.title = "Dangal";
refThirteen.director = "Nitesh Tiwari";
refThirteen.producer = "Aamir Khan";
refThirteen.productionCompany = "Aamir Khan Productions";
refThirteen.releaseYear = 2016;
refThirteen.language = "Hindi";
refThirteen.genre = "Sports Drama";
refThirteen.duration = 2.41;
refThirteen.budget = 70.0;
refThirteen.boxOfficeCollection = 2000.0;
refThirteen.leadActor = "Aamir Khan";
refThirteen.leadActress = "Fatima Sana Shaikh";
refThirteen.supportingActor = "Sakshi Tanwar";
refThirteen.supportingActress = "Sanya Malhotra";
refThirteen.musicDirector = "Pritam";
refThirteen.cinematographer = "Satyajit Pande";
refThirteen.editor = "Ballu Saluja";
refThirteen.distributor = "UTV Motion Pictures";
refThirteen.hasSequel = false;
refThirteen.hasPrequel = false;
refThirteen.wonAwards = true;
refThirteen.rating = "4.8/5";
refThirteen.countryOfOrigin = "India";
refThirteen.audienceType = "U";

System.out.println("The movieId is: " + refThirteen.movieId);
System.out.println("The title is: " + refThirteen.title);
System.out.println("The director is: " + refThirteen.director);
System.out.println("The producer is: " + refThirteen.producer);
System.out.println("The productionCompany is: " + refThirteen.productionCompany);
System.out.println("The releaseYear is: " + refThirteen.releaseYear);
System.out.println("The language is: " + refThirteen.language);
System.out.println("The genre is: " + refThirteen.genre);
System.out.println("The duration is: " + refThirteen.duration);
System.out.println("The budget is: " + refThirteen.budget);
System.out.println("The boxOfficeCollection is: " + refThirteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refThirteen.leadActor);
System.out.println("The leadActress is: " + refThirteen.leadActress);
System.out.println("The supportingActor is: " + refThirteen.supportingActor);
System.out.println("The supportingActress is: " + refThirteen.supportingActress);
System.out.println("The musicDirector is: " + refThirteen.musicDirector);
System.out.println("The cinematographer is: " + refThirteen.cinematographer);
System.out.println("The editor is: " + refThirteen.editor);
System.out.println("The distributor is: " + refThirteen.distributor);
System.out.println("The hasSequel is: " + refThirteen.hasSequel);
System.out.println("The hasPrequel is: " + refThirteen.hasPrequel);
System.out.println("The wonAwards is: " + refThirteen.wonAwards);
System.out.println("The rating is: " + refThirteen.rating);
System.out.println("The countryOfOrigin is: " + refThirteen.countryOfOrigin);
System.out.println("The audienceType is: " + refThirteen.audienceType);
Movie refFourteen = new Movie();

System.out.println("The movieId is: " + refFourteen.movieId);
System.out.println("The title is: " + refFourteen.title);
System.out.println("The director is: " + refFourteen.director);
System.out.println("The producer is: " + refFourteen.producer);
System.out.println("The productionCompany is: " + refFourteen.productionCompany);
System.out.println("The releaseYear is: " + refFourteen.releaseYear);
System.out.println("The language is: " + refFourteen.language);
System.out.println("The genre is: " + refFourteen.genre);
System.out.println("The duration is: " + refFourteen.duration);
System.out.println("The budget is: " + refFourteen.budget);
System.out.println("The boxOfficeCollection is: " + refFourteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refFourteen.leadActor);
System.out.println("The leadActress is: " + refFourteen.leadActress);
System.out.println("The supportingActor is: " + refFourteen.supportingActor);
System.out.println("The supportingActress is: " + refFourteen.supportingActress);
System.out.println("The musicDirector is: " + refFourteen.musicDirector);
System.out.println("The cinematographer is: " + refFourteen.cinematographer);
System.out.println("The editor is: " + refFourteen.editor);
System.out.println("The distributor is: " + refFourteen.distributor);
System.out.println("The hasSequel is: " + refFourteen.hasSequel);
System.out.println("The hasPrequel is: " + refFourteen.hasPrequel);
System.out.println("The wonAwards is: " + refFourteen.wonAwards);
System.out.println("The rating is: " + refFourteen.rating);
System.out.println("The countryOfOrigin is: " + refFourteen.countryOfOrigin);
System.out.println("The audienceType is: " + refFourteen.audienceType);

refFourteen.movieId = 14;
refFourteen.title = "Baahubali 2: The Conclusion";
refFourteen.director = "S. S. Rajamouli";
refFourteen.producer = "Shobu Yarlagadda";
refFourteen.productionCompany = "Arka Media Works";
refFourteen.releaseYear = 2017;
refFourteen.language = "Telugu";
refFourteen.genre = "Epic Action";
refFourteen.duration = 2.47;
refFourteen.budget = 250.0;
refFourteen.boxOfficeCollection = 1800.0;
refFourteen.leadActor = "Prabhas";
refFourteen.leadActress = "Anushka Shetty";
refFourteen.supportingActor = "Rana Daggubati";
refFourteen.supportingActress = "Tamannaah";
refFourteen.musicDirector = "M. M. Keeravani";
refFourteen.cinematographer = "K. K. Senthil Kumar";
refFourteen.editor = "Kotagiri Venkateswara Rao";
refFourteen.distributor = "Dharma Productions";
refFourteen.hasSequel = false;
refFourteen.hasPrequel = true;
refFourteen.wonAwards = true;
refFourteen.rating = "4.9/5";
refFourteen.countryOfOrigin = "India";
refFourteen.audienceType = "U/A";

System.out.println("The movieId is: " + refFourteen.movieId);
System.out.println("The title is: " + refFourteen.title);
System.out.println("The director is: " + refFourteen.director);
System.out.println("The producer is: " + refFourteen.producer);
System.out.println("The productionCompany is: " + refFourteen.productionCompany);
System.out.println("The releaseYear is: " + refFourteen.releaseYear);
System.out.println("The language is: " + refFourteen.language);
System.out.println("The genre is: " + refFourteen.genre);
System.out.println("The duration is: " + refFourteen.duration);
System.out.println("The budget is: " + refFourteen.budget);
System.out.println("The boxOfficeCollection is: " + refFourteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refFourteen.leadActor);
System.out.println("The leadActress is: " + refFourteen.leadActress);
System.out.println("The supportingActor is: " + refFourteen.supportingActor);
System.out.println("The supportingActress is: " + refFourteen.supportingActress);
System.out.println("The musicDirector is: " + refFourteen.musicDirector);
System.out.println("The cinematographer is: " + refFourteen.cinematographer);
System.out.println("The editor is: " + refFourteen.editor);
System.out.println("The distributor is: " + refFourteen.distributor);
System.out.println("The hasSequel is: " + refFourteen.hasSequel);
System.out.println("The hasPrequel is: " + refFourteen.hasPrequel);
System.out.println("The wonAwards is: " + refFourteen.wonAwards);
System.out.println("The rating is: " + refFourteen.rating);
System.out.println("The countryOfOrigin is: " + refFourteen.countryOfOrigin);
System.out.println("The audienceType is: " + refFourteen.audienceType);
Movie refFifteen = new Movie();

System.out.println("The movieId is: " + refFifteen.movieId);
System.out.println("The title is: " + refFifteen.title);
System.out.println("The director is: " + refFifteen.director);
System.out.println("The producer is: " + refFifteen.producer);
System.out.println("The productionCompany is: " + refFifteen.productionCompany);
System.out.println("The releaseYear is: " + refFifteen.releaseYear);
System.out.println("The language is: " + refFifteen.language);
System.out.println("The genre is: " + refFifteen.genre);
System.out.println("The duration is: " + refFifteen.duration);
System.out.println("The budget is: " + refFifteen.budget);
System.out.println("The boxOfficeCollection is: " + refFifteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refFifteen.leadActor);
System.out.println("The leadActress is: " + refFifteen.leadActress);
System.out.println("The supportingActor is: " + refFifteen.supportingActor);
System.out.println("The supportingActress is: " + refFifteen.supportingActress);
System.out.println("The musicDirector is: " + refFifteen.musicDirector);
System.out.println("The cinematographer is: " + refFifteen.cinematographer);
System.out.println("The editor is: " + refFifteen.editor);
System.out.println("The distributor is: " + refFifteen.distributor);
System.out.println("The hasSequel is: " + refFifteen.hasSequel);
System.out.println("The hasPrequel is: " + refFifteen.hasPrequel);
System.out.println("The wonAwards is: " + refFifteen.wonAwards);
System.out.println("The rating is: " + refFifteen.rating);
System.out.println("The countryOfOrigin is: " + refFifteen.countryOfOrigin);
System.out.println("The audienceType is: " + refFifteen.audienceType);

refFifteen.movieId = 15;
refFifteen.title = "Kantara";
refFifteen.director = "Rishab Shetty";
refFifteen.producer = "Vijay Kiragandur";
refFifteen.productionCompany = "Hombale Films";
refFifteen.releaseYear = 2022;
refFifteen.language = "Kannada";
refFifteen.genre = "Action Thriller";
refFifteen.duration = 2.30;
refFifteen.budget = 16.0;
refFifteen.boxOfficeCollection = 400.0;
refFifteen.leadActor = "Rishab Shetty";
refFifteen.leadActress = "Sapthami Gowda";
refFifteen.supportingActor = "Achyuth Kumar";
refFifteen.supportingActress = "Pramod Shetty";
refFifteen.musicDirector = "B. Ajaneesh Loknath";
refFifteen.cinematographer = "Arvind S. Kashyap";
refFifteen.editor = "Pratheek Shetty";
refFifteen.distributor = "Hombale Films";
refFifteen.hasSequel = true;
refFifteen.hasPrequel = false;
refFifteen.wonAwards = true;
refFifteen.rating = "4.8/5";
refFifteen.countryOfOrigin = "India";
refFifteen.audienceType = "U/A";

System.out.println("The movieId is: " + refFifteen.movieId);
System.out.println("The title is: " + refFifteen.title);
System.out.println("The director is: " + refFifteen.director);
System.out.println("The producer is: " + refFifteen.producer);
System.out.println("The productionCompany is: " + refFifteen.productionCompany);
System.out.println("The releaseYear is: " + refFifteen.releaseYear);
System.out.println("The language is: " + refFifteen.language);
System.out.println("The genre is: " + refFifteen.genre);
System.out.println("The duration is: " + refFifteen.duration);
System.out.println("The budget is: " + refFifteen.budget);
System.out.println("The boxOfficeCollection is: " + refFifteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refFifteen.leadActor);
System.out.println("The leadActress is: " + refFifteen.leadActress);
System.out.println("The supportingActor is: " + refFifteen.supportingActor);
System.out.println("The supportingActress is: " + refFifteen.supportingActress);
System.out.println("The musicDirector is: " + refFifteen.musicDirector);
System.out.println("The cinematographer is: " + refFifteen.cinematographer);
System.out.println("The editor is: " + refFifteen.editor);
System.out.println("The distributor is: " + refFifteen.distributor);
System.out.println("The hasSequel is: " + refFifteen.hasSequel);
System.out.println("The hasPrequel is: " + refFifteen.hasPrequel);
System.out.println("The wonAwards is: " + refFifteen.wonAwards);
System.out.println("The rating is: " + refFifteen.rating);
System.out.println("The countryOfOrigin is: " + refFifteen.countryOfOrigin);
System.out.println("The audienceType is: " + refFifteen.audienceType);
Movie refSixteen = new Movie();

System.out.println("The movieId is: " + refSixteen.movieId);
System.out.println("The title is: " + refSixteen.title);
System.out.println("The director is: " + refSixteen.director);
System.out.println("The producer is: " + refSixteen.producer);
System.out.println("The productionCompany is: " + refSixteen.productionCompany);
System.out.println("The releaseYear is: " + refSixteen.releaseYear);
System.out.println("The language is: " + refSixteen.language);
System.out.println("The genre is: " + refSixteen.genre);
System.out.println("The duration is: " + refSixteen.duration);
System.out.println("The budget is: " + refSixteen.budget);
System.out.println("The boxOfficeCollection is: " + refSixteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refSixteen.leadActor);
System.out.println("The leadActress is: " + refSixteen.leadActress);
System.out.println("The supportingActor is: " + refSixteen.supportingActor);
System.out.println("The supportingActress is: " + refSixteen.supportingActress);
System.out.println("The musicDirector is: " + refSixteen.musicDirector);
System.out.println("The cinematographer is: " + refSixteen.cinematographer);
System.out.println("The editor is: " + refSixteen.editor);
System.out.println("The distributor is: " + refSixteen.distributor);
System.out.println("The hasSequel is: " + refSixteen.hasSequel);
System.out.println("The hasPrequel is: " + refSixteen.hasPrequel);
System.out.println("The wonAwards is: " + refSixteen.wonAwards);
System.out.println("The rating is: " + refSixteen.rating);
System.out.println("The countryOfOrigin is: " + refSixteen.countryOfOrigin);
System.out.println("The audienceType is: " + refSixteen.audienceType);

refSixteen.movieId = 16;
refSixteen.title = "Avengers: Endgame";
refSixteen.director = "Anthony Russo & Joe Russo";
refSixteen.producer = "Kevin Feige";
refSixteen.productionCompany = "Marvel Studios";
refSixteen.releaseYear = 2019;
refSixteen.language = "English";
refSixteen.genre = "Superhero";
refSixteen.duration = 3.02;
refSixteen.budget = 356.0;
refSixteen.boxOfficeCollection = 2797.0;
refSixteen.leadActor = "Robert Downey Jr.";
refSixteen.leadActress = "Scarlett Johansson";
refSixteen.supportingActor = "Chris Evans";
refSixteen.supportingActress = "Brie Larson";
refSixteen.musicDirector = "Alan Silvestri";
refSixteen.cinematographer = "Trent Opaloch";
refSixteen.editor = "Jeffrey Ford";
refSixteen.distributor = "Walt Disney Studios";
refSixteen.hasSequel = false;
refSixteen.hasPrequel = true;
refSixteen.wonAwards = true;
refSixteen.rating = "4.9/5";
refSixteen.countryOfOrigin = "USA";
refSixteen.audienceType = "U/A";

System.out.println("The movieId is: " + refSixteen.movieId);
System.out.println("The title is: " + refSixteen.title);
System.out.println("The director is: " + refSixteen.director);
System.out.println("The producer is: " + refSixteen.producer);
System.out.println("The productionCompany is: " + refSixteen.productionCompany);
System.out.println("The releaseYear is: " + refSixteen.releaseYear);
System.out.println("The language is: " + refSixteen.language);
System.out.println("The genre is: " + refSixteen.genre);
System.out.println("The duration is: " + refSixteen.duration);
System.out.println("The budget is: " + refSixteen.budget);
System.out.println("The boxOfficeCollection is: " + refSixteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refSixteen.leadActor);
System.out.println("The leadActress is: " + refSixteen.leadActress);
System.out.println("The supportingActor is: " + refSixteen.supportingActor);
System.out.println("The supportingActress is: " + refSixteen.supportingActress);
System.out.println("The musicDirector is: " + refSixteen.musicDirector);
System.out.println("The cinematographer is: " + refSixteen.cinematographer);
System.out.println("The editor is: " + refSixteen.editor);
System.out.println("The distributor is: " + refSixteen.distributor);
System.out.println("The hasSequel is: " + refSixteen.hasSequel);
System.out.println("The hasPrequel is: " + refSixteen.hasPrequel);
System.out.println("The wonAwards is: " + refSixteen.wonAwards);
System.out.println("The rating is: " + refSixteen.rating);
System.out.println("The countryOfOrigin is: " + refSixteen.countryOfOrigin);
System.out.println("The audienceType is: " + refSixteen.audienceType);
Movie refSeventeen = new Movie();

System.out.println("The movieId is: " + refSeventeen.movieId);
System.out.println("The title is: " + refSeventeen.title);
System.out.println("The director is: " + refSeventeen.director);
System.out.println("The producer is: " + refSeventeen.producer);
System.out.println("The productionCompany is: " + refSeventeen.productionCompany);
System.out.println("The releaseYear is: " + refSeventeen.releaseYear);
System.out.println("The language is: " + refSeventeen.language);
System.out.println("The genre is: " + refSeventeen.genre);
System.out.println("The duration is: " + refSeventeen.duration);
System.out.println("The budget is: " + refSeventeen.budget);
System.out.println("The boxOfficeCollection is: " + refSeventeen.boxOfficeCollection);
System.out.println("The leadActor is: " + refSeventeen.leadActor);
System.out.println("The leadActress is: " + refSeventeen.leadActress);
System.out.println("The supportingActor is: " + refSeventeen.supportingActor);
System.out.println("The supportingActress is: " + refSeventeen.supportingActress);
System.out.println("The musicDirector is: " + refSeventeen.musicDirector);
System.out.println("The cinematographer is: " + refSeventeen.cinematographer);
System.out.println("The editor is: " + refSeventeen.editor);
System.out.println("The distributor is: " + refSeventeen.distributor);
System.out.println("The hasSequel is: " + refSeventeen.hasSequel);
System.out.println("The hasPrequel is: " + refSeventeen.hasPrequel);
System.out.println("The wonAwards is: " + refSeventeen.wonAwards);
System.out.println("The rating is: " + refSeventeen.rating);
System.out.println("The countryOfOrigin is: " + refSeventeen.countryOfOrigin);
System.out.println("The audienceType is: " + refSeventeen.audienceType);

refSeventeen.movieId = 17;
refSeventeen.title = "Interstellar";
refSeventeen.director = "Christopher Nolan";
refSeventeen.producer = "Emma Thomas";
refSeventeen.productionCompany = "Syncopy";
refSeventeen.releaseYear = 2014;
refSeventeen.language = "English";
refSeventeen.genre = "Science Fiction";
refSeventeen.duration = 2.49;
refSeventeen.budget = 165.0;
refSeventeen.boxOfficeCollection = 701.0;
refSeventeen.leadActor = "Matthew McConaughey";
refSeventeen.leadActress = "Anne Hathaway";
refSeventeen.supportingActor = "Michael Caine";
refSeventeen.supportingActress = "Jessica Chastain";
refSeventeen.musicDirector = "Hans Zimmer";
refSeventeen.cinematographer = "Hoyte van Hoytema";
refSeventeen.editor = "Lee Smith";
refSeventeen.distributor = "Paramount Pictures";
refSeventeen.hasSequel = false;
refSeventeen.hasPrequel = false;
refSeventeen.wonAwards = true;
refSeventeen.rating = "4.9/5";
refSeventeen.countryOfOrigin = "USA";
refSeventeen.audienceType = "U/A";

System.out.println("The movieId is: " + refSeventeen.movieId);
System.out.println("The title is: " + refSeventeen.title);
System.out.println("The director is: " + refSeventeen.director);
System.out.println("The producer is: " + refSeventeen.producer);
System.out.println("The productionCompany is: " + refSeventeen.productionCompany);
System.out.println("The releaseYear is: " + refSeventeen.releaseYear);
System.out.println("The language is: " + refSeventeen.language);
System.out.println("The genre is: " + refSeventeen.genre);
System.out.println("The duration is: " + refSeventeen.duration);
System.out.println("The budget is: " + refSeventeen.budget);
System.out.println("The boxOfficeCollection is: " + refSeventeen.boxOfficeCollection);
System.out.println("The leadActor is: " + refSeventeen.leadActor);
System.out.println("The leadActress is: " + refSeventeen.leadActress);
System.out.println("The supportingActor is: " + refSeventeen.supportingActor);
System.out.println("The supportingActress is: " + refSeventeen.supportingActress);
System.out.println("The musicDirector is: " + refSeventeen.musicDirector);
System.out.println("The cinematographer is: " + refSeventeen.cinematographer);
System.out.println("The editor is: " + refSeventeen.editor);
System.out.println("The distributor is: " + refSeventeen.distributor);
System.out.println("The hasSequel is: " + refSeventeen.hasSequel);
System.out.println("The hasPrequel is: " + refSeventeen.hasPrequel);
System.out.println("The wonAwards is: " + refSeventeen.wonAwards);
System.out.println("The rating is: " + refSeventeen.rating);
System.out.println("The countryOfOrigin is: " + refSeventeen.countryOfOrigin);
System.out.println("The audienceType is: " + refSeventeen.audienceType);
Movie refEighteen = new Movie();

System.out.println("The movieId is: " + refEighteen.movieId);
System.out.println("The title is: " + refEighteen.title);
System.out.println("The director is: " + refEighteen.director);
System.out.println("The producer is: " + refEighteen.producer);
System.out.println("The productionCompany is: " + refEighteen.productionCompany);
System.out.println("The releaseYear is: " + refEighteen.releaseYear);
System.out.println("The language is: " + refEighteen.language);
System.out.println("The genre is: " + refEighteen.genre);
System.out.println("The duration is: " + refEighteen.duration);
System.out.println("The budget is: " + refEighteen.budget);
System.out.println("The boxOfficeCollection is: " + refEighteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refEighteen.leadActor);
System.out.println("The leadActress is: " + refEighteen.leadActress);
System.out.println("The supportingActor is: " + refEighteen.supportingActor);
System.out.println("The supportingActress is: " + refEighteen.supportingActress);
System.out.println("The musicDirector is: " + refEighteen.musicDirector);
System.out.println("The cinematographer is: " + refEighteen.cinematographer);
System.out.println("The editor is: " + refEighteen.editor);
System.out.println("The distributor is: " + refEighteen.distributor);
System.out.println("The hasSequel is: " + refEighteen.hasSequel);
System.out.println("The hasPrequel is: " + refEighteen.hasPrequel);
System.out.println("The wonAwards is: " + refEighteen.wonAwards);
System.out.println("The rating is: " + refEighteen.rating);
System.out.println("The countryOfOrigin is: " + refEighteen.countryOfOrigin);
System.out.println("The audienceType is: " + refEighteen.audienceType);

refEighteen.movieId = 18;
refEighteen.title = "Inception";
refEighteen.director = "Christopher Nolan";
refEighteen.producer = "Emma Thomas";
refEighteen.productionCompany = "Syncopy";
refEighteen.releaseYear = 2010;
refEighteen.language = "English";
refEighteen.genre = "Science Fiction";
refEighteen.duration = 2.28;
refEighteen.budget = 160.0;
refEighteen.boxOfficeCollection = 836.0;
refEighteen.leadActor = "Leonardo DiCaprio";
refEighteen.leadActress = "Marion Cotillard";
refEighteen.supportingActor = "Joseph Gordon-Levitt";
refEighteen.supportingActress = "Elliot Page";
refEighteen.musicDirector = "Hans Zimmer";
refEighteen.cinematographer = "Wally Pfister";
refEighteen.editor = "Lee Smith";
refEighteen.distributor = "Warner Bros.";
refEighteen.hasSequel = false;
refEighteen.hasPrequel = false;
refEighteen.wonAwards = true;
refEighteen.rating = "4.8/5";
refEighteen.countryOfOrigin = "USA";
refEighteen.audienceType = "U/A";

System.out.println("The movieId is: " + refEighteen.movieId);
System.out.println("The title is: " + refEighteen.title);
System.out.println("The director is: " + refEighteen.director);
System.out.println("The producer is: " + refEighteen.producer);
System.out.println("The productionCompany is: " + refEighteen.productionCompany);
System.out.println("The releaseYear is: " + refEighteen.releaseYear);
System.out.println("The language is: " + refEighteen.language);
System.out.println("The genre is: " + refEighteen.genre);
System.out.println("The duration is: " + refEighteen.duration);
System.out.println("The budget is: " + refEighteen.budget);
System.out.println("The boxOfficeCollection is: " + refEighteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refEighteen.leadActor);
System.out.println("The leadActress is: " + refEighteen.leadActress);
System.out.println("The supportingActor is: " + refEighteen.supportingActor);
System.out.println("The supportingActress is: " + refEighteen.supportingActress);
System.out.println("The musicDirector is: " + refEighteen.musicDirector);
System.out.println("The cinematographer is: " + refEighteen.cinematographer);
System.out.println("The editor is: " + refEighteen.editor);
System.out.println("The distributor is: " + refEighteen.distributor);
System.out.println("The hasSequel is: " + refEighteen.hasSequel);
System.out.println("The hasPrequel is: " + refEighteen.hasPrequel);
System.out.println("The wonAwards is: " + refEighteen.wonAwards);
System.out.println("The rating is: " + refEighteen.rating);
System.out.println("The countryOfOrigin is: " + refEighteen.countryOfOrigin);
System.out.println("The audienceType is: " + refEighteen.audienceType);
Movie refNineteen = new Movie();

System.out.println("The movieId is: " + refNineteen.movieId);
System.out.println("The title is: " + refNineteen.title);
System.out.println("The director is: " + refNineteen.director);
System.out.println("The producer is: " + refNineteen.producer);
System.out.println("The productionCompany is: " + refNineteen.productionCompany);
System.out.println("The releaseYear is: " + refNineteen.releaseYear);
System.out.println("The language is: " + refNineteen.language);
System.out.println("The genre is: " + refNineteen.genre);
System.out.println("The duration is: " + refNineteen.duration);
System.out.println("The budget is: " + refNineteen.budget);
System.out.println("The boxOfficeCollection is: " + refNineteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refNineteen.leadActor);
System.out.println("The leadActress is: " + refNineteen.leadActress);
System.out.println("The supportingActor is: " + refNineteen.supportingActor);
System.out.println("The supportingActress is: " + refNineteen.supportingActress);
System.out.println("The musicDirector is: " + refNineteen.musicDirector);
System.out.println("The cinematographer is: " + refNineteen.cinematographer);
System.out.println("The editor is: " + refNineteen.editor);
System.out.println("The distributor is: " + refNineteen.distributor);
System.out.println("The hasSequel is: " + refNineteen.hasSequel);
System.out.println("The hasPrequel is: " + refNineteen.hasPrequel);
System.out.println("The wonAwards is: " + refNineteen.wonAwards);
System.out.println("The rating is: " + refNineteen.rating);
System.out.println("The countryOfOrigin is: " + refNineteen.countryOfOrigin);
System.out.println("The audienceType is: " + refNineteen.audienceType);

refNineteen.movieId = 19;
refNineteen.title = "The Dark Knight";
refNineteen.director = "Christopher Nolan";
refNineteen.producer = "Emma Thomas";
refNineteen.productionCompany = "Warner Bros.";
refNineteen.releaseYear = 2008;
refNineteen.language = "English";
refNineteen.genre = "Action Thriller";
refNineteen.duration = 2.32;
refNineteen.budget = 185.0;
refNineteen.boxOfficeCollection = 1004.0;
refNineteen.leadActor = "Christian Bale";
refNineteen.leadActress = "Maggie Gyllenhaal";
refNineteen.supportingActor = "Heath Ledger";
refNineteen.supportingActress = "Morgan Freeman";
refNineteen.musicDirector = "Hans Zimmer";
refNineteen.cinematographer = "Wally Pfister";
refNineteen.editor = "Lee Smith";
refNineteen.distributor = "Warner Bros.";
refNineteen.hasSequel = true;
refNineteen.hasPrequel = true;
refNineteen.wonAwards = true;
refNineteen.rating = "4.9/5";
refNineteen.countryOfOrigin = "USA";
refNineteen.audienceType = "U/A";

System.out.println("The movieId is: " + refNineteen.movieId);
System.out.println("The title is: " + refNineteen.title);
System.out.println("The director is: " + refNineteen.director);
System.out.println("The producer is: " + refNineteen.producer);
System.out.println("The productionCompany is: " + refNineteen.productionCompany);
System.out.println("The releaseYear is: " + refNineteen.releaseYear);
System.out.println("The language is: " + refNineteen.language);
System.out.println("The genre is: " + refNineteen.genre);
System.out.println("The duration is: " + refNineteen.duration);
System.out.println("The budget is: " + refNineteen.budget);
System.out.println("The boxOfficeCollection is: " + refNineteen.boxOfficeCollection);
System.out.println("The leadActor is: " + refNineteen.leadActor);
System.out.println("The leadActress is: " + refNineteen.leadActress);
System.out.println("The supportingActor is: " + refNineteen.supportingActor);
System.out.println("The supportingActress is: " + refNineteen.supportingActress);
System.out.println("The musicDirector is: " + refNineteen.musicDirector);
System.out.println("The cinematographer is: " + refNineteen.cinematographer);
System.out.println("The editor is: " + refNineteen.editor);
System.out.println("The distributor is: " + refNineteen.distributor);
System.out.println("The hasSequel is: " + refNineteen.hasSequel);
System.out.println("The hasPrequel is: " + refNineteen.hasPrequel);
System.out.println("The wonAwards is: " + refNineteen.wonAwards);
System.out.println("The rating is: " + refNineteen.rating);
System.out.println("The countryOfOrigin is: " + refNineteen.countryOfOrigin);
System.out.println("The audienceType is: " + refNineteen.audienceType);
Movie refTwenty = new Movie();

System.out.println("The movieId is: " + refTwenty.movieId);
System.out.println("The title is: " + refTwenty.title);
System.out.println("The director is: " + refTwenty.director);
System.out.println("The producer is: " + refTwenty.producer);
System.out.println("The productionCompany is: " + refTwenty.productionCompany);
System.out.println("The releaseYear is: " + refTwenty.releaseYear);
System.out.println("The language is: " + refTwenty.language);
System.out.println("The genre is: " + refTwenty.genre);
System.out.println("The duration is: " + refTwenty.duration);
System.out.println("The budget is: " + refTwenty.budget);
System.out.println("The boxOfficeCollection is: " + refTwenty.boxOfficeCollection);
System.out.println("The leadActor is: " + refTwenty.leadActor);
System.out.println("The leadActress is: " + refTwenty.leadActress);
System.out.println("The supportingActor is: " + refTwenty.supportingActor);
System.out.println("The supportingActress is: " + refTwenty.supportingActress);
System.out.println("The musicDirector is: " + refTwenty.musicDirector);
System.out.println("The cinematographer is: " + refTwenty.cinematographer);
System.out.println("The editor is: " + refTwenty.editor);
System.out.println("The distributor is: " + refTwenty.distributor);
System.out.println("The hasSequel is: " + refTwenty.hasSequel);
System.out.println("The hasPrequel is: " + refTwenty.hasPrequel);
System.out.println("The wonAwards is: " + refTwenty.wonAwards);
System.out.println("The rating is: " + refTwenty.rating);
System.out.println("The countryOfOrigin is: " + refTwenty.countryOfOrigin);
System.out.println("The audienceType is: " + refTwenty.audienceType);

refTwenty.movieId = 20;
refTwenty.title = "Titanic";
refTwenty.director = "James Cameron";
refTwenty.producer = "James Cameron";
refTwenty.productionCompany = "20th Century Fox";
refTwenty.releaseYear = 1997;
refTwenty.language = "English";
refTwenty.genre = "Romance Drama";
refTwenty.duration = 3.14;
refTwenty.budget = 200.0;
refTwenty.boxOfficeCollection = 2264.0;
refTwenty.leadActor = "Leonardo DiCaprio";
refTwenty.leadActress = "Kate Winslet";
refTwenty.supportingActor = "Billy Zane";
refTwenty.supportingActress = "Gloria Stuart";
refTwenty.musicDirector = "James Horner";
refTwenty.cinematographer = "Russell Carpenter";
refTwenty.editor = "Conrad Buff";
refTwenty.distributor = "Paramount Pictures";
refTwenty.hasSequel = false;
refTwenty.hasPrequel = false;
refTwenty.wonAwards = true;
refTwenty.rating = "4.8/5";
refTwenty.countryOfOrigin = "USA";
refTwenty.audienceType = "U/A";

System.out.println("The movieId is: " + refTwenty.movieId);
System.out.println("The title is: " + refTwenty.title);
System.out.println("The director is: " + refTwenty.director);
System.out.println("The producer is: " + refTwenty.producer);
System.out.println("The productionCompany is: " + refTwenty.productionCompany);
System.out.println("The releaseYear is: " + refTwenty.releaseYear);
System.out.println("The language is: " + refTwenty.language);
System.out.println("The genre is: " + refTwenty.genre);
System.out.println("The duration is: " + refTwenty.duration);
System.out.println("The budget is: " + refTwenty.budget);
System.out.println("The boxOfficeCollection is: " + refTwenty.boxOfficeCollection);
System.out.println("The leadActor is: " + refTwenty.leadActor);
System.out.println("The leadActress is: " + refTwenty.leadActress);
System.out.println("The supportingActor is: " + refTwenty.supportingActor);
System.out.println("The supportingActress is: " + refTwenty.supportingActress);
System.out.println("The musicDirector is: " + refTwenty.musicDirector);
System.out.println("The cinematographer is: " + refTwenty.cinematographer);
System.out.println("The editor is: " + refTwenty.editor);
System.out.println("The distributor is: " + refTwenty.distributor);
System.out.println("The hasSequel is: " + refTwenty.hasSequel);
System.out.println("The hasPrequel is: " + refTwenty.hasPrequel);
System.out.println("The wonAwards is: " + refTwenty.wonAwards);
System.out.println("The rating is: " + refTwenty.rating);
System.out.println("The countryOfOrigin is: " + refTwenty.countryOfOrigin);
System.out.println("The audienceType is: " + refTwenty.audienceType);
}
}