class NutritionExecutor {
    public static void main(String[] args) {

        NutritionTable n1 = new NutritionTable();
        n1.setNutritionId(1);
        n1.setFoodName("Rice");
        n1.setCalories(130);
        n1.setProtein(2.7);
        n1.setCarbs(28);
        n1.setFats(0.3);
        n1.setServingSize("100g");
        System.out.println(n1.getNutritionId());
        System.out.println(n1.getFoodName());
        System.out.println(n1.getCalories());
        System.out.println(n1.getProtein());
        System.out.println(n1.getCarbs());
        System.out.println(n1.getFats());
        System.out.println(n1.getServingSize());

        NutritionTable n2 = new NutritionTable();
        n2.setNutritionId(2);
        n2.setFoodName("Idli");
        n2.setCalories(58);
        n2.setProtein(2);
        n2.setCarbs(12);
        n2.setFats(0.4);
        n2.setServingSize("1 piece");
        System.out.println(n2.getNutritionId());
        System.out.println(n2.getFoodName());
        System.out.println(n2.getCalories());
        System.out.println(n2.getProtein());
        System.out.println(n2.getCarbs());
        System.out.println(n2.getFats());
        System.out.println(n2.getServingSize());

        NutritionTable n3 = new NutritionTable();
        n3.setNutritionId(3);
        n3.setFoodName("Dosa");
        n3.setCalories(168);
        n3.setProtein(3.9);
        n3.setCarbs(27);
        n3.setFats(3.7);
        n3.setServingSize("1 piece");
        System.out.println(n3.getNutritionId());
        System.out.println(n3.getFoodName());
        System.out.println(n3.getCalories());
        System.out.println(n3.getProtein());
        System.out.println(n3.getCarbs());
        System.out.println(n3.getFats());
        System.out.println(n3.getServingSize());

        NutritionTable n4 = new NutritionTable();
        n4.setNutritionId(4);
        n4.setFoodName("Chapati");
        n4.setCalories(104);
        n4.setProtein(3);
        n4.setCarbs(18);
        n4.setFats(1.5);
        n4.setServingSize("1 piece");
        System.out.println(n4.getNutritionId());
        System.out.println(n4.getFoodName());
        System.out.println(n4.getCalories());
        System.out.println(n4.getProtein());
        System.out.println(n4.getCarbs());
        System.out.println(n4.getFats());
        System.out.println(n4.getServingSize());

        NutritionTable n5 = new NutritionTable();
        n5.setNutritionId(5);
        n5.setFoodName("Egg");
        n5.setCalories(155);
        n5.setProtein(13);
        n5.setCarbs(1.1);
        n5.setFats(11);
        n5.setServingSize("1 piece");
        System.out.println(n5.getNutritionId());
        System.out.println(n5.getFoodName());
        System.out.println(n5.getCalories());
        System.out.println(n5.getProtein());
        System.out.println(n5.getCarbs());
        System.out.println(n5.getFats());
        System.out.println(n5.getServingSize());

        NutritionTable n6 = new NutritionTable();
        n6.setNutritionId(6);
        n6.setFoodName("Milk");
        n6.setCalories(42);
        n6.setProtein(3.4);
        n6.setCarbs(5);
        n6.setFats(1);
        n6.setServingSize("100ml");
        System.out.println(n6.getNutritionId());
        System.out.println(n6.getFoodName());
        System.out.println(n6.getCalories());
        System.out.println(n6.getProtein());
        System.out.println(n6.getCarbs());
        System.out.println(n6.getFats());
        System.out.println(n6.getServingSize());

        NutritionTable n7 = new NutritionTable();
        n7.setNutritionId(7);
        n7.setFoodName("Banana");
        n7.setCalories(89);
        n7.setProtein(1.1);
        n7.setCarbs(23);
        n7.setFats(0.3);
        n7.setServingSize("1 piece");
        System.out.println(n7.getNutritionId());
        System.out.println(n7.getFoodName());
        System.out.println(n7.getCalories());
        System.out.println(n7.getProtein());
        System.out.println(n7.getCarbs());
        System.out.println(n7.getFats());
        System.out.println(n7.getServingSize());

        NutritionTable n8 = new NutritionTable();
        n8.setNutritionId(8);
        n8.setFoodName("Apple");
        n8.setCalories(52);
        n8.setProtein(0.3);
        n8.setCarbs(14);
        n8.setFats(0.2);
        n8.setServingSize("1 piece");
        System.out.println(n8.getNutritionId());
        System.out.println(n8.getFoodName());
        System.out.println(n8.getCalories());
        System.out.println(n8.getProtein());
        System.out.println(n8.getCarbs());
        System.out.println(n8.getFats());
        System.out.println(n8.getServingSize());

        NutritionTable n9 = new NutritionTable();
        n9.setNutritionId(9);
        n9.setFoodName("Chicken");
        n9.setCalories(239);
        n9.setProtein(27);
        n9.setCarbs(0);
        n9.setFats(14);
        n9.setServingSize("100g");
        System.out.println(n9.getNutritionId());
        System.out.println(n9.getFoodName());
        System.out.println(n9.getCalories());
        System.out.println(n9.getProtein());
        System.out.println(n9.getCarbs());
        System.out.println(n9.getFats());
        System.out.println(n9.getServingSize());

        NutritionTable n10 = new NutritionTable();
        n10.setNutritionId(10);
        n10.setFoodName("Fish");
        n10.setCalories(206);
        n10.setProtein(22);
        n10.setCarbs(0);
        n10.setFats(12);
        n10.setServingSize("100g");
        System.out.println(n10.getNutritionId());
        System.out.println(n10.getFoodName());
        System.out.println(n10.getCalories());
        System.out.println(n10.getProtein());
        System.out.println(n10.getCarbs());
        System.out.println(n10.getFats());
        System.out.println(n10.getServingSize());

        NutritionTable n11 = new NutritionTable();
        n11.setNutritionId(11);
        n11.setFoodName("Paneer");
        n11.setCalories(265);
        n11.setProtein(18);
        n11.setCarbs(1.2);
        n11.setFats(20);
        n11.setServingSize("100g");
        System.out.println(n11.getNutritionId());
        System.out.println(n11.getFoodName());
        System.out.println(n11.getCalories());
        System.out.println(n11.getProtein());
        System.out.println(n11.getCarbs());
        System.out.println(n11.getFats());
        System.out.println(n11.getServingSize());

        NutritionTable n12 = new NutritionTable();
        n12.setNutritionId(12);
        n12.setFoodName("Dal");
        n12.setCalories(116);
        n12.setProtein(9);
        n12.setCarbs(20);
        n12.setFats(0.4);
        n12.setServingSize("100g");
        System.out.println(n12.getNutritionId());
        System.out.println(n12.getFoodName());
        System.out.println(n12.getCalories());
        System.out.println(n12.getProtein());
        System.out.println(n12.getCarbs());
        System.out.println(n12.getFats());
        System.out.println(n12.getServingSize());

        NutritionTable n13 = new NutritionTable();
        n13.setNutritionId(13);
        n13.setFoodName("Curd");
        n13.setCalories(98);
        n13.setProtein(11);
        n13.setCarbs(3.4);
        n13.setFats(4.3);
        n13.setServingSize("100g");
        System.out.println(n13.getNutritionId());
        System.out.println(n13.getFoodName());
        System.out.println(n13.getCalories());
        System.out.println(n13.getProtein());
        System.out.println(n13.getCarbs());
        System.out.println(n13.getFats());
        System.out.println(n13.getServingSize());

        NutritionTable n14 = new NutritionTable();
        n14.setNutritionId(14);
        n14.setFoodName("Bread");
        n14.setCalories(265);
        n14.setProtein(9);
        n14.setCarbs(49);
        n14.setFats(3.2);
        n14.setServingSize("2 slices");
        System.out.println(n14.getNutritionId());
        System.out.println(n14.getFoodName());
        System.out.println(n14.getCalories());
        System.out.println(n14.getProtein());
        System.out.println(n14.getCarbs());
        System.out.println(n14.getFats());
        System.out.println(n14.getServingSize());

        NutritionTable n15 = new NutritionTable();
        n15.setNutritionId(15);
        n15.setFoodName("Butter");
        n15.setCalories(717);
        n15.setProtein(0.9);
        n15.setCarbs(0.1);
        n15.setFats(81);
        n15.setServingSize("100g");
        System.out.println(n15.getNutritionId());
        System.out.println(n15.getFoodName());
        System.out.println(n15.getCalories());
        System.out.println(n15.getProtein());
        System.out.println(n15.getCarbs());
        System.out.println(n15.getFats());
        System.out.println(n15.getServingSize());

        NutritionTable n16 = new NutritionTable();
        n16.setNutritionId(16);
        n16.setFoodName("Cheese");
        n16.setCalories(402);
        n16.setProtein(25);
        n16.setCarbs(1.3);
        n16.setFats(33);
        n16.setServingSize("100g");
        System.out.println(n16.getNutritionId());
        System.out.println(n16.getFoodName());
        System.out.println(n16.getCalories());
        System.out.println(n16.getProtein());
        System.out.println(n16.getCarbs());
        System.out.println(n16.getFats());
        System.out.println(n16.getServingSize());

        NutritionTable n17 = new NutritionTable();
        n17.setNutritionId(17);
        n17.setFoodName("Orange");
        n17.setCalories(47);
        n17.setProtein(0.9);
        n17.setCarbs(12);
        n17.setFats(0.1);
        n17.setServingSize("1 piece");
        System.out.println(n17.getNutritionId());
        System.out.println(n17.getFoodName());
        System.out.println(n17.getCalories());
        System.out.println(n17.getProtein());
        System.out.println(n17.getCarbs());
        System.out.println(n17.getFats());
        System.out.println(n17.getServingSize());

        NutritionTable n18 = new NutritionTable();
        n18.setNutritionId(18);
        n18.setFoodName("Mango");
        n18.setCalories(60);
        n18.setProtein(0.8);
        n18.setCarbs(15);
        n18.setFats(0.4);
        n18.setServingSize("1 piece");
        System.out.println(n18.getNutritionId());
        System.out.println(n18.getFoodName());
        System.out.println(n18.getCalories());
        System.out.println(n18.getProtein());
        System.out.println(n18.getCarbs());
        System.out.println(n18.getFats());
        System.out.println(n18.getServingSize());

        NutritionTable n19 = new NutritionTable();
        n19.setNutritionId(19);
        n19.setFoodName("Potato");
        n19.setCalories(77);
        n19.setProtein(2);
        n19.setCarbs(17);
        n19.setFats(0.1);
        n19.setServingSize("100g");
        System.out.println(n19.getNutritionId());
        System.out.println(n19.getFoodName());
        System.out.println(n19.getCalories());
        System.out.println(n19.getProtein());
        System.out.println(n19.getCarbs());
        System.out.println(n19.getFats());
        System.out.println(n19.getServingSize());

        NutritionTable n20 = new NutritionTable();
        n20.setNutritionId(20);
        n20.setFoodName("Carrot");
        n20.setCalories(41);
        n20.setProtein(0.9);
        n20.setCarbs(10);
        n20.setFats(0.2);
        n20.setServingSize("100g");
        System.out.println(n20.getNutritionId());
        System.out.println(n20.getFoodName());
        System.out.println(n20.getCalories());
        System.out.println(n20.getProtein());
        System.out.println(n20.getCarbs());
        System.out.println(n20.getFats());
        System.out.println(n20.getServingSize());

        NutritionTable n21 = new NutritionTable();
        n21.setNutritionId(21);
        n21.setFoodName("Tomato");
        n21.setCalories(18);
        n21.setProtein(0.9);
        n21.setCarbs(3.9);
        n21.setFats(0.2);
        n21.setServingSize("100g");
        System.out.println(n21.getNutritionId());
        System.out.println(n21.getFoodName());
        System.out.println(n21.getCalories());
        System.out.println(n21.getProtein());
        System.out.println(n21.getCarbs());
        System.out.println(n21.getFats());
        System.out.println(n21.getServingSize());

        NutritionTable n22 = new NutritionTable();
        n22.setNutritionId(22);
        n22.setFoodName("Cucumber");
        n22.setCalories(16);
        n22.setProtein(0.7);
        n22.setCarbs(3.6);
        n22.setFats(0.1);
        n22.setServingSize("100g");
        System.out.println(n22.getNutritionId());
        System.out.println(n22.getFoodName());
        System.out.println(n22.getCalories());
        System.out.println(n22.getProtein());
        System.out.println(n22.getCarbs());
        System.out.println(n22.getFats());
        System.out.println(n22.getServingSize());

        NutritionTable n23 = new NutritionTable();
        n23.setNutritionId(23);
        n23.setFoodName("Spinach");
        n23.setCalories(23);
        n23.setProtein(2.9);
        n23.setCarbs(3.6);
        n23.setFats(0.4);
        n23.setServingSize("100g");
        System.out.println(n23.getNutritionId());
        System.out.println(n23.getFoodName());
        System.out.println(n23.getCalories());
        System.out.println(n23.getProtein());
        System.out.println(n23.getCarbs());
        System.out.println(n23.getFats());
        System.out.println(n23.getServingSize());

        NutritionTable n24 = new NutritionTable();
        n24.setNutritionId(24);
        n24.setFoodName("Oats");
        n24.setCalories(389);
        n24.setProtein(17);
        n24.setCarbs(66);
        n24.setFats(7);
        n24.setServingSize("100g");
        System.out.println(n24.getNutritionId());
        System.out.println(n24.getFoodName());
        System.out.println(n24.getCalories());
        System.out.println(n24.getProtein());
        System.out.println(n24.getCarbs());
        System.out.println(n24.getFats());
        System.out.println(n24.getServingSize());

        NutritionTable n25 = new NutritionTable();
        n25.setNutritionId(25);
        n25.setFoodName("Corn");
        n25.setCalories(86);
        n25.setProtein(3.2);
        n25.setCarbs(19);
        n25.setFats(1.2);
        n25.setServingSize("100g");
        System.out.println(n25.getNutritionId());
        System.out.println(n25.getFoodName());
        System.out.println(n25.getCalories());
        System.out.println(n25.getProtein());
        System.out.println(n25.getCarbs());
        System.out.println(n25.getFats());
        System.out.println(n25.getServingSize());

        NutritionTable n26 = new NutritionTable();
        n26.setNutritionId(26);
        n26.setFoodName("Peanuts");
        n26.setCalories(567);
        n26.setProtein(26);
        n26.setCarbs(16);
        n26.setFats(49);
        n26.setServingSize("100g");
        System.out.println(n26.getNutritionId());
        System.out.println(n26.getFoodName());
        System.out.println(n26.getCalories());
        System.out.println(n26.getProtein());
        System.out.println(n26.getCarbs());
        System.out.println(n26.getFats());
        System.out.println(n26.getServingSize());

        NutritionTable n27 = new NutritionTable();
        n27.setNutritionId(27);
        n27.setFoodName("Almonds");
        n27.setCalories(579);
        n27.setProtein(21);
        n27.setCarbs(22);
        n27.setFats(50);
        n27.setServingSize("100g");
        System.out.println(n27.getNutritionId());
        System.out.println(n27.getFoodName());
        System.out.println(n27.getCalories());
        System.out.println(n27.getProtein());
        System.out.println(n27.getCarbs());
        System.out.println(n27.getFats());
        System.out.println(n27.getServingSize());

        NutritionTable n28 = new NutritionTable();
        n28.setNutritionId(28);
        n28.setFoodName("Cashew");
        n28.setCalories(553);
        n28.setProtein(18);
        n28.setCarbs(30);
        n28.setFats(44);
        n28.setServingSize("100g");
        System.out.println(n28.getNutritionId());
        System.out.println(n28.getFoodName());
        System.out.println(n28.getCalories());
        System.out.println(n28.getProtein());
        System.out.println(n28.getCarbs());
        System.out.println(n28.getFats());
        System.out.println(n28.getServingSize());

        NutritionTable n29 = new NutritionTable();
        n29.setNutritionId(29);
        n29.setFoodName("Walnut");
        n29.setCalories(654);
        n29.setProtein(15);
        n29.setCarbs(14);
        n29.setFats(65);
        n29.setServingSize("100g");
        System.out.println(n29.getNutritionId());
        System.out.println(n29.getFoodName());
        System.out.println(n29.getCalories());
        System.out.println(n29.getProtein());
        System.out.println(n29.getCarbs());
        System.out.println(n29.getFats());
        System.out.println(n29.getServingSize());
    }
}