class PatientExecutor {
    public static void main(String[] args) {

        Patient p1 = new Patient();
        p1.setPatientId(1);
        p1.setName("Patient1");
        p1.setAge(21);
        p1.setGender("Male");
        p1.setDisease("Fever");
        p1.setDoctorName("Doctor1");
        p1.setAdmissionDate("2024-01-01");
        System.out.println(p1.getPatientId());
        System.out.println(p1.getName());
        System.out.println(p1.getAge());
        System.out.println(p1.getGender());
        System.out.println(p1.getDisease());
        System.out.println(p1.getDoctorName());
        System.out.println(p1.getAdmissionDate());

        Patient p2 = new Patient();
        p2.setPatientId(2);
        p2.setName("Patient2");
        p2.setAge(22);
        p2.setGender("Female");
        p2.setDisease("Cold");
        p2.setDoctorName("Doctor2");
        p2.setAdmissionDate("2024-01-02");
        System.out.println(p2.getPatientId());
        System.out.println(p2.getName());
        System.out.println(p2.getAge());
        System.out.println(p2.getGender());
        System.out.println(p2.getDisease());
        System.out.println(p2.getDoctorName());
        System.out.println(p2.getAdmissionDate());

        Patient p3 = new Patient();
        p3.setPatientId(3);
        p3.setName("Patient3");
        p3.setAge(23);
        p3.setGender("Male");
        p3.setDisease("Headache");
        p3.setDoctorName("Doctor3");
        p3.setAdmissionDate("2024-01-03");
        System.out.println(p3.getPatientId());
        System.out.println(p3.getName());
        System.out.println(p3.getAge());
        System.out.println(p3.getGender());
        System.out.println(p3.getDisease());
        System.out.println(p3.getDoctorName());
        System.out.println(p3.getAdmissionDate());

        Patient p4 = new Patient();
        p4.setPatientId(4);
        p4.setName("Patient4");
        p4.setAge(24);
        p4.setGender("Female");
        p4.setDisease("Cough");
        p4.setDoctorName("Doctor4");
        p4.setAdmissionDate("2024-01-04");
        System.out.println(p4.getPatientId());
        System.out.println(p4.getName());
        System.out.println(p4.getAge());
        System.out.println(p4.getGender());
        System.out.println(p4.getDisease());
        System.out.println(p4.getDoctorName());
        System.out.println(p4.getAdmissionDate());

        Patient p5 = new Patient();
        p5.setPatientId(5);
        p5.setName("Patient5");
        p5.setAge(25);
        p5.setGender("Male");
        p5.setDisease("Fever");
        p5.setDoctorName("Doctor5");
        p5.setAdmissionDate("2024-01-05");
        System.out.println(p5.getPatientId());
        System.out.println(p5.getName());
        System.out.println(p5.getAge());
        System.out.println(p5.getGender());
        System.out.println(p5.getDisease());
        System.out.println(p5.getDoctorName());
        System.out.println(p5.getAdmissionDate());

        Patient p6 = new Patient();
        p6.setPatientId(6);
        p6.setName("Patient6");
        p6.setAge(26);
        p6.setGender("Female");
        p6.setDisease("Cold");
        p6.setDoctorName("Doctor6");
        p6.setAdmissionDate("2024-01-06");
        System.out.println(p6.getPatientId());
        System.out.println(p6.getName());
        System.out.println(p6.getAge());
        System.out.println(p6.getGender());
        System.out.println(p6.getDisease());
        System.out.println(p6.getDoctorName());
        System.out.println(p6.getAdmissionDate());

        Patient p7 = new Patient();
        p7.setPatientId(7);
        p7.setName("Patient7");
        p7.setAge(27);
        p7.setGender("Male");
        p7.setDisease("Headache");
        p7.setDoctorName("Doctor7");
        p7.setAdmissionDate("2024-01-07");
        System.out.println(p7.getPatientId());
        System.out.println(p7.getName());
        System.out.println(p7.getAge());
        System.out.println(p7.getGender());
        System.out.println(p7.getDisease());
        System.out.println(p7.getDoctorName());
        System.out.println(p7.getAdmissionDate());

        Patient p8 = new Patient();
        p8.setPatientId(8);
        p8.setName("Patient8");
        p8.setAge(28);
        p8.setGender("Female");
        p8.setDisease("Cough");
        p8.setDoctorName("Doctor8");
        p8.setAdmissionDate("2024-01-08");
        System.out.println(p8.getPatientId());
        System.out.println(p8.getName());
        System.out.println(p8.getAge());
        System.out.println(p8.getGender());
        System.out.println(p8.getDisease());
        System.out.println(p8.getDoctorName());
        System.out.println(p8.getAdmissionDate());

        Patient p9 = new Patient();
        p9.setPatientId(9);
        p9.setName("Patient9");
        p9.setAge(29);
        p9.setGender("Male");
        p9.setDisease("Fever");
        p9.setDoctorName("Doctor9");
        p9.setAdmissionDate("2024-01-09");
        System.out.println(p9.getPatientId());
        System.out.println(p9.getName());
        System.out.println(p9.getAge());
        System.out.println(p9.getGender());
        System.out.println(p9.getDisease());
        System.out.println(p9.getDoctorName());
        System.out.println(p9.getAdmissionDate());

        Patient p10 = new Patient();
        p10.setPatientId(10);
        p10.setName("Patient10");
        p10.setAge(30);
        p10.setGender("Female");
        p10.setDisease("Cold");
        p10.setDoctorName("Doctor10");
        p10.setAdmissionDate("2024-01-10");
        System.out.println(p10.getPatientId());
        System.out.println(p10.getName());
        System.out.println(p10.getAge());
        System.out.println(p10.getGender());
        System.out.println(p10.getDisease());
        System.out.println(p10.getDoctorName());
        System.out.println(p10.getAdmissionDate());

        Patient p11 = new Patient();
        p11.setPatientId(11);
        p11.setName("Patient11");
        p11.setAge(31);
        p11.setGender("Male");
        p11.setDisease("Headache");
        p11.setDoctorName("Doctor11");
        p11.setAdmissionDate("2024-01-11");
        System.out.println(p11.getPatientId());
        System.out.println(p11.getName());
        System.out.println(p11.getAge());
        System.out.println(p11.getGender());
        System.out.println(p11.getDisease());
        System.out.println(p11.getDoctorName());
        System.out.println(p11.getAdmissionDate());

        Patient p12 = new Patient();
        p12.setPatientId(12);
        p12.setName("Patient12");
        p12.setAge(32);
        p12.setGender("Female");
        p12.setDisease("Cough");
        p12.setDoctorName("Doctor12");
        p12.setAdmissionDate("2024-01-12");
        System.out.println(p12.getPatientId());
        System.out.println(p12.getName());
        System.out.println(p12.getAge());
        System.out.println(p12.getGender());
        System.out.println(p12.getDisease());
        System.out.println(p12.getDoctorName());
        System.out.println(p12.getAdmissionDate());

        Patient p13 = new Patient();
        p13.setPatientId(13);
        p13.setName("Patient13");
        p13.setAge(33);
        p13.setGender("Male");
        p13.setDisease("Fever");
        p13.setDoctorName("Doctor13");
        p13.setAdmissionDate("2024-01-13");
        System.out.println(p13.getPatientId());
        System.out.println(p13.getName());
        System.out.println(p13.getAge());
        System.out.println(p13.getGender());
        System.out.println(p13.getDisease());
        System.out.println(p13.getDoctorName());
        System.out.println(p13.getAdmissionDate());

        Patient p14 = new Patient();
        p14.setPatientId(14);
        p14.setName("Patient14");
        p14.setAge(34);
        p14.setGender("Female");
        p14.setDisease("Cold");
        p14.setDoctorName("Doctor14");
        p14.setAdmissionDate("2024-01-14");
        System.out.println(p14.getPatientId());
        System.out.println(p14.getName());
        System.out.println(p14.getAge());
        System.out.println(p14.getGender());
        System.out.println(p14.getDisease());
        System.out.println(p14.getDoctorName());
        System.out.println(p14.getAdmissionDate());

        Patient p15 = new Patient();
        p15.setPatientId(15);
        p15.setName("Patient15");
        p15.setAge(35);
        p15.setGender("Male");
        p15.setDisease("Headache");
        p15.setDoctorName("Doctor15");
        p15.setAdmissionDate("2024-01-15");
        System.out.println(p15.getPatientId());
        System.out.println(p15.getName());
        System.out.println(p15.getAge());
        System.out.println(p15.getGender());
        System.out.println(p15.getDisease());
        System.out.println(p15.getDoctorName());
        System.out.println(p15.getAdmissionDate());

        Patient p16 = new Patient();
        p16.setPatientId(16);
        p16.setName("Patient16");
        p16.setAge(36);
        p16.setGender("Female");
        p16.setDisease("Cough");
        p16.setDoctorName("Doctor16");
        p16.setAdmissionDate("2024-01-16");
        System.out.println(p16.getPatientId());
        System.out.println(p16.getName());
        System.out.println(p16.getAge());
        System.out.println(p16.getGender());
        System.out.println(p16.getDisease());
        System.out.println(p16.getDoctorName());
        System.out.println(p16.getAdmissionDate());

        Patient p17 = new Patient();
        p17.setPatientId(17);
        p17.setName("Patient17");
        p17.setAge(37);
        p17.setGender("Male");
        p17.setDisease("Fever");
        p17.setDoctorName("Doctor17");
        p17.setAdmissionDate("2024-01-17");
        System.out.println(p17.getPatientId());
        System.out.println(p17.getName());
        System.out.println(p17.getAge());
        System.out.println(p17.getGender());
        System.out.println(p17.getDisease());
        System.out.println(p17.getDoctorName());
        System.out.println(p17.getAdmissionDate());

        Patient p18 = new Patient();
        p18.setPatientId(18);
        p18.setName("Patient18");
        p18.setAge(38);
        p18.setGender("Female");
        p18.setDisease("Cold");
        p18.setDoctorName("Doctor18");
        p18.setAdmissionDate("2024-01-18");
        System.out.println(p18.getPatientId());
        System.out.println(p18.getName());
        System.out.println(p18.getAge());
        System.out.println(p18.getGender());
        System.out.println(p18.getDisease());
        System.out.println(p18.getDoctorName());
        System.out.println(p18.getAdmissionDate());

        Patient p19 = new Patient();
        p19.setPatientId(19);
        p19.setName("Patient19");
        p19.setAge(39);
        p19.setGender("Male");
        p19.setDisease("Headache");
        p19.setDoctorName("Doctor19");
        p19.setAdmissionDate("2024-01-19");
        System.out.println(p19.getPatientId());
        System.out.println(p19.getName());
        System.out.println(p19.getAge());
        System.out.println(p19.getGender());
        System.out.println(p19.getDisease());
        System.out.println(p19.getDoctorName());
        System.out.println(p19.getAdmissionDate());

        Patient p20 = new Patient();
        p20.setPatientId(20);
        p20.setName("Patient20");
        p20.setAge(40);
        p20.setGender("Female");
        p20.setDisease("Cough");
        p20.setDoctorName("Doctor20");
        p20.setAdmissionDate("2024-01-20");
        System.out.println(p20.getPatientId());
        System.out.println(p20.getName());
        System.out.println(p20.getAge());
        System.out.println(p20.getGender());
        System.out.println(p20.getDisease());
        System.out.println(p20.getDoctorName());
        System.out.println(p20.getAdmissionDate());

        Patient p21 = new Patient();
        p21.setPatientId(21);
        p21.setName("Patient21");
        p21.setAge(41);
        p21.setGender("Male");
        p21.setDisease("Fever");
        p21.setDoctorName("Doctor21");
        p21.setAdmissionDate("2024-01-21");
        System.out.println(p21.getPatientId());
        System.out.println(p21.getName());
        System.out.println(p21.getAge());
        System.out.println(p21.getGender());
        System.out.println(p21.getDisease());
        System.out.println(p21.getDoctorName());
        System.out.println(p21.getAdmissionDate());

        Patient p22 = new Patient();
        p22.setPatientId(22);
        p22.setName("Patient22");
        p22.setAge(42);
        p22.setGender("Female");
        p22.setDisease("Cold");
        p22.setDoctorName("Doctor22");
        p22.setAdmissionDate("2024-01-22");
        System.out.println(p22.getPatientId());
        System.out.println(p22.getName());
        System.out.println(p22.getAge());
        System.out.println(p22.getGender());
        System.out.println(p22.getDisease());
        System.out.println(p22.getDoctorName());
        System.out.println(p22.getAdmissionDate());

        Patient p23 = new Patient();
        p23.setPatientId(23);
        p23.setName("Patient23");
        p23.setAge(43);
        p23.setGender("Male");
        p23.setDisease("Headache");
        p23.setDoctorName("Doctor23");
        p23.setAdmissionDate("2024-01-23");
        System.out.println(p23.getPatientId());
        System.out.println(p23.getName());
        System.out.println(p23.getAge());
        System.out.println(p23.getGender());
        System.out.println(p23.getDisease());
        System.out.println(p23.getDoctorName());
        System.out.println(p23.getAdmissionDate());

        Patient p24 = new Patient();
        p24.setPatientId(24);
        p24.setName("Patient24");
        p24.setAge(44);
        p24.setGender("Female");
        p24.setDisease("Cough");
        p24.setDoctorName("Doctor24");
        p24.setAdmissionDate("2024-01-24");
        System.out.println(p24.getPatientId());
        System.out.println(p24.getName());
        System.out.println(p24.getAge());
        System.out.println(p24.getGender());
        System.out.println(p24.getDisease());
        System.out.println(p24.getDoctorName());
        System.out.println(p24.getAdmissionDate());

        Patient p25 = new Patient();
        p25.setPatientId(25);
        p25.setName("Patient25");
        p25.setAge(45);
        p25.setGender("Male");
        p25.setDisease("Fever");
        p25.setDoctorName("Doctor25");
        p25.setAdmissionDate("2024-01-25");
        System.out.println(p25.getPatientId());
        System.out.println(p25.getName());
        System.out.println(p25.getAge());
        System.out.println(p25.getGender());
        System.out.println(p25.getDisease());
        System.out.println(p25.getDoctorName());
        System.out.println(p25.getAdmissionDate());

        Patient p26 = new Patient();
        p26.setPatientId(26);
        p26.setName("Patient26");
        p26.setAge(46);
        p26.setGender("Female");
        p26.setDisease("Cold");
        p26.setDoctorName("Doctor26");
        p26.setAdmissionDate("2024-01-26");
        System.out.println(p26.getPatientId());
        System.out.println(p26.getName());
        System.out.println(p26.getAge());
        System.out.println(p26.getGender());
        System.out.println(p26.getDisease());
        System.out.println(p26.getDoctorName());
        System.out.println(p26.getAdmissionDate());

        Patient p27 = new Patient();
        p27.setPatientId(27);
        p27.setName("Patient27");
        p27.setAge(47);
        p27.setGender("Male");
        p27.setDisease("Headache");
        p27.setDoctorName("Doctor27");
        p27.setAdmissionDate("2024-01-27");
        System.out.println(p27.getPatientId());
        System.out.println(p27.getName());
        System.out.println(p27.getAge());
        System.out.println(p27.getGender());
        System.out.println(p27.getDisease());
        System.out.println(p27.getDoctorName());
        System.out.println(p27.getAdmissionDate());

        Patient p28 = new Patient();
        p28.setPatientId(28);
        p28.setName("Patient28");
        p28.setAge(48);
        p28.setGender("Female");
        p28.setDisease("Cough");
        p28.setDoctorName("Doctor28");
        p28.setAdmissionDate("2024-01-28");
        System.out.println(p28.getPatientId());
        System.out.println(p28.getName());
        System.out.println(p28.getAge());
        System.out.println(p28.getGender());
        System.out.println(p28.getDisease());
        System.out.println(p28.getDoctorName());
        System.out.println(p28.getAdmissionDate());

        Patient p29 = new Patient();
        p29.setPatientId(29);
        p29.setName("Patient29");
        p29.setAge(49);
        p29.setGender("Male");
        p29.setDisease("Fever");
        p29.setDoctorName("Doctor29");
        p29.setAdmissionDate("2024-01-29");
        System.out.println(p29.getPatientId());
        System.out.println(p29.getName());
        System.out.println(p29.getAge());
        System.out.println(p29.getGender());
        System.out.println(p29.getDisease());
        System.out.println(p29.getDoctorName());
        System.out.println(p29.getAdmissionDate());
    }
}