class PlayerExecutor {
    public static void main(String[] args) {

        Player p1 = new Player();
        p1.setPlayerId(1);
        p1.setPlayerName("Player1");
        p1.setSport("Cricket");
        p1.setTeam("Team1");
        p1.setAge(21);
        p1.setSalary(10000);
        p1.setCountry("India");
        System.out.println(p1.getPlayerId());
        System.out.println(p1.getPlayerName());
        System.out.println(p1.getSport());
        System.out.println(p1.getTeam());
        System.out.println(p1.getAge());
        System.out.println(p1.getSalary());
        System.out.println(p1.getCountry());

        Player p2 = new Player();
        p2.setPlayerId(2);
        p2.setPlayerName("Player2");
        p2.setSport("Football");
        p2.setTeam("Team2");
        p2.setAge(22);
        p2.setSalary(20000);
        p2.setCountry("Brazil");
        System.out.println(p2.getPlayerId());
        System.out.println(p2.getPlayerName());
        System.out.println(p2.getSport());
        System.out.println(p2.getTeam());
        System.out.println(p2.getAge());
        System.out.println(p2.getSalary());
        System.out.println(p2.getCountry());

        Player p3 = new Player();
        p3.setPlayerId(3);
        p3.setPlayerName("Player3");
        p3.setSport("Tennis");
        p3.setTeam("Team3");
        p3.setAge(23);
        p3.setSalary(30000);
        p3.setCountry("Spain");
        System.out.println(p3.getPlayerId());
        System.out.println(p3.getPlayerName());
        System.out.println(p3.getSport());
        System.out.println(p3.getTeam());
        System.out.println(p3.getAge());
        System.out.println(p3.getSalary());
        System.out.println(p3.getCountry());

        Player p4 = new Player();
        p4.setPlayerId(4);
        p4.setPlayerName("Player4");
        p4.setSport("Cricket");
        p4.setTeam("Team4");
        p4.setAge(24);
        p4.setSalary(40000);
        p4.setCountry("India");
        System.out.println(p4.getPlayerId());
        System.out.println(p4.getPlayerName());
        System.out.println(p4.getSport());
        System.out.println(p4.getTeam());
        System.out.println(p4.getAge());
        System.out.println(p4.getSalary());
        System.out.println(p4.getCountry());

        Player p5 = new Player();
        p5.setPlayerId(5);
        p5.setPlayerName("Player5");
        p5.setSport("Football");
        p5.setTeam("Team5");
        p5.setAge(25);
        p5.setSalary(50000);
        p5.setCountry("Argentina");
        System.out.println(p5.getPlayerId());
        System.out.println(p5.getPlayerName());
        System.out.println(p5.getSport());
        System.out.println(p5.getTeam());
        System.out.println(p5.getAge());
        System.out.println(p5.getSalary());
        System.out.println(p5.getCountry());

        Player p6 = new Player();
        p6.setPlayerId(6);
        p6.setPlayerName("Player6");
        p6.setSport("Tennis");
        p6.setTeam("Team6");
        p6.setAge(26);
        p6.setSalary(60000);
        p6.setCountry("USA");
        System.out.println(p6.getPlayerId());
        System.out.println(p6.getPlayerName());
        System.out.println(p6.getSport());
        System.out.println(p6.getTeam());
        System.out.println(p6.getAge());
        System.out.println(p6.getSalary());
        System.out.println(p6.getCountry());

        Player p7 = new Player();
        p7.setPlayerId(7);
        p7.setPlayerName("Player7");
        p7.setSport("Cricket");
        p7.setTeam("Team7");
        p7.setAge(27);
        p7.setSalary(70000);
        p7.setCountry("India");
        System.out.println(p7.getPlayerId());
        System.out.println(p7.getPlayerName());
        System.out.println(p7.getSport());
        System.out.println(p7.getTeam());
        System.out.println(p7.getAge());
        System.out.println(p7.getSalary());
        System.out.println(p7.getCountry());

        Player p8 = new Player();
        p8.setPlayerId(8);
        p8.setPlayerName("Player8");
        p8.setSport("Football");
        p8.setTeam("Team8");
        p8.setAge(28);
        p8.setSalary(80000);
        p8.setCountry("Germany");
        System.out.println(p8.getPlayerId());
        System.out.println(p8.getPlayerName());
        System.out.println(p8.getSport());
        System.out.println(p8.getTeam());
        System.out.println(p8.getAge());
        System.out.println(p8.getSalary());
        System.out.println(p8.getCountry());

        Player p9 = new Player();
        p9.setPlayerId(9);
        p9.setPlayerName("Player9");
        p9.setSport("Tennis");
        p9.setTeam("Team9");
        p9.setAge(29);
        p9.setSalary(90000);
        p9.setCountry("France");
        System.out.println(p9.getPlayerId());
        System.out.println(p9.getPlayerName());
        System.out.println(p9.getSport());
        System.out.println(p9.getTeam());
        System.out.println(p9.getAge());
        System.out.println(p9.getSalary());
        System.out.println(p9.getCountry());

        Player p10 = new Player();
        p10.setPlayerId(10);
        p10.setPlayerName("Player10");
        p10.setSport("Cricket");
        p10.setTeam("Team10");
        p10.setAge(30);
        p10.setSalary(100000);
        p10.setCountry("India");
        System.out.println(p10.getPlayerId());
        System.out.println(p10.getPlayerName());
        System.out.println(p10.getSport());
        System.out.println(p10.getTeam());
        System.out.println(p10.getAge());
        System.out.println(p10.getSalary());
        System.out.println(p10.getCountry());

        Player p11 = new Player();
        p11.setPlayerId(11);
        p11.setPlayerName("Player11");
        p11.setSport("Football");
        p11.setTeam("Team11");
        p11.setAge(31);
        p11.setSalary(110000);
        p11.setCountry("England");
        System.out.println(p11.getPlayerId());
        System.out.println(p11.getPlayerName());
        System.out.println(p11.getSport());
        System.out.println(p11.getTeam());
        System.out.println(p11.getAge());
        System.out.println(p11.getSalary());
        System.out.println(p11.getCountry());

        Player p12 = new Player();
        p12.setPlayerId(12);
        p12.setPlayerName("Player12");
        p12.setSport("Tennis");
        p12.setTeam("Team12");
        p12.setAge(32);
        p12.setSalary(120000);
        p12.setCountry("Serbia");
        System.out.println(p12.getPlayerId());
        System.out.println(p12.getPlayerName());
        System.out.println(p12.getSport());
        System.out.println(p12.getTeam());
        System.out.println(p12.getAge());
        System.out.println(p12.getSalary());
        System.out.println(p12.getCountry());

        Player p13 = new Player();
        p13.setPlayerId(13);
        p13.setPlayerName("Player13");
        p13.setSport("Cricket");
        p13.setTeam("Team13");
        p13.setAge(23);
        p13.setSalary(130000);
        p13.setCountry("India");
        System.out.println(p13.getPlayerId());
        System.out.println(p13.getPlayerName());
        System.out.println(p13.getSport());
        System.out.println(p13.getTeam());
        System.out.println(p13.getAge());
        System.out.println(p13.getSalary());
        System.out.println(p13.getCountry());

        Player p14 = new Player();
        p14.setPlayerId(14);
        p14.setPlayerName("Player14");
        p14.setSport("Football");
        p14.setTeam("Team14");
        p14.setAge(24);
        p14.setSalary(140000);
        p14.setCountry("Portugal");
        System.out.println(p14.getPlayerId());
        System.out.println(p14.getPlayerName());
        System.out.println(p14.getSport());
        System.out.println(p14.getTeam());
        System.out.println(p14.getAge());
        System.out.println(p14.getSalary());
        System.out.println(p14.getCountry());

        Player p15 = new Player();
        p15.setPlayerId(15);
        p15.setPlayerName("Player15");
        p15.setSport("Tennis");
        p15.setTeam("Team15");
        p15.setAge(25);
        p15.setSalary(150000);
        p15.setCountry("Switzerland");
        System.out.println(p15.getPlayerId());
        System.out.println(p15.getPlayerName());
        System.out.println(p15.getSport());
        System.out.println(p15.getTeam());
        System.out.println(p15.getAge());
        System.out.println(p15.getSalary());
        System.out.println(p15.getCountry());

        Player p16 = new Player();
        p16.setPlayerId(16);
        p16.setPlayerName("Player16");
        p16.setSport("Cricket");
        p16.setTeam("Team16");
        p16.setAge(26);
        p16.setSalary(160000);
        p16.setCountry("India");
        System.out.println(p16.getPlayerId());
        System.out.println(p16.getPlayerName());
        System.out.println(p16.getSport());
        System.out.println(p16.getTeam());
        System.out.println(p16.getAge());
        System.out.println(p16.getSalary());
        System.out.println(p16.getCountry());

        Player p17 = new Player();
        p17.setPlayerId(17);
        p17.setPlayerName("Player17");
        p17.setSport("Football");
        p17.setTeam("Team17");
        p17.setAge(27);
        p17.setSalary(170000);
        p17.setCountry("Italy");
        System.out.println(p17.getPlayerId());
        System.out.println(p17.getPlayerName());
        System.out.println(p17.getSport());
        System.out.println(p17.getTeam());
        System.out.println(p17.getAge());
        System.out.println(p17.getSalary());
        System.out.println(p17.getCountry());

        Player p18 = new Player();
        p18.setPlayerId(18);
        p18.setPlayerName("Player18");
        p18.setSport("Tennis");
        p18.setTeam("Team18");
        p18.setAge(28);
        p18.setSalary(180000);
        p18.setCountry("Russia");
        System.out.println(p18.getPlayerId());
        System.out.println(p18.getPlayerName());
        System.out.println(p18.getSport());
        System.out.println(p18.getTeam());
        System.out.println(p18.getAge());
        System.out.println(p18.getSalary());
        System.out.println(p18.getCountry());

        Player p19 = new Player();
        p19.setPlayerId(19);
        p19.setPlayerName("Player19");
        p19.setSport("Cricket");
        p19.setTeam("Team19");
        p19.setAge(29);
        p19.setSalary(190000);
        p19.setCountry("India");
        System.out.println(p19.getPlayerId());
        System.out.println(p19.getPlayerName());
        System.out.println(p19.getSport());
        System.out.println(p19.getTeam());
        System.out.println(p19.getAge());
        System.out.println(p19.getSalary());
        System.out.println(p19.getCountry());

        Player p20 = new Player();
        p20.setPlayerId(20);
        p20.setPlayerName("Player20");
        p20.setSport("Football");
        p20.setTeam("Team20");
        p20.setAge(30);
        p20.setSalary(200000);
        p20.setCountry("Spain");
        System.out.println(p20.getPlayerId());
        System.out.println(p20.getPlayerName());
        System.out.println(p20.getSport());
        System.out.println(p20.getTeam());
        System.out.println(p20.getAge());
        System.out.println(p20.getSalary());
        System.out.println(p20.getCountry());

        Player p21 = new Player();
        p21.setPlayerId(21);
        p21.setPlayerName("Player21");
        p21.setSport("Tennis");
        p21.setTeam("Team21");
        p21.setAge(31);
        p21.setSalary(210000);
        p21.setCountry("Japan");
        System.out.println(p21.getPlayerId());
        System.out.println(p21.getPlayerName());
        System.out.println(p21.getSport());
        System.out.println(p21.getTeam());
        System.out.println(p21.getAge());
        System.out.println(p21.getSalary());
        System.out.println(p21.getCountry());

        Player p22 = new Player();
        p22.setPlayerId(22);
        p22.setPlayerName("Player22");
        p22.setSport("Cricket");
        p22.setTeam("Team22");
        p22.setAge(22);
        p22.setSalary(220000);
        p22.setCountry("India");
        System.out.println(p22.getPlayerId());
        System.out.println(p22.getPlayerName());
        System.out.println(p22.getSport());
        System.out.println(p22.getTeam());
        System.out.println(p22.getAge());
        System.out.println(p22.getSalary());
        System.out.println(p22.getCountry());

        Player p23 = new Player();
        p23.setPlayerId(23);
        p23.setPlayerName("Player23");
        p23.setSport("Football");
        p23.setTeam("Team23");
        p23.setAge(23);
        p23.setSalary(230000);
        p23.setCountry("Netherlands");
        System.out.println(p23.getPlayerId());
        System.out.println(p23.getPlayerName());
        System.out.println(p23.getSport());
        System.out.println(p23.getTeam());
        System.out.println(p23.getAge());
        System.out.println(p23.getSalary());
        System.out.println(p23.getCountry());

        Player p24 = new Player();
        p24.setPlayerId(24);
        p24.setPlayerName("Player24");
        p24.setSport("Tennis");
        p24.setTeam("Team24");
        p24.setAge(24);
        p24.setSalary(240000);
        p24.setCountry("Australia");
        System.out.println(p24.getPlayerId());
        System.out.println(p24.getPlayerName());
        System.out.println(p24.getSport());
        System.out.println(p24.getTeam());
        System.out.println(p24.getAge());
        System.out.println(p24.getSalary());
        System.out.println(p24.getCountry());

        Player p25 = new Player();
        p25.setPlayerId(25);
        p25.setPlayerName("Player25");
        p25.setSport("Cricket");
        p25.setTeam("Team25");
        p25.setAge(25);
        p25.setSalary(250000);
        p25.setCountry("India");
        System.out.println(p25.getPlayerId());
        System.out.println(p25.getPlayerName());
        System.out.println(p25.getSport());
        System.out.println(p25.getTeam());
        System.out.println(p25.getAge());
        System.out.println(p25.getSalary());
        System.out.println(p25.getCountry());

        Player p26 = new Player();
        p26.setPlayerId(26);
        p26.setPlayerName("Player26");
        p26.setSport("Football");
        p26.setTeam("Team26");
        p26.setAge(26);
        p26.setSalary(260000);
        p26.setCountry("Belgium");
        System.out.println(p26.getPlayerId());
        System.out.println(p26.getPlayerName());
        System.out.println(p26.getSport());
        System.out.println(p26.getTeam());
        System.out.println(p26.getAge());
        System.out.println(p26.getSalary());
        System.out.println(p26.getCountry());

        Player p27 = new Player();
        p27.setPlayerId(27);
        p27.setPlayerName("Player27");
        p27.setSport("Tennis");
        p27.setTeam("Team27");
        p27.setAge(27);
        p27.setSalary(270000);
        p27.setCountry("Canada");
        System.out.println(p27.getPlayerId());
        System.out.println(p27.getPlayerName());
        System.out.println(p27.getSport());
        System.out.println(p27.getTeam());
        System.out.println(p27.getAge());
        System.out.println(p27.getSalary());
        System.out.println(p27.getCountry());

        Player p28 = new Player();
        p28.setPlayerId(28);
        p28.setPlayerName("Player28");
        p28.setSport("Cricket");
        p28.setTeam("Team28");
        p28.setAge(28);
        p28.setSalary(280000);
        p28.setCountry("India");
        System.out.println(p28.getPlayerId());
        System.out.println(p28.getPlayerName());
        System.out.println(p28.getSport());
        System.out.println(p28.getTeam());
        System.out.println(p28.getAge());
        System.out.println(p28.getSalary());
        System.out.println(p28.getCountry());

        Player p29 = new Player();
        p29.setPlayerId(29);
        p29.setPlayerName("Player29");
        p29.setSport("Football");
        p29.setTeam("Team29");
        p29.setAge(29);
        p29.setSalary(290000);
        p29.setCountry("France");
        System.out.println(p29.getPlayerId());
        System.out.println(p29.getPlayerName());
        System.out.println(p29.getSport());
        System.out.println(p29.getTeam());
        System.out.println(p29.getAge());
        System.out.println(p29.getSalary());
        System.out.println(p29.getCountry());
    }
}