class ResturantExecutor{
public static void main(String[] args){
Restaurant refOne = new Restaurant();

System.out.println("The restaurantId is: " + refOne.restaurantId);
System.out.println("The restaurantName is: " + refOne.restaurantName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfTables is: " + refOne.numberOfTables);
System.out.println("The numberOfChairs is: " + refOne.numberOfChairs);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasOutdoorSeating is: " + refOne.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refOne.hasDelivery);
System.out.println("The hasTakeaway is: " + refOne.hasTakeaway);
System.out.println("The hasBuffet is: " + refOne.hasBuffet);
System.out.println("The hasBar is: " + refOne.hasBar);
System.out.println("The cuisineType is: " + refOne.cuisineType);
System.out.println("The averageCostPerPerson is: " + refOne.averageCostPerPerson);
System.out.println("The ownerName is: " + refOne.ownerName);
System.out.println("The managerName is: " + refOne.managerName);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The isFamilyFriendly is: " + refOne.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refOne.hasLiveMusic);
System.out.println("The rating is: " + refOne.rating);

refOne.restaurantId = 1;
refOne.restaurantName = "Spice Villa";
refOne.location = "MG Road";
refOne.city = "Bengaluru";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfTables = 20;
refOne.numberOfChairs = 80;
refOne.hasWifi = true;
refOne.hasParking = true;
refOne.hasOutdoorSeating = true;
refOne.hasDelivery = true;
refOne.hasTakeaway = true;
refOne.hasBuffet = false;
refOne.hasBar = true;
refOne.cuisineType = "Indian";
refOne.averageCostPerPerson = 750.50;
refOne.ownerName = "Ramesh Kumar";
refOne.managerName = "Anita Sharma";
refOne.contactNumber = "9876543210";
refOne.email = "info@spicevilla.com";
refOne.website = "www.spicevilla.com";
refOne.establishedYear = 2015;
refOne.isFamilyFriendly = true;
refOne.hasLiveMusic = false;
refOne.rating = "4.5/5";

System.out.println("The restaurantId is: " + refOne.restaurantId);
System.out.println("The restaurantName is: " + refOne.restaurantName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfTables is: " + refOne.numberOfTables);
System.out.println("The numberOfChairs is: " + refOne.numberOfChairs);
System.out.println("The hasWifi is: " + refOne.hasWifi);
System.out.println("The hasParking is: " + refOne.hasParking);
System.out.println("The hasOutdoorSeating is: " + refOne.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refOne.hasDelivery);
System.out.println("The hasTakeaway is: " + refOne.hasTakeaway);
System.out.println("The hasBuffet is: " + refOne.hasBuffet);
System.out.println("The hasBar is: " + refOne.hasBar);
System.out.println("The cuisineType is: " + refOne.cuisineType);
System.out.println("The averageCostPerPerson is: " + refOne.averageCostPerPerson);
System.out.println("The ownerName is: " + refOne.ownerName);
System.out.println("The managerName is: " + refOne.managerName);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The isFamilyFriendly is: " + refOne.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refOne.hasLiveMusic);
System.out.println("The rating is: " + refOne.rating);
Restaurant refTwo = new Restaurant();

System.out.println("The restaurantId is: " + refTwo.restaurantId);
System.out.println("The restaurantName is: " + refTwo.restaurantName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfTables is: " + refTwo.numberOfTables);
System.out.println("The numberOfChairs is: " + refTwo.numberOfChairs);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasOutdoorSeating is: " + refTwo.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refTwo.hasDelivery);
System.out.println("The hasTakeaway is: " + refTwo.hasTakeaway);
System.out.println("The hasBuffet is: " + refTwo.hasBuffet);
System.out.println("The hasBar is: " + refTwo.hasBar);
System.out.println("The cuisineType is: " + refTwo.cuisineType);
System.out.println("The averageCostPerPerson is: " + refTwo.averageCostPerPerson);
System.out.println("The ownerName is: " + refTwo.ownerName);
System.out.println("The managerName is: " + refTwo.managerName);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The isFamilyFriendly is: " + refTwo.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refTwo.hasLiveMusic);
System.out.println("The rating is: " + refTwo.rating);

refTwo.restaurantId = 2;
refTwo.restaurantName = "Ocean Breeze";
refTwo.location = "Marine Drive";
refTwo.city = "Mumbai";
refTwo.state = "Maharashtra";
refTwo.country = "India";
refTwo.numberOfTables = 30;
refTwo.numberOfChairs = 120;
refTwo.hasWifi = true;
refTwo.hasParking = false;
refTwo.hasOutdoorSeating = true;
refTwo.hasDelivery = true;
refTwo.hasTakeaway = true;
refTwo.hasBuffet = true;
refTwo.hasBar = true;
refTwo.cuisineType = "Seafood";
refTwo.averageCostPerPerson = 1200.00;
refTwo.ownerName = "Sunil Mehta";
refTwo.managerName = "Priya Desai";
refTwo.contactNumber = "9123456780";
refTwo.email = "contact@oceanbreeze.com";
refTwo.website = "www.oceanbreeze.com";
refTwo.establishedYear = 2010;
refTwo.isFamilyFriendly = true;
refTwo.hasLiveMusic = true;
refTwo.rating = "4.7/5";

System.out.println("The restaurantId is: " + refTwo.restaurantId);
System.out.println("The restaurantName is: " + refTwo.restaurantName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfTables is: " + refTwo.numberOfTables);
System.out.println("The numberOfChairs is: " + refTwo.numberOfChairs);
System.out.println("The hasWifi is: " + refTwo.hasWifi);
System.out.println("The hasParking is: " + refTwo.hasParking);
System.out.println("The hasOutdoorSeating is: " + refTwo.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refTwo.hasDelivery);
System.out.println("The hasTakeaway is: " + refTwo.hasTakeaway);
System.out.println("The hasBuffet is: " + refTwo.hasBuffet);
System.out.println("The hasBar is: " + refTwo.hasBar);
System.out.println("The cuisineType is: " + refTwo.cuisineType);
System.out.println("The averageCostPerPerson is: " + refTwo.averageCostPerPerson);
System.out.println("The ownerName is: " + refTwo.ownerName);
System.out.println("The managerName is: " + refTwo.managerName);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The isFamilyFriendly is: " + refTwo.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refTwo.hasLiveMusic);
System.out.println("The rating is: " + refTwo.rating);
Restaurant refThree = new Restaurant();

System.out.println("The restaurantId is: " + refThree.restaurantId);
System.out.println("The restaurantName is: " + refThree.restaurantName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfTables is: " + refThree.numberOfTables);
System.out.println("The numberOfChairs is: " + refThree.numberOfChairs);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasOutdoorSeating is: " + refThree.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refThree.hasDelivery);
System.out.println("The hasTakeaway is: " + refThree.hasTakeaway);
System.out.println("The hasBuffet is: " + refThree.hasBuffet);
System.out.println("The hasBar is: " + refThree.hasBar);
System.out.println("The cuisineType is: " + refThree.cuisineType);
System.out.println("The averageCostPerPerson is: " + refThree.averageCostPerPerson);
System.out.println("The ownerName is: " + refThree.ownerName);
System.out.println("The managerName is: " + refThree.managerName);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The isFamilyFriendly is: " + refThree.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refThree.hasLiveMusic);
System.out.println("The rating is: " + refThree.rating);

refThree.restaurantId = 3;
refThree.restaurantName = "Mountain Delight";
refThree.location = "Hilltop Road";
refThree.city = "Shimla";
refThree.state = "Himachal Pradesh";
refThree.country = "India";
refThree.numberOfTables = 15;
refThree.numberOfChairs = 60;
refThree.hasWifi = false;
refThree.hasParking = true;
refThree.hasOutdoorSeating = true;
refThree.hasDelivery = false;
refThree.hasTakeaway = true;
refThree.hasBuffet = false;
refThree.hasBar = false;
refThree.cuisineType = "Continental";
refThree.averageCostPerPerson = 950.75;
refThree.ownerName = "Vikram Singh";
refThree.managerName = "Ritu Sharma";
refThree.contactNumber = "9876512345";
refThree.email = "info@mountaindelight.com";
refThree.website = "www.mountaindelight.com";
refThree.establishedYear = 2018;
refThree.isFamilyFriendly = true;
refThree.hasLiveMusic = true;
refThree.rating = "4.6/5";

System.out.println("The restaurantId is: " + refThree.restaurantId);
System.out.println("The restaurantName is: " + refThree.restaurantName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfTables is: " + refThree.numberOfTables);
System.out.println("The numberOfChairs is: " + refThree.numberOfChairs);
System.out.println("The hasWifi is: " + refThree.hasWifi);
System.out.println("The hasParking is: " + refThree.hasParking);
System.out.println("The hasOutdoorSeating is: " + refThree.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refThree.hasDelivery);
System.out.println("The hasTakeaway is: " + refThree.hasTakeaway);
System.out.println("The hasBuffet is: " + refThree.hasBuffet);
System.out.println("The hasBar is: " + refThree.hasBar);
System.out.println("The cuisineType is: " + refThree.cuisineType);
System.out.println("The averageCostPerPerson is: " + refThree.averageCostPerPerson);
System.out.println("The ownerName is: " + refThree.ownerName);
System.out.println("The managerName is: " + refThree.managerName);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The isFamilyFriendly is: " + refThree.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refThree.hasLiveMusic);
System.out.println("The rating is: " + refThree.rating);
Restaurant refFour = new Restaurant();

System.out.println("The restaurantId is: " + refFour.restaurantId);
System.out.println("The restaurantName is: " + refFour.restaurantName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfTables is: " + refFour.numberOfTables);
System.out.println("The numberOfChairs is: " + refFour.numberOfChairs);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasOutdoorSeating is: " + refFour.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refFour.hasDelivery);
System.out.println("The hasTakeaway is: " + refFour.hasTakeaway);
System.out.println("The hasBuffet is: " + refFour.hasBuffet);
System.out.println("The hasBar is: " + refFour.hasBar);
System.out.println("The cuisineType is: " + refFour.cuisineType);
System.out.println("The averageCostPerPerson is: " + refFour.averageCostPerPerson);
System.out.println("The ownerName is: " + refFour.ownerName);
System.out.println("The managerName is: " + refFour.managerName);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The isFamilyFriendly is: " + refFour.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refFour.hasLiveMusic);
System.out.println("The rating is: " + refFour.rating);

refFour.restaurantId = 4;
refFour.restaurantName = "Sunset Grill";
refFour.location = "Beach Road";
refFour.city = "Goa";
refFour.state = "Goa";
refFour.country = "India";
refFour.numberOfTables = 25;
refFour.numberOfChairs = 100;
refFour.hasWifi = true;
refFour.hasParking = true;
refFour.hasOutdoorSeating = true;
refFour.hasDelivery = false;
refFour.hasTakeaway = true;
refFour.hasBuffet = true;
refFour.hasBar = true;
refFour.cuisineType = "Grilled & Barbecue";
refFour.averageCostPerPerson = 1100.00;
refFour.ownerName = "Anand Rao";
refFour.managerName = "Sonal Verma";
refFour.contactNumber = "9988776655";
refFour.email = "contact@sunsetgrill.com";
refFour.website = "www.sunsetgrill.com";
refFour.establishedYear = 2012;
refFour.isFamilyFriendly = true;
refFour.hasLiveMusic = true;
refFour.rating = "4.8/5";

System.out.println("The restaurantId is: " + refFour.restaurantId);
System.out.println("The restaurantName is: " + refFour.restaurantName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfTables is: " + refFour.numberOfTables);
System.out.println("The numberOfChairs is: " + refFour.numberOfChairs);
System.out.println("The hasWifi is: " + refFour.hasWifi);
System.out.println("The hasParking is: " + refFour.hasParking);
System.out.println("The hasOutdoorSeating is: " + refFour.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refFour.hasDelivery);
System.out.println("The hasTakeaway is: " + refFour.hasTakeaway);
System.out.println("The hasBuffet is: " + refFour.hasBuffet);
System.out.println("The hasBar is: " + refFour.hasBar);
System.out.println("The cuisineType is: " + refFour.cuisineType);
System.out.println("The averageCostPerPerson is: " + refFour.averageCostPerPerson);
System.out.println("The ownerName is: " + refFour.ownerName);
System.out.println("The managerName is: " + refFour.managerName);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The isFamilyFriendly is: " + refFour.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refFour.hasLiveMusic);
System.out.println("The rating is: " + refFour.rating);
Restaurant refFive = new Restaurant();

System.out.println("The restaurantId is: " + refFive.restaurantId);
System.out.println("The restaurantName is: " + refFive.restaurantName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfTables is: " + refFive.numberOfTables);
System.out.println("The numberOfChairs is: " + refFive.numberOfChairs);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The hasParking is: " + refFive.hasParking);
System.out.println("The hasOutdoorSeating is: " + refFive.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refFive.hasDelivery);
System.out.println("The hasTakeaway is: " + refFive.hasTakeaway);
System.out.println("The hasBuffet is: " + refFive.hasBuffet);
System.out.println("The hasBar is: " + refFive.hasBar);
System.out.println("The cuisineType is: " + refFive.cuisineType);
System.out.println("The averageCostPerPerson is: " + refFive.averageCostPerPerson);
System.out.println("The ownerName is: " + refFive.ownerName);
System.out.println("The managerName is: " + refFive.managerName);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The isFamilyFriendly is: " + refFive.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refFive.hasLiveMusic);
System.out.println("The rating is: " + refFive.rating);

refFive.restaurantId = 5;
refFive.restaurantName = "Garden Feast";
refFive.location = "Green Park";
refFive.city = "Chennai";
refFive.state = "Tamil Nadu";
refFive.country = "India";
refFive.numberOfTables = 18;
refFive.numberOfChairs = 72;
refFive.hasWifi = true;
refFive.hasParking = true;
refFive.hasOutdoorSeating = true;
refFive.hasDelivery = true;
refFive.hasTakeaway = true;
refFive.hasBuffet = true;
refFive.hasBar = false;
refFive.cuisineType = "Vegetarian";
refFive.averageCostPerPerson = 650.00;
refFive.ownerName = "Lakshmi Narayan";
refFive.managerName = "Deepa Ramesh";
refFive.contactNumber = "9445566778";
refFive.email = "info@gardenfeast.com";
refFive.website = "www.gardenfeast.com";
refFive.establishedYear = 2016;
refFive.isFamilyFriendly = true;
refFive.hasLiveMusic = false;
refFive.rating = "4.4/5";

System.out.println("The restaurantId is: " + refFive.restaurantId);
System.out.println("The restaurantName is: " + refFive.restaurantName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfTables is: " + refFive.numberOfTables);
System.out.println("The numberOfChairs is: " + refFive.numberOfChairs);
System.out.println("The hasWifi is: " + refFive.hasWifi);
System.out.println("The hasParking is: " + refFive.hasParking);
System.out.println("The hasOutdoorSeating is: " + refFive.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refFive.hasDelivery);
System.out.println("The hasTakeaway is: " + refFive.hasTakeaway);
System.out.println("The hasBuffet is: " + refFive.hasBuffet);
System.out.println("The hasBar is: " + refFive.hasBar);
System.out.println("The cuisineType is: " + refFive.cuisineType);
System.out.println("The averageCostPerPerson is: " + refFive.averageCostPerPerson);
System.out.println("The ownerName is: " + refFive.ownerName);
System.out.println("The managerName is: " + refFive.managerName);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The isFamilyFriendly is: " + refFive.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refFive.hasLiveMusic);
System.out.println("The rating is: " + refFive.rating);
Restaurant refSix = new Restaurant();

System.out.println("The restaurantId is: " + refSix.restaurantId);
System.out.println("The restaurantName is: " + refSix.restaurantName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfTables is: " + refSix.numberOfTables);
System.out.println("The numberOfChairs is: " + refSix.numberOfChairs);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasOutdoorSeating is: " + refSix.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refSix.hasDelivery);
System.out.println("The hasTakeaway is: " + refSix.hasTakeaway);
System.out.println("The hasBuffet is: " + refSix.hasBuffet);
System.out.println("The hasBar is: " + refSix.hasBar);
System.out.println("The cuisineType is: " + refSix.cuisineType);
System.out.println("The averageCostPerPerson is: " + refSix.averageCostPerPerson);
System.out.println("The ownerName is: " + refSix.ownerName);
System.out.println("The managerName is: " + refSix.managerName);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The isFamilyFriendly is: " + refSix.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refSix.hasLiveMusic);
System.out.println("The rating is: " + refSix.rating);

refSix.restaurantId = 6;
refSix.restaurantName = "The Royal Feast";
refSix.location = "MG Road";
refSix.city = "Jaipur";
refSix.state = "Rajasthan";
refSix.country = "India";
refSix.numberOfTables = 22;
refSix.numberOfChairs = 88;
refSix.hasWifi = true;
refSix.hasParking = true;
refSix.hasOutdoorSeating = false;
refSix.hasDelivery = true;
refSix.hasTakeaway = true;
refSix.hasBuffet = true;
refSix.hasBar = true;
refSix.cuisineType = "Rajasthani";
refSix.averageCostPerPerson = 1300.00;
refSix.ownerName = "Rajiv Singh";
refSix.managerName = "Meera Kapoor";
refSix.contactNumber = "9876123456";
refSix.email = "info@royalfeast.com";
refSix.website = "www.royalfeast.com";
refSix.establishedYear = 2014;
refSix.isFamilyFriendly = true;
refSix.hasLiveMusic = true;
refSix.rating = "4.7/5";

System.out.println("The restaurantId is: " + refSix.restaurantId);
System.out.println("The restaurantName is: " + refSix.restaurantName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfTables is: " + refSix.numberOfTables);
System.out.println("The numberOfChairs is: " + refSix.numberOfChairs);
System.out.println("The hasWifi is: " + refSix.hasWifi);
System.out.println("The hasParking is: " + refSix.hasParking);
System.out.println("The hasOutdoorSeating is: " + refSix.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refSix.hasDelivery);
System.out.println("The hasTakeaway is: " + refSix.hasTakeaway);
System.out.println("The hasBuffet is: " + refSix.hasBuffet);
System.out.println("The hasBar is: " + refSix.hasBar);
System.out.println("The cuisineType is: " + refSix.cuisineType);
System.out.println("The averageCostPerPerson is: " + refSix.averageCostPerPerson);
System.out.println("The ownerName is: " + refSix.ownerName);
System.out.println("The managerName is: " + refSix.managerName);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The isFamilyFriendly is: " + refSix.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refSix.hasLiveMusic);
System.out.println("The rating is: " + refSix.rating);
Restaurant refSeven = new Restaurant();

System.out.println("The restaurantId is: " + refSeven.restaurantId);
System.out.println("The restaurantName is: " + refSeven.restaurantName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfTables is: " + refSeven.numberOfTables);
System.out.println("The numberOfChairs is: " + refSeven.numberOfChairs);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasOutdoorSeating is: " + refSeven.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refSeven.hasDelivery);
System.out.println("The hasTakeaway is: " + refSeven.hasTakeaway);
System.out.println("The hasBuffet is: " + refSeven.hasBuffet);
System.out.println("The hasBar is: " + refSeven.hasBar);
System.out.println("The cuisineType is: " + refSeven.cuisineType);
System.out.println("The averageCostPerPerson is: " + refSeven.averageCostPerPerson);
System.out.println("The ownerName is: " + refSeven.ownerName);
System.out.println("The managerName is: " + refSeven.managerName);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The isFamilyFriendly is: " + refSeven.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refSeven.hasLiveMusic);
System.out.println("The rating is: " + refSeven.rating);

refSeven.restaurantId = 7;
refSeven.restaurantName = "Café Aroma";
refSeven.location = "Brigade Road";
refSeven.city = "Bengaluru";
refSeven.state = "Karnataka";
refSeven.country = "India";
refSeven.numberOfTables = 12;
refSeven.numberOfChairs = 48;
refSeven.hasWifi = true;
refSeven.hasParking = false;
refSeven.hasOutdoorSeating = true;
refSeven.hasDelivery = true;
refSeven.hasTakeaway = true;
refSeven.hasBuffet = false;
refSeven.hasBar = false;
refSeven.cuisineType = "Cafe & Bakery";
refSeven.averageCostPerPerson = 500.00;
refSeven.ownerName = "Manish Kapoor";
refSeven.managerName = "Sonia Reddy";
refSeven.contactNumber = "9988223344";
refSeven.email = "contact@cafearoma.com";
refSeven.website = "www.cafearoma.com";
refSeven.establishedYear = 2019;
refSeven.isFamilyFriendly = true;
refSeven.hasLiveMusic = false;
refSeven.rating = "4.3/5";

System.out.println("The restaurantId is: " + refSeven.restaurantId);
System.out.println("The restaurantName is: " + refSeven.restaurantName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfTables is: " + refSeven.numberOfTables);
System.out.println("The numberOfChairs is: " + refSeven.numberOfChairs);
System.out.println("The hasWifi is: " + refSeven.hasWifi);
System.out.println("The hasParking is: " + refSeven.hasParking);
System.out.println("The hasOutdoorSeating is: " + refSeven.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refSeven.hasDelivery);
System.out.println("The hasTakeaway is: " + refSeven.hasTakeaway);
System.out.println("The hasBuffet is: " + refSeven.hasBuffet);
System.out.println("The hasBar is: " + refSeven.hasBar);
System.out.println("The cuisineType is: " + refSeven.cuisineType);
System.out.println("The averageCostPerPerson is: " + refSeven.averageCostPerPerson);
System.out.println("The ownerName is: " + refSeven.ownerName);
System.out.println("The managerName is: " + refSeven.managerName);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The isFamilyFriendly is: " + refSeven.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refSeven.hasLiveMusic);
System.out.println("The rating is: " + refSeven.rating);
Restaurant refEight = new Restaurant();

System.out.println("The restaurantId is: " + refEight.restaurantId);
System.out.println("The restaurantName is: " + refEight.restaurantName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfTables is: " + refEight.numberOfTables);
System.out.println("The numberOfChairs is: " + refEight.numberOfChairs);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasOutdoorSeating is: " + refEight.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refEight.hasDelivery);
System.out.println("The hasTakeaway is: " + refEight.hasTakeaway);
System.out.println("The hasBuffet is: " + refEight.hasBuffet);
System.out.println("The hasBar is: " + refEight.hasBar);
System.out.println("The cuisineType is: " + refEight.cuisineType);
System.out.println("The averageCostPerPerson is: " + refEight.averageCostPerPerson);
System.out.println("The ownerName is: " + refEight.ownerName);
System.out.println("The managerName is: " + refEight.managerName);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The isFamilyFriendly is: " + refEight.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refEight.hasLiveMusic);
System.out.println("The rating is: " + refEight.rating);

refEight.restaurantId = 8;
refEight.restaurantName = "Spice Route";
refEight.location = "Connaught Place";
refEight.city = "New Delhi";
refEight.state = "Delhi";
refEight.country = "India";
refEight.numberOfTables = 28;
refEight.numberOfChairs = 112;
refEight.hasWifi = true;
refEight.hasParking = true;
refEight.hasOutdoorSeating = true;
refEight.hasDelivery = true;
refEight.hasTakeaway = true;
refEight.hasBuffet = true;
refEight.hasBar = true;
refEight.cuisineType = "Pan-Asian";
refEight.averageCostPerPerson = 1400.00;
refEight.ownerName = "Rohit Malhotra";
refEight.managerName = "Anjali Gupta";
refEight.contactNumber = "9876541122";
refEight.email = "contact@spiceroute.com";
refEight.website = "www.spiceroute.com";
refEight.establishedYear = 2011;
refEight.isFamilyFriendly = true;
refEight.hasLiveMusic = true;
refEight.rating = "4.6/5";

System.out.println("The restaurantId is: " + refEight.restaurantId);
System.out.println("The restaurantName is: " + refEight.restaurantName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfTables is: " + refEight.numberOfTables);
System.out.println("The numberOfChairs is: " + refEight.numberOfChairs);
System.out.println("The hasWifi is: " + refEight.hasWifi);
System.out.println("The hasParking is: " + refEight.hasParking);
System.out.println("The hasOutdoorSeating is: " + refEight.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refEight.hasDelivery);
System.out.println("The hasTakeaway is: " + refEight.hasTakeaway);
System.out.println("The hasBuffet is: " + refEight.hasBuffet);
System.out.println("The hasBar is: " + refEight.hasBar);
System.out.println("The cuisineType is: " + refEight.cuisineType);
System.out.println("The averageCostPerPerson is: " + refEight.averageCostPerPerson);
System.out.println("The ownerName is: " + refEight.ownerName);
System.out.println("The managerName is: " + refEight.managerName);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The isFamilyFriendly is: " + refEight.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refEight.hasLiveMusic);
System.out.println("The rating is: " + refEight.rating);
Restaurant refNine = new Restaurant();

System.out.println("The restaurantId is: " + refNine.restaurantId);
System.out.println("The restaurantName is: " + refNine.restaurantName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfTables is: " + refNine.numberOfTables);
System.out.println("The numberOfChairs is: " + refNine.numberOfChairs);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasOutdoorSeating is: " + refNine.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refNine.hasDelivery);
System.out.println("The hasTakeaway is: " + refNine.hasTakeaway);
System.out.println("The hasBuffet is: " + refNine.hasBuffet);
System.out.println("The hasBar is: " + refNine.hasBar);
System.out.println("The cuisineType is: " + refNine.cuisineType);
System.out.println("The averageCostPerPerson is: " + refNine.averageCostPerPerson);
System.out.println("The ownerName is: " + refNine.ownerName);
System.out.println("The managerName is: " + refNine.managerName);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The isFamilyFriendly is: " + refNine.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refNine.hasLiveMusic);
System.out.println("The rating is: " + refNine.rating);

refNine.restaurantId = 9;
refNine.restaurantName = "The Italian Oven";
refNine.location = "Park Street";
refNine.city = "Kolkata";
refNine.state = "West Bengal";
refNine.country = "India";
refNine.numberOfTables = 20;
refNine.numberOfChairs = 80;
refNine.hasWifi = true;
refNine.hasParking = true;
refNine.hasOutdoorSeating = false;
refNine.hasDelivery = true;
refNine.hasTakeaway = true;
refNine.hasBuffet = false;
refNine.hasBar = true;
refNine.cuisineType = "Italian";
refNine.averageCostPerPerson = 1100.50;
refNine.ownerName = "Alberto Rossi";
refNine.managerName = "Neha Mitra";
refNine.contactNumber = "9876547788";
refNine.email = "contact@italianoven.com";
refNine.website = "www.italianoven.com";
refNine.establishedYear = 2013;
refNine.isFamilyFriendly = true;
refNine.hasLiveMusic = false;
refNine.rating = "4.5/5";

System.out.println("The restaurantId is: " + refNine.restaurantId);
System.out.println("The restaurantName is: " + refNine.restaurantName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfTables is: " + refNine.numberOfTables);
System.out.println("The numberOfChairs is: " + refNine.numberOfChairs);
System.out.println("The hasWifi is: " + refNine.hasWifi);
System.out.println("The hasParking is: " + refNine.hasParking);
System.out.println("The hasOutdoorSeating is: " + refNine.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refNine.hasDelivery);
System.out.println("The hasTakeaway is: " + refNine.hasTakeaway);
System.out.println("The hasBuffet is: " + refNine.hasBuffet);
System.out.println("The hasBar is: " + refNine.hasBar);
System.out.println("The cuisineType is: " + refNine.cuisineType);
System.out.println("The averageCostPerPerson is: " + refNine.averageCostPerPerson);
System.out.println("The ownerName is: " + refNine.ownerName);
System.out.println("The managerName is: " + refNine.managerName);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The isFamilyFriendly is: " + refNine.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refNine.hasLiveMusic);
System.out.println("The rating is: " + refNine.rating);
Restaurant refTen = new Restaurant();

System.out.println("The restaurantId is: " + refTen.restaurantId);
System.out.println("The restaurantName is: " + refTen.restaurantName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfTables is: " + refTen.numberOfTables);
System.out.println("The numberOfChairs is: " + refTen.numberOfChairs);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refTen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refTen.hasDelivery);
System.out.println("The hasTakeaway is: " + refTen.hasTakeaway);
System.out.println("The hasBuffet is: " + refTen.hasBuffet);
System.out.println("The hasBar is: " + refTen.hasBar);
System.out.println("The cuisineType is: " + refTen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refTen.averageCostPerPerson);
System.out.println("The ownerName is: " + refTen.ownerName);
System.out.println("The managerName is: " + refTen.managerName);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refTen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refTen.hasLiveMusic);
System.out.println("The rating is: " + refTen.rating);

refTen.restaurantId = 10;
refTen.restaurantName = "Blue Lagoon";
refTen.location = "Marine Street";
refTen.city = "Kochi";
refTen.state = "Kerala";
refTen.country = "India";
refTen.numberOfTables = 24;
refTen.numberOfChairs = 96;
refTen.hasWifi = true;
refTen.hasParking = true;
refTen.hasOutdoorSeating = true;
refTen.hasDelivery = true;
refTen.hasTakeaway = true;
refTen.hasBuffet = false;
refTen.hasBar = true;
refTen.cuisineType = "Seafood & Continental";
refTen.averageCostPerPerson = 1250.00;
refTen.ownerName = "Joseph Mathew";
refTen.managerName = "Anu Varghese";
refTen.contactNumber = "9445566990";
refTen.email = "info@bluelagoon.com";
refTen.website = "www.bluelagoon.com";
refTen.establishedYear = 2017;
refTen.isFamilyFriendly = true;
refTen.hasLiveMusic = true;
refTen.rating = "4.7/5";

System.out.println("The restaurantId is: " + refTen.restaurantId);
System.out.println("The restaurantName is: " + refTen.restaurantName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfTables is: " + refTen.numberOfTables);
System.out.println("The numberOfChairs is: " + refTen.numberOfChairs);
System.out.println("The hasWifi is: " + refTen.hasWifi);
System.out.println("The hasParking is: " + refTen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refTen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refTen.hasDelivery);
System.out.println("The hasTakeaway is: " + refTen.hasTakeaway);
System.out.println("The hasBuffet is: " + refTen.hasBuffet);
System.out.println("The hasBar is: " + refTen.hasBar);
System.out.println("The cuisineType is: " + refTen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refTen.averageCostPerPerson);
System.out.println("The ownerName is: " + refTen.ownerName);
System.out.println("The managerName is: " + refTen.managerName);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refTen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refTen.hasLiveMusic);
System.out.println("The rating is: " + refTen.rating);
Restaurant refEleven = new Restaurant();

System.out.println("The restaurantId is: " + refEleven.restaurantId);
System.out.println("The restaurantName is: " + refEleven.restaurantName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfTables is: " + refEleven.numberOfTables);
System.out.println("The numberOfChairs is: " + refEleven.numberOfChairs);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasOutdoorSeating is: " + refEleven.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refEleven.hasDelivery);
System.out.println("The hasTakeaway is: " + refEleven.hasTakeaway);
System.out.println("The hasBuffet is: " + refEleven.hasBuffet);
System.out.println("The hasBar is: " + refEleven.hasBar);
System.out.println("The cuisineType is: " + refEleven.cuisineType);
System.out.println("The averageCostPerPerson is: " + refEleven.averageCostPerPerson);
System.out.println("The ownerName is: " + refEleven.ownerName);
System.out.println("The managerName is: " + refEleven.managerName);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The isFamilyFriendly is: " + refEleven.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refEleven.hasLiveMusic);
System.out.println("The rating is: " + refEleven.rating);

refEleven.restaurantId = 11;
refEleven.restaurantName = "Royal Spice";
refEleven.location = "Sector 18";
refEleven.city = "Noida";
refEleven.state = "Uttar Pradesh";
refEleven.country = "India";
refEleven.numberOfTables = 26;
refEleven.numberOfChairs = 104;
refEleven.hasWifi = true;
refEleven.hasParking = true;
refEleven.hasOutdoorSeating = false;
refEleven.hasDelivery = true;
refEleven.hasTakeaway = true;
refEleven.hasBuffet = true;
refEleven.hasBar = true;
refEleven.cuisineType = "North Indian";
refEleven.averageCostPerPerson = 1250.00;
refEleven.ownerName = "Anil Kumar";
refEleven.managerName = "Richa Sharma";
refEleven.contactNumber = "9811223344";
refEleven.email = "info@royalspice.com";
refEleven.website = "www.royalspice.com";
refEleven.establishedYear = 2015;
refEleven.isFamilyFriendly = true;
refEleven.hasLiveMusic = true;
refEleven.rating = "4.6/5";

System.out.println("The restaurantId is: " + refEleven.restaurantId);
System.out.println("The restaurantName is: " + refEleven.restaurantName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfTables is: " + refEleven.numberOfTables);
System.out.println("The numberOfChairs is: " + refEleven.numberOfChairs);
System.out.println("The hasWifi is: " + refEleven.hasWifi);
System.out.println("The hasParking is: " + refEleven.hasParking);
System.out.println("The hasOutdoorSeating is: " + refEleven.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refEleven.hasDelivery);
System.out.println("The hasTakeaway is: " + refEleven.hasTakeaway);
System.out.println("The hasBuffet is: " + refEleven.hasBuffet);
System.out.println("The hasBar is: " + refEleven.hasBar);
System.out.println("The cuisineType is: " + refEleven.cuisineType);
System.out.println("The averageCostPerPerson is: " + refEleven.averageCostPerPerson);
System.out.println("The ownerName is: " + refEleven.ownerName);
System.out.println("The managerName is: " + refEleven.managerName);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The isFamilyFriendly is: " + refEleven.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refEleven.hasLiveMusic);
System.out.println("The rating is: " + refEleven.rating);
Restaurant refTwelve = new Restaurant();

System.out.println("The restaurantId is: " + refTwelve.restaurantId);
System.out.println("The restaurantName is: " + refTwelve.restaurantName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfTables is: " + refTwelve.numberOfTables);
System.out.println("The numberOfChairs is: " + refTwelve.numberOfChairs);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasOutdoorSeating is: " + refTwelve.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refTwelve.hasDelivery);
System.out.println("The hasTakeaway is: " + refTwelve.hasTakeaway);
System.out.println("The hasBuffet is: " + refTwelve.hasBuffet);
System.out.println("The hasBar is: " + refTwelve.hasBar);
System.out.println("The cuisineType is: " + refTwelve.cuisineType);
System.out.println("The averageCostPerPerson is: " + refTwelve.averageCostPerPerson);
System.out.println("The ownerName is: " + refTwelve.ownerName);
System.out.println("The managerName is: " + refTwelve.managerName);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The isFamilyFriendly is: " + refTwelve.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refTwelve.hasLiveMusic);
System.out.println("The rating is: " + refTwelve.rating);

refTwelve.restaurantId = 12;
refTwelve.restaurantName = "Olive Garden";
refTwelve.location = "Sector 34";
refTwelve.city = "Gurgaon";
refTwelve.state = "Haryana";
refTwelve.country = "India";
refTwelve.numberOfTables = 20;
refTwelve.numberOfChairs = 80;
refTwelve.hasWifi = true;
refTwelve.hasParking = true;
refTwelve.hasOutdoorSeating = true;
refTwelve.hasDelivery = true;
refTwelve.hasTakeaway = true;
refTwelve.hasBuffet = false;
refTwelve.hasBar = true;
refTwelve.cuisineType = "Italian & Continental";
refTwelve.averageCostPerPerson = 1350.00;
refTwelve.ownerName = "Sandeep Malhotra";
refTwelve.managerName = "Neha Khanna";
refTwelve.contactNumber = "9811225566";
refTwelve.email = "contact@olivegarden.com";
refTwelve.website = "www.olivegarden.com";
refTwelve.establishedYear = 2016;
refTwelve.isFamilyFriendly = true;
refTwelve.hasLiveMusic = true;
refTwelve.rating = "4.6/5";

System.out.println("The restaurantId is: " + refTwelve.restaurantId);
System.out.println("The restaurantName is: " + refTwelve.restaurantName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfTables is: " + refTwelve.numberOfTables);
System.out.println("The numberOfChairs is: " + refTwelve.numberOfChairs);
System.out.println("The hasWifi is: " + refTwelve.hasWifi);
System.out.println("The hasParking is: " + refTwelve.hasParking);
System.out.println("The hasOutdoorSeating is: " + refTwelve.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refTwelve.hasDelivery);
System.out.println("The hasTakeaway is: " + refTwelve.hasTakeaway);
System.out.println("The hasBuffet is: " + refTwelve.hasBuffet);
System.out.println("The hasBar is: " + refTwelve.hasBar);
System.out.println("The cuisineType is: " + refTwelve.cuisineType);
System.out.println("The averageCostPerPerson is: " + refTwelve.averageCostPerPerson);
System.out.println("The ownerName is: " + refTwelve.ownerName);
System.out.println("The managerName is: " + refTwelve.managerName);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The isFamilyFriendly is: " + refTwelve.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refTwelve.hasLiveMusic);
System.out.println("The rating is: " + refTwelve.rating);
Restaurant refThirteen = new Restaurant();

System.out.println("The restaurantId is: " + refThirteen.restaurantId);
System.out.println("The restaurantName is: " + refThirteen.restaurantName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfTables is: " + refThirteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refThirteen.numberOfChairs);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refThirteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refThirteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refThirteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refThirteen.hasBuffet);
System.out.println("The hasBar is: " + refThirteen.hasBar);
System.out.println("The cuisineType is: " + refThirteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refThirteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refThirteen.ownerName);
System.out.println("The managerName is: " + refThirteen.managerName);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refThirteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refThirteen.hasLiveMusic);
System.out.println("The rating is: " + refThirteen.rating);

refThirteen.restaurantId = 13;
refThirteen.restaurantName = "The Green Leaf";
refThirteen.location = "Indiranagar";
refThirteen.city = "Bengaluru";
refThirteen.state = "Karnataka";
refThirteen.country = "India";
refThirteen.numberOfTables = 18;
refThirteen.numberOfChairs = 72;
refThirteen.hasWifi = true;
refThirteen.hasParking = true;
refThirteen.hasOutdoorSeating = true;
refThirteen.hasDelivery = true;
refThirteen.hasTakeaway = true;
refThirteen.hasBuffet = false;
refThirteen.hasBar = false;
refThirteen.cuisineType = "Vegan & Organic";
refThirteen.averageCostPerPerson = 900.00;
refThirteen.ownerName = "Priya Ramesh";
refThirteen.managerName = "Anil Sharma";
refThirteen.contactNumber = "9988774455";
refThirteen.email = "info@thegreenleaf.com";
refThirteen.website = "www.thegreenleaf.com";
refThirteen.establishedYear = 2020;
refThirteen.isFamilyFriendly = true;
refThirteen.hasLiveMusic = false;
refThirteen.rating = "4.5/5";

System.out.println("The restaurantId is: " + refThirteen.restaurantId);
System.out.println("The restaurantName is: " + refThirteen.restaurantName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfTables is: " + refThirteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refThirteen.numberOfChairs);
System.out.println("The hasWifi is: " + refThirteen.hasWifi);
System.out.println("The hasParking is: " + refThirteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refThirteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refThirteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refThirteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refThirteen.hasBuffet);
System.out.println("The hasBar is: " + refThirteen.hasBar);
System.out.println("The cuisineType is: " + refThirteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refThirteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refThirteen.ownerName);
System.out.println("The managerName is: " + refThirteen.managerName);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refThirteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refThirteen.hasLiveMusic);
System.out.println("The rating is: " + refThirteen.rating);
Restaurant refFourteen = new Restaurant();

System.out.println("The restaurantId is: " + refFourteen.restaurantId);
System.out.println("The restaurantName is: " + refFourteen.restaurantName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfTables is: " + refFourteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refFourteen.numberOfChairs);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refFourteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refFourteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refFourteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refFourteen.hasBuffet);
System.out.println("The hasBar is: " + refFourteen.hasBar);
System.out.println("The cuisineType is: " + refFourteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refFourteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refFourteen.ownerName);
System.out.println("The managerName is: " + refFourteen.managerName);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refFourteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refFourteen.hasLiveMusic);
System.out.println("The rating is: " + refFourteen.rating);

refFourteen.restaurantId = 14;
refFourteen.restaurantName = "Sunrise Diner";
refFourteen.location = "Marine Street";
refFourteen.city = "Pune";
refFourteen.state = "Maharashtra";
refFourteen.country = "India";
refFourteen.numberOfTables = 16;
refFourteen.numberOfChairs = 64;
refFourteen.hasWifi = true;
refFourteen.hasParking = true;
refFourteen.hasOutdoorSeating = true;
refFourteen.hasDelivery = true;
refFourteen.hasTakeaway = true;
refFourteen.hasBuffet = false;
refFourteen.hasBar = false;
refFourteen.cuisineType = "Breakfast & Cafe";
refFourteen.averageCostPerPerson = 550.00;
refFourteen.ownerName = "Rohit Deshpande";
refFourteen.managerName = "Neha Patil";
refFourteen.contactNumber = "9876512340";
refFourteen.email = "contact@sunrisediner.com";
refFourteen.website = "www.sunrisediner.com";
refFourteen.establishedYear = 2018;
refFourteen.isFamilyFriendly = true;
refFourteen.hasLiveMusic = false;
refFourteen.rating = "4.4/5";

System.out.println("The restaurantId is: " + refFourteen.restaurantId);
System.out.println("The restaurantName is: " + refFourteen.restaurantName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfTables is: " + refFourteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refFourteen.numberOfChairs);
System.out.println("The hasWifi is: " + refFourteen.hasWifi);
System.out.println("The hasParking is: " + refFourteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refFourteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refFourteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refFourteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refFourteen.hasBuffet);
System.out.println("The hasBar is: " + refFourteen.hasBar);
System.out.println("The cuisineType is: " + refFourteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refFourteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refFourteen.ownerName);
System.out.println("The managerName is: " + refFourteen.managerName);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refFourteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refFourteen.hasLiveMusic);
System.out.println("The rating is: " + refFourteen.rating);
Restaurant refFifteen = new Restaurant();

System.out.println("The restaurantId is: " + refFifteen.restaurantId);
System.out.println("The restaurantName is: " + refFifteen.restaurantName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfTables is: " + refFifteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refFifteen.numberOfChairs);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refFifteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refFifteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refFifteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refFifteen.hasBuffet);
System.out.println("The hasBar is: " + refFifteen.hasBar);
System.out.println("The cuisineType is: " + refFifteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refFifteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refFifteen.ownerName);
System.out.println("The managerName is: " + refFifteen.managerName);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refFifteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refFifteen.hasLiveMusic);
System.out.println("The rating is: " + refFifteen.rating);

refFifteen.restaurantId = 15;
refFifteen.restaurantName = "Cinnamon Lounge";
refFifteen.location = "City Center";
refFifteen.city = "Hyderabad";
refFifteen.state = "Telangana";
refFifteen.country = "India";
refFifteen.numberOfTables = 20;
refFifteen.numberOfChairs = 80;
refFifteen.hasWifi = true;
refFifteen.hasParking = true;
refFifteen.hasOutdoorSeating = true;
refFifteen.hasDelivery = true;
refFifteen.hasTakeaway = true;
refFifteen.hasBuffet = true;
refFifteen.hasBar = true;
refFifteen.cuisineType = "Asian & Indian Fusion";
refFifteen.averageCostPerPerson = 1200.00;
refFifteen.ownerName = "Srinivas Reddy";
refFifteen.managerName = "Neha Reddy";
refFifteen.contactNumber = "9988771122";
refFifteen.email = "contact@cinnamonlounge.com";
refFifteen.website = "www.cinnamonlounge.com";
refFifteen.establishedYear = 2017;
refFifteen.isFamilyFriendly = true;
refFifteen.hasLiveMusic = true;
refFifteen.rating = "4.7/5";

System.out.println("The restaurantId is: " + refFifteen.restaurantId);
System.out.println("The restaurantName is: " + refFifteen.restaurantName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfTables is: " + refFifteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refFifteen.numberOfChairs);
System.out.println("The hasWifi is: " + refFifteen.hasWifi);
System.out.println("The hasParking is: " + refFifteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refFifteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refFifteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refFifteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refFifteen.hasBuffet);
System.out.println("The hasBar is: " + refFifteen.hasBar);
System.out.println("The cuisineType is: " + refFifteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refFifteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refFifteen.ownerName);
System.out.println("The managerName is: " + refFifteen.managerName);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refFifteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refFifteen.hasLiveMusic);
System.out.println("The rating is: " + refFifteen.rating);
Restaurant refSixteen = new Restaurant();

System.out.println("The restaurantId is: " + refSixteen.restaurantId);
System.out.println("The restaurantName is: " + refSixteen.restaurantName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfTables is: " + refSixteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refSixteen.numberOfChairs);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refSixteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refSixteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refSixteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refSixteen.hasBuffet);
System.out.println("The hasBar is: " + refSixteen.hasBar);
System.out.println("The cuisineType is: " + refSixteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refSixteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refSixteen.ownerName);
System.out.println("The managerName is: " + refSixteen.managerName);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refSixteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refSixteen.hasLiveMusic);
System.out.println("The rating is: " + refSixteen.rating);

refSixteen.restaurantId = 16;
refSixteen.restaurantName = "Lotus Pavilion";
refSixteen.location = "Bandra West";
refSixteen.city = "Mumbai";
refSixteen.state = "Maharashtra";
refSixteen.country = "India";
refSixteen.numberOfTables = 22;
refSixteen.numberOfChairs = 88;
refSixteen.hasWifi = true;
refSixteen.hasParking = true;
refSixteen.hasOutdoorSeating = true;
refSixteen.hasDelivery = true;
refSixteen.hasTakeaway = true;
refSixteen.hasBuffet = true;
refSixteen.hasBar = true;
refSixteen.cuisineType = "Asian & Indian";
refSixteen.averageCostPerPerson = 1450.00;
refSixteen.ownerName = "Rahul Mehta";
refSixteen.managerName = "Anita Shah";
refSixteen.contactNumber = "9988112233";
refSixteen.email = "contact@lotuspavilion.com";
refSixteen.website = "www.lotuspavilion.com";
refSixteen.establishedYear = 2014;
refSixteen.isFamilyFriendly = true;
refSixteen.hasLiveMusic = true;
refSixteen.rating = "4.8/5";

System.out.println("The restaurantId is: " + refSixteen.restaurantId);
System.out.println("The restaurantName is: " + refSixteen.restaurantName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfTables is: " + refSixteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refSixteen.numberOfChairs);
System.out.println("The hasWifi is: " + refSixteen.hasWifi);
System.out.println("The hasParking is: " + refSixteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refSixteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refSixteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refSixteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refSixteen.hasBuffet);
System.out.println("The hasBar is: " + refSixteen.hasBar);
System.out.println("The cuisineType is: " + refSixteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refSixteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refSixteen.ownerName);
System.out.println("The managerName is: " + refSixteen.managerName);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refSixteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refSixteen.hasLiveMusic);
System.out.println("The rating is: " + refSixteen.rating);
Restaurant refSeventeen = new Restaurant();

System.out.println("The restaurantId is: " + refSeventeen.restaurantId);
System.out.println("The restaurantName is: " + refSeventeen.restaurantName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfTables is: " + refSeventeen.numberOfTables);
System.out.println("The numberOfChairs is: " + refSeventeen.numberOfChairs);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refSeventeen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refSeventeen.hasDelivery);
System.out.println("The hasTakeaway is: " + refSeventeen.hasTakeaway);
System.out.println("The hasBuffet is: " + refSeventeen.hasBuffet);
System.out.println("The hasBar is: " + refSeventeen.hasBar);
System.out.println("The cuisineType is: " + refSeventeen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refSeventeen.averageCostPerPerson);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
System.out.println("The managerName is: " + refSeventeen.managerName);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refSeventeen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refSeventeen.hasLiveMusic);
System.out.println("The rating is: " + refSeventeen.rating);

refSeventeen.restaurantId = 17;
refSeventeen.restaurantName = "The Spice Hub";
refSeventeen.location = "MG Road";
refSeventeen.city = "Bengaluru";
refSeventeen.state = "Karnataka";
refSeventeen.country = "India";
refSeventeen.numberOfTables = 20;
refSeventeen.numberOfChairs = 80;
refSeventeen.hasWifi = true;
refSeventeen.hasParking = true;
refSeventeen.hasOutdoorSeating = true;
refSeventeen.hasDelivery = true;
refSeventeen.hasTakeaway = true;
refSeventeen.hasBuffet = false;
refSeventeen.hasBar = true;
refSeventeen.cuisineType = "Indian & Continental";
refSeventeen.averageCostPerPerson = 1150.00;
refSeventeen.ownerName = "Rahul Sharma";
refSeventeen.managerName = "Pooja Verma";
refSeventeen.contactNumber = "9988775544";
refSeventeen.email = "info@thespicehub.com";
refSeventeen.website = "www.thespicehub.com";
refSeventeen.establishedYear = 2016;
refSeventeen.isFamilyFriendly = true;
refSeventeen.hasLiveMusic = true;
refSeventeen.rating = "4.7/5";

System.out.println("The restaurantId is: " + refSeventeen.restaurantId);
System.out.println("The restaurantName is: " + refSeventeen.restaurantName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfTables is: " + refSeventeen.numberOfTables);
System.out.println("The numberOfChairs is: " + refSeventeen.numberOfChairs);
System.out.println("The hasWifi is: " + refSeventeen.hasWifi);
System.out.println("The hasParking is: " + refSeventeen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refSeventeen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refSeventeen.hasDelivery);
System.out.println("The hasTakeaway is: " + refSeventeen.hasTakeaway);
System.out.println("The hasBuffet is: " + refSeventeen.hasBuffet);
System.out.println("The hasBar is: " + refSeventeen.hasBar);
System.out.println("The cuisineType is: " + refSeventeen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refSeventeen.averageCostPerPerson);
System.out.println("The ownerName is: " + refSeventeen.ownerName);
System.out.println("The managerName is: " + refSeventeen.managerName);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refSeventeen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refSeventeen.hasLiveMusic);
System.out.println("The rating is: " + refSeventeen.rating);
Restaurant refEighteen = new Restaurant();

System.out.println("The restaurantId is: " + refEighteen.restaurantId);
System.out.println("The restaurantName is: " + refEighteen.restaurantName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfTables is: " + refEighteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refEighteen.numberOfChairs);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refEighteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refEighteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refEighteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refEighteen.hasBuffet);
System.out.println("The hasBar is: " + refEighteen.hasBar);
System.out.println("The cuisineType is: " + refEighteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refEighteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refEighteen.ownerName);
System.out.println("The managerName is: " + refEighteen.managerName);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refEighteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refEighteen.hasLiveMusic);
System.out.println("The rating is: " + refEighteen.rating);

refEighteen.restaurantId = 18;
refEighteen.restaurantName = "Azure Bay";
refEighteen.location = "Marine Drive";
refEighteen.city = "Kochi";
refEighteen.state = "Kerala";
refEighteen.country = "India";
refEighteen.numberOfTables = 24;
refEighteen.numberOfChairs = 96;
refEighteen.hasWifi = true;
refEighteen.hasParking = true;
refEighteen.hasOutdoorSeating = true;
refEighteen.hasDelivery = true;
refEighteen.hasTakeaway = true;
refEighteen.hasBuffet = true;
refEighteen.hasBar = true;
refEighteen.cuisineType = "Seafood & Continental";
refEighteen.averageCostPerPerson = 1350.00;
refEighteen.ownerName = "Joseph Mathew";
refEighteen.managerName = "Anu Varghese";
refEighteen.contactNumber = "9445566991";
refEighteen.email = "info@azurebay.com";
refEighteen.website = "www.azurebay.com";
refEighteen.establishedYear = 2017;
refEighteen.isFamilyFriendly = true;
refEighteen.hasLiveMusic = true;
refEighteen.rating = "4.7/5";

System.out.println("The restaurantId is: " + refEighteen.restaurantId);
System.out.println("The restaurantName is: " + refEighteen.restaurantName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfTables is: " + refEighteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refEighteen.numberOfChairs);
System.out.println("The hasWifi is: " + refEighteen.hasWifi);
System.out.println("The hasParking is: " + refEighteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refEighteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refEighteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refEighteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refEighteen.hasBuffet);
System.out.println("The hasBar is: " + refEighteen.hasBar);
System.out.println("The cuisineType is: " + refEighteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refEighteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refEighteen.ownerName);
System.out.println("The managerName is: " + refEighteen.managerName);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refEighteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refEighteen.hasLiveMusic);
System.out.println("The rating is: " + refEighteen.rating);
Restaurant refNineteen = new Restaurant();

System.out.println("The restaurantId is: " + refNineteen.restaurantId);
System.out.println("The restaurantName is: " + refNineteen.restaurantName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfTables is: " + refNineteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refNineteen.numberOfChairs);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refNineteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refNineteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refNineteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refNineteen.hasBuffet);
System.out.println("The hasBar is: " + refNineteen.hasBar);
System.out.println("The cuisineType is: " + refNineteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refNineteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refNineteen.ownerName);
System.out.println("The managerName is: " + refNineteen.managerName);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refNineteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refNineteen.hasLiveMusic);
System.out.println("The rating is: " + refNineteen.rating);

refNineteen.restaurantId = 19;
refNineteen.restaurantName = "Golden Spoon";
refNineteen.location = "Hitech City";
refNineteen.city = "Hyderabad";
refNineteen.state = "Telangana";
refNineteen.country = "India";
refNineteen.numberOfTables = 18;
refNineteen.numberOfChairs = 72;
refNineteen.hasWifi = true;
refNineteen.hasParking = true;
refNineteen.hasOutdoorSeating = true;
refNineteen.hasDelivery = true;
refNineteen.hasTakeaway = true;
refNineteen.hasBuffet = true;
refNineteen.hasBar = true;
refNineteen.cuisineType = "Indian & Asian Fusion";
refNineteen.averageCostPerPerson = 1250.00;
refNineteen.ownerName = "Vikram Reddy";
refNineteen.managerName = "Meera Reddy";
refNineteen.contactNumber = "9988776655";
refNineteen.email = "info@goldenspoon.com";
refNineteen.website = "www.goldenspoon.com";
refNineteen.establishedYear = 2015;
refNineteen.isFamilyFriendly = true;
refNineteen.hasLiveMusic = true;
refNineteen.rating = "4.7/5";

System.out.println("The restaurantId is: " + refNineteen.restaurantId);
System.out.println("The restaurantName is: " + refNineteen.restaurantName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfTables is: " + refNineteen.numberOfTables);
System.out.println("The numberOfChairs is: " + refNineteen.numberOfChairs);
System.out.println("The hasWifi is: " + refNineteen.hasWifi);
System.out.println("The hasParking is: " + refNineteen.hasParking);
System.out.println("The hasOutdoorSeating is: " + refNineteen.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refNineteen.hasDelivery);
System.out.println("The hasTakeaway is: " + refNineteen.hasTakeaway);
System.out.println("The hasBuffet is: " + refNineteen.hasBuffet);
System.out.println("The hasBar is: " + refNineteen.hasBar);
System.out.println("The cuisineType is: " + refNineteen.cuisineType);
System.out.println("The averageCostPerPerson is: " + refNineteen.averageCostPerPerson);
System.out.println("The ownerName is: " + refNineteen.ownerName);
System.out.println("The managerName is: " + refNineteen.managerName);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The isFamilyFriendly is: " + refNineteen.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refNineteen.hasLiveMusic);
System.out.println("The rating is: " + refNineteen.rating);
Restaurant refTwenty = new Restaurant();

System.out.println("The restaurantId is: " + refTwenty.restaurantId);
System.out.println("The restaurantName is: " + refTwenty.restaurantName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfTables is: " + refTwenty.numberOfTables);
System.out.println("The numberOfChairs is: " + refTwenty.numberOfChairs);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasOutdoorSeating is: " + refTwenty.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refTwenty.hasDelivery);
System.out.println("The hasTakeaway is: " + refTwenty.hasTakeaway);
System.out.println("The hasBuffet is: " + refTwenty.hasBuffet);
System.out.println("The hasBar is: " + refTwenty.hasBar);
System.out.println("The cuisineType is: " + refTwenty.cuisineType);
System.out.println("The averageCostPerPerson is: " + refTwenty.averageCostPerPerson);
System.out.println("The ownerName is: " + refTwenty.ownerName);
System.out.println("The managerName is: " + refTwenty.managerName);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The isFamilyFriendly is: " + refTwenty.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refTwenty.hasLiveMusic);
System.out.println("The rating is: " + refTwenty.rating);

refTwenty.restaurantId = 20;
refTwenty.restaurantName = "Cocoa Lounge";
refTwenty.location = "Brigade Road";
refTwenty.city = "Bengaluru";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.numberOfTables = 18;
refTwenty.numberOfChairs = 72;
refTwenty.hasWifi = true;
refTwenty.hasParking = true;
refTwenty.hasOutdoorSeating = true;
refTwenty.hasDelivery = true;
refTwenty.hasTakeaway = true;
refTwenty.hasBuffet = false;
refTwenty.hasBar = true;
refTwenty.cuisineType = "Desserts & Cafe";
refTwenty.averageCostPerPerson = 700.00;
refTwenty.ownerName = "Manish Kapoor";
refTwenty.managerName = "Sonal Verma";
refTwenty.contactNumber = "9988773344";
refTwenty.email = "contact@cocoalounge.com";
refTwenty.website = "www.cocoalounge.com";
refTwenty.establishedYear = 2019;
refTwenty.isFamilyFriendly = true;
refTwenty.hasLiveMusic = false;
refTwenty.rating = "4.5/5";

System.out.println("The restaurantId is: " + refTwenty.restaurantId);
System.out.println("The restaurantName is: " + refTwenty.restaurantName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfTables is: " + refTwenty.numberOfTables);
System.out.println("The numberOfChairs is: " + refTwenty.numberOfChairs);
System.out.println("The hasWifi is: " + refTwenty.hasWifi);
System.out.println("The hasParking is: " + refTwenty.hasParking);
System.out.println("The hasOutdoorSeating is: " + refTwenty.hasOutdoorSeating);
System.out.println("The hasDelivery is: " + refTwenty.hasDelivery);
System.out.println("The hasTakeaway is: " + refTwenty.hasTakeaway);
System.out.println("The hasBuffet is: " + refTwenty.hasBuffet);
System.out.println("The hasBar is: " + refTwenty.hasBar);
System.out.println("The cuisineType is: " + refTwenty.cuisineType);
System.out.println("The averageCostPerPerson is: " + refTwenty.averageCostPerPerson);
System.out.println("The ownerName is: " + refTwenty.ownerName);
System.out.println("The managerName is: " + refTwenty.managerName);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The isFamilyFriendly is: " + refTwenty.isFamilyFriendly);
System.out.println("The hasLiveMusic is: " + refTwenty.hasLiveMusic);
System.out.println("The rating is: " + refTwenty.rating);
}
}