class SchoolExecutor{
public static void main(String[] args){
School refOne = new School();

System.out.println("The schoolId is: " + refOne.schoolId);
System.out.println("The schoolName is: " + refOne.schoolName);
System.out.println("The principalName is: " + refOne.principalName);
System.out.println("The vicePrincipalName is: " + refOne.vicePrincipalName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfTeachers is: " + refOne.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refOne.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refOne.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refOne.hasLibrary);
System.out.println("The hasLaboratory is: " + refOne.hasLaboratory);
System.out.println("The hasPlayground is: " + refOne.hasPlayground);
System.out.println("The hasCafeteria is: " + refOne.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refOne.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refOne.hasComputerLab);
System.out.println("The hasScienceLab is: " + refOne.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refOne.hasMusicRoom);
System.out.println("The schoolType is: " + refOne.schoolType);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The accreditation is: " + refOne.accreditation);


refOne.schoolId = 1;
refOne.schoolName = "Green Valley School";
refOne.principalName = "Ramesh Sharma";
refOne.vicePrincipalName = "Anita Rao";
refOne.location = "MG Road";
refOne.city = "Bengaluru";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfTeachers = 60;
refOne.numberOfStudents = 1200;
refOne.numberOfClassrooms = 40;
refOne.hasLibrary = true;
refOne.hasLaboratory = true;
refOne.hasPlayground = true;
refOne.hasCafeteria = true;
refOne.hasTransportFacility = true;
refOne.hasComputerLab = true;
refOne.hasScienceLab = true;
refOne.hasMusicRoom = true;
refOne.schoolType = "Private";
refOne.establishedYear = 2005;
refOne.contactNumber = "9876543210";
refOne.email = "info@greenvalleyschool.com";
refOne.website = "www.greenvalleyschool.com";
refOne.accreditation = "CBSE";


System.out.println("The schoolId is: " + refOne.schoolId);
System.out.println("The schoolName is: " + refOne.schoolName);
System.out.println("The principalName is: " + refOne.principalName);
System.out.println("The vicePrincipalName is: " + refOne.vicePrincipalName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfTeachers is: " + refOne.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refOne.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refOne.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refOne.hasLibrary);
System.out.println("The hasLaboratory is: " + refOne.hasLaboratory);
System.out.println("The hasPlayground is: " + refOne.hasPlayground);
System.out.println("The hasCafeteria is: " + refOne.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refOne.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refOne.hasComputerLab);
System.out.println("The hasScienceLab is: " + refOne.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refOne.hasMusicRoom);
System.out.println("The schoolType is: " + refOne.schoolType);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The accreditation is: " + refOne.accreditation);
School refTwo = new School();

System.out.println("The schoolId is: " + refTwo.schoolId);
System.out.println("The schoolName is: " + refTwo.schoolName);
System.out.println("The principalName is: " + refTwo.principalName);
System.out.println("The vicePrincipalName is: " + refTwo.vicePrincipalName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfTeachers is: " + refTwo.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refTwo.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refTwo.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refTwo.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwo.hasLaboratory);
System.out.println("The hasPlayground is: " + refTwo.hasPlayground);
System.out.println("The hasCafeteria is: " + refTwo.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refTwo.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refTwo.hasComputerLab);
System.out.println("The hasScienceLab is: " + refTwo.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refTwo.hasMusicRoom);
System.out.println("The schoolType is: " + refTwo.schoolType);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The accreditation is: " + refTwo.accreditation);

refTwo.schoolId = 2;
refTwo.schoolName = "Sunrise Public School";
refTwo.principalName = "Lakshmi Narayan";
refTwo.vicePrincipalName = "Deepa Shetty";
refTwo.location = "Jayanagar";
refTwo.city = "Bengaluru";
refTwo.state = "Karnataka";
refTwo.country = "India";
refTwo.numberOfTeachers = 55;
refTwo.numberOfStudents = 1100;
refTwo.numberOfClassrooms = 38;
refTwo.hasLibrary = true;
refTwo.hasLaboratory = true;
refTwo.hasPlayground = true;
refTwo.hasCafeteria = false;
refTwo.hasTransportFacility = true;
refTwo.hasComputerLab = true;
refTwo.hasScienceLab = true;
refTwo.hasMusicRoom = false;
refTwo.schoolType = "Private";
refTwo.establishedYear = 2010;
refTwo.contactNumber = "9845012345";
refTwo.email = "contact@sunriseps.com";
refTwo.website = "www.sunriseps.com";
refTwo.accreditation = "ICSE";

System.out.println("The schoolId is: " + refTwo.schoolId);
System.out.println("The schoolName is: " + refTwo.schoolName);
System.out.println("The principalName is: " + refTwo.principalName);
System.out.println("The vicePrincipalName is: " + refTwo.vicePrincipalName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfTeachers is: " + refTwo.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refTwo.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refTwo.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refTwo.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwo.hasLaboratory);
System.out.println("The hasPlayground is: " + refTwo.hasPlayground);
System.out.println("The hasCafeteria is: " + refTwo.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refTwo.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refTwo.hasComputerLab);
System.out.println("The hasScienceLab is: " + refTwo.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refTwo.hasMusicRoom);
System.out.println("The schoolType is: " + refTwo.schoolType);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The accreditation is: " + refTwo.accreditation);
School refThree = new School();

System.out.println("The schoolId is: " + refThree.schoolId);
System.out.println("The schoolName is: " + refThree.schoolName);
System.out.println("The principalName is: " + refThree.principalName);
System.out.println("The vicePrincipalName is: " + refThree.vicePrincipalName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfTeachers is: " + refThree.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refThree.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refThree.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refThree.hasLibrary);
System.out.println("The hasLaboratory is: " + refThree.hasLaboratory);
System.out.println("The hasPlayground is: " + refThree.hasPlayground);
System.out.println("The hasCafeteria is: " + refThree.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refThree.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refThree.hasComputerLab);
System.out.println("The hasScienceLab is: " + refThree.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refThree.hasMusicRoom);
System.out.println("The schoolType is: " + refThree.schoolType);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The accreditation is: " + refThree.accreditation);


refThree.schoolId = 3;
refThree.schoolName = "Bright Future School";
refThree.principalName = "Suresh Kumar";
refThree.vicePrincipalName = "Meena Nair";
refThree.location = "Indiranagar";
refThree.city = "Bengaluru";
refThree.state = "Karnataka";
refThree.country = "India";
refThree.numberOfTeachers = 48;
refThree.numberOfStudents = 980;
refThree.numberOfClassrooms = 32;
refThree.hasLibrary = true;
refThree.hasLaboratory = true;
refThree.hasPlayground = true;
refThree.hasCafeteria = true;
refThree.hasTransportFacility = true;
refThree.hasComputerLab = true;
refThree.hasScienceLab = true;
refThree.hasMusicRoom = true;
refThree.schoolType = "Private";
refThree.establishedYear = 2012;
refThree.contactNumber = "9871234560";
refThree.email = "info@brightfuture.edu";
refThree.website = "www.brightfuture.edu";
refThree.accreditation = "CBSE";


System.out.println("The schoolId is: " + refThree.schoolId);
System.out.println("The schoolName is: " + refThree.schoolName);
System.out.println("The principalName is: " + refThree.principalName);
System.out.println("The vicePrincipalName is: " + refThree.vicePrincipalName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfTeachers is: " + refThree.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refThree.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refThree.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refThree.hasLibrary);
System.out.println("The hasLaboratory is: " + refThree.hasLaboratory);
System.out.println("The hasPlayground is: " + refThree.hasPlayground);
System.out.println("The hasCafeteria is: " + refThree.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refThree.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refThree.hasComputerLab);
System.out.println("The hasScienceLab is: " + refThree.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refThree.hasMusicRoom);
System.out.println("The schoolType is: " + refThree.schoolType);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The accreditation is: " + refThree.accreditation);
School refFour = new School();

System.out.println("The schoolId is: " + refFour.schoolId);
System.out.println("The schoolName is: " + refFour.schoolName);
System.out.println("The principalName is: " + refFour.principalName);
System.out.println("The vicePrincipalName is: " + refFour.vicePrincipalName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfTeachers is: " + refFour.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refFour.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refFour.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refFour.hasLibrary);
System.out.println("The hasLaboratory is: " + refFour.hasLaboratory);
System.out.println("The hasPlayground is: " + refFour.hasPlayground);
System.out.println("The hasCafeteria is: " + refFour.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refFour.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refFour.hasComputerLab);
System.out.println("The hasScienceLab is: " + refFour.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refFour.hasMusicRoom);
System.out.println("The schoolType is: " + refFour.schoolType);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The accreditation is: " + refFour.accreditation);

refFour.schoolId = 4;
refFour.schoolName = "National Public School";
refFour.principalName = "Anil Kumar";
refFour.vicePrincipalName = "Priya Menon";
refFour.location = "Rajajinagar";
refFour.city = "Bengaluru";
refFour.state = "Karnataka";
refFour.country = "India";
refFour.numberOfTeachers = 70;
refFour.numberOfStudents = 1500;
refFour.numberOfClassrooms = 45;
refFour.hasLibrary = true;
refFour.hasLaboratory = true;
refFour.hasPlayground = true;
refFour.hasCafeteria = true;
refFour.hasTransportFacility = true;
refFour.hasComputerLab = true;
refFour.hasScienceLab = true;
refFour.hasMusicRoom = false;
refFour.schoolType = "Private";
refFour.establishedYear = 2008;
refFour.contactNumber = "9898765432";
refFour.email = "info@nps.edu";
refFour.website = "www.nps.edu";
refFour.accreditation = "CBSE";

System.out.println("The schoolId is: " + refFour.schoolId);
System.out.println("The schoolName is: " + refFour.schoolName);
System.out.println("The principalName is: " + refFour.principalName);
System.out.println("The vicePrincipalName is: " + refFour.vicePrincipalName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfTeachers is: " + refFour.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refFour.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refFour.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refFour.hasLibrary);
System.out.println("The hasLaboratory is: " + refFour.hasLaboratory);
System.out.println("The hasPlayground is: " + refFour.hasPlayground);
System.out.println("The hasCafeteria is: " + refFour.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refFour.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refFour.hasComputerLab);
System.out.println("The hasScienceLab is: " + refFour.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refFour.hasMusicRoom);
System.out.println("The schoolType is: " + refFour.schoolType);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The accreditation is: " + refFour.accreditation);
School refFive = new School();

System.out.println("The schoolId is: " + refFive.schoolId);
System.out.println("The schoolName is: " + refFive.schoolName);
System.out.println("The principalName is: " + refFive.principalName);
System.out.println("The vicePrincipalName is: " + refFive.vicePrincipalName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfTeachers is: " + refFive.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refFive.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refFive.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refFive.hasLibrary);
System.out.println("The hasLaboratory is: " + refFive.hasLaboratory);
System.out.println("The hasPlayground is: " + refFive.hasPlayground);
System.out.println("The hasCafeteria is: " + refFive.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refFive.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refFive.hasComputerLab);
System.out.println("The hasScienceLab is: " + refFive.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refFive.hasMusicRoom);
System.out.println("The schoolType is: " + refFive.schoolType);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The accreditation is: " + refFive.accreditation);

refFive.schoolId = 5;
refFive.schoolName = "St. Mary's High School";
refFive.principalName = "Joseph D'Souza";
refFive.vicePrincipalName = "Mary Fernandes";
refFive.location = "Frazer Town";
refFive.city = "Bengaluru";
refFive.state = "Karnataka";
refFive.country = "India";
refFive.numberOfTeachers = 52;
refFive.numberOfStudents = 1050;
refFive.numberOfClassrooms = 36;
refFive.hasLibrary = true;
refFive.hasLaboratory = true;
refFive.hasPlayground = true;
refFive.hasCafeteria = false;
refFive.hasTransportFacility = true;
refFive.hasComputerLab = true;
refFive.hasScienceLab = true;
refFive.hasMusicRoom = true;
refFive.schoolType = "Private";
refFive.establishedYear = 1998;
refFive.contactNumber = "9812345678";
refFive.email = "info@stmaryschool.edu";
refFive.website = "www.stmaryschool.edu";
refFive.accreditation = "ICSE";

System.out.println("The schoolId is: " + refFive.schoolId);
System.out.println("The schoolName is: " + refFive.schoolName);
System.out.println("The principalName is: " + refFive.principalName);
System.out.println("The vicePrincipalName is: " + refFive.vicePrincipalName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfTeachers is: " + refFive.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refFive.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refFive.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refFive.hasLibrary);
System.out.println("The hasLaboratory is: " + refFive.hasLaboratory);
System.out.println("The hasPlayground is: " + refFive.hasPlayground);
System.out.println("The hasCafeteria is: " + refFive.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refFive.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refFive.hasComputerLab);
System.out.println("The hasScienceLab is: " + refFive.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refFive.hasMusicRoom);
System.out.println("The schoolType is: " + refFive.schoolType);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The accreditation is: " + refFive.accreditation);
School refSix = new School();

System.out.println("The schoolId is: " + refSix.schoolId);
System.out.println("The schoolName is: " + refSix.schoolName);
System.out.println("The principalName is: " + refSix.principalName);
System.out.println("The vicePrincipalName is: " + refSix.vicePrincipalName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfTeachers is: " + refSix.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refSix.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refSix.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refSix.hasLibrary);
System.out.println("The hasLaboratory is: " + refSix.hasLaboratory);
System.out.println("The hasPlayground is: " + refSix.hasPlayground);
System.out.println("The hasCafeteria is: " + refSix.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refSix.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refSix.hasComputerLab);
System.out.println("The hasScienceLab is: " + refSix.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refSix.hasMusicRoom);
System.out.println("The schoolType is: " + refSix.schoolType);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The accreditation is: " + refSix.accreditation);

refSix.schoolId = 6;
refSix.schoolName = "Royal International School";
refSix.principalName = "Vijay Prakash";
refSix.vicePrincipalName = "Shilpa Reddy";
refSix.location = "Whitefield";
refSix.city = "Bengaluru";
refSix.state = "Karnataka";
refSix.country = "India";
refSix.numberOfTeachers = 65;
refSix.numberOfStudents = 1400;
refSix.numberOfClassrooms = 42;
refSix.hasLibrary = true;
refSix.hasLaboratory = true;
refSix.hasPlayground = true;
refSix.hasCafeteria = true;
refSix.hasTransportFacility = true;
refSix.hasComputerLab = true;
refSix.hasScienceLab = true;
refSix.hasMusicRoom = true;
refSix.schoolType = "International";
refSix.establishedYear = 2015;
refSix.contactNumber = "9823456781";
refSix.email = "info@royalinternational.edu";
refSix.website = "www.royalinternational.edu";
refSix.accreditation = "IB";

System.out.println("The schoolId is: " + refSix.schoolId);
System.out.println("The schoolName is: " + refSix.schoolName);
System.out.println("The principalName is: " + refSix.principalName);
System.out.println("The vicePrincipalName is: " + refSix.vicePrincipalName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfTeachers is: " + refSix.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refSix.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refSix.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refSix.hasLibrary);
System.out.println("The hasLaboratory is: " + refSix.hasLaboratory);
System.out.println("The hasPlayground is: " + refSix.hasPlayground);
System.out.println("The hasCafeteria is: " + refSix.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refSix.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refSix.hasComputerLab);
System.out.println("The hasScienceLab is: " + refSix.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refSix.hasMusicRoom);
System.out.println("The schoolType is: " + refSix.schoolType);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The accreditation is: " + refSix.accreditation);
School refSeven = new School();

System.out.println("The schoolId is: " + refSeven.schoolId);
System.out.println("The schoolName is: " + refSeven.schoolName);
System.out.println("The principalName is: " + refSeven.principalName);
System.out.println("The vicePrincipalName is: " + refSeven.vicePrincipalName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfTeachers is: " + refSeven.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refSeven.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refSeven.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refSeven.hasLibrary);
System.out.println("The hasLaboratory is: " + refSeven.hasLaboratory);
System.out.println("The hasPlayground is: " + refSeven.hasPlayground);
System.out.println("The hasCafeteria is: " + refSeven.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refSeven.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refSeven.hasComputerLab);
System.out.println("The hasScienceLab is: " + refSeven.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refSeven.hasMusicRoom);
System.out.println("The schoolType is: " + refSeven.schoolType);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The accreditation is: " + refSeven.accreditation);

refSeven.schoolId = 7;
refSeven.schoolName = "Little Flower High School";
refSeven.principalName = "Thomas Mathew";
refSeven.vicePrincipalName = "Latha Joseph";
refSeven.location = "BTM Layout";
refSeven.city = "Bengaluru";
refSeven.state = "Karnataka";
refSeven.country = "India";
refSeven.numberOfTeachers = 50;
refSeven.numberOfStudents = 1000;
refSeven.numberOfClassrooms = 34;
refSeven.hasLibrary = true;
refSeven.hasLaboratory = true;
refSeven.hasPlayground = true;
refSeven.hasCafeteria = false;
refSeven.hasTransportFacility = true;
refSeven.hasComputerLab = true;
refSeven.hasScienceLab = true;
refSeven.hasMusicRoom = false;
refSeven.schoolType = "Private";
refSeven.establishedYear = 2001;
refSeven.contactNumber = "9834567890";
refSeven.email = "info@littleflower.edu";
refSeven.website = "www.littleflower.edu";
refSeven.accreditation = "ICSE";

System.out.println("The schoolId is: " + refSeven.schoolId);
System.out.println("The schoolName is: " + refSeven.schoolName);
System.out.println("The principalName is: " + refSeven.principalName);
System.out.println("The vicePrincipalName is: " + refSeven.vicePrincipalName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfTeachers is: " + refSeven.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refSeven.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refSeven.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refSeven.hasLibrary);
System.out.println("The hasLaboratory is: " + refSeven.hasLaboratory);
System.out.println("The hasPlayground is: " + refSeven.hasPlayground);
System.out.println("The hasCafeteria is: " + refSeven.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refSeven.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refSeven.hasComputerLab);
System.out.println("The hasScienceLab is: " + refSeven.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refSeven.hasMusicRoom);
System.out.println("The schoolType is: " + refSeven.schoolType);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The accreditation is: " + refSeven.accreditation);
School refEight = new School();

System.out.println("The schoolId is: " + refEight.schoolId);
System.out.println("The schoolName is: " + refEight.schoolName);
System.out.println("The principalName is: " + refEight.principalName);
System.out.println("The vicePrincipalName is: " + refEight.vicePrincipalName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfTeachers is: " + refEight.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refEight.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refEight.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refEight.hasLibrary);
System.out.println("The hasLaboratory is: " + refEight.hasLaboratory);
System.out.println("The hasPlayground is: " + refEight.hasPlayground);
System.out.println("The hasCafeteria is: " + refEight.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refEight.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refEight.hasComputerLab);
System.out.println("The hasScienceLab is: " + refEight.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refEight.hasMusicRoom);
System.out.println("The schoolType is: " + refEight.schoolType);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The accreditation is: " + refEight.accreditation);

refEight.schoolId = 8;
refEight.schoolName = "Oxford Public School";
refEight.principalName = "Rahul Verma";
refEight.vicePrincipalName = "Sneha Kapoor";
refEight.location = "Yelahanka";
refEight.city = "Bengaluru";
refEight.state = "Karnataka";
refEight.country = "India";
refEight.numberOfTeachers = 58;
refEight.numberOfStudents = 1250;
refEight.numberOfClassrooms = 39;
refEight.hasLibrary = true;
refEight.hasLaboratory = true;
refEight.hasPlayground = true;
refEight.hasCafeteria = true;
refEight.hasTransportFacility = true;
refEight.hasComputerLab = true;
refEight.hasScienceLab = true;
refEight.hasMusicRoom = true;
refEight.schoolType = "Private";
refEight.establishedYear = 2011;
refEight.contactNumber = "9845678910";
refEight.email = "info@oxfordpublicschool.edu";
refEight.website = "www.oxfordpublicschool.edu";
refEight.accreditation = "CBSE";

System.out.println("The schoolId is: " + refEight.schoolId);
System.out.println("The schoolName is: " + refEight.schoolName);
System.out.println("The principalName is: " + refEight.principalName);
System.out.println("The vicePrincipalName is: " + refEight.vicePrincipalName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfTeachers is: " + refEight.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refEight.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refEight.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refEight.hasLibrary);
System.out.println("The hasLaboratory is: " + refEight.hasLaboratory);
System.out.println("The hasPlayground is: " + refEight.hasPlayground);
System.out.println("The hasCafeteria is: " + refEight.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refEight.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refEight.hasComputerLab);
System.out.println("The hasScienceLab is: " + refEight.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refEight.hasMusicRoom);
System.out.println("The schoolType is: " + refEight.schoolType);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The accreditation is: " + refEight.accreditation);
School refNine = new School();

System.out.println("The schoolId is: " + refNine.schoolId);
System.out.println("The schoolName is: " + refNine.schoolName);
System.out.println("The principalName is: " + refNine.principalName);
System.out.println("The vicePrincipalName is: " + refNine.vicePrincipalName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfTeachers is: " + refNine.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refNine.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refNine.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refNine.hasLibrary);
System.out.println("The hasLaboratory is: " + refNine.hasLaboratory);
System.out.println("The hasPlayground is: " + refNine.hasPlayground);
System.out.println("The hasCafeteria is: " + refNine.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refNine.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refNine.hasComputerLab);
System.out.println("The hasScienceLab is: " + refNine.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refNine.hasMusicRoom);
System.out.println("The schoolType is: " + refNine.schoolType);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The accreditation is: " + refNine.accreditation);

refNine.schoolId = 9;
refNine.schoolName = "Cambridge High School";
refNine.principalName = "Arvind Rao";
refNine.vicePrincipalName = "Nisha Sharma";
refNine.location = "Electronic City";
refNine.city = "Bengaluru";
refNine.state = "Karnataka";
refNine.country = "India";
refNine.numberOfTeachers = 62;
refNine.numberOfStudents = 1300;
refNine.numberOfClassrooms = 41;
refNine.hasLibrary = true;
refNine.hasLaboratory = true;
refNine.hasPlayground = true;
refNine.hasCafeteria = true;
refNine.hasTransportFacility = true;
refNine.hasComputerLab = true;
refNine.hasScienceLab = true;
refNine.hasMusicRoom = false;
refNine.schoolType = "Private";
refNine.establishedYear = 2009;
refNine.contactNumber = "9876501234";
refNine.email = "info@cambridgehs.edu";
refNine.website = "www.cambridgehs.edu";
refNine.accreditation = "CBSE";

System.out.println("The schoolId is: " + refNine.schoolId);
System.out.println("The schoolName is: " + refNine.schoolName);
System.out.println("The principalName is: " + refNine.principalName);
System.out.println("The vicePrincipalName is: " + refNine.vicePrincipalName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfTeachers is: " + refNine.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refNine.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refNine.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refNine.hasLibrary);
System.out.println("The hasLaboratory is: " + refNine.hasLaboratory);
System.out.println("The hasPlayground is: " + refNine.hasPlayground);
System.out.println("The hasCafeteria is: " + refNine.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refNine.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refNine.hasComputerLab);
System.out.println("The hasScienceLab is: " + refNine.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refNine.hasMusicRoom);
System.out.println("The schoolType is: " + refNine.schoolType);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The accreditation is: " + refNine.accreditation);
School refTen = new School();

System.out.println("The schoolId is: " + refTen.schoolId);
System.out.println("The schoolName is: " + refTen.schoolName);
System.out.println("The principalName is: " + refTen.principalName);
System.out.println("The vicePrincipalName is: " + refTen.vicePrincipalName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfTeachers is: " + refTen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refTen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refTen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refTen.hasLibrary);
System.out.println("The hasLaboratory is: " + refTen.hasLaboratory);
System.out.println("The hasPlayground is: " + refTen.hasPlayground);
System.out.println("The hasCafeteria is: " + refTen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refTen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refTen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refTen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refTen.hasMusicRoom);
System.out.println("The schoolType is: " + refTen.schoolType);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The accreditation is: " + refTen.accreditation);

refTen.schoolId = 10;
refTen.schoolName = "Global Knowledge School";
refTen.principalName = "Kiran Desai";
refTen.vicePrincipalName = "Pooja Nair";
refTen.location = "Hebbal";
refTen.city = "Bengaluru";
refTen.state = "Karnataka";
refTen.country = "India";
refTen.numberOfTeachers = 68;
refTen.numberOfStudents = 1450;
refTen.numberOfClassrooms = 44;
refTen.hasLibrary = true;
refTen.hasLaboratory = true;
refTen.hasPlayground = true;
refTen.hasCafeteria = true;
refTen.hasTransportFacility = true;
refTen.hasComputerLab = true;
refTen.hasScienceLab = true;
refTen.hasMusicRoom = true;
refTen.schoolType = "International";
refTen.establishedYear = 2016;
refTen.contactNumber = "9867543210";
refTen.email = "info@globalknowledge.edu";
refTen.website = "www.globalknowledge.edu";
refTen.accreditation = "IB";

System.out.println("The schoolId is: " + refTen.schoolId);
System.out.println("The schoolName is: " + refTen.schoolName);
System.out.println("The principalName is: " + refTen.principalName);
System.out.println("The vicePrincipalName is: " + refTen.vicePrincipalName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfTeachers is: " + refTen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refTen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refTen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refTen.hasLibrary);
System.out.println("The hasLaboratory is: " + refTen.hasLaboratory);
System.out.println("The hasPlayground is: " + refTen.hasPlayground);
System.out.println("The hasCafeteria is: " + refTen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refTen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refTen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refTen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refTen.hasMusicRoom);
System.out.println("The schoolType is: " + refTen.schoolType);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The accreditation is: " + refTen.accreditation);
School refEleven = new School();

System.out.println("The schoolId is: " + refEleven.schoolId);
System.out.println("The schoolName is: " + refEleven.schoolName);
System.out.println("The principalName is: " + refEleven.principalName);
System.out.println("The vicePrincipalName is: " + refEleven.vicePrincipalName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfTeachers is: " + refEleven.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refEleven.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refEleven.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refEleven.hasLibrary);
System.out.println("The hasLaboratory is: " + refEleven.hasLaboratory);
System.out.println("The hasPlayground is: " + refEleven.hasPlayground);
System.out.println("The hasCafeteria is: " + refEleven.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refEleven.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refEleven.hasComputerLab);
System.out.println("The hasScienceLab is: " + refEleven.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refEleven.hasMusicRoom);
System.out.println("The schoolType is: " + refEleven.schoolType);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The accreditation is: " + refEleven.accreditation);

refEleven.schoolId = 11;
refEleven.schoolName = "Silver Oak School";
refEleven.principalName = "Mahesh Bhat";
refEleven.vicePrincipalName = "Radhika Iyer";
refEleven.location = "Banashankari";
refEleven.city = "Bengaluru";
refEleven.state = "Karnataka";
refEleven.country = "India";
refEleven.numberOfTeachers = 54;
refEleven.numberOfStudents = 1120;
refEleven.numberOfClassrooms = 35;
refEleven.hasLibrary = true;
refEleven.hasLaboratory = true;
refEleven.hasPlayground = true;
refEleven.hasCafeteria = false;
refEleven.hasTransportFacility = true;
refEleven.hasComputerLab = true;
refEleven.hasScienceLab = true;
refEleven.hasMusicRoom = true;
refEleven.schoolType = "Private";
refEleven.establishedYear = 2007;
refEleven.contactNumber = "9843215678";
refEleven.email = "info@silveroakschool.edu";
refEleven.website = "www.silveroakschool.edu";
refEleven.accreditation = "CBSE";

System.out.println("The schoolId is: " + refEleven.schoolId);
System.out.println("The schoolName is: " + refEleven.schoolName);
System.out.println("The principalName is: " + refEleven.principalName);
System.out.println("The vicePrincipalName is: " + refEleven.vicePrincipalName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfTeachers is: " + refEleven.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refEleven.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refEleven.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refEleven.hasLibrary);
System.out.println("The hasLaboratory is: " + refEleven.hasLaboratory);
System.out.println("The hasPlayground is: " + refEleven.hasPlayground);
System.out.println("The hasCafeteria is: " + refEleven.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refEleven.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refEleven.hasComputerLab);
System.out.println("The hasScienceLab is: " + refEleven.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refEleven.hasMusicRoom);
System.out.println("The schoolType is: " + refEleven.schoolType);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The accreditation is: " + refEleven.accreditation);
School refTwelve = new School();

System.out.println("The schoolId is: " + refTwelve.schoolId);
System.out.println("The schoolName is: " + refTwelve.schoolName);
System.out.println("The principalName is: " + refTwelve.principalName);
System.out.println("The vicePrincipalName is: " + refTwelve.vicePrincipalName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfTeachers is: " + refTwelve.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refTwelve.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refTwelve.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refTwelve.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwelve.hasLaboratory);
System.out.println("The hasPlayground is: " + refTwelve.hasPlayground);
System.out.println("The hasCafeteria is: " + refTwelve.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refTwelve.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refTwelve.hasComputerLab);
System.out.println("The hasScienceLab is: " + refTwelve.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refTwelve.hasMusicRoom);
System.out.println("The schoolType is: " + refTwelve.schoolType);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The accreditation is: " + refTwelve.accreditation);

refTwelve.schoolId = 12;
refTwelve.schoolName = "Delhi Public School";
refTwelve.principalName = "Sanjay Gupta";
refTwelve.vicePrincipalName = "Anjali Mehta";
refTwelve.location = "Sarjapur Road";
refTwelve.city = "Bengaluru";
refTwelve.state = "Karnataka";
refTwelve.country = "India";
refTwelve.numberOfTeachers = 75;
refTwelve.numberOfStudents = 1600;
refTwelve.numberOfClassrooms = 48;
refTwelve.hasLibrary = true;
refTwelve.hasLaboratory = true;
refTwelve.hasPlayground = true;
refTwelve.hasCafeteria = true;
refTwelve.hasTransportFacility = true;
refTwelve.hasComputerLab = true;
refTwelve.hasScienceLab = true;
refTwelve.hasMusicRoom = true;
refTwelve.schoolType = "Private";
refTwelve.establishedYear = 2013;
refTwelve.contactNumber = "9890011223";
refTwelve.email = "info@dpsschool.edu";
refTwelve.website = "www.dpsschool.edu";
refTwelve.accreditation = "CBSE";

System.out.println("The schoolId is: " + refTwelve.schoolId);
System.out.println("The schoolName is: " + refTwelve.schoolName);
System.out.println("The principalName is: " + refTwelve.principalName);
System.out.println("The vicePrincipalName is: " + refTwelve.vicePrincipalName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfTeachers is: " + refTwelve.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refTwelve.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refTwelve.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refTwelve.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwelve.hasLaboratory);
System.out.println("The hasPlayground is: " + refTwelve.hasPlayground);
System.out.println("The hasCafeteria is: " + refTwelve.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refTwelve.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refTwelve.hasComputerLab);
System.out.println("The hasScienceLab is: " + refTwelve.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refTwelve.hasMusicRoom);
System.out.println("The schoolType is: " + refTwelve.schoolType);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The accreditation is: " + refTwelve.accreditation);
School refThirteen = new School();

System.out.println("The schoolId is: " + refThirteen.schoolId);
System.out.println("The schoolName is: " + refThirteen.schoolName);
System.out.println("The principalName is: " + refThirteen.principalName);
System.out.println("The vicePrincipalName is: " + refThirteen.vicePrincipalName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfTeachers is: " + refThirteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refThirteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refThirteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refThirteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refThirteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refThirteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refThirteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refThirteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refThirteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refThirteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refThirteen.hasMusicRoom);
System.out.println("The schoolType is: " + refThirteen.schoolType);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The accreditation is: " + refThirteen.accreditation);

refThirteen.schoolId = 13;
refThirteen.schoolName = "Harmony International School";
refThirteen.principalName = "Deepak Menon";
refThirteen.vicePrincipalName = "Kavita Sharma";
refThirteen.location = "Marathahalli";
refThirteen.city = "Bengaluru";
refThirteen.state = "Karnataka";
refThirteen.country = "India";
refThirteen.numberOfTeachers = 72;
refThirteen.numberOfStudents = 1500;
refThirteen.numberOfClassrooms = 46;
refThirteen.hasLibrary = true;
refThirteen.hasLaboratory = true;
refThirteen.hasPlayground = true;
refThirteen.hasCafeteria = true;
refThirteen.hasTransportFacility = true;
refThirteen.hasComputerLab = true;
refThirteen.hasScienceLab = true;
refThirteen.hasMusicRoom = true;
refThirteen.schoolType = "International";
refThirteen.establishedYear = 2014;
refThirteen.contactNumber = "9871122334";
refThirteen.email = "info@harmonyschool.edu";
refThirteen.website = "www.harmonyschool.edu";
refThirteen.accreditation = "IB";

System.out.println("The schoolId is: " + refThirteen.schoolId);
System.out.println("The schoolName is: " + refThirteen.schoolName);
System.out.println("The principalName is: " + refThirteen.principalName);
System.out.println("The vicePrincipalName is: " + refThirteen.vicePrincipalName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfTeachers is: " + refThirteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refThirteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refThirteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refThirteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refThirteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refThirteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refThirteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refThirteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refThirteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refThirteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refThirteen.hasMusicRoom);
System.out.println("The schoolType is: " + refThirteen.schoolType);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The accreditation is: " + refThirteen.accreditation);
School refFourteen = new School();

System.out.println("The schoolId is: " + refFourteen.schoolId);
System.out.println("The schoolName is: " + refFourteen.schoolName);
System.out.println("The principalName is: " + refFourteen.principalName);
System.out.println("The vicePrincipalName is: " + refFourteen.vicePrincipalName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfTeachers is: " + refFourteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refFourteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refFourteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refFourteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refFourteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refFourteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refFourteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refFourteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refFourteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refFourteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refFourteen.hasMusicRoom);
System.out.println("The schoolType is: " + refFourteen.schoolType);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The accreditation is: " + refFourteen.accreditation);

refFourteen.schoolId = 14;
refFourteen.schoolName = "Springfield High School";
refFourteen.principalName = "Rajesh Khanna";
refFourteen.vicePrincipalName = "Neha Agarwal";
refFourteen.location = "Koramangala";
refFourteen.city = "Bengaluru";
refFourteen.state = "Karnataka";
refFourteen.country = "India";
refFourteen.numberOfTeachers = 64;
refFourteen.numberOfStudents = 1350;
refFourteen.numberOfClassrooms = 40;
refFourteen.hasLibrary = true;
refFourteen.hasLaboratory = true;
refFourteen.hasPlayground = true;
refFourteen.hasCafeteria = true;
refFourteen.hasTransportFacility = true;
refFourteen.hasComputerLab = true;
refFourteen.hasScienceLab = true;
refFourteen.hasMusicRoom = false;
refFourteen.schoolType = "Private";
refFourteen.establishedYear = 2010;
refFourteen.contactNumber = "9811223344";
refFourteen.email = "info@springfieldschool.edu";
refFourteen.website = "www.springfieldschool.edu";
refFourteen.accreditation = "CBSE";

System.out.println("The schoolId is: " + refFourteen.schoolId);
System.out.println("The schoolName is: " + refFourteen.schoolName);
System.out.println("The principalName is: " + refFourteen.principalName);
System.out.println("The vicePrincipalName is: " + refFourteen.vicePrincipalName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfTeachers is: " + refFourteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refFourteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refFourteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refFourteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refFourteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refFourteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refFourteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refFourteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refFourteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refFourteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refFourteen.hasMusicRoom);
System.out.println("The schoolType is: " + refFourteen.schoolType);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The accreditation is: " + refFourteen.accreditation);
School refFifteen = new School();

System.out.println("The schoolId is: " + refFifteen.schoolId);
System.out.println("The schoolName is: " + refFifteen.schoolName);
System.out.println("The principalName is: " + refFifteen.principalName);
System.out.println("The vicePrincipalName is: " + refFifteen.vicePrincipalName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfTeachers is: " + refFifteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refFifteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refFifteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refFifteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refFifteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refFifteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refFifteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refFifteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refFifteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refFifteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refFifteen.hasMusicRoom);
System.out.println("The schoolType is: " + refFifteen.schoolType);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The accreditation is: " + refFifteen.accreditation);

refFifteen.schoolId = 15;
refFifteen.schoolName = "Evergreen Public School";
refFifteen.principalName = "Vikram Singh";
refFifteen.vicePrincipalName = "Asha Rani";
refFifteen.location = "Malleshwaram";
refFifteen.city = "Bengaluru";
refFifteen.state = "Karnataka";
refFifteen.country = "India";
refFifteen.numberOfTeachers = 59;
refFifteen.numberOfStudents = 1180;
refFifteen.numberOfClassrooms = 37;
refFifteen.hasLibrary = true;
refFifteen.hasLaboratory = true;
refFifteen.hasPlayground = true;
refFifteen.hasCafeteria = false;
refFifteen.hasTransportFacility = true;
refFifteen.hasComputerLab = true;
refFifteen.hasScienceLab = true;
refFifteen.hasMusicRoom = true;
refFifteen.schoolType = "Private";
refFifteen.establishedYear = 2006;
refFifteen.contactNumber = "9874433221";
refFifteen.email = "info@evergreen.edu";
refFifteen.website = "www.evergreen.edu";
refFifteen.accreditation = "CBSE";

System.out.println("The schoolId is: " + refFifteen.schoolId);
System.out.println("The schoolName is: " + refFifteen.schoolName);
System.out.println("The principalName is: " + refFifteen.principalName);
System.out.println("The vicePrincipalName is: " + refFifteen.vicePrincipalName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfTeachers is: " + refFifteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refFifteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refFifteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refFifteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refFifteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refFifteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refFifteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refFifteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refFifteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refFifteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refFifteen.hasMusicRoom);
System.out.println("The schoolType is: " + refFifteen.schoolType);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The accreditation is: " + refFifteen.accreditation);
School refSixteen = new School();

System.out.println("The schoolId is: " + refSixteen.schoolId);
System.out.println("The schoolName is: " + refSixteen.schoolName);
System.out.println("The principalName is: " + refSixteen.principalName);
System.out.println("The vicePrincipalName is: " + refSixteen.vicePrincipalName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfTeachers is: " + refSixteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refSixteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refSixteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refSixteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refSixteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refSixteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refSixteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refSixteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refSixteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refSixteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refSixteen.hasMusicRoom);
System.out.println("The schoolType is: " + refSixteen.schoolType);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The accreditation is: " + refSixteen.accreditation);

refSixteen.schoolId = 16;
refSixteen.schoolName = "Greenwood High School";
refSixteen.principalName = "Anand Kulkarni";
refSixteen.vicePrincipalName = "Ritu Sharma";
refSixteen.location = "HSR Layout";
refSixteen.city = "Bengaluru";
refSixteen.state = "Karnataka";
refSixteen.country = "India";
refSixteen.numberOfTeachers = 66;
refSixteen.numberOfStudents = 1420;
refSixteen.numberOfClassrooms = 43;
refSixteen.hasLibrary = true;
refSixteen.hasLaboratory = true;
refSixteen.hasPlayground = true;
refSixteen.hasCafeteria = true;
refSixteen.hasTransportFacility = true;
refSixteen.hasComputerLab = true;
refSixteen.hasScienceLab = true;
refSixteen.hasMusicRoom = true;
refSixteen.schoolType = "International";
refSixteen.establishedYear = 2017;
refSixteen.contactNumber = "9877766554";
refSixteen.email = "info@greenwood.edu";
refSixteen.website = "www.greenwood.edu";
refSixteen.accreditation = "IB";

System.out.println("The schoolId is: " + refSixteen.schoolId);
System.out.println("The schoolName is: " + refSixteen.schoolName);
System.out.println("The principalName is: " + refSixteen.principalName);
System.out.println("The vicePrincipalName is: " + refSixteen.vicePrincipalName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfTeachers is: " + refSixteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refSixteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refSixteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refSixteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refSixteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refSixteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refSixteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refSixteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refSixteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refSixteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refSixteen.hasMusicRoom);
System.out.println("The schoolType is: " + refSixteen.schoolType);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The accreditation is: " + refSixteen.accreditation);
School refSeventeen = new School();

System.out.println("The schoolId is: " + refSeventeen.schoolId);
System.out.println("The schoolName is: " + refSeventeen.schoolName);
System.out.println("The principalName is: " + refSeventeen.principalName);
System.out.println("The vicePrincipalName is: " + refSeventeen.vicePrincipalName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfTeachers is: " + refSeventeen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refSeventeen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refSeventeen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refSeventeen.hasLibrary);
System.out.println("The hasLaboratory is: " + refSeventeen.hasLaboratory);
System.out.println("The hasPlayground is: " + refSeventeen.hasPlayground);
System.out.println("The hasCafeteria is: " + refSeventeen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refSeventeen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refSeventeen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refSeventeen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refSeventeen.hasMusicRoom);
System.out.println("The schoolType is: " + refSeventeen.schoolType);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The accreditation is: " + refSeventeen.accreditation);

refSeventeen.schoolId = 17;
refSeventeen.schoolName = "Lotus Valley School";
refSeventeen.principalName = "Rohit Sharma";
refSeventeen.vicePrincipalName = "Anita Das";
refSeventeen.location = "JP Nagar";
refSeventeen.city = "Bengaluru";
refSeventeen.state = "Karnataka";
refSeventeen.country = "India";
refSeventeen.numberOfTeachers = 61;
refSeventeen.numberOfStudents = 1290;
refSeventeen.numberOfClassrooms = 39;
refSeventeen.hasLibrary = true;
refSeventeen.hasLaboratory = true;
refSeventeen.hasPlayground = true;
refSeventeen.hasCafeteria = true;
refSeventeen.hasTransportFacility = true;
refSeventeen.hasComputerLab = true;
refSeventeen.hasScienceLab = true;
refSeventeen.hasMusicRoom = false;
refSeventeen.schoolType = "Private";
refSeventeen.establishedYear = 2011;
refSeventeen.contactNumber = "9886655443";
refSeventeen.email = "info@lotusvalley.edu";
refSeventeen.website = "www.lotusvalley.edu";
refSeventeen.accreditation = "CBSE";

System.out.println("The schoolId is: " + refSeventeen.schoolId);
System.out.println("The schoolName is: " + refSeventeen.schoolName);
System.out.println("The principalName is: " + refSeventeen.principalName);
System.out.println("The vicePrincipalName is: " + refSeventeen.vicePrincipalName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfTeachers is: " + refSeventeen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refSeventeen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refSeventeen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refSeventeen.hasLibrary);
System.out.println("The hasLaboratory is: " + refSeventeen.hasLaboratory);
System.out.println("The hasPlayground is: " + refSeventeen.hasPlayground);
System.out.println("The hasCafeteria is: " + refSeventeen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refSeventeen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refSeventeen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refSeventeen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refSeventeen.hasMusicRoom);
System.out.println("The schoolType is: " + refSeventeen.schoolType);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The accreditation is: " + refSeventeen.accreditation);
School refEighteen = new School();

System.out.println("The schoolId is: " + refEighteen.schoolId);
System.out.println("The schoolName is: " + refEighteen.schoolName);
System.out.println("The principalName is: " + refEighteen.principalName);
System.out.println("The vicePrincipalName is: " + refEighteen.vicePrincipalName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfTeachers is: " + refEighteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refEighteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refEighteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refEighteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refEighteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refEighteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refEighteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refEighteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refEighteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refEighteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refEighteen.hasMusicRoom);
System.out.println("The schoolType is: " + refEighteen.schoolType);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The accreditation is: " + refEighteen.accreditation);

refEighteen.schoolId = 18;
refEighteen.schoolName = "Golden Future School";
refEighteen.principalName = "Manoj Verma";
refEighteen.vicePrincipalName = "Pallavi Joshi";
refEighteen.location = "Bellandur";
refEighteen.city = "Bengaluru";
refEighteen.state = "Karnataka";
refEighteen.country = "India";
refEighteen.numberOfTeachers = 63;
refEighteen.numberOfStudents = 1320;
refEighteen.numberOfClassrooms = 41;
refEighteen.hasLibrary = true;
refEighteen.hasLaboratory = true;
refEighteen.hasPlayground = true;
refEighteen.hasCafeteria = true;
refEighteen.hasTransportFacility = true;
refEighteen.hasComputerLab = true;
refEighteen.hasScienceLab = true;
refEighteen.hasMusicRoom = true;
refEighteen.schoolType = "Private";
refEighteen.establishedYear = 2012;
refEighteen.contactNumber = "9873344556";
refEighteen.email = "info@goldenfuture.edu";
refEighteen.website = "www.goldenfuture.edu";
refEighteen.accreditation = "CBSE";

System.out.println("The schoolId is: " + refEighteen.schoolId);
System.out.println("The schoolName is: " + refEighteen.schoolName);
System.out.println("The principalName is: " + refEighteen.principalName);
System.out.println("The vicePrincipalName is: " + refEighteen.vicePrincipalName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfTeachers is: " + refEighteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refEighteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refEighteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refEighteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refEighteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refEighteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refEighteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refEighteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refEighteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refEighteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refEighteen.hasMusicRoom);
System.out.println("The schoolType is: " + refEighteen.schoolType);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The accreditation is: " + refEighteen.accreditation);
School refNineteen = new School();

System.out.println("The schoolId is: " + refNineteen.schoolId);
System.out.println("The schoolName is: " + refNineteen.schoolName);
System.out.println("The principalName is: " + refNineteen.principalName);
System.out.println("The vicePrincipalName is: " + refNineteen.vicePrincipalName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfTeachers is: " + refNineteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refNineteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refNineteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refNineteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refNineteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refNineteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refNineteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refNineteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refNineteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refNineteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refNineteen.hasMusicRoom);
System.out.println("The schoolType is: " + refNineteen.schoolType);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The accreditation is: " + refNineteen.accreditation);

refNineteen.schoolId = 19;
refNineteen.schoolName = "Sunshine High School";
refNineteen.principalName = "Ramesh Iyer";
refNineteen.vicePrincipalName = "Divya Nair";
refNineteen.location = "KR Puram";
refNineteen.city = "Bengaluru";
refNineteen.state = "Karnataka";
refNineteen.country = "India";
refNineteen.numberOfTeachers = 57;
refNineteen.numberOfStudents = 1210;
refNineteen.numberOfClassrooms = 36;
refNineteen.hasLibrary = true;
refNineteen.hasLaboratory = true;
refNineteen.hasPlayground = true;
refNineteen.hasCafeteria = false;
refNineteen.hasTransportFacility = true;
refNineteen.hasComputerLab = true;
refNineteen.hasScienceLab = true;
refNineteen.hasMusicRoom = false;
refNineteen.schoolType = "Private";
refNineteen.establishedYear = 2004;
refNineteen.contactNumber = "9845566778";
refNineteen.email = "info@sunshine.edu";
refNineteen.website = "www.sunshine.edu";
refNineteen.accreditation = "CBSE";

System.out.println("The schoolId is: " + refNineteen.schoolId);
System.out.println("The schoolName is: " + refNineteen.schoolName);
System.out.println("The principalName is: " + refNineteen.principalName);
System.out.println("The vicePrincipalName is: " + refNineteen.vicePrincipalName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfTeachers is: " + refNineteen.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refNineteen.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refNineteen.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refNineteen.hasLibrary);
System.out.println("The hasLaboratory is: " + refNineteen.hasLaboratory);
System.out.println("The hasPlayground is: " + refNineteen.hasPlayground);
System.out.println("The hasCafeteria is: " + refNineteen.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refNineteen.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refNineteen.hasComputerLab);
System.out.println("The hasScienceLab is: " + refNineteen.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refNineteen.hasMusicRoom);
System.out.println("The schoolType is: " + refNineteen.schoolType);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The accreditation is: " + refNineteen.accreditation);
School refTwenty = new School();

System.out.println("The schoolId is: " + refTwenty.schoolId);
System.out.println("The schoolName is: " + refTwenty.schoolName);
System.out.println("The principalName is: " + refTwenty.principalName);
System.out.println("The vicePrincipalName is: " + refTwenty.vicePrincipalName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfTeachers is: " + refTwenty.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refTwenty.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refTwenty.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refTwenty.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwenty.hasLaboratory);
System.out.println("The hasPlayground is: " + refTwenty.hasPlayground);
System.out.println("The hasCafeteria is: " + refTwenty.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refTwenty.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refTwenty.hasComputerLab);
System.out.println("The hasScienceLab is: " + refTwenty.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refTwenty.hasMusicRoom);
System.out.println("The schoolType is: " + refTwenty.schoolType);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The accreditation is: " + refTwenty.accreditation);

refTwenty.schoolId = 20;
refTwenty.schoolName = "Future Stars School";
refTwenty.principalName = "Sandeep Kumar";
refTwenty.vicePrincipalName = "Neelam Verma";
refTwenty.location = "Yeshwanthpur";
refTwenty.city = "Bengaluru";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.numberOfTeachers = 60;
refTwenty.numberOfStudents = 1250;
refTwenty.numberOfClassrooms = 38;
refTwenty.hasLibrary = true;
refTwenty.hasLaboratory = true;
refTwenty.hasPlayground = true;
refTwenty.hasCafeteria = true;
refTwenty.hasTransportFacility = true;
refTwenty.hasComputerLab = true;
refTwenty.hasScienceLab = true;
refTwenty.hasMusicRoom = true;
refTwenty.schoolType = "Private";
refTwenty.establishedYear = 2018;
refTwenty.contactNumber = "9876655443";
refTwenty.email = "info@futurestars.edu";
refTwenty.website = "www.futurestars.edu";
refTwenty.accreditation = "CBSE";

System.out.println("The schoolId is: " + refTwenty.schoolId);
System.out.println("The schoolName is: " + refTwenty.schoolName);
System.out.println("The principalName is: " + refTwenty.principalName);
System.out.println("The vicePrincipalName is: " + refTwenty.vicePrincipalName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfTeachers is: " + refTwenty.numberOfTeachers);
System.out.println("The numberOfStudents is: " + refTwenty.numberOfStudents);
System.out.println("The numberOfClassrooms is: " + refTwenty.numberOfClassrooms);
System.out.println("The hasLibrary is: " + refTwenty.hasLibrary);
System.out.println("The hasLaboratory is: " + refTwenty.hasLaboratory);
System.out.println("The hasPlayground is: " + refTwenty.hasPlayground);
System.out.println("The hasCafeteria is: " + refTwenty.hasCafeteria);
System.out.println("The hasTransportFacility is: " + refTwenty.hasTransportFacility);
System.out.println("The hasComputerLab is: " + refTwenty.hasComputerLab);
System.out.println("The hasScienceLab is: " + refTwenty.hasScienceLab);
System.out.println("The hasMusicRoom is: " + refTwenty.hasMusicRoom);
System.out.println("The schoolType is: " + refTwenty.schoolType);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The accreditation is: " + refTwenty.accreditation);
}
}