class SubscriptionExecutor {
    public static void main(String[] args) {

        SubscriptionDetails s1 = new SubscriptionDetails();
        s1.setSubscriptionId(1);
        s1.setUserName("User1");
        s1.setPlanName("Basic");
        s1.setPrice(199.0);
        s1.setDuration(1);
        s1.setStartDate("2024-01-01");
        s1.setEndDate("2024-02-01");
        System.out.println(s1.getSubscriptionId());
        System.out.println(s1.getUserName());
        System.out.println(s1.getPlanName());
        System.out.println(s1.getPrice());
        System.out.println(s1.getDuration());
        System.out.println(s1.getStartDate());
        System.out.println(s1.getEndDate());

        SubscriptionDetails s2 = new SubscriptionDetails();
        s2.setSubscriptionId(2);
        s2.setUserName("User2");
        s2.setPlanName("Standard");
        s2.setPrice(299.0);
        s2.setDuration(2);
        s2.setStartDate("2024-01-02");
        s2.setEndDate("2024-03-02");
        System.out.println(s2.getSubscriptionId());
        System.out.println(s2.getUserName());
        System.out.println(s2.getPlanName());
        System.out.println(s2.getPrice());
        System.out.println(s2.getDuration());
        System.out.println(s2.getStartDate());
        System.out.println(s2.getEndDate());

        SubscriptionDetails s3 = new SubscriptionDetails();
        s3.setSubscriptionId(3);
        s3.setUserName("User3");
        s3.setPlanName("Premium");
        s3.setPrice(399.0);
        s3.setDuration(3);
        s3.setStartDate("2024-01-03");
        s3.setEndDate("2024-04-03");
        System.out.println(s3.getSubscriptionId());
        System.out.println(s3.getUserName());
        System.out.println(s3.getPlanName());
        System.out.println(s3.getPrice());
        System.out.println(s3.getDuration());
        System.out.println(s3.getStartDate());
        System.out.println(s3.getEndDate());

        SubscriptionDetails s4 = new SubscriptionDetails();
        s4.setSubscriptionId(4);
        s4.setUserName("User4");
        s4.setPlanName("Basic");
        s4.setPrice(199.0);
        s4.setDuration(4);
        s4.setStartDate("2024-01-04");
        s4.setEndDate("2024-05-04");
        System.out.println(s4.getSubscriptionId());
        System.out.println(s4.getUserName());
        System.out.println(s4.getPlanName());
        System.out.println(s4.getPrice());
        System.out.println(s4.getDuration());
        System.out.println(s4.getStartDate());
        System.out.println(s4.getEndDate());

        SubscriptionDetails s5 = new SubscriptionDetails();
        s5.setSubscriptionId(5);
        s5.setUserName("User5");
        s5.setPlanName("Standard");
        s5.setPrice(299.0);
        s5.setDuration(5);
        s5.setStartDate("2024-01-05");
        s5.setEndDate("2024-06-05");
        System.out.println(s5.getSubscriptionId());
        System.out.println(s5.getUserName());
        System.out.println(s5.getPlanName());
        System.out.println(s5.getPrice());
        System.out.println(s5.getDuration());
        System.out.println(s5.getStartDate());
        System.out.println(s5.getEndDate());

        SubscriptionDetails s6 = new SubscriptionDetails();
        s6.setSubscriptionId(6);
        s6.setUserName("User6");
        s6.setPlanName("Premium");
        s6.setPrice(399.0);
        s6.setDuration(6);
        s6.setStartDate("2024-01-06");
        s6.setEndDate("2024-07-06");
        System.out.println(s6.getSubscriptionId());
        System.out.println(s6.getUserName());
        System.out.println(s6.getPlanName());
        System.out.println(s6.getPrice());
        System.out.println(s6.getDuration());
        System.out.println(s6.getStartDate());
        System.out.println(s6.getEndDate());

        SubscriptionDetails s7 = new SubscriptionDetails();
        s7.setSubscriptionId(7);
        s7.setUserName("User7");
        s7.setPlanName("Basic");
        s7.setPrice(199.0);
        s7.setDuration(7);
        s7.setStartDate("2024-01-07");
        s7.setEndDate("2024-08-07");
        System.out.println(s7.getSubscriptionId());
        System.out.println(s7.getUserName());
        System.out.println(s7.getPlanName());
        System.out.println(s7.getPrice());
        System.out.println(s7.getDuration());
        System.out.println(s7.getStartDate());
        System.out.println(s7.getEndDate());

        SubscriptionDetails s8 = new SubscriptionDetails();
        s8.setSubscriptionId(8);
        s8.setUserName("User8");
        s8.setPlanName("Standard");
        s8.setPrice(299.0);
        s8.setDuration(8);
        s8.setStartDate("2024-01-08");
        s8.setEndDate("2024-09-08");
        System.out.println(s8.getSubscriptionId());
        System.out.println(s8.getUserName());
        System.out.println(s8.getPlanName());
        System.out.println(s8.getPrice());
        System.out.println(s8.getDuration());
        System.out.println(s8.getStartDate());
        System.out.println(s8.getEndDate());

        SubscriptionDetails s9 = new SubscriptionDetails();
        s9.setSubscriptionId(9);
        s9.setUserName("User9");
        s9.setPlanName("Premium");
        s9.setPrice(399.0);
        s9.setDuration(9);
        s9.setStartDate("2024-01-09");
        s9.setEndDate("2024-10-09");
        System.out.println(s9.getSubscriptionId());
        System.out.println(s9.getUserName());
        System.out.println(s9.getPlanName());
        System.out.println(s9.getPrice());
        System.out.println(s9.getDuration());
        System.out.println(s9.getStartDate());
        System.out.println(s9.getEndDate());

        SubscriptionDetails s10 = new SubscriptionDetails();
        s10.setSubscriptionId(10);
        s10.setUserName("User10");
        s10.setPlanName("Basic");
        s10.setPrice(199.0);
        s10.setDuration(10);
        s10.setStartDate("2024-01-10");
        s10.setEndDate("2024-11-10");
        System.out.println(s10.getSubscriptionId());
        System.out.println(s10.getUserName());
        System.out.println(s10.getPlanName());
        System.out.println(s10.getPrice());
        System.out.println(s10.getDuration());
        System.out.println(s10.getStartDate());
        System.out.println(s10.getEndDate());

        SubscriptionDetails s11 = new SubscriptionDetails();
        s11.setSubscriptionId(11);
        s11.setUserName("User11");
        s11.setPlanName("Standard");
        s11.setPrice(299.0);
        s11.setDuration(11);
        s11.setStartDate("2024-01-11");
        s11.setEndDate("2024-12-11");
        System.out.println(s11.getSubscriptionId());
        System.out.println(s11.getUserName());
        System.out.println(s11.getPlanName());
        System.out.println(s11.getPrice());
        System.out.println(s11.getDuration());
        System.out.println(s11.getStartDate());
        System.out.println(s11.getEndDate());

        SubscriptionDetails s12 = new SubscriptionDetails();
        s12.setSubscriptionId(12);
        s12.setUserName("User12");
        s12.setPlanName("Premium");
        s12.setPrice(399.0);
        s12.setDuration(12);
        s12.setStartDate("2024-01-12");
        s12.setEndDate("2025-01-12");
        System.out.println(s12.getSubscriptionId());
        System.out.println(s12.getUserName());
        System.out.println(s12.getPlanName());
        System.out.println(s12.getPrice());
        System.out.println(s12.getDuration());
        System.out.println(s12.getStartDate());
        System.out.println(s12.getEndDate());

        SubscriptionDetails s13 = new SubscriptionDetails();
        s13.setSubscriptionId(13);
        s13.setUserName("User13");
        s13.setPlanName("Basic");
        s13.setPrice(199.0);
        s13.setDuration(1);
        s13.setStartDate("2024-01-13");
        s13.setEndDate("2024-02-13");
        System.out.println(s13.getSubscriptionId());
        System.out.println(s13.getUserName());
        System.out.println(s13.getPlanName());
        System.out.println(s13.getPrice());
        System.out.println(s13.getDuration());
        System.out.println(s13.getStartDate());
        System.out.println(s13.getEndDate());

        SubscriptionDetails s14 = new SubscriptionDetails();
        s14.setSubscriptionId(14);
        s14.setUserName("User14");
        s14.setPlanName("Standard");
        s14.setPrice(299.0);
        s14.setDuration(2);
        s14.setStartDate("2024-01-14");
        s14.setEndDate("2024-03-14");
        System.out.println(s14.getSubscriptionId());
        System.out.println(s14.getUserName());
        System.out.println(s14.getPlanName());
        System.out.println(s14.getPrice());
        System.out.println(s14.getDuration());
        System.out.println(s14.getStartDate());
        System.out.println(s14.getEndDate());

        SubscriptionDetails s15 = new SubscriptionDetails();
        s15.setSubscriptionId(15);
        s15.setUserName("User15");
        s15.setPlanName("Premium");
        s15.setPrice(399.0);
        s15.setDuration(3);
        s15.setStartDate("2024-01-15");
        s15.setEndDate("2024-04-15");
        System.out.println(s15.getSubscriptionId());
        System.out.println(s15.getUserName());
        System.out.println(s15.getPlanName());
        System.out.println(s15.getPrice());
        System.out.println(s15.getDuration());
        System.out.println(s15.getStartDate());
        System.out.println(s15.getEndDate());

        SubscriptionDetails s16 = new SubscriptionDetails();
        s16.setSubscriptionId(16);
        s16.setUserName("User16");
        s16.setPlanName("Basic");
        s16.setPrice(199.0);
        s16.setDuration(4);
        s16.setStartDate("2024-01-16");
        s16.setEndDate("2024-05-16");
        System.out.println(s16.getSubscriptionId());
        System.out.println(s16.getUserName());
        System.out.println(s16.getPlanName());
        System.out.println(s16.getPrice());
        System.out.println(s16.getDuration());
        System.out.println(s16.getStartDate());
        System.out.println(s16.getEndDate());

        SubscriptionDetails s17 = new SubscriptionDetails();
        s17.setSubscriptionId(17);
        s17.setUserName("User17");
        s17.setPlanName("Standard");
        s17.setPrice(299.0);
        s17.setDuration(5);
        s17.setStartDate("2024-01-17");
        s17.setEndDate("2024-06-17");
        System.out.println(s17.getSubscriptionId());
        System.out.println(s17.getUserName());
        System.out.println(s17.getPlanName());
        System.out.println(s17.getPrice());
        System.out.println(s17.getDuration());
        System.out.println(s17.getStartDate());
        System.out.println(s17.getEndDate());

        SubscriptionDetails s18 = new SubscriptionDetails();
        s18.setSubscriptionId(18);
        s18.setUserName("User18");
        s18.setPlanName("Premium");
        s18.setPrice(399.0);
        s18.setDuration(6);
        s18.setStartDate("2024-01-18");
        s18.setEndDate("2024-07-18");
        System.out.println(s18.getSubscriptionId());
        System.out.println(s18.getUserName());
        System.out.println(s18.getPlanName());
        System.out.println(s18.getPrice());
        System.out.println(s18.getDuration());
        System.out.println(s18.getStartDate());
        System.out.println(s18.getEndDate());

        SubscriptionDetails s19 = new SubscriptionDetails();
        s19.setSubscriptionId(19);
        s19.setUserName("User19");
        s19.setPlanName("Basic");
        s19.setPrice(199.0);
        s19.setDuration(7);
        s19.setStartDate("2024-01-19");
        s19.setEndDate("2024-08-19");
        System.out.println(s19.getSubscriptionId());
        System.out.println(s19.getUserName());
        System.out.println(s19.getPlanName());
        System.out.println(s19.getPrice());
        System.out.println(s19.getDuration());
        System.out.println(s19.getStartDate());
        System.out.println(s19.getEndDate());

        SubscriptionDetails s20 = new SubscriptionDetails();
        s20.setSubscriptionId(20);
        s20.setUserName("User20");
        s20.setPlanName("Standard");
        s20.setPrice(299.0);
        s20.setDuration(8);
        s20.setStartDate("2024-01-20");
        s20.setEndDate("2024-09-20");
        System.out.println(s20.getSubscriptionId());
        System.out.println(s20.getUserName());
        System.out.println(s20.getPlanName());
        System.out.println(s20.getPrice());
        System.out.println(s20.getDuration());
        System.out.println(s20.getStartDate());
        System.out.println(s20.getEndDate());

        SubscriptionDetails s21 = new SubscriptionDetails();
        s21.setSubscriptionId(21);
        s21.setUserName("User21");
        s21.setPlanName("Premium");
        s21.setPrice(399.0);
        s21.setDuration(9);
        s21.setStartDate("2024-01-21");
        s21.setEndDate("2024-10-21");
        System.out.println(s21.getSubscriptionId());
        System.out.println(s21.getUserName());
        System.out.println(s21.getPlanName());
        System.out.println(s21.getPrice());
        System.out.println(s21.getDuration());
        System.out.println(s21.getStartDate());
        System.out.println(s21.getEndDate());

        SubscriptionDetails s22 = new SubscriptionDetails();
        s22.setSubscriptionId(22);
        s22.setUserName("User22");
        s22.setPlanName("Basic");
        s22.setPrice(199.0);
        s22.setDuration(10);
        s22.setStartDate("2024-01-22");
        s22.setEndDate("2024-11-22");
        System.out.println(s22.getSubscriptionId());
        System.out.println(s22.getUserName());
        System.out.println(s22.getPlanName());
        System.out.println(s22.getPrice());
        System.out.println(s22.getDuration());
        System.out.println(s22.getStartDate());
        System.out.println(s22.getEndDate());

        SubscriptionDetails s23 = new SubscriptionDetails();
        s23.setSubscriptionId(23);
        s23.setUserName("User23");
        s23.setPlanName("Standard");
        s23.setPrice(299.0);
        s23.setDuration(11);
        s23.setStartDate("2024-01-23");
        s23.setEndDate("2024-12-23");
        System.out.println(s23.getSubscriptionId());
        System.out.println(s23.getUserName());
        System.out.println(s23.getPlanName());
        System.out.println(s23.getPrice());
        System.out.println(s23.getDuration());
        System.out.println(s23.getStartDate());
        System.out.println(s23.getEndDate());

        SubscriptionDetails s24 = new SubscriptionDetails();
        s24.setSubscriptionId(24);
        s24.setUserName("User24");
        s24.setPlanName("Premium");
        s24.setPrice(399.0);
        s24.setDuration(12);
        s24.setStartDate("2024-01-24");
        s24.setEndDate("2025-01-24");
        System.out.println(s24.getSubscriptionId());
        System.out.println(s24.getUserName());
        System.out.println(s24.getPlanName());
        System.out.println(s24.getPrice());
        System.out.println(s24.getDuration());
        System.out.println(s24.getStartDate());
        System.out.println(s24.getEndDate());

        SubscriptionDetails s25 = new SubscriptionDetails();
        s25.setSubscriptionId(25);
        s25.setUserName("User25");
        s25.setPlanName("Basic");
        s25.setPrice(199.0);
        s25.setDuration(1);
        s25.setStartDate("2024-01-25");
        s25.setEndDate("2024-02-25");
        System.out.println(s25.getSubscriptionId());
        System.out.println(s25.getUserName());
        System.out.println(s25.getPlanName());
        System.out.println(s25.getPrice());
        System.out.println(s25.getDuration());
        System.out.println(s25.getStartDate());
        System.out.println(s25.getEndDate());

        SubscriptionDetails s26 = new SubscriptionDetails();
        s26.setSubscriptionId(26);
        s26.setUserName("User26");
        s26.setPlanName("Standard");
        s26.setPrice(299.0);
        s26.setDuration(2);
        s26.setStartDate("2024-01-26");
        s26.setEndDate("2024-03-26");
        System.out.println(s26.getSubscriptionId());
        System.out.println(s26.getUserName());
        System.out.println(s26.getPlanName());
        System.out.println(s26.getPrice());
        System.out.println(s26.getDuration());
        System.out.println(s26.getStartDate());
        System.out.println(s26.getEndDate());

        SubscriptionDetails s27 = new SubscriptionDetails();
        s27.setSubscriptionId(27);
        s27.setUserName("User27");
        s27.setPlanName("Premium");
        s27.setPrice(399.0);
        s27.setDuration(3);
        s27.setStartDate("2024-01-27");
        s27.setEndDate("2024-04-27");
        System.out.println(s27.getSubscriptionId());
        System.out.println(s27.getUserName());
        System.out.println(s27.getPlanName());
        System.out.println(s27.getPrice());
        System.out.println(s27.getDuration());
        System.out.println(s27.getStartDate());
        System.out.println(s27.getEndDate());

        SubscriptionDetails s28 = new SubscriptionDetails();
        s28.setSubscriptionId(28);
        s28.setUserName("User28");
        s28.setPlanName("Basic");
        s28.setPrice(199.0);
        s28.setDuration(4);
        s28.setStartDate("2024-01-28");
        s28.setEndDate("2024-05-28");
        System.out.println(s28.getSubscriptionId());
        System.out.println(s28.getUserName());
        System.out.println(s28.getPlanName());
        System.out.println(s28.getPrice());
        System.out.println(s28.getDuration());
        System.out.println(s28.getStartDate());
        System.out.println(s28.getEndDate());

        SubscriptionDetails s29 = new SubscriptionDetails();
        s29.setSubscriptionId(29);
        s29.setUserName("User29");
        s29.setPlanName("Standard");
        s29.setPrice(299.0);
        s29.setDuration(5);
        s29.setStartDate("2024-01-29");
        s29.setEndDate("2024-06-29");
        System.out.println(s29.getSubscriptionId());
        System.out.println(s29.getUserName());
        System.out.println(s29.getPlanName());
        System.out.println(s29.getPrice());
        System.out.println(s29.getDuration());
        System.out.println(s29.getStartDate());
        System.out.println(s29.getEndDate());
    }
}