class TicketExecutor {
    public static void main(String[] args) {

        TicketDetails t1 = new TicketDetails();
        t1.setTicketId(1);
        t1.setPassengerName("Passenger1");
        t1.setSource("CityA");
        t1.setDestination("CityB");
        t1.setPrice(500.0);
        t1.setTravelDate("2024-01-01");
        t1.setSeatNumber("S1");
        System.out.println(t1.getTicketId());
        System.out.println(t1.getPassengerName());
        System.out.println(t1.getSource());
        System.out.println(t1.getDestination());
        System.out.println(t1.getPrice());
        System.out.println(t1.getTravelDate());
        System.out.println(t1.getSeatNumber());

        TicketDetails t2 = new TicketDetails();
        t2.setTicketId(2);
        t2.setPassengerName("Passenger2");
        t2.setSource("CityA");
        t2.setDestination("CityB");
        t2.setPrice(600.0);
        t2.setTravelDate("2024-01-02");
        t2.setSeatNumber("S2");
        System.out.println(t2.getTicketId());
        System.out.println(t2.getPassengerName());
        System.out.println(t2.getSource());
        System.out.println(t2.getDestination());
        System.out.println(t2.getPrice());
        System.out.println(t2.getTravelDate());
        System.out.println(t2.getSeatNumber());

        TicketDetails t3 = new TicketDetails();
        t3.setTicketId(3);
        t3.setPassengerName("Passenger3");
        t3.setSource("CityA");
        t3.setDestination("CityB");
        t3.setPrice(700.0);
        t3.setTravelDate("2024-01-03");
        t3.setSeatNumber("S3");
        System.out.println(t3.getTicketId());
        System.out.println(t3.getPassengerName());
        System.out.println(t3.getSource());
        System.out.println(t3.getDestination());
        System.out.println(t3.getPrice());
        System.out.println(t3.getTravelDate());
        System.out.println(t3.getSeatNumber());

        TicketDetails t4 = new TicketDetails();
        t4.setTicketId(4);
        t4.setPassengerName("Passenger4");
        t4.setSource("CityA");
        t4.setDestination("CityB");
        t4.setPrice(800.0);
        t4.setTravelDate("2024-01-04");
        t4.setSeatNumber("S4");
        System.out.println(t4.getTicketId());
        System.out.println(t4.getPassengerName());
        System.out.println(t4.getSource());
        System.out.println(t4.getDestination());
        System.out.println(t4.getPrice());
        System.out.println(t4.getTravelDate());
        System.out.println(t4.getSeatNumber());

        TicketDetails t5 = new TicketDetails();
        t5.setTicketId(5);
        t5.setPassengerName("Passenger5");
        t5.setSource("CityA");
        t5.setDestination("CityB");
        t5.setPrice(900.0);
        t5.setTravelDate("2024-01-05");
        t5.setSeatNumber("S5");
        System.out.println(t5.getTicketId());
        System.out.println(t5.getPassengerName());
        System.out.println(t5.getSource());
        System.out.println(t5.getDestination());
        System.out.println(t5.getPrice());
        System.out.println(t5.getTravelDate());
        System.out.println(t5.getSeatNumber());

        TicketDetails t6 = new TicketDetails();
        t6.setTicketId(6);
        t6.setPassengerName("Passenger6");
        t6.setSource("CityA");
        t6.setDestination("CityB");
        t6.setPrice(1000.0);
        t6.setTravelDate("2024-01-06");
        t6.setSeatNumber("S6");
        System.out.println(t6.getTicketId());
        System.out.println(t6.getPassengerName());
        System.out.println(t6.getSource());
        System.out.println(t6.getDestination());
        System.out.println(t6.getPrice());
        System.out.println(t6.getTravelDate());
        System.out.println(t6.getSeatNumber());

        TicketDetails t7 = new TicketDetails();
        t7.setTicketId(7);
        t7.setPassengerName("Passenger7");
        t7.setSource("CityA");
        t7.setDestination("CityB");
        t7.setPrice(1100.0);
        t7.setTravelDate("2024-01-07");
        t7.setSeatNumber("S7");
        System.out.println(t7.getTicketId());
        System.out.println(t7.getPassengerName());
        System.out.println(t7.getSource());
        System.out.println(t7.getDestination());
        System.out.println(t7.getPrice());
        System.out.println(t7.getTravelDate());
        System.out.println(t7.getSeatNumber());

        TicketDetails t8 = new TicketDetails();
        t8.setTicketId(8);
        t8.setPassengerName("Passenger8");
        t8.setSource("CityA");
        t8.setDestination("CityB");
        t8.setPrice(1200.0);
        t8.setTravelDate("2024-01-08");
        t8.setSeatNumber("S8");
        System.out.println(t8.getTicketId());
        System.out.println(t8.getPassengerName());
        System.out.println(t8.getSource());
        System.out.println(t8.getDestination());
        System.out.println(t8.getPrice());
        System.out.println(t8.getTravelDate());
        System.out.println(t8.getSeatNumber());

        TicketDetails t9 = new TicketDetails();
        t9.setTicketId(9);
        t9.setPassengerName("Passenger9");
        t9.setSource("CityA");
        t9.setDestination("CityB");
        t9.setPrice(1300.0);
        t9.setTravelDate("2024-01-09");
        t9.setSeatNumber("S9");
        System.out.println(t9.getTicketId());
        System.out.println(t9.getPassengerName());
        System.out.println(t9.getSource());
        System.out.println(t9.getDestination());
        System.out.println(t9.getPrice());
        System.out.println(t9.getTravelDate());
        System.out.println(t9.getSeatNumber());

        TicketDetails t10 = new TicketDetails();
        t10.setTicketId(10);
        t10.setPassengerName("Passenger10");
        t10.setSource("CityA");
        t10.setDestination("CityB");
        t10.setPrice(1400.0);
        t10.setTravelDate("2024-01-10");
        t10.setSeatNumber("S10");
        System.out.println(t10.getTicketId());
        System.out.println(t10.getPassengerName());
        System.out.println(t10.getSource());
        System.out.println(t10.getDestination());
        System.out.println(t10.getPrice());
        System.out.println(t10.getTravelDate());
        System.out.println(t10.getSeatNumber());

        TicketDetails t11 = new TicketDetails();
        t11.setTicketId(11);
        t11.setPassengerName("Passenger11");
        t11.setSource("CityA");
        t11.setDestination("CityB");
        t11.setPrice(1500.0);
        t11.setTravelDate("2024-01-11");
        t11.setSeatNumber("S11");
        System.out.println(t11.getTicketId());
        System.out.println(t11.getPassengerName());
        System.out.println(t11.getSource());
        System.out.println(t11.getDestination());
        System.out.println(t11.getPrice());
        System.out.println(t11.getTravelDate());
        System.out.println(t11.getSeatNumber());

        TicketDetails t12 = new TicketDetails();
        t12.setTicketId(12);
        t12.setPassengerName("Passenger12");
        t12.setSource("CityA");
        t12.setDestination("CityB");
        t12.setPrice(1600.0);
        t12.setTravelDate("2024-01-12");
        t12.setSeatNumber("S12");
        System.out.println(t12.getTicketId());
        System.out.println(t12.getPassengerName());
        System.out.println(t12.getSource());
        System.out.println(t12.getDestination());
        System.out.println(t12.getPrice());
        System.out.println(t12.getTravelDate());
        System.out.println(t12.getSeatNumber());

        TicketDetails t13 = new TicketDetails();
        t13.setTicketId(13);
        t13.setPassengerName("Passenger13");
        t13.setSource("CityA");
        t13.setDestination("CityB");
        t13.setPrice(1700.0);
        t13.setTravelDate("2024-01-13");
        t13.setSeatNumber("S13");
        System.out.println(t13.getTicketId());
        System.out.println(t13.getPassengerName());
        System.out.println(t13.getSource());
        System.out.println(t13.getDestination());
        System.out.println(t13.getPrice());
        System.out.println(t13.getTravelDate());
        System.out.println(t13.getSeatNumber());

        TicketDetails t14 = new TicketDetails();
        t14.setTicketId(14);
        t14.setPassengerName("Passenger14");
        t14.setSource("CityA");
        t14.setDestination("CityB");
        t14.setPrice(1800.0);
        t14.setTravelDate("2024-01-14");
        t14.setSeatNumber("S14");
        System.out.println(t14.getTicketId());
        System.out.println(t14.getPassengerName());
        System.out.println(t14.getSource());
        System.out.println(t14.getDestination());
        System.out.println(t14.getPrice());
        System.out.println(t14.getTravelDate());
        System.out.println(t14.getSeatNumber());

        TicketDetails t15 = new TicketDetails();
        t15.setTicketId(15);
        t15.setPassengerName("Passenger15");
        t15.setSource("CityA");
        t15.setDestination("CityB");
        t15.setPrice(1900.0);
        t15.setTravelDate("2024-01-15");
        t15.setSeatNumber("S15");
        System.out.println(t15.getTicketId());
        System.out.println(t15.getPassengerName());
        System.out.println(t15.getSource());
        System.out.println(t15.getDestination());
        System.out.println(t15.getPrice());
        System.out.println(t15.getTravelDate());
        System.out.println(t15.getSeatNumber());

        TicketDetails t16 = new TicketDetails();
        t16.setTicketId(16);
        t16.setPassengerName("Passenger16");
        t16.setSource("CityA");
        t16.setDestination("CityB");
        t16.setPrice(2000.0);
        t16.setTravelDate("2024-01-16");
        t16.setSeatNumber("S16");
        System.out.println(t16.getTicketId());
        System.out.println(t16.getPassengerName());
        System.out.println(t16.getSource());
        System.out.println(t16.getDestination());
        System.out.println(t16.getPrice());
        System.out.println(t16.getTravelDate());
        System.out.println(t16.getSeatNumber());

        TicketDetails t17 = new TicketDetails();
        t17.setTicketId(17);
        t17.setPassengerName("Passenger17");
        t17.setSource("CityA");
        t17.setDestination("CityB");
        t17.setPrice(2100.0);
        t17.setTravelDate("2024-01-17");
        t17.setSeatNumber("S17");
        System.out.println(t17.getTicketId());
        System.out.println(t17.getPassengerName());
        System.out.println(t17.getSource());
        System.out.println(t17.getDestination());
        System.out.println(t17.getPrice());
        System.out.println(t17.getTravelDate());
        System.out.println(t17.getSeatNumber());

        TicketDetails t18 = new TicketDetails();
        t18.setTicketId(18);
        t18.setPassengerName("Passenger18");
        t18.setSource("CityA");
        t18.setDestination("CityB");
        t18.setPrice(2200.0);
        t18.setTravelDate("2024-01-18");
        t18.setSeatNumber("S18");
        System.out.println(t18.getTicketId());
        System.out.println(t18.getPassengerName());
        System.out.println(t18.getSource());
        System.out.println(t18.getDestination());
        System.out.println(t18.getPrice());
        System.out.println(t18.getTravelDate());
        System.out.println(t18.getSeatNumber());

        TicketDetails t19 = new TicketDetails();
        t19.setTicketId(19);
        t19.setPassengerName("Passenger19");
        t19.setSource("CityA");
        t19.setDestination("CityB");
        t19.setPrice(2300.0);
        t19.setTravelDate("2024-01-19");
        t19.setSeatNumber("S19");
        System.out.println(t19.getTicketId());
        System.out.println(t19.getPassengerName());
        System.out.println(t19.getSource());
        System.out.println(t19.getDestination());
        System.out.println(t19.getPrice());
        System.out.println(t19.getTravelDate());
        System.out.println(t19.getSeatNumber());

        TicketDetails t20 = new TicketDetails();
        t20.setTicketId(20);
        t20.setPassengerName("Passenger20");
        t20.setSource("CityA");
        t20.setDestination("CityB");
        t20.setPrice(2400.0);
        t20.setTravelDate("2024-01-20");
        t20.setSeatNumber("S20");
        System.out.println(t20.getTicketId());
        System.out.println(t20.getPassengerName());
        System.out.println(t20.getSource());
        System.out.println(t20.getDestination());
        System.out.println(t20.getPrice());
        System.out.println(t20.getTravelDate());
        System.out.println(t20.getSeatNumber());

        TicketDetails t21 = new TicketDetails();
        t21.setTicketId(21);
        t21.setPassengerName("Passenger21");
        t21.setSource("CityA");
        t21.setDestination("CityB");
        t21.setPrice(2500.0);
        t21.setTravelDate("2024-01-21");
        t21.setSeatNumber("S21");
        System.out.println(t21.getTicketId());
        System.out.println(t21.getPassengerName());
        System.out.println(t21.getSource());
        System.out.println(t21.getDestination());
        System.out.println(t21.getPrice());
        System.out.println(t21.getTravelDate());
        System.out.println(t21.getSeatNumber());

        TicketDetails t22 = new TicketDetails();
        t22.setTicketId(22);
        t22.setPassengerName("Passenger22");
        t22.setSource("CityA");
        t22.setDestination("CityB");
        t22.setPrice(2600.0);
        t22.setTravelDate("2024-01-22");
        t22.setSeatNumber("S22");
        System.out.println(t22.getTicketId());
        System.out.println(t22.getPassengerName());
        System.out.println(t22.getSource());
        System.out.println(t22.getDestination());
        System.out.println(t22.getPrice());
        System.out.println(t22.getTravelDate());
        System.out.println(t22.getSeatNumber());

        TicketDetails t23 = new TicketDetails();
        t23.setTicketId(23);
        t23.setPassengerName("Passenger23");
        t23.setSource("CityA");
        t23.setDestination("CityB");
        t23.setPrice(2700.0);
        t23.setTravelDate("2024-01-23");
        t23.setSeatNumber("S23");
        System.out.println(t23.getTicketId());
        System.out.println(t23.getPassengerName());
        System.out.println(t23.getSource());
        System.out.println(t23.getDestination());
        System.out.println(t23.getPrice());
        System.out.println(t23.getTravelDate());
        System.out.println(t23.getSeatNumber());

        TicketDetails t24 = new TicketDetails();
        t24.setTicketId(24);
        t24.setPassengerName("Passenger24");
        t24.setSource("CityA");
        t24.setDestination("CityB");
        t24.setPrice(2800.0);
        t24.setTravelDate("2024-01-24");
        t24.setSeatNumber("S24");
        System.out.println(t24.getTicketId());
        System.out.println(t24.getPassengerName());
        System.out.println(t24.getSource());
        System.out.println(t24.getDestination());
        System.out.println(t24.getPrice());
        System.out.println(t24.getTravelDate());
        System.out.println(t24.getSeatNumber());

        TicketDetails t25 = new TicketDetails();
        t25.setTicketId(25);
        t25.setPassengerName("Passenger25");
        t25.setSource("CityA");
        t25.setDestination("CityB");
        t25.setPrice(2900.0);
        t25.setTravelDate("2024-01-25");
        t25.setSeatNumber("S25");
        System.out.println(t25.getTicketId());
        System.out.println(t25.getPassengerName());
        System.out.println(t25.getSource());
        System.out.println(t25.getDestination());
        System.out.println(t25.getPrice());
        System.out.println(t25.getTravelDate());
        System.out.println(t25.getSeatNumber());

        TicketDetails t26 = new TicketDetails();
        t26.setTicketId(26);
        t26.setPassengerName("Passenger26");
        t26.setSource("CityA");
        t26.setDestination("CityB");
        t26.setPrice(3000.0);
        t26.setTravelDate("2024-01-26");
        t26.setSeatNumber("S26");
        System.out.println(t26.getTicketId());
        System.out.println(t26.getPassengerName());
        System.out.println(t26.getSource());
        System.out.println(t26.getDestination());
        System.out.println(t26.getPrice());
        System.out.println(t26.getTravelDate());
        System.out.println(t26.getSeatNumber());

        TicketDetails t27 = new TicketDetails();
        t27.setTicketId(27);
        t27.setPassengerName("Passenger27");
        t27.setSource("CityA");
        t27.setDestination("CityB");
        t27.setPrice(3100.0);
        t27.setTravelDate("2024-01-27");
        t27.setSeatNumber("S27");
        System.out.println(t27.getTicketId());
        System.out.println(t27.getPassengerName());
        System.out.println(t27.getSource());
        System.out.println(t27.getDestination());
        System.out.println(t27.getPrice());
        System.out.println(t27.getTravelDate());
        System.out.println(t27.getSeatNumber());

        TicketDetails t28 = new TicketDetails();
        t28.setTicketId(28);
        t28.setPassengerName("Passenger28");
        t28.setSource("CityA");
        t28.setDestination("CityB");
        t28.setPrice(3200.0);
        t28.setTravelDate("2024-01-28");
        t28.setSeatNumber("S28");
        System.out.println(t28.getTicketId());
        System.out.println(t28.getPassengerName());
        System.out.println(t28.getSource());
        System.out.println(t28.getDestination());
        System.out.println(t28.getPrice());
        System.out.println(t28.getTravelDate());
        System.out.println(t28.getSeatNumber());

        TicketDetails t29 = new TicketDetails();
        t29.setTicketId(29);
        t29.setPassengerName("Passenger29");
        t29.setSource("CityA");
        t29.setDestination("CityB");
        t29.setPrice(3300.0);
        t29.setTravelDate("2024-01-29");
        t29.setSeatNumber("S29");
        System.out.println(t29.getTicketId());
        System.out.println(t29.getPassengerName());
        System.out.println(t29.getSource());
        System.out.println(t29.getDestination());
        System.out.println(t29.getPrice());
        System.out.println(t29.getTravelDate());
        System.out.println(t29.getSeatNumber());
    }
}