class TransportCompanyExecutor{
public static void main(String[] args){
TransportCompany refOne = new TransportCompany();

System.out.println("The companyId is: " + refOne.companyId);
System.out.println("The companyName is: " + refOne.companyName);
System.out.println("The ceoName is: " + refOne.ceoName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfVehicles is: " + refOne.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refOne.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refOne.numberOfEmployees);
System.out.println("The hasCargoService is: " + refOne.hasCargoService);
System.out.println("The hasPassengerService is: " + refOne.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refOne.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refOne.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refOne.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refOne.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refOne.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refOne.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The companyType is: " + refOne.companyType);
System.out.println("The annualRevenue is: " + refOne.annualRevenue);
System.out.println("The headquarters is: " + refOne.headquarters);

refOne.companyId = 1;
refOne.companyName = "SpeedLine Transport";
refOne.ceoName = "Rohit Sharma";
refOne.location = "Industrial Area";
refOne.city = "Bengaluru";
refOne.state = "Karnataka";
refOne.country = "India";
refOne.numberOfVehicles = 120;
refOne.numberOfDrivers = 95;
refOne.numberOfEmployees = 150;
refOne.hasCargoService = true;
refOne.hasPassengerService = false;
refOne.hasOnlineBooking = true;
refOne.hasMobileApp = true;
refOne.hasTrackingSystem = true;
refOne.hasWarehousing = true;
refOne.hasMaintenanceFacility = true;
refOne.hasInsuranceCoverage = true;
refOne.contactNumber = "9876543210";
refOne.email = "info@speedline.com";
refOne.website = "www.speedline.com";
refOne.establishedYear = 2010;
refOne.companyType = "Logistics";
refOne.annualRevenue = 25.75;
refOne.headquarters = "Bengaluru";

System.out.println("The companyId is: " + refOne.companyId);
System.out.println("The companyName is: " + refOne.companyName);
System.out.println("The ceoName is: " + refOne.ceoName);
System.out.println("The location is: " + refOne.location);
System.out.println("The city is: " + refOne.city);
System.out.println("The state is: " + refOne.state);
System.out.println("The country is: " + refOne.country);
System.out.println("The numberOfVehicles is: " + refOne.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refOne.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refOne.numberOfEmployees);
System.out.println("The hasCargoService is: " + refOne.hasCargoService);
System.out.println("The hasPassengerService is: " + refOne.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refOne.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refOne.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refOne.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refOne.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refOne.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refOne.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refOne.contactNumber);
System.out.println("The email is: " + refOne.email);
System.out.println("The website is: " + refOne.website);
System.out.println("The establishedYear is: " + refOne.establishedYear);
System.out.println("The companyType is: " + refOne.companyType);
System.out.println("The annualRevenue is: " + refOne.annualRevenue);
System.out.println("The headquarters is: " + refOne.headquarters);
TransportCompany refTwo = new TransportCompany();

System.out.println("The companyId is: " + refTwo.companyId);
System.out.println("The companyName is: " + refTwo.companyName);
System.out.println("The ceoName is: " + refTwo.ceoName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfVehicles is: " + refTwo.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refTwo.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refTwo.numberOfEmployees);
System.out.println("The hasCargoService is: " + refTwo.hasCargoService);
System.out.println("The hasPassengerService is: " + refTwo.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refTwo.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refTwo.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refTwo.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refTwo.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refTwo.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refTwo.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The companyType is: " + refTwo.companyType);
System.out.println("The annualRevenue is: " + refTwo.annualRevenue);
System.out.println("The headquarters is: " + refTwo.headquarters);

refTwo.companyId = 2;
refTwo.companyName = "GreenWay Logistics";
refTwo.ceoName = "Anita Desai";
refTwo.location = "MG Road";
refTwo.city = "Mumbai";
refTwo.state = "Maharashtra";
refTwo.country = "India";
refTwo.numberOfVehicles = 200;
refTwo.numberOfDrivers = 160;
refTwo.numberOfEmployees = 250;
refTwo.hasCargoService = true;
refTwo.hasPassengerService = false;
refTwo.hasOnlineBooking = true;
refTwo.hasMobileApp = true;
refTwo.hasTrackingSystem = true;
refTwo.hasWarehousing = true;
refTwo.hasMaintenanceFacility = true;
refTwo.hasInsuranceCoverage = true;
refTwo.contactNumber = "9876501234";
refTwo.email = "support@greenway.com";
refTwo.website = "www.greenwaylogistics.com";
refTwo.establishedYear = 2012;
refTwo.companyType = "Logistics";
refTwo.annualRevenue = 40.50;
refTwo.headquarters = "Mumbai";

System.out.println("The companyId is: " + refTwo.companyId);
System.out.println("The companyName is: " + refTwo.companyName);
System.out.println("The ceoName is: " + refTwo.ceoName);
System.out.println("The location is: " + refTwo.location);
System.out.println("The city is: " + refTwo.city);
System.out.println("The state is: " + refTwo.state);
System.out.println("The country is: " + refTwo.country);
System.out.println("The numberOfVehicles is: " + refTwo.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refTwo.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refTwo.numberOfEmployees);
System.out.println("The hasCargoService is: " + refTwo.hasCargoService);
System.out.println("The hasPassengerService is: " + refTwo.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refTwo.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refTwo.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refTwo.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refTwo.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refTwo.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refTwo.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refTwo.contactNumber);
System.out.println("The email is: " + refTwo.email);
System.out.println("The website is: " + refTwo.website);
System.out.println("The establishedYear is: " + refTwo.establishedYear);
System.out.println("The companyType is: " + refTwo.companyType);
System.out.println("The annualRevenue is: " + refTwo.annualRevenue);
System.out.println("The headquarters is: " + refTwo.headquarters);
TransportCompany refThree = new TransportCompany();

System.out.println("The companyId is: " + refThree.companyId);
System.out.println("The companyName is: " + refThree.companyName);
System.out.println("The ceoName is: " + refThree.ceoName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfVehicles is: " + refThree.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refThree.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refThree.numberOfEmployees);
System.out.println("The hasCargoService is: " + refThree.hasCargoService);
System.out.println("The hasPassengerService is: " + refThree.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refThree.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refThree.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refThree.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refThree.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refThree.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refThree.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The companyType is: " + refThree.companyType);
System.out.println("The annualRevenue is: " + refThree.annualRevenue);
System.out.println("The headquarters is: " + refThree.headquarters);

refThree.companyId = 3;
refThree.companyName = "Skyline Transport";
refThree.ceoName = "Vikram Mehta";
refThree.location = "Connaught Place";
refThree.city = "Delhi";
refThree.state = "Delhi";
refThree.country = "India";
refThree.numberOfVehicles = 150;
refThree.numberOfDrivers = 120;
refThree.numberOfEmployees = 210;
refThree.hasCargoService = true;
refThree.hasPassengerService = true;
refThree.hasOnlineBooking = true;
refThree.hasMobileApp = false;
refThree.hasTrackingSystem = true;
refThree.hasWarehousing = true;
refThree.hasMaintenanceFacility = true;
refThree.hasInsuranceCoverage = true;
refThree.contactNumber = "9123456780";
refThree.email = "contact@skyline.com";
refThree.website = "www.skylinetransport.com";
refThree.establishedYear = 2008;
refThree.companyType = "Transport & Logistics";
refThree.annualRevenue = 55.80;
refThree.headquarters = "Delhi";

System.out.println("The companyId is: " + refThree.companyId);
System.out.println("The companyName is: " + refThree.companyName);
System.out.println("The ceoName is: " + refThree.ceoName);
System.out.println("The location is: " + refThree.location);
System.out.println("The city is: " + refThree.city);
System.out.println("The state is: " + refThree.state);
System.out.println("The country is: " + refThree.country);
System.out.println("The numberOfVehicles is: " + refThree.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refThree.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refThree.numberOfEmployees);
System.out.println("The hasCargoService is: " + refThree.hasCargoService);
System.out.println("The hasPassengerService is: " + refThree.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refThree.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refThree.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refThree.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refThree.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refThree.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refThree.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refThree.contactNumber);
System.out.println("The email is: " + refThree.email);
System.out.println("The website is: " + refThree.website);
System.out.println("The establishedYear is: " + refThree.establishedYear);
System.out.println("The companyType is: " + refThree.companyType);
System.out.println("The annualRevenue is: " + refThree.annualRevenue);
System.out.println("The headquarters is: " + refThree.headquarters);
TransportCompany refFour = new TransportCompany();

System.out.println("The companyId is: " + refFour.companyId);
System.out.println("The companyName is: " + refFour.companyName);
System.out.println("The ceoName is: " + refFour.ceoName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfVehicles is: " + refFour.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refFour.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refFour.numberOfEmployees);
System.out.println("The hasCargoService is: " + refFour.hasCargoService);
System.out.println("The hasPassengerService is: " + refFour.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refFour.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refFour.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refFour.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refFour.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refFour.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refFour.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The companyType is: " + refFour.companyType);
System.out.println("The annualRevenue is: " + refFour.annualRevenue);
System.out.println("The headquarters is: " + refFour.headquarters);

refFour.companyId = 4;
refFour.companyName = "RapidMove Logistics";
refFour.ceoName = "Sanjay Gupta";
refFour.location = "Salt Lake";
refFour.city = "Kolkata";
refFour.state = "West Bengal";
refFour.country = "India";
refFour.numberOfVehicles = 175;
refFour.numberOfDrivers = 140;
refFour.numberOfEmployees = 230;
refFour.hasCargoService = true;
refFour.hasPassengerService = false;
refFour.hasOnlineBooking = true;
refFour.hasMobileApp = true;
refFour.hasTrackingSystem = true;
refFour.hasWarehousing = true;
refFour.hasMaintenanceFacility = true;
refFour.hasInsuranceCoverage = true;
refFour.contactNumber = "9012345678";
refFour.email = "info@rapidmove.com";
refFour.website = "www.rapidmove.com";
refFour.establishedYear = 2015;
refFour.companyType = "Cargo & Logistics";
refFour.annualRevenue = 32.40;
refFour.headquarters = "Kolkata";

System.out.println("The companyId is: " + refFour.companyId);
System.out.println("The companyName is: " + refFour.companyName);
System.out.println("The ceoName is: " + refFour.ceoName);
System.out.println("The location is: " + refFour.location);
System.out.println("The city is: " + refFour.city);
System.out.println("The state is: " + refFour.state);
System.out.println("The country is: " + refFour.country);
System.out.println("The numberOfVehicles is: " + refFour.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refFour.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refFour.numberOfEmployees);
System.out.println("The hasCargoService is: " + refFour.hasCargoService);
System.out.println("The hasPassengerService is: " + refFour.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refFour.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refFour.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refFour.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refFour.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refFour.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refFour.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refFour.contactNumber);
System.out.println("The email is: " + refFour.email);
System.out.println("The website is: " + refFour.website);
System.out.println("The establishedYear is: " + refFour.establishedYear);
System.out.println("The companyType is: " + refFour.companyType);
System.out.println("The annualRevenue is: " + refFour.annualRevenue);
System.out.println("The headquarters is: " + refFour.headquarters);
TransportCompany refFive = new TransportCompany();

System.out.println("The companyId is: " + refFive.companyId);
System.out.println("The companyName is: " + refFive.companyName);
System.out.println("The ceoName is: " + refFive.ceoName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfVehicles is: " + refFive.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refFive.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refFive.numberOfEmployees);
System.out.println("The hasCargoService is: " + refFive.hasCargoService);
System.out.println("The hasPassengerService is: " + refFive.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refFive.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refFive.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refFive.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refFive.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refFive.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refFive.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The companyType is: " + refFive.companyType);
System.out.println("The annualRevenue is: " + refFive.annualRevenue);
System.out.println("The headquarters is: " + refFive.headquarters);

refFive.companyId = 5;
refFive.companyName = "BlueLine Transport";
refFive.ceoName = "Arjun Reddy";
refFive.location = "Banjara Hills";
refFive.city = "Hyderabad";
refFive.state = "Telangana";
refFive.country = "India";
refFive.numberOfVehicles = 220;
refFive.numberOfDrivers = 180;
refFive.numberOfEmployees = 300;
refFive.hasCargoService = true;
refFive.hasPassengerService = true;
refFive.hasOnlineBooking = true;
refFive.hasMobileApp = true;
refFive.hasTrackingSystem = true;
refFive.hasWarehousing = false;
refFive.hasMaintenanceFacility = true;
refFive.hasInsuranceCoverage = true;
refFive.contactNumber = "9988776655";
refFive.email = "support@blueline.com";
refFive.website = "www.bluelinetransport.com";
refFive.establishedYear = 2011;
refFive.companyType = "Passenger & Cargo";
refFive.annualRevenue = 48.90;
refFive.headquarters = "Hyderabad";

System.out.println("The companyId is: " + refFive.companyId);
System.out.println("The companyName is: " + refFive.companyName);
System.out.println("The ceoName is: " + refFive.ceoName);
System.out.println("The location is: " + refFive.location);
System.out.println("The city is: " + refFive.city);
System.out.println("The state is: " + refFive.state);
System.out.println("The country is: " + refFive.country);
System.out.println("The numberOfVehicles is: " + refFive.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refFive.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refFive.numberOfEmployees);
System.out.println("The hasCargoService is: " + refFive.hasCargoService);
System.out.println("The hasPassengerService is: " + refFive.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refFive.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refFive.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refFive.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refFive.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refFive.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refFive.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refFive.contactNumber);
System.out.println("The email is: " + refFive.email);
System.out.println("The website is: " + refFive.website);
System.out.println("The establishedYear is: " + refFive.establishedYear);
System.out.println("The companyType is: " + refFive.companyType);
System.out.println("The annualRevenue is: " + refFive.annualRevenue);
System.out.println("The headquarters is: " + refFive.headquarters);
TransportCompany refSix = new TransportCompany();

System.out.println("The companyId is: " + refSix.companyId);
System.out.println("The companyName is: " + refSix.companyName);
System.out.println("The ceoName is: " + refSix.ceoName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfVehicles is: " + refSix.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refSix.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refSix.numberOfEmployees);
System.out.println("The hasCargoService is: " + refSix.hasCargoService);
System.out.println("The hasPassengerService is: " + refSix.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refSix.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refSix.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refSix.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refSix.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refSix.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refSix.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The companyType is: " + refSix.companyType);
System.out.println("The annualRevenue is: " + refSix.annualRevenue);
System.out.println("The headquarters is: " + refSix.headquarters);

refSix.companyId = 6;
refSix.companyName = "Metro Cargo Services";
refSix.ceoName = "Rahul Khanna";
refSix.location = "Anna Nagar";
refSix.city = "Chennai";
refSix.state = "Tamil Nadu";
refSix.country = "India";
refSix.numberOfVehicles = 140;
refSix.numberOfDrivers = 110;
refSix.numberOfEmployees = 190;
refSix.hasCargoService = true;
refSix.hasPassengerService = false;
refSix.hasOnlineBooking = true;
refSix.hasMobileApp = false;
refSix.hasTrackingSystem = true;
refSix.hasWarehousing = true;
refSix.hasMaintenanceFacility = true;
refSix.hasInsuranceCoverage = true;
refSix.contactNumber = "9871234560";
refSix.email = "info@metrocargo.com";
refSix.website = "www.metrocargo.com";
refSix.establishedYear = 2009;
refSix.companyType = "Cargo Transport";
refSix.annualRevenue = 29.60;
refSix.headquarters = "Chennai";

System.out.println("The companyId is: " + refSix.companyId);
System.out.println("The companyName is: " + refSix.companyName);
System.out.println("The ceoName is: " + refSix.ceoName);
System.out.println("The location is: " + refSix.location);
System.out.println("The city is: " + refSix.city);
System.out.println("The state is: " + refSix.state);
System.out.println("The country is: " + refSix.country);
System.out.println("The numberOfVehicles is: " + refSix.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refSix.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refSix.numberOfEmployees);
System.out.println("The hasCargoService is: " + refSix.hasCargoService);
System.out.println("The hasPassengerService is: " + refSix.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refSix.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refSix.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refSix.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refSix.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refSix.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refSix.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refSix.contactNumber);
System.out.println("The email is: " + refSix.email);
System.out.println("The website is: " + refSix.website);
System.out.println("The establishedYear is: " + refSix.establishedYear);
System.out.println("The companyType is: " + refSix.companyType);
System.out.println("The annualRevenue is: " + refSix.annualRevenue);
System.out.println("The headquarters is: " + refSix.headquarters);
TransportCompany refSeven = new TransportCompany();

System.out.println("The companyId is: " + refSeven.companyId);
System.out.println("The companyName is: " + refSeven.companyName);
System.out.println("The ceoName is: " + refSeven.ceoName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfVehicles is: " + refSeven.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refSeven.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refSeven.numberOfEmployees);
System.out.println("The hasCargoService is: " + refSeven.hasCargoService);
System.out.println("The hasPassengerService is: " + refSeven.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refSeven.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refSeven.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refSeven.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refSeven.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refSeven.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refSeven.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The companyType is: " + refSeven.companyType);
System.out.println("The annualRevenue is: " + refSeven.annualRevenue);
System.out.println("The headquarters is: " + refSeven.headquarters);

refSeven.companyId = 7;
refSeven.companyName = "ExpressWay Transport";
refSeven.ceoName = "Karan Malhotra";
refSeven.location = "Sector 62";
refSeven.city = "Noida";
refSeven.state = "Uttar Pradesh";
refSeven.country = "India";
refSeven.numberOfVehicles = 165;
refSeven.numberOfDrivers = 130;
refSeven.numberOfEmployees = 210;
refSeven.hasCargoService = true;
refSeven.hasPassengerService = false;
refSeven.hasOnlineBooking = true;
refSeven.hasMobileApp = true;
refSeven.hasTrackingSystem = true;
refSeven.hasWarehousing = true;
refSeven.hasMaintenanceFacility = true;
refSeven.hasInsuranceCoverage = true;
refSeven.contactNumber = "9874501236";
refSeven.email = "contact@expressway.com";
refSeven.website = "www.expresswaytransport.com";
refSeven.establishedYear = 2013;
refSeven.companyType = "Logistics";
refSeven.annualRevenue = 37.80;
refSeven.headquarters = "Noida";

System.out.println("The companyId is: " + refSeven.companyId);
System.out.println("The companyName is: " + refSeven.companyName);
System.out.println("The ceoName is: " + refSeven.ceoName);
System.out.println("The location is: " + refSeven.location);
System.out.println("The city is: " + refSeven.city);
System.out.println("The state is: " + refSeven.state);
System.out.println("The country is: " + refSeven.country);
System.out.println("The numberOfVehicles is: " + refSeven.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refSeven.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refSeven.numberOfEmployees);
System.out.println("The hasCargoService is: " + refSeven.hasCargoService);
System.out.println("The hasPassengerService is: " + refSeven.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refSeven.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refSeven.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refSeven.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refSeven.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refSeven.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refSeven.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refSeven.contactNumber);
System.out.println("The email is: " + refSeven.email);
System.out.println("The website is: " + refSeven.website);
System.out.println("The establishedYear is: " + refSeven.establishedYear);
System.out.println("The companyType is: " + refSeven.companyType);
System.out.println("The annualRevenue is: " + refSeven.annualRevenue);
System.out.println("The headquarters is: " + refSeven.headquarters);
TransportCompany refEight = new TransportCompany();

System.out.println("The companyId is: " + refEight.companyId);
System.out.println("The companyName is: " + refEight.companyName);
System.out.println("The ceoName is: " + refEight.ceoName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfVehicles is: " + refEight.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refEight.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refEight.numberOfEmployees);
System.out.println("The hasCargoService is: " + refEight.hasCargoService);
System.out.println("The hasPassengerService is: " + refEight.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refEight.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refEight.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refEight.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refEight.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refEight.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refEight.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The companyType is: " + refEight.companyType);
System.out.println("The annualRevenue is: " + refEight.annualRevenue);
System.out.println("The headquarters is: " + refEight.headquarters);

refEight.companyId = 8;
refEight.companyName = "FastTrack Logistics";
refEight.ceoName = "Neha Kapoor";
refEight.location = "Whitefield";
refEight.city = "Bengaluru";
refEight.state = "Karnataka";
refEight.country = "India";
refEight.numberOfVehicles = 190;
refEight.numberOfDrivers = 150;
refEight.numberOfEmployees = 260;
refEight.hasCargoService = true;
refEight.hasPassengerService = false;
refEight.hasOnlineBooking = true;
refEight.hasMobileApp = true;
refEight.hasTrackingSystem = true;
refEight.hasWarehousing = true;
refEight.hasMaintenanceFacility = true;
refEight.hasInsuranceCoverage = true;
refEight.contactNumber = "9988123456";
refEight.email = "info@fasttrack.com";
refEight.website = "www.fasttracklogistics.com";
refEight.establishedYear = 2014;
refEight.companyType = "Logistics";
refEight.annualRevenue = 41.20;
refEight.headquarters = "Bengaluru";

System.out.println("The companyId is: " + refEight.companyId);
System.out.println("The companyName is: " + refEight.companyName);
System.out.println("The ceoName is: " + refEight.ceoName);
System.out.println("The location is: " + refEight.location);
System.out.println("The city is: " + refEight.city);
System.out.println("The state is: " + refEight.state);
System.out.println("The country is: " + refEight.country);
System.out.println("The numberOfVehicles is: " + refEight.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refEight.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refEight.numberOfEmployees);
System.out.println("The hasCargoService is: " + refEight.hasCargoService);
System.out.println("The hasPassengerService is: " + refEight.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refEight.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refEight.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refEight.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refEight.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refEight.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refEight.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refEight.contactNumber);
System.out.println("The email is: " + refEight.email);
System.out.println("The website is: " + refEight.website);
System.out.println("The establishedYear is: " + refEight.establishedYear);
System.out.println("The companyType is: " + refEight.companyType);
System.out.println("The annualRevenue is: " + refEight.annualRevenue);
System.out.println("The headquarters is: " + refEight.headquarters);
TransportCompany refNine = new TransportCompany();

System.out.println("The companyId is: " + refNine.companyId);
System.out.println("The companyName is: " + refNine.companyName);
System.out.println("The ceoName is: " + refNine.ceoName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfVehicles is: " + refNine.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refNine.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refNine.numberOfEmployees);
System.out.println("The hasCargoService is: " + refNine.hasCargoService);
System.out.println("The hasPassengerService is: " + refNine.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refNine.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refNine.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refNine.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refNine.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refNine.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refNine.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The companyType is: " + refNine.companyType);
System.out.println("The annualRevenue is: " + refNine.annualRevenue);
System.out.println("The headquarters is: " + refNine.headquarters);

refNine.companyId = 9;
refNine.companyName = "Global Move Transport";
refNine.ceoName = "Priya Nair";
refNine.location = "Panampilly Nagar";
refNine.city = "Kochi";
refNine.state = "Kerala";
refNine.country = "India";
refNine.numberOfVehicles = 130;
refNine.numberOfDrivers = 100;
refNine.numberOfEmployees = 170;
refNine.hasCargoService = true;
refNine.hasPassengerService = false;
refNine.hasOnlineBooking = true;
refNine.hasMobileApp = true;
refNine.hasTrackingSystem = true;
refNine.hasWarehousing = false;
refNine.hasMaintenanceFacility = true;
refNine.hasInsuranceCoverage = true;
refNine.contactNumber = "9898981234";
refNine.email = "contact@globalmove.com";
refNine.website = "www.globalmove.com";
refNine.establishedYear = 2016;
refNine.companyType = "Logistics";
refNine.annualRevenue = 27.45;
refNine.headquarters = "Kochi";

System.out.println("The companyId is: " + refNine.companyId);
System.out.println("The companyName is: " + refNine.companyName);
System.out.println("The ceoName is: " + refNine.ceoName);
System.out.println("The location is: " + refNine.location);
System.out.println("The city is: " + refNine.city);
System.out.println("The state is: " + refNine.state);
System.out.println("The country is: " + refNine.country);
System.out.println("The numberOfVehicles is: " + refNine.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refNine.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refNine.numberOfEmployees);
System.out.println("The hasCargoService is: " + refNine.hasCargoService);
System.out.println("The hasPassengerService is: " + refNine.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refNine.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refNine.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refNine.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refNine.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refNine.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refNine.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refNine.contactNumber);
System.out.println("The email is: " + refNine.email);
System.out.println("The website is: " + refNine.website);
System.out.println("The establishedYear is: " + refNine.establishedYear);
System.out.println("The companyType is: " + refNine.companyType);
System.out.println("The annualRevenue is: " + refNine.annualRevenue);
System.out.println("The headquarters is: " + refNine.headquarters);
TransportCompany refTen = new TransportCompany();

System.out.println("The companyId is: " + refTen.companyId);
System.out.println("The companyName is: " + refTen.companyName);
System.out.println("The ceoName is: " + refTen.ceoName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfVehicles is: " + refTen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refTen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refTen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refTen.hasCargoService);
System.out.println("The hasPassengerService is: " + refTen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refTen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refTen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refTen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refTen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refTen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refTen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The companyType is: " + refTen.companyType);
System.out.println("The annualRevenue is: " + refTen.annualRevenue);
System.out.println("The headquarters is: " + refTen.headquarters);

refTen.companyId = 10;
refTen.companyName = "Prime Cargo Movers";
refTen.ceoName = "Amit Verma";
refTen.location = "Indiranagar";
refTen.city = "Bengaluru";
refTen.state = "Karnataka";
refTen.country = "India";
refTen.numberOfVehicles = 210;
refTen.numberOfDrivers = 170;
refTen.numberOfEmployees = 290;
refTen.hasCargoService = true;
refTen.hasPassengerService = false;
refTen.hasOnlineBooking = true;
refTen.hasMobileApp = true;
refTen.hasTrackingSystem = true;
refTen.hasWarehousing = true;
refTen.hasMaintenanceFacility = true;
refTen.hasInsuranceCoverage = true;
refTen.contactNumber = "9001234567";
refTen.email = "support@primecargo.com";
refTen.website = "www.primecargo.com";
refTen.establishedYear = 2017;
refTen.companyType = "Logistics";
refTen.annualRevenue = 46.75;
refTen.headquarters = "Bengaluru";

System.out.println("The companyId is: " + refTen.companyId);
System.out.println("The companyName is: " + refTen.companyName);
System.out.println("The ceoName is: " + refTen.ceoName);
System.out.println("The location is: " + refTen.location);
System.out.println("The city is: " + refTen.city);
System.out.println("The state is: " + refTen.state);
System.out.println("The country is: " + refTen.country);
System.out.println("The numberOfVehicles is: " + refTen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refTen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refTen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refTen.hasCargoService);
System.out.println("The hasPassengerService is: " + refTen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refTen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refTen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refTen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refTen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refTen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refTen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refTen.contactNumber);
System.out.println("The email is: " + refTen.email);
System.out.println("The website is: " + refTen.website);
System.out.println("The establishedYear is: " + refTen.establishedYear);
System.out.println("The companyType is: " + refTen.companyType);
System.out.println("The annualRevenue is: " + refTen.annualRevenue);
System.out.println("The headquarters is: " + refTen.headquarters);
TransportCompany refEleven = new TransportCompany();

System.out.println("The companyId is: " + refEleven.companyId);
System.out.println("The companyName is: " + refEleven.companyName);
System.out.println("The ceoName is: " + refEleven.ceoName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfVehicles is: " + refEleven.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refEleven.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refEleven.numberOfEmployees);
System.out.println("The hasCargoService is: " + refEleven.hasCargoService);
System.out.println("The hasPassengerService is: " + refEleven.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refEleven.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refEleven.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refEleven.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refEleven.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refEleven.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refEleven.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The companyType is: " + refEleven.companyType);
System.out.println("The annualRevenue is: " + refEleven.annualRevenue);
System.out.println("The headquarters is: " + refEleven.headquarters);

refEleven.companyId = 11;
refEleven.companyName = "Swift Wheels Logistics";
refEleven.ceoName = "Deepak Arora";
refEleven.location = "Rajajinagar";
refEleven.city = "Bengaluru";
refEleven.state = "Karnataka";
refEleven.country = "India";
refEleven.numberOfVehicles = 160;
refEleven.numberOfDrivers = 125;
refEleven.numberOfEmployees = 205;
refEleven.hasCargoService = true;
refEleven.hasPassengerService = false;
refEleven.hasOnlineBooking = true;
refEleven.hasMobileApp = true;
refEleven.hasTrackingSystem = true;
refEleven.hasWarehousing = true;
refEleven.hasMaintenanceFacility = true;
refEleven.hasInsuranceCoverage = true;
refEleven.contactNumber = "9011122233";
refEleven.email = "info@swiftwheels.com";
refEleven.website = "www.swiftwheels.com";
refEleven.establishedYear = 2018;
refEleven.companyType = "Logistics";
refEleven.annualRevenue = 35.60;
refEleven.headquarters = "Bengaluru";

System.out.println("The companyId is: " + refEleven.companyId);
System.out.println("The companyName is: " + refEleven.companyName);
System.out.println("The ceoName is: " + refEleven.ceoName);
System.out.println("The location is: " + refEleven.location);
System.out.println("The city is: " + refEleven.city);
System.out.println("The state is: " + refEleven.state);
System.out.println("The country is: " + refEleven.country);
System.out.println("The numberOfVehicles is: " + refEleven.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refEleven.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refEleven.numberOfEmployees);
System.out.println("The hasCargoService is: " + refEleven.hasCargoService);
System.out.println("The hasPassengerService is: " + refEleven.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refEleven.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refEleven.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refEleven.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refEleven.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refEleven.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refEleven.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refEleven.contactNumber);
System.out.println("The email is: " + refEleven.email);
System.out.println("The website is: " + refEleven.website);
System.out.println("The establishedYear is: " + refEleven.establishedYear);
System.out.println("The companyType is: " + refEleven.companyType);
System.out.println("The annualRevenue is: " + refEleven.annualRevenue);
System.out.println("The headquarters is: " + refEleven.headquarters);
TransportCompany refTwelve = new TransportCompany();

System.out.println("The companyId is: " + refTwelve.companyId);
System.out.println("The companyName is: " + refTwelve.companyName);
System.out.println("The ceoName is: " + refTwelve.ceoName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfVehicles is: " + refTwelve.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refTwelve.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refTwelve.numberOfEmployees);
System.out.println("The hasCargoService is: " + refTwelve.hasCargoService);
System.out.println("The hasPassengerService is: " + refTwelve.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refTwelve.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refTwelve.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refTwelve.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refTwelve.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refTwelve.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refTwelve.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The companyType is: " + refTwelve.companyType);
System.out.println("The annualRevenue is: " + refTwelve.annualRevenue);
System.out.println("The headquarters is: " + refTwelve.headquarters);

refTwelve.companyId = 12;
refTwelve.companyName = "National Freight Movers";
refTwelve.ceoName = "Rakesh Menon";
refTwelve.location = "Vyttila";
refTwelve.city = "Kochi";
refTwelve.state = "Kerala";
refTwelve.country = "India";
refTwelve.numberOfVehicles = 180;
refTwelve.numberOfDrivers = 140;
refTwelve.numberOfEmployees = 220;
refTwelve.hasCargoService = true;
refTwelve.hasPassengerService = false;
refTwelve.hasOnlineBooking = true;
refTwelve.hasMobileApp = true;
refTwelve.hasTrackingSystem = true;
refTwelve.hasWarehousing = true;
refTwelve.hasMaintenanceFacility = true;
refTwelve.hasInsuranceCoverage = true;
refTwelve.contactNumber = "9123456789";
refTwelve.email = "contact@nationalfreight.com";
refTwelve.website = "www.nationalfreight.com";
refTwelve.establishedYear = 2014;
refTwelve.companyType = "Freight Transport";
refTwelve.annualRevenue = 39.25;
refTwelve.headquarters = "Kochi";

System.out.println("The companyId is: " + refTwelve.companyId);
System.out.println("The companyName is: " + refTwelve.companyName);
System.out.println("The ceoName is: " + refTwelve.ceoName);
System.out.println("The location is: " + refTwelve.location);
System.out.println("The city is: " + refTwelve.city);
System.out.println("The state is: " + refTwelve.state);
System.out.println("The country is: " + refTwelve.country);
System.out.println("The numberOfVehicles is: " + refTwelve.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refTwelve.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refTwelve.numberOfEmployees);
System.out.println("The hasCargoService is: " + refTwelve.hasCargoService);
System.out.println("The hasPassengerService is: " + refTwelve.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refTwelve.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refTwelve.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refTwelve.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refTwelve.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refTwelve.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refTwelve.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refTwelve.contactNumber);
System.out.println("The email is: " + refTwelve.email);
System.out.println("The website is: " + refTwelve.website);
System.out.println("The establishedYear is: " + refTwelve.establishedYear);
System.out.println("The companyType is: " + refTwelve.companyType);
System.out.println("The annualRevenue is: " + refTwelve.annualRevenue);
System.out.println("The headquarters is: " + refTwelve.headquarters);
TransportCompany refThirteen = new TransportCompany();

System.out.println("The companyId is: " + refThirteen.companyId);
System.out.println("The companyName is: " + refThirteen.companyName);
System.out.println("The ceoName is: " + refThirteen.ceoName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfVehicles is: " + refThirteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refThirteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refThirteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refThirteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refThirteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refThirteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refThirteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refThirteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refThirteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refThirteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refThirteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The companyType is: " + refThirteen.companyType);
System.out.println("The annualRevenue is: " + refThirteen.annualRevenue);
System.out.println("The headquarters is: " + refThirteen.headquarters);

refThirteen.companyId = 13;
refThirteen.companyName = "CityLink Transport";
refThirteen.ceoName = "Suresh Iyer";
refThirteen.location = "T Nagar";
refThirteen.city = "Chennai";
refThirteen.state = "Tamil Nadu";
refThirteen.country = "India";
refThirteen.numberOfVehicles = 155;
refThirteen.numberOfDrivers = 120;
refThirteen.numberOfEmployees = 200;
refThirteen.hasCargoService = true;
refThirteen.hasPassengerService = true;
refThirteen.hasOnlineBooking = true;
refThirteen.hasMobileApp = true;
refThirteen.hasTrackingSystem = true;
refThirteen.hasWarehousing = false;
refThirteen.hasMaintenanceFacility = true;
refThirteen.hasInsuranceCoverage = true;
refThirteen.contactNumber = "9012347890";
refThirteen.email = "support@citylink.com";
refThirteen.website = "www.citylinktransport.com";
refThirteen.establishedYear = 2015;
refThirteen.companyType = "Passenger & Cargo";
refThirteen.annualRevenue = 33.70;
refThirteen.headquarters = "Chennai";

System.out.println("The companyId is: " + refThirteen.companyId);
System.out.println("The companyName is: " + refThirteen.companyName);
System.out.println("The ceoName is: " + refThirteen.ceoName);
System.out.println("The location is: " + refThirteen.location);
System.out.println("The city is: " + refThirteen.city);
System.out.println("The state is: " + refThirteen.state);
System.out.println("The country is: " + refThirteen.country);
System.out.println("The numberOfVehicles is: " + refThirteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refThirteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refThirteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refThirteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refThirteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refThirteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refThirteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refThirteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refThirteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refThirteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refThirteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refThirteen.contactNumber);
System.out.println("The email is: " + refThirteen.email);
System.out.println("The website is: " + refThirteen.website);
System.out.println("The establishedYear is: " + refThirteen.establishedYear);
System.out.println("The companyType is: " + refThirteen.companyType);
System.out.println("The annualRevenue is: " + refThirteen.annualRevenue);
System.out.println("The headquarters is: " + refThirteen.headquarters);
TransportCompany refFourteen = new TransportCompany();

System.out.println("The companyId is: " + refFourteen.companyId);
System.out.println("The companyName is: " + refFourteen.companyName);
System.out.println("The ceoName is: " + refFourteen.ceoName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfVehicles is: " + refFourteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refFourteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refFourteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refFourteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refFourteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refFourteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refFourteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refFourteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refFourteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refFourteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refFourteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The companyType is: " + refFourteen.companyType);
System.out.println("The annualRevenue is: " + refFourteen.annualRevenue);
System.out.println("The headquarters is: " + refFourteen.headquarters);

refFourteen.companyId = 14;
refFourteen.companyName = "TransIndia Movers";
refFourteen.ceoName = "Karthik Rao";
refFourteen.location = "Malleswaram";
refFourteen.city = "Bengaluru";
refFourteen.state = "Karnataka";
refFourteen.country = "India";
refFourteen.numberOfVehicles = 175;
refFourteen.numberOfDrivers = 140;
refFourteen.numberOfEmployees = 230;
refFourteen.hasCargoService = true;
refFourteen.hasPassengerService = false;
refFourteen.hasOnlineBooking = true;
refFourteen.hasMobileApp = true;
refFourteen.hasTrackingSystem = true;
refFourteen.hasWarehousing = true;
refFourteen.hasMaintenanceFacility = true;
refFourteen.hasInsuranceCoverage = true;
refFourteen.contactNumber = "9098765432";
refFourteen.email = "info@transindia.com";
refFourteen.website = "www.transindia.com";
refFourteen.establishedYear = 2011;
refFourteen.companyType = "Logistics";
refFourteen.annualRevenue = 38.90;
refFourteen.headquarters = "Bengaluru";

System.out.println("The companyId is: " + refFourteen.companyId);
System.out.println("The companyName is: " + refFourteen.companyName);
System.out.println("The ceoName is: " + refFourteen.ceoName);
System.out.println("The location is: " + refFourteen.location);
System.out.println("The city is: " + refFourteen.city);
System.out.println("The state is: " + refFourteen.state);
System.out.println("The country is: " + refFourteen.country);
System.out.println("The numberOfVehicles is: " + refFourteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refFourteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refFourteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refFourteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refFourteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refFourteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refFourteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refFourteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refFourteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refFourteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refFourteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refFourteen.contactNumber);
System.out.println("The email is: " + refFourteen.email);
System.out.println("The website is: " + refFourteen.website);
System.out.println("The establishedYear is: " + refFourteen.establishedYear);
System.out.println("The companyType is: " + refFourteen.companyType);
System.out.println("The annualRevenue is: " + refFourteen.annualRevenue);
System.out.println("The headquarters is: " + refFourteen.headquarters);TransportCompany refFifteen = new TransportCompany();

System.out.println("The companyId is: " + refFifteen.companyId);
System.out.println("The companyName is: " + refFifteen.companyName);
System.out.println("The ceoName is: " + refFifteen.ceoName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfVehicles is: " + refFifteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refFifteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refFifteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refFifteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refFifteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refFifteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refFifteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refFifteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refFifteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refFifteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refFifteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The companyType is: " + refFifteen.companyType);
System.out.println("The annualRevenue is: " + refFifteen.annualRevenue);
System.out.println("The headquarters is: " + refFifteen.headquarters);

refFifteen.companyId = 15;
refFifteen.companyName = "UltraSpeed Logistics";
refFifteen.ceoName = "Nikhil Sharma";
refFifteen.location = "Andheri";
refFifteen.city = "Mumbai";
refFifteen.state = "Maharashtra";
refFifteen.country = "India";
refFifteen.numberOfVehicles = 195;
refFifteen.numberOfDrivers = 160;
refFifteen.numberOfEmployees = 250;
refFifteen.hasCargoService = true;
refFifteen.hasPassengerService = false;
refFifteen.hasOnlineBooking = true;
refFifteen.hasMobileApp = true;
refFifteen.hasTrackingSystem = true;
refFifteen.hasWarehousing = true;
refFifteen.hasMaintenanceFacility = true;
refFifteen.hasInsuranceCoverage = true;
refFifteen.contactNumber = "9988001122";
refFifteen.email = "info@ultraspeed.com";
refFifteen.website = "www.ultraspeedlogistics.com";
refFifteen.establishedYear = 2016;
refFifteen.companyType = "Logistics";
refFifteen.annualRevenue = 44.10;
refFifteen.headquarters = "Mumbai";

System.out.println("The companyId is: " + refFifteen.companyId);
System.out.println("The companyName is: " + refFifteen.companyName);
System.out.println("The ceoName is: " + refFifteen.ceoName);
System.out.println("The location is: " + refFifteen.location);
System.out.println("The city is: " + refFifteen.city);
System.out.println("The state is: " + refFifteen.state);
System.out.println("The country is: " + refFifteen.country);
System.out.println("The numberOfVehicles is: " + refFifteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refFifteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refFifteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refFifteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refFifteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refFifteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refFifteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refFifteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refFifteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refFifteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refFifteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refFifteen.contactNumber);
System.out.println("The email is: " + refFifteen.email);
System.out.println("The website is: " + refFifteen.website);
System.out.println("The establishedYear is: " + refFifteen.establishedYear);
System.out.println("The companyType is: " + refFifteen.companyType);
System.out.println("The annualRevenue is: " + refFifteen.annualRevenue);
System.out.println("The headquarters is: " + refFifteen.headquarters);
TransportCompany refSixteen = new TransportCompany();

System.out.println("The companyId is: " + refSixteen.companyId);
System.out.println("The companyName is: " + refSixteen.companyName);
System.out.println("The ceoName is: " + refSixteen.ceoName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfVehicles is: " + refSixteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refSixteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refSixteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refSixteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refSixteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refSixteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refSixteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refSixteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refSixteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refSixteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refSixteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The companyType is: " + refSixteen.companyType);
System.out.println("The annualRevenue is: " + refSixteen.annualRevenue);
System.out.println("The headquarters is: " + refSixteen.headquarters);

refSixteen.companyId = 16;
refSixteen.companyName = "Speed Cargo Express";
refSixteen.ceoName = "Anil Kumar";
refSixteen.location = "BTM Layout";
refSixteen.city = "Bengaluru";
refSixteen.state = "Karnataka";
refSixteen.country = "India";
refSixteen.numberOfVehicles = 145;
refSixteen.numberOfDrivers = 110;
refSixteen.numberOfEmployees = 190;
refSixteen.hasCargoService = true;
refSixteen.hasPassengerService = false;
refSixteen.hasOnlineBooking = true;
refSixteen.hasMobileApp = true;
refSixteen.hasTrackingSystem = true;
refSixteen.hasWarehousing = true;
refSixteen.hasMaintenanceFacility = true;
refSixteen.hasInsuranceCoverage = true;
refSixteen.contactNumber = "9870012345";
refSixteen.email = "info@speedcargo.com";
refSixteen.website = "www.speedcargoexpress.com";
refSixteen.establishedYear = 2013;
refSixteen.companyType = "Cargo Logistics";
refSixteen.annualRevenue = 30.85;
refSixteen.headquarters = "Bengaluru";

System.out.println("The companyId is: " + refSixteen.companyId);
System.out.println("The companyName is: " + refSixteen.companyName);
System.out.println("The ceoName is: " + refSixteen.ceoName);
System.out.println("The location is: " + refSixteen.location);
System.out.println("The city is: " + refSixteen.city);
System.out.println("The state is: " + refSixteen.state);
System.out.println("The country is: " + refSixteen.country);
System.out.println("The numberOfVehicles is: " + refSixteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refSixteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refSixteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refSixteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refSixteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refSixteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refSixteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refSixteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refSixteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refSixteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refSixteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refSixteen.contactNumber);
System.out.println("The email is: " + refSixteen.email);
System.out.println("The website is: " + refSixteen.website);
System.out.println("The establishedYear is: " + refSixteen.establishedYear);
System.out.println("The companyType is: " + refSixteen.companyType);
System.out.println("The annualRevenue is: " + refSixteen.annualRevenue);
System.out.println("The headquarters is: " + refSixteen.headquarters);
TransportCompany refSeventeen = new TransportCompany();

System.out.println("The companyId is: " + refSeventeen.companyId);
System.out.println("The companyName is: " + refSeventeen.companyName);
System.out.println("The ceoName is: " + refSeventeen.ceoName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfVehicles is: " + refSeventeen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refSeventeen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refSeventeen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refSeventeen.hasCargoService);
System.out.println("The hasPassengerService is: " + refSeventeen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refSeventeen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refSeventeen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refSeventeen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refSeventeen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refSeventeen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refSeventeen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The companyType is: " + refSeventeen.companyType);
System.out.println("The annualRevenue is: " + refSeventeen.annualRevenue);
System.out.println("The headquarters is: " + refSeventeen.headquarters);

refSeventeen.companyId = 17;
refSeventeen.companyName = "MegaTrans Logistics";
refSeventeen.ceoName = "Rohan Bansal";
refSeventeen.location = "Sector 18";
refSeventeen.city = "Noida";
refSeventeen.state = "Uttar Pradesh";
refSeventeen.country = "India";
refSeventeen.numberOfVehicles = 205;
refSeventeen.numberOfDrivers = 170;
refSeventeen.numberOfEmployees = 260;
refSeventeen.hasCargoService = true;
refSeventeen.hasPassengerService = false;
refSeventeen.hasOnlineBooking = true;
refSeventeen.hasMobileApp = true;
refSeventeen.hasTrackingSystem = true;
refSeventeen.hasWarehousing = true;
refSeventeen.hasMaintenanceFacility = true;
refSeventeen.hasInsuranceCoverage = true;
refSeventeen.contactNumber = "9887766554";
refSeventeen.email = "contact@megatrans.com";
refSeventeen.website = "www.megatranslogistics.com";
refSeventeen.establishedYear = 2018;
refSeventeen.companyType = "Logistics";
refSeventeen.annualRevenue = 47.35;
refSeventeen.headquarters = "Noida";

System.out.println("The companyId is: " + refSeventeen.companyId);
System.out.println("The companyName is: " + refSeventeen.companyName);
System.out.println("The ceoName is: " + refSeventeen.ceoName);
System.out.println("The location is: " + refSeventeen.location);
System.out.println("The city is: " + refSeventeen.city);
System.out.println("The state is: " + refSeventeen.state);
System.out.println("The country is: " + refSeventeen.country);
System.out.println("The numberOfVehicles is: " + refSeventeen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refSeventeen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refSeventeen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refSeventeen.hasCargoService);
System.out.println("The hasPassengerService is: " + refSeventeen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refSeventeen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refSeventeen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refSeventeen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refSeventeen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refSeventeen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refSeventeen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refSeventeen.contactNumber);
System.out.println("The email is: " + refSeventeen.email);
System.out.println("The website is: " + refSeventeen.website);
System.out.println("The establishedYear is: " + refSeventeen.establishedYear);
System.out.println("The companyType is: " + refSeventeen.companyType);
System.out.println("The annualRevenue is: " + refSeventeen.annualRevenue);
System.out.println("The headquarters is: " + refSeventeen.headquarters);
TransportCompany refEighteen = new TransportCompany();

System.out.println("The companyId is: " + refEighteen.companyId);
System.out.println("The companyName is: " + refEighteen.companyName);
System.out.println("The ceoName is: " + refEighteen.ceoName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfVehicles is: " + refEighteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refEighteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refEighteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refEighteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refEighteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refEighteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refEighteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refEighteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refEighteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refEighteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refEighteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The companyType is: " + refEighteen.companyType);
System.out.println("The annualRevenue is: " + refEighteen.annualRevenue);
System.out.println("The headquarters is: " + refEighteen.headquarters);

refEighteen.companyId = 18;
refEighteen.companyName = "RapidLink Transport";
refEighteen.ceoName = "Vivek Gupta";
refEighteen.location = "Civil Lines";
refEighteen.city = "Jaipur";
refEighteen.state = "Rajasthan";
refEighteen.country = "India";
refEighteen.numberOfVehicles = 150;
refEighteen.numberOfDrivers = 115;
refEighteen.numberOfEmployees = 185;
refEighteen.hasCargoService = true;
refEighteen.hasPassengerService = false;
refEighteen.hasOnlineBooking = true;
refEighteen.hasMobileApp = true;
refEighteen.hasTrackingSystem = true;
refEighteen.hasWarehousing = false;
refEighteen.hasMaintenanceFacility = true;
refEighteen.hasInsuranceCoverage = true;
refEighteen.contactNumber = "9776655443";
refEighteen.email = "support@rapidlink.com";
refEighteen.website = "www.rapidlinktransport.com";
refEighteen.establishedYear = 2017;
refEighteen.companyType = "Logistics";
refEighteen.annualRevenue = 28.90;
refEighteen.headquarters = "Jaipur";

System.out.println("The companyId is: " + refEighteen.companyId);
System.out.println("The companyName is: " + refEighteen.companyName);
System.out.println("The ceoName is: " + refEighteen.ceoName);
System.out.println("The location is: " + refEighteen.location);
System.out.println("The city is: " + refEighteen.city);
System.out.println("The state is: " + refEighteen.state);
System.out.println("The country is: " + refEighteen.country);
System.out.println("The numberOfVehicles is: " + refEighteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refEighteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refEighteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refEighteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refEighteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refEighteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refEighteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refEighteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refEighteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refEighteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refEighteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refEighteen.contactNumber);
System.out.println("The email is: " + refEighteen.email);
System.out.println("The website is: " + refEighteen.website);
System.out.println("The establishedYear is: " + refEighteen.establishedYear);
System.out.println("The companyType is: " + refEighteen.companyType);
System.out.println("The annualRevenue is: " + refEighteen.annualRevenue);
System.out.println("The headquarters is: " + refEighteen.headquarters);
TransportCompany refNineteen = new TransportCompany();

System.out.println("The companyId is: " + refNineteen.companyId);
System.out.println("The companyName is: " + refNineteen.companyName);
System.out.println("The ceoName is: " + refNineteen.ceoName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfVehicles is: " + refNineteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refNineteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refNineteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refNineteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refNineteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refNineteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refNineteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refNineteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refNineteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refNineteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refNineteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The companyType is: " + refNineteen.companyType);
System.out.println("The annualRevenue is: " + refNineteen.annualRevenue);
System.out.println("The headquarters is: " + refNineteen.headquarters);

refNineteen.companyId = 19;
refNineteen.companyName = "StarLine Cargo";
refNineteen.ceoName = "Manoj Agarwal";
refNineteen.location = "Park Street";
refNineteen.city = "Kolkata";
refNineteen.state = "West Bengal";
refNineteen.country = "India";
refNineteen.numberOfVehicles = 165;
refNineteen.numberOfDrivers = 130;
refNineteen.numberOfEmployees = 210;
refNineteen.hasCargoService = true;
refNineteen.hasPassengerService = false;
refNineteen.hasOnlineBooking = true;
refNineteen.hasMobileApp = true;
refNineteen.hasTrackingSystem = true;
refNineteen.hasWarehousing = true;
refNineteen.hasMaintenanceFacility = true;
refNineteen.hasInsuranceCoverage = true;
refNineteen.contactNumber = "9765432109";
refNineteen.email = "info@starlinecargo.com";
refNineteen.website = "www.starlinecargo.com";
refNineteen.establishedYear = 2012;
refNineteen.companyType = "Cargo Logistics";
refNineteen.annualRevenue = 36.75;
refNineteen.headquarters = "Kolkata";

System.out.println("The companyId is: " + refNineteen.companyId);
System.out.println("The companyName is: " + refNineteen.companyName);
System.out.println("The ceoName is: " + refNineteen.ceoName);
System.out.println("The location is: " + refNineteen.location);
System.out.println("The city is: " + refNineteen.city);
System.out.println("The state is: " + refNineteen.state);
System.out.println("The country is: " + refNineteen.country);
System.out.println("The numberOfVehicles is: " + refNineteen.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refNineteen.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refNineteen.numberOfEmployees);
System.out.println("The hasCargoService is: " + refNineteen.hasCargoService);
System.out.println("The hasPassengerService is: " + refNineteen.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refNineteen.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refNineteen.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refNineteen.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refNineteen.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refNineteen.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refNineteen.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refNineteen.contactNumber);
System.out.println("The email is: " + refNineteen.email);
System.out.println("The website is: " + refNineteen.website);
System.out.println("The establishedYear is: " + refNineteen.establishedYear);
System.out.println("The companyType is: " + refNineteen.companyType);
System.out.println("The annualRevenue is: " + refNineteen.annualRevenue);
System.out.println("The headquarters is: " + refNineteen.headquarters);
TransportCompany refTwenty = new TransportCompany();

System.out.println("The companyId is: " + refTwenty.companyId);
System.out.println("The companyName is: " + refTwenty.companyName);
System.out.println("The ceoName is: " + refTwenty.ceoName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfVehicles is: " + refTwenty.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refTwenty.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refTwenty.numberOfEmployees);
System.out.println("The hasCargoService is: " + refTwenty.hasCargoService);
System.out.println("The hasPassengerService is: " + refTwenty.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refTwenty.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refTwenty.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refTwenty.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refTwenty.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refTwenty.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refTwenty.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The companyType is: " + refTwenty.companyType);
System.out.println("The annualRevenue is: " + refTwenty.annualRevenue);
System.out.println("The headquarters is: " + refTwenty.headquarters);

refTwenty.companyId = 20;
refTwenty.companyName = "Continental Transport";
refTwenty.ceoName = "Sanjay Nair";
refTwenty.location = "MG Road";
refTwenty.city = "Bengaluru";
refTwenty.state = "Karnataka";
refTwenty.country = "India";
refTwenty.numberOfVehicles = 200;
refTwenty.numberOfDrivers = 160;
refTwenty.numberOfEmployees = 270;
refTwenty.hasCargoService = true;
refTwenty.hasPassengerService = true;
refTwenty.hasOnlineBooking = true;
refTwenty.hasMobileApp = true;
refTwenty.hasTrackingSystem = true;
refTwenty.hasWarehousing = true;
refTwenty.hasMaintenanceFacility = true;
refTwenty.hasInsuranceCoverage = true;
refTwenty.contactNumber = "9876543210";
refTwenty.email = "contact@continental.com";
refTwenty.website = "www.continentaltransport.com";
refTwenty.establishedYear = 2010;
refTwenty.companyType = "Passenger & Cargo";
refTwenty.annualRevenue = 50.00;
refTwenty.headquarters = "Bengaluru";

System.out.println("The companyId is: " + refTwenty.companyId);
System.out.println("The companyName is: " + refTwenty.companyName);
System.out.println("The ceoName is: " + refTwenty.ceoName);
System.out.println("The location is: " + refTwenty.location);
System.out.println("The city is: " + refTwenty.city);
System.out.println("The state is: " + refTwenty.state);
System.out.println("The country is: " + refTwenty.country);
System.out.println("The numberOfVehicles is: " + refTwenty.numberOfVehicles);
System.out.println("The numberOfDrivers is: " + refTwenty.numberOfDrivers);
System.out.println("The numberOfEmployees is: " + refTwenty.numberOfEmployees);
System.out.println("The hasCargoService is: " + refTwenty.hasCargoService);
System.out.println("The hasPassengerService is: " + refTwenty.hasPassengerService);
System.out.println("The hasOnlineBooking is: " + refTwenty.hasOnlineBooking);
System.out.println("The hasMobileApp is: " + refTwenty.hasMobileApp);
System.out.println("The hasTrackingSystem is: " + refTwenty.hasTrackingSystem);
System.out.println("The hasWarehousing is: " + refTwenty.hasWarehousing);
System.out.println("The hasMaintenanceFacility is: " + refTwenty.hasMaintenanceFacility);
System.out.println("The hasInsuranceCoverage is: " + refTwenty.hasInsuranceCoverage);
System.out.println("The contactNumber is: " + refTwenty.contactNumber);
System.out.println("The email is: " + refTwenty.email);
System.out.println("The website is: " + refTwenty.website);
System.out.println("The establishedYear is: " + refTwenty.establishedYear);
System.out.println("The companyType is: " + refTwenty.companyType);
System.out.println("The annualRevenue is: " + refTwenty.annualRevenue);
System.out.println("The headquarters is: " + refTwenty.headquarters);
}
}