class UserAccountExecutor {
    public static void main(String[] args) {

        UserAccount u1 = new UserAccount();
        u1.setUserId(1);
        u1.setUserName("User1");
        u1.setEmail("user1@gmail.com");
        u1.setPassword("pass1");
        u1.setPhone("9000000001");
        u1.setAccountType("Free");
        u1.setCreatedDate("2024");
        System.out.println(u1.getUserId());
        System.out.println(u1.getUserName());
        System.out.println(u1.getEmail());
        System.out.println(u1.getPassword());
        System.out.println(u1.getPhone());
        System.out.println(u1.getAccountType());
        System.out.println(u1.getCreatedDate());

        UserAccount u2 = new UserAccount();
        u2.setUserId(2);
        u2.setUserName("User2");
        u2.setEmail("user2@gmail.com");
        u2.setPassword("pass2");
        u2.setPhone("9000000002");
        u2.setAccountType("Premium");
        u2.setCreatedDate("2024");
        System.out.println(u2.getUserId());
        System.out.println(u2.getUserName());
        System.out.println(u2.getEmail());
        System.out.println(u2.getPassword());
        System.out.println(u2.getPhone());
        System.out.println(u2.getAccountType());
        System.out.println(u2.getCreatedDate());

        UserAccount u3 = new UserAccount();
        u3.setUserId(3);
        u3.setUserName("User3");
        u3.setEmail("user3@gmail.com");
        u3.setPassword("pass3");
        u3.setPhone("9000000003");
        u3.setAccountType("Free");
        u3.setCreatedDate("2024");
        System.out.println(u3.getUserId());
        System.out.println(u3.getUserName());
        System.out.println(u3.getEmail());
        System.out.println(u3.getPassword());
        System.out.println(u3.getPhone());
        System.out.println(u3.getAccountType());
        System.out.println(u3.getCreatedDate());

        UserAccount u4 = new UserAccount();
        u4.setUserId(4);
        u4.setUserName("User4");
        u4.setEmail("user4@gmail.com");
        u4.setPassword("pass4");
        u4.setPhone("9000000004");
        u4.setAccountType("Premium");
        u4.setCreatedDate("2024");
        System.out.println(u4.getUserId());
        System.out.println(u4.getUserName());
        System.out.println(u4.getEmail());
        System.out.println(u4.getPassword());
        System.out.println(u4.getPhone());
        System.out.println(u4.getAccountType());
        System.out.println(u4.getCreatedDate());

        UserAccount u5 = new UserAccount();
        u5.setUserId(5);
        u5.setUserName("User5");
        u5.setEmail("user5@gmail.com");
        u5.setPassword("pass5");
        u5.setPhone("9000000005");
        u5.setAccountType("Free");
        u5.setCreatedDate("2024");
        System.out.println(u5.getUserId());
        System.out.println(u5.getUserName());
        System.out.println(u5.getEmail());
        System.out.println(u5.getPassword());
        System.out.println(u5.getPhone());
        System.out.println(u5.getAccountType());
        System.out.println(u5.getCreatedDate());

        UserAccount u6 = new UserAccount();
        u6.setUserId(6);
        u6.setUserName("User6");
        u6.setEmail("user6@gmail.com");
        u6.setPassword("pass6");
        u6.setPhone("9000000006");
        u6.setAccountType("Premium");
        u6.setCreatedDate("2024");
        System.out.println(u6.getUserId());
        System.out.println(u6.getUserName());
        System.out.println(u6.getEmail());
        System.out.println(u6.getPassword());
        System.out.println(u6.getPhone());
        System.out.println(u6.getAccountType());
        System.out.println(u6.getCreatedDate());

        UserAccount u7 = new UserAccount();
        u7.setUserId(7);
        u7.setUserName("User7");
        u7.setEmail("user7@gmail.com");
        u7.setPassword("pass7");
        u7.setPhone("9000000007");
        u7.setAccountType("Free");
        u7.setCreatedDate("2024");
        System.out.println(u7.getUserId());
        System.out.println(u7.getUserName());
        System.out.println(u7.getEmail());
        System.out.println(u7.getPassword());
        System.out.println(u7.getPhone());
        System.out.println(u7.getAccountType());
        System.out.println(u7.getCreatedDate());

        UserAccount u8 = new UserAccount();
        u8.setUserId(8);
        u8.setUserName("User8");
        u8.setEmail("user8@gmail.com");
        u8.setPassword("pass8");
        u8.setPhone("9000000008");
        u8.setAccountType("Premium");
        u8.setCreatedDate("2024");
        System.out.println(u8.getUserId());
        System.out.println(u8.getUserName());
        System.out.println(u8.getEmail());
        System.out.println(u8.getPassword());
        System.out.println(u8.getPhone());
        System.out.println(u8.getAccountType());
        System.out.println(u8.getCreatedDate());

        UserAccount u9 = new UserAccount();
        u9.setUserId(9);
        u9.setUserName("User9");
        u9.setEmail("user9@gmail.com");
        u9.setPassword("pass9");
        u9.setPhone("9000000009");
        u9.setAccountType("Free");
        u9.setCreatedDate("2024");
        System.out.println(u9.getUserId());
        System.out.println(u9.getUserName());
        System.out.println(u9.getEmail());
        System.out.println(u9.getPassword());
        System.out.println(u9.getPhone());
        System.out.println(u9.getAccountType());
        System.out.println(u9.getCreatedDate());

        UserAccount u10 = new UserAccount();
        u10.setUserId(10);
        u10.setUserName("User10");
        u10.setEmail("user10@gmail.com");
        u10.setPassword("pass10");
        u10.setPhone("9000000010");
        u10.setAccountType("Premium");
        u10.setCreatedDate("2024");
        System.out.println(u10.getUserId());
        System.out.println(u10.getUserName());
        System.out.println(u10.getEmail());
        System.out.println(u10.getPassword());
        System.out.println(u10.getPhone());
        System.out.println(u10.getAccountType());
        System.out.println(u10.getCreatedDate());

        UserAccount u11 = new UserAccount();
        u11.setUserId(11);
        u11.setUserName("User11");
        u11.setEmail("user11@gmail.com");
        u11.setPassword("pass11");
        u11.setPhone("9000000011");
        u11.setAccountType("Free");
        u11.setCreatedDate("2024");
        System.out.println(u11.getUserId());
        System.out.println(u11.getUserName());
        System.out.println(u11.getEmail());
        System.out.println(u11.getPassword());
        System.out.println(u11.getPhone());
        System.out.println(u11.getAccountType());
        System.out.println(u11.getCreatedDate());

        UserAccount u12 = new UserAccount();
        u12.setUserId(12);
        u12.setUserName("User12");
        u12.setEmail("user12@gmail.com");
        u12.setPassword("pass12");
        u12.setPhone("9000000012");
        u12.setAccountType("Premium");
        u12.setCreatedDate("2024");
        System.out.println(u12.getUserId());
        System.out.println(u12.getUserName());
        System.out.println(u12.getEmail());
        System.out.println(u12.getPassword());
        System.out.println(u12.getPhone());
        System.out.println(u12.getAccountType());
        System.out.println(u12.getCreatedDate());

        UserAccount u13 = new UserAccount();
        u13.setUserId(13);
        u13.setUserName("User13");
        u13.setEmail("user13@gmail.com");
        u13.setPassword("pass13");
        u13.setPhone("9000000013");
        u13.setAccountType("Free");
        u13.setCreatedDate("2024");
        System.out.println(u13.getUserId());
        System.out.println(u13.getUserName());
        System.out.println(u13.getEmail());
        System.out.println(u13.getPassword());
        System.out.println(u13.getPhone());
        System.out.println(u13.getAccountType());
        System.out.println(u13.getCreatedDate());

        UserAccount u14 = new UserAccount();
        u14.setUserId(14);
        u14.setUserName("User14");
        u14.setEmail("user14@gmail.com");
        u14.setPassword("pass14");
        u14.setPhone("9000000014");
        u14.setAccountType("Premium");
        u14.setCreatedDate("2024");
        System.out.println(u14.getUserId());
        System.out.println(u14.getUserName());
        System.out.println(u14.getEmail());
        System.out.println(u14.getPassword());
        System.out.println(u14.getPhone());
        System.out.println(u14.getAccountType());
        System.out.println(u14.getCreatedDate());

        UserAccount u15 = new UserAccount();
        u15.setUserId(15);
        u15.setUserName("User15");
        u15.setEmail("user15@gmail.com");
        u15.setPassword("pass15");
        u15.setPhone("9000000015");
        u15.setAccountType("Free");
        u15.setCreatedDate("2024");
        System.out.println(u15.getUserId());
        System.out.println(u15.getUserName());
        System.out.println(u15.getEmail());
        System.out.println(u15.getPassword());
        System.out.println(u15.getPhone());
        System.out.println(u15.getAccountType());
        System.out.println(u15.getCreatedDate());

        UserAccount u16 = new UserAccount();
        u16.setUserId(16);
        u16.setUserName("User16");
        u16.setEmail("user16@gmail.com");
        u16.setPassword("pass16");
        u16.setPhone("9000000016");
        u16.setAccountType("Premium");
        u16.setCreatedDate("2024");
        System.out.println(u16.getUserId());
        System.out.println(u16.getUserName());
        System.out.println(u16.getEmail());
        System.out.println(u16.getPassword());
        System.out.println(u16.getPhone());
        System.out.println(u16.getAccountType());
        System.out.println(u16.getCreatedDate());

        UserAccount u17 = new UserAccount();
        u17.setUserId(17);
        u17.setUserName("User17");
        u17.setEmail("user17@gmail.com");
        u17.setPassword("pass17");
        u17.setPhone("9000000017");
        u17.setAccountType("Free");
        u17.setCreatedDate("2024");
        System.out.println(u17.getUserId());
        System.out.println(u17.getUserName());
        System.out.println(u17.getEmail());
        System.out.println(u17.getPassword());
        System.out.println(u17.getPhone());
        System.out.println(u17.getAccountType());
        System.out.println(u17.getCreatedDate());

        UserAccount u18 = new UserAccount();
        u18.setUserId(18);
        u18.setUserName("User18");
        u18.setEmail("user18@gmail.com");
        u18.setPassword("pass18");
        u18.setPhone("9000000018");
        u18.setAccountType("Premium");
        u18.setCreatedDate("2024");
        System.out.println(u18.getUserId());
        System.out.println(u18.getUserName());
        System.out.println(u18.getEmail());
        System.out.println(u18.getPassword());
        System.out.println(u18.getPhone());
        System.out.println(u18.getAccountType());
        System.out.println(u18.getCreatedDate());

        UserAccount u19 = new UserAccount();
        u19.setUserId(19);
        u19.setUserName("User19");
        u19.setEmail("user19@gmail.com");
        u19.setPassword("pass19");
        u19.setPhone("9000000019");
        u19.setAccountType("Free");
        u19.setCreatedDate("2024");
        System.out.println(u19.getUserId());
        System.out.println(u19.getUserName());
        System.out.println(u19.getEmail());
        System.out.println(u19.getPassword());
        System.out.println(u19.getPhone());
        System.out.println(u19.getAccountType());
        System.out.println(u19.getCreatedDate());

        UserAccount u20 = new UserAccount();
        u20.setUserId(20);
        u20.setUserName("User20");
        u20.setEmail("user20@gmail.com");
        u20.setPassword("pass20");
        u20.setPhone("9000000020");
        u20.setAccountType("Premium");
        u20.setCreatedDate("2024");
        System.out.println(u20.getUserId());
        System.out.println(u20.getUserName());
        System.out.println(u20.getEmail());
        System.out.println(u20.getPassword());
        System.out.println(u20.getPhone());
        System.out.println(u20.getAccountType());
        System.out.println(u20.getCreatedDate());

        UserAccount u21 = new UserAccount();
        u21.setUserId(21);
        u21.setUserName("User21");
        u21.setEmail("user21@gmail.com");
        u21.setPassword("pass21");
        u21.setPhone("9000000021");
        u21.setAccountType("Free");
        u21.setCreatedDate("2024");
        System.out.println(u21.getUserId());
        System.out.println(u21.getUserName());
        System.out.println(u21.getEmail());
        System.out.println(u21.getPassword());
        System.out.println(u21.getPhone());
        System.out.println(u21.getAccountType());
        System.out.println(u21.getCreatedDate());

        UserAccount u22 = new UserAccount();
        u22.setUserId(22);
        u22.setUserName("User22");
        u22.setEmail("user22@gmail.com");
        u22.setPassword("pass22");
        u22.setPhone("9000000022");
        u22.setAccountType("Premium");
        u22.setCreatedDate("2024");
        System.out.println(u22.getUserId());
        System.out.println(u22.getUserName());
        System.out.println(u22.getEmail());
        System.out.println(u22.getPassword());
        System.out.println(u22.getPhone());
        System.out.println(u22.getAccountType());
        System.out.println(u22.getCreatedDate());

        UserAccount u23 = new UserAccount();
        u23.setUserId(23);
        u23.setUserName("User23");
        u23.setEmail("user23@gmail.com");
        u23.setPassword("pass23");
        u23.setPhone("9000000023");
        u23.setAccountType("Free");
        u23.setCreatedDate("2024");
        System.out.println(u23.getUserId());
        System.out.println(u23.getUserName());
        System.out.println(u23.getEmail());
        System.out.println(u23.getPassword());
        System.out.println(u23.getPhone());
        System.out.println(u23.getAccountType());
        System.out.println(u23.getCreatedDate());

        UserAccount u24 = new UserAccount();
        u24.setUserId(24);
        u24.setUserName("User24");
        u24.setEmail("user24@gmail.com");
        u24.setPassword("pass24");
        u24.setPhone("9000000024");
        u24.setAccountType("Premium");
        u24.setCreatedDate("2024");
        System.out.println(u24.getUserId());
        System.out.println(u24.getUserName());
        System.out.println(u24.getEmail());
        System.out.println(u24.getPassword());
        System.out.println(u24.getPhone());
        System.out.println(u24.getAccountType());
        System.out.println(u24.getCreatedDate());

        UserAccount u25 = new UserAccount();
        u25.setUserId(25);
        u25.setUserName("User25");
        u25.setEmail("user25@gmail.com");
        u25.setPassword("pass25");
        u25.setPhone("9000000025");
        u25.setAccountType("Free");
        u25.setCreatedDate("2024");
        System.out.println(u25.getUserId());
        System.out.println(u25.getUserName());
        System.out.println(u25.getEmail());
        System.out.println(u25.getPassword());
        System.out.println(u25.getPhone());
        System.out.println(u25.getAccountType());
        System.out.println(u25.getCreatedDate());

        UserAccount u26 = new UserAccount();
        u26.setUserId(26);
        u26.setUserName("User26");
        u26.setEmail("user26@gmail.com");
        u26.setPassword("pass26");
        u26.setPhone("9000000026");
        u26.setAccountType("Premium");
        u26.setCreatedDate("2024");
        System.out.println(u26.getUserId());
        System.out.println(u26.getUserName());
        System.out.println(u26.getEmail());
        System.out.println(u26.getPassword());
        System.out.println(u26.getPhone());
        System.out.println(u26.getAccountType());
        System.out.println(u26.getCreatedDate());

        UserAccount u27 = new UserAccount();
        u27.setUserId(27);
        u27.setUserName("User27");
        u27.setEmail("user27@gmail.com");
        u27.setPassword("pass27");
        u27.setPhone("9000000027");
        u27.setAccountType("Free");
        u27.setCreatedDate("2024");
        System.out.println(u27.getUserId());
        System.out.println(u27.getUserName());
        System.out.println(u27.getEmail());
        System.out.println(u27.getPassword());
        System.out.println(u27.getPhone());
        System.out.println(u27.getAccountType());
        System.out.println(u27.getCreatedDate());

        UserAccount u28 = new UserAccount();
        u28.setUserId(28);
        u28.setUserName("User28");
        u28.setEmail("user28@gmail.com");
        u28.setPassword("pass28");
        u28.setPhone("9000000028");
        u28.setAccountType("Premium");
        u28.setCreatedDate("2024");
        System.out.println(u28.getUserId());
        System.out.println(u28.getUserName());
        System.out.println(u28.getEmail());
        System.out.println(u28.getPassword());
        System.out.println(u28.getPhone());
        System.out.println(u28.getAccountType());
        System.out.println(u28.getCreatedDate());

        UserAccount u29 = new UserAccount();
        u29.setUserId(29);
        u29.setUserName("User29");
        u29.setEmail("user29@gmail.com");
        u29.setPassword("pass29");
        u29.setPhone("9000000029");
        u29.setAccountType("Free");
        u29.setCreatedDate("2024");
        System.out.println(u29.getUserId());
        System.out.println(u29.getUserName());
        System.out.println(u29.getEmail());
        System.out.println(u29.getPassword());
        System.out.println(u29.getPhone());
        System.out.println(u29.getAccountType());
        System.out.println(u29.getCreatedDate());

    }
}